<?php
/* General stuff */
$LANGS['language'] = 'Español (México)';
$LANGS['languageenglish'] = 'Spanish (Mexico)';
$LANGS['languagecode'] = 'es_MX.UTF-8';
$LANGS['languagechange'] = 'El idioma del sitio ha sido cambiado a Español (Latinoamérica).';
$LANGS['numberformat'] = 0; /* If your language uses comma separators (example: 1,000,000), value will be 1. If it uses dots (example: 1.000.000) or doesn't use separators, value will be 0.*/

/* Language window */
$LANGS['welcometobitview'] = '¡Bienvenido a BitView!';
$LANGS['languagesuggestion'] = 'Idioma recomendado establecimos tu preferencia de idioma a): ';
$LANGS['languagesuggestiondesc1'] = 'Para cambiar tu preferencia de idioma, utiliza el menú de selección de idioma situado en la parte inferior de la página.';
$LANGS['languagesuggestiondesc2'] = 'Haz clic "en Aceptar" para aceptar esta configuración, o haz clic en "Cancelar" para ver el sitio en inglés.';

/* Time, dates, etc */
$LANGS['second'] = 'segundo';
$LANGS['minute'] = 'minuto';
$LANGS['hour'] = 'hora';
$LANGS['day'] = 'día';
$LANGS['week'] = 'semana';
$LANGS['month'] = 'mes';
$LANGS['year'] = 'año';
$LANGS['seconds'] = 'segundos';
$LANGS['minutes'] = 'minutos';
$LANGS['hours'] = 'horas';
$LANGS['days'] = 'días';
$LANGS['weeks'] = 'semanas';
$LANGS['months'] = 'meses';
$LANGS['years'] = 'años';
$LANGS['ago1'] = 'hace '; /* Explanation: Text before "x seconds/minutes/hours..." Example: "hace (1 día)" in Spanish. If your language doesn't use this, leave it empty like this: ''*/
$LANGS['ago2'] = ''; /* Explanation: ago2 -> Text after "x seconds/minutes/hours..." Example: "(1 day) ago" in English, "(1 anno) fa" in Italian. If your language doesn't use this, leave it empty like this: ''*/
$LANGS['january'] = 'Enero';
$LANGS['february'] = 'Febrero';
$LANGS['march'] = 'Marzo';
$LANGS['april'] = 'Abril';
$LANGS['may'] = 'Mayo';
$LANGS['june'] = 'Junio';
$LANGS['july'] = 'Julio';
$LANGS['august'] = 'Agosto';
$LANGS['september'] = 'Septiembre';
$LANGS['october'] = 'Octubre';
$LANGS['november'] = 'Noviembre';
$LANGS['december'] = 'Diciembre';
$LANGS['shorttimeformat'] = '%e %b %Y';
$LANGS['videotimeformat'] = '%e de %B de %Y';
$LANGS['longtimeformat'] = '%e de %B de %Y';
$LANGS['timehourformat'] = '%e de %B de %Y, %k:%M:%S';
$LANGS['myvideostimeformat'] = '%a %e %b %Y, %k:%M:%S';
$LANGS['blogpostformat'] = '%A, %e de %B de %Y';
$LANGS['timenumberformat'] = 'd/m/Y';

/* Header */
$LANGS['home'] = 'Página principal';
$LANGS['videos'] = 'Videos';
$LANGS['channels'] = 'Canales';
$LANGS['community'] = 'Comunidad';
$LANGS['search'] = 'Buscar';
$LANGS['login'] = 'Iniciar sesión';
$LANGS['or'] = 'o';
$LANGS['signup'] = 'Crear cuenta';
$LANGS['logout'] = 'Cerrar sesión';
$LANGS['upload'] = 'Subir';
$LANGS['subscriptions'] = 'Suscripciones';
$LANGS['history'] = 'Historia';
$LANGS['account'] = 'Cuenta';
$LANGS['myvideos'] = 'Mis videos';
$LANGS['favorites'] = 'Favoritos';
$LANGS['playlists'] = 'Listas de reproducción';
$LANGS['help'] = 'Ayuda';

/* Homepage */
$LANGS['viewall'] = 'ver todos';
$LANGS['videoviews'] = 'de reproducciones';
$LANGS['beingwatched'] = 'Videos que se están viendo ahora';
$LANGS['featured'] = 'Videos destacados';
$LANGS['recommendedforyou'] = 'Recomendado para ti';
$LANGS['mostpopular'] = 'Más populares';
$LANGS['inboxstats'] = 'Bandeja de entrada';
$LANGS['profilesettings'] = 'ajustes de cuenta';
$LANGS['messages'] = 'mensajes';
$LANGS['message'] = 'mensaje';
$LANGS['comments'] = 'comentarios';
$LANGS['comment'] = 'comentario';
$LANGS['friendinvites'] = 'peticiones de amistad';
$LANGS['friendinvite'] = 'petición de amistad';
$LANGS['subscribers'] = 'suscriptores';
$LANGS['subscriber'] = 'suscriptor';
$LANGS['totalviews'] = 'reproducciones totales';
$LANGS['sendmessage'] = 'enviar mensaje';
$LANGS['whatsnew'] = 'Novedades';
$LANGS['readmore'] = 'Más información en nuestro blog';
$LANGS['videocontest'] = '- Concurso de videos';
$LANGS['joincontest'] = '¡Participa ya!';
$LANGS['personalize'] = '¿Quieres personalizar esta página principal?';
$LANGS['signinnow'] = '¡<a href="/login">Inicia sesión</a> o <a href="/signup">regístrate</a> ahora mismo!';
$LANGS['nowconverting'] = "El video se está procesando, espera unos minutos.";
$LANGS['modules'] = "Agregar / Eliminar módulos";
$LANGS['friendactivity'] = "Actividad de amigos";
$LANGS['customizehomepage'] = "Personalizar página principal";
$LANGS['customizethehomepage'] = "Personalizar la página principal";
$LANGS['customizehomepagedesc'] = "Selecciona los módulos que quieres que aparezcan en tu página principal.";
$LANGS['displaypreferences'] = "Preferencias de visualización";
$LANGS['thefeed'] = "El feed";
$LANGS['thefeeddesc'] = "combina todos tus módulos en un único feed.";
$LANGS['friendactivitytitle'] = "Actividad de amigos: ¿pueden ver otros usuarios lo que hago?";
$LANGS['friendactivitydesc'] = "Esta sección muestra a tus amigos confirmados las acciones que muestras de forma pública en tu historial de actividad. Por ejemplo, si añades un video como favorito, tu nuevo video favorito se mostrará en la caja de Actividad reciente de tu canal y en las páginas princiaples de tus amigos.";
$LANGS['feedfeatured'] = "Video destacado";
$LANGS['feedbeingwatched'] = "Video que se está viendo ahora";
$LANGS['feedrecommended'] = "Video recomendado";
$LANGS['nosubscriptions'] = "Aún no te has suscrito a ningún canal.";
$LANGS['nosubscriptionsdesc'] = "Cuando te suscribas a algún canal, los nuevos videos subidos aparecerán en esta página.";
$LANGS['nofriendactivity'] = "Aún no has añadido amigos.";
$LANGS['nofriendactivitydesc'] = "Una vez hayas añadido amigos, esta página te mostrará sus puntuaciones de videos, favoritos, boletines y videos subidos más recientes.";
$LANGS['homeediting'] = "Edición";
$LANGS['homedisplay'] = "Mostrar como";
$LANGS['homerows'] = "Número de filas que mostrar";
$LANGS['gridview'] = "Vista de cuadrícula";
$LANGS['listview'] = "Vista de lista";

/* Page title */
$LANGS['homepretitle'] = "BitView de "; /* Explanation: Use if "BitView" goes before the username. Example: "BitView de username" in Spanish. If your language doesn't use this, leave it empty like this: ''*/
$LANGS['homeposttitle'] = ""; /* Explanation: Use if "BitView" goes after the username. Example: "username's BitView" in English. If your language doesn't use this, leave it empty like this: '' */
$LANGS['chpretitle'] = "Canal de "; /* Explanation: Use if "channel" goes before the username. Example: "Canal de username" in Spanish. If your language doesn't use this, leave it empty like this: ''*/
$LANGS['chposttitle'] = ""; /* Explanation: Use if "channel" goes after the username. Example: "username's Channel" in English. If your language doesn't use this, leave it empty like this: '' */
$LANGS['signintitle'] = "Iniciar sesión";
$LANGS['historytitle'] = "Historial";
$LANGS['favtitle'] = "Favoritos";
$LANGS['pltitle'] = "Listas de reproducción";
$LANGS['partnerprogram'] = "Programa para partners";

/* Notifications */
$LANGS['searcherror'] = 'Tu búsqueda debe de contener al menos 2 caracteres.';
$LANGS['addvideoplaylist1'] = 'Has añadido';
$LANGS['addvideoplaylist2'] = 'videos a tu lista de reproducción.';
$LANGS['addfavorite1'] = 'Has añadido';
$LANGS['addfavorite2'] = 'videos a tus favoritos.';
$LANGS['groupdoesnotexist'] = 'Este grupo no existe.';
$LANGS['uploaddisabled'] = 'Se ha deshabilitado la subida de videos para mantenimeinto.';
$LANGS['10vidsday'] = 'Has llegado al límite de videos diarios (10 videos). Prueba a subir videos mañana.';
$LANGS['3mins'] = 'Espera 3 minutos para subir un video.';
$LANGS['backgroundsuccess'] = 'Se ha establecido la imagen de fondo.';
$LANGS['backgrounderror'] = 'La imagen de fondo debe de pesar menos de 2 MB y ser un archivo de imagen.';
$LANGS['backgrounddeleted'] = 'Se ha eliminado la imagen de fondo.';
$LANGS['bannersuccess'] = 'Se ha establecido la cabecera del canal.';
$LANGS['bannererror'] = 'La cabecera del canal debe de pesar menos de 2 MB y ser un archivo de imagen.';
$LANGS['bannerdeleted'] = 'Se ha eliminado la cabecera del canal.';
$LANGS['minibannersuccess'] = 'Se ha establecido la mini-cabecera del canal.';
$LANGS['minibannererror'] = 'La mini-cabecera del canal debe de pesar menos de 2 MB y ser un archivo de imagen.';
$LANGS['minibannerdeleted'] = 'Se ha eliminado la mini-cabecera del canal.';
$LANGS['sideimagesuccess'] = 'Se ha establecido la imagen lateral.';
$LANGS['sideimageerror'] = 'La imagen lateral debe de pesar menos de 2 MB y ser un archivo de imagen.';
$LANGS['sideimagedeleted'] = 'Se ha eliminado la imagen lateral.';
$LANGS['avatarsuccess'] = 'Se ha establecido la imagen de perfil.';
$LANGS['avatarerror'] = 'La imagen de perfil debe de pesar menos de 1 MB y ser un archivo de imagen.';
$LANGS['avatardeleted'] = 'Se ha eliminado la imagen de perfil.';
$LANGS['changessaved'] = 'Se han guardado los cambios.';
$LANGS['profilesdisabled'] = 'Se han deshabilitado los canales para mantenimeinto.';
$LANGS['bulletinposted'] = 'Se ha publicado el boletín.';
$LANGS['channelcommentsent'] = 'Se ha enviado el comentario.';
$LANGS['somethingwentwrong'] = 'Ha habido un problema.';
$LANGS['replysubmitted'] = 'Se ha enviado el comentario.';
$LANGS['onlyonecomment'] = 'Solo puedes agregar un comentario.';
$LANGS['vpnbrowser'] = 'No puedes usar una VPN para crear una cuenta de BitView.';
$LANGS['torbrowser'] = 'No puedes usar TOR para crear una cuenta de BitView.';
$LANGS['captchaincorrect'] = 'El código de verificación es incorrecto.';
$LANGS['toomanyaccounts'] = 'Has alcanzado el máximo de cuentas por usuario.';
$LANGS['banned2times'] = 'Has sido suspendido 2 veces. ¡Ya no puedes crear más cuentas!';
$LANGS['nohistory'] = 'No has visto ningún video durante esta sesión.';
$LANGS['historycleared'] = 'Se ha borrado tu historial de reproducciones.';
$LANGS['watchdisabled'] = 'Se ha deshabilitado la reproducción de videos para mantenimeinto.';
$LANGS['videonotexist'] = 'Este video no existe o ha sido eliminado por infringir las Términos de uso.';
$LANGS['responseerror'] = 'Ha habido un problema y no se ha podido agregar la respuesta en video. Comprueba que el enlace es correcto.';
$LANGS['responseexist'] = 'Ya se ha añadido este video a las respuestas.';
$LANGS['responseadded'] = 'Se ha añadido este video a las respuestas.';
$LANGS['responseaccepted'] = 'Se ha aceptado esta respuesta en video.';
$LANGS['60secscomment'] = 'Espera 60 segundos para publicar otro comentario.';
$LANGS['plnotexist'] = 'Esta lista de reproducción no existe.';
$LANGS['positionnotexist'] = 'Esta posición no existe.';
$LANGS['positionchanged'] = 'Se ha cambiado la posición de el video.';
$LANGS['invalidurl'] = 'El enlace no es válido.';
$LANGS['videopladded'] = 'Se ha añadido el video a la lista de reproducción.';
$LANGS['videoalreadyinpl'] = 'Este video ya está en la lista de reproducción.';
$LANGS['plvideoremoved'] = 'Se ha eliminado el video de la lista de reproducción.';
$LANGS['plinfochanged'] = 'Se ha cambiado la información de la lista de reproducción.';
$LANGS['pltitleneeded'] = 'Tu lista de reproducción debe tener un título.';
$LANGS['flashenabled'] = 'Se ha activado el reproductor con Adobe Flash.';
$LANGS['flashdisabled'] = 'Se ha desactivado el reproductor con Adobe Flash.';
$LANGS['messagesent'] = 'Se ha enviado el mensaje.';
$LANGS['usernotexist'] = 'Este usuario no existe.';
$LANGS['nocriteria'] = 'No cumples los requisitos para unirte al programa para partners de BitView.';
$LANGS['alreadypartner'] = 'Ya perteneces al programa para partners de BitView.';
$LANGS['alreadyapplied'] = 'Tu solicitud ya ha sido presentada.';
$LANGS['applicationsent'] = 'Se ha presentado tu solicitud para unirte al programa de partners de BitView.';
$LANGS['joinedgroup'] = 'Te has unido al grupo.';
$LANGS['leftgroup'] = 'Te has salido del grupo.';
$LANGS['grouprequest'] = 'Has enviado una solicitud para unirte al grupo.';
$LANGS['groupdeleted'] = 'Se ha eliminado el grupo.';
$LANGS['groupvideoadded'] = 'Se ha añadido el video.';
$LANGS['groupvideoalreadyadded'] = 'Ya has añadido este video.';
$LANGS['groupvideonotowned'] = 'No eres el propietario del video.';
$LANGS['3groups'] = 'Solo puedes crear 3 grupos.';
$LANGS['groupnameempty'] = 'Tu grupo debe tener un nombre.';
$LANGS['groupdescempty'] = 'Tu grupo debe tener una descripción.';
$LANGS['groupnoimage'] = 'Tu grupo debe tener una imagen.';
$LANGS['groupimageerror'] = 'La imagen del grupo debe de pesar menos de 1 MB y ser un archivo de imagen.';
$LANGS['groupcreated'] = 'Se ha creado el grupo.';
$LANGS['urlnotvalid'] = 'Este enlace no es válido.';
$LANGS['discussiondeleted'] = 'Se ha eliminado el debate.';
$LANGS['videodeleted'] = 'Se ha eliminado el video.';
$LANGS['pldeleted'] = 'Se ha eliminado la lista de reproducción.';
$LANGS['invitesent'] = 'Se ha enviado la solicitud de amistad.';
$LANGS['descriptionchanged'] = 'Se ha cambiado la descripción.';
$LANGS['emptymessage'] = 'No se puede enviar un mensaje vacío.';
$LANGS['styleupdated'] = 'Se ha actualizado el estilo del grupo.';
$LANGS['imageupdated'] = 'Se ha actualizado la imagen del grupo.';
$LANGS['plcreated'] = 'Se ha creado la lista de reproducción.';
$LANGS['discussiontitle2chars'] = 'El título del debate tiene que contener al menos 2 caracteres.';
$LANGS['discussiondesc10chars'] = 'La descripción del debate tiene que contener al menos 10 caracteres.';
$LANGS['5discussionsday'] = 'Solo puedes crear 5 debates al día.';
$LANGS['discussionsuccess'] = 'Se ha creado el debate.';
$LANGS['memberaccepted1'] = 'Has aceptado la solicitud de ';
$LANGS['memberaccepted2'] = '.';
$LANGS['memberdeclined1'] = 'Has rechazado la solicitud de ';
$LANGS['memberdeclined2'] = '.';
$LANGS['videoaccepted'] = 'Se ha aceptado el video.';
$LANGS['bulletindeleted'] = 'Se ha eliminado el boletín.';
$LANGS['messagedeleted'] = 'Se ha eliminado el mensaje.';
$LANGS['responsedeleted'] = 'Se ha eliminado la respuesta en video.';
$LANGS['flagmod'] = 'No puedes marcar a un moderador.';
$LANGS['userflagged'] = 'Se ha enviado la notificación.';
$LANGS['discussionreplysubmitted'] = 'Se ha enviado el comentario.';
$LANGS['discussionreplyempty'] = 'No se puede enviar una respuesta vacía.';

/* Watch */
$LANGS['moreinfo'] = 'más información';
$LANGS['lessinfo'] = 'Menos información';
$LANGS['category'] = 'Categoría';
$LANGS['recordedon'] = 'Fecha de grabación';
$LANGS['location'] = 'Ubicación';
$LANGS['tags'] = 'Etiquetas';
$LANGS['embed'] = 'Insertar';
$LANGS['partnervideo'] = 'Video de partner';
$LANGS['subscribe'] = 'Suscribirse';
$LANGS['unsubscribe'] = 'Anular suscripción';
$LANGS['nodesc'] = 'No hay descripción...';
$LANGS['logintosub'] = 'Debes iniciar sesión para suscribirte a un canal.';
$LANGS['logintosubbox'] = '¿Quieres suscribirte?';
$LANGS['subyourself'] = 'No puedes suscribirte a tu propia cuenta.';
$LANGS['videoowner'] = 'Opciones del propietario del video';
$LANGS['editvideo'] = 'Editar video';
$LANGS['insight'] = 'Insight';
$LANGS['morefrom'] = 'Más de:';
$LANGS['relatedvideos'] = 'Videos relacionados';
$LANGS['novideosfound'] = 'No se han encontrado videos...';
$LANGS['morevideos'] = 'Ver todos los videos';
$LANGS['changeplayersize'] = 'Cambia el tamaño del reproductor';
$LANGS['newwindow'] = 'Ve este video en una nueva ventana';
$LANGS['featuredtext'] = 'Este video ha sido destacado. ¿Quieres ver más? <a href="/browse?t=2">Haz clic aquí</a>.';
$LANGS['ratings'] = 'calificaciones';
$LANGS['rating'] = 'calificación';
$LANGS['favorite'] = 'Favoritos';
$LANGS['addtofav'] = 'Agregar a favoritos';
$LANGS['removefav'] = 'Eliminar de favoritos';
$LANGS['favadded'] = 'Este video se ha <strong>añadido</strong> a tus <a href="/my_favorites">favoritos</a>.';
$LANGS['favremoved'] = 'Este video se ha <strong>eliminado</strong> de tus <a href="/my_favorites">favoritos</a>.';
$LANGS['undo'] = 'Deshacer';
$LANGS['thanksforrating'] = '¡Gracias por calificar!';
$LANGS['playlistdesc'] = 'Para agregar un video a tu lista de reproducción, entra en <a href="/my_playlists">"Listas de reproducción"</a>.';
$LANGS['addtoplaylist'] = 'Añadir a lista de reproducción';
$LANGS['addtoplaylistsuccess'] = 'El video se ha añadido a tu lista de reproducción.';
$LANGS['share'] = 'Compartir';
$LANGS['flag'] = 'Marcar';
$LANGS['flagthisvid'] = 'Marcar este video';
$LANGS['removeflag'] = 'Desmarcar este video';
$LANGS['flagnote'] = "Antes de denunciar un video, asegúrate de que incumpla alguna norma. No denuncies solo porque no te guste el video: así estarás dificultando el trabajo de los moderadores.";
$LANGS['statadded'] = 'Añadido';
$LANGS['statviews'] = 'Reproducciones';
$LANGS['statratings'] = 'Calificaciones';
$LANGS['statresponses'] = 'Respuestas';
$LANGS['statcomments'] = 'Comentarios';
$LANGS['statfavorited'] = 'Favoritos';
$LANGS['statsdata'] = 'Estadística y datos';
$LANGS['honors'] = 'Galardones de este video';
$LANGS['mostviewed'] = 'Más vistos';
$LANGS['topfavorited'] = 'Los Favoritos';
$LANGS['times'] = 'veces';
$LANGS['mostdiscussed'] = 'Más comentados';
$LANGS['toprated'] = 'Más valorados';
$LANGS['videolinks'] = 'Sitios con enlaces a este video';
$LANGS['clicksfrom'] = 'clics desde';
$LANGS['responses'] = 'Respuestas en video';
$LANGS['responsespost'] = 'Publicar una respuesta en video';
$LANGS['textcomments'] = 'Comentarios escritos';
$LANGS['commentpost'] = 'Escribe un comentario';
$LANGS['commentonthisvideo'] = 'Comenta en este video';
$LANGS['postcomment'] = 'Comentar';
$LANGS['remainingcounter'] = 'Número de caracteres restantes';
$LANGS['nocomments'] = 'Este video no tiene <b>comentarios</b>.';
$LANGS['noresponses'] = 'Este video no tiene <b>respuestas</b>.';
$LANGS['commviewall'] = 'Ver todos los';
$LANGS['delete'] = 'Suprimir';
$LANGS['reply'] = 'Responder';
$LANGS['commentlogin'] = '¿Quieres enviar algún comentario?';
$LANGS['commentlogindesc'] = '<a href="/signup">Únete a BitView</a> para obtener una cuenta gratuita o <a href="/login">inicia sesión</a> si ya eres miembro.';
$LANGS['logintoresponse'] = 'Inicia sesión para publicar una respuesta en video';
$LANGS['logintocomment'] = 'Inicia sesión para publicar un comentario';
$LANGS['logintofav'] = '<a href="/login">Inicia sesión</a> para agregar este video a favoritos.';
$LANGS['logintopl'] = '<a href="/login">Inicia sesión</a> para agregar un video a una lista de reproducción.';
$LANGS['logintoflag'] = '<a href="/login">Inicia sesión</a> para marcar este video.';
$LANGS['close'] = 'cerrar';
$LANGS['addresponse'] = 'Agregar respuesta';
$LANGS['recentlyrated'] = 'Calificaciones recientes';
$LANGS['commentsdisabled'] = 'No se pueden añadir comentarios sobre este video.';
$LANGS['ratingsdisabled'] = 'Calificaciones desactivadas';
$LANGS['rating1'] = 'Malo';
$LANGS['rating2'] = 'Nada especial';
$LANGS['rating3'] = 'Vale la pena';
$LANGS['rating4'] = 'Bastante bueno';
$LANGS['rating5'] = '¡Impresionante!';
$LANGS['saving'] = 'Guardando...';
$LANGS['signintorate'] = '<a href="/login">Accede</a> para calificar';
$LANGS['addingcomment'] = "Añadiendo comentario...";
$LANGS['commentposted'] = "Comentario publicado";
$LANGS['commentspammsg'] = "Publicar el mismo comentario nuevamente se considera spam. Vuelve a intentarlo más tarde.";
$LANGS['commentspammsg2'] = "Publicar más de 5 comentarios consecutivos se considera spam. Vuelve a intentarlo más tarde.";
$LANGS['emptycomment'] = "Tu comentario no puede estar vacío.";
$LANGS['spambutton'] = "Spam";
$LANGS['notspambutton'] = "No es spam";
$LANGS['commentsspam'] = "Comentario marcado como spam";
$LANGS['marked'] = "Marcado como spam";
$LANGS['spamshow'] = "Mostrar";
$LANGS['spamhide'] = "Esconder";
$LANGS['poorcomment'] = "Comentario deficiente";
$LANGS['goodcomment'] = "Buen comentario";
$LANGS['pleasesignin'] = "Inicia sesión";
$LANGS['showmorecomments'] = "Mostrar más contenidos";
$LANGS['showingamount'] = "<strong>Mostrando {number}</strong> de {total} comentarios";

/* Watch comments */
$LANGS['allcomments'] = 'Todos los comentarios';

/* Sign In */
$LANGS['username'] = "Nombre de usuario";
$LANGS['password'] = "Contraseña";
$LANGS['logindesc'] = "Inicia sesión a BitView con tu cuenta";
$LANGS['forgot'] = "¿No puedes iniciar sesión en tu cuenta?";
$LANGS['forgotmsg'] = "Por favor, póngase en contacto con nosotros vía Twitter (@BitView_) o envíe un mensaje a nuestros moderadores en Discord (enlace en el pie de página).";
$LANGS['noaccount'] = "¿No tienes una cuenta?";
$LANGS['signuptobv'] = "Regístrate en BitView.";
$LANGS['signintobv'] = "Inicia sesión en BitView";
$LANGS['signindesc1'] = "¡Únete a la comunidad para compartir videos más extensa del mundo!";
$LANGS['signindesc2'] = "Obtén acceso total con tu cuenta de BitView:";
$LANGS['signindesc3'] = "Sube y comparte tus videos con millones de usuarios";
$LANGS['signindesc4'] = "Publica los videos que grabes con tu cámara digital o teléfono móvil";
$LANGS['signindesc5'] = "Guarda tus videos favoritos para mirar y compartir luego";
$LANGS['notallowed'] = "Tu cuenta ha sido suspendida 3 veces. ¡Ya no puedes volver a usar BitView!";
$LANGS['wrongpassword'] = 'La contraseña que has introducido es incorrecta.';
$LANGS['staysigned'] = "No cerrar sesión";

/* Sign Up */
$LANGS['email'] = "Dirección de correo electrónico";
$LANGS['passwordstrength'] = "Nivel de seguridad de la contraseña";
$LANGS['psnone'] = "Ninguna";
$LANGS['psweak'] = "Débil";
$LANGS['psfair'] = "Regular";
$LANGS['psgood'] = "Bueno";
$LANGS['psstrong'] = "Fuerte";
$LANGS['repassword'] = "Vuelve a escribir la contraseña";
$LANGS['usernamedesc'] = "El nombre de usuario solo puede contener letras de A-Z o números del 0-9.";
$LANGS['captcha'] = "Verificación de captcha";
$LANGS['acceptterms'] = 'Acepto los <a href="/terms">Términos de uso</a> y la <a href="/privacy">Política de privacidad</a>.';
$LANGS['copyrighttext'] = 'Si subes material que no te pertenece, infringirás los derechos de autor y la ley. Si subes material que no te pertenece, tu cuenta se eliminará.';
$LANGS['mustaccept'] = 'Debes aceptar los Términos de uso y la Política de privacidad para crear tu cuenta.';
$LANGS['createaccount'] = 'Crear mi cuenta';
$LANGS['signuperror'] = 'Ha habido un error al crear tu cuenta.';
$LANGS['sameemail'] = 'Este nombre de usuario o la dirección de correo electrónico ya está en uso.';
$LANGS['usernamechar'] = 'Los nombres de usuario solo pueden tener letras y números.';
$LANGS['required'] = 'Debes llenar todos los cuadros de texto.';
$LANGS['notmatch'] = 'Las contraseñas no coinciden.';
$LANGS['signuphead'] = 'Crea tu cuenta de BitView';

/* Videos Page */
$LANGS['recentvideos'] = 'Videos recientes';
$LANGS['random'] = 'Aleatorio';
$LANGS['dropdownmore'] = 'más';
$LANGS['allcatin'] = 'en';
$LANGS['allcat'] = 'Todas las categorías';
$LANGS['categories'] = 'Categorías';
$LANGS['nomorevideos'] = 'No hemos encontrado más videos...';
$LANGS['timetoday'] = 'Hoy';
$LANGS['timeweek'] = 'Esta semana';
$LANGS['timemonth'] = 'Este mes';
$LANGS['alltime'] = 'Siempre';
$LANGS['when'] = 'Cuándo';
$LANGS['videofavorites'] = 'favoritos';
$LANGS['videocomments'] = 'comentarios';
$LANGS['trendingtopics'] = 'Tendencia';

/* Channels Page */
$LANGS['mostsubscribed'] = 'Con más suscripciones';
$LANGS['lastlogin'] = 'Último inicio de sesión';
$LANGS['cstatviews'] = 'Reproducciones';
$LANGS['cstatvideos'] = 'Videos';
$LANGS['cstatsubs'] = 'Suscriptores';
$LANGS['nochannels'] = 'No hemos encontrado más canales...';

/* Video Categories */
$LANGS['cat1'] = "Cine y animación";
$LANGS['cat2'] = "Automovilismo";
$LANGS['cat3'] = "Educación";
$LANGS['cat4'] = "Entretenimiento";
$LANGS['cat5'] = "Eventos y bodas";
$LANGS['cat6'] = "Familiar";
$LANGS['cat7'] = "En venta y subastas";
$LANGS['cat8'] = "Aficiones e intereses";
$LANGS['cat9'] = "Comedia";
$LANGS['cat10'] = "Música";
$LANGS['cat11'] = "Noticias y política";
$LANGS['cat12'] = "Extraño y escandaloso";
$LANGS['cat13'] = "Gente y blogs";
$LANGS['cat14'] = "Citas";
$LANGS['cat15'] = "Mascotas y animales";
$LANGS['cat16'] = "Ciencia & Tecnología";
$LANGS['cat17'] = "Cortometrajes";
$LANGS['cat18'] = "Deportes";
$LANGS['cat19'] = "Viajes & Eventos";
$LANGS['cat20'] = "Juego";
$LANGS['cat21'] = "Videoblogs";

/* Channel Types */
$LANGS['type0'] = "Ninguno";
$LANGS['type1'] = "Miembro";
$LANGS['type1p'] = "Miembros";
$LANGS['type2'] = "Humorista";
$LANGS['type2p'] = "Humoristas";
$LANGS['type3'] = "Director";
$LANGS['type3p'] = "Directores";
$LANGS['type4'] = "Gurú";
$LANGS['type4p'] = "Gurús";
$LANGS['type5'] = "Músico";
$LANGS['type5p'] = "Músicos";
$LANGS['type6'] = "Reportero";
$LANGS['type6p'] = "Reporteros";

/* Countries */
$LANGS['cat_AF'] = "Afganistán";
$LANGS['cat_AX'] = "Islas Åland";
$LANGS['cat_AL'] = "Albania";
$LANGS['cat_DZ'] = "Algeria";
$LANGS['cat_AS'] = "Samoa Americana";
$LANGS['cat_AD'] = "Andorra";
$LANGS['cat_AO'] = "Angola";
$LANGS['cat_AI'] = "Anguilla";
$LANGS['cat_AQ'] = "Antártida";
$LANGS['cat_AG'] = "Antigua y Barbuda";
$LANGS['cat_AR'] = "Argentina";
$LANGS['cat_AM'] = "Armenia";
$LANGS['cat_AW'] = "Aruba";
$LANGS['cat_AU'] = "Australia";
$LANGS['cat_AT'] = "Austria";
$LANGS['cat_AZ'] = "Azerbaiyán";
$LANGS['cat_BS'] = "Bahamas";
$LANGS['cat_BH'] = "Baréin";
$LANGS['cat_BD'] = "Bangladesh";
$LANGS['cat_BB'] = "Barbados";
$LANGS['cat_BY'] = "Bielorrusia";
$LANGS['cat_BE'] = "Bélgica";
$LANGS['cat_BZ'] = "Belice";
$LANGS['cat_BJ'] = "Benín";
$LANGS['cat_BM'] = "Bermudas";
$LANGS['cat_BT'] = "Bután";
$LANGS['cat_BO'] = "Bolivia";
$LANGS['cat_BQ'] = "Caribe Neerlandés";
$LANGS['cat_BA'] = "Bosnia y Herzegovina";
$LANGS['cat_BW'] = "Botsuana";
$LANGS['cat_BV'] = "Isla Bouvet";
$LANGS['cat_BR'] = "Brasil";
$LANGS['cat_IO'] = "Territorio Británico del Océano Índico";
$LANGS['cat_BN'] = "Brunéi";
$LANGS['cat_BG'] = "Bulgaria";
$LANGS['cat_BF'] = "Burkina Faso";
$LANGS['cat_BI'] = "Burundi";
$LANGS['cat_KH'] = "Camboya";
$LANGS['cat_CM'] = "Camerún";
$LANGS['cat_CA'] = "Canadá";
$LANGS['cat_CV'] = "Cabo Verde";
$LANGS['cat_KY'] = "Islas Caimán";
$LANGS['cat_CF'] = "República Centroafricana";
$LANGS['cat_TD'] = "Chad";
$LANGS['cat_CL'] = "Chile";
$LANGS['cat_CN'] = "China";
$LANGS['cat_CX'] = "Isla de Navidad";
$LANGS['cat_CC'] = "Islas Cocos";
$LANGS['cat_CO'] = "Colombia";
$LANGS['cat_KM'] = "Comoras";
$LANGS['cat_CG'] = "Congo";
$LANGS['cat_CD'] = "República Democrática del Congo";
$LANGS['cat_CK'] = "Islas Cook";
$LANGS['cat_CR'] = "Costa Rica";
$LANGS['cat_CI'] = "Costa de Marfil";
$LANGS['cat_HR'] = "Croacia";
$LANGS['cat_CU'] = "Cuba";
$LANGS['cat_CW'] = "Curazao";
$LANGS['cat_CY'] = "Chipre";
$LANGS['cat_CZ'] = "República Checa";
$LANGS['cat_DK'] = "Dinamarca";
$LANGS['cat_DJ'] = "Yibuti";
$LANGS['cat_DM'] = "Dominica";
$LANGS['cat_DO'] = "República Dominicana";
$LANGS['cat_EC'] = "Ecuador";
$LANGS['cat_EG'] = "Egipto";
$LANGS['cat_SV'] = "El Salvador";
$LANGS['cat_GQ'] = "Guinea Ecuatorial";
$LANGS['cat_ER'] = "Eritrea";
$LANGS['cat_EE'] = "Estonia";
$LANGS['cat_ET'] = "Etiopía";
$LANGS['cat_FK'] = "Islas Malvinas";
$LANGS['cat_FO'] = "Islas Feroe";
$LANGS['cat_FJ'] = "Fiyi";
$LANGS['cat_FI'] = "Finlandia";
$LANGS['cat_FR'] = "Francia";
$LANGS['cat_GF'] = "Guayana Francesa";
$LANGS['cat_FG'] = "Guayana Francesa";
$LANGS['cat_PF'] = "Polinesia Francesa";
$LANGS['cat_TF'] = "Territorios Australes Franceses";
$LANGS['cat_GA'] = "Gabón";
$LANGS['cat_GM'] = "Gambia";
$LANGS['cat_GE'] = "Georgia";
$LANGS['cat_DE'] = "Alemania";
$LANGS['cat_GH'] = "Ghana";
$LANGS['cat_GI'] = "Gibraltar";
$LANGS['cat_GR'] = "Grecia";
$LANGS['cat_GL'] = "Groenlandia";
$LANGS['cat_GD'] = "Granada";
$LANGS['cat_GP'] = "Guadalupe";
$LANGS['cat_GU'] = "Guam";
$LANGS['cat_GT'] = "Guatemala";
$LANGS['cat_GG'] = "Guernsey";
$LANGS['cat_GN'] = "Guinea";
$LANGS['cat_GW'] = "Guinea-Bisáu";
$LANGS['cat_GY'] = "Guyana";
$LANGS['cat_HT'] = "Haití";
$LANGS['cat_HM'] = "Islas Heard y McDonald";
$LANGS['cat_VA'] = "Ciudad del Vaticano";
$LANGS['cat_HN'] = "Honduras";
$LANGS['cat_HK'] = "Hong Kong";
$LANGS['cat_HU'] = "Hungría";
$LANGS['cat_IS'] = "Islandia";
$LANGS['cat_IN'] = "India";
$LANGS['cat_ID'] = "Indonesia";
$LANGS['cat_IR'] = "Irán";
$LANGS['cat_IQ'] = "Irak";
$LANGS['cat_IE'] = "Irlanda";
$LANGS['cat_IM'] = "Isla de Man";
$LANGS['cat_IL'] = "Israel";
$LANGS['cat_IT'] = "Italia";
$LANGS['cat_JM'] = "Jamaica";
$LANGS['cat_JP'] = "Japón";
$LANGS['cat_JE'] = "Jersey";
$LANGS['cat_JO'] = "Jordania";
$LANGS['cat_KZ'] = "Kazajistán";
$LANGS['cat_KE'] = "Kenia";
$LANGS['cat_KI'] = "Kiribati";
$LANGS['cat_XK'] = "Kosovo";
$LANGS['cat_KP'] = "Corea del Norte";
$LANGS['cat_KR'] = "Corea del Sur";
$LANGS['cat_KW'] = "Kuwait";
$LANGS['cat_KG'] = "Kirguistán";
$LANGS['cat_LA'] = "Laos";
$LANGS['cat_LV'] = "Letonia";
$LANGS['cat_LB'] = "Líbano";
$LANGS['cat_LS'] = "Lesoto";
$LANGS['cat_LR'] = "Liberia";
$LANGS['cat_LY'] = "Libia";
$LANGS['cat_LI'] = "Liechtenstein";
$LANGS['cat_LT'] = "Lituania";
$LANGS['cat_LU'] = "Luxemburgo";
$LANGS['cat_MO'] = "Macao";
$LANGS['cat_MK'] = "Macedonia del Norte";
$LANGS['cat_MG'] = "Madagascar";
$LANGS['cat_MW'] = "Malaui";
$LANGS['cat_MY'] = "Malasia";
$LANGS['cat_MV'] = "Maldivas";
$LANGS['cat_ML'] = "Mali";
$LANGS['cat_MT'] = "Malta";
$LANGS['cat_MH'] = "Islas Marshall";
$LANGS['cat_MQ'] = "Martinica";
$LANGS['cat_MR'] = "Mauritania";
$LANGS['cat_MU'] = "Mauricio";
$LANGS['cat_YT'] = "Mayotte";
$LANGS['cat_MX'] = "México";
$LANGS['cat_FM'] = "Micronesia";
$LANGS['cat_MD'] = "Moldavia";
$LANGS['cat_MC'] = "Mónaco";
$LANGS['cat_MN'] = "Mongolia";
$LANGS['cat_ME'] = "Montenegro";
$LANGS['cat_MS'] = "Montserrat";
$LANGS['cat_MA'] = "Marruecos";
$LANGS['cat_MZ'] = "Mozambique";
$LANGS['cat_MM'] = "Birmania";
$LANGS['cat_NA'] = "Namibia";
$LANGS['cat_NR'] = "Nauru";
$LANGS['cat_NP'] = "Nepal";
$LANGS['cat_NL'] = "Países Bajos";
$LANGS['cat_AN'] = "Antillas Neerlandesas";
$LANGS['cat_NC'] = "Nueva Caledonia";
$LANGS['cat_NZ'] = "Nueva Zelanda";
$LANGS['cat_NI'] = "Nicaragua";
$LANGS['cat_NE'] = "Níger";
$LANGS['cat_NG'] = "Nigeria";
$LANGS['cat_NU'] = "Niue";
$LANGS['cat_NF'] = "Isla Norfolk";
$LANGS['cat_MP'] = "Islas Marianas del Norte";
$LANGS['cat_NO'] = "Noruega";
$LANGS['cat_OM'] = "Omán";
$LANGS['cat_PK'] = "Pakistán";
$LANGS['cat_PW'] = "Palaos";
$LANGS['cat_PS'] = "Palestina";
$LANGS['cat_PA'] = "Panamá";
$LANGS['cat_PG'] = "Papúa Nueva Guinea";
$LANGS['cat_PY'] = "Paraguay";
$LANGS['cat_PE'] = "Perú";
$LANGS['cat_PH'] = "Filipinas";
$LANGS['cat_PN'] = "Islas Pitcairn";
$LANGS['cat_PL'] = "Polonia";
$LANGS['cat_PT'] = "Portugal";
$LANGS['cat_PR'] = "Puerto Rico";
$LANGS['cat_QA'] = "Catar";
$LANGS['cat_RE'] = "Reunión";
$LANGS['cat_RO'] = "Rumanía";
$LANGS['cat_RU'] = "Rusia";
$LANGS['cat_RW'] = "Ruanda";
$LANGS['cat_BL'] = "San Bartolomé";
$LANGS['cat_SH'] = "Santa Elena";
$LANGS['cat_KN'] = "San Cristóbal y Nieves";
$LANGS['cat_LC'] = "Santa Lucía";
$LANGS['cat_MF'] = "San Martín";
$LANGS['cat_PM'] = "San Pedro y Miquelón";
$LANGS['cat_VC'] = "San Vicente y las Granadinas";
$LANGS['cat_WS'] = "Samoa";
$LANGS['cat_SM'] = "San Marino";
$LANGS['cat_ST'] = "Santo Tomé y Príncipe";
$LANGS['cat_SA'] = "Arabia Saudita";
$LANGS['cat_SN'] = "Senegal";
$LANGS['cat_RS'] = "Serbia";
$LANGS['cat_SC'] = "Seychelles";
$LANGS['cat_SL'] = "Sierra Leona";
$LANGS['cat_SG'] = "Signapur";
$LANGS['cat_SX'] = "Sint Maarten";
$LANGS['cat_SK'] = "Eslovaquia";
$LANGS['cat_SI'] = "Eslovenia";
$LANGS['cat_SB'] = "Islas Salomón";
$LANGS['cat_SO'] = "Somalia";
$LANGS['cat_ZA'] = "Sudáfrica";
$LANGS['cat_GS'] = "Islas Georgias del Sur y Sandwich del Sur";
$LANGS['cat_ES'] = "España";
$LANGS['cat_LK'] = "Sri Lanka";
$LANGS['cat_SD'] = "Sudán";
$LANGS['cat_SR'] = "Surinam";
$LANGS['cat_SJ'] = "Svalbard y Jan Mayen";
$LANGS['cat_SZ'] = "Esuatini";
$LANGS['cat_SE'] = "Suecia";
$LANGS['cat_CH'] = "Suiza";
$LANGS['cat_SS'] = "Sudán del Sur";
$LANGS['cat_SY'] = "Siria";
$LANGS['cat_TW'] = "Taiwán";
$LANGS['cat_TJ'] = "Tayikistán";
$LANGS['cat_TZ'] = "Tanzania";
$LANGS['cat_TH'] = "Tailandia";
$LANGS['cat_TL'] = "Timor Oriental";
$LANGS['cat_TG'] = "Togo";
$LANGS['cat_TK'] = "Tokelau";
$LANGS['cat_TO'] = "Tonga";
$LANGS['cat_TT'] = "Trinidad y Tobago";
$LANGS['cat_TN'] = "Túnez";
$LANGS['cat_TR'] = "Turquía";
$LANGS['cat_TM'] = "Turkmenistán";
$LANGS['cat_TC'] = "Islas Turcas y Caicos";
$LANGS['cat_TV'] = "Tuvalu";
$LANGS['cat_UG'] = "Uganda";
$LANGS['cat_UA'] = "Ucrania";
$LANGS['cat_AE'] = "Emiratos Árabes Unidos";
$LANGS['cat_GB'] = "Reino Unido";
$LANGS['cat_US'] = "Estados Unidos";
$LANGS['cat_UM'] = "Islas Ultramarinas Menores de Estados Unidos";
$LANGS['cat_UY'] = "Uruguay";
$LANGS['cat_UZ'] = "Uzbekistán";
$LANGS['cat_VU'] = "Vanatu";
$LANGS['cat_VE'] = "Venezuela";
$LANGS['cat_VN'] = "Vietnam";
$LANGS['cat_VG'] = "Islas Vírgenes Británicas";
$LANGS['cat_VI'] = "Islas Vírgenes de los Estados Unidos";
$LANGS['cat_WF'] = "Wallis y Futuna";
$LANGS['cat_EH'] = "Sahara Occidental";
$LANGS['cat_YE'] = "Yemen";
$LANGS['cat_ZM'] = "Zambia";
$LANGS['cat_ZW'] = "Zimbabue";

/* My Subscriptions */
$LANGS['newvideos'] = "Videos nuevos";

/* Account */
$LANGS['myaccount'] = "Mi cuenta";
$LANGS['vidsfavs'] = "Mis videos, favoritos y listas de reproducción";
$LANGS['accountsettings'] = "Configuración de cuenta";
$LANGS['viewinghistory'] = "Historial";
$LANGS['mychannel'] = "Mi canal";
$LANGS['uploadedvideos'] = "Videos subidos";
$LANGS['new'] = "Nuevo";
$LANGS['playlist'] = "Lista de reproducción";
$LANGS['videoupload'] = "Subir video";
$LANGS['nosubvideos'] = "No te has suscrito a ningún canal...";
$LANGS['nofavvideos'] = "No tienes ningún video favorito...";

/* My Videos */
$LANGS['sortby'] = "Ordenar por";
$LANGS['sorttitle'] = "Título";
$LANGS['sorttime'] = "Duración";
$LANGS['sortdateadded'] = "Fecha en que se añadió";
$LANGS['sortviews'] = "Reproducciones";
$LANGS['sortrating'] = "Calificación";
$LANGS['stattime'] = "Duración";
$LANGS['statrating'] = "Calificación";
$LANGS['statbroadcast'] = "Emitir";
$LANGS['statrawfile'] = "Archivo sin procesar";
$LANGS['public'] = "Público";
$LANGS['private'] = "Privado";
$LANGS['live'] = "En directo";
$LANGS['converting'] = "Procesando...";
$LANGS['uploading'] = "Subiendo...";
$LANGS['addvidsto'] = "Agregar videos a";
$LANGS['play'] = "Reproducir";
$LANGS['edit'] = "Editar";
$LANGS['setasavatar'] = "Establecer avatar";
$LANGS['downloadmp4'] = "Descargar MP4";
$LANGS['deleteconfirmation'] = "¿Estás seguro de que quieres eliminar este video?";
$LANGS['novideos'] = "No has subido ningún video. ¡<a href='/my_videos_upload'>Sube tu primer video</a>!";
$LANGS['nomyvideosresults'] = "No se han encontrado resultados. Comprueba que has escrito bien tu búsqueda.";

/* Edit Video */
$LANGS['title'] = "Título";
$LANGS['desc'] = "Descripción";
$LANGS['privacy'] = "Privacidad";
$LANGS['saveinfo'] = "Guardar";
$LANGS['saveinfoconfirm'] = "¿Estás seguro de que quieres guardar los cambios?";
$LANGS['viewchart'] = "Gráfico de reproducciones";
$LANGS['videodetails'] = "Detalles del video";
$LANGS['backtopreviouspage'] = "Volver a la página anterior";
$LANGS['editsavechanges'] = "Guardar cambios";
$LANGS['editcancel'] = "cancelar";
$LANGS['videoinfo'] = "Información del video";
$LANGS['videothumbnail'] = "Miniatura de video";
$LANGS['uploadthumbnail'] = "Subir miniatura";
$LANGS['customthumbdesc'] = 'Para establecer una miniatura personalizada, haga click en la miniatura del lado izquierdo y seleccione el archivo a subir. Entonces, haga click en el botón "Subir miniatura".';
$LANGS['customthumbtitle'] = '¿Quiere cambiar esta miniatura?';
$LANGS['customthumbinfo'] = 'Las miniaturas personalizadas son exclusivas para partners. Si quiere leer más sobre las ventajas de unirse al programa de partners y revisar si cumple los requisitos, haga click en el botón de abajo.';
$LANGS['partnerreadmore'] = 'Leer más';
$LANGS['broadcastingoptions'] = 'Opciones de transmisión y para compartir';
$LANGS['publicdesc'] = "todos pueden buscar y ver el video, recomendado";
$LANGS['privatedesc'] = "sólo usuarios específicos de BitView pueden ver el video";
$LANGS['allowcomments'] = "Permitir comentarios automáticamente";
$LANGS['allowfriendcomments'] = "Sólo permitir comentarios de amigos";
$LANGS['disablecomments'] = "No permitir comentarios";
$LANGS['dateandmap'] = "Fecha y mapa";
$LANGS['clear'] = "Borrar";
$LANGS['allowratings'] = "Sí, permitir que otros usuarios puntúen este video";
$LANGS['dontallowratings'] = "No permitir que otros usuarios puntúen este video";

/* My Playlists */
$LANGS['addedpl'] = "Creado";
$LANGS['frompl'] = "De";
$LANGS['nopl'] = "No has creado ninguna lista de reproducción.";

/* My Playlist */
$LANGS['playlistedit'] = "Editar lista de reproducción";
$LANGS['videourl'] = "Enlace del video";
$LANGS['add'] = "Agregar";
$LANGS['editinfo'] = "Editar información";

/* Edit Playlist */
$LANGS['pledittitle'] = "Editar lista de reproducción";
$LANGS['pleditdesc'] = "Una lista de reproducción es una colección de videos que puedes configurar como quieras.";
$LANGS['cancel'] = "Cancelar";

/* Create Playlist */
$LANGS['createplaylisttitle'] = "Crear una lista de reproducción";
$LANGS['createplaylist'] = "Crear lista";

/* View Playlist */
$LANGS['plpermalink'] = "Lista de reproducción/URL (enlace permanente):";
$LANGS['sortcomments'] = "Comentarios";
$LANGS['unsorted'] = "Sin ordenar";
$LANGS['playallvideos'] = "Reproducir todos los videos";

/* Inbox */
$LANGS['compose'] = "Redactar";
$LANGS['from'] = "De";
$LANGS['subject'] = "Asunto";
$LANGS['date'] = "Fecha";
$LANGS['allmsg'] = "Todos los mensajes";
$LANGS['msgcom'] = "Comentarios";
$LANGS['sentmsg'] = "Mensajes enviados";
$LANGS['nomsg'] = "No tienes mensajes";


/* Send Message */
$LANGS['messagecont'] = "Mensaje";
$LANGS['to'] = "A";
$LANGS['sendmessagebutton'] = "Enviar mensaje";

/* Groups */
$LANGS['groups'] = "Grupos";
$LANGS['joinedgroups'] = "Tus grupos";
$LANGS['recentgroups'] = "Grupos recientes";
$LANGS['mostmembers'] = "Con más miembros";
$LANGS['mostvideos'] = "Con más videos";
$LANGS['groupmostdiscussed'] = "Con más debates";
$LANGS['createagroup'] = "Crear un grupo";
$LANGS['groupvideos'] = "Videos";
$LANGS['groupmembers'] = "Miembros";
$LANGS['discussions'] = "Debates";
$LANGS['groupcreated'] = "Fecha de creación";
$LANGS['nogroups'] = "No se han encontrado más grupos...";

/* Group */
$LANGS['jointhisgroup'] = "Unirme a este grupo";
$LANGS['removerequest'] = "Cancelar solicitud";
$LANGS['leavegroup'] = "Salirme del grupo";
$LANGS['moderation'] = "Moderación";
$LANGS['viewallvideos'] = "Ver todos los videos";
$LANGS['addvideo'] = "Agregar un video";
$LANGS['novideos'] = "No hay videos...";
$LANGS['nodiscussions'] = "No hay debates...";
$LANGS['creatediscussion'] = "Crear un debate";
$LANGS['topostatopic'] = "para crear un tema";
$LANGS['topic'] = "Tema";
$LANGS['author'] = "Autor";
$LANGS['replies'] = "Réplicas";
$LANGS['lastpost'] = "Último comentario";
$LANGS['viewallmembers'] = "Ver todos los miembros";
$LANGS['owner'] = "Propietario";
$LANGS['grouptype'] = "Puedes unirte";
$LANGS['instantjoin'] = "Instantáneamente";
$LANGS['approvalrequired'] = "Tienes que ser aceptado";
$LANGS['groupurl'] = "URL";
$LANGS['deletediscussion'] = "Eliminar debate";
$LANGS['postreply'] = "Publicar respuesta";
$LANGS['post'] = "Publicar";
$LANGS['accept'] = "Aceptar";
$LANGS['decline'] = "Declinar";

/* Group Moderation */
$LANGS['groupmoderation'] = "Moderación del grupo";
$LANGS['approvemembers'] = "Aprobar miembros";
$LANGS['approvevideos'] = "Aprobar videos";
$LANGS['yes'] = "Sí";
$LANGS['no'] = "No";
$LANGS['changeinfo'] = "Cambiar información";
$LANGS['changeimage'] = "Cambiar imagen";
$LANGS['image'] = "Imagen";
$LANGS['styling'] = "Estilo";
$LANGS['cssdesc'] = "Se suspenderá tu cuenta si usas fondos o gráficos que muestren contenido ilegal.";
$LANGS['updatecss'] = "Actualizar estilo";
$LANGS['groupmessage'] = "Mensaje";
$LANGS['sendmessagetomembers'] = "Enviar mensaje a los miembros";
$LANGS['delgroup'] = "Eliminar grupo";

/* Submit Group Video */
$LANGS['submitvideotitle'] = "Agregar video al grupo";
$LANGS['submitvideo'] = "Agregar video";

/* Create Group */
$LANGS['groupname'] = "Nombre del grupo";
$LANGS['groupimage'] = "Imagen del grupo";
$LANGS['creategroup'] = "Crear grupo";
$LANGS['creategroupdesc'] = "Los grupos te permiten discutir con otros miembros y compartir videos con otros de forma sencilla.";

/* Create Group Discussion */
$LANGS['discussiontitle'] = "Título del debate";
$LANGS['creatediscussiondesc'] = "Los debates son partes de los grupos donde puedes discutir un tema.";

/* Search Results */
$LANGS['resultspre'] = "Resultados para"; /* Explanation: Use if the search query goes before "results". Example: "Resultados para search" in Spanish. If your language doesn't use this, leave it empty like this: ''*/
$LANGS['resultspost'] = ""; /* Explanation: Use if "BitView" goes after the username. Example: "search results" in English. If your language doesn't use this, leave it empty like this: '' */
$LANGS['relevance'] = 'Relevancia';
$LANGS['viewcount'] = 'Número de reproducciones';
$LANGS['searchrating'] = 'Calificación';
$LANGS['newest'] = 'Fecha de subida';
$LANGS['nochannelsfound'] = 'No se ha encontrado ningún canal...';
$LANGS['noplfound'] = 'No se ha encontrado ninguna lista de reproducción...';
$LANGS['nogroupsfound'] = 'No se ha encontrado ningún grupo...';

/* Profile */
$LANGS['channelsuspended'] = 'Esta cuenta está suspendida.';
$LANGS['accountnotfound'] = 'No se ha encontrado esta cuenta.';
$LANGS['channel'] = 'Canal';
$LANGS['friends'] = 'Amigos';
$LANGS['channelsubscribers'] = 'Suscriptores';
$LANGS['linkcomments'] = 'Comentarios';
$LANGS['bulletins'] = 'Boletines';
$LANGS['editchannel'] = 'Editar canal';
$LANGS['type'] = 'Tipo';
$LANGS['joined'] = 'Antigüedad';
$LANGS['videoswatched'] = 'Videos vistos';
$LANGS['channelviews'] = 'Reproducciones del canal';
$LANGS['age'] = 'Edad';
$LANGS['gender'] = 'Género';
$LANGS['male'] = 'Hombre';
$LANGS['female'] = 'Mujer';
$LANGS['status'] = 'Estado';
$LANGS['single_m'] = 'Soltero';
$LANGS['single_f'] = 'Soltera';
$LANGS['taken_m'] = 'En una relación';
$LANGS['taken_f'] = 'En una relación';
$LANGS['married_m'] = 'Casado';
$LANGS['married_f'] = 'Casada';
$LANGS['country'] = 'País';
$LANGS['website'] = 'URL del sitio web';
$LANGS['hobbies'] = 'Intereses y aficiones';
$LANGS['music'] = 'Música';
$LANGS['movies'] = 'Películas y espectáculos';
$LANGS['books'] = 'Libros';
$LANGS['mostsub'] = 'Con más suscripciones';
$LANGS['report'] = 'Notificar';
$LANGS['pfpviolation'] = 'infracción de imagen de perfil';
$LANGS['connectwith'] = 'Conectar con';
$LANGS['profilesendmessage'] = 'Enviar mensaje';
$LANGS['messagetoyourself'] = 'No puedes enviar un mensaje a tu propio canal.';
$LANGS['logintomessage'] = 'Inicia sesión para enviar mensajes.';
$LANGS['addcomment'] = 'Agregar comentario';
$LANGS['logintocommentchannel'] = 'Inicia sesión para comentar en los canales.';
$LANGS['sharechannel'] = 'Compartir canal';
$LANGS['addfriend'] = 'Agregar como amigo';
$LANGS['retractinvite'] = 'Cancelar solicitud';
$LANGS['removefriend'] = 'Suprimir amigo';
$LANGS['notfriendyourself'] = 'No te puedes enviar una solicitud a tu propio canal.';
$LANGS['logintofriend'] = 'Inicia sesión para agregar amigos.';
$LANGS['blockuser'] = 'Bloquear usuario';
$LANGS['channelembed'] = 'Insertar este canal';
$LANGS['recentratings'] = 'Actividad reciente';
$LANGS['seeall'] = 'ver todo';
$LANGS['writebulletin'] = 'Escribir boletín';
$LANGS['bulletin'] = 'Boletín';
$LANGS['subvideos1'] = 'Suscribirse a los videos de ';
$LANGS['subvideos2'] = '';
$LANGS['plvideos'] = 'Videos';
$LANGS['playall'] = 'Reproducir todos';
$LANGS['featuredchannels'] = 'Canales destacados';
$LANGS['channelcomments'] = 'Comentarios sobre el canal';
$LANGS['bggraphic'] = 'gráfico del fondo';
$LANGS['reportthisuser'] = 'este usuario';
$LANGS['norecentratings'] = 'No hay actividad reciente...';
$LANGS['nosubscribers'] = 'No hay suscriptores...';
$LANGS['nosubscriptions'] = 'No hay suscripciones...';
$LANGS['nofriends'] = 'No hay amigos...';
$LANGS['nobulletins'] = 'No hay boletines...';
$LANGS['novideoschannel'] = 'No hay videos...';
$LANGS['nofavs'] = 'No hay videos favoritos...';
$LANGS['noplchannel'] = 'No hay listas de reproducción...';
$LANGS['pvideos'] = 'Videos privados';
$LANGS['pvideosallow'] = 'No tienes permiso para ver estos videos';
$LANGS['plvideoamount'] = 'videos';
$LANGS['bulletinpost'] = 'Boletín';
$LANGS['deletebulletin'] = 'Eliminar boletín';
$LANGS['body'] = 'Contenido';
$LANGS['bulletincomments'] = 'Comentarios sobre el boletín';
$LANGS['tocommentbulletin'] = 'para publicar un comentario en este boletín';
$LANGS['addacomment'] = 'Agregar un comentario';
$LANGS['postreplychannel'] = 'Publicar comentario';
$LANGS['writecomment'] = 'Escribe un comentario';
$LANGS['for'] = 'para';
$LANGS['commentdesc'] = 'Publica un comentario que aparecerá en el canal.';
$LANGS['postbulletin'] = 'Publicar boletín';
$LANGS['writeabulletin'] = 'Escribe un boletín';
$LANGS['bulletindesc'] = 'Los boletines aparecen en tu canal y en el de tus amigos.';
$LANGS['sharingoptions'] = 'Opciones para compartir';
$LANGS['sharingoptionsdesc'] = 'Existen dos formas de compartir este canal.';
$LANGS['sharingoptions1'] = '1. Copia y pega este enlace en un mensaje instantáneo o de correo electrónico.';
$LANGS['sharingoptions2'] = '2. Envía este canal mediante el programa de correo electrónico de tu equipo.';
$LANGS['clicktosend'] = 'Haz clic para enviar.';
$LANGS['honorless'] = 'menos';
$LANGS['activitycomment'] = 'ha realizado un comentario sobre';
$LANGS['activityfavorite'] = 'ha marcado un video como favorito';
$LANGS['activityrating'] = 'ha calificado un video:';
$LANGS['activityupload'] = 'ha subido un nuevo video';
$LANGS['activityfriend'] = 'se ha hecho amigo de';
$LANGS['activitysubscription'] = 'se ha suscrito a';
$LANGS['next'] = "Siguiente";
$LANGS['previous'] = "Anterior";

/* My Profile page */
$LANGS['myprofiledesc'] = 'Esta página incluye toda la configuración de tu cuenta de BitView.';
$LANGS['profileimages'] = 'Imágenes del canal';
$LANGS['avatar'] = 'Imagen de perfil';
$LANGS['backgroundimage'] = 'Imagen de fondo';
$LANGS['deleteimage'] = 'Eliminar imagen';
$LANGS['channelinformation'] = 'Información del canal';
$LANGS['genderrelationprivate'] = 'Prefiero no decirlo';
$LANGS['fctitle'] = 'Título canales destacados';
$LANGS['relationship'] = 'Relación';
$LANGS['birthday'] = 'Fecha de nacimiento';
$LANGS['showage'] = 'Mostrar edad';
$LANGS['aboutme'] = 'Descríbete';
$LANGS['emailprefs'] = 'Ajustes de correo electrónico';
$LANGS['emailpm'] = 'Envíame correo cuando me envíen un mensaje privado';
$LANGS['emailcomm'] = 'Envíame correo cuando me publiquen un comentario';
$LANGS['emailsub'] = 'Envíame correo con nuevos videos de mis suscripciones';
$LANGS['layoutprefs'] = 'Personalización de diseño';
$LANGS['bgcolor'] = 'Color de fondo';
$LANGS['bgfixed'] = 'Fijar imagen de fondo';
$LANGS['bgrepeat'] = 'Repetir imagen de fondo';
$LANGS['norepeat'] = 'No';
$LANGS['repeat'] = 'Sí';
$LANGS['repeatx'] = 'Horizontalmente';
$LANGS['repeaty'] = 'Verticalmente';
$LANGS['bgposition'] = 'Posición de imagen de fondo';
$LANGS['top'] = 'Arriba';
$LANGS['middle'] = 'Mitad';
$LANGS['bottom'] = 'Abajo';
$LANGS['fontcolor'] = 'Color del texto';
$LANGS['titlefontcolor'] = 'Color del texto del título';
$LANGS['linkcolor'] = 'Color del vínculo';
$LANGS['hlfontcolor'] = 'Color del texto de resalte';
$LANGS['hlheadercolor'] = 'Color de borde de resalte';
$LANGS['hlinsidecolor'] = 'Color de fondo de resalte';
$LANGS['headercolor'] = 'Color de borde';
$LANGS['insidecolor'] = 'Color de fondo';
$LANGS['font'] = 'Fuente';
$LANGS['featuredvideobox'] = 'Video destacado';
$LANGS['subscribersbox'] = 'Caja de suscriptores';
$LANGS['subscriptionsbox'] = 'Caja de suscripciones';
$LANGS['friendsbox'] = 'Caja de amigos';
$LANGS['bulletinsbox'] = 'Caja de boletines';
$LANGS['videosbox'] = 'Caja para videos';
$LANGS['favoritesbox'] = 'Caja para favoritos';
$LANGS['playlistsbox'] = 'Caja para listas de reproducción';
$LANGS['commentsbox'] = 'Caja de comentarios';
$LANGS['ratingsbox'] = 'Caja de actividad reciente';
$LANGS['partnersettings'] = 'Ajustes para partners';
$LANGS['bannerimage'] = 'Imagen de cabecera';
$LANGS['minibannerimage'] = 'Imagen de mini-cabecera';
$LANGS['sideimage'] = 'Imagen lateral';
$LANGS['recommendedsize'] = 'tamaño recomendado';
$LANGS['bannerlink'] = 'Enlace de cabecera';
$LANGS['sideimagelink'] = 'Enlace de la imagen lateral';
$LANGS['custombox'] = 'Caja personalizable';
$LANGS['customboxtitle'] = 'Título de la caja';
$LANGS['customboxcontent'] = 'Contenido de la caja';
$LANGS['savechanges'] = 'Actualizar canal';
$LANGS['submitimage'] = 'Subir imagen';

/* Upload page */
$LANGS['uploadpagetitle'] = 'Subida de videos';
$LANGS['step1of2'] = 'paso 1 de 2';
$LANGS['step2of2'] = 'paso 2 de 2';
$LANGS['videocategory'] = 'Categoría de video';
$LANGS['tagsdesc'] = 'Las etiquetas son palabras clave utilizadas para que otros usuarios puedan localizar tu video. <i>(separación con comas)</i>';
$LANGS['requiredfield'] = '(* indica que el campo es obligatorio)';
$LANGS['datemapoptions'] = 'Opciones de mapas y fechas';
$LANGS['optional'] = '(opcional)';
$LANGS['chooseoptions'] = 'elegir opciones';
$LANGS['lessoptions'] = 'menos opciones';
$LANGS['addressrecorded'] = 'Lugar de grabación';
$LANGS['uploadcontinue'] = 'Subir un video...';
$LANGS['file'] = 'Archivo';
$LANGS['broadcastoptions'] = 'Opciones de emisión';
$LANGS['uploadvideo'] = 'Subir video';
$LANGS['needfilevideotoupload'] = 'Debes de seleccionar un video para subirlo.';
$LANGS['aboutuploading'] = 'Acerca de la subida...';
$LANGS['uploaddesc1'] = 'Las subidas de videos normalmente tardan entre 1 y 5 minutos por cada MB con una conexión de alta velocidad, además de unos minutos adicionales para realizar la conversión del video.';
$LANGS['videolimit1'] = 'Tu video se limita a un tamaño de 100 MB y una duración de 15 minutos.';
$LANGS['videolimit2'] = 'Tu video se limita a un tamaño de 2 GB y una duración de 15 minutos.';
$LANGS['partnervideolimit1'] = 'Tu video se limita a un tamaño de 100 MB y una duración de 30 minutos.';
$LANGS['partnervideolimit2'] = 'Tu video se limita a un tamaño de 2 GB y una duración de 30 minutos.';
$LANGS['myvideosdesc'] = 'Después de la subida puedes editar o eliminar el video cuando quieras en el menú <a href="/my_videos">Mis videos</a>.';
$LANGS['newuploader'] = 'Utilizar la herramienta de subida avanzada';
$LANGS['olduploader'] = 'Utilizar la herramienta de subida básica';
$LANGS['videoadded'] = '¡Se ha añadido tu video exitosamente!';
$LANGS['videoaddeddesc'] = 'Tu video se está procesando y estará disponible en unos minutos.';
$LANGS['thankyou'] = 'Gracias';
$LANGS['sharelink'] = 'Comparte este video. Copia el enlace de abajo:';
$LANGS['embedlink'] = 'Inserta este video en tu página web. Copia el siguiente código:';
$LANGS['allrequiredinfo'] = 'Tienes que llenar todos los campos obligatorios.';

/* Partners */
$LANGS['partnerhead'] = 'Programas para partners';
$LANGS['partnertitle'] = 'Conviértete en partner de BitView';
$LANGS['partnerdesc'] = 'Si tienes videos atractivos y un público cada vez mayor, deja que BitView te ayude a dar el siguiente paso incorporándote al Programa para partners.';
$LANGS['applynow'] = 'Solicitar ahora';
$LANGS['contentpartners'] = 'Partners de contenido';
$LANGS['partnerbenefits'] = 'Ventajas para partners';
$LANGS['partnerbenefitsdesc'] = 'Convertirte en partner de BitView te ofrece muchas ventajas:<br><br>- Marca: hazte notar con imágenes de marca, incluyendo imágenes de cabecera, enlaces y una caja completamente personalizable.<br><br>- ¡Habrán más funciones en el futuro!';
$LANGS['qualificationsfaq'] = 'Requisitos y preguntas frecuentes';
$LANGS['qualificationsfaqdesc'] = 'Para poder participar en el Programa para partners de BitView, debes completar estos requisitos:<br><br>- Creas contenido original apropiado para ser subido en Internet.<br><br>- Tienes más de 75 suscriptores.<br><br>- Tu cuenta no incumple las <a href="/guidelines">Instrucciones de la comunidad</a>.';

/* Staff */
$LANGS['bvstaff'] = 'Equipo de BitView';
$LANGS['bvstaffdesc'] = "Estas son las personas que trabajan (o han trabajado) en BitView, manteniendo este sitio vivo, para que así los usuarios puedan Expresarse.";
$LANGS['owners'] = 'Propietarios';
$LANGS['ownerdesc'] = 'Las personas que (vaya sorpresa) son dueñas del sitio.';
$LANGS['coowndev'] = 'Co-propietario y <br> desarrollador';
$LANGS['owndev'] = 'Propietario y <br> desarrollador';
$LANGS['coownserver'] = 'Co-propietario,<br> propietario del servidor<br> y desarrollador';
$LANGS['modsanddevs'] = 'Moderadores y desarrolladores';
$LANGS['modsanddevsdesc'] = 'Las personas que mantienen el sitio limpio y seguro. ¿Tienes algún problema? Habla con ellos.';
$LANGS['moderator'] = 'Moderador';
$LANGS['moddev'] = 'Desarrollador y<br>moderador';
$LANGS['lettertitle'] = 'Carta a todas las personas que ayudaron con la página';
$LANGS['letter'] = "Queridos co-propietarios, desarrolladores y moderadores de BitView,<br><br>
                En nombre de todo el equipo de BitView, me gustaría expresar mi más sincera gratitud por vuestra dedicación excepcional y vuestro trabajo duro. Como uno de los propietarios, me llena de orgullo presenciar el crecimiento y éxito de nuestra plataforma para compartir videos, que no habría sido posible sin vuestras incalculables contribuciones.
                <br><br>
                Para el resto de co-propietarios, gracias por vuestro inquebrantable apoyo y visión. Vuestro compromiso con el desarrollo de la plataforma y sus mejoras han sido instrumentales para convertir BitView.net en la notable comunidad que es actualmente. Vuestro liderazgo y orientación estratégica han sido vitales para superar los retos y dificultades que hemos encontrado en nuestro camino.
                <br><br>
                Para nuestros talentosos desarrolladores, vuestros conocimientos técnicos e innovadoras ideas han transformado a BitView en una plataforma puntera que representa a la perfección cómo era YouTube en sus primeros años. Vuestras incontables horas desarrollando, solucionando problemas e implementando nuevas funciones han mejorado la experiencia de usuario y han convertido esta plataforma en un centro creativo y de entretenimiento. Vuestra dedicación para perfeccionar la funcionalidad y el rendimiento del sitio ha sido verdaderamente admirable.
                <br><br>
                A nuestros diligentes moderadores, expreso mi máximo agradecimiento por mantener la integridad y seguridad de nuestra comunidad. Vuestra vigilancia para hacer cumplir las normas y directrices, garantizando interacciones con respeto, y rápidamente solucionando cualquier problema que surja ha sido crucial para fomentar un entorno acogedor para todos los usuarios. Vuestros esfuerzos para mantener BitView como un espacio por el compromiso constructivo y el contenido positivo son muy admirables.
                <br><br>
                Juntos, como un equipo unificado, hemos alcanzado importantes hitos y hemos superado muchos obstáculos. El éxito de BitView es un testimonio del esfuerzo colectivo y a la pasión que cada uno de vosotros aporta. Vuestro compromiso con nuestra visión compartida ha sido verdaderamente inspiradora, y estoy agradecido de tener personas tan excepcionales a mi lado.
                <br><br>
                A medida que continuamos creciendo y evolucionando, atesoremos los lazos que hemos forjado y sigamos comprometidos con los valores que definen nuestro pequeño sitio. Juntos, seguiremos ese viaje de la nostalgia y proporcionaremos una plataforma donde los creadores puedan mostrar sus talentos.
                <br><br>
                De nuevo, gracias: co-propietarios, desarrolladores y moderadores, por vuestra dedicación inquebrantable, habilidad, y apoyo. Vuestro trabajo duro no ha pasado desapercibido, y estoy increiblemente orgulloso de formar parte de nuestro equipo.
                <br><br>
                Seguid expresándoos,<br>
                <3 vistafan12";
$LANGS['backtobitview'] = "Volver a BitView";

/* My Friends */
$LANGS['myfriends'] = 'Mis amigos';
$LANGS['invites'] = 'Solicitudes';
$LANGS['myinvites'] = 'Solicitudes enviadas';
$LANGS['incominginvites'] = 'Solicitudes de amistad';
$LANGS['noinvites'] = 'No hay invitaciones...';
$LANGS['actions'] = 'Acciones';
$LANGS['retract'] = 'Retirar';

/* About */
$LANGS['aboutus'] = 'Sobre nosotros';
$LANGS['abouttitle'] = '¿Qué es BitView?';
$LANGS['aboutdesc'] = 'BitView es una plataforma para subir videos. En BitView puedes:';
$LANGS['about1'] = 'Publicar tus videos favoritos a todo el mundo';
$LANGS['about2'] = 'Grabar a tus perros, gatos, y otras mascotas';
$LANGS['about3'] = 'Publica los videos que grabes con tu cámara digital o teléfono móvil';
$LANGS['about4'] = 'Mostrar videos de forma privada y segura a tus amigos y familia';
$LANGS['about5'] = '... ¡y mucho más!';
$LANGS['aboutsignup'] = '<a href="/signup">Crea tu cuenta ahora</a>.';
$LANGS['abouthelp'] = 'Para conocer más sobre nuestro servicio, consulta nuestra sección de <a href="help">ayuda</a>.';
$LANGS['aboutmail'] = 'Siéntete libre de <a href="mailto:contact@vidlii.co">contactarnos</a>.';

/* Community Guidelines */
$LANGS['bvguidelines'] = 'Instrucciones de la comunidad BitView';
$LANGS['cgtitle1'] = 'Respeta a la comunidad de BitView';
$LANGS['cgtitle2'] = "No cruces la línea";
$LANGS['cgtitle3'] = 'Revisamos los videos marcados como inadecuados';
$LANGS['cgtitle4'] = 'BitView es para la comunidad';
$LANGS['cgtitle5'] = 'Consejos sobre las Instrucciones de la comunidad';
$LANGS['cgdesc1'] = "No estamos solicitando el tipo de respeto reservado al clero o a las personas mayores. Lo que queremos decir con respeto es que no abuses del sitio. Todas las funciones nuevas de la comunidad de BitView implican un cierto nivel de confianza. Confiamos en que seas responsable, y millones de usuarios respetan esa confianza, así que conviértete en uno de ellos.";
$LANGS['cgdesc2'] = "Aquí te mostramos algunas normas, de sentido común, que te ayudarán a evitar problemas:";
$LANGS['cgdesc3'] = "Please take these rules seriously and take them to heart. Don't try to look for loopholes or try to lawyer your way around the guidelines — just understand them and try to respect the spirit in which they were created. If you'd like more details, check out our <a href='#tips'>Community Guideline Tips</a>.";
$LANGS['cgdesc4'] = "Sabemos que se trata de un asunto más nuestro que tuyo. Cuando un video se marca como inadecuado, lo revisamos para determinar si infringe los Términos de uso. El sistema no retira automáticamente los videos marcados. Si retiramos tu video después de verlo, puedes dar por hecho que lo hemos retirado con determinación, y debes tomar muy en serio nuestra notificación de advertencia. Respira hondo, lee nuestros Términos de uso invitándote a verlo desde nuestro punto de vista. Si encuentras algún otro video en BitView con las mismas infracciones, márcalo para que también podamos revisarlo. Para obtener más información sobre el procedimiento de aplicación de las Instrucciones de la comunidad y sobre las consecuencias derivadas de su infracción, visita la página del <a href='/help'>Centro de asistencia</a>";
$LANGS['cgdesc5'] = "Recuerda que esta es tu comunidad. Todos y cada uno de los usuarios de BitView hacen del sitio lo que es, por lo que no debes tener reparo alguno en investigar e involucrarte.";
$LANGS['cgdesc6'] = "¡Esto es todo! Gracias por leer las Instrucciones de la Comunidad.";
$LANGS['cgdesc7'] = "¿Quieres obtener más información sobre los límites y las excepciones de las Instrucciones de la comunidad? A continuación te ofrecemos una serie de sugerencias y ejemplos de utilidad:";
$LANGS['rule1'] = "BitView no admite contenido pornográfico o sexual explícito. Si tu video incluye este tipo de contenido, aunque sea un video sobre ti mismo, no lo publiques en BitView. Ten en cuenta que trabajamos estrechamente con las autoridades y que daremos parte de cualquier tipo de explotación de menores. Lee nuestros Consejos de seguridad y preserva tu seguridad en BitView.";
$LANGS['rule2'] = "No publiques videos que muestren cosas malas como abusos a animales, consumo de drogas o fabricación de bombas.";
$LANGS['rule3'] = "No se permite la violencia explícita. Si en tu video aparece alguna persona a la que se esté hiriendo, atacando o humillando, no lo publiques.";
$LANGS['rule4'] = "BitView no es un sitio de shock. No publiques videos asquerosos de accidentes, cadáveres y cosas similares.";
$LANGS['rule5'] = "Respeta los derechos de autor. Sube solamente videos creados por ti o que estés autorizado a usar. Esto supone no subir videos que no hayas creado tú ni utilizar contenido en tus videos cuyos derechos de autor pertenezcan a otra persona (tales como pistas de música o fragmentos de programas protegidos por derechos de autor) ni videos creados por otros usuarios sin las autorizaciones necesarias.";
$LANGS['rule6'] = "Fomentamos la libertad de expresión y defendemos el derecho de todo el mundo a expresar puntos de vista controvertidos. Pero no se aceptan discursos discriminatorios que ataquen o humillen a un grupo debido a su raza u origen étnico, religión, discapacidad, sexo, edad, categoría de veterano u orientación/identidad sexual. Esto también se aplica a la promoción de ideologías extremistas de forma positiva.";
$LANGS['rule7'] = "No se toleran en modo alguno las amenazas, el comportamiento agresivo, el hostigamiento, el acoso, la invasión de la privacidad ni la revelación de información personal de otros miembros. Cualquier persona que incurra en alguno de los comportamientos anteriores puede ser expulsada de forma permanente de BitView.";
$LANGS['rule8'] = "Todo el mundo odia el spam. No incluyas descripciones engañosas, etiquetas, títulos ni texto miniatura para aumentar el número de veces que ven tu video. No está bien publicar mucho contenido sin audiencia específica, repetitivo o no deseado, incluidos comentarios y mensajes privados.";
$LANGS['rule9'] = "Mantengamos el sitio seguro. No intentes acceder a la fuerza a una cuenta que no te pertenece. Además, está prohibido compartir los datos de inicio de sesión de forma pública.";
$LANGS['rule10'] = "Las multicuentas apestan. Queremos que nuestros videos y canales tengan cifras genuinas. No uses más de una cuenta para puntuar videos o/y comentar. Además, está prohibido usar múlitples cuentas para suscribirte a tu canal.";
$LANGS['rule11'] = "¿Has roto alguna de las reglas y tu cuenta ha sido suspendida? No hace falta decir que está prohibido evadir este castigo. Cada cuenta nueva que haya sido creada por un usuario suspendido se eliminará automáticamente.";
$LANGS['cglist1'] = "<b>Disfruta con el sitio.</b> Hay mucho que ver y muchos usuarios creando contenidos asombrosos. ¡Podrías ser uno de ellos! El equipo necesario para hacer video es cada vez más barato y más fácil de utilizar, así que involúcrate, interésate y disfruta.";
$LANGS['cglist2'] = "<b>Expresa lo que piensas a la comunidad.</b> Los comentarios forman parte de la experiencia y, cuando se realizan con respeto, pueden resultar un método estupendo para hacer amigos, hacer comunidad, compartir historias y aprovechar mejor el tiempo que pasas en BitView. Te recomendamos que dejes comentarios, califiques videos, introduzcas tus propias respuestas a videos de tu incumbencia, participes en grupos de interés, etc. Hay mucho que explorar y muchas formas de participar en BitView.";
$LANGS['cglist3'] = '<b>Es posible que no te guste todo lo que veas.</b> Puede que algunos de los videos te resulten ofensivos. Si crees que algún video infringe los Términos de uso, haz clic en "Inadecuado" (la bandera) bajo el video que estás viendo para que el personal de BitView lo revise. Si no es así, haz clic en otra cosa; ¿para qué perder el tiempo viendo videos que no te gustan?';
$LANGS['thebitviewteam'] = "— El equipo de BitView";
$LANGS['cgcat1'] = "Sexo y desnudos";
$LANGS['cgcat2'] = "Discurso de incitación al odio";
$LANGS['cgcat3'] = "Espeluznante y desagradable";
$LANGS['cgcat4'] = "Actos ilegales peligrosos";
$LANGS['cgcat5'] = "Niños";
$LANGS['cgcat6'] = "Copyright";
$LANGS['cgcat7'] = "Privacidad";
$LANGS['cgcat8'] = "Acoso";
$LANGS['cgcat9'] = "Suplantación de identidad";
$LANGS['cgcat10'] = "Amenazas";
$LANGS['cgcat1desc'] = "La mayoría de los desnudos no están permitidos, especialmente si se muestran en un contexto sexual. Por lo general, los videos cuya finalidad es la provocación sexual tienen menos probabilidades de considerarse aceptables para BitView. Existen excepciones aplicables a algunos videos de carácter educativo, documental o científico, pero este tipo de videos sólo son aceptables si su única finalidad es divulgativa, documental o científica y no muestran imágenes explícitas de forma gratuita. Por ejemplo, un documental sobre el cáncer de mama se consideraría un contenido adecuado, pero publicar videos sobre el tema fuera del contexto documental podría no serlo. Esto también aplica para contenido animado.";
$LANGS['cgcat2desc'] = 'El término "discurso de incitación al odio" hace referencia a contenido que fomenta el odio hacia los miembros de un grupo protegido. Por ejemplo, se puede considerar "discurso de incitación al odio" el contenido racista o sexista. A veces, la línea que separa lo que se puede considerar discurso de incitación al odio de lo que no es muy fina. Por ejemplo, por lo general, se considera aceptable realizar críticas sobre un país, pero no es correcto realizar generalizaciones de carácter insultante sobre las personas de una determinada nacionalidad.';
$LANGS['cgcat3desc'] = "El mundo es un lugar peligroso. A veces, se cometen actos violentos y es inevitable que algunos de esos sucesos aparezcan en BitView. Sin embargo, no está bien publicar contenido morboso o violento cuya finalidad principal sea causar un efecto impactante, sensacionalista o irrespetuoso. Si un video resulta particularmente explícito o desagradable, debe estar acompañado de un contexto adecuado o de información adicional que justifique su publicación. Por ejemplo, incluir imágenes de un caballo sacrificado en un video sobre ganadería intensiva podría ser apropiado. Sin embargo, mostrar una sucesión de imágenes inconexas y desagradables de animales sacrificados en un video se podría considerar una exposición gratuita de imágenes si su finalidad es impactar en vez de informar.";
$LANGS['cgcat4desc'] = "Aunque podría parecer una injusticia decir que no se puede mostrar un contenido por la reacción que podría llegar a causar en las personas que lo vean, no admitimos ningún contenido que tenga la finalidad de promover la violencia o de fomentar la comisión de actividades ilegales peligrosas que conlleven un riesgo de muerte o de lesiones físicas graves. No se permite, por tanto, la publicación de videos en los que se ofrezcan, por ejemplo, instrucciones para la fabricación de bombas, consejos para la realización de carreras de coches ilegales o imágenes de formación de asesinos ninjas, ataques de francotiradores o entrenamiento de terroristas. Cualquier imagen de este tipo que se publique deberá ser de carácter educativo o documental y no tener la finalidad de ayudar ni alentar a otras personas a imitar los actos que aparecen representados en ella.";
$LANGS['cgcat5desc'] = "Los videos en los que participan menores de 18 años son especialmente delicados. Estos videos nunca deben mostrar imágenes de contenido sexual o violento. Ten cuidado al publicar contenido en el que aparezcan menores. Si lo que vas a publicar es un video casero o de carácter privado, considera la posibilidad de clasificarlo como video privado para que sólo puedan verlo tus amigos y familiares.";
$LANGS['cgcat6desc'] = "Cuando creas contenido original, posees los derechos de copyright de ese contenido. Del mismo modo, cuando otras personas crean contenido, pueden poseer derechos de copyright sobre él. BitView es una comunidad creativa en la que es esencial que todos los usuarios respeten los derechos de copyright de los demás. Si no estás seguro de si un determinado material puede infringir los derechos de copyright de otra persona, lo más seguro que puedes hacer es publicar un contenido completamente original en el que tanto las imágenes como el sonido estén creados por ti. Si el contenido te pertenece en su totalidad, nunca tendrás que preocuparte por su copyright, ya que te corresponderá a ti. Si has grabado un video de un DVD o de la televisión o lo has descargado online, no lo publiques a menos que dispongas de los permisos necesarios.";
$LANGS['cgcat7desc'] = "Si en un video que has grabado aparecen personas que se pueden identificar fácilmente y que no han concedido permiso para que se las grabe, esas personas pueden presentar una reclamación de privacidad para que se retire el video. En ese caso, recibirás una notificación y podrás editar el video y volver a subirlo antes de que se tomen medidas en relación con la reclamación. Si retiramos el video por razones de privacidad, no subas otro video en el que aparezcan las mismas personas, ya que es posible que las personas en cuestión vuelvan a presentar una reclamación de privacidad o te denuncien por acoso. No publiques información personal de otras personas, incluidos números de teléfono, direcciones, números de tarjetas de crédito y de DNI. Nos tomamos muy en serio la seguridad de nuestros usuarios y suspendemos cualquier cuenta que vulnera la privacidad personal.";
$LANGS['cgcat8desc'] = "Se trata de una cuestión de respeto. BitView es un sitio destinado a compartir y a interactuar con la comunidad de forma respetuosa. Si no estás seguro de si un video o un comentario que has realizado es adecuado, aplica una sencilla regla general: si se trata de algo que no le dirías a alguien a la cara, no lo digas en BitView; y si buscas el ataque, el acoso, la humillación o la suplantación de la identidad de otras personas, vete a otro sitio.";
$LANGS['cgcat9desc'] = "La suplantación de la identidad de otro usuario copiando el diseño exacto de su canal, utilizando un nombre de usuario similar o imitándolo en comentarios, mensajes de correo electrónico o videos se considera acoso. Si deseas mantener tu cuenta, evita la participación en cualquier tipo de actividad de acoso o de suplantación de identidad en el sitio.";
$LANGS['cgcat10desc'] = "Los usuarios no deben sentirse amenazados en modo alguno al visitar BitView. No publiques comentarios amenazadores sobre los videos de otras personas.";

/* Contests */
$LANGS['monthlycontest'] = "Concurso mensual";
$LANGS['monthlycontestschedule'] = "Programación del concurso mensual";
$LANGS['whatisit'] = "¿De qué se trata?";
$LANGS['thismonthcontest'] = "Este mes";
$LANGS['lastmonthwinners'] = "Ganadores del mes pasado";
$LANGS['howtoenter'] = "¿Cómo participo?";
$LANGS['whowins'] = "¿Quién gana?";
$LANGS['whowinsdesc'] = "El ganador será elegido al final de cada mes por el equipo de BitView.";
$LANGS['theprize'] = "¿Qué gano?";
$LANGS['theprizedesc'] = "La fama, fortuna, y la envidia de todos los que te vean.";
$LANGS['contestsuggestion'] = '¿Tienes alguna idea para un concurso mensual? <a href="mailto:contact@vidlii.co">Cuéntanosla</a>.';

/* Help */
$LANGS['q1'] = 'P: ¿Cómo comparto mis videos y los enlazo a mi página web?';
$LANGS['a1'] = 'R: <a href="/sharing">Cómo compartir tus videos y enlazarlos</a>';
$LANGS['q2'] = 'P: ¿Qué tipo de videos puedo subir?';
$LANGS['a2'] = 'R: Puedes subir cualquier tipo de video casero que quieras compartir al mundo. No permitimos desnudez y tu video debe de ser apropiado para todas las edades.
<br/>
<br/>
Aun así, ¡tienes mucho para crear! ¿Tienes un <a href="results?search=perro&t=Search+Videos">perro</a> o un <a href="/results?search=gato&t=Search+Videos">gato</a>? ¿Te has ido de vacaciones a <a href="/results?search=mexico&t=Search+Videos">México</a>? ¿Vives en <a href="/results?search=netherlands&t=Search+Videos">Paises Bajos</a>?
<br/>
<br/>
Estos son algunos ejemplos de videos que nuestros usuarios suben. Al fin y al cabo, eres tú el que lo sabe bien. ¿Qué te gustaría a <i>ti</i> capturar en video?';
$LANGS['q3'] = 'P: ¿Qué duración máxima deben tener mis videos?';
$LANGS['a3'] = 'R: El video debe durar menos de 15 minutos y pesar menos de 2 GB (100 MB si tienes un navegador antiguo).';
$LANGS['q4'] = 'P: ¿En qué formato puedo subir mi video?';
$LANGS['a4'] = 'R: BitView acepta videos de la mayoría de las cámaras digitales y teléfonos móviles en formato .wmv, .avi, .mov, .mpg y .mp4.';
$LANGS['q5'] = 'P: ¿Cómo puedo mejorar mis videos?';
$LANGS['a5'] = 'R: Recomendamos que edites tus videos con programas como <a href="https://windows-movie-maker-vista.en.softonic.com/" target="_blank">Windows Movie Maker</a> (incluido con Windows), o <a href="https://www.apple.com/lae/imovie/" target="_blank">Apple iMovie</a>. Con estos programas puedes editar tus videos, agregar música, entre otros.';
$LANGS['q6'] = 'P: ¿Mantengo todos los derechos de autor y otros derechos legales de mis videos?';
$LANGS['a6'] = 'R: Por supuesto. Tú conservas los derechos de autor de tu contenido. BitView no asume ningún derecho de autor sobre tu material.';
$LANGS['q7'] = 'P: ¿Qué políticas tenéis sobre las infracciones de derechos de autor?';
$LANGS['a7'] = 'R: BitView respeta los derechos de autor y solo permite subidas de videos de personas que poseen todos los derechos necesarios para el material subido. Nuestra política es responder ante cualquier denuncia de infracción de derechos de autor que cumplan con la Ley de Derechos de Autor de la Era Digital (DMCA). Si recibimos una denuncia o tenemos alguna razón para creer que tu contenido infringe los derechos de autor de un tercero, tu video podrá ser retirado de BitView y tu cuenta podría ser suspendida.';
$LANGS['q8'] = 'P: ¿Cómo denuncio una infracción de derechos de autor?';
$LANGS['a8'] = 'R: Si crees que otra persona ha subido tu contenido protegido por los derechos de autor sin tu permiso, te recomendamos que contactes directamente con esa persona para resolver cualquier problema. También puedes contactar nuestro equipo a través de este <a href="mailto:contact@vidlii.co">correo electrónico</a>.';
$LANGS['q9'] = 'P: ¿Qué hago si me acusan fraudulentamente de infringir los derechos de autor?';
$LANGS['a9'] = 'R: Te haremos saber si has recibido alguna reclamación de derechos de autor en alguno de tus videos que hayas subido a BitView. Te daremos la oportunidad de responder adecuadamente.';
$LANGS['q10'] = 'P: ¿Cómo hacéis para prevenir que aparezca el contenido que infringa las normas?';
$LANGS['a10'] = 'R: Hacemos una revisión preliminar de forma manual y automática. Aunque intentamos detectar y eliminar los video que incumplan nuestras reglas, nos centramos en eliminar contenido para adultos o infracciones de copyright, y no es perfecto. De todas fromas, recomendamos que nuestros usuarios nos notifiquen cuando encuentran contenido infractor: tenemos un proceso de revisión de contenido denunciado y respondemos ante peticiones bajo la Ley de Derechos de Autor de la Era Digital (DMCA).';
$LANGS['q11'] = 'P: ¿Tenéis un servidor de Discord o Twitter?';
$LANGS['a11'] = 'R: Puedes unirte a nuestro servidor pinchando <a href="https://discord.gg/wgGaqCmwuQ">aquí</a>, y puedes seguirnos en Twitter pinchando <a href="https://twitter.com/bitview_">aquí</a>.';
$LANGS['q12'] = 'P: Estoy usando un navegador antiguo y no puedo ver videos. ¿Qué puedo hacer?';
$LANGS['activate'] = 'Activar';
$LANGS['deactivate'] = 'Desactivar';
$LANGS['flashdisclaimer'] = "<b>Nota:</b> Ofrecemos el reproductor de BitView que usa Adobe Flash como una solución de compatibilidad. Si tu navegador soporta HTML5, no actives esta opción.";

/* BitView on your site */
$LANGS['bvsitetitle1'] = "Los básicos";
$LANGS['bvsitetitle2'] = "API y participación del usuario";
$LANGS['bvsitedesc1'] = 'Cualquier presencia que tengas en Internet (un sitio web extenso, un blog, una página de red social o prácticamente cualquier otra cosa), existen muchas formas de integrar a BitView en ella. Desde simples inserciones de videos hasta nuestras API completas, puedes integrar videos en todos los niveles de conocimiento técnico.';
$LANGS['bvsitedesc2'] = 'Incorporar BitView a tu sitio no es sólo agregar algunos de los millones de videos disponibles en BitView. Mantiene interesados a tus visitantes y permite la expresión personal y la interacción con uno de sus servicios favoritos. E incorpora a tu sitio, blog o página a la comunidad de videos de BitView, una red internacional de usuarios, creadores y sitios conectados a través de la recopilación más extensa de videos en Internet.';
$LANGS['bvsitedesc3'] = "A continuación hemos resaltado algunas maneras típicas de integrar contenido de video; sólo debes hacer clic en la flecha junto a la pregunta para obtener la respuesta. Si tienes alguna duda o sugerencia, o algún proyecto que deseas que conozcamos, deberás dejar un mensaje en nuestro <a href='https://discord.gg/wgGaqCmwuQ'>servidor de Discord</a>.";
$LANGS['bvsitesectiontitle1'] = "¿Cómo puedo agregar un video a mi blog o página web?";
$LANGS['bvsitesectiontitle2'] = "¿Cómo puedo agregar un video a mi página de red social?";
$LANGS['bvsitesectiontitle3'] = "Trabajo para un blog o una compañía web importante. ¿Cómo puede un video incrementar la participación del usuario en nuestro sitio?";
$LANGS['bvsitesectiontitle4'] = "Tenemos un sitio y contamos con nuestros propios videos. ¿Podemos publicarlos en nuestro sitio por medio de BitView?";
$LANGS['bvsitesection1desc1'] = 'Deberás editar el HTML de la entrada o página de tu blog, lo cual debería ser relativamente sencillo. En Blogger, por ejemplo, solo debes hacer clic en la pestaña "Editar HTML".';
$LANGS['bvsitesection1desc2'] = 'A continuación, accede al video que desees y busca el cuadro "Insertar" en la sección "Acerca de este video". Al copiar el código HTML que se encuentra en tu sitio web, se creará un reproductor insertado; el video se reproducirá dentro de tu sitio cuando el usuario haga clic en el botón "Reproducir".';
$LANGS['bvsitesection1desc3'] = 'Puedes ajustar el reproductor al editar los campos del <em>ancho="425"</em> y la <em>altura="350"</em> del objeto tanto al comienzo como al final del código de reproductor insertado. Asegúrate de que los tamaños que elijas tengan la misma proporción que los números predeterminados, de modo que el video no se extienda y deforme; sólo multiplica el ancho por 0.8235 para obtener la altura.';
$LANGS['bvsitesection2desc1'] = "Agregar videos a tus perfiles en redes sociales como SpaceHey es una excelente manera de compartir tus videos o favoritos con amigos. O, si estás promocionando algo (como tu banda) en SpaceHey, los videos ayudarán a atraer visitantes a tu página, quienes entonces podrán compartir el vínculo con sus amigos. Los sitios de redes sociales poseen maneras similares de agregar videos, por lo tanto utilizaremos SpaceHey como ejemplo.";
$LANGS['bvsitesection2desc2'] = 'Inicia sesión en tu perfil de MySpace, luego haz clic en el botón "Editar perfil".';
$LANGS['bvsitesection2desc3'] = 'A continuación, accede al video que desees y busca el cuadro "Insertar" en la sección "Acerca de este video". Al copiar el código HTML que se encuentra en tu sitio web, se creará un reproductor insertado.';
$LANGS['bvsitesection2desc4'] = 'Puedes ajustar el reproductor al editar los campos del <em>ancho="425"</em> y la <em>altura="350"</em> del objeto tanto al comienzo como al final del código de reproductor insertado. Asegúrate de que los tamaños que elijas tengan la misma proporción que los números predeterminados, de modo que el video no se extienda y deforme; sólo multiplica el ancho por 0.8235 para obtener la altura.';
$LANGS['bvsitesection2desc5'] = 'Haz clic en "Vista previa" y luego en "Enviar".';
$LANGS['bvsitesection3desc1'] = "Un video es mucho más cautivante que un texto. Atrae a más usuarios y los mantiene en el sitio durante más tiempo. BitView dispone de un gran depósito de contenidos de videos de Internet junto con las herramientas de búsqueda, reproducción y API para facilitar la función de agregar videos.";
$LANGS['bvsitesection3desc2'] = "Si deseas aumentar la participación, prueba utilizar el video para iniciar un debate o hacer un comentario con más contexto para tus usuarios:";
$LANGS['bvsitesection4desc1'] = "Construir de forma gratuita tu propio sitio con tus videos es muy fácil. Lo único que necesitas hacer es, primero, subir tus videos a BitView. Es gratuito y nosotros cubrimos los gastos de almacenamiento y transmisión. No sólo es una excelente manera de incrementar la participación del usuario en tu sitio, sino que también es muy sencillo, además de gratuito.";
$LANGS['bvsitesection4desc2'] = "Cuando hayas subido los videos, así puedes regresarlos a tu sitio:";
$LANGS['bvsitesection4desc3'] = '<b>Inserta videos de a uno:</b> Accede al video que deseas poner en tu sitio web y busca el cuadro “Insertar” debajo del reproductor de video. Al copiar el código HTML que se encuentra en tu blog, se creará un reproductor insertado. El video se reproducirá dentro de tu sitio cuando el usuario haga clic en el botón "Reproducir".';

/* RSS Feeds */
$LANGS['rsstitle1'] = "¿Qué son los canales RSS?";
$LANGS['rsstitle2'] = "Cómo acceder a los canales RSS";
$LANGS['rsstitle3'] = "Cómo suscribirse a los canales RSS de BitView";
$LANGS['rssdesc1'] = "Really Simple Syndication (RSS) es un formato basado en XML que se utiliza para la sindicación y distribución de contenido. Si te suscribes a canales RSS, podrás recibir información personalizada y actualizada de tus fuentes de contenido en línea favoritas sin tener que comprobar habitualmente el sitio para ver si hay actualizaciones.";
$LANGS['rssdesc2'] = "Los lectores de noticias que muestran canales RSS en los sitios web que has especificado—verifican los canales RSS a los que te has suscrito y muestran los elementos nuevos de cada canal. Puedes descargar las aplicaciones de lector de noticias en tu computadora y aquí también encontrarás varios lectores de noticias populares basados en la web disponibles, como Google Reader y Bloglines. Algunas aplicaciones de navegadores web y correo electrónico también poseen funciones RSS integradas.";
$LANGS['rssdesc3'] = "Puedes ver una lista de varios lectores de noticias disponibles en <a href='http://es.wikipedia.org/wiki/Agregador'>Wikipedia</a>."; //Use your language's Wikipedia article if possible
$LANGS['rssdesc4'] = "BitView ofrece varios canales RSS para grupos de videos divididos en categorías (por ejemplo, subidos recientemente, más vistos, etc.), al igual que canales personalizados para usuarios y etiquetas.";
$LANGS['rssdesc5'] = 'Para suscribirte a grupos de videos divididos en categorías, simplemente accede a la categoría que deseas (por ejemplo, "<a href="/browse">Los más vistos del día</a>"). Luego haz clic en el botón naranja "RSS". Esto debe activar el lector de noticias que elegiste para agregar la suscripción.';
$LANGS['rssdesc6'] = 'Si tu navegador posee funciones RSS, podrás agregar el canal aquí. El comando varía según los navegadores, pero generalmente se puede encontrar en los menús "Archivo" o "Marcadores", y su nombre será similar a "Subscríbete a esta página" o "Nuevo marcador en directo".';
$LANGS['rssthispage'] = "Incluir esta página en RSS";

/* TestView */
$LANGS['testviewdesc'] = 'Te damos la bienvenida a TestView, nuestra "incubadora" de ideas. Aquí es donde los desarrolladores e ingenieros de BitView prueban las recetas y las mezclas que aún están un poco crudas. Estás invitado a comentarnos qué te parecen.';
$LANGS['flashvideo'] = "Video Flash";
$LANGS['flashvideodesc'] = "¿Tu navegador no soporta HTML5? ¡No te preocupes! Prueba nuestro reproductor Flash.";
$LANGS['feather'] = "Light";
$LANGS['featherdesc'] = "Ver videos de BitView en una página de latencia muy baja.";
$LANGS['tryitout'] = "Pruébalo";
$LANGS['disabletest'] = "Deshabilitar";

/* Footer */
$LANGS['youraccount'] = 'Tu cuenta';
$LANGS['inbox'] = 'Bandeja de entrada';
$LANGS['footmore'] = 'más...';
$LANGS['helpinfo'] = 'Ayuda';
$LANGS['helpcenter'] = 'Obtén ayuda';
$LANGS['ourtwitter'] = 'Nuestro Twitter';
$LANGS['ourdiscord'] = 'Nuestro Discord';
$LANGS['guidelines'] = 'Instrucciones de la comunidad';
$LANGS['partnerships'] = 'Asociaciones';
$LANGS['terms'] = 'Términos de uso';
$LANGS['privacypolicy'] = 'Política de privacidad';
$LANGS['currentlanguage'] = 'Idioma actual';
$LANGS['showlanguages'] = 'Mostrar idiomas';
$LANGS['setlanguagepref'] = 'Establecer preferencia de idioma';
$LANGS['programs'] = 'Programas';
$LANGS['developers'] = 'Desarrolladores';
$LANGS['bitviewblog'] = 'Blog de BitView';
$LANGS['policy'] = 'Política';
$LANGS['discover'] = 'Descubrir';
$LANGS['bvphone'] = 'BitView en tu teléfono';
$LANGS['bvsite'] = 'BitView en tu sitio';
$LANGS['bvrss'] = 'Canales RSS de BitView';
$LANGS['mobile'] = 'Móvil';
?>
