<?php
/* General stuff */
$LANGS['language'] = 'Français';
$LANGS['languageenglish'] = 'French';
$LANGS['languagecode'] = 'fr_FR.UTF-8';
$LANGS['languagechange'] = 'La langue a bien été changée en français.';
$LANGS['numberformat'] = 1; /* If your language uses comma separators (example: 1,000,000), value will be 1. If it uses dots (example: 1.000.000) or doesn't use separators, value will be 0.*/

/* Language window */
$LANGS['welcometobitview'] = 'Bienvenue sur BitView !';
$LANGS['languagesuggestion'] = 'Langue suggérée (nous avons définis ceci dans vos préférences) :';
// $LANGS['languagesuggestiondesc1'] = 'To change your language preference, please use the language selector in the footer (end of the page).';
$LANGS['languagesuggestiondesc1'] = 'Pour changer votre préférence de langue, utilisez le sélécteur de langue à la fin de la page.';
$LANGS['languagesuggestiondesc2'] = 'Cliquez sur "OK" pour accepter cette préférence, ou cliquez sur "Annuler" pour voir la page en Anglais.';

/* Time, dates, etc */
$LANGS['second'] = 'seconde';
$LANGS['minute'] = 'minute';
$LANGS['hour'] = 'heure';
$LANGS['day'] = 'jour';
$LANGS['week'] = 'semaine';
$LANGS['month'] = 'mois';
$LANGS['year'] = 'an';
$LANGS['seconds'] = 'secondes';
$LANGS['minutes'] = 'minutes';
$LANGS['hours'] = 'heures';
$LANGS['days'] = 'jours';
$LANGS['weeks'] = 'semaines';
$LANGS['months'] = 'mois';
$LANGS['years'] = 'ans';
$LANGS['ago1'] = 'il y a '; /* Explanation: Text before "x seconds/minutes/hours..." Example: "hace (1 día)" in Spanish. If your language doesn't use this, leave it empty like this: ''*/
$LANGS['ago2'] = ''; /* Explanation: ago2 -> Text after "x seconds/minutes/hours..." Example: "(1 day) ago" in English, "(1 anno) fa" in Italian. If your language doesn't use this, leave it empty like this: ''*/
$LANGS['january'] = 'Janvier';
$LANGS['february'] = 'Février';
$LANGS['march'] = 'Mars';
$LANGS['april'] = 'Avril';
$LANGS['may'] = 'Mai';
$LANGS['june'] = 'Juin';
$LANGS['july'] = 'Juillet';
$LANGS['august'] = 'Août';
$LANGS['september'] = 'Septembre';
$LANGS['october'] = 'Octobre';
$LANGS['november'] = 'Novembre';
$LANGS['december'] = 'Décembre';

// je sais pas vraiment quoi faire ici
$LANGS['shorttimeformat'] = '%b %e, %Y';
$LANGS['videotimeformat'] = '%b %e, %Y';
$LANGS['longtimeformat'] = '%B %e, %Y';
$LANGS['timehourformat'] = '%b %e, %Y %I:%M %p';
$LANGS['myvideostimeformat'] = '%A, %b %e %Y, %I:%M:%S %p';
$LANGS['blogpostformat'] = '%A, %B %e, %Y';
$LANGS['timenumberformat'] = 'd.m.Y';

/* Header */
$LANGS['home'] = 'Accueil';
$LANGS['videos'] = 'Vidéos';
$LANGS['channels'] = 'Chaînes';
$LANGS['community'] = 'Communauté';
$LANGS['search'] = 'Chercher';
$LANGS['login'] = 'Se connecter';
$LANGS['or'] = 'ou';
$LANGS['signup'] = 'Créer un compte';
$LANGS['logout'] = 'Se déconnecter';
$LANGS['upload'] = 'Mettre en ligne';
$LANGS['subscriptions'] = 'Abonnements';
$LANGS['history'] = 'Historique';
$LANGS['account'] = 'Compte';
$LANGS['myvideos'] = 'Mes vidéos';
$LANGS['favorites'] = 'Favoris';
$LANGS['playlists'] = 'Playlists';
$LANGS['help'] = 'Aide';
$LANGS['suggestions'] = 'Suggestions';
$LANGS['quicklist'] = 'Liste rapide';

/* Homepage */
$LANGS['viewall'] = 'tout voir';
$LANGS['videoviews'] = 'vues';
$LANGS['beingwatched'] = 'Vidéos regardées en ce moment';
$LANGS['featured'] = 'Vidéos à la une';
$LANGS['recommendedforyou'] = 'Recommended for You';
$LANGS['mostpopular'] = 'Les plus populaires';
$LANGS['inboxstats'] = 'Messagerie & Statistiques';
$LANGS['profilesettings'] = 'paramètres du compte';
$LANGS['messages'] = 'Messages';
$LANGS['message'] = 'Message';
$LANGS['comments'] = 'Commentaires';
$LANGS['comment'] = 'Commentaire';
$LANGS['friendinvites'] = 'Invitations d\'amis';
$LANGS['friendinvite'] = 'Invitation d\'un ami';
$LANGS['subscribers'] = 'Abonnés';
$LANGS['subscriber'] = 'Abonné';
$LANGS['totalviews'] = 'Vues totals';
$LANGS['sendmessage'] = 'envoyer le message';
$LANGS['whatsnew'] = "Quoi de neuf, docteur ?";
$LANGS['readmore'] = 'Tout lire dans le Blog';
$LANGS['videocontest'] = 'Concours vidéo';
$LANGS['joincontest'] = 'Rejoindre le concours !';
$LANGS['personalize'] = 'Souhaitez-vous personnaliser cette page d\'accueil ?';
$LANGS['signinnow'] = '<a href="/login">Connectez-vous</a> ou <a href="/signup">Inscrivez-vous</a> maintenant !';
$LANGS['nowconverting'] = "Cette vidéo est en conversion, veuillez patienter...";
$LANGS['modules'] = "Ajouter / Supprimer des Modules";
$LANGS['friendactivity'] = "Activité des Amis";
$LANGS['customizehomepage'] = "Personnaliser la Page d'Accueil";
$LANGS['customizethehomepage'] = "Personnaliser la Page d'Accueil";
$LANGS['customizehomepagedesc'] = "Sélectionnez les modules que vous souhaitez voir sur votre page d'accueil personnalisée.";
$LANGS['displaypreferences'] = "Préférences d'Affichage";
$LANGS['thefeed'] = "Le Fil d'Actualité";
$LANGS['thefeeddesc'] = "Regroupez tous vos modules dans un seul fil d'actualité.";
$LANGS['friendactivitytitle'] = "Activité des Amis - Les gens peuvent-ils voir ce que je fais ?";
$LANGS['friendactivitydesc'] = "Cette section montre à vos amis confirmés les actions que vous diffusez publiquement dans votre historique d'activité récente. Par exemple, si vous ajoutez une vidéo à vos favoris, cette nouvelle vidéo favorite peut apparaître dans la boîte d'activité récente de votre chaîne, ainsi que sur la page d'accueil de vos amis.";
$LANGS['feedfeatured'] = "Vidéo en Vedette";
$LANGS['feedbeingwatched'] = "Vidéo Actuellement Visionnée";
$LANGS['feedrecommended'] = "Vidéo Recommandée";
$LANGS['nosubscriptions'] = "Vous n'avez encore souscrit à aucune chaîne.";
$LANGS['nosubscriptionsdesc'] = "Lorsque vous ajoutez de nouvelles souscriptions, nous afficherons leurs téléchargements sur cette page.";
$LANGS['nofriendactivity'] = "Vos amis n'ont pas été actifs récemment.";
$LANGS['nofriendactivitydesc'] = "Vous pouvez essayer d'ajouter quelques amis. Ensuite, nous afficherons leur activité sur cette page.";
$LANGS['homeediting'] = "Édition";
$LANGS['homedisplay'] = "Afficher comme";
$LANGS['homerows'] = "Nombre de lignes à afficher";
$LANGS['gridview'] = "Vue en Grille";
$LANGS['listview'] = "Vue en Liste";

/* Page title */
$LANGS['homepretitle'] = "BitView de "; /* Explanation: Use if "BitView" goes before the username. Example: "BitView de username" in Spanish. If your language doesn't use this, leave it empty like this: ''*/
$LANGS['homeposttitle'] = ""; /* Explanation: Use if "BitView" goes after the username. Example: "username's BitView" in English. If your language doesn't use this, leave it empty like this: '' */
$LANGS['chpretitle'] = "La chaîne de "; /* Explanation: Use if "channel" goes before the username. Example: "Canal de username" in Spanish. If your language doesn't use this, leave it empty like this: ''*/
$LANGS['chposttitle'] = ""; /* Explanation: Use if "channel" goes after the username. Example: "username's Channel" in English. If your language doesn't use this, leave it empty like this: '' */
$LANGS['signintitle'] = "Se connecter";
$LANGS['historytitle'] = "Historique de visionnage";
$LANGS['favtitle'] = "Favoris";
$LANGS['pltitle'] = "Playlists";
$LANGS['partnerprogram'] = "Programme de partenaires";

/* Notifications */
$LANGS['searcherror'] = 'Votre recherche doit-être d\'au moins 2 caractères !';
$LANGS['addvideoplaylist1'] = "Vous avez ajouté";
$LANGS['addvideoplaylist2'] = 'vidéos dans votre playlist !';
$LANGS['addfavorite1'] = "Vous avez favori";
$LANGS['addfavorite2'] = 'vidéos !';
$LANGS['groupdoesnotexist'] = "Ce groupe est inexistant !";
$LANGS['uploaddisabled'] = 'La mise en ligne a été désactivée pour maintenance.';
//$LANGS['10vidsday'] = 'You can not upload more than 10 videos per day! Please try uploading tomorrow.';
$LANGS['10vidsday'] = 'Vous ne pouvez pas mettre en ligne plus de 10 vidéos par jour ! Essayez demain.';
$LANGS['3mins'] = 'Attendez 3 minutes avant de mettre une nouvelle vidéo en ligne !';
$LANGS['backgroundsuccess'] = 'L\'arrière-plan a été téléchargé avec succès !';
//$LANGS['backgrounderror'] = 'Background image must be under 2MB and be an image file!';
$LANGS['backgrounderror'] = 'L\'image d\'arrière-plan doit être en dessous de 2 mo et doit être un fichier d\'image !';
$LANGS['backgrounddeleted'] = 'L\'arrière-plan a bien été supprimé !';
//$LANGS['bannersuccess'] = 'Banner has been successfully uploaded!';
$LANGS['bannersuccess'] = 'La bannière a été téléchargée avec succès !';
$LANGS['bannererror'] = 'L\'image de bannière doit être en dessous de 2 mo et doit être un fichier d\'image !';
$LANGS['bannerdeleted'] = 'Votre bannière a bien été supprimée !';
$LANGS['minibannersuccess'] = 'La mini-bannière a été téléchargée avec succès !';
$LANGS['minibannererror'] = 'L\'image de mini-bannière doit être en dessous de 2 mo et doit être un fichier d\'image !';
$LANGS['minibannerdeleted'] = 'Votre mini-bannière a bien été supprimée !';
$LANGS['sideimagesuccess'] = 'L\'image latérale a été téléchargée avec succès !';
$LANGS['sideimageerror'] = 'L\'image latérale doit être en dessous de 2 mo et doit être un fichier d\'image !';
$LANGS['sideimagedeleted'] = 'L\'image latérale a bien été supprimée !';
$LANGS['avatarsuccess'] = 'L\'avatar a été téléchargé avec succès !';
$LANGS['avatarerror'] = 'L\'avatar doit être en dessous de 1 mo et doit être un fichier d\'image !';
$LANGS['avatardeleted'] = '"L\'avatar a bien été supprimé !';
$LANGS['changessaved'] = 'Les modifications ont été enregistrées avec succès !';
$LANGS['profilesdisabled'] = 'Les profils ont étés désactivés pour maintenance.';
$LANGS['bulletinposted'] = 'Le bulletin a été publié !';
$LANGS['channelcommentsent'] = 'Le commentaire de chaîne a été publié !';
$LANGS['somethingwentwrong'] = 'Quelque chose s\'est mal passé !';
$LANGS['replysubmitted'] = 'La réponse a été publié !';
$LANGS['onlyonecomment'] = 'Vous ne pouvez publier qu\'un seul commentaire !';
$LANGS['vpnbrowser'] = "Vous ne pouvez pas utiliser un VPN pour créer un compte BitView !";
$LANGS['torbrowser'] = "Vous ne pouvez pas utiliser TOR pour créer un compte BitView !";
$LANGS['captchaincorrect'] = "Vous n'avez pas entré le code correctement.";
$LANGS['toomanyaccounts'] = 'Vous avez trop de comptes !';
$LANGS['banned2times'] = "Vous avez déjà été banni deux fois. Vous ne pouvez pas créer plus de comptes !";
$LANGS['nohistory'] = "Vous n'avez pas encore regardé de vidéos au cours de cette session !";
$LANGS['historycleared'] = 'Votre historique de visionnage a été vidé.';
//$LANGS['watchdisabled'] = 'Video watching has been disabled for maintenance.';
$LANGS['watchdisabled'] = 'Le visionnage de vidéos est désactivé pour maintenance.';
$LANGS['videonotexist'] = 'Cette vidéo n\'existe pas ou a été supprimée en raison d\'une violation des conditions d\'utilisation.';
$LANGS['responseerror'] = 'Quelque chose s\'est mal passé avec votre vidéo-réponse ! Veuillez revérifier l\'URL.';
$LANGS['responseexist'] = 'La vidéo a déjà été demandée !';
$LANGS['responseadded'] = 'Vidéo-réponse ajoutée avec succès !';
$LANGS['responseaccepted'] = 'Nouvelle vidéo-réponse acceptée !';
$LANGS['60secscomment'] = 'Veuillez patienter 60 secondes avant d\'ajouter un nouveau commentaire !';
$LANGS['plnotexist'] = "Cette playlist n'existe pas !";
$LANGS['positionnotexist'] = "Cette position n'existe pas !";
$LANGS['positionchanged'] = "La position de la vidéo a été changée !";
$LANGS['invalidurl'] = 'URL invalide !';
$LANGS['videopladded'] = 'Vidéo ajoutée avec succès !';
$LANGS['videoalreadyinpl'] = 'Cette vidéo est déjà dans cette playlist !';
$LANGS['plvideoremoved'] = 'Cette vidéo a été supprimée !';
$LANGS['plinfochanged'] = 'Les informations de la playlist ont été modifiées avec succès !';
$LANGS['pltitleneeded'] = 'Vous devez définir un titre pour la playlist !';
$LANGS['flashenabled'] = 'Adobe Flash Player activé !';
$LANGS['flashdisabled'] = 'Adobe Flash Player desactivé !';
$LANGS['messagesent'] = 'Le message a été envoyé avec succès !';
$LANGS['usernotexist'] = "Cet utilisateur n'existe pas !";
$LANGS['nocriteria'] = "Vous ne remplissez pas les critères requis !";
$LANGS['alreadypartner'] = 'Vous avez déjà été accepté dans le programme partenaire !';
$LANGS['alreadyapplied'] = 'Vous avez déjà postulé !';
$LANGS['applicationsent'] = 'Votre candidature a été soumise !';
$LANGS['joinedgroup'] = 'Vous avez rejoint le groupe avec succès !';
$LANGS['leftgroup'] = 'Vous avez quitté le groupe avec succès !';
$LANGS['grouprequest'] = 'Vous avez envoyé une demande de groupe avec succès ! Maintenant, vous devez attendre qu\'il soit accepté.';
$LANGS['groupdeleted'] = 'Le groupe a été supprimé avec succès !';
$LANGS['groupvideoadded'] = 'La vidéo a été soumise !';
$LANGS['groupvideoalreadyadded'] = 'Vous avez déjà soumis cette vidéo !';
$LANGS['groupvideonotowned'] = "Vous n'êtes pas propriétaire de cette vidéo !";
$LANGS['3groups'] = 'Vous ne pouvez posséder que 3 groupes au maximum !';
$LANGS['groupnameempty'] = 'Le nom du groupe ne peut pas être vide !';
$LANGS['groupdescempty'] = 'La description du groupe ne peut pas être vide !';
$LANGS['groupnoimage'] = 'Vous devez télécharger une image pour votre groupe !';
$LANGS['groupimageerror'] = 'Les images de groupe doivent avoir une taille inférieure à 1 Mo et être un fichier image !';
$LANGS['groupcreated'] = 'Le groupe a été créé avec succès !';
$LANGS['urlnotvalid'] = "Cette URL de vidéo n'est pas valide !";
$LANGS['discussiondeleted'] = 'Le sujet a été supprimé avec succès !';
$LANGS['videodeleted'] = 'La vidéo a été supprimée avec succès !';
$LANGS['pldeleted'] = 'La playlist a été supprimée avec succès !';
$LANGS['invitesent'] = "L'invitation d'ami a été envoyée avec succès !";
$LANGS['descriptionchanged'] = 'La description a été modifiée !';
$LANGS['emptymessage'] = 'Vous ne pouvez pas envoyer de messages vides !';
$LANGS['styleupdated'] = 'Le style du groupe a été mis à jour avec succès !';
$LANGS['imageupdated'] = "L'image du groupe a été mise à jour avec succès !";
$LANGS['plcreated'] = 'La playlist a été créée avec succès !';
$LANGS['discussiontitle2chars'] = 'Le titre doit comporter plus de 2 caractères !';
$LANGS['discussiondesc10chars'] = 'Les descriptions doivent comporter plus de 10 caractères !';
$LANGS['5discussionsday'] = 'Vous ne pouvez créer que 5 discussions par jour !';
$LANGS['discussionsuccess'] = 'La discussion a été créée avec succès !';
$LANGS['memberaccepted1'] = '';
$LANGS['memberaccepted2'] = 'a été accepté avec succès !';
$LANGS['memberdeclined1'] = '';
$LANGS['memberdeclined2'] = 'a été refusé avec succès !';
$LANGS['videoaccepted'] = 'La vidéo a été acceptée avec succès !';
$LANGS['bulletindeleted'] = 'Le bulletin a été supprimé avec succès !';
$LANGS['messagedeleted'] = 'Le message a été supprimé avec succès !';
$LANGS['responsedeleted'] = 'La réponse vidéo a été supprimée avec succès !';
$LANGS['flagmod'] = "Vous ne pouvez pas signaler un utilisateur qui a des permissions de modérateur !";
$LANGS['userflagged'] = 'Le signalement a été soumis !';
$LANGS['discussionreplysubmitted'] = 'La réponse a été envoyée avec succès !';
$LANGS['discussionreplyempty'] = 'Une réponse ne peut pas être vide !';

$LANGS['moreinfo'] = 'plus d\'informations';
$LANGS['lessinfo'] = 'moins d\'informations';
$LANGS['category'] = 'Catégorie';
$LANGS['recordedon'] = 'Enregistré le';
$LANGS['location'] = 'Lieu';
$LANGS['tags'] = 'Tags';
$LANGS['embed'] = 'Intégrer';
$LANGS['partnervideo'] = 'Vidéo du partenaire';
$LANGS['subscribe'] = 'S\'abonner';
$LANGS['unsubscribe'] = 'Se désabonner';
$LANGS['nodesc'] = 'Pas de description...';
$LANGS['logintosub'] = 'Veuillez vous connecter pour vous abonner !';
$LANGS['logintosubbox'] = 'Vous voulez vous abonner ?';
$LANGS['subyourself'] = 'Vous ne pouvez pas vous abonner à vous-même !';
$LANGS['videoowner'] = 'Options du propriétaire de la vidéo';
$LANGS['editvideo'] = 'Modifier la vidéo';
$LANGS['insight'] = 'Statistiques';
$LANGS['morefrom'] = 'Plus de :';
$LANGS['relatedvideos'] = 'Vidéos similaires';
$LANGS['novideosfound'] = 'Aucune vidéo trouvée...';
$LANGS['morevideos'] = 'Voir toutes les vidéos';
$LANGS['changeplayersize'] = 'Modifier la taille du lecteur';
$LANGS['newwindow'] = 'Regarder cette vidéo dans une nouvelle fenêtre';
$LANGS['featuredtext'] = 'Cette vidéo a été mise en avant. Vous voulez voir plus de vidéos mises en avant ? <a href="/browse?t=2">Cliquez ici</a>.';
$LANGS['ratings'] = 'évaluations';
$LANGS['rating'] = 'évaluation';
$LANGS['favorite'] = 'Favori';
$LANGS['addtofav'] = 'Ajouter aux favoris';
$LANGS['removefav'] = 'Supprimer des favoris';
$LANGS['favadded'] = 'Cette vidéo a été <strong>ajoutée</strong> à vos <a href="/my_favorites">favoris</a>.';
$LANGS['favremoved'] = 'Cette vidéo a été <strong>supprimée</strong> de vos <a href="/my_favorites">favoris</a>.';
$LANGS['undo'] = 'Annuler';
$LANGS['thanksforrating'] = 'Merci d\'avoir évalué !';
$LANGS['playlistdesc'] = 'Pour ajouter une nouvelle vidéo à votre playlist, rendez-vous sur la page <a href="/my_playlists">"Mes Playlists"</a>.';
$LANGS['addtoplaylist'] = 'Ajouter à la playlist';
$LANGS['addtoplaylistsuccess'] = 'La vidéo a été ajoutée à votre playlist.';
$LANGS['share'] = 'Partager';
$LANGS['flag'] = 'Signaler';
$LANGS['flagthisvid'] = 'Signaler cette vidéo';
$LANGS['removeflag'] = 'Retirer le signalement';
$LANGS['flagnote'] = "Avant de signaler : assurez-vous que la vidéo enfreint une règle. Ne signalez pas simplement parce que vous n'aimez pas cette vidéo, sinon vous entraverez le travail des modérateurs.";
$LANGS['statadded'] = 'Ajoutée';
$LANGS['statviews'] = 'Vues';
$LANGS['statratings'] = 'Évaluations';
$LANGS['statresponses'] = 'Réponses';
$LANGS['statcomments'] = 'Commentaires';
$LANGS['statfavorited'] = 'Favoris';
$LANGS['statsdata'] = 'Statistiques et données';
$LANGS['honors'] = 'Distinctions pour cette vidéo';
$LANGS['mostviewed'] = 'Les plus regardées';
$LANGS['topfavorited'] = 'Les plus favorisées';
$LANGS['times'] = 'fois';
$LANGS['mostdiscussed'] = 'Les plus commentées';
$LANGS['toprated'] = 'Les mieux notées';
$LANGS['videolinks'] = 'Sites qui font un lien vers cette vidéo';
$LANGS['clicksfrom'] = 'clics depuis';
$LANGS['responses'] = 'Réponses vidéo';
$LANGS['responsespost'] = 'Publier une réponse vidéo';
$LANGS['textcomments'] = 'Commentaires textuels';
$LANGS['commentpost'] = 'Publier un commentaire textuel';
$LANGS['commentonthisvideo'] = 'Commenter cette vidéo';
$LANGS['postcomment'] = 'Publier un commentaire';
$LANGS['remainingcounter'] = 'Compteur de caractères restants';
$LANGS['nocomments'] = 'Cette vidéo n\'a <b>aucun commentaire</b>.';
$LANGS['noresponses'] = 'Cette vidéo n\'a <b>aucune réponse</b>.';
$LANGS['commviewall'] = 'Voir tout';
$LANGS['delete'] = 'Supprimer';
$LANGS['reply'] = 'Répondre';
$LANGS['commentlogin'] = 'Voulez-vous commenter ?';
$LANGS['commentlogindesc'] = '<a href="/signup">Inscrivez-vous à BitView</a> gratuitement ou <a href="/login">connectez-vous</a> si vous êtes déjà membre.';
$LANGS['logintoresponse'] = 'Connectez-vous pour poster une réponse vidéo';
$LANGS['logintocomment'] = 'Connectez-vous pour poster un commentaire';
$LANGS['logintofav'] = 'Voulez-vous ajouter aux favoris ? <a href="/login">Connectez-vous</a> ou <a href="/signup">inscrivez-vous</a> maintenant !';
$LANGS['logintopl'] = 'Voulez-vous ajouter à une playlist ? <a href="/login">Connectez-vous</a> ou <a href="/signup">inscrivez-vous</a> maintenant !';
$LANGS['logintoflag'] = 'Voulez-vous signaler une vidéo ? <a href="/login">Connectez-vous</a> ou <a href="/signup">inscrivez-vous</a> maintenant !';
$LANGS['close'] = 'fermer';
$LANGS['addresponse'] = 'Ajouter une réponse';
$LANGS['recentlyrated'] = 'Récemment noté';
$LANGS['commentsdisabled'] = 'Les commentaires ont été désactivés pour cette vidéo.';
$LANGS['ratingsdisabled'] = 'Évaluations désactivées';
$LANGS['rating1'] = 'Mauvais';
$LANGS['rating2'] = 'Rien de spécial';
$LANGS['rating3'] = 'Vaut la peine de regarder';
$LANGS['rating4'] = 'Plutôt cool';
$LANGS['rating5'] = 'Génial !';
$LANGS['saving'] = 'Enregistrement...';
$LANGS['signintorate'] = '<a href="/login">Connectez-vous</a> pour noter';
$LANGS['addingcomment'] = "Ajout du commentaire...";
$LANGS['commentposted'] = "Commentaire posté !";
$LANGS['commentspammsg'] = "Poster le même commentaire à nouveau est considéré comme du spam. Réessayez plus tard.";
$LANGS['commentspammsg2'] = "Poster plus de 5 commentaires consécutifs est considéré comme du spam. Réessayez plus tard.";
$LANGS['emptycomment'] = "Votre commentaire ne peut pas être vide.";
$LANGS['spambutton'] = "Spam";
$LANGS['notspambutton'] = "Pas du spam";
$LANGS['commentsspam'] = "Commentaire(s) marqué(s) comme spam";
$LANGS['marked'] = "Marqué comme spam";
$LANGS['spamshow'] = "Afficher";
$LANGS['spamhide'] = "Masquer";
$LANGS['poorcomment'] = "Commentaire médiocre";
$LANGS['goodcomment'] = "Bon commentaire";
$LANGS['pleasesignin'] = "Veuillez vous connecter";
$LANGS['showmorecomments'] = "Afficher plus de commentaires";
$LANGS['showingamount'] = "<strong>Affichage de {number}</strong> sur {total} commentaires";
$LANGS['customize'] = "Personnaliser";
$LANGS['customizedesc'] = "Après avoir fait votre choix, copiez et collez le code d'intégration ci-dessus. Le code change en fonction de votre sélection.";

/* Watch comments */
$LANGS['allcomments'] = 'Tout les commentaires';

/* Sign In */
$LANGS['username'] = "Nom d'utilisateur";
$LANGS['password'] = "Mot de passe";
$LANGS['logindesc'] = "Connectez-vous à BitView avec votre compte";
$LANGS['forgot'] = "Impossible d'accéder à votre compte ?";
$LANGS['forgotmsg'] = 'Veuillez nous contacter sur Twitter (@BitView_) ou envoyer un message aux modérateurs sur Discord (lien dans le pied de page).';
$LANGS['noaccount'] = "Vous n'avez pas de compte ?";
$LANGS['signuptobv'] = "Inscrivez-vous sur BitView !";
$LANGS['signintobv'] = "Connectez-vous à BitView !";
$LANGS['signindesc1'] = "Rejoignez la plus grande communauté mondiale de partage de vidéos !";
$LANGS['signindesc2'] = "BitView vous permet de :";
$LANGS['signindesc3'] = "Montrer vos vidéos préférées au monde entier";
$LANGS['signindesc4'] = "Bloguer les vidéos que vous prenez avec votre appareil photo numérique ou votre téléphone portable";
$LANGS['signindesc5'] = "Montrer vos vidéos de manière sécurisée et privée à vos amis et à votre famille partout dans le monde";
$LANGS['notallowed'] = "Vous avez déjà été banni 3 fois. Vous n'êtes plus autorisé à utiliser BitView !";
$LANGS['wrongpassword'] = 'Mauvais mot de passe ! Veuillez réessayer.';
$LANGS['staysigned'] = "Rester connecté";

/* Sign Up */
$LANGS['email'] = "Adresse e-mail";
$LANGS['passwordstrength'] = "Force du mot de passe";
$LANGS['psnone'] = "Aucune";
$LANGS['psweak'] = "Faible";
$LANGS['psfair'] = "Moyenne";
$LANGS['psgood'] = "Bonne";
$LANGS['psstrong'] = "Solide";
$LANGS['repassword'] = "Retapez le mot de passe";
$LANGS['usernamedesc'] = "Votre nom d'utilisateur ne peut contenir que des lettres de A à Z ou des chiffres de 0 à 9.";
$LANGS['captcha'] = "Captcha";
$LANGS['acceptterms'] = "J'accepte les <a href='/terms'>Conditions d'utilisation</a> et la <a href='/privacy'>Politique de confidentialité</a>.";
$LANGS['copyrighttext'] = "Le téléchargement de matériel que vous ne possédez pas constitue une violation du droit d'auteur et est illégal. Si vous téléchargez du matériel que vous ne possédez pas, votre compte sera supprimé.";
$LANGS['mustaccept'] = "Vous devez accepter les Conditions d'utilisation et la Politique de confidentialité pour créer votre compte.";
$LANGS['createaccount'] = "Créer mon compte";
$LANGS['signuperror'] = "Une erreur s'est produite lors de la création de votre compte.";
$LANGS['sameemail'] = "Ce nom d'utilisateur ou cette adresse e-mail est déjà utilisé(e) !";
$LANGS['usernamechar'] = "Les noms d'utilisateur ne peuvent contenir que des lettres et des chiffres !";
$LANGS['required'] = "Tous les champs de texte sont obligatoires !";
$LANGS['notmatch'] = "Les mots de passe ne correspondent pas !";
$LANGS['signuphead'] = "Commencez avec votre compte";

/* Videos Page */
$LANGS['recentvideos'] = 'Vidéos récentes';
$LANGS['random'] = 'Aléatoire';
$LANGS['dropdownmore'] = 'plus';
$LANGS['allcatin'] = 'dans';
$LANGS['allcat'] = 'Toutes les catégories';
$LANGS['categories'] = 'Catégories';
$LANGS['nomorevideos'] = 'Aucune autre vidéo n\'a été trouvée...';
$LANGS['timetoday'] = 'Aujourd\'hui';
$LANGS['timeweek'] = 'Cette semaine';
$LANGS['timemonth'] = 'Ce mois-ci';
$LANGS['alltime'] = 'Tout le temps';
$LANGS['when'] = 'Quand';
$LANGS['videofavorites'] = 'favoris';
$LANGS['videocomments'] = 'commentaires';
$LANGS['trendingtopics'] = 'Sujets Tendances';

/* Channels Page */
$LANGS['mostsubscribed'] = 'Les plus abonnés';
$LANGS['lastlogin'] = 'Dernière connexion';
$LANGS['cstatviews'] = 'Vues';
$LANGS['cstatvideos'] = 'Vidéos';
$LANGS['cstatsubs'] = 'Abonnés';
$LANGS['nochannels'] = 'Aucune autre chaîne n\'a été trouvée...';

/* Video Categories */
$LANGS['cat1'] = "Films et animations";
$LANGS['cat2'] = "Voitures et véhicules";
$LANGS['cat3'] = "Éducation et enseignement";
$LANGS['cat4'] = "Divertissement";
$LANGS['cat5'] = "Événements et mariages";
$LANGS['cat6'] = "Famille";
$LANGS['cat7'] = "Vente et enchères";
$LANGS['cat8'] = "Loisirs et intérêts";
$LANGS['cat9'] = "Humour";
$LANGS['cat10'] = "Musique";
$LANGS['cat11'] = "Actualités et politique";
$LANGS['cat12'] = "Insolite et scandaleux";
$LANGS['cat13'] = "Personnes et blogs";
$LANGS['cat14'] = "Rencontres et rencontres";
$LANGS['cat15'] = "Animaux et animaux domestiques";
$LANGS['cat16'] = "Science et technologie";
$LANGS['cat17'] = "Courts métrages";
$LANGS['cat18'] = "Sports";
$LANGS['cat19'] = "Voyages et événements";
$LANGS['cat20'] = "Jeux vidéo";
$LANGS['cat21'] = "Videoblogging";

/* Channel Types */
$LANGS['type0'] = "Aucun";
$LANGS['type1'] = "Membre";
$LANGS['type1p'] = "Membres";
$LANGS['type2'] = "Humoriste";
$LANGS['type2p'] = "Humoristes";
$LANGS['type3'] = "Réalisateur";
$LANGS['type3p'] = "Réalisateurs";
$LANGS['type4'] = "Gourou";
$LANGS['type4p'] = "Gourous";
$LANGS['type5'] = "Musicien";
$LANGS['type5p'] = "Musiciens";
$LANGS['type6'] = "Journaliste";
$LANGS['type6p'] = "Journalistes";

/* Countries */
$LANGS['cat_AF'] = "Afghanistan";
$LANGS['cat_AX'] = "Îles Åland";
$LANGS['cat_AL'] = "Albanie";
$LANGS['cat_DZ'] = "Algérie";
$LANGS['cat_AS'] = "Samoa américaines";
$LANGS['cat_AD'] = "Andorre";
$LANGS['cat_AO'] = "Angola";
$LANGS['cat_AI'] = "Anguilla";
$LANGS['cat_AQ'] = "Antarctique";
$LANGS['cat_AG'] = "Antigua-et-Barbuda";
$LANGS['cat_AR'] = "Argentine";
$LANGS['cat_AM'] = "Arménie";
$LANGS['cat_AW'] = "Aruba";
$LANGS['cat_AU'] = "Australie";
$LANGS['cat_AT'] = "Autriche";
$LANGS['cat_AZ'] = "Azerbaïdjan";
$LANGS['cat_BS'] = "Bahamas";
$LANGS['cat_BH'] = "Bahreïn";
$LANGS['cat_BD'] = "Bangladesh";
$LANGS['cat_BB'] = "Barbade";
$LANGS['cat_BY'] = "Biélorussie";
$LANGS['cat_BE'] = "Belgique";
$LANGS['cat_BZ'] = "Belize";
$LANGS['cat_BJ'] = "Bénin";
$LANGS['cat_BM'] = "Bermudes";
$LANGS['cat_BT'] = "Bhoutan";
$LANGS['cat_BO'] = "Bolivie";
$LANGS['cat_BQ'] = "Pays-Bas caribéens";
$LANGS['cat_BA'] = "Bosnie-Herzégovine";
$LANGS['cat_BW'] = "Botswana";
$LANGS['cat_BV'] = "Île Bouvet";
$LANGS['cat_BR'] = "Brésil";
$LANGS['cat_IO'] = "Territoire britannique de l'océan Indien";
$LANGS['cat_BN'] = "Brunéi Darussalam";
$LANGS['cat_BG'] = "Bulgarie";
$LANGS['cat_BF'] = "Burkina Faso";
$LANGS['cat_BI'] = "Burundi";
$LANGS['cat_KH'] = "Cambodge";
$LANGS['cat_CM'] = "Cameroun";
$LANGS['cat_CA'] = "Canada";
$LANGS['cat_CV'] = "Cap-Vert";
$LANGS['cat_KY'] = "Îles Caïmans";
$LANGS['cat_CF'] = "République centrafricaine";
$LANGS['cat_TD'] = "Tchad";
$LANGS['cat_CL'] = "Chili";
$LANGS['cat_CN'] = "Chine";
$LANGS['cat_CX'] = "Île Christmas";
$LANGS['cat_CC'] = "Îles Cocos (Keeling)";
$LANGS['cat_CO'] = "Colombie";
$LANGS['cat_KM'] = "Comores";
$LANGS['cat_CG'] = "République du Congo";
$LANGS['cat_CD'] = "République démocratique du Congo";
$LANGS['cat_CK'] = "Îles Cook";
$LANGS['cat_CR'] = "Costa Rica";
$LANGS['cat_CI'] = "Côte d'Ivoire";
$LANGS['cat_HR'] = "Croatie";
$LANGS['cat_CU'] = "Cuba";
$LANGS['cat_CW'] = "Curaçao";
$LANGS['cat_CY'] = "Chypre";
$LANGS['cat_CZ'] = "République tchèque";
$LANGS['cat_DK'] = "Danemark";
$LANGS['cat_DJ'] = "Djibouti";
$LANGS['cat_DM'] = "Dominique";
$LANGS['cat_DO'] = "République dominicaine";
$LANGS['cat_EC'] = "Équateur";
$LANGS['cat_EG'] = "Égypte";
$LANGS['cat_SV'] = "Salvador";
$LANGS['cat_GQ'] = "Guinée équatoriale";
$LANGS['cat_ER'] = "Érythrée";
$LANGS['cat_EE'] = "Estonie";
$LANGS['cat_ET'] = "Éthiopie";
$LANGS['cat_FK'] = "Îles Malouines";
$LANGS['cat_FO'] = "Îles Féroé";
$LANGS['cat_FJ'] = "Fidji";
$LANGS['cat_FI'] = "Finlande";
$LANGS['cat_FR'] = "France";
$LANGS['cat_GF'] = "Guyane française";
$LANGS['cat_FG'] = "Guyane française";
$LANGS['cat_PF'] = "Polynésie française";
$LANGS['cat_TF'] = "Terres australes françaises";
$LANGS['cat_GA'] = "Gabon";
$LANGS['cat_GM'] = "Gambie";
$LANGS['cat_GE'] = "Géorgie";
$LANGS['cat_DE'] = "Allemagne";
$LANGS['cat_GH'] = "Ghana";
$LANGS['cat_GI'] = "Gibraltar";
$LANGS['cat_GR'] = "Grèce";
$LANGS['cat_GL'] = "Groenland";
$LANGS['cat_GD'] = "Grenade";
$LANGS['cat_GP'] = "Guadeloupe";
$LANGS['cat_GU'] = "Guam";
$LANGS['cat_GT'] = "Guatemala";
$LANGS['cat_GG'] = "Guernesey";
$LANGS['cat_GN'] = "Guinée";
$LANGS['cat_GW'] = "Guinée-Bissau";
$LANGS['cat_GY'] = "Guyana";
$LANGS['cat_HT'] = "Haïti";
$LANGS['cat_HM'] = "Îles Heard-et-MacDonald";
$LANGS['cat_VA'] = "Saint-Siège (État de la Cité du Vatican)";
$LANGS['cat_HN'] = "Honduras";
$LANGS['cat_HK'] = "Hong Kong";
$LANGS['cat_HU'] = "Hongrie";
$LANGS['cat_IS'] = "Islande";
$LANGS['cat_IN'] = "Inde";
$LANGS['cat_ID'] = "Indonésie";
$LANGS['cat_IR'] = "Iran";
$LANGS['cat_IQ'] = "Irak";
$LANGS['cat_IE'] = "Irlande";
$LANGS['cat_IM'] = "Île de Man";
$LANGS['cat_IL'] = "Israël";
$LANGS['cat_IT'] = "Italie";
$LANGS['cat_JM'] = "Jamaïque";
$LANGS['cat_JP'] = "Japon";
$LANGS['cat_JE'] = "Jersey";
$LANGS['cat_JO'] = "Jordanie";
$LANGS['cat_KZ'] = "Kazakhstan";
$LANGS['cat_KE'] = "Kenya";
$LANGS['cat_KI'] = "Kiribati";
$LANGS['cat_XK'] = "Kosovo";
$LANGS['cat_KP'] = "Corée du Nord";
$LANGS['cat_KR'] = "Corée du Sud";
$LANGS['cat_KW'] = "Koweït";
$LANGS['cat_KG'] = "Kirghizistan";
$LANGS['cat_LA'] = "Laos";
$LANGS['cat_LV'] = "Lettonie";
$LANGS['cat_LB'] = "Liban";
$LANGS['cat_LS'] = "Lesotho";
$LANGS['cat_LR'] = "Libéria";
$LANGS['cat_LY'] = "Libye";
$LANGS['cat_LI'] = "Liechtenstein";
$LANGS['cat_LT'] = "Lituanie";
$LANGS['cat_LU'] = "Luxembourg";
$LANGS['cat_MO'] = "Macao";
$LANGS['cat_MK'] = "Macédoine du Nord";
$LANGS['cat_MG'] = "Madagascar";
$LANGS['cat_MW'] = "Malawi";
$LANGS['cat_MY'] = "Malaisie";
$LANGS['cat_MV'] = "Maldives";
$LANGS['cat_ML'] = "Mali";
$LANGS['cat_MT'] = "Malte";
$LANGS['cat_MH'] = "Îles Marshall";
$LANGS['cat_MQ'] = "Martinique";
$LANGS['cat_MR'] = "Mauritanie";
$LANGS['cat_MU'] = "Maurice";
$LANGS['cat_YT'] = "Mayotte";
$LANGS['cat_MX'] = "Mexique";
$LANGS['cat_FM'] = "Micronésie";
$LANGS['cat_MD'] = "Moldavie";
$LANGS['cat_MC'] = "Monaco";
$LANGS['cat_MN'] = "Mongolie";
$LANGS['cat_ME'] = "Monténégro";
$LANGS['cat_MS'] = "Montserrat";
$LANGS['cat_MA'] = "Maroc";
$LANGS['cat_MZ'] = "Mozambique";
$LANGS['cat_MM'] = "Myanmar";
$LANGS['cat_NA'] = "Namibie";
$LANGS['cat_NR'] = "Nauru";
$LANGS['cat_NP'] = "Népal";
$LANGS['cat_NL'] = "Pays-Bas";
$LANGS['cat_AN'] = "Antilles néerlandaises";
$LANGS['cat_NC'] = "Nouvelle-Calédonie";
$LANGS['cat_NZ'] = "Nouvelle-Zélande";
$LANGS['cat_NI'] = "Nicaragua";
$LANGS['cat_NE'] = "Niger";
$LANGS['cat_NG'] = "Nigéria";
$LANGS['cat_NU'] = "Niue";
$LANGS['cat_NF'] = "Île Norfolk";
$LANGS['cat_MP'] = "Îles Mariannes du Nord";
$LANGS['cat_NO'] = "Norvège";
$LANGS['cat_OM'] = "Oman";
$LANGS['cat_PK'] = "Pakistan";
$LANGS['cat_PW'] = "Palaos";
$LANGS['cat_PS'] = "Palestine";
$LANGS['cat_PA'] = "Panama";
$LANGS['cat_PG'] = "Papouasie-Nouvelle-Guinée";
$LANGS['cat_PY'] = "Paraguay";
$LANGS['cat_PE'] = "Pérou";
$LANGS['cat_PH'] = "Philippines";
$LANGS['cat_PN'] = "Îles Pitcairn";
$LANGS['cat_PL'] = "Pologne";
$LANGS['cat_PT'] = "Portugal";
$LANGS['cat_PR'] = "Porto Rico";
$LANGS['cat_QA'] = "Qatar";
$LANGS['cat_RE'] = "Réunion";
$LANGS['cat_RO'] = "Roumanie";
$LANGS['cat_RU'] = "Russie";
$LANGS['cat_RW'] = "Rwanda";
$LANGS['cat_BL'] = "Saint-Barthélémy";
$LANGS['cat_SH'] = "Sainte-Hélène";
$LANGS['cat_KN'] = "Saint-Christophe-et-Niévès";
$LANGS['cat_LC'] = "Sainte-Lucie";
$LANGS['cat_MF'] = "Saint-Martin (partie française)";
$LANGS['cat_PM'] = "Saint-Pierre-et-Miquelon";
$LANGS['cat_VC'] = "Saint-Vincent-et-les-Grenadines";
$LANGS['cat_WS'] = "Samoa";
$LANGS['cat_SM'] = "Saint-Marin";
$LANGS['cat_ST'] = "Sao Tomé-et-Principe";
$LANGS['cat_SA'] = "Arabie saoudite";
$LANGS['cat_SN'] = "Sénégal";
$LANGS['cat_RS'] = "Serbie";
$LANGS['cat_SC'] = "Seychelles";
$LANGS['cat_SL'] = "Sierra Leone";
$LANGS['cat_SG'] = "Singapour";
$LANGS['cat_SX'] = "Saint-Martin";
$LANGS['cat_SK'] = "Slovaquie";
$LANGS['cat_SI'] = "Slovénie";
$LANGS['cat_SB'] = "Îles Salomon";
$LANGS['cat_SO'] = "Somalie";
$LANGS['cat_ZA'] = "Afrique du Sud";
$LANGS['cat_GS'] = "Géorgie du Sud-et-les îles Sandwich du Sud";
$LANGS['cat_ES'] = "Espagne";
$LANGS['cat_LK'] = "Sri Lanka";
$LANGS['cat_SD'] = "Soudan";
$LANGS['cat_SR'] = "Suriname";
$LANGS['cat_SJ'] = "Svalbard et Jan Mayen";
$LANGS['cat_SZ'] = "Eswatini";
$LANGS['cat_SE'] = "Suède";
$LANGS['cat_CH'] = "Suisse";
$LANGS['cat_SS'] = "Soudan du Sud";
$LANGS['cat_SY'] = "Syrie";
$LANGS['cat_TW'] = "Taïwan";
$LANGS['cat_TJ'] = "Tadjikistan";
$LANGS['cat_TZ'] = "Tanzanie";
$LANGS['cat_TH'] = "Thaïlande";
$LANGS['cat_TL'] = "Timor oriental";
$LANGS['cat_TG'] = "Togo";
$LANGS['cat_TK'] = "Tokelau";
$LANGS['cat_TO'] = "Tonga";
$LANGS['cat_TT'] = "Trinité-et-Tobago";
$LANGS['cat_TN'] = "Tunisie";
$LANGS['cat_TR'] = "Turquie";
$LANGS['cat_TM'] = "Turkménistan";
$LANGS['cat_TC'] = "Îles Turks-et-Caïcos";
$LANGS['cat_TV'] = "Tuvalu";
$LANGS['cat_UG'] = "Ouganda";
$LANGS['cat_UA'] = "Ukraine";
$LANGS['cat_AE'] = "Émirats arabes unis";
$LANGS['cat_GB'] = "Royaume-Uni";
$LANGS['cat_US'] = "États-Unis";
$LANGS['cat_UM'] = "Îles mineures éloignées des États-Unis";
$LANGS['cat_UY'] = "Uruguay";
$LANGS['cat_UZ'] = "Ouzbékistan";
$LANGS['cat_VU'] = "Vanuatu";
$LANGS['cat_VE'] = "Venezuela";
$LANGS['cat_VN'] = "Vietnam";
$LANGS['cat_VG'] = "Îles Vierges britanniques";
$LANGS['cat_VI'] = "Îles Vierges des États-Unis";
$LANGS['cat_WF'] = "Wallis-et-Futuna";
$LANGS['cat_EH'] = "Sahara occidental";
$LANGS['cat_YE'] = "Yémen";
$LANGS['cat_ZM'] = "Zambie";
$LANGS['cat_ZW'] = "Zimbabwe";

/* My Subscriptions */
$LANGS['newvideos'] = "Nouvelles vidéos";

/* Account */
$LANGS['myaccount'] = "Mon compte";
$LANGS['vidsfavs'] = "Vidéos, Favoris et Listes de lecture";
$LANGS['accountsettings'] = "Paramètres du compte";
$LANGS['viewinghistory'] = "Historique";
$LANGS['mychannel'] = "Ma chaîne";
$LANGS['uploadedvideos'] = "Vidéos téléchargées";
$LANGS['new'] = "Nouveau";
$LANGS['playlist'] = "Liste de lecture";
$LANGS['videoupload'] = "Téléchargement de vidéos";
$LANGS['nosubvideos'] = "Vous n'avez aucune inscription...";
$LANGS['nofavvideos'] = "Vous n'avez pas ajouté de vidéos en favoris...";

/* My Videos */
$LANGS['sortby'] = "Trier par";
$LANGS['sorttitle'] = "Titre";
$LANGS['sorttime'] = "Temps";
$LANGS['sortdateadded'] = "Date d'ajout";
$LANGS['sortviews'] = "Vues";
$LANGS['sortrating'] = "Évaluation";
$LANGS['stattime'] = "Temps";
$LANGS['statrating'] = "Évaluation";
$LANGS['statbroadcast'] = "Diffusion";
$LANGS['statrawfile'] = "Fichier brut";
$LANGS['public'] = "Public";
$LANGS['private'] = "Privé";
$LANGS['live'] = "En direct !";
$LANGS['converting'] = "Conversion en cours...";
$LANGS['uploading'] = "Téléchargement en cours...";
$LANGS['addvidsto'] = "Ajouter des vidéos à";
$LANGS['play'] = "Lire";
$LANGS['edit'] = "Modifier";
$LANGS['setasavatar'] = "Définir comme image de profil";
$LANGS['downloadmp4'] = "Télécharger MP4";
$LANGS['deleteconfirmation'] = "Êtes-vous sûr(e) de vouloir supprimer cette vidéo ?";
$LANGS['novideos'] = 'Vous n\'avez téléchargé aucune vidéo. <a href="/my_videos_upload">Commencez à télécharger une vidéo maintenant</a> !';
$LANGS['nomyvideosresults'] = "Aucun résultat. Vérifiez l'orthographe de votre recherche.";

/* Edit Video */
$LANGS['title'] = "Titre";
$LANGS['desc'] = "Description";
$LANGS['privacy'] = "Confidentialité";
$LANGS['saveinfo'] = "Enregistrer les informations";
$LANGS['saveinfoconfirm'] = "Êtes-vous sûr(e) de vouloir modifier les informations de la vidéo ?";
$LANGS['viewchart'] = "Voir le graphique";
$LANGS['backtopreviouspage'] = "Retour à la Page Précédente";
$LANGS['editsavechanges'] = "Enregistrer les Modifications";
$LANGS['editcancel'] = "Annuler";
$LANGS['videoinfo'] = "Informations sur la Vidéo";
$LANGS['videothumbnail'] = "Miniature de la Vidéo";
$LANGS['uploadthumbnail'] = "Télécharger la Miniature";
$LANGS['customthumbdesc'] = "Pour définir une miniature personnalisée, cliquez sur la miniature du côté gauche et sélectionnez le fichier image de votre choix. Ensuite, cliquez sur \"Télécharger la Miniature\".";
$LANGS['customthumbtitle'] = "Voulez-vous changer cette miniature ?";
$LANGS['customthumbinfo'] = "Les miniatures personnalisées sont exclusives aux partenaires. Pour en savoir plus sur les avantages de rejoindre le programme de partenariat et ses exigences, cliquez sur le bouton ci-dessous.";
$LANGS['partnerreadmore'] = 'En savoir plus';
$LANGS['broadcastingoptions'] = 'Options de Diffusion et de Partage';
$LANGS['publicdesc'] = "tout le monde peut rechercher et voir - recommandé";
$LANGS['privatedesc'] = "seuls les utilisateurs spécifiques de BitView peuvent voir";
$LANGS['allowcomments'] = "Autoriser automatiquement les commentaires";
$LANGS['allowfriendcomments'] = "Seuls les amis peuvent commenter";
$LANGS['disablecomments'] = "Ne pas autoriser les commentaires";
$LANGS['dateandmap'] = "Date et Carte";
$LANGS['clear'] = "Effacer";
$LANGS['allowratings'] = "Oui, autoriser cette vidéo à être évaluée par d'autres.";
$LANGS['dontallowratings'] = "Non, ne pas autoriser cette vidéo à être évaluée.";

/* My Playlists */
$LANGS['addedpl'] = "Ajouté";
$LANGS['frompl'] = "De";
$LANGS['nopl'] = "Pas de playlist à été trouvé....";

/* My Playlist */
$LANGS['playlistedit'] = "Modifier la playlist";
$LANGS['videourl'] = "URL de la vidéo";
$LANGS['add'] = "Ajouter";
$LANGS['editinfo'] = "Modifer l'info";

/* Edit Playlist */
$LANGS['pledittitle'] = "Modifier la playlist";
$LANGS['pleditdesc'] = "Les playlists sont des collections de vidéos que vous pouvez organiser selon vos préférences.";
$LANGS['cancel'] = "Annuler";

/* Create Playlist */
$LANGS['createplaylisttitle'] = "Créer une Playlist Vidéo";
$LANGS['createplaylist'] = "Créer une Playlist";

/* View Playlist */
$LANGS['plpermalink'] = "Playlist/URL (Permalien) :";
$LANGS['sortcomments'] = "Commentaires";
$LANGS['unsorted'] = "Non trié";
$LANGS['playallvideos'] = "Lire toutes les vidéos";

/* Inbox */
$LANGS['compose'] = "Composer";
$LANGS['from'] = "De";
$LANGS['subject'] = "Sujet";
$LANGS['date'] = "Date";
$LANGS['allmsg'] = "Tous les Messages";
$LANGS['msgcom'] = "Commentaires";
$LANGS['sentmsg'] = "Messages Envoyés";
$LANGS['nomsg'] = "Vous n'avez aucun message...";


/* Send Message */
$LANGS['messagecont'] = "Message";
$LANGS['to'] = "À";
$LANGS['sendmessagebutton'] = "Envoyer le Message";

/* Groups */
$LANGS['groups'] = "Groupes";
$LANGS['joinedgroups'] = "Groupes Rejoins";
$LANGS['recentgroups'] = "Groupes Récents";
$LANGS['mostmembers'] = "Plus de Membres";
$LANGS['mostvideos'] = "Plus de Vidéos";
$LANGS['groupmostdiscussed'] = "Le Plus Discuté";
$LANGS['createagroup'] = "Créer un Groupe";
$LANGS['groupvideos'] = "Vidéos";
$LANGS['groupmembers'] = "Membres";
$LANGS['discussions'] = "Discussions";
$LANGS['groupcreated'] = "Créé";
$LANGS['nogroups'] = "Aucun groupe trouvé...";

/* Group */
$LANGS['jointhisgroup'] = "Rejoindre ce Groupe";
$LANGS['removerequest'] = "Retirer la Demande";
$LANGS['leavegroup'] = "Quitter le Groupe";
$LANGS['moderation'] = "Modération";
$LANGS['viewallvideos'] = "Voir Toutes les Vidéos";
$LANGS['addvideo'] = "Ajouter une Vidéo";
$LANGS['novideos'] = "Pas de Vidéos...";
$LANGS['nodiscussions'] = "Pas de Discussions...";
$LANGS['creatediscussion'] = "Créer une Discussion";
$LANGS['topostatopic'] = "pour publier un sujet.";
$LANGS['topic'] = "Sujet";
$LANGS['author'] = "Auteur";
$LANGS['replies'] = "Réponses";
$LANGS['lastpost'] = "Dernier Message";
$LANGS['viewallmembers'] = "Voir Tous les Membres";
$LANGS['owner'] = "Propriétaire";
$LANGS['grouptype'] = "Type";
$LANGS['instantjoin'] = "Rejoindre Instantanément";
$LANGS['approvalrequired'] = "Approbation Requise";
$LANGS['groupurl'] = "URL";
$LANGS['deletediscussion'] = "Supprimer la Discussion";
$LANGS['postreply'] = "Poster une Réponse";
$LANGS['post'] = "Poster";
$LANGS['accept'] = "Accepter";
$LANGS['decline'] = "Refuser";

/* Group Moderation */
$LANGS['groupmoderation'] = "Modération du Groupe";
$LANGS['approvemembers'] = "Approuver les Membres";
$LANGS['approvevideos'] = "Approuver les Vidéos";
$LANGS['yes'] = "Oui";
$LANGS['no'] = "Non";
$LANGS['changeinfo'] = "Modifier les Informations";
$LANGS['changeimage'] = "Changer l'Image";
$LANGS['image'] = "Image";
$LANGS['styling'] = "Styles";
$LANGS['cssdesc'] = "Avoir des arrière-plans ou des graphiques qui font ou montrent des choses illégales entraînera la résiliation de votre compte.";
$LANGS['updatecss'] = "Mettre à Jour le CSS";
$LANGS['groupmessage'] = "Message";
$LANGS['sendmessagetomembers'] = "Envoyer un Message aux Membres";
$LANGS['delgroup'] = "Supprimer le Groupe";

/* Submit Group Video */
$LANGS['submitvideotitle'] = "Soumettre une Vidéo au Groupe";
$LANGS['submitvideo'] = "Soumettre la Vidéo";

/* Create Group */
$LANGS['groupname'] = "Nom du Groupe";
$LANGS['groupimage'] = "Image du Groupe";
$LANGS['creategroup'] = "Créer un Groupe";
$LANGS['creategroupdesc'] = "Les groupes vous permettent de créer des discussions avec d'autres membres et de partager facilement vos vidéos avec d'autres personnes.";

/* Create Group Discussion */
$LANGS['discussiontitle'] = "Discussion Title";
$LANGS['creatediscussiondesc'] = "Discussions are parts of groups in which you discuss the set topic.";

/* Search Results */
$LANGS['resultspre'] = ""; /* Explanation: Use if the search query goes before "results". Example: "Resultados para search" in Spanish. If your language doesn't use this, leave it empty like this: ''*/
$LANGS['resultspost'] = "résultats";  /* Explanation: Use if "BitView" goes after the username. Example: "search results" in English. If your language doesn't use this, leave it empty like this: '' */
$LANGS['relevance'] = 'Pertinence';
$LANGS['viewcount'] = 'Nombre de Vues';
$LANGS['searchrating'] = 'Évaluation';
$LANGS['newest'] = 'Plus Récentes';
$LANGS['nochannelsfound'] = 'Aucune Chaîne Trouvée...';
$LANGS['noplfound'] = 'Aucune Playlist Trouvée...';
$LANGS['nogroupsfound'] = 'Aucun Groupe Trouvé...';
$LANGS['uploaded'] = 'Téléchargée';
$LANGS['anytime'] = 'À Tout Moment';
$LANGS['partnervideos'] = 'Vidéos des Partenaires';
$LANGS['resultcount'] = '{r} résultats sur environ {t}';

/* Profile */
$LANGS['channelsuspended'] = 'Ce compte est suspendu.';
$LANGS['accountnotfound'] = 'Ce compte n\'a pas pu être trouvé.';
$LANGS['channel'] = 'Chaîne';
$LANGS['friends'] = 'Amis';
$LANGS['channelsubscribers'] = 'Abonnés';
$LANGS['linkcomments'] = 'Commentaires';
$LANGS['bulletins'] = 'Bulletins';
$LANGS['editchannel'] = 'Modifier la Chaîne';
$LANGS['type'] = 'Type';
$LANGS['joined'] = 'Rejoint';
$LANGS['videoswatched'] = 'Vidéos Vues';
$LANGS['channelviews'] = 'Vues de la Chaîne';
$LANGS['age'] = 'Âge';
$LANGS['gender'] = 'Genre';
$LANGS['male'] = 'Homme';
$LANGS['female'] = 'Femme';
$LANGS['status'] = 'Statut';
$LANGS['single_m'] = 'Célibataire';
$LANGS['single_f'] = 'Célibataire';
$LANGS['taken_m'] = 'En couple';
$LANGS['taken_f'] = 'En couple';
$LANGS['married_m'] = 'Marié';
$LANGS['married_f'] = 'Mariée';
$LANGS['country'] = 'Pays';
$LANGS['website'] = 'Site Web';
$LANGS['hobbies'] = 'Centres d\'intérêt et Loisirs';
$LANGS['music'] = 'Musique';
$LANGS['movies'] = 'Films et Émissions';
$LANGS['books'] = 'Livres';
$LANGS['mostsub'] = 'Plus Abonnées';
$LANGS['report'] = 'Signaler';
$LANGS['pfpviolation'] = 'violation de l\'image de profil';
$LANGS['connectwith'] = 'Se Connecter avec';
$LANGS['profilesendmessage'] = 'Envoyer un Message';
$LANGS['messagetoyourself'] = 'Vous ne pouvez pas envoyer de messages à vous-même !';
$LANGS['logintomessage'] = 'Veuillez vous connecter pour envoyer des messages !';
$LANGS['addcomment'] = 'Ajouter un Commentaire';
$LANGS['logintocommentchannel'] = 'Veuillez vous connecter pour commenter';
$LANGS['sharechannel'] = 'Partager la Chaîne';
$LANGS['addfriend'] = 'Ajouter en tant qu\'Ami';
$LANGS['retractinvite'] = 'Retracter l\'Invitation';
$LANGS['removefriend'] = 'Retirer de la liste d\'Amis';
$LANGS['notfriendyourself'] = 'Vous ne pouvez pas vous ajouter vous-même en ami !';
$LANGS['logintofriend'] = 'Veuillez vous connecter pour ajouter des amis !';
$LANGS['blockuser'] = 'Bloquer l\'Utilisateur';
$LANGS['channelembed'] = 'Intégrer cette Chaîne';
$LANGS['recentratings'] = 'Activité Récente';
$LANGS['seeall'] = 'voir tout';
$LANGS['writebulletin'] = 'Écrire un Bulletin';
$LANGS['bulletin'] = 'Bulletin';
$LANGS['subvideos1'] = 'S\'abonner à ';
$LANGS['subvideos2'] = "'s vidéos";
$LANGS['plvideos'] = 'Vidéos';
$LANGS['playall'] = 'Lire Tout';
$LANGS['featuredchannels'] = 'Chaînes Recommandées';
$LANGS['channelcomments'] = 'Commentaires de la Chaîne';
$LANGS['bggraphic'] = 'graphique d\'arrière-plan';
$LANGS['reportthisuser'] = 'cet utilisateur.';
$LANGS['norecentratings'] = 'Aucune activité récente trouvée...';
$LANGS['nosubscribers'] = 'Aucun Abonné...';
$LANGS['nosubscriptions'] = 'Aucune Abonnement...';
$LANGS['nofriends'] = 'Aucun Ami...';
$LANGS['nobulletins'] = 'Aucun Bulletin...';
$LANGS['novideoschannel'] = 'Aucune Vidéo...';
$LANGS['nofavs'] = 'Aucune Vidéo Favorite...';
$LANGS['noplchannel'] = 'Aucune Playlist...';
$LANGS['pvideos'] = 'Vidéos Privées';
$LANGS['pvideosallow'] = 'Vous n\'êtes pas autorisé à voir ces vidéos...';
$LANGS['plvideoamount'] = 'vidéos';
$LANGS['bulletinpost'] = 'Poste de Bulletin';
$LANGS['deletebulletin'] = 'Supprimer le Bulletin';
$LANGS['body'] = 'Corps';
$LANGS['bulletincomments'] = 'Commentaires du Bulletin';
$LANGS['tocommentbulletin'] = 'pour poster une réponse à ce bulletin !';
$LANGS['addacomment'] = 'Ajouter un Commentaire :';
$LANGS['postreplychannel'] = 'Poster une Réponse';
$LANGS['writecomment'] = 'Écrire un Commentaire';
$LANGS['for'] = 'pour';
$LANGS['commentdesc'] = 'Les commentaires de la chaîne apparaissent sur la page de la chaîne de l\'utilisateur.';
$LANGS['postbulletin'] = 'Poster un Bulletin';
$LANGS['writeabulletin'] = 'Écrire un bulletin';
$LANGS['bulletindesc'] = 'Les bulletins apparaissent sur votre propre page de chaîne et sur celles de vos amis.';
$LANGS['sharingoptions'] = 'Partage';
$LANGS['sharingoptionsdesc'] = 'Il existe 2 façons de partager cette chaîne.';
$LANGS['sharingoptions1'] = '1. Copiez-collez ce lien dans un e-mail ou un message instantané.';
$LANGS['sharingoptions2'] = "2. Envoyez cette chaîne à l'aide de l'application de messagerie de votre ordinateur.";
$LANGS['clicktosend'] = 'Cliquez pour envoyer !';
$LANGS['honorless'] = 'moins';
$LANGS['activitycomment'] = 'a commenté sur';
$LANGS['activityfavorite'] = 'a mis en favori une vidéo';
$LANGS['activityrating'] = 'a évalué une vidéo :';
$LANGS['activityupload'] = 'a téléchargé une nouvelle vidéo';
$LANGS['activityfriend'] = 'est devenu ami avec';
$LANGS['activitysubscription'] = 's\'est abonné à';
$LANGS['next'] = "Suivant";
$LANGS['previous'] = "Précédent";
$LANGS['settings'] = "Paramètres";
$LANGS['themescolors'] = "Thèmes et Couleurs";
$LANGS['channelmodules'] = "Modules";
$LANGS['videosandpl'] = "Vidéos et Playlists";
$LANGS['revert'] = "Revenir ! Je veux retrouver mon ancienne chaîne";
$LANGS['all'] = "Tous";
$LANGS['uploads'] = "Téléchargements";
$LANGS['channelpl'] = "Playlists";
$LANGS['backtoplaylists'] = "Retour aux Playlists";
$LANGS['searchuploads'] = "Rechercher les Téléchargements";
$LANGS['info'] = "Info";
$LANGS['viewcomments'] = "Voir les commentaires, les vidéos associées, et plus encore";
$LANGS['seeallcommentsandresponses'] = "Voir tous les commentaires et réponses vidéo";
$LANGS['pastethislink'] = "Collez ce lien dans un e-mail ou un message instantané";
$LANGS['selectplaylist'] = "Sélectionner la Playlist";
$LANGS['profilemsg'] = 'Les visiteurs de votre chaîne verront des liens ici, notamment "s\'abonner" et "ajouter en ami".';
$LANGS['profile'] = 'Profil';
$LANGS['profilechangessaved'] = 'Modifications enregistrées.';
$LANGS['posting'] = 'poste en cours...';
$LANGS['name'] = 'Nom';
$LANGS['totaluploadviews'] = 'Vues Totales des Téléchargements';
$LANGS['channeldesc'] = 'Description de la Chaîne';
$LANGS['hometown'] = 'Ville Natale';
$LANGS['occupation'] = 'Profession';
$LANGS['companies'] = 'Entreprises';
$LANGS['schools'] = 'Écoles';
$LANGS['interests'] = 'Centres d\'Intérêt';
$LANGS['movies'] = 'Films';
$LANGS['featuredchannelsdefault'] = 'Cliquez sur "modifier" ci-dessus pour saisir les chaînes que vous souhaitez lier.';
$LANGS['featuredchannelsdesc'] = 'Veuillez lister jusqu\'à 4 chaînes de destination dans l\'ordre dans lequel vous souhaitez les afficher sur votre chaîne, séparées par des virgules et sans espaces. Ne pas lister de chaînes empêchera cette boîte de s\'afficher sur votre chaîne.';
$LANGS['backtochannel'] = "retour à la chaîne de {c}";
$LANGS['refresh'] = "Actualiser";
$LANGS['whichcontent'] = "Quel contenu souhaitez-vous afficher ?";
$LANGS['myuploadedvideos'] = "Mes Téléchargements";
$LANGS['myfavorites'] = "Mes Favoris";
$LANGS['alsoshowall'] = 'Afficher également la vue "Tout"';
$LANGS['featuredvideo'] = 'Vidéo en vedette';
$LANGS['usemostrecent'] = 'Utiliser la vidéo la plus récente de mon ensemble en vedette';
$LANGS['autoplayfeatured'] = "Lecture automatique de la vidéo en vedette";
$LANGS['areyousure'] = "Êtes-vous sûr de vouloir continuer ?";
$LANGS['unsavedchanges'] = "Êtes-vous sûr de vouloir changer le thème ? Les modifications non enregistrées seront perdues.";
$LANGS['showadvancedoptions'] = "Afficher les options avancées";
$LANGS['hideadvancedoptions'] = "Masquer les options avancées";
$LANGS['general'] = "Général";
$LANGS['colorpalettes'] = "Palettes de couleurs";
$LANGS['font'] = "Police";
$LANGS['wrappercolor'] = "Couleur de l'enveloppe";
$LANGS['wrappertextcolor'] = "Couleur du texte de l'enveloppe";
$LANGS['wrapperlinkcolor'] = "Couleur du lien de l'enveloppe";
$LANGS['wrappertransparency'] = "Transparence de l'enveloppe";
$LANGS['repeatbackground'] = "Répéter l'arrière-plan";
$LANGS['titletextcolor'] = "Couleur du texte du titre";
$LANGS['bodytextcolor'] = "Couleur du texte du corps";
$LANGS['transparency'] = "Transparence";
$LANGS['bgimgdesc'] = "Téléchargez une image qui s'affichera en arrière-plan de votre chaîne (maximum 2 Mo).";
$LANGS['channeltype'] = "Type de chaîne";
$LANGS['channeltags'] = "Étiquettes de chaîne";
$LANGS['commaseparated'] = "(séparées par des virgules)";
$LANGS['channeltagsdesc'] = "Les étiquettes sont des mots-clés utilisés pour aider les gens à trouver votre chaîne.";

/* My Profile page */
$LANGS['myprofiledesc'] = 'Cette page contient tous les paramètres de votre chaîne BitView.';
$LANGS['profileimages'] = 'Images de profil';
$LANGS['avatar'] = 'Avatar';
$LANGS['backgroundimage'] = 'Image d\'arrière-plan';
$LANGS['deleteimage'] = 'Supprimer l\'image';
$LANGS['channelinformation'] = 'Informations sur la chaîne';
$LANGS['genderrelationprivate'] = 'Privé';
$LANGS['fctitle'] = 'Titre F.C.';
$LANGS['relationship'] = 'Relation';
$LANGS['birthday'] = 'Anniversaire';
$LANGS['showage'] = 'Afficher l\'âge';
$LANGS['aboutme'] = 'À propos de moi';
$LANGS['emailprefs'] = 'Préférences de messagerie électronique';
$LANGS['emailpm'] = 'M\'envoyer un e-mail pour les messages privés';
$LANGS['emailcomm'] = 'M\'envoyer un e-mail pour les commentaires vidéo';
$LANGS['emailsub'] = 'M\'envoyer un e-mail pour les moments forts hebdomadaires des abonnements';
$LANGS['layoutprefs'] = 'Préférences de mise en page';
$LANGS['bgcolor'] = 'Couleur de l\'arrière-plan';
$LANGS['bgfixed'] = 'Fixe';
$LANGS['bgrepeat'] = 'Répéter';
$LANGS['norepeat'] = 'Pas de répétition';
$LANGS['repeat'] = 'Répéter';
$LANGS['repeatx'] = 'Répéter X';
$LANGS['repeaty'] = 'Répéter Y';
$LANGS['bgposition'] = 'Position';
$LANGS['top'] = 'Haut';
$LANGS['middle'] = 'Milieu';
$LANGS['bottom'] = 'Bas';
$LANGS['fontcolor'] = 'Couleur de la police';
$LANGS['titlefontcolor'] = 'Couleur de la police du titre';
$LANGS['linkcolor'] = 'Couleur du lien';
$LANGS['hlfontcolor'] = 'Couleur de la police en surbrillance';
$LANGS['hlheadercolor'] = 'En-tête de surbrillance';
$LANGS['hlinsidecolor'] = 'Intérieur de surbrillance';
$LANGS['headercolor'] = 'En-tête régulier';
$LANGS['insidecolor'] = 'Intérieur régulier';
$LANGS['font'] = 'Police de chaîne';
$LANGS['featuredvideobox'] = 'Boîte vidéo en vedette';
$LANGS['subscribersbox'] = 'Boîte d\'abonnés';
$LANGS['subscriptionsbox'] = 'Boîte d\'abonnements';
$LANGS['friendsbox'] = 'Boîte d\'amis';
$LANGS['bulletinsbox'] = 'Boîte des bulletins';
$LANGS['videosbox'] = 'Boîte des vidéos';
$LANGS['favoritesbox'] = 'Boîte des favoris';
$LANGS['playlistsbox'] = 'Boîte des playlists';
$LANGS['commentsbox'] = 'Boîte des commentaires';
$LANGS['ratingsbox'] = 'Boîte d\'activité récente';
$LANGS['partnersettings'] = 'Paramètres du partenaire';
$LANGS['bannerimage'] = 'Image de bannière';
$LANGS['minibannerimage'] = 'Mini-image de bannière';
$LANGS['sideimage'] = 'Image latérale';
$LANGS['recommendedsize'] = 'Taille recommandée';
$LANGS['bannerlink'] = 'Site Web de la bannière';
$LANGS['sideimagelink'] = 'Site Web de l\'image latérale';
$LANGS['custombox'] = 'Boîte personnalisée';
$LANGS['customboxtitle'] = 'Titre de la boîte personnalisée';
$LANGS['customboxcontent'] = 'Contenu de la boîte personnalisée';
$LANGS['savechanges'] = 'Enregistrer les modifications';
$LANGS['submitimage'] = 'Soumettre l\'image';
$LANGS['overview'] = 'Aperçu';
$LANGS['profilesetup'] = 'Configuration du profil';
$LANGS['playbacksetup'] = 'Configuration de la lecture';
$LANGS['emailoptions'] = 'Options de messagerie électronique';
$LANGS['manageaccount'] = 'Gérer le compte';
$LANGS['chvideoviews'] = 'Vues vidéo';
$LANGS['change'] = "changement";
$LANGS['mynetwork'] = "Mon réseau";
$LANGS['contacts'] = "Contacts";
$LANGS['chvideocomments'] = "Commentaires vidéo";
$LANGS['chmore'] = "Plus";
$LANGS['changepicture'] = "Changer l'image";
$LANGS['changepicturedesc'] = "Vous pouvez télécharger un fichier JPG, BMP ou PNG. Ne téléchargez pas de photos contenant des célébrités, de la nudité, des œuvres d'art ou des images protégées par des droits d'auteur. Votre image sera affichée sous la forme d'un carré de 88 px sur 88 px. <b>La taille maximale du fichier est de 2 Mo.</b>";
$LANGS['describeyourself'] = "Décrivez-vous";
$LANGS['personaldetails'] = "Détails Personnels";
$LANGS['jobscareer'] = "Emplois / Carrière";
$LANGS['education'] = "Éducation";
$LANGS['videoplaybackquality'] = "Qualité de Lecture des Vidéos";
$LANGS['videoplaybackqualitydesc'] = "Choisissez le paramètre par défaut pour la visualisation des vidéos";
$LANGS['alwayshd'] = "Toujours lire les vidéos en qualité HD";
$LANGS['neverhd'] = "Ne jamais lire aucune vidéo en qualité HD";
$LANGS['currentemail'] = "Adresse Email Actuelle";
$LANGS['changeemailaddress'] = "Changer l'Adresse Email";
$LANGS['changeemail'] = "Changer l'Email";
$LANGS['partnerimages'] = "Images Partenaire";
$LANGS['partnerimagelinks'] = "Liens d'Images Partenaire";
$LANGS['accountstatuscg'] = "État du Compte : Règles de la Communauté";
$LANGS['accountstatuscopy'] = "État du Compte : Droits d'Auteur";
$LANGS['changeusername'] = "Changer le Nom d'Utilisateur";
$LANGS['changepassword'] = "Changer le Mot de Passe";
$LANGS['deleteaccount'] = "Supprimer le Compte";
$LANGS['goodaccount'] = "Votre compte est en bon état.";
$LANGS['accountstrike'] = "Vous avez {s} avertissement. Soyez prudent !";
$LANGS['accountstrikes'] = "Vous avez {s} avertissements. Soyez prudent !";
$LANGS['cannotchangeusername'] = "Vous ne pouvez pas encore changer votre nom d'utilisateur ! Veuillez attendre jusqu'à ";
$LANGS['usernamechangedesc'] = "Vous ne pourrez changer votre nom d'utilisateur qu'une fois par an, alors choisissez-le judicieusement.";
$LANGS['newusername'] = "Nouveau nom d'utilisateur";
$LANGS['currentpassword'] = "Mot de passe actuel";
$LANGS['newpassword'] = "Nouveau mot de passe";
$LANGS['confirmnewpassword'] = "Confirmer le nouveau mot de passe";
$LANGS['enterpassword'] = "Pour des raisons de sécurité, veuillez entrer votre mot de passe";

/* Upload page */
$LANGS['uploadpagetitle'] = 'Téléchargement de Vidéo';
$LANGS['step1of2'] = 'Étape 1 sur 2';
$LANGS['step2of2'] = 'Étape 2 sur 2';
$LANGS['videocategory'] = 'Catégorie de Vidéo';
$LANGS['tagsdesc'] = 'Les tags sont des mots-clés utilisés pour aider les gens à trouver votre vidéo.<br> <i>(séparés par des virgules)</i>';
$LANGS['requiredfield'] = '(* indique un champ obligatoire)';
$LANGS['datemapoptions'] = 'Options de Date et de Carte';
$LANGS['optional'] = '(optionnel)';
$LANGS['chooseoptions'] = 'choisissez les options';
$LANGS['lessoptions'] = 'moins d\'options';
$LANGS['addressrecorded'] = 'Adresse Enregistrée';
$LANGS['uploadcontinue'] = 'Télécharger une vidéo...';
$LANGS['file'] = 'Fichier';
$LANGS['broadcastoptions'] = 'Options de Diffusion';
$LANGS['uploadvideo'] = 'Télécharger la Vidéo';
$LANGS['needfilevideotoupload'] = 'Veuillez sélectionner un fichier vidéo à télécharger !';
$LANGS['aboutuploading'] = 'À propos du téléchargement...';
$LANGS['uploaddesc1'] = 'Les téléchargements prennent généralement de 1 à 5 minutes par Mo sur une connexion haut débit, et la conversion de votre vidéo prend quelques minutes.';
$LANGS['videolimit1'] = 'Votre vidéo est limitée à 100 Mo - la durée maximale de la vidéo est de 15 minutes.';
$LANGS['videolimit2'] = 'Votre vidéo est limitée à 2 Go - la durée maximale de la vidéo est de 15 minutes.';
$LANGS['partnervideolimit1'] = 'Votre vidéo est limitée à 100 Mo - la durée maximale de la vidéo est de 30 minutes.';
$LANGS['partnervideolimit2'] = 'Votre vidéo est limitée à 2 Go - la durée maximale de la vidéo est de 30 minutes.';
$LANGS['myvideosdesc'] = 'Après le téléchargement, vous pouvez modifier ou supprimer cette vidéo à tout moment sous le lien "<a href="/my_videos">Mes Vidéos</a>" en haut de la page.';
$LANGS['newuploader'] = 'Utiliser le nouvel outil de téléchargement de vidéos';
$LANGS['olduploader'] = 'Utiliser l\'ancien outil de téléchargement de vidéos';
$LANGS['videoadded'] = 'Votre vidéo a été ajoutée avec succès !';
$LANGS['videoaddeddesc'] = 'Votre vidéo est en cours de traitement et sera disponible dans quelques minutes.';
$LANGS['thankyou'] = 'Merci !';
$LANGS['sharelink'] = 'Partagez le lien de votre vidéo ! Copiez et collez ci-dessous :';
$LANGS['embedlink'] = 'Lisez cette vidéo directement SUR votre site web ! Copiez et collez le code suivant :';
$LANGS['allrequiredinfo'] = 'Veuillez remplir tous les champs obligatoires !';


/* Partners */
$LANGS['partnerhead'] = 'Partenariats';
$LANGS['partnertitle'] = 'Partenariat avec BitView';
$LANGS['partnerdesc'] = "Vous avez d'excellentes vidéos et un public croissant. Laissez BitView vous aider à passer à la vitesse supérieure grâce à notre programme de partenariat.";
$LANGS['applynow'] = 'Postulez maintenant';
$LANGS['contentpartners'] = 'Partenaires de Contenu';
$LANGS['partnerbenefits'] = 'Avantages du Partenariat';
$LANGS['partnerbenefitsdesc'] = 'Il y a de nombreux avantages à devenir partenaire BitView. Certains d\'entre eux incluent :<br><br>- Image de marque : démarquez-vous avec une image de marque personnalisée, comprenant des bannières, une boîte personnalisée pour votre chaîne et un badge de partenaire sur toutes vos vidéos.<br><br>- Il y aura d\'autres avantages à venir dans le futur !';
$LANGS['qualificationsfaq'] = 'Critères et FAQ';
$LANGS['qualificationsfaqdesc'] = 'Pour être éligible au programme de partenariat BitView, vous devez respecter certains critères minimums :<br><br>- Vous créez des vidéos originales adaptées à la diffusion en ligne.<br><br>- Vous avez plus de 75 abonnés.<br><br>- Votre compte ne viole aucune <a href="/guidelines">directive communautaire.</a>';

/* Staff */
$LANGS['bvstaff'] = 'Équipe BitView';
$LANGS['bvstaffdesc'] = "Voici la liste des personnes qui ont travaillé (ou travaillent encore) sur BitView - maintenant le site en vie - afin que les utilisateurs puissent s'exprimer.";
$LANGS['owners'] = 'Propriétaires';
$LANGS['ownerdesc'] = 'Les personnes qui - quelle surprise - possèdent la chose BitView.';
$LANGS['coowndev'] = 'Co-propriétaire & <br> Développeur';
$LANGS['owndev'] = 'Propriétaire & <br> Développeur';
$LANGS['coownserver'] = 'Co-propriétaire &<br>Propriétaire/Développeur du Serveur';
$LANGS['modsanddevs'] = 'Modérateurs et Développeurs';
$LANGS['modsanddevsdesc'] = 'Les personnes qui veillent à la sécurité et à la clarté du site. Vous avez un problème avec votre compte ? Vous devriez les contacter (en anglais, s\'il vous plaît !).';
$LANGS['moderator'] = 'Modérateur';
$LANGS['moddev'] = 'Développeur &<br>Modérateur';
$LANGS['lettertitle'] = 'Lettre à toutes les personnes qui ont aidé avec le site';
$LANGS['letter'] = "Chers Co-propriétaires, Développeurs et Modérateurs de BitView,<br><br>
                Au nom de toute l'équipe BitView, je tiens à exprimer ma gratitude sincère pour votre dévouement exceptionnel et votre travail acharné. En tant que l'un des propriétaires, cela me remplit de fierté de voir la croissance et le succès de notre plateforme de partage de vidéos, et cela n'aurait pas été possible sans vos contributions inestimables.
                <br><br>
                Aux autres Co-propriétaires, merci pour votre soutien indéfectible et votre vision. Votre engagement dans le développement et l'amélioration de la plateforme a été essentiel pour façonner BitView.net en la communauté remarquable qu'elle est aujourd'hui. Votre leadership et vos conseils stratégiques ont été cruciaux pour naviguer dans les défis et opportunités qui se sont présentés.
                <br><br>
                À nos talentueux Développeurs, votre expertise technique et vos idées innovantes ont transformé BitView en une plateforme de pointe qui représente parfaitement à quoi ressemblait YouTube à l'époque. Vos nombreuses heures de codage, de résolution de problèmes et d'implémentation de fonctionnalités ont rehaussé l'expérience utilisateur et ont fait de notre plateforme un centre de créativité et de divertissement. Votre dévouement à affiner la fonctionnalité et les performances du site est vraiment louable.
                <br><br>
                À nos Modérateurs diligents, j'exprime ma plus profonde reconnaissance pour maintenir l'intégrité et la sécurité de notre communauté. Votre vigilance dans l'application des règles et des lignes directrices, en veillant à des interactions respectueuses et en abordant rapidement tout problème qui se présente, a été crucial pour favoriser un environnement accueillant pour tous les utilisateurs. Vos efforts pour maintenir BitView comme un espace d'engagement constructif et de contenu positif sont hautement louables.
                <br><br>
                Ensemble, en tant qu'équipe unifiée, nous avons atteint d'importants jalons et surmonté de nombreux obstacles. Le succès de BitView témoigne de l'effort collectif et de la passion que chacun de vous apporte. Votre engagement envers notre vision partagée est vraiment inspirant, et je suis reconnaissant d'avoir de tels individus exceptionnels à mes côtés.
                <br><br>
                Alors que nous continuons à croître et à évoluer, chérissons les liens que nous avons forgés et restons attachés aux valeurs qui définissent notre petit site. Ensemble, nous continuerons ce voyage nostalgique et fournirons une plateforme pour que les créateurs puissent présenter leurs talents.
                <br><br>
                Encore une fois, merci : Co-propriétaires, Développeurs et Modérateurs, pour votre dévouement inébranlable, votre expertise et votre soutien indéfectible. Votre travail acharné n'est pas passé inaperçu, et je suis incroyablement fier de faire partie de cette équipe remarquable.
                <br><br>
                Continuez à vous exprimer,<br>
                <3 vistafan12";
$LANGS['backtobitview'] = "Retour à BitView";

/* My Friends */
$LANGS['myfriends'] = 'Mes Amis';
$LANGS['invites'] = 'Invitations';
$LANGS['myinvites'] = 'Mes Invitations';
$LANGS['incominginvites'] = 'Invitations Entrantes';
$LANGS['noinvites'] = 'Vous n\'avez aucune invitation...';
$LANGS['actions'] = 'Actions';
$LANGS['retract'] = 'Retirer';

/* History */
$LANGS['clearhistory'] = "Effacer l'historique de visionnage";
$LANGS['noviewinghistory'] = "Il n'y a pas de vidéos dans votre historique.";

/* QuickList */
$LANGS['playquicklist'] = "Lire la liste rapide";
$LANGS['clearquicklist'] = "Effacer la liste rapide";
$LANGS['noquicklist'] = "Il n'y a pas de vidéos dans votre liste rapide.";
$LANGS['noquicklistdesc'] = "La liste rapide vous permet de créer une liste de vidéos pour les visionner ultérieurement. Cliquez sur le signe « + » (en bas à gauche) de n'importe quelle vidéo pour l'ajouter à votre QuickList. Pour afficher votre liste, recherchez la barre QuickList sous n'importe quelle vidéo que vous regardez.";
$LANGS['quicklistcleared'] = "Votre liste rapide a été effacée avec succès.";
$LANGS['addedtoquicklist'] = "Ajouté à <br> la liste rapide";

/* About */
$LANGS['aboutus'] = 'À propos de nous';
$LANGS['abouttitle'] = 'Qu\'est-ce que BitView ?';
$LANGS['aboutdesc'] = 'BitView est une manière de diffuser vos vidéos aux personnes qui comptent pour vous. Avec BitView, vous pouvez :';
$LANGS['about1'] = 'Montrer vos vidéos préférées au monde';
$LANGS['about2'] = 'Filmer vos chiens, chats et autres animaux de compagnie';
$LANGS['about3'] = 'Bloguer les vidéos prises avec votre appareil photo numérique ou téléphone portable';
$LANGS['about4'] = 'Montrer vos vidéos de manière sécurisée et privée à vos amis et votre famille dans le monde entier';
$LANGS['about5'] = '... et bien plus encore !';
$LANGS['aboutsignup'] = '<a href="/signup">Inscrivez-vous maintenant</a> et ouvrez un compte gratuit.';
$LANGS['abouthelp'] = 'Pour en savoir plus sur notre service, consultez notre section <a href="help">Aide</a>.';
$LANGS['aboutmail'] = 'N\'hésitez pas à <a href="mailto:contact@vidlii.co">nous contacter</a>.';

/* Community Guidelines */
$LANGS['bvguidelines'] = 'Directives de la communauté BitView';
$LANGS['cgtitle1'] = 'Respectez la communauté BitView';
$LANGS['cgtitle2'] = "Ne franchissez pas la ligne";
$LANGS['cgtitle3'] = 'Nous appliquons ces directives';
$LANGS['cgtitle4'] = 'BitView est pour la communauté';
$LANGS['cgtitle5'] = 'Conseils pour les directives de la communauté';
$LANGS['cgdesc1'] = "Nous ne demandons pas le genre de respect réservé aux nonnes, aux personnes âgées et aux chirurgiens cérébraux. Nous voulons dire de ne pas abuser du site. Chaque nouvelle fonctionnalité communautaire géniale sur BitView implique un certain niveau de confiance. Nous comptons sur vous pour être responsables, et des millions d'utilisateurs respectent cette confiance. Soyez-en un.";
$LANGS['cgdesc2'] = "Voici quelques règles de bon sens qui vous aideront à éviter les ennuis :";
$LANGS['cgdesc3'] = "Veuillez prendre ces règles au sérieux et les assimiler. Ne cherchez pas de failles ou ne tentez pas de contourner les directives avec des arguments légaux - comprenez-les simplement et essayez de respecter l'esprit dans lequel elles ont été créées. Si vous souhaitez plus de détails, consultez nos <a href='#tips'>Conseils pour les directives de la communauté</a>.";
$LANGS['cgdesc4'] = "D'accord, celle-ci concerne plus nous que vous. Le personnel de BitView examine les vidéos signalées 24 heures sur 24, sept jours sur sept, pour déterminer si elles enfreignent nos directives de la communauté. Lorsqu'elles le font, nous les supprimons. Parfois, une vidéo ne viole pas nos directives de la communauté, mais peut ne pas être appropriée pour tout le monde. Ces vidéos peuvent être soumises à des restrictions d'âge. Les comptes sont pénalisés en cas de violation des directives de la communauté et des violations graves ou répétées peuvent entraîner la résiliation du compte. Si votre compte est résilié, vous ne serez pas autorisé à créer de nouveaux comptes. Pour plus d'informations sur la manière dont les directives de la communauté sont appliquées et les conséquences de leur violation, veuillez consulter le <a href='/help'>Centre d'aide</a>.";
$LANGS['cgdesc5'] = "N'oubliez pas que c'est votre communauté ! Chaque utilisateur de BitView contribue à faire du site ce qu'il est, alors n'hésitez pas à vous impliquer !";
$LANGS['cgdesc6'] = "C'est tout ! Merci de lire !";
$LANGS['cgdesc7'] = "Vous voulez un peu plus d'informations sur les limites et exceptions dans les directives de la communauté ? Voici quelques exemples et conseils utiles :";
$LANGS['rule1'] = "BitView n'est pas destiné à la pornographie ou au contenu sexuellement explicite. Si votre vidéo correspond à cette description, même s'il s'agit d'une vidéo de vous-même, ne la publiez pas sur BitView. De plus, sachez que nous collaborons étroitement avec les forces de l'ordre et signalons l'exploitation des enfants.";
$LANGS['rule2'] = "Ne publiez pas de vidéos montrant des actes répréhensibles tels que la maltraitance animale, l'abus de drogues, la consommation d'alcool et de tabac par des mineurs, ou la fabrication de bombes.";
$LANGS['rule3'] = "La violence graphique ou gratuite n'est pas autorisée. Si votre vidéo montre quelqu'un étant physiquement blessé, attaqué ou humilié, ne la publiez pas.";
$LANGS['rule4'] = "BitView n'est pas un site de choc. Ne publiez pas de vidéos choquantes montrant des accidents, des cadavres ou des choses similaires dans le but de choquer ou de dégoûter.";
$LANGS['rule5'] = "Respectez le droit d'auteur. Ne téléchargez que des vidéos que vous avez réalisées ou pour lesquelles vous avez l'autorisation d'utilisation. Cela signifie de ne pas télécharger de vidéos que vous n'avez pas réalisées, ou d'utiliser du contenu dans vos vidéos dont quelqu'un d'autre détient les droits d'auteur, tels que des morceaux de musique, des extraits de programmes protégés par le droit d'auteur ou des vidéos réalisées par d'autres utilisateurs, sans les autorisations nécessaires.";
$LANGS['rule6'] = "Nous encourageons la liberté d'expression et défendons le droit de chacun à exprimer des points de vue impopulaires. Cependant, nous n'autorisons pas la haine (discours attaquant ou dégradant un groupe en fonction de sa race ou de son origine ethnique, de sa religion, de son handicap, de son sexe, de son âge, de son statut de vétéran, et de son orientation sexuelle/identité de genre). Cela s'applique également à la promotion d'idéologies extrémistes de manière positive.";
$LANGS['rule7'] = "Les comportements prédateurs, le harcèlement, les menaces, l'intimidation, l'atteinte à la vie privée, la divulgation d'informations personnelles sur autrui, et l'incitation à la violence ou à la violation des Conditions d'utilisation sont pris très au sérieux. Toute personne surprise à faire ces choses peut être bannie de manière permanente de BitView.";
$LANGS['rule8'] = "Tout le monde déteste le spam. Ne créez pas de descriptions, tags, titres ou miniatures trompeurs dans le but d'augmenter les vues. Il n'est pas acceptable de publier de grandes quantités de contenu non ciblé, indésirable ou répétitif, y compris des commentaires et des messages privés.";
$LANGS['rule9'] = "Soyons prudents sur le site. Ne tentez pas de forcer un compte que vous ne possédez pas. De plus, partager publiquement les informations de connexion d'un compte n'est pas autorisé.";
$LANGS['rule10'] = "Les multi-comptes ne sont pas acceptables. Nous voulons des chiffres authentiques sur les vidéos et les chaînes. N'utilisez pas plus d'un compte pour évaluer des vidéos et/ou des commentaires. Vous n'êtes pas autorisé à utiliser plusieurs comptes pour vous abonner à vous-même non plus.";
$LANGS['rule11'] = "Vous avez enfreint l'une de ces règles et votre compte a été suspendu ? Il va sans dire qu'éviter cette sanction n'est pas accepté. Chaque nouveau compte créé par une personne suspendue sera automatiquement supprimé.";
$LANGS['cglist1'] = "Amusez-vous sur le site. Il y a beaucoup à voir ici, et beaucoup de gens créent des choses incroyables, l'un d'entre eux pourrait être vous ! L'équipement devient de moins en moins cher et plus facile à utiliser avec le temps, alors plongez et profitez-en.";
$LANGS['cglist2'] = "Faites savoir ce que vous pensez. Les commentaires font partie de l'expérience et, lorsqu'ils sont faits avec respect, peuvent être un excellent moyen de se faire des amis, de partager des histoires et d'enrichir votre expérience sur BitView. Laissez donc des commentaires, évaluez des vidéos, créez vos propres réponses aux vidéos qui vous touchent, participez à des concours intéressants, il y a beaucoup d'activités et de façons de participer.";
$LANGS['cglist3'] = "Vous n'aimerez peut-être pas tout ce que vous verrez. Certains contenus ici peuvent vous offenser - si vous trouvez qu'ils enfreignent nos Conditions d'utilisation, cliquez sur le bouton « Signaler » sous la vidéo que vous regardez pour la soumettre à l'examen du personnel de BitView. Sinon, envisagez simplement de cliquer sur autre chose - pourquoi perdre du temps à regarder des vidéos qui ne vous plaisent pas ?";
$LANGS['thebitviewteam'] = "— L'équipe BitView";
$LANGS['cgcat1'] = "Sexe et Nudité";
$LANGS['cgcat2'] = "Discours Haineux";
$LANGS['cgcat3'] = "Choquant et Dégoûtant";
$LANGS['cgcat4'] = "Actes Illégaux Dangereux";
$LANGS['cgcat5'] = "Enfants";
$LANGS['cgcat6'] = "Droit d'Auteur";
$LANGS['cgcat7'] = "Vie Privée";
$LANGS['cgcat8'] = "Harcèlement";
$LANGS['cgcat9'] = "Usurpation d'Identité";
$LANGS['cgcat10'] = "Menaces";
$LANGS['cgcat1desc'] = "La plupart de la nudité n'est pas autorisée, en particulier si elle est de nature sexuelle. En général, si une vidéo est destinée à être sexuellement provocante, elle a moins de chances d'être acceptable pour BitView. Il existe des exceptions pour certains contenus éducatifs, documentaires et scientifiques, mais uniquement si c'est le seul but de la vidéo et qu'elle n'est pas gratuitement explicite. Par exemple, un documentaire sur le cancer du sein serait approprié, mais publier des extraits hors contexte du documentaire pourrait ne pas l'être. Cela s'applique également au contenu animé.";
$LANGS['cgcat2desc'] = 'Le "discours haineux" fait référence à un contenu qui promeut la haine envers les membres d\'un groupe protégé. Par exemple, un contenu raciste ou sexiste peut être considéré comme un discours haineux. Parfois, il y a une fine ligne entre ce qui est considéré comme du discours haineux et ce qui ne l\'est pas. Par exemple, il est généralement acceptable de critiquer une nation, mais pas acceptable de faire des généralisations insultantes sur les personnes d\'une nationalité particulière.';
$LANGS['cgcat3desc'] = "Le monde est un endroit dangereux. Parfois, les gens se blessent et il est inévitable que ces événements soient documentés sur BitView. Cependant, il n'est pas acceptable de publier du contenu violent ou gore principalement destiné à être choquant, sensationnel ou irrespectueux. Si une vidéo est particulièrement graphique ou dérangeante, elle doit être équilibrée avec un contexte et des informations supplémentaires. Par exemple, inclure un extrait d'un abattoir dans une vidéo sur l'élevage industriel peut être approprié. Cependant, assembler des extraits non liés et macabres d'animaux abattus dans une vidéo peut être considéré comme gratuit si son but est de choquer plutôt qu'illustrer.";
$LANGS['cgcat4desc'] = "Bien qu'il puisse ne pas sembler juste de dire que vous ne pouvez pas montrer quelque chose en raison de ce que les téléspectateurs pourraient théoriquement faire en réponse, nous fixons une limite au contenu destiné à inciter à la violence ou à encourager des activités illégales et dangereuses présentant un risque inhérent de blessures graves ou de décès. Cela signifie de ne pas publier de vidéos sur des sujets tels que la fabrication de bombes, l'entraînement d'assassins ninja, les attaques de tireurs d'élite, les vidéos formant des terroristes ou des conseils sur les courses de rue illégales. Toutes les représentations de ce type doivent être éducatives ou documentaires et ne doivent pas être conçues pour aider ou encourager les autres à les imiter.";
$LANGS['cgcat5desc'] = "Les vidéos impliquant des enfants (personnes de moins de 18 ans) sont particulièrement sensibles. Les vidéos contenant des enfants ne doivent jamais être sexuellement suggestives ou violentes. Soyez prudent lorsque vous publiez quelque chose impliquant un enfant. Si vous partagez un moment privé ou un film familial, envisagez de le rendre privé afin que seuls votre famille et vos amis puissent le voir. De plus, en acceptant les <a href='/terms'>Conditions d'Utilisation</a>, vous affirmez avoir plus de 13 ans. Les comptes appartenant à des utilisateurs mineurs seront suspendus.";
$LANGS['cgcat6desc'] = "Lorsque vous créez quelque chose d'original, vous en détenez les droits d'auteur. De même, lorsque d'autres personnes créent du contenu, elles peuvent en détenir les droits d'auteur. En tant que communauté créative, il est essentiel que tout le monde sur BitView respecte les droits d'auteur des autres. Si vous n'êtes pas sûr que quelque chose violera les droits d'auteur de quelqu'un, la chose la plus sûre à faire est de créer quelque chose de complètement original, avec des images et des sons que vous avez créés. Si tout vous appartient, vous n'avez jamais à vous soucier du droit d'auteur, vous en êtes le propriétaire. Si vous avez enregistré quelque chose à partir d'un DVD, filmé votre écran de télévision ou téléchargé une vidéo en ligne, ne la publiez pas sauf si vous avez la permission.";
$LANGS['cgcat7desc'] = "Si une vidéo que vous avez enregistrée présente des personnes facilement identifiables et qui n'ont pas consenti à être filmées, il y a une chance qu'elles déposent une plainte pour atteinte à la vie privée demandant sa suppression. Nous vous informerons si cela se produit et vous donnerons la possibilité de modifier et de réuploader votre vidéo avant que nous n'agissions sur la plainte. Si nous retirons votre vidéo pour des raisons de confidentialité, ne téléchargez pas une autre version présentant les mêmes personnes. Il est probable que ces personnes déposent une nouvelle plainte pour atteinte à la vie privée ou vous signalent pour harcèlement. Ne publiez pas les informations personnelles d'autres personnes, y compris les numéros de téléphone, les adresses, les numéros de carte de crédit et les pièces d'identité gouvernementales. Nous sommes sérieux au sujet de la sécurité de nos utilisateurs et suspendons les comptes qui violent la vie privée des gens.";
$LANGS['cgcat8desc'] = "Cela se résume au respect. BitView consiste à partager et à interagir avec la communauté de manière respectueuse. Si vous n'êtes pas sûr que la vidéo ou le commentaire que vous avez fait franchit la ligne, suivez une règle simple : si vous ne le diriez pas en face de quelqu'un, ne le dites pas sur BitView. Et si vous cherchez à attaquer, harceler, rabaisser ou usurper l'identité des autres, allez ailleurs.";
$LANGS['cgcat9desc'] = "L'usurpation de l'identité d'un autre utilisateur en copiant la mise en page exacte du canal, en utilisant un nom d'utilisateur similaire ou en se faisant passer pour cette personne dans des commentaires, des e-mails ou des vidéos est considérée comme du harcèlement. Si vous voulez conserver votre compte, évitez de participer à toute forme d'usurpation ou d'activité de harcèlement sur le site.";
$LANGS['cgcat10desc'] = "Les utilisateurs ne devraient pas se sentir menacés lorsqu'ils sont sur BitView. Point final. Ne laissez pas de commentaires menaçants sur les vidéos des autres.";

/* Contests */
$LANGS['monthlycontest'] = "Concours Mensuel";
$LANGS['monthlycontestschedule'] = "Calendrier du Concours Vidéo Mensuel";
$LANGS['whatisit'] = "Qu'est-ce que c'est ?";
$LANGS['thismonthcontest'] = "Ce Mois-ci";
$LANGS['lastmonthwinners'] = "Gagnants du Mois Dernier";
$LANGS['howtoenter'] = "Comment participer ?";
$LANGS['whowins'] = "Qui gagne ?";
$LANGS['whowinsdesc'] = "Le gagnant sera choisi à la fin du mois par l'équipe BitView.";
$LANGS['theprize'] = "Le Prix ?";
$LANGS['theprizedesc'] = "La gloire, la fortune et la convoitise de tous les regards.";
$LANGS['contestsuggestion'] = 'Vous avez une suggestion pour un concours vidéo mensuel ? Veuillez <a href="mailto:contact@vidlii.co">nous en informer</a>.';

/* Help */
$LANGS['q1'] = 'Q : Comment puis-je partager mes vidéos et faire un lien vers elles depuis mon site web ?';
$LANGS['a1'] = 'R : <a href="/sharing">Comment partager et faire un lien vers vos vidéos</a>';
$LANGS['q2'] = 'Q : Quel type de vidéos puis-je télécharger ?';
$LANGS['a2'] = 'R : Vous pouvez télécharger n\'importe quel type de vidéo personnelle que vous souhaitez partager avec le monde. Nous n\'autorisons aucune nudité et votre vidéo doit être appropriée pour tous les publics.
<br/>
<br/>
Cela laisse cependant beaucoup de place à la créativité ! Possédez-vous un <a href="results?search=dog&t=Search+Videos">chien</a> ou un <a href="/results?search=cat&t=Search+Videos">chat</a> ? Êtes-vous parti en vacances au <a href="/results?search=mexico&t=Search+Videos">Mexique</a> ? Vivez-vous aux <a href="/results?search=netherlands&t=Search+Videos">Pays-Bas</a> ?
<br/>
<br/>
Ce ne sont que quelques exemples de vidéos que nos utilisateurs téléchargent. En fin de compte, vous vous connaissez le mieux. Qu\'aimeriez-vous capturer en vidéo ?';
$LANGS['q3'] = 'Q : Combien de temps ma vidéo peut-elle durer ?';
$LANGS['a3'] = 'R : La vidéo doit durer moins de 15 minutes et ne pas dépasser 2 Go en taille (100 Mo si vous utilisez un ancien navigateur).';
$LANGS['q4'] = 'Q : Quels formats de fichier vidéo puis-je télécharger ?';
$LANGS['a4'] = 'R : BitView accepte les fichiers vidéo de la plupart des appareils photo numériques et des téléphones portables aux formats de fichier .WMV, .AVI, .MOV, .MPG, .MP4.';
$LANGS['q5'] = 'Q : Comment puis-je améliorer mes vidéos ?';
$LANGS['a5'] = 'R : Nous vous encourageons à éditer vos vidéos avec des logiciels tels que <a href="https://windows-movie-maker-vista.en.softonic.com/" target="_blank">Windows Movie Maker</a> (fourni avec chaque installation Windows) ou <a href="https://www.apple.com/lae/imovie/" target="_blank">Apple iMovie</a>. En utilisant ces programmes, vous pouvez facilement éditer vos vidéos, ajouter des bandes sonores, etc.';
$LANGS['q6'] = 'Q : Est-ce que je conserve les droits d\'auteur et autres droits légaux sur mes vidéos ?';
$LANGS['a6'] = 'R : Oui. Vous conservez tous les droits sur votre contenu. BitView n\'assume aucun droit d\'auteur sur votre matériel.';
$LANGS['q7'] = 'Q : Quelle est votre politique en matière de violation du droit d\'auteur ?';
$LANGS['a7'] = "R : BitView respecte les droits des détenteurs de droits d'auteur et des éditeurs, et n'accepte que des téléchargements de vidéos de personnes détenant tous les droits nécessaires sur le matériel téléchargé. Notre politique consiste à répondre à toute notification de violation présumée conforme à la Loi sur le droit d'auteur du millénaire numérique (DMCA). Si nous recevons une notification ou avons d'autres raisons de croire que le contenu que vous avez soumis enfreint le droit d'auteur d'une autre partie, votre compte peut être résilié et la vidéo supprimée de BitView.";
$LANGS['q8'] = 'Q : Comment signaler une violation du droit d\'auteur ?';
$LANGS['a8'] = 'R : Si vous pensez que quelqu\'un d\'autre a téléchargé votre contenu protégé par le droit d\'auteur sans votre autorisation, nous vous encourageons à contacter directement cette personne pour résoudre tout différend. Vous pouvez également contacter notre équipe d\'assistance via cet <a href="mailto:contact@vidlii.co">e-mail</a>.';
$LANGS['q9'] = 'Q : Et si l\'on m\'accusait à tort de violation du droit d\'auteur ?';
$LANGS['a9'] = "R : Nous vous informerons si nous recevons une plainte de droit d'auteur concernant l'un de vos contenus vidéo hébergés sur BitView. Nous vous donnerons l'occasion de répondre de manière appropriée.";
$LANGS['q10'] = 'Q : Que faites-vous pour empêcher l\'apparition de contenu en violation de vos politiques sur BitView ?';
$LANGS['a10'] = 'R : Nous effectuons une revue préliminaire des vidéos téléchargées par le biais d\'un processus manuel et automatisé. Bien que nous essayions de détecter et de supprimer les vidéos en violation de nos directives de politique, notre processus de revue est principalement axé sur la suppression du contenu pour adultes ou des violations de droits d\'auteur évidentes, et n\'est pas infaillible. Cependant, nous encourageons nos téléspectateurs à nous informer lorsqu\'ils découvrent des violations de politique signalées ou des problèmes de droits d\'auteur. Nous avons un processus d\'examen des violations de politique signalées et nous répondons aux violations de droits d\'auteur signalées en vertu de la Loi sur le droit d\'auteur du millénaire numérique.';
$LANGS['q11'] = 'Q : Avez-vous un serveur Discord ou un compte Twitter ?';
$LANGS['a11'] = 'Oui ! Nous avons effectivement un serveur Discord et un compte Twitter. Vous pouvez rejoindre le serveur Discord en cliquant <a href="https://discord.gg/wgGaqCmwuQ">ici</a> et nous suivre sur Twitter <a href="https://twitter.com/bitview_">ici</a>.';
$LANGS['q12'] = "Q : J'utilise un vieux navigateur sur BitView et je ne peux donc pas regarder les vidéos. Que puis-je faire ?";
$LANGS['activate'] = 'Activer';
$LANGS['deactivate'] = 'Désactiver';
$LANGS['flashdisclaimer'] = "<b>Remarque :</b> Le lecteur Flash de BitView est proposé en tant qu'option de compatibilité. Si votre navigateur prend en charge le lecteur HTML5 de BitView, vous ne devez pas activer cette option.";

/* BitView on your site */
$LANGS['bvsitetitle1'] = "Les bases";
$LANGS['bvsitetitle2'] = "APIs et Engagement Utilisateur";
$LANGS['bvsitedesc1'] = "Peu importe la présence que vous avez sur Internet – un grand site web, un blog, une page de réseau social, ou à peu près n'importe quoi d'autre – il existe de nombreuses façons d'intégrer BitView. Des simples vidéos intégrées à nos APIs puissantes, vous pouvez intégrer des vidéos à tous les niveaux de compétence technique.";
$LANGS['bvsitedesc2'] = "Intégrer BitView sur votre site ne se limite pas à ajouter certaines des milliers de vidéos disponibles sur BitView. Cela maintient l'intérêt de vos visiteurs, permet l'expression personnelle et l'interaction avec l'un de leurs services préférés. Et cela intègre votre site, blog ou page dans la communauté vidéo BitView – un réseau international d'utilisateurs, de créateurs et de sites connectés par une vaste collection de vidéos en ligne.";
$LANGS['bvsitedesc3'] = "Nous avons mis en évidence quelques façons typiques d'intégrer du contenu vidéo ci-dessous – il suffit de cliquer sur la flèche à côté de la question pour obtenir la réponse. Si vous avez des questions, des suggestions, ou des projets dont vous souhaitez nous faire part, veuillez les laisser dans notre <a href='https://discord.gg/wgGaqCmwuQ'>serveur Discord</a>.";
$LANGS['bvsitesectiontitle1'] = "Comment ajouter une vidéo à mon blog ou ma page web ?";
$LANGS['bvsitesectiontitle2'] = "Comment ajouter une vidéo à ma page de réseau social ?";
$LANGS['bvsitesectiontitle3'] = "Je travaille pour une grande entreprise de blog/web. Comment la vidéo peut-elle augmenter l'engagement des utilisateurs sur notre site ?";
$LANGS['bvsitesectiontitle4'] = "Nous avons un site et nous avons nos propres vidéos. Pouvons-nous les publier sur notre site en utilisant BitView ?";
$LANGS['bvsitesection1desc1'] = "Vous devrez éditer le HTML de votre billet de blog ou de votre page – cela devrait être relativement simple. Sur Blogger, par exemple, cliquez simplement sur l'onglet \"Modifier HTML\".";
$LANGS['bvsitesection1desc2'] = "Ensuite, allez à la vidéo que vous souhaitez et recherchez la boîte 'Intégrer' dans la section 'À propos de cette vidéo'. Copier le code HTML qui s'y trouve dans votre site web créera un lecteur intégré ; la vidéo se lira sur votre site lorsque l'utilisateur cliquera sur le bouton 'Lire'.";
$LANGS['bvsitesection1desc3'] = "Vous pouvez redimensionner le lecteur en modifiant les champs <em>object width=\"425\"</em> et <em>height=\"350\"</em> au début et à la fin du code du lecteur intégré. Assurez-vous que les tailles que vous choisissez ont le même rapport que les nombres par défaut, afin que la vidéo ne soit pas étirée – multipliez simplement la largeur par 0,8235 pour obtenir la hauteur.";
$LANGS['bvsitesection2desc1'] = "Ajouter des vidéos à vos profils sur des réseaux sociaux comme SpaceHey est un excellent moyen de partager vos vidéos ou favoris avec vos amis. Ou, si vous promouvez quelque chose (comme votre groupe) sur SpaceHey, les vidéos aideront à attirer des visiteurs sur votre page, qui pourront ensuite partager le lien avec leurs amis. Les sites de réseaux sociaux ont des façons similaires d'ajouter des vidéos, nous utiliserons donc SpaceHey comme exemple.";
$LANGS['bvsitesection2desc2'] = 'Connectez-vous à votre profil SpaceHey, puis cliquez sur le bouton "Modifier le profil".';
$LANGS['bvsitesection2desc3'] = "Ensuite, allez à la vidéo que vous souhaitez et recherchez la boîte 'Intégrer' dans la section 'À propos de cette vidéo'. Copier le code HTML qui s'y trouve dans votre site web créera un lecteur intégré.";
$LANGS['bvsitesection2desc4'] = "Vous pouvez redimensionner le lecteur en modifiant les champs object width=\"425\" et height=\"350\" au début et à la fin du code du lecteur intégré. Assurez-vous que les tailles que vous choisissez ont le même rapport que les chiffres par défaut, afin que la vidéo ne soit pas étirée – multipliez simplement la largeur par 0,8235 pour obtenir la hauteur.";
$LANGS['bvsitesection2desc5'] = 'Cliquez sur "Aperçu", puis sur "Soumettre".';
$LANGS['bvsitesection3desc1'] = "La vidéo est beaucoup plus engageante que le texte. Elle attire plus d'utilisateurs et les maintient sur votre site plus longtemps. BitView dispose d'un vaste répertoire de contenus vidéo sur Internet ainsi que des outils de recherche, de lecture et d'API pour faciliter l'ajout de vidéos pour vous.";
$LANGS['bvsitesection3desc2'] = "Lorsque vous cherchez à augmenter l'engagement, essayez d'utiliser la vidéo comme moyen de démarrer une discussion ou de faire un commentaire en fournissant plus de contexte à vos utilisateurs :";
$LANGS['bvsitesection4desc1'] = "Il est très facile de développer votre propre site avec vos propres vidéos gratuitement. Il vous suffit de télécharger d'abord les vidéos sur BitView. Il n'y a pas de frais et nous couvrirons les coûts d'hébergement et de diffusion. C'est non seulement un excellent moyen d'augmenter l'engagement des utilisateurs sur votre site, mais c'est aussi très facile et gratuit.";
$LANGS['bvsitesection4desc2'] = "Une fois que vous avez téléchargé les vidéos, vous pouvez les ramener sur le site :";
$LANGS['bvsitesection4desc3'] = "<b>Intégrer les vidéos une par une :</b> Allez à la vidéo que vous souhaitez mettre sur votre site, et recherchez la boîte 'Intégrer' à côté du lecteur vidéo. Copier le code HTML qui s'y trouve dans votre blog créera un lecteur intégré ; la vidéo se lira sur votre site lorsque l'utilisateur cliquera sur le bouton 'Lire'.";

/* RSS Feeds */
$LANGS['rsstitle1'] = "Qu'est-ce que les flux RSS ?";
$LANGS['rsstitle2'] = "Comment accéder aux flux RSS";
$LANGS['rsstitle3'] = "Comment s'abonner aux flux RSS de BitView";
$LANGS['rssdesc1'] = "La syndication vraiment simple (RSS) est un format basé sur XML utilisé pour la distribution et la syndication de contenu. S'abonner aux flux RSS vous permet de recevoir des informations personnalisées et à jour de vos sources de contenu en ligne préférées sans avoir à vérifier régulièrement le site pour les mises à jour.";
$LANGS['rssdesc2'] = "Les lecteurs de nouvelles affichent les flux RSS des sites web que vous spécifiez. Ils vérifient les flux RSS auxquels vous vous êtes abonnés et affichent les nouveaux éléments de chaque flux. Vous pouvez télécharger des applications de lecteur de nouvelles pour votre ordinateur, et il existe également de nombreux lecteurs de nouvelles basés sur le web populaires, tels que Google Reader et Bloglines. Certains navigateurs web et applications de messagerie ont également des capacités RSS intégrées.";
$LANGS['rssdesc3'] = "Vous pouvez voir une liste de nombreux lecteurs de nouvelles disponibles sur <a href='http://fr.wikipedia.org/wiki/Liste_de_lecteurs_de_flux'>Wikipédia</a>."; //Utilisez l'article Wikipédia de votre langue si possible
$LANGS['rssdesc4'] = "BitView propose plusieurs flux RSS pour des groupes de vidéos catégorisés (comme les vidéos récemment téléchargées, les plus vues, etc.) ainsi que des flux personnalisés pour les utilisateurs et les balises.";
$LANGS['rssdesc5'] = "Pour vous abonner à des groupes de vidéos catégorisés, il vous suffit de vous rendre dans la catégorie que vous souhaitez (par exemple, &quot;<a href='/browse'>Les plus vues - Aujourd'hui</a>&quot;). Ensuite, cliquez sur le bouton 'RSS' orange. Cela devrait déclencher l'ajout de l'abonnement dans votre lecteur de nouvelles choisi.";
$LANGS['rssdesc6'] = "Si votre navigateur a des capacités RSS, vous pouvez ajouter le flux à partir de là. La commande varie d'un navigateur à l'autre, mais peut généralement être trouvée dans les menus 'Fichier' ou 'Signets', et s'appellera quelque chose comme &quot;S'abonner à cette page&quot; ou &quot;Nouveau signet dynamique&quot;.";
$LANGS['rssthispage'] = "RSS de cette page";

/* TestView */
$LANGS['testviewdesc'] = "Bienvenue sur TestView, notre incubateur d'idées. C'est ici que les ingénieurs et développeurs de BitView testent des recettes et concoctions qui ne sont pas tout à fait prêtes et vous invitent à nous dire ce que vous en pensez.";
$LANGS['flashvideo'] = "Vidéo Flash";
$LANGS['flashvideodesc'] = "Votre navigateur ne prend pas en charge la vidéo HTML5 ? Ne vous inquiétez pas ! Essayez notre lecteur Flash.";
$LANGS['feather'] = "Feather";
$LANGS['featherdesc'] = "Visionnez les vidéos BitView sur une page à latence ultra basse.";
$LANGS['tryitout'] = "Essayez-le";
$LANGS['disabletest'] = "Désactiver";
$LANGS['timemachine'] = "Machine à remonter le temps";
$LANGS['timemachinedesc'] = "Revenez en arrière dans le temps, en remontant chaque date sur BitView jusqu'aux années 2000.";
$LANGS['lightsout'] = "Extinction des feux";
$LANGS['lightsoutdesc'] = "Vous en avez assez de voir le blanc le plus éclatant sur votre écran ? Mettez-le en noir et essayez une nouvelle interface cool.";
$LANGS['featherenabled'] = '"Feather" est maintenant activé !';
$LANGS['timemachineenabled'] = '"Machine à remonter le temps" est maintenant activée !';
$LANGS['lightsoutenabled'] = '"Extinction des feux" est maintenant activée !';
$LANGS['featherdisabled'] = '"Feather" est maintenant désactivé !';
$LANGS['timemachinedisabled'] = '"Machine à remonter le temps" est maintenant désactivée !';
$LANGS['lightsoutdisabled'] = '"Extinction des feux" est maintenant désactivée !';

/* Footer */
$LANGS['youraccount'] = 'Votre compte';
$LANGS['inbox'] = 'Boîte de réception';
$LANGS['footmore'] = 'plus...';
$LANGS['helpinfo'] = 'Aide';
$LANGS['helpcenter'] = 'Obtenir de l\'aide';
$LANGS['ourtwitter'] = 'Notre Twitter';
$LANGS['ourdiscord'] = 'Notre Discord';
$LANGS['guidelines'] = 'Directives de la communauté';
$LANGS['partnerships'] = 'Partenariats';
$LANGS['terms'] = 'Conditions d\'utilisation';
$LANGS['privacypolicy'] = 'Politique de confidentialité';
$LANGS['currentlanguage'] = 'Langue actuelle';
$LANGS['showlanguages'] = 'Afficher les langues';
$LANGS['setlanguagepref'] = 'Définir votre préférence de langue';
$LANGS['programs'] = 'Programmes';
$LANGS['developers'] = 'Développeurs';
$LANGS['bitviewblog'] = 'Blog BitView';
$LANGS['policy'] = 'Politique';
$LANGS['discover'] = 'Découvrir';
$LANGS['bvphone'] = 'BitView sur votre téléphone';
$LANGS['bvsite'] = 'BitView sur votre site';
$LANGS['bvrss'] = 'Flux RSS BitView';
$LANGS['mobile'] = 'Mobile';

?>
