<?php
/* General stuff */
$LANGS['language'] = 'Hrvatski (HR)'; 
$LANGS['languageenglish'] = 'Croatian (HR)'; 
$LANGS['languagecode'] = 'hr_HR.UTF-8'; 
$LANGS['languagechange'] = 'Postavljen je jezik na Hrvatskom (HR).';
$LANGS['numberformat'] = 1; /* If your language uses comma separators (example: 1,000,000), value will be 1. If it uses dots (example: 1.000.000) or doesn't use separators, value will be 0.*/

/* Language window */
$LANGS['welcometobitview'] = 'Dobrodošli u BitView!';
$LANGS['languagesuggestion'] = 'Preporučeni Jezici (postavili smo vašu preferenciju na ovo):';
$LANGS['languagesuggestiondesc1'] = 'Za promjenu jezičnih postavki, molimo da koristite birač jezika u podnožju (na kraju stranice).';
$LANGS['languagesuggestiondesc2'] = 'Kliknite "OK" da biste prihvatili ovu postavku ili kliknite "Odustani" da biste vidjeli stranicu na hrvatskom.';

/* Time, dates, etc */
$LANGS['second'] = 'sekunda';
$LANGS['minute'] = 'minuta';
$LANGS['hour'] = 'sat';
$LANGS['day'] = 'dan';
$LANGS['week'] = 'tjedan';
$LANGS['month'] = 'mjesec';
$LANGS['year'] = 'godina';
$LANGS['seconds'] = 'sekunde';
$LANGS['minutes'] = 'minute';
$LANGS['hours'] = 'sati';
$LANGS['days'] = 'dana';
$LANGS['weeks'] = 'tjedna';
$LANGS['months'] = 'mjeseca';
$LANGS['years'] = 'godine';
$LANGS['ago'] = 'pred {t}';
$LANGS['january'] = 'Siječanj';
$LANGS['february'] = 'Veljača';
$LANGS['march'] = 'Ožujak';
$LANGS['april'] = 'Travanj';
$LANGS['may'] = 'Svibanj';
$LANGS['june'] = 'Lipanj';
$LANGS['july'] = 'Srpanj';
$LANGS['august'] = 'Kolovoz';
$LANGS['september'] = 'Rujan';
$LANGS['october'] = 'Listopad';
$LANGS['november'] = 'Studeni';
$LANGS['december'] = 'Prosinac';
$LANGS['shorttimeformat'] = '%b %e, %Y';
$LANGS['videotimeformat'] = '%b %e, %Y';
$LANGS['longtimeformat'] = '%B %e, %Y';
$LANGS['timehourformat'] = '%b %e, %Y %I:%M %p';
$LANGS['myvideostimeformat'] = '%A, %b %e %Y, %I:%M:%S %p';
$LANGS['blogpostformat'] = '%A, %B %e, %Y';
$LANGS['monthformat'] = '%B %Y';
$LANGS['timenumberformat'] = 'd.m.Y';

/* Header */
$LANGS['home'] = 'Početna Stranica';
$LANGS['videos'] = 'Videozapisi';
$LANGS['channels'] = 'Kanali';
$LANGS['community'] = 'Društva';
$LANGS['search'] = 'Pretraži';
$LANGS['login'] = 'Prijava';
$LANGS['or'] = 'ili';
$LANGS['signup'] = 'Izradi račun';
$LANGS['logout'] = 'Odjava';
$LANGS['upload'] = 'Prenesi';
$LANGS['subscriptions'] = 'Pretplate';
$LANGS['history'] = 'Povijest';
$LANGS['account'] = 'Račun';
$LANGS['myvideos'] = 'Moji Videozapisi';
$LANGS['favorites'] = 'Omiljeni';
$LANGS['playlists'] = 'Popisi';
$LANGS['help'] = 'Pomoć';
$LANGS['suggestions'] = 'Prijedlozi';
$LANGS['quicklist'] = 'QuickList';
$LANGS['browse'] = 'Pregledavanje';
$LANGS['messagesmenu'] = 'Poruke';

/* Homepage */
$LANGS['viewall'] = 'pogledajte sve';
$LANGS['videoviews'] = 'pregleda';
$LANGS['beingwatched'] = 'Trenutno gledani videozapisi';
$LANGS['featured'] = 'Istaknuti videozapisi';
$LANGS['recommendedforyou'] = 'Preporučeno za vas';
$LANGS['mostpopular'] = 'Najpopularnije';
$LANGS['inboxstats'] = 'Pošta i Statistika';
$LANGS['profilesettings'] = 'postavke na računu'; 
$LANGS['messages'] = 'Poruke';
$LANGS['message'] = 'Poruka';
$LANGS['comments'] = 'Komentari';
$LANGS['comment'] = 'Komentar';
$LANGS['sharedwithyou'] = 'Podijeljeno s vama';
$LANGS['sharedwithyousingular'] = 'Podijeljeno s vama';
$LANGS['videoresponses'] = 'Video odgovori';
$LANGS['videoresponse'] = 'Video odgovor';
$LANGS['friendinvites'] = 'Prijateljske pozivnice';
$LANGS['friendinvite'] = 'Prijateljska pozivnica';
$LANGS['subscribers'] = 'Pretplatnici';
$LANGS['subscriber'] = 'Pretplatnik';
$LANGS['totalviews'] = 'Ukupno pregleda';
$LANGS['sendmessage'] = 'pošalji poruku';
$LANGS['whatsnew'] = "Što je novo";
$LANGS['readmore'] = 'Pročitajte više u našem Blog-u';
$LANGS['videocontest'] = 'Video Natjecanje';
$LANGS['joincontest'] = 'Pridružite se natjecanju sad!'; 
$LANGS['personalize'] = 'Želite personalizirati ovu početnu stranicu?';
$LANGS['signinnow'] = '<a href="/login">Prijavite se</a> ili <a href="/signup">Izradite račun</a> sada!';
$LANGS['nowconverting'] = "Ovaj video se postavlja, pričekajte par minuta.";
$LANGS['modules'] = "Dodaj / Ukloni Module";
$LANGS['friendactivity'] = "Aktivnost prijatelja";
$LANGS['customizehomepage'] = "Prilagodite početnu stranicu";
$LANGS['customizethehomepage'] = "Prilagodite početnu stranicu";
$LANGS['customizehomepagedesc'] = "Odaberite module koje želite vidjeti na vašoj prilagođenoj početnoj stranici.";
$LANGS['displaypreferences'] = "Postavke prikaza";
$LANGS['thefeed'] = "Feed";
$LANGS['thefeeddesc'] = "Kombinirajte sve svoje module u jedan feed.";
$LANGS['friendactivitytitle'] = "Aktivnost prijatelja - Mogu li ljudi vidjeti što radim?";
$LANGS['friendactivitydesc'] = "This section shows your confirmed friends the actions that you're publicly broacasting in your recent activity history. For example, if you favorite a video, then your new favorite video might show up in your channel's Recent Activity box, as well as on your friends' homepages.";
$LANGS['feedfeatured'] = "Istaknuti videozapis";
$LANGS['feedbeingwatched'] = 'Trenutno gledani videozapis';
$LANGS['feedrecommended'] = "Preporučeni videozapis";
$LANGS['homenosubscriptions'] = "Još se niste pretplatili ni na jedan kanal.";
$LANGS['homenosubscriptionsdesc'] = "Kada dodate pretplate, mi ćemo pokazivati njihove prijenose na ovoj stranici.";
$LANGS['homenofriendactivity'] = "Vaši prijatelji nisu bili aktivni u posljednje vrijeme.";
$LANGS['homenofriendactivitydesc'] = "Možete probati dodati neke prijatelje. Zatim ćemo prikazati njihovu aktivnost ovdje na ovoj stranici.";
$LANGS['homeediting'] = "Uređivanje";
$LANGS['homedisplay'] = "Prikaži kao";
$LANGS['homerows'] = "Broj redaka za prikaz";
$LANGS['gridview'] = "Mrežni prikaz";
$LANGS['listview'] = "Popisni prikaz";

/* Page title */
$LANGS['hometitle'] = "{n}-ov BitView";
$LANGS['channeltitle'] = "{n}-ov Kanal";
$LANGS['signintitle'] = "Prijava";
$LANGS['historytitle'] = "Povijest pregleda";
$LANGS['favtitle'] = "Omiljeni";
$LANGS['pltitle'] = "Popisi";
$LANGS['partnerprogram'] = "Partner Program";

/* Notifications */
$LANGS['searcherror'] = 'Vaš upit za pretraživanje mora imati najmanje 2 znakova!';
$LANGS['addvideoplaylist1'] = "Dodali ste"; 
$LANGS['addvideoplaylist2'] = 'videozapise na vašem popisu!';  
$LANGS['addfavorite1'] = "Dodali ste"; 
$LANGS['addfavorite2'] = 'videozapisa u popis omiljenih!'; 
$LANGS['groupdoesnotexist'] = "Ova grupa ne postoji!";
$LANGS['uploaddisabled'] = 'Prijenos videozapisa je onemogućeno zbog održavanja.';
$LANGS['10vidsday'] = 'Ne možete prenijeti više nego 10 videozapisa po danu! Molimo da probate prenijeti sutra.';
$LANGS['3mins'] = 'Pričekajte 3 minute prije nego što prenosite novi videozapis!';
$LANGS['backgroundsuccess'] = 'Pozadina se uspješno postavila!';
$LANGS['backgrounderror'] = 'Pozadinska slika mora biti ispod 2MB i mora biti slikovna datoteka!';
$LANGS['backgrounddeleted'] = 'Pozadina se uspješno uklonila!';
$LANGS['bannersuccess'] = 'Natpis je uspješno postavljen!';
$LANGS['bannererror'] = 'Natpis mora biti ispod 2MB i mora biti slikovna datoteka!';
$LANGS['bannerdeleted'] = 'Vaš natpis je uspješno uklonjen!';
$LANGS['minibannersuccess'] = 'Manji natpis je uspješno postavljen!';
$LANGS['minibannererror'] = 'Manji natpis mora biti ispod 2MB i mora biti slikovna datoteka!';
$LANGS['minibannerdeleted'] = 'Vaš manji natpis je uspješno uklonjen!';
$LANGS['sideimagesuccess'] = 'Slika sa strane je uspješno postavljena!';
$LANGS['sideimageerror'] = 'Slika sa strane mora biti ispod 2MB i mora biti slikovna datoteka!';
$LANGS['sideimagedeleted'] = 'Vaša slika sa strane je uspješno uklonjena!';
$LANGS['avatarsuccess'] = 'Avatar je uspješno postavljen!';
$LANGS['avatarerror'] = 'Avatar mora biti ispod 2MB i mora biti slikovna datoteka!';
$LANGS['avatardeleted'] = '"Avatar se uspješno uklonila!';
$LANGS['changessaved'] = 'Promjene su uspješno spremljene!';
$LANGS['profilesdisabled'] = 'Profili su onemogućene zbog održavanja.';
$LANGS['bulletinposted'] = 'Bulletin je poslan!';
$LANGS['channelcommentsent'] = 'Komentar na kanalu je poslan!';
$LANGS['somethingwentwrong'] = 'Nešto nije u redu!'; 
$LANGS['replysubmitted'] = 'Odgovor je poslan!';
$LANGS['onlyonecomment'] = 'Možete ostaviti samo jedan komentar!';
$LANGS['vpnbrowser'] = "Ne možete koristiti VPN da izradite BitView račun!";
$LANGS['torbrowser'] = "Ne možete koristiti TOR da izradite BitView račun!";
$LANGS['captchaincorrect'] = "Niste točno unijeli kod.";
$LANGS['toomanyaccounts'] = 'Imate previše računa!';
$LANGS['banned2times'] = "Već su vam 2 računa zabranjena. Ne možete više izraditi račun!"; 
$LANGS['nohistory'] = "Niste pogledali niti jedan videozapis u ovoj sesiji!";
$LANGS['historycleared'] = 'Vaš povijest pregledavanja je očišćen.';
$LANGS['watchdisabled'] = 'Gledanje videozapisa je onemogućeno zbog održavanja.';
$LANGS['videonotexist'] = 'Ovaj videozapis ne postoji ili je bio izbrisan zbog kršenja Uvjeta Korištenja.';
$LANGS['responseerror'] = 'Nešto nije u redu s vašim video odgovorom! Molimo pregledajte URL opet.';
$LANGS['responseexist'] = 'Videozapis je već zatražen!';
$LANGS['responseadded'] = 'Video odgovor je uspješno dodan!';
$LANGS['responseaccepted'] = 'Prihvaćen je novi video odgovor!';
$LANGS['60secscomment'] = 'Molimo sačekajte 60 sekundi prije nego što objavite novi komentar!';
$LANGS['plnotexist'] = "Ovaj popis ne postoji!";
$LANGS['positionnotexist'] = "Ova pozicija ne postoji!";
$LANGS['positionchanged'] = "Pozicija videozapisa je izmijenjena!";
$LANGS['invalidurl'] = 'Neispravni URL!';
$LANGS['videopladded'] = 'Videozapis je uspješno dodan!';
$LANGS['videoalreadyinpl'] = 'Ovaj videozapis već je u ovom popisu!';
$LANGS['plvideoremoved'] = 'Videozapis je uklonjen!';
$LANGS['plinfochanged'] = 'Informacija popisa je uspješno promjenjen!';
$LANGS['pltitleneeded'] = 'Morate postaviti titulu za popis!';
$LANGS['flashenabled'] = 'Adobe Flash Player je omogućen!';
$LANGS['flashdisabled'] = 'Adobe Flash Player je onemogućen!';
$LANGS['messagesent'] = 'Poruka je uspješno poslana!';
$LANGS['usernotexist'] = "Ovaj korisnik ne postoji!";
$LANGS['nocriteria'] = "Ne ispunjavate očekivanu kriteriju!";
$LANGS['alreadypartner'] = 'Več ste bili prihvaćeni u partnerski program!';
$LANGS['alreadyapplied'] = 'Već ste se prijavili!'; 
$LANGS['applicationsent'] = 'Vaša zahtjev je poslan!';
$LANGS['joinedgroup'] = 'Uspješno ste se pridružili grupi!';
$LANGS['leftgroup'] = 'Uspješno ste izašli iz grupe!';
$LANGS['grouprequest'] = 'You successfully sent a group request! Now you must wait for it to be accepted.';
$LANGS['groupdeleted'] = 'Grupa je uspješno izbrisana!';
$LANGS['groupvideoadded'] = 'Videozapis je poslan!';
$LANGS['groupvideoalreadyadded'] = 'Već ste poslali ovaj videozapis!';
$LANGS['groupvideonotowned'] = "Vi ne posjedujete ovaj videozapis!";
$LANGS['3groups'] = 'Možete biti vlasnik od najviše 3 grupa!';
$LANGS['groupnameempty'] = 'Ime grupe ne može biti prazan!';
$LANGS['groupdescempty'] = 'Opis grupe ne može biti prazan!';
$LANGS['groupnoimage'] = 'Morate objaviti sliku za vašu grupu!';
$LANGS['groupimageerror'] = 'Grupna slika mora biti ispod 1MB i mora biti slikovna datoteka!';
$LANGS['groupcreated'] = 'Grupa je uspješno napravljena!';
$LANGS['urlnotvalid'] = "Ovo nije ispravan URL!";
$LANGS['discussiondeleted'] = 'Rasprava je uspješno izbrisana!';
$LANGS['videodeleted'] = 'Videzapis je uspješno izbrisan!';
$LANGS['pldeleted'] = 'Popis je uspješno izbrisan!';
$LANGS['invitesent'] = 'Poziv za prijetaljstvo je uspješno poslan!';
$LANGS['descriptionchanged'] = 'Opis je upravo promijenjen!';
$LANGS['emptymessage'] = 'Ne možete slati prazne poruke!';
$LANGS['styleupdated'] = 'Stil grupe je uspješno promijenjen!';
$LANGS['imageupdated'] = 'Grupna slika je uspješno promijenjena!';
$LANGS['plcreated'] = 'Popis je uspješno napravljen!';
$LANGS['discussiontitle2chars'] = 'Naslov mora imati više od 2 znakova!';
$LANGS['discussiondesc10chars'] = 'Opis mora imati više od 10 znakova!';
$LANGS['5discussionsday'] = 'Možete imati do 10 rasprava na dan!';
$LANGS['discussionsuccess'] = 'Rasprava je uspješno napravljena!';
$LANGS['memberaccepted1'] = '';
$LANGS['memberaccepted2'] = 'je uspješno prihvatio!';
$LANGS['memberdeclined1'] = '';
$LANGS['memberdeclined2'] = 'je uspješno odbio!';
$LANGS['videoaccepted'] = 'Videozapis je uspješno prihvaćen!';
$LANGS['bulletindeleted'] = 'Bulletin je uspješno izbrisan!';
$LANGS['messagedeleted'] = 'Poruka je uspješno izbrisana!';
$LANGS['responsedeleted'] = 'Video odgovor je uspješno izbrisan!';
$LANGS['flagmod'] = 'Ne možete prijaviti korisnika koji imaju dozvole moderatora!';
$LANGS['userflagged'] = 'Prijava je poslana!';
$LANGS['discussionreplysubmitted'] = 'Odgovor je uspješno poslan!';
$LANGS['discussionreplyempty'] = 'Odgovor ne može biti prazan!';

/* Watch */
$LANGS['moreinfo'] = 'više informacija';
$LANGS['lessinfo'] = 'manje informacija';
$LANGS['category'] = 'Kategorija';
$LANGS['recordedon'] = 'Snimljeno na';
$LANGS['location'] = 'Lokacija';
$LANGS['tags'] = 'Oznake';
$LANGS['embed'] = 'Embed';
$LANGS['partnervideo'] = 'Partnerski videozapis';
$LANGS['subscribe'] = 'Pretplatite se';
$LANGS['unsubscribe'] = 'Otkažite pretplatu';
$LANGS['nodesc'] = 'Nema opis...';
$LANGS['logintosub'] = 'Molimo da se prijavite kako biste se pretplatili!';
$LANGS['logintosubbox'] = 'Želite li se pretplatiti?';
$LANGS['subyourself'] = 'Ne možete se sami sebi pretplatiti!'; 
$LANGS['videoowner'] = 'Opcije za vlasnika videozapisa'; 
$LANGS['editvideo'] = 'Uredi videozapis';
$LANGS['insight'] = 'Insight';
$LANGS['morefrom'] = 'Više Od:';
$LANGS['relatedvideos'] = 'Slični Videozapisi';
$LANGS['novideosfound'] = 'Videozapisi nisu pronađeni...';
$LANGS['morevideos'] = 'Pogledajte sve videozapise';
$LANGS['changeplayersize'] = 'Promjenite veličinu player-a'; 
$LANGS['newwindow'] = 'Gledajte ovaj videozapis u novom prozoru'; 
$LANGS['featuredtext'] = 'Ovaj videozapis je istaknut. Želite li vidjeti više preporučenih videozapisa? <a href="/browse?t=2">Pritisnite ovdje</a>.';
$LANGS['ratings'] = 'ocjene';
$LANGS['rating'] = 'ocjena';
$LANGS['favorite'] = 'Omiljeni';
$LANGS['addtofav'] = 'Dodaj u popis omiljenih';
$LANGS['removefav'] = 'Ukloni iz popisa omiljenih';
$LANGS['favadded'] = 'Ovaj videozapis je <strong>dodan</strong> u popisu <a href="/my_favorites">omiljenih</a>.';
$LANGS['favremoved'] = 'Ovaj videozapis je <strong>uklonjen</strong> u popisu <a href="/my_favorites">omiljenih</a>.';
$LANGS['undo'] = 'Poništi';
$LANGS['thanksforrating'] = 'Hvala za ocjenu!';
$LANGS['playlistdesc'] = 'Kako biste dodali videozapis u popis, otiđite u <a href="/my_playlists">"Moje Popise"</a>.';
$LANGS['addtoplaylist'] = 'Dodaj u popis';
$LANGS['addtoplaylistsuccess'] = 'Videozapis je dodan u popis.';
$LANGS['share'] = 'Podijelite';
$LANGS['flag'] = 'Prijavite';
$LANGS['flagthisvid'] = 'Prijavite videozapis';
$LANGS['removeflag'] = 'Ukloni prijavu';
$LANGS['flagnote'] = "Prije nego što prijavite: molimo vas da pogledate dobro ako videozapis krši neka pravila. Nemojte prijaviti samo zato što vam se videozapis ne sviđa, inače biste samo ometali moderatore.";
$LANGS['statadded'] = 'Dodano';
$LANGS['statviews'] = 'pregleda';
$LANGS['statratings'] = 'Ocjene';
$LANGS['statresponses'] = 'Odgovori';
$LANGS['statcomments'] = 'Komentari';
$LANGS['statfavorited'] = 'Stavljeno kod omiljenih';
$LANGS['statsdata'] = 'Statistike i Podatci';
$LANGS['honors'] = 'Pohvale za ovaj videozapis';
$LANGS['mostviewed'] = 'Najpregledaniji';
$LANGS['topfavorited'] = 'Najviše dodan u popis omiljenih';
$LANGS['times'] = 'puta';
$LANGS['mostdiscussed'] = 'Najviše raspravljeni';
$LANGS['toprated'] = 'Najviše ocijenjeni';
$LANGS['videolinks'] = 'Stranice koje vode do ovog videozapisa';
$LANGS['clicksfrom'] = 'klikovi od';
$LANGS['responses'] = 'Video Odgovore';
$LANGS['responsespost'] = 'Pošalji Video Odgovor';
$LANGS['textcomments'] = 'Tekst komentari';
$LANGS['commentpost'] = 'Pošalji tekst komentar';
$LANGS['commentonthisvideo'] = 'Komentiraj na ovaj videozapis';
$LANGS['postcomment'] = 'Pošalji komentar';
$LANGS['remainingcounter'] = 'Preostalo znakova';
$LANGS['nocomments'] = 'Ovaj videozapis <b>nema komentara</b>.';
$LANGS['noresponses'] = 'Ovaj videozapis <b>nema odgovora</b>.';
$LANGS['commviewall'] = 'Pogledaj sve';
$LANGS['delete'] = 'Izbriši';
$LANGS['reply'] = 'Odgovori';
$LANGS['commentlogin'] = 'Želite li komentirati?';
$LANGS['commentlogindesc'] = '<a href="/signup">Pridružite se BitView-u</a> za besplatni račun ili <a href="/login">prijavite se</a> ako ste već član.';
$LANGS['logintoresponse'] = 'Prijavite se kako biste poslali Video Odgovor';
$LANGS['logintocomment'] = 'Prijavite se kako biste komentirali';
$LANGS['logintofav'] = 'Želite li dodati u popis omiljenih? <a href="/login">Prijavite se</a> ili <a href="/signup">Izradite račun</a> sad!'; 
$LANGS['logintopl'] = 'Želite li dodat u popisa? <a href="/login">Prijavite se</a> ili <a href="/signup">Izradite račun</a> sad!'; 
$LANGS['logintoflag'] = 'Želite li prijaviti videozapis? <a href="/login">Prijavite se</a> ili <a href="/signup">Izradite račun</a> sad!'; 
$LANGS['close'] = 'zatvori';
$LANGS['addresponse'] = 'Dodaj Odgovor';
$LANGS['recentlyrated'] = 'Nedavno ocijenjeno';
$LANGS['commentsdisabled'] = 'Dodavanje komentara nije moguć na ovom videozapisu.';
$LANGS['ratingsdisabled'] = 'Ocjene su onemogućene';
$LANGS['rating1'] = 'Slabo';
$LANGS['rating2'] = 'Ništa posebno';
$LANGS['rating3'] = 'Vrijedno gledati';
$LANGS['rating4'] = 'Vrlo dobro';
$LANGS['rating5'] = 'Izvrsno!';
$LANGS['saving'] = 'Spremanje...';
$LANGS['signintorate'] = '<a href="/login">Prijavite se</a> da biste ocijenili videozapis';
$LANGS['addingcomment'] = "Dodavanje komentara...";
$LANGS['commentposted'] = "Komentar objavljen!";
$LANGS['commentspammsg'] = "Ponovno postavljanje istog komentara smatra se spamom. Pokušajte ponovno kasnije.";
$LANGS['commentspammsg2'] = "Objavljivanje više od 5 komentara uzastopno smatra se spamom. Pokušajte ponovno kasnije.";
$LANGS['emptycomment'] = "Vaš komentar ne može biti prazan.";
$LANGS['spambutton'] = "Spam";
$LANGS['notspambutton'] = "Nije spam";
$LANGS['commentsspam'] = "Komentar(i) označeni kao spam";
$LANGS['marked'] = "Označen kao spam";
$LANGS['spamshow'] = "Prikaži";
$LANGS['spamhide'] = "Sakrij";
$LANGS['poorcomment'] = "Slab komentar";
$LANGS['goodcomment'] = "Dobar komentar";
$LANGS['pleasesignin'] = "Molimo prijavite se";
$LANGS['showmorecomments'] = "Prikaži više komentara";
$LANGS['showingamount'] = "<strong>Prikazivanje {number}</strong> od {total} komentara";
$LANGS['customize'] = "Prilagodite";
$LANGS['customizedesc'] = "Nakon odabira kopirajte i zalijepite gornji kod za ugradnju. Šifra se mijenja ovisno o vašem odabiru.";
$LANGS['editvideodetail'] = "Uredi detalje videozapisa";
$LANGS['editannotations'] = "Uredi anotacije";
$LANGS['insightstats'] = "Insight statistike";
$LANGS['allowratingscheck'] = "Dopusti da ljudi <b>ocjenjuju</b> videozapis.";
$LANGS['thisvideoispublic'] = "Ovaj videozapis je javan.";
$LANGS['thisvideoisprivate'] = "Ovaj videozapis je privatan.";
$LANGS['thisvideois'] = "Ovaj videozapis je";
$LANGS['like'] = "Like";
$LANGS['saveto'] = "Spremi na";
$LANGS['uservideoamount'] = "{n} videozapisa";
$LANGS['respondvideo'] = "Odgovori na ovaj videozapis...";
$LANGS['signinnowcomment'] = '<a href="/login">Prijavite se</a> ili <a href="/signup">Izradite račun</a> da biste objavili komentar!';
$LANGS['charactersremaining'] = 'znakova preostalo';
$LANGS['attachavideo'] = 'Priloži videozapis';
$LANGS['commentok'] = 'U redu';
$LANGS['commenterror'] = 'Greška';
$LANGS['highestratedcomments'] = 'Najviše ocjenjeni komentari';
$LANGS['options'] = 'Opcije';
$LANGS['openplaylist'] = 'Otvori popis';
$LANGS['autoplayon'] = 'Autoplay (uključen)';
$LANGS['autoplayoff'] = 'Autoplay (isključen)';
$LANGS['playlistposition'] = '<b>{n1}</b> od {n2}';
$LANGS['nextin'] = 'Slijedeći u {n}';
$LANGS['subscribetooltip'] = "Kliknite za primanje obavijesti o novim videozapisima s ovog kanala";
$LANGS['unsubscribetooltip'] = "Kliknite da biste prestali primati obavijesti o novim videozapisima s ovog kanala";
$LANGS['liketooltip'] = "Sviđa mi se";
$LANGS['disliketooltip'] = "Ne sviđa mi se";
$LANGS['likeratiotooltip'] = "{l} lajkova, {d} dislajkova";
$LANGS['savetotooltip'] = "Dodaj u popis omiljenih ili u popis";
$LANGS['sharetooltip'] = "Podijeli ovaj videozapis";
$LANGS['embedtooltip'] = "Nabavite kod za ugrađivanje videozapisa";
$LANGS['flagtooltip'] = "Prijavi kao neprimjen";
$LANGS['voteuptooltip'] = "Glasaj gore";
$LANGS['votedowntooltip'] = "Glasaj dole";
$LANGS['flagspamtooltip'] = "Prijavi za spam";
$LANGS['removetooltip'] = "Ukloni";
$LANGS['likemessage'] = "Sviđa vam se videozapis. Hvala za povratnu informaciju!<br>Pogledajte više <a href='/my_liked_videos'>videozapisa koje vam se sviđaju</a>.";
$LANGS['dislikemessage'] = "Sviđa vam se videozapis. Hvala za povratnu informaciju!";
$LANGS['ratingsforthisvideo'] = "Ocjene za ovaj videozapis";
$LANGS['liketotal'] = "{l} ukupan";

/* Watch comments */
$LANGS['allcomments'] = 'Svi komentari';

/* Player */
$LANGS['fullscreen'] = "Puni ekran";
$LANGS['expand'] = "Povećaj";
$LANGS['shrink'] = "Smanji";
$LANGS['popout'] = "Pop out";
$LANGS['mute'] = "Mute";
$LANGS['unmute'] = "Unmute";

/* Sign In */
$LANGS['username'] = "Korisničko ime";
$LANGS['password'] = "Lozinka";
$LANGS['logindesc'] = "Prijavite se na BitView sa vašim računom.";
$LANGS['forgot'] = "Ne možete pristupiti računu?";
$LANGS['forgotmsg'] = 'Molimo da nas kontaktirate na Twitter-u (@BitView_) ili da pošaljete poruku moderatorima u Matrix-u. (pozivnica na doljnoj strani stranice)';
$LANGS['noaccount'] = "Nemate račun?"; 
$LANGS['signuptobv'] = "Prijavite se za BitView!";
$LANGS['signintobv'] = "Izradite račun za BitView!";
$LANGS['signindesc1'] = "Pridružite se najvećoj svjetskoj zajednici za dijeljenje videa!";
$LANGS['signindesc2'] = "BitView je način da pokažete vaše videozapise onima koji su vam najvažniji. Sa BitView-om možete:";
$LANGS['signindesc3'] = "Pokazivati vaše omiljene videozapise svijetu";
$LANGS['signindesc4'] = "Blogovati videozapisa koje ste snimili sa vašim digitalnom kamerom ili telefonom.";
$LANGS['signindesc5'] = "Sigurno i privatno pokazivati videozapise vašim prijateljima i obitelji diljem svijeta"; 
$LANGS['notallowed'] = "Već su vam 3 računa zabranjena. Ne smijete više koristiti BitView!"; 
$LANGS['wrongpassword'] = 'Kriva lozinka! Pokušajte ponovno.';
$LANGS['staysigned'] = "Ostanite prijavljeni";

/* Sign Up */
$LANGS['email'] = "Adresa e-pošte";
$LANGS['passwordstrength'] = "Snaga lozinke";
$LANGS['psnone'] = "Nikakva";
$LANGS['psweak'] = "Slaba";
$LANGS['psfair'] = "Dovoljna";
$LANGS['psgood'] = "Dobra";
$LANGS['psstrong'] = "Jaka";
$LANGS['repassword'] = "Ponovno unesite lozinku";
$LANGS['usernamedesc'] = "Vaše korisničko ime može imati samo slova (engleska) A-Z ili brojeve 0-9.";
$LANGS['captcha'] = "Captcha";
$LANGS['acceptterms'] = 'Prihvaćam <a href="/terms">Uvjete Korištenja</a> i <a href="/privacy">Pravila Privatnosti</a>.';
$LANGS['copyrighttext'] = 'Objavljivanje materijala koji nisu u vašem vlasništvu je kršenje autorskih prava i protivzakonito. Ako objavite materijal koji ne posjedujete, vaš će račun biti izbrisan.';
$LANGS['mustaccept'] = 'Morate prihvatiti Uvjeti Korištenja i Pravila Privatnosti da biste izradili račun';
$LANGS['createaccount'] = 'Izradi moj račun';
$LANGS['signuperror'] = 'There was an error while creating your account.';
$LANGS['sameemail'] = 'Ovo korisničko ime ili e-pošta je već u uporabi!';
$LANGS['usernamechar'] = 'Korisničko ime može imati samo brojeve i slova!';
$LANGS['required'] = 'Sva polja su obavezna!';
$LANGS['notmatch'] = "Lozinke se razlikuju!";
$LANGS['signuphead'] = 'Započnite sa vašim računom';

/* Videos Page */
$LANGS['recentvideos'] = 'Recent Videos';
$LANGS['random'] = 'Razno';
$LANGS['dropdownmore'] = 'više';
$LANGS['allcatin'] = 'u';
$LANGS['allcat'] = 'Sve Kategorije';
$LANGS['categories'] = 'Kategorije';
$LANGS['nomorevideos'] = 'Nije pronađeno više videozapisa...';
$LANGS['timetoday'] = 'Danas';
$LANGS['timeweek'] = 'Ovaj tjedan';
$LANGS['timemonth'] = 'Ovaj mjesec';
$LANGS['alltime'] = 'Od svih vremena';
$LANGS['when'] = 'Kada';
$LANGS['videofavorites'] = 'favorite';
$LANGS['videocomments'] = 'komentare';
$LANGS['trendingtopics'] = 'Teme u trendu';

/* Channels Page */
$LANGS['mostsubscribed'] = 'Najviše pretplaćeni'; 
$LANGS['lastlogin'] = 'Zadnji put prijavljeni';
$LANGS['cstatviews'] = 'Pregleda';
$LANGS['cstatvideos'] = 'Videozapisa';
$LANGS['cstatsubs'] = 'Preplatnika';
$LANGS['nochannels'] = 'Više nije pronađen nijedan kanal...';

/* Video Categories */
$LANGS['cat1'] = "Film i Animacija";
$LANGS['cat2'] = "Automobili i Vozila";
$LANGS['cat3'] = "Edukacija i Instrukcija";
$LANGS['cat4'] = "Zabava";
$LANGS['cat5'] = "Događanja i Vjenčanja";
$LANGS['cat6'] = "Obitelj";
$LANGS['cat7'] = "Za Prodaju i Aukcije";
$LANGS['cat8'] = "Hobijevi i Interese";
$LANGS['cat9'] = "Humor";
$LANGS['cat10'] = "Glazba";
$LANGS['cat11'] = "Vijesti i Politika";
$LANGS['cat12'] = "Čudno i Ludo";
$LANGS['cat13'] = "Ljudi i Blogovi";
$LANGS['cat14'] = "Osobno i Veze";
$LANGS['cat15'] = "Kućni Ljubimci I Životinje";
$LANGS['cat16'] = "Znanost i Tehnologija";
$LANGS['cat17'] = "Kratki Filmovi";
$LANGS['cat18'] = "Sport";
$LANGS['cat19'] = "Putovanje i Događanja";
$LANGS['cat20'] = "Igranje Igara";
$LANGS['cat21'] = "Videoblogovanje";

/* Channel Types */
$LANGS['type0'] = "Ništa";
$LANGS['type1'] = "Član";
$LANGS['type1p'] = "Članovi";
$LANGS['type2'] = "Komedičar";
$LANGS['type2p'] = "Komedičari";
$LANGS['type3'] = "Direktor";
$LANGS['type3p'] = "Direktori";
$LANGS['type4'] = "Guru";
$LANGS['type4p'] = "Guru-i";
$LANGS['type5'] = "Glazbenik";
$LANGS['type5p'] = "Glazbenici";
$LANGS['type6'] = "Novinar";
$LANGS['type6p'] = "Novinari";

/* Countries */
$LANGS['cat_AF'] = "Afganistan"; 
$LANGS['cat_AX'] = "Ålandski otoci";
$LANGS['cat_AL'] = "Albanija";
$LANGS['cat_DZ'] = "Alžir";
$LANGS['cat_AS'] = "Američka Samoa";
$LANGS['cat_VI'] = "Američki Djevičanski otoci";
$LANGS['cat_AD'] = "Andora";
$LANGS['cat_AO'] = "Angola";
$LANGS['cat_AI'] = "Angvila";
$LANGS['cat_AQ'] = "Antartika";
$LANGS['cat_AG'] = "Antigva i Barbuda";
$LANGS['cat_AR'] = "Argentina";
$LANGS['cat_AM'] = "Armenija";
$LANGS['cat_AW'] = "Aruba";
$LANGS['cat_AU'] = "Australija";
$LANGS['cat_AT'] = "Austrija";
$LANGS['cat_AZ'] = "Azerbajdžan";
$LANGS['cat_BS'] = "Bahami";
$LANGS['cat_BH'] = "Bahrein";
$LANGS['cat_BD'] = "Bangladeš";
$LANGS['cat_BB'] = "Barbados";
$LANGS['cat_BE'] = "Belgija";
$LANGS['cat_BZ'] = "Belize";
$LANGS['cat_BJ'] = "Benin";
$LANGS['cat_BM'] = "Bermudi";
$LANGS['cat_BY'] = "Bjelarus";
$LANGS['cat_BW'] = "Bocvana";
$LANGS['cat_BO'] = "Bolivija";
$LANGS['cat_BA'] = "Bosna i Hercegovina";
$LANGS['cat_CX'] = "Božićni Otok";
$LANGS['cat_BR'] = "Brazil";
$LANGS['cat_VG'] = "Britanski Djevičanski otoci";
$LANGS['cat_IO'] = "Britanski Indijskooceanski teritorij"; 
$LANGS['cat_BN'] = "Brunej Darussalam";
$LANGS['cat_BG'] = "Bugarska";
$LANGS['cat_BF'] = "Burkina Faso";
$LANGS['cat_BI'] = "Burundi";
$LANGS['cat_BT'] = "Butan";
$LANGS['cat_CY'] = "Cipar";
$LANGS['cat_CK'] = "Cookovo Otočje";
$LANGS['cat_ME'] = "Crna Gora";
$LANGS['cat_CW'] = "Curaçao";
$LANGS['cat_TD'] = "Čad";
$LANGS['cat_CZ'] = "Česka";
$LANGS['cat_CL'] = "Čile";
$LANGS['cat_DK'] = "Danska";
$LANGS['cat_CD'] = "Demokratska Republika Kongo";
$LANGS['cat_DM'] = "Dominika";
$LANGS['cat_DO'] = "Dominikanska Republika";
$LANGS['cat_DJ'] = "Džibuti";
$LANGS['cat_EG'] = "Egipat";
$LANGS['cat_EC'] = "Ekvador";
$LANGS['cat_GQ'] = "Ekvatorska Gvineja";
$LANGS['cat_SV'] = "El Salvador";
$LANGS['cat_ER'] = "Eritreja";
$LANGS['cat_EE'] = "Estonija";
$LANGS['cat_SZ'] = "Esvatini";
$LANGS['cat_ET'] = "Etiopija";
$LANGS['cat_FK'] = "Falklandski Otoci"; 
$LANGS['cat_FO'] = "Farski Otoci";
$LANGS['cat_FJ'] = "Fidži";
$LANGS['cat_PH'] = "Filipini";
$LANGS['cat_FI'] = "Finska";
$LANGS['cat_FR'] = "Francuska";
$LANGS['cat_GF'] = "Francuska Gijana";
$LANGS['cat_FG'] = "Francuska Gijana";
$LANGS['cat_PF'] = "Francuska Polinezija";
$LANGS['cat_TF'] = "Francuski Južni Teritoriji"; 
$LANGS['cat_GA'] = "Gabon";
$LANGS['cat_GM'] = "Gambija";
$LANGS['cat_GH'] = "Gana";
$LANGS['cat_GI'] = "Gibraltar";
$LANGS['cat_GR'] = "Grčka";
$LANGS['cat_GD'] = "Grenada";
$LANGS['cat_GL'] = "Grenland";
$LANGS['cat_GE'] = "Gruzija";
$LANGS['cat_GU'] = "Guam";
$LANGS['cat_GG'] = "Guernsey";
$LANGS['cat_GT'] = "Gvatemala";
$LANGS['cat_GG'] = "Guernsey";
$LANGS['cat_GY'] = "Gvajana";
$LANGS['cat_GN'] = "Gvineja";
$LANGS['cat_GW'] = "Gvineja Bisau";
$LANGS['cat_HT'] = "Haiti";
$LANGS['cat_HN'] = "Honduras";
$LANGS['cat_HK'] = "Hong Kong";
$LANGS['cat_HR'] = "Hrvatska";
$LANGS['cat_IN'] = "Indija";
$LANGS['cat_ID'] = "Indonezija";
$LANGS['cat_IQ'] = "Irak";
$LANGS['cat_IR'] = "Iran";
$LANGS['cat_IE'] = "Irska";
$LANGS['cat_IS'] = "Island";
$LANGS['cat_TL'] = "Istočni Timor";
$LANGS['cat_IT'] = "Italija";
$LANGS['cat_IL'] = "Izrael";
$LANGS['cat_JM'] = "Jamajka";
$LANGS['cat_JP'] = "Japan";
$LANGS['cat_YE'] = "Jemen";
$LANGS['cat_JO'] = "Jordan";
$LANGS['cat_ZA'] = "Južna Afrika";
$LANGS['cat_GS'] = "Južna Georgija i otočje Južni Sandwich";
$LANGS['cat_KR'] = "Južna Koreja";
$LANGS['cat_SS'] = "Južni Sudan";
$LANGS['cat_KY'] = "Kajmanski Otoci";
$LANGS['cat_KH'] = "Kambodža";
$LANGS['cat_CM'] = "Kamerun";
$LANGS['cat_CA'] = "Kanada";
$LANGS['cat_QA'] = "Katar";
$LANGS['cat_KZ'] = "Kazahstan";
$LANGS['cat_KE'] = "Kenija";
$LANGS['cat_CN'] = "Kina";
$LANGS['cat_KG'] = "Kirgistan";
$LANGS['cat_KI'] = "Kiribati";
$LANGS['cat_CC'] = "Kokosovi Otoci"; 
$LANGS['cat_CO'] = "Kolumbija";
$LANGS['cat_KM'] = "Komori";
$LANGS['cat_XK'] = "Kosovo";
$LANGS['cat_CR'] = "Kostarika";
$LANGS['cat_CU'] = "Kuba";
$LANGS['cat_KW'] = "Kuvajt";
$LANGS['cat_LA'] = "Laos";
$LANGS['cat_LV'] = "Latvija";
$LANGS['cat_LS'] = "Lesoto";
$LANGS['cat_LB'] = "Libanon";
$LANGS['cat_LR'] = "Liberija";
$LANGS['cat_LY'] = "Libija";
$LANGS['cat_LI'] = "Lihtenštajn";
$LANGS['cat_LU'] = "Luksemburg";
$LANGS['cat_LT'] = "Litva";
$LANGS['cat_MG'] = "Madagaskar";
$LANGS['cat_HU'] = "Mađarska";
$LANGS['cat_MO'] = "Makao";
$LANGS['cat_MW'] = "Malavi";
$LANGS['cat_MV'] = "Maldivi";
$LANGS['cat_MY'] = "Malezija";
$LANGS['cat_ML'] = "Mali";
$LANGS['cat_UM'] = "Mali udaljeni otoci SAD-a"; 
$LANGS['cat_MT'] = "Malta";
$LANGS['cat_MA'] = "Maroko";
$LANGS['cat_MH'] = "Maršalovi Otoci";
$LANGS['cat_MQ'] = "Martinik";
$LANGS['cat_MU'] = "Mauricijus";
$LANGS['cat_MR'] = "Mauritanija";
$LANGS['cat_YT'] = "Mayotte";
$LANGS['cat_MX'] = "Meksiko";
$LANGS['cat_FM'] = "Mikronezija";
$LANGS['cat_MM'] = "Mjanmar";
$LANGS['cat_MD'] = "Moldavija";
$LANGS['cat_MC'] = "Monako";
$LANGS['cat_MN'] = "Mongolija";
$LANGS['cat_MS'] = "Montserrat";
$LANGS['cat_MZ'] = "Mozambik";
$LANGS['cat_NA'] = "Namibija";
$LANGS['cat_NR'] = "Nauru";
$LANGS['cat_NP'] = "Nepal";
$LANGS['cat_NE'] = "Niger";
$LANGS['cat_NG'] = "Nigerija";
$LANGS['cat_NI'] = "Nikaragva";
$LANGS['cat_NU'] = "Niue";
$LANGS['cat_NL'] = "Nizozemska";
$LANGS['cat_AN'] = "Nizozemski Antili";
$LANGS['cat_BQ'] = "Nizozemski Karibi";
$LANGS['cat_NO'] = "Norveška";
$LANGS['cat_NC'] = "Nova Kaledonija";
$LANGS['cat_NZ'] = "Novi Zeland";
$LANGS['cat_DE'] = "Njemačka";
$LANGS['cat_CI'] = "Obala Bijelokosti";
$LANGS['cat_JE'] = "Oblast Jersey";
$LANGS['cat_OM'] = "Oman";
$LANGS['cat_TC'] = "Otoci Turks i Caicos"; 
$LANGS['cat_BV'] = "Otok Bouvet";
$LANGS['cat_GP'] = "Otok Guadalupe";
$LANGS['cat_HM'] = "Otok Heard i otočje McDonald"; 
$LANGS['cat_IM'] = "Otok Man";
$LANGS['cat_NF'] = "Otok Norfolk";
$LANGS['cat_PK'] = "Pakistan";
$LANGS['cat_PW'] = "Palau";
$LANGS['cat_PS'] = "Palestina";
$LANGS['cat_PA'] = "Panama";
$LANGS['cat_PY'] = "Paragvaj";
$LANGS['cat_PG'] = "Papua Nova Gvineja";
$LANGS['cat_PE'] = "Peru";
$LANGS['cat_PN'] = "Pitcairnovo Otočje";
$LANGS['cat_PL'] = "Poljska";
$LANGS['cat_PR'] = "Portoriko";
$LANGS['cat_PT'] = "Portugal";
$LANGS['cat_CG'] = "Republika Kongo"; 
$LANGS['cat_RE'] = "Réunion";
$LANGS['cat_RW'] = "Ruanda";
$LANGS['cat_RO'] = "Rumunjska";
$LANGS['cat_RU'] = "Rusija";
$LANGS['cat_SB'] = "Salomonovi Otoci";
$LANGS['cat_WS'] = "Samoa";
$LANGS['cat_SM'] = "San Marino";
$LANGS['cat_SA'] = "Saudijska Arabija";
$LANGS['cat_SC'] = "Sejšeli";
$LANGS['cat_SN'] = "Senegal";
$LANGS['cat_SL'] = "Sijera Leone";
$LANGS['cat_SG'] = "Singapur";
$LANGS['cat_SY'] = "Sirija";
$LANGS['cat_US'] = "Sjedinjene Američke Države";
$LANGS['cat_KP'] = "Sjeverna Koreja";
$LANGS['cat_MK'] = "Sjeverna Makedonija";
$LANGS['cat_MP'] = "Sjevernomarijanski otoci"; 
$LANGS['cat_SK'] = "Slovačka";
$LANGS['cat_SI'] = "Slovenija";
$LANGS['cat_SO'] = "Somalija";
$LANGS['cat_RS'] = "Srbija";
$LANGS['cat_CF'] = "Srednjoafrička Republika";
$LANGS['cat_SD'] = "Sudan";
$LANGS['cat_SR'] = "Surinam";
$LANGS['cat_SJ'] = "Svalbard i Jan Mayen"; 
$LANGS['cat_SH'] = "Sveta Helena";
$LANGS['cat_LC'] = "Sveta Lucija";
$LANGS['cat_BL'] = "Sveti Bartolomej";
$LANGS['cat_KN'] = "Sveti Kristofor i Nevis";
$LANGS['cat_MF'] = "Sveti Martin (Frenzuski dio)"; 
$LANGS['cat_PM'] = "Sveti Petar i Mikelon"; 
$LANGS['cat_ST'] = "Sveti Toma i Prinsipe"; 
$LANGS['cat_VC'] = "Sveti Vincent i Grenadini";
$LANGS['cat_ES'] = "Španjolska";
$LANGS['cat_LK'] = "Šri Lanka";
$LANGS['cat_SE'] = "Švedska";
$LANGS['cat_CH'] = "Švicarska";
$LANGS['cat_TJ'] = "Tadžikistan";
$LANGS['cat_TH'] = "Tajland";
$LANGS['cat_TW'] = "Tajvan";
$LANGS['cat_TZ'] = "Tanzanija";
$LANGS['cat_TG'] = "Togo";
$LANGS['cat_TK'] = "Tokelau";
$LANGS['cat_TO'] = "Tonga";
$LANGS['cat_TT'] = "Trinidad i Tobago";
$LANGS['cat_TN'] = "Tunis";
$LANGS['cat_TM'] = "Turkmenistan";
$LANGS['cat_TR'] = "Turska";
$LANGS['cat_TV'] = "Tuvalu";
$LANGS['cat_UG'] = "Uganda";
$LANGS['cat_GB'] = "Ujedinjena Kraljevina";
$LANGS['cat_AE'] = "Ujedinjeni Arapski Emirati";
$LANGS['cat_UA'] = "Ukrajina";
$LANGS['cat_UY'] = "Urugvaj";
$LANGS['cat_UZ'] = "Uzbekistan";
$LANGS['cat_VU'] = "Vanuatu";
$LANGS['cat_VA'] = "Vatikan"; 
$LANGS['cat_VE'] = "Venezuela";
$LANGS['cat_VN'] = "Vijetnam";
$LANGS['cat_ZM'] = "Zambija";
$LANGS['cat_EH'] = "Zapadna Sahara";
$LANGS['cat_CV'] = "Zelenortski Otoci";
$LANGS['cat_SX'] = "Zemlja Sveti Martin";
$LANGS['cat_ZW'] = "Zimbabve"; 
$LANGS['cat_WF'] = "Wallis i Futuna";

/* My Subscriptions */
$LANGS['newvideos'] = "Novi Videozapisi";
$LANGS['addselectedto'] = "Add the selected videos to:";
$LANGS['addtoplaylists'] = "Dodaj u popis";

/* Account */
$LANGS['myaccount'] = "Moj račun";
$LANGS['vidsfavs'] = "Videozapisi, omiljeni videozapisi i popisi";
$LANGS['accountsettings'] = "Postavke računa";
$LANGS['viewinghistory'] = "Povijest";
$LANGS['mychannel'] = "Moj kanal";
$LANGS['uploadedvideos'] = "Objavljeni videozapisi";
$LANGS['new'] = "Nov";
$LANGS['playlist'] = "Popis";
$LANGS['videoupload'] = "Prijenos videozapisa";
$LANGS['nosubvideos'] = "You have no subscriptions...";
$LANGS['nofavvideos'] = "You haven't favorited any video...";

/* My Videos */
$LANGS['sortby'] = "Poredaj na temelju";
$LANGS['sorttitle'] = "Naslova";
$LANGS['sorttime'] = "Vrijemena";
$LANGS['sortdateadded'] = "Datuma";
$LANGS['sortviews'] = "Pregleda";
$LANGS['sortrating'] = "Ocjena";
$LANGS['stattime'] = "Vrijeme";
$LANGS['statrating'] = "Ocjene";
$LANGS['statbroadcast'] = "Emitiranje";
$LANGS['statrawfile'] = "Čista datoteka";
$LANGS['public'] = "Javno";
$LANGS['private'] = "Privatno";
$LANGS['live'] = "Uživo!";
$LANGS['converting'] = "Postavljanje...";
$LANGS['uploading'] = "Pretvaranje...";
$LANGS['addvidsto'] = "Dodaj videozapis u";
$LANGS['play'] = "Pustite Videozapis";
$LANGS['edit'] = "Uredi";
$LANGS['setasavatar'] = "Postavi sličicu kao profilnu sliku";
$LANGS['downloadmp4'] = "Preuzmi MP4";
$LANGS['deleteconfirmation'] = "Da li ste sigurni da želite ovaj videozapis ukloniti?";
$LANGS['novideos'] = 'Nemate još prenesenih videozapisa. <a href="/my_videos_upload">Počnite objavljivati sada</a>!';
$LANGS['nomyvideosresults'] = "Nema rezultata. Pogledajte ako ste napisali točno.";

/* Edit Video */
$LANGS['infoandsettings'] = "Informacije i Postavke";
$LANGS['annotations'] = "Anotacije";
$LANGS['captionsandsubtitles'] = "Opisi i titlovi";
$LANGS['viewonvideopage'] = "Pogledajte na video stranici »";
$LANGS['title'] = "Naslov";
$LANGS['desc'] = "Opis";
$LANGS['privacy'] = "Privatnost";
$LANGS['saveinfo'] = "Spremi informacije";
$LANGS['saveinfoconfirm'] = "Jeste li sigurni da želite promijeniti informacije o videozapisu?";
$LANGS['viewchart'] = "Pogledaj Grafikon";
$LANGS['videodetails'] = "Detalji videozapisa";
$LANGS['backtopreviouspage'] = "Natrag u prethodnu stranici";
$LANGS['editsavechanges'] = "Spremi promjene";
$LANGS['editcancel'] = "odustani";
$LANGS['videoinfo'] = "Informacija o videozapisu";
$LANGS['videothumbnail'] = "Sličica Videozapisa";
$LANGS['uploadthumbnail'] = "Objavi Sličicu";
$LANGS['customthumbdesc'] = 'Kako biste postavili prilagođenu sličicu, kliknite sličicu na lijevoj strani i odaberite željenu slikovnu datoteku. Onda pritisnite "Objavi Sličicu".';
$LANGS['customthumbtitle'] = 'Želite li promjeniti ovu sličicu?';
$LANGS['customthumbinfo'] = 'Prilagođene sličice ekskluzivne su za partnere. Kako biste pročitali više o prednostima pridruživanja partnerskom programu i njegovim zahtjevima, kliknite na gumb ispod.';
$LANGS['partnerreadmore'] = 'Pročitaj više';
$LANGS['broadcastingoptions'] = 'Postavke za Emitiranje i Dijeljenje';
$LANGS['publicdesc'] = "svi mogu pretraživati i pregledavati - preporučeno";
$LANGS['privatedesc'] = "mogu pregledavati samo određeni BitView korisnici";
$LANGS['allowcomments'] = "Automatski dopusti komentare";
$LANGS['allowfriendcomments'] = "Samo prijatelji mogu komentirat";
$LANGS['disablecomments'] = "Nemoj dopustit komentare";
$LANGS['dateandmap'] = "Datum i karta";
$LANGS['clear'] = "Očisti";
$LANGS['allowratings'] = "Da, dopusti da drugi ocjenjuju ovaj videozapis.";
$LANGS['dontallowratings'] = "Ne, nemoj dopustiti da drugi ocjenjuju ovaj videozapis.";
$LANGS['updatevideo'] = "Ažuriraj videozapis";
$LANGS['updatevideofilesize'] = "(najveća veličina datoteka: 100MB)";

/* Edit Video Annotations */
$LANGS['publish'] = "Objavi";
$LANGS['published'] = "Objavljeno";
$LANGS['saved'] = "Spremljeno";
$LANGS['notvaliddate'] = "Unijeli ste nevažeću vremensku oznaku!";
$LANGS['outsiderange'] = "Unijeli ste vremensku oznaku izvan raspona trajanja videa!";
$LANGS['video_pl'] = "Zaljepi poveznicu za videozapis";
$LANGS['playlist_pl'] = "Zaljepi poveznicu za popis";
$LANGS['channel_pl'] = "Unesi korisničko ime";
$LANGS['group_pl'] = "Zaljepi poveznicu za grupu";
$LANGS['search_pl'] = "Unesite vaš upit za pretraživanje ovdje";
$LANGS['entertext'] = "Unesite vaš tekst ovdje";
$LANGS['loading'] = "Učitavanje...";
$LANGS['addlink'] = "Dodaj poveznicu";
$LANGS['linktype'] = "Vrsta poveznice";
$LANGS['group'] = "Grupa";
$LANGS['composemessage'] = "Sastavi poruku";
$LANGS['videoresponseupload'] = "Prijenos video odgovora";
$LANGS['searchquery'] = "BitView-ov upit za pretraživanje";
$LANGS['entervalidurl'] = "Molimo unesite valjani URL";

/* My Playlists */
$LANGS['addedpl'] = "Dodano";
$LANGS['frompl'] = "Od";
$LANGS['nopl'] = "Nijedan popis nije pronađen....";

/* My Playlist */
$LANGS['playlistedit'] = "Uredi popis";
$LANGS['videourl'] = "Video URL";
$LANGS['add'] = "Dodaj";
$LANGS['editinfo'] = "Uredi informacije";
$LANGS['editdetails'] = "Uredi detalje";
$LANGS['deleteplaylist'] = "Izbriši popis";
$LANGS['addvideostoplaylist'] = "Dodaj videozapis u popis";
$LANGS['novideoswerefound'] = "Nije pronađen niti jedan videozapis.";
$LANGS['position'] = "Pozicija";
$LANGS['move'] = "Makni";
$LANGS['deleteplaylistconfirmdesc'] = "Jeste li sigurni da želite izbrisati <strong>{p}</strong>?<br><br>Napomena: Brisanje popisa za reprodukciju trajna je radnja i ne može se poništiti.";
$LANGS['deleteplaylistconfirm'] = "Da, izbriši";
$LANGS['titledesctags'] = "Naslov, opis, oznake";
$LANGS['savechangespl'] = "Spremi promjene";

/* Edit Playlist */
$LANGS['pledittitle'] = "Uredi Popis";
$LANGS['pleditdesc'] = "Popisi za reprodukciju su zbirke videozapisa koje možete postaviti kako želite.";
$LANGS['cancel'] = "Odustani";

/* Create Playlist */
$LANGS['createplaylisttitle'] = "Izradi Popis Videozapisa";
$LANGS['createplaylist'] = "Stvori Popis";

/* View Playlist */
$LANGS['plpermalink'] = "Popis/URL (Stalna poveznica):";
$LANGS['sortcomments'] = "Komentari";
$LANGS['unsorted'] = "Nerazvrstano";
$LANGS['playallvideos'] = "Reproduciraj sve videozapise";

/* Inbox */
$LANGS['compose'] = "Sastavi";
$LANGS['from'] = "Od";
$LANGS['subject'] = "Predmet";
$LANGS['date'] = "Datum";
$LANGS['allmsg'] = "Sve Poruke";
$LANGS['msgcom'] = "Komentare";
$LANGS['sentmsg'] = "Poslane Poruke";
$LANGS['nomsg'] = "Nemate Poruke...";
$LANGS['personalmessages'] = "Osobne Poruke";
$LANGS['sharedwithyouinbox'] = "Podijeljeno s vama";
$LANGS['friendinvitesinbox'] = "Poziv za prijatelje";
$LANGS['videoresponsesinbox'] = "Video Odgovore";
$LANGS['sent'] = "Poslano";
$LANGS['attachvideo'] = "Priloži Videozapis";
$LANGS['msgchannelcomment'] = "Komentirajte na vašem kanalu";
$LANGS['msgcomment'] = "Komentirajte na vašem videozapisu";
$LANGS['msgvideoresponse'] = "Video Odgovor na vašem videozapisu";
$LANGS['msgmention'] = "Spomeni na videozapisu";
$LANGS['msgmentionchannel'] = "Spomeni na {channel}ovom kanalu";

/* Address Book */
$LANGS['addressbook'] = "Adresna Knjiga";
$LANGS['allcontacts'] = "Svi Kontakti";
$LANGS['selectedcontacts'] = "Odabrani Kontakti";
$LANGS['choosecontacts'] = "Odaberite s popisa kontakata";
$LANGS['friendssince'] = "Prijatelji od";
$LANGS['friendsinvitenot'] = "Poziv za prijateljstvo još nije prihvaćen";
$LANGS['friendstatus'] = "Status prijatelja";
$LANGS['unselect'] = "Poništi odabir";
$LANGS['unselectall'] = "Poništi sve";
$LANGS['nocontacts'] = "Nema kontakta...";
$LANGS['selectacontact'] = "Molimo da odaberete barem jedan kontakt za brisanje!";
$LANGS['selectacontactmsg'] = "Molimo da odaberete barem jedan kontakt da im pošaljete poruku!";
$LANGS['selectonecompose'] = "Ne možete sastavljati više kontakata odjednom!<br>Molimo odaberite kontakt kojem želite poslati poruku.";

/* Insight */
$LANGS['insighttitle'] = "Insight: Statistika i Podatci";
$LANGS['allvideos'] = "Svi Videozapisi";
$LANGS['summary'] = "Sažetak";
$LANGS['demographics'] = "Demografija";
$LANGS['viewsdesc'] = "Koliko pregleda mi videozapisi dobivaju?";
$LANGS['demodesc'] = "Tko je pretplaćen na moj kanal?";
$LANGS['commdesc'] = "Gdje se moji pretplatnici nalazu?";
$LANGS['video'] = "Videozapis";
$LANGS['topvideos'] = "Top videozapisi";
$LANGS['viewspercentage'] = "Pregleda (&percnt; od ukupnog)";
$LANGS['percentoftotalviews'] = "&percnt; od ukupnih pregleda";
$LANGS['searchmyvideos'] = "Pretraži moje videozapise";
$LANGS['insufdemo'] = "Nema dovoljno podataka za prikaz demografskih podataka. Pokušajte odabrati drugi vremenski raspon.";
$LANGS['ageranges'] = "Dobni raspon za oba spola";
$LANGS['genderranges'] = "Spolovi za sve dobne skupine";
$LANGS['engdesc'] = "Broj korisnika koji su komentirali, označili kao favorite ili ocijenili vaše videozapise";
$LANGS['engagements'] = "angažmani u zajednici";
$LANGS['dailysubs'] = "Dnevne pretplatnike";
$LANGS['daily'] = "Dnevno";
$LANGS['total'] = "Ukupno";
$LANGS['insightvideodesc'] = "Koliko puta je ovaj videozapis pogledan?";
$LANGS['videototalviews'] = "Ukupno pogleda";
$LANGS['dailyviews'] = "Dnevna pogleda";

/* Send Message */
$LANGS['messagecont'] = "Poruka";
$LANGS['to'] = "do";
$LANGS['sendmessagebutton'] = "Pošalji Poruku";

/* Groups */
$LANGS['groups'] = "Grupe";
$LANGS['joinedgroups'] = "Pridružene Grupe";
$LANGS['recentgroups'] = "Nedavne Grupe";
$LANGS['mostmembers'] = "Najviše Članova";
$LANGS['mostvideos'] = "Najviše Videozapisa";
$LANGS['groupmostdiscussed'] = "Najviše Raspravljene";
$LANGS['createagroup'] = "Izradi Grupu";
$LANGS['groupvideos'] = "Videozapisi";
$LANGS['groupmembers'] = "Članovi";
$LANGS['discussions'] = "Rasprave";
$LANGS['groupcreated'] = "Izrađen";
$LANGS['nogroups'] = "Nisu pronađene grupe...";

/* Group */
$LANGS['jointhisgroup'] = "Pridruži se Grupi";
$LANGS['removerequest'] = "Ukloni Zahtjev";
$LANGS['leavegroup'] = "Izađi iz Grupe";
$LANGS['moderation'] = "Moderacija";
$LANGS['viewallvideos'] = "View All Videos";
$LANGS['addvideo'] = "Dodaj Videozapis";
$LANGS['novideos'] = "Nema Videozapisa...";
$LANGS['nodiscussions'] = "Nema Rasprava...";
$LANGS['creatediscussion'] = "Izradi Raspravu";
$LANGS['topostatopic'] = "da biste objavili temu za raspravu.";
$LANGS['topic'] = "Tema";
$LANGS['author'] = "Autor";
$LANGS['replies'] = "Odgovore";
$LANGS['lastpost'] = "Zadnja Objava";
$LANGS['viewallmembers'] = "Pokaži sve članove";
$LANGS['owner'] = "Vlasnik";
$LANGS['grouptype'] = "Vrsta";
$LANGS['instantjoin'] = "Instant Pridruživanje";
$LANGS['approvalrequired'] = "Potrebno odobrenje";
$LANGS['groupurl'] = "URL";
$LANGS['deletediscussion'] = "Izbriši Raspravu";
$LANGS['postreply'] = "Objavi Odgovor";
$LANGS['post'] = "Objavi";
$LANGS['accept'] = "Prihvati";
$LANGS['decline'] = "Odbij";

/* Group Moderation */
$LANGS['groupmoderation'] = "Grupna Moderacija";
$LANGS['approvemembers'] = "Odobri Članove";
$LANGS['approvevideos'] = "Odobri Videozapise";
$LANGS['yes'] = "Da";
$LANGS['no'] = "Ne";
$LANGS['changeinfo'] = "Promjeni Informaciju";
$LANGS['changeimage'] = "Promjeni Sliku";
$LANGS['image'] = "Slika";
$LANGS['styling'] = "Stil";
$LANGS['cssdesc'] = "Having backgrounds or graphics that do or show illegal things will result in your termination.";
$LANGS['updatecss'] = "Ažuriraj CSS";
$LANGS['groupmessage'] = "Poruka";
$LANGS['sendmessagetomembers'] = "Pošalji Poruku Članovima";
$LANGS['delgroup'] = "Izbriši Grupu";

/* Submit Group Video */
$LANGS['submitvideotitle'] = "Pošalji Videozapis Grupi";
$LANGS['submitvideo'] = "Pošalji Videozapis";

/* Create Group */
$LANGS['groupname'] = "Naziv Grupe";
$LANGS['groupimage'] = "Grupna Slika";
$LANGS['creategroup'] = "Izradi Grupu";
$LANGS['creategroupdesc'] = "Grupe vam omogućuju stvaranje rasprava s drugim članovima i jednostavno dijeljenje vaših videozapisa s drugima.";

/* Create Group Discussion */
$LANGS['discussiontitle'] = "Naslov Rasprave";
$LANGS['creatediscussiondesc'] = "Rasprave su dijelovi grupa u kojima se raspravlja o zadanoj temi.";

/* Search Results */
$LANGS['results'] = "{s} rezultata";
$LANGS['relevance'] = 'Relevantnost';
$LANGS['viewcount'] = 'Broj pregleda';
$LANGS['searchrating'] = 'Ocjena';
$LANGS['newest'] = 'Datum prijenosa';
$LANGS['nochannelsfound'] = 'Nema pronađenih kanala...';
$LANGS['noplfound'] = 'Nema pronađenih popisa...';
$LANGS['nogroupsfound'] = 'Nema pronađenih grupa...';
$LANGS['uploaded'] = 'Prenesen';
$LANGS['anytime'] = 'Bilokad';
$LANGS['partnervideos'] = 'Partnerske Videozapise';
$LANGS['resultcount'] = 'rezultata {r} od otprilike {t}';
$LANGS['searchoptions'] = 'Opcije pretraživanja';
$LANGS['resulttype'] = 'Vrsta rezultata';
$LANGS['duration'] = 'Trajanje';
$LANGS['durshort'] = 'Kratko (~4 minute)';
$LANGS['durlong'] = 'Dugo (15~ minute)';
$LANGS['features'] = 'Značajke';
$LANGS['novideosfoundfor'] = 'Nisu pronađene videozapise za';
$LANGS['noresultsfoundfor'] = 'Nisu pronađene rezultate za';

/* Profile */
$LANGS['channelsuspended'] = 'Ovaj račun je obustavljen.';
$LANGS['accountnotfound'] = 'Ovaj račun nije moguće pronaći.';
$LANGS['channel'] = 'Kanal';
$LANGS['friends'] = 'Prijatelji';
$LANGS['channelsubscribers'] = 'Pretplatnike';
$LANGS['linkcomments'] = 'Komentare';
$LANGS['bulletins'] = 'Bulletin-ove';
$LANGS['editchannel'] = 'Uredi Kanal';
$LANGS['type'] = 'Vrsta';
$LANGS['joined'] = 'Pridružio se';
$LANGS['videoswatched'] = 'Videozapisa pogledao';
$LANGS['channelviews'] = 'Pregleda u kanalu';
$LANGS['age'] = 'Dob';
$LANGS['gender'] = 'Rod';
$LANGS['male'] = 'Muški';
$LANGS['female'] = 'Ženski';
$LANGS['nonbinary'] = 'Non-Binary';
$LANGS['status'] = 'Stanje';
$LANGS['single_m'] = 'Samac';
$LANGS['single_f'] = 'Samac';
$LANGS['taken_m'] = 'Zauzet';
$LANGS['taken_f'] = 'Zauzet';
$LANGS['married_m'] = 'Oženjen';
$LANGS['married_f'] = 'Udana';
$LANGS['country'] = 'Država';
$LANGS['website'] = 'Web-stranica';
$LANGS['hobbies'] = 'Interesi i Hobijevi';
$LANGS['music'] = 'Glazba';
$LANGS['movies'] = 'Filmovi i Serije';
$LANGS['books'] = 'Knjige';
$LANGS['mostsub'] = 'Najviše pretplaćeni';
$LANGS['report'] = 'Prijavi';
$LANGS['pfpviolation'] = 'povreda profilna slika';
$LANGS['connectwith'] = 'Spoji se s';
$LANGS['profilesendmessage'] = 'Pošalji Poruku';
$LANGS['messagetoyourself'] = 'Ne možete slati poruke samome sebi!';
$LANGS['logintomessage'] = 'Molimo prijavite se kako biste slali poruke!';
$LANGS['addcomment'] = 'Dodaj Komentar';
$LANGS['logintocommentchannel'] = 'Molimo prijavite se kako biste komentirali';
$LANGS['sharechannel'] = 'Podijeli Kanal';
$LANGS['addfriend'] = 'Dodaj kao Prijatelja';
$LANGS['retractinvite'] = 'Povuci poziv';
$LANGS['removefriend'] = 'Ukloni Prijatelja';
$LANGS['notfriendyourself'] = 'Ne možete samog sebe dodati prijateljima!';
$LANGS['logintofriend'] = 'Molimo prijavite se za dodavanje prijatelja!';
$LANGS['blockuser'] = 'Blokiraj korisnika';
$LANGS['channelembed'] = 'Ugradi ovaj kanal';
$LANGS['recentratings'] = 'Nedavna Aktivnost';
$LANGS['seeall'] = 'pogledaj sve';
$LANGS['writebulletin'] = 'Napiši Bulletin';
$LANGS['bulletin'] = 'Bulletin';
$LANGS['subvideos1'] = 'Pretplati se ';
$LANGS['subvideos2'] = "'-ove videozapise";
$LANGS['plvideos'] = 'Videozapisi';
$LANGS['playall'] = 'Reproduciraj sve';
$LANGS['featuredchannels'] = 'Istaknuti kanali';
$LANGS['channelcomments'] = 'Komentare u kanalu';
$LANGS['bggraphic'] = 'grafika pozadine';
$LANGS['reportthisuser'] = 'ovaj korisnik.';
$LANGS['norecentratings'] = 'Nema nedavne aktivnosti...';
$LANGS['nosubscribers'] = 'Nema pretplatnika...';
$LANGS['nosubscriptions'] = 'Nema pretplate...';
$LANGS['nofriends'] = 'Nema prijatelja...';
$LANGS['nobulletins'] = 'Nema bulletin-ove...';
$LANGS['novideoschannel'] = 'Nema videozapisa...';
$LANGS['nofavs'] = 'Nema omiljenih videozapisa...';
$LANGS['noplchannel'] = 'Nema popisa...';
$LANGS['pvideos'] = 'Privatni Videozapisi';
$LANGS['pvideosallow'] = 'Nije vam dopušteno vidjeti ove videozapise...';
$LANGS['plvideoamount'] = 'videozapisa';
$LANGS['bulletinpost'] = 'Bulletin Objava';
$LANGS['deletebulletin'] = 'Izbriši Bulletin';
$LANGS['body'] = 'Tijelo';
$LANGS['bulletincomments'] = 'Bulletin Komentare';
$LANGS['tocommentbulletin'] = 'za slanje odgovora na ovaj Bulletin!';
$LANGS['addacomment'] = 'Dodaj Komentar:';
$LANGS['postreplychannel'] = 'Pošalji Odgovor';
$LANGS['writecomment'] = 'Napiši Komentar';
$LANGS['for'] = 'za';
$LANGS['commentdesc'] = 'Komentari kanala pojavljuju se na kanalu korisnika.';
$LANGS['postbulletin'] = 'Objavi Bulletin';
$LANGS['writeabulletin'] = 'Napiši bulletin';
$LANGS['bulletindesc'] = 'Bulletin se pojavljuje na vašem kanalu i kanalu vaših prijatelja.';
$LANGS['sharingoptions'] = 'Opcije dijeljenja';
$LANGS['sharingoptionsdesc'] = 'Postoje 2 načina za dijeljenje ovog kanala.';
$LANGS['sharingoptions1'] = '1. Kopirajte i zalijepite ovu vezu u e-poštu ili izravnu poruku.';
$LANGS['sharingoptions2'] = "2. Pošaljite ovaj kanal pomoću programa za e-poštu vašeg računala.";
$LANGS['clicktosend'] = 'Kliknite da pošaljete!';
$LANGS['honorless'] = 'manje';
$LANGS['activitycomment'] = 'je komentirao na';
$LANGS['activityfavorite'] = 'je označio video kao omiljen';
$LANGS['activitylike'] = 'je lajkao video';
$LANGS['activityrating'] = 'je ocjenio video:';
$LANGS['activityupload'] = 'je objavio novi videozapis';
$LANGS['activityfriend'] = 'je postao prijatelj sa';
$LANGS['activitysubscription'] = 'je pretplaćen';
$LANGS['next'] = "Dalje";
$LANGS['previous'] = "Natrag";
$LANGS['settings'] = "Postavke";
$LANGS['themescolors'] = "Teme i boje";
$LANGS['channelmodules'] = "Module";
$LANGS['videosandpl'] = "Videozapise i popise";
$LANGS['revert'] = "Vraćaj! Želim svoj stari kanal natrag";
$LANGS['all'] = "Sve";
$LANGS['uploads'] = "Prijenosi";
$LANGS['channelpl'] = "Popisi";
$LANGS['backtoplaylists'] = "Natrag do popisa";
$LANGS['searchuploads'] = "Pretraži prijenose";
$LANGS['info'] = "Informacija";
$LANGS['viewcomments'] = "Pogledajte komentare, povezane videozapise i još mnogo toga";
$LANGS['seeallcommentsandresponses'] = "Pogledajte sve komentare i videoodgovore";
$LANGS['pastethislink'] = "Zalijepite ovu vezu u e-poruku ili trenutnu poruku";
$LANGS['selectplaylist'] = "Odaberi Popis";
$LANGS['profilemsg'] = 'Gledatelji vašeg kanala ovdje će vidjeti veze, uključujući "pretplati se" i "dodaj kao prijatelja".';
$LANGS['profile'] = 'Profil';
$LANGS['profilechangessaved'] = 'Promjene spremljene.';
$LANGS['posting'] = 'objavljivanje...';
$LANGS['name'] = 'Ime';
$LANGS['totaluploadviews'] = 'Ukupno Pogleda na Prijenose';
$LANGS['channeldesc'] = 'Opis Kanala';
$LANGS['hometown'] = 'Rodni kraj';
$LANGS['occupation'] = 'Okupacija';
$LANGS['companies'] = 'Tvrtke';
$LANGS['schools'] = 'Škole';
$LANGS['interests'] = 'Interesi';
$LANGS['movies'] = 'Filmovi';
$LANGS['featuredchannelsdefault'] = 'Kliknite na "uredi" iznad za unos kanala na koje se želite povezati.';
$LANGS['featuredchannelsdesc'] = 'Molimo navedite do 4 odredišna kanala redoslijedom kojim želite da budu prikazani na vašem kanalu, odvojeni zarezima i bez razmaka. Nenavođenje kanala spriječit će pojavljivanje ovog okvira na vašem kanalu.';
$LANGS['backtochannel'] = "natrag do {c}ovog kanala";
$LANGS['refresh'] = "Osvježi";
$LANGS['whichcontent'] = "Koji sadržaj želite prikazati?";
$LANGS['myuploadedvideos'] = "Moji Prenešeni Videozapisi";
$LANGS['myfavorites'] = "Moji Omiljeni";
$LANGS['alsoshowall'] = 'Također prikaži prikaz "Sve"';
$LANGS['featuredvideo'] = 'Istaknuti videozapis';
$LANGS['usemostrecent'] = 'Koristi najnoviji video iz mog skupa istaknutih';
$LANGS['autoplayfeatured'] = "Automatično reproduciraj istaknuti video";
$LANGS['areyousure'] = "Jeste li sigurni da želite nastaviti?";
$LANGS['unsavedchanges'] = "Jeste li sigurni da želite promijeniti temu? Nespremljene promjene bit će izgubljene.";
$LANGS['showadvancedoptions'] = "pokaži napredne postavke";
$LANGS['hideadvancedoptions'] = "sakrij napredne postavke";
$LANGS['general'] = "Općenito";
$LANGS['colorpalettes'] = "Paleta Boje";
$LANGS['font'] = "Font";
$LANGS['wrappercolor'] = "Boja omota";
$LANGS['wrappertextcolor'] = "Boja teksta omota";
$LANGS['wrapperlinkcolor'] = "Boja omotne poveznice";
$LANGS['wrappertransparency'] = "Prozirnost omota";
$LANGS['repeatbackground'] = "Ponavljaj pozadinu";
$LANGS['titletextcolor'] = "Boja naslovnog teksta";
$LANGS['bodytextcolor'] = "Boja teksta";
$LANGS['transparency'] = "Prozirnost";
$LANGS['bgimgdesc'] = "Učitajte sliku koja će biti prikazana kao pozadina na vašem kanalu (maksimalno 2MB).";
$LANGS['channeltype'] = "Vrsta kanala";
$LANGS['channeltags'] = "Oznake kanala";
$LANGS['commaseparated'] = "(odvojeno zarezom)";
$LANGS['channeltagsdesc'] = "Oznake su ključne riječi koje se koriste da pomognu ljudima da pronađu vaš kanal.";

/* My Profile page */
$LANGS['myprofiledesc'] = 'Ova stranica sadrži sve postavke za vaš BitView kanal.';
$LANGS['profileimages'] = 'Profilna Slika';
$LANGS['avatar'] = 'Avatar';
$LANGS['backgroundimage'] = 'Pozadinska Slika';
$LANGS['deleteimage'] = 'Izbriši Sliku';
$LANGS['channelinformation'] = 'Informacija Kanala';
$LANGS['genderrelationprivate'] = 'Private';
$LANGS['fctitle'] = 'F.C. Naslov';
$LANGS['relationship'] = 'Relationship';
$LANGS['birthday'] = 'Rođendan';
$LANGS['showage'] = 'Pokaži dob';
$LANGS['aboutme'] = 'O Meni';
$LANGS['emailprefs'] = 'Preferencije E-Pošte';
$LANGS['emailpm'] = 'Pošalji mi e-poštu na Privatne Poruke';
$LANGS['emailcomm'] = 'Pošalji mi e-poštu na Video Komentare';
$LANGS['emailsub'] = 'Pošalji mi e-poštu na tjedne Pretplaćene Spotlight-ove';
$LANGS['layoutprefs'] = 'Postavke izgleda';
$LANGS['bgcolor'] = 'Pozadinska Boja';
$LANGS['bgfixed'] = 'Popravljeno';
$LANGS['bgrepeat'] = 'Ponavljanje';
$LANGS['norepeat'] = 'Bez Ponavljanja';
$LANGS['repeat'] = 'Ponavljanje';
$LANGS['repeatx'] = 'Ponavljanje X';
$LANGS['repeaty'] = 'Ponavljanje Y';
$LANGS['bgposition'] = 'Pozicija';
$LANGS['top'] = 'Vrh';
$LANGS['middle'] = 'Sredina';
$LANGS['bottom'] = 'Dno';
$LANGS['fontcolor'] = 'Boja Fonta';
$LANGS['titlefontcolor'] = 'Boja Fonta za Naslov';
$LANGS['linkcolor'] = 'Boja Poveznica';
$LANGS['hlfontcolor'] = 'Boja Označenog Fonta';
$LANGS['hlheadercolor'] = 'Označeni Vrh';
$LANGS['hlinsidecolor'] = 'Označena Sredina';
$LANGS['headercolor'] = 'Običan Vrh';
$LANGS['insidecolor'] = 'Obična Sredina';
$LANGS['font'] = 'Font Kanala';
$LANGS['featuredvideobox'] = 'Kutija za Istaknuti Videozapis';
$LANGS['subscribersbox'] = 'Kutija za Pretplatnike';
$LANGS['subscriptionsbox'] = 'Kutija za Pretplate';
$LANGS['friendsbox'] = 'Kutija za Prijatelje';
$LANGS['bulletinsbox'] = 'Kutija za Bulletin';
$LANGS['videosbox'] = 'Kutija za Videozapise';
$LANGS['favoritesbox'] = 'Kutija za Favorite';
$LANGS['playlistsbox'] = 'Kutija za Popis';
$LANGS['commentsbox'] = 'Kutija za Komentare';
$LANGS['ratingsbox'] = 'Kutija za Nedavne Aktivnosti';
$LANGS['partnersettings'] = 'Partner Postavke';
$LANGS['bannerimage'] = 'Natpisna Slika';
$LANGS['minibannerimage'] = 'Manja Natpisna Slika';
$LANGS['sideimage'] = 'Slika sa strane';
$LANGS['recommendedsize'] = 'preporučena veličina';
$LANGS['bannerlink'] = 'Web-stranica za Natpis';
$LANGS['sideimagelink'] = 'Web-stranica za sliku sa strane';
$LANGS['custombox'] = 'Prilagođena kutija';
$LANGS['customboxtitle'] = 'Naslov Prilagođene kutije';
$LANGS['customboxcontent'] = 'Sadržaj Prilagođene kutijet';
$LANGS['savechanges'] = 'Spremi Promjene';
$LANGS['submitimage'] = 'Pošalji Sliku';
$LANGS['overview'] = 'Pregled';
$LANGS['profilesetup'] = 'Postavke Profila';
$LANGS['playbacksetup'] = 'Playback Postavke';
$LANGS['emailoptions'] = 'Postavke e-pošte';
$LANGS['manageaccount'] = 'Upravljanje računa';
$LANGS['chvideoviews'] = 'Pregleda sa videozapisa';
$LANGS['change'] = "promijeni";
$LANGS['mynetwork'] = "Moja Mreža";
$LANGS['contacts'] = "Kontakti";
$LANGS['chvideocomments'] = "Video Komentare";
$LANGS['chmore'] = "Više";
$LANGS['changepicture'] = "Promijeni Sliku";
$LANGS['changepicturedesc'] = "Možete prenijeti JPG, BMP ili PNG datoteku. Nemojte postavljati slike koje sadrže slavne osobe, golotinju, umjetnička djela ili slike zaštićene autorskim pravima. Vaša će slika biti prikazana kao kvadrat veličine 88 x 88 piksela. <b>Maksimalna veličina datoteke je 2 MB.</b>";
$LANGS['describeyourself'] = "Opiši sebe";
$LANGS['personaldetails'] = "Osobne Detalje";
$LANGS['jobscareer'] = "Poslovi / Karijera";
$LANGS['education'] = "Edukacija";
$LANGS['videoplaybackquality'] = "Kvaliteta video reprodukcije";
$LANGS['videoplaybackqualitydesc'] = "Odaberite zadanu postavku za gledanje videa";
$LANGS['alwayshd'] = "Uvijek reproduciraj video u HD kvaliteti";
$LANGS['neverhd'] = "Nikad ne reproduciraj nijedan video u HD kvaliteti";
$LANGS['currentemail'] = "Trenutna adresa e-pošte";
$LANGS['changeemailaddress'] = "Promijeni adresu e-pošte";
$LANGS['changeemail'] = "Promijeni e-poštu";
$LANGS['partnerimages'] = "Partner Slike";
$LANGS['partnerimagelinks'] = "Poveznica Partner Slika";
$LANGS['accountstatuscg'] = "Stanje računa: Smjernica Zajednice";
$LANGS['accountstatuscopy'] = "Stanje računa: Autorska Prava";
$LANGS['changeusername'] = "Promjeni korisničko ime";
$LANGS['changepassword'] = "Promjeni lozinku";
$LANGS['deleteaccount'] = "Izbriši račun";
$LANGS['goodaccount'] = "Vaš račun je u dobrom stanju.";
$LANGS['accountstrike'] = "Imate {s} opomena. Budite pažljivi!";
$LANGS['accountstrikes'] = "Imate {s} opomena. Budite pažljivi!";
$LANGS['cannotchangeusername'] = "Ne možete još promjeniti korisničko ime! Molimo sačekajte do ";
$LANGS['usernamechangedesc'] = "Svoje korisničko ime možeš promijeniti samo jednom godišnje, stoga mudro odaberite novo korisničko ime.";
$LANGS['newusername'] = "Novo korisničko ime";
$LANGS['currentpassword'] = "Trenutna lozinka";
$LANGS['newpassword'] = "Nova lozinka";
$LANGS['confirmnewpassword'] = "Potvrdi novu lozinku";
$LANGS['enterpassword'] = "Iz sigurnosnih razloga, molimo unesite svoju lozinku";

/* Upload page */
$LANGS['uploadpagetitle'] = 'Prijenos Videozapisa';
$LANGS['step1of2'] = 'Korak 1 od 2';
$LANGS['step2of2'] = 'Korak 2 od 2';
$LANGS['videocategory'] = 'Kategorija videozapisa';
$LANGS['tagsdesc'] = 'Oznake su ključne riječi koje se koriste da pomognu ljudima da pronađu vaš video.<br> <i>(odvojeno zarezom)</i>';
$LANGS['requiredfield'] = '(* označava obavezno polje)';
$LANGS['datemapoptions'] = 'Opcije datuma i karte';
$LANGS['optional'] = '(neobavezno)';
$LANGS['chooseoptions'] = 'odaberi opcije';
$LANGS['lessoptions'] = 'manje opcija';
$LANGS['addressrecorded'] = 'Adresa gdje je snimljen';
$LANGS['uploadcontinue'] = 'Učitaj video...';
$LANGS['file'] = 'Datoteka';
$LANGS['broadcastoptions'] = 'Opcije Emitiranja';
$LANGS['uploadvideo'] = 'Objavi Videozapis';
$LANGS['needfilevideotoupload'] = 'Molimo da odaberete video datoteku za prijenos!';
$LANGS['aboutuploading'] = 'O prijenosima...';
$LANGS['uploaddesc1'] = 'Prijenos obično traje 1-5 minuta po MB na brzoj vezi, a obrađivanje vašeg videa traje nekoliko minuta.';
$LANGS['videolimit1'] = 'Vaš video je ograničen na 100MB - maksimalno trajanje videozapisa je 15 minuta.';
$LANGS['videolimit2'] = 'Vaš video je ograničen na 2 GB - maksimalno trajanje videozapisa je 15 minuta.';
$LANGS['partnervideolimit1'] = 'Vaš video je ograničen na 100MB - maksimalno trajanje videozapisa je 30 minuta.';
$LANGS['partnervideolimit2'] = 'Vaš video je ograničen na 2 GB - maksimalno trajanje videozapisa je 30 minuta.';
$LANGS['myvideosdesc'] = 'Nakon prijenosa moći ćete urediti ili ukloniti ovaj videozapis u bilo kojem trenutku ispod veze "<a href="/my_videos">Moji Videozapisi</a>" na vrhu stranice.';
$LANGS['newuploader'] = 'Koristite novi video uploader';
$LANGS['olduploader'] = 'Koristi stari video uploader';
$LANGS['videoadded'] = 'Vaš video je uspješno dodan!';
$LANGS['videoaddeddesc'] = 'Vaš video se trenutno obrađuje i bit će dostupan za gledanje za nekoliko minuta.';
$LANGS['thankyou'] = 'Hvala Vam';
$LANGS['sharelink'] = 'Podijelite svoju video vezu! Kopirajte i zalijepite ispod:';
$LANGS['embedlink'] = 'Reproduciraj ovaj video izravno NA svojoj web stranici! Kopirajte i zalijepite sljedeći isječak:';
$LANGS['allrequiredinfo'] = 'Molimo ispunite sva obavezna polja!';
$LANGS['videoscanbe'] = 'Videozapisi mogu biti...';
$LANGS['uploadhd'] = 'Visoka definicija';
$LANGS['uploadsize'] = 'Veličine do 2 GB';
$LANGS['uploadlength'] = 'Do 15 minuta duljine';
$LANGS['uploadlengthpartners'] = 'U trajanju do 1 sat';
$LANGS['uploadformats'] = 'Širok izbor formata';
$LANGS['basicuploader'] = 'Problemi s prijenosom? Isprobajte <a href="/my_videos_upload_basic">osnovni prijenos videozapisa</a> (radi na starijim računalima i web-preglednicima).';
$LANGS['uploadinstruction1'] = '<strong>Važno:</strong> Nemojte prenositi nikakve TV emisije, glazbene spotove, glazbene koncerte ili reklame bez dopuštenja osim ako se u potpunosti sastoje od sadržaja koji ste sami izradili.';
$LANGS['uploadinstruction2'] = '<a href="/guidelines">Smjernice zajednice</a> mogu vam pomoći da odredite krši li vaš videozapis nečija autorska prava.';
$LANGS['uploadinstruction3'] = 'Klikom na "Objavi Videozapis", izjavljujete da ovaj video ne krši <a id="terms-of-use-link" href="/terms">Uvjete korištenja</a> BitViewa i da posjeduju sva autorska prava na ovaj videozapis ili imaju ovlaštenje za prijenos istog.';
$LANGS['fileuploaded'] = 'Vaša datoteka je prenesena. Trenutno obrađujemo videozapis...';
$LANGS['videosettingssaved'] = 'Vaše video postavke su spremljene.';
$LANGS['uploadprogress'] = 'Napredak prijenosa';
$LANGS['timeremaining'] = 'Oko {m} min. preostalo...';
$LANGS['minuteremaining'] = 'Preostalo je manje od minute...';
$LANGS['preview'] = 'Pregled';
$LANGS['processing'] = 'Obrada';
$LANGS['generatingpreviews'] = 'Generiranje pregleda...';
$LANGS['errorpreview'] = "Pogreška: nije moguće generirati pregled";
$LANGS['infoandprivacy'] = "Video informacije i postavke privatnosti";
$LANGS['sharingoptions'] = "Opcije dijeljenja";
$LANGS['url'] = "URL";
$LANGS['durationerror'] = "Možete uploadati samo video zapise duljine do {n} minuta.";

/* Video Response Upload */
$LANGS['postingresponse'] = "Objavljujete video odgovor na: ";
$LANGS['responsessofar'] = "{n} Video Odgovor(a) do sada";
$LANGS['chooseavideo'] = "Odaberi Video";
$LANGS['uploadavideo'] = "Prenesi Video";
$LANGS['responsesdesc1'] = "<h4>Što je video odgovor?</h4><p>Jeste li ikada željeli odgovoriti na video? Sada imate priliku - možete prenijeti odgovor na ovaj video, a mi ćemo poveži ih zajedno.</p>";
$LANGS['responsesdesc2'] = "<h4>Kako mogu objaviti video odgovor?</h4><p>Možete snimiti novi video, odabrati neki od video zapisa koje već imate ili stvoriti i prenijeti novi video. Odaberite opciju s lijeve strane koja najbolje odgovara vašim potrebama.</p>";
$LANGS['responsesdesc3'] = '<h4>Ups! Zapravo sam mislio objaviti tekstualni komentar. Kako to učiniti?</h4><p>Vratite se na video (pritiskom na gumb "natrag" u pregledniku ili klikom na naslov videa na vrhu ove stranice) i kliknite "Objavi tekstualni komentar" .</p>';
$LANGS['choosevideotitle'] = "Odaberite jedan od svojih postojećih videa kao odgovor";
$LANGS['selectvideo'] = "Odaberite Videozapis kojim želite odgovoriti: ";
$LANGS['useselectedvideo'] = "Koristi odabrani video";
$LANGS['uploadvideoresponse'] = "Upload your Video Response";
$LANGS['clickstart'] = 'Pritisnite "Započni" kako biste počeli prijenos vašeg Video Odgovora.';
$LANGS['start'] = 'Započni';

/* Partners */
$LANGS['partnerhead'] = 'Partnerships';
$LANGS['partnertitle'] = 'Partneri s BitView-om';
$LANGS['partnerdesc'] = "Imate izvrsne videozapise i sve veću publiku. Neka vam BitView pomogne da pređete na višu razinu putem našeg Partnerskog programa.";
$LANGS['applynow'] = 'Pošalji zahtjev';
$LANGS['contentpartners'] = 'Partneri za sadržaj';
$LANGS['partnerbenefits'] = 'Pogodnosti za partnere';
$LANGS['partnerbenefitsdesc'] = 'Mnoge su prednosti ako postanete BitView partner. Neki od njih uključuju:<br><br>- Brendiranje: istaknite se prilagođenim brendiranjem, što uključuje bannere, prilagođeni okvir za vaš kanal i značku partnera na svim vašim videozapisima.<br><br>- Postoje više pogodnosti dolazi u budućnosti!';
$LANGS['qualificationsfaq'] = 'Kvalifikacije & FAQ';
$LANGS['qualificationsfaqdesc'] = 'Da biste se kvalificirali za BitView Partner program, morate zadovoljiti neke minimalne kriterije:<br><br>- Stvarate originalne videozapise prikladne za online streaming.<br><br>- Imate > 75 pretplatnika.<br><br>- Vaš račun ne krši nijednu <a href="/guidelines">Smjernicu zajednice.</a>';

/* Staff */
$LANGS['bvstaff'] = 'BitView Osoblje';
$LANGS['bvstaffdesc'] = "Ovo je popis ljudi koji su radili (ili još uvijek rade) na BitViewu - održavajući web stranicu živom - tako da korisnici mogu izraziti sebe.";
$LANGS['owners'] = 'Vlasnici';
$LANGS['ownerdesc'] = 'Ljudi koji - koja šokirajuća zanimljivost - posjeduje BitView stvarčicu.';
$LANGS['coowndev'] = 'Suvlasnik & <br> Programer';
$LANGS['owndev'] = 'Vlasnik & <br> Programer';
$LANGS['coownserver'] = 'Suvlasnik &<br>Vlasnik poslužitelja/Programer';
$LANGS['modsanddevs'] = 'Moderatori i Programeri';
$LANGS['modsanddevsdesc'] = 'Ljudi koji web stranicu održavaju sigurnom i preglednom. Imate li problema sa svojim računom? Trebao bi ih kontaktirati.';
$LANGS['moderator'] = 'Moderator';
$LANGS['moddev'] = 'Developer &<br>Moderator';
$LANGS['lettertitle'] = 'Pismo svim ljudima koji su pomogli oko web stranice';
$LANGS['letter'] = "Dragi suvlasnici, programeri i moderatori BitViewa,<br><br>
                U ime cijelog BitView tima, želim izraziti svoju zahvalnost od srca na vašoj iznimnoj predanosti i marljivom radu. Kao jednog od vlasnika, ispunjava me neizmjernim ponosom svjedočiti rastu i uspjehu naše platforme za dijeljenje videa, a to ne bi bilo moguće bez vašeg neprocjenjivog doprinosa.
                <br><br>
                Ostalim suvlasnicima, hvala na nepokolebljivoj podršci i viziji. Vaša predanost razvoju i poboljšanju platforme bila je ključna u oblikovanju BitView.net-a u izvanrednu zajednicu kakva je danas. Vaše vodstvo i strateško vodstvo bili su ključni u suočavanju s izazovima i prilikama koje su nam se ukazale.
                <br><br>
				Za naše talentirane programere, vaša tehnička stručnost i inovativne ideje transformirale su BitView u vrhunsku platformu koja savršeno predstavlja kako je YouTube izgledao u davna vremena. Vaši bezbrojni sati kodiranja, rješavanja problema i implementacije značajki podigli su korisničko iskustvo i učinili našu platformu središtem kreativnosti i zabave. Vaša predanost usavršavanju funkcionalnosti i performansi web-mjesta doista je vrijedna hvale.
                <br><br>
                Našim marljivim moderatorima izražavam najdublju zahvalnost za održavanje integriteta i sigurnosti naše zajednice. Vaša budnost u provođenju pravila i smjernica, osiguravanju interakcije s poštovanjem i brzom rješavanju bilo kakvih problema koji su se pojavili bili su ključni za poticanje ugodnog okruženja za sve korisnike. Vaši napori da BitView održite prostorom za konstruktivan angažman i pozitivan sadržaj su vrlo pohvalni.
                <br><br>
                Zajedno, kao jedinstven tim, postigli smo značajne prekretnice i prevladali brojne prepreke. Uspjeh BitViewa dokaz je kolektivnog truda i strasti koje svatko od vas donosi za stol. Vaša predanost našoj zajedničkoj viziji bila je doista inspirativna i zahvalan sam što uz sebe imam tako iznimne pojedince.
                <br><br>
                Dok nastavljamo rasti i razvijati se, čuvajmo veze koje smo iskovali i ostanimo predani vrijednostima koje definiraju naše malo mjesto. Zajedno ćemo nastaviti to nostalgično putovanje i pružiti platformu za kreatore da pokažu svoje talente.
                <br><br>
                Još jednom, hvala vama: Suvlasnicima, programerima i moderatorima, na vašoj nepokolebljivoj predanosti, stručnosti i nepokolebljivoj podršci. Vaš naporan rad nije prošao nezapaženo i nevjerojatno sam ponosan što sam dio ovog izvanrednog tima.
                <br><br>
                Nastavite se izražavati,<br>
                <3 vistafan12";
$LANGS['backtobitview'] = "Natrag na BitView";

/* My Friends */
$LANGS['myfriends'] = 'Moji Prijatelji';
$LANGS['invites'] = 'Pozivnice';
$LANGS['myinvites'] = 'Moje Pozivnice';
$LANGS['incominginvites'] = 'Nadolazeće Pozivnice';
$LANGS['noinvites'] = 'You have no invites...';
$LANGS['actions'] = 'Akcije';
$LANGS['retract'] = 'Povuci';

/* History */
$LANGS['clearhistory'] = "Clear Viewing History";
$LANGS['noviewinghistory'] = "Nema videozapisa u vašoj povijesti pregledavanja.";
$LANGS['addto'] = "Dodaj u";
$LANGS['sortorder'] = "Order";
$LANGS['sortnewest'] = "Najnoviji";
$LANGS['sortoldest'] = "Najstariji";
$LANGS['sortmostviewed'] = "Most viewed";
$LANGS['sortlongest'] = "Longest";
$LANGS['sortshortest'] = "Shortest";
$LANGS['sortaz'] = "A-Z";
$LANGS['sortza'] = "Z-A";
$LANGS['newpltitle'] = "Playlist title";
$LANGS['newpldesc'] = "Playlist description";
$LANGS['newpltags'] = "Playlist tags";
$LANGS['newplbutton'] = "Izradi popis";
$LANGS['addvideos'] = "Dodaj videozapise";
$LANGS['liked'] = "Liked";
$LANGS['mylikedvideos'] = "My Liked Videos";
$LANGS['savedtoplaylist'] = "Videos saved to playlist(s) successfully!";
$LANGS['sureremovevideos'] = "Are you sure you want to delete the selected videos?";
$LANGS['remove'] = "Remove";
$LANGS['plvideoamountsingular'] = "video";

/* QuickList */
$LANGS['playquicklist'] = "Reproduciraj brzi popis";
$LANGS['clearquicklist'] = "Obriši brzi popis";
$LANGS['noquicklist'] = "Nema video zapisa na vašem brzom popisu.";
$LANGS['noquicklistdesc'] = "QuickList vam omogućuje da napravite popis videozapisa za kasnije gledanje. Kliknite &quot;+&quot; (u donjem lijevom kutu) bilo kojeg videa da biste ga dodali na svoj QuickList. Za pregled popisa pogledajte za traku QuickList ispod bilo kojeg videozapisa koji gledate.";
$LANGS['quicklistcleared'] = "Vaš Quicklist je uspješno izbrisan.";
$LANGS['addedtoquicklist'] = "Dodano <br> brzom popisu";
$LANGS['queue'] = "Ček čekanja";
$LANGS['playqueue'] = "Reprodukcija u redu";
$LANGS['clearqueue'] = "Očisti red čekanja";
$LANGS['addtoqueue'] = "Dodaj u red čekanja";
$LANGS['addedtoqueue'] = "Dodano u <br> red čekanja";


/* About */
$LANGS['aboutus'] = 'O nama';
$LANGS['abouttitle'] = 'Što je BitView?';
$LANGS['aboutdesc'] = 'BitView je način da svoje videozapise dopremite do ljudi koji su vam važni. Uz BitView možete:';
$LANGS['about1'] = 'Pokažite svijetu svoje omiljene videozapise';
$LANGS['about2'] = 'Snimite svoje pse, mačke i druge kućne ljubimce';
$LANGS['about3'] = 'Blogirajte videozapise koje snimate digitalnom kamerom ili mobitelom';
$LANGS['about4'] = 'Sigurno i privatno pokažite videozapise svojim prijateljima i obitelji diljem svijeta';
$LANGS['about5'] = '... i još, još, još više!';
$LANGS['aboutsignup'] = '<a href="/signup">Prijavite se sada</a> i otvorite besplatni račun.';
$LANGS['abouthelp'] = 'Kako biste saznali više o našoj usluzi, pogledajte naš odjeljak <a href="help">Pomoć</a>.';
$LANGS['aboutmail'] = 'Slobodno nas <a href="mailto:bitview@vistafan12.eu.org">kontaktirajte</a>.';

/* Community Guidelines */
$LANGS['bvguidelines'] = 'BitView smjernice zajednice';
$LANGS['cgtitle1'] = 'Poštujte BitView zajednicu';
$LANGS['cgtitle2'] = "Nemoj prijeći crtu";
$LANGS['cgtitle3'] = 'Mi provodimo ove smjernice';
$LANGS['cgtitle4'] = 'BitView je za zajednicu';
$LANGS['cgtitle5'] = 'Savjeti o smjernicama zajednice';
$LANGS['cgdesc1'] = "Ne tražimo poštovanje koje je rezervirano za časne sestre, starije osobe i neurokirurge. Mislimo da ne zlorabite stranicu. Svaka cool nova značajka zajednice na BitViewu uključuje određenu razinu povjerenja. Vjerujte da ste odgovorni, a milijuni korisnika poštuju to povjerenje.";
$LANGS['cgdesc2'] = "Ovdje su neka zdravorazumska pravila koja će vam pomoći da se klonite problema:";
$LANGS['cgdesc3'] = "Molimo vas da ova pravila shvatite ozbiljno i da ih uzmete k srcu. Ne pokušavajte tražiti rupe u zakonu ili pokušavati zaobići smjernice - samo ih razumite i pokušajte poštovati duh u kojem su su stvoreni. Ako želite više detalja, pogledajte naše <a href='#tips'>Savjete o smjernicama zajednice</a>.";
$LANGS['cgdesc4'] = "U redu, ovo je više o nama nego o vama. BitView osoblje pregledava označene videozapise 24 sata dnevno, sedam dana u tjednu kako bi utvrdilo krše li naše Smjernice zajednice. Kada krše, mi ih uklanjamo . Ponekad videozapisi ne krše naše Smjernice zajednice, ali možda nisu prikladni za svakoga. Računi se kažnjavaju zbog kršenja Smjernica zajednice, a ako je vaš račun vrijedan prekinut, neće vam biti dopušteno kreirati nove račune. Za više informacija o tome kako se provode Smjernice zajednice i posljedicama njihovog kršenja, posjetite <a href='/help'>Centar za pomoć</a>. ";
$LANGS['cgdesc5'] = "Zapamtite da je ovo vaša zajednica! Svaki korisnik BitViewa čini stranicu onakvom kakva jest, stoga se nemojte bojati istražiti i uključiti se!";
$LANGS['cgdesc6'] = "To je to! Hvala na čitanju!";
$LANGS['cgdesc7'] = "Želite malo više uvida u ograničenja i iznimke u Smjernicama zajednice? Evo nekoliko korisnih primjera i savjeta:";
$LANGS['rule1'] = "BitView nije za pornografiju ili seksualno eksplicitan sadržaj. Ako ovo opisuje vaš videozapis, čak i ako je to videozapis vas samih, nemojte ga objavljivati ​​na BitViewu. Također, imajte na umu da blisko surađujemo s provođenje zakona i prijavljujemo iskorištavanje djece.";
$LANGS['rule2'] = "Nemojte objavljivati ​​videozapise koji prikazuju loše stvari kao što su zlostavljanje životinja, zlouporaba droga, maloljetničko pijenje i pušenje ili izrada bombi.";
$LANGS['rule3'] = "Grapičko ili neopravdano nasilje nije dopušteno. Ako vaš video prikazuje nekoga fizički ozlijeđenog, napadnutog ili poniženog, nemojte ga objavljivati.";
$LANGS['rule4'] = "BitView nije mjesto za šok. Ne postavljajte odvratne videozapise nesreća, mrtvih tijela ili sličnih stvari s namjerom šokiranja ili gađenja.";
$LANGS['rule5'] = "Poštujte autorska prava. Učitavajte samo videozapise koje ste sami napravili ili za koje ste ovlašteni koristiti. To znači da nemojte učitavati videozapise koje niste napravili ili koristiti sadržaj u svojim videozapisima čiji je netko drugi vlasnik autorsko pravo na, kao što su glazbeni zapisi, isječci programa zaštićenih autorskim pravima ili videozapisi koje su napravili drugi korisnici, bez potrebnih ovlaštenja.";
$LANGS['rule6'] = "Potičemo slobodu govora i branimo svačije pravo na izražavanje nepopularnih stajališta. Ali ne dopuštamo govor mržnje (govor koji napada ili ponižava skupinu na temelju rase ili etničkog podrijetla, vjere, invaliditeta , spol, dob, status veterana i seksualna orijentacija/rodni identitet) također se odnosi na promicanje ekstremističkih ideologija u pozitivnom svjetlu.";
$LANGS['rule7'] = "Stvari poput predatorskog ponašanja, uhođenja, prijetnji, uznemiravanja, zastrašivanja, narušavanja privatnosti, otkrivanja tuđih osobnih podataka i poticanja drugih na nasilne radnje ili kršenje Uvjeta korištenja shvaćaju se vrlo ozbiljno. Svatko tko bude uhvaćen u takvim stvarima može biti trajno zabranjen pristup BitViewu.";
$LANGS['rule8'] = "Svi mrze neželjenu poštu. Nemojte stvarati zavaravajuće opise, oznake, naslove ili sličice kako biste povećali preglede. Nije u redu objavljivati ​​velike količine neciljanog, neželjenog ili ponavljajućeg sadržaja, uključujući komentare i privatne poruke.";
$LANGS['rule9'] = "Čuvajmo web stranicu sigurnom. Ne pokušavajte grubo natjerati račun koji ne posjedujete. Štoviše, javno dijeljenje podataka za prijavu na račun nije dopušteno.";
$LANGS['rule10'] = "Više računa je sranje. Želimo prave brojeve na video zapisima i kanalima. Nemojte koristiti više od jednog računa za ocjenjivanje videa i/ili komentara. Nije vam dopušteno korištenje više računa za pretplatu na ni sebi.";
$LANGS['rule11'] = "Jeste li prekršili jedno od ovih pravila i vaš račun je suspendiran? Podrazumijeva se da izbjegavanje ove kazne nije prihvaćeno. Svaki novi račun koji je stvorila suspendirana osoba bit će automatski izbrisan .";
$LANGS['cglist1'] = "Zabavite se sa web mjestom. Ovdje ima puno toga za vidjeti i puno ljudi izrađuje nevjerojatne stvari — jedan od njih biste mogli biti i vi! Oprema postaje sve jeftinija i lakša za korištenje cijelo vrijeme, stoga zaronite unutra i uživaj.";
$LANGS['cglist2'] = "Recite ljudima što mislite. Povratne informacije su dio iskustva, a kada se daju s poštovanjem, mogu biti sjajan način da steknete prijatelje, podijelite priče i obogatite svoje vrijeme na BitViewu. Zato ostavite komentirajte, ocjenjujte videozapise, dajte vlastite odgovore na videozapise koji utječu na vas, sudjelujte u natjecanjima od interesa — puno se toga događa i postoji mnogo načina za sudjelovanje.";
$LANGS['cglist3'] = "Možda vam se neće svidjeti sve što vidite. Neki od sadržaja ovdje mogu vas uvrijediti — ako ustanovite da krši naše Uvjete korištenja, kliknite gumb &quot;Označi&quot; ispod videa gledate da ga pošaljete na pregled osoblju BitViewa. Ako ne, razmislite o tome da jednostavno kliknete na nešto drugo — zašto gubiti vrijeme gledajući videozapise koji vam se ne sviđaju?";
$LANGS['thebitviewteam'] = "— BitView Tim";
$LANGS['cgcat1'] = "Seks i golotinja";
$LANGS['cgcat2'] = "Govor mržnje";
$LANGS['cgcat3'] = "Šokantno i odvratno";
$LANGS['cgcat4'] = "Opasne nezakonite radnje";
$LANGS['cgcat5'] = "Djeca";
$LANGS['cgcat6'] = "Autorsko pravo";
$LANGS['cgcat7'] = "Privatnost";
$LANGS['cgcat8'] = "Uznemiravanje";
$LANGS['cgcat9'] = "Lažno predstavljanje";
$LANGS['cgcat10'] = "Prijetnje";
$LANGS['cgcat1desc'] = "Većina golotinje nije dopuštena, osobito ako je u seksualnom kontekstu. Općenito, ako je namjera videozapisa biti seksualno provokativan, manje je vjerojatno da će biti prihvatljiv za BitView. Postoje iznimke za neke obrazovni, dokumentarni i znanstveni sadržaj, ali samo ako je to jedina svrha videozapisa i ako nije nepotrebno eksplicitan. Na primjer, dokumentarac o raku dojke bi bio prikladan, ali objavljivanje isječaka izvan konteksta dokumentarca možda nije. Ovo također vrijedi za animirani sadržaj.";
$LANGS['cgcat2desc'] = 'Govor mržnje" odnosi se na sadržaj koji promiče mržnju prema članovima zaštićene skupine. Na primjer, rasistički ili seksistički sadržaj može se smatrati govorom mržnje. Ponekad postoji tanka linija između onoga što jest i onoga što jest ne smatra se govorom mržnje. Na primjer, općenito je u redu kritizirati naciju, ali nije u redu praviti uvredljive generalizacije o ljudima određene nacionalnosti.';
$LANGS['cgcat3desc'] = "Svijet je opasno mjesto. Ponekad se ljudi povrijede i neizbježno je da ti događaji budu dokumentirani na BitViewu. Međutim, nije u redu objavljivati ​​nasilan ili krvav sadržaj čija je prvenstveno namjera šokirati , senzacionalan ili omalovažavajući. Ako je videozapis posebno eksplicitan ili uznemirujući, trebao bi biti uravnotežen s dodatnim kontekstom i informacijama, na primjer, uključivanje isječka iz klaonice u videozapis o uzgoju u tvornici može biti prikladno jezivi isječci klanja životinja u videozapisu mogu se smatrati nepotrebnim ako je njihova svrha šokirati, a ne ilustrirati.";
$LANGS['cgcat4desc'] = "Iako se možda ne čini pošteno reći da ne možete pokazati nešto zbog onoga što bi gledatelji teoretski mogli učiniti kao odgovor, povlačimo crtu na sadržaj koji je namijenjen poticanju nasilja ili opasnim, nezakonitim aktivnostima koji imaju svojstven rizik od ozbiljnih fizičkih ozljeda ili smrti. To znači da se ne smiju objavljivati ​​videozapisi o stvarima kao što su upute za izradu bombi, obuka nindža ubojica, snajperski napadi, videozapisi koji treniraju teroriste ili savjeti o ilegalnim uličnim utrkama ili dokumentarac i ne bi trebao biti osmišljen da pomogne ili potakne druge da ih oponašaju.";
$LANGS['cgcat5desc'] = "Videozapisi koji uključuju djecu (bilo tko mlađi od 18 godina) posebno su osjetljivi. Videozapisi koji sadrže djecu nikada ne bi trebali biti seksualno sugestivni ili nasilni. Budite oprezni kada objavljujete nešto što uključuje dijete. Ako dijelite privatni trenutak ili kućni film, razmislite o tome da ga učinite privatnim videozapisom kako bi ga mogli vidjeti samo vaša obitelj i prijatelji. Štoviše, prihvaćanjem <a href='/terms'>Uvjeta korištenja</a> potvrđujete da. imate više od 14 godina. Računi koji pripadaju maloljetnim korisnicima bit će suspendirani.";
$LANGS['cgcat6desc'] = "Kada stvorite nešto originalno, posjedujete autorska prava za to. Isto tako, kada drugi ljudi stvaraju sadržaj, mogu imati autorska prava na njega. Kao kreativna zajednica, bitno je da svi na BitViewu poštuju autorska prava drugih. Ako niste sigurni hoće li nešto povrijediti nečija autorska prava, najsigurnije je stvoriti nešto potpuno originalno, sa slikama i zvukom koje ste sami stvorili, ne morate brinuti o autorskim pravima — posjedujete ga. Ako ste snimili nešto s DVD-a, snimili video s TV ekrana ili preuzeli video s interneta, nemojte to objavljivati ​​ako nemate dopuštenje.";
$LANGS['cgcat7desc'] = "Ako video koji ste snimili uključuje ljude koje je lako identificirati i koji nisu pristali na snimanje, postoji mogućnost da će podnijeti žalbu zbog povrede privatnosti tražeći njegovo uklanjanje. Obavijestit ćemo ako se to dogodi i dati vam priliku da uredite i ponovno prenesete svoj videozapis prije nego što postupimo po pritužbi, nemojte prenijeti drugu verziju s istim osobama podnijeti drugu žalbu zbog povrede privatnosti ili vas prijaviti za uznemiravanje, uključujući telefonske brojeve, adrese, brojeve kreditnih kartica i državne osobne iskaznice. ";
$LANGS['cgcat8desc'] = "Svodi se na poštovanje. BitView je samo dijeljenje i interakcija sa zajednicom na načine pune poštovanja. Ako niste sigurni da li video ili komentar koji ste napravili prelazi granicu, slijedite jednostavno pravilo: ako to ne želite nekome reći u lice, nemojte to reći na BitViewu. A ako želite napasti, uznemiravati, ponižavati ili glumiti druge, idite negdje drugdje.";
$LANGS['cgcat9desc'] = "Lažno predstavljanje drugog korisnika kopiranjem nečijeg točnog izgleda kanala, korištenjem sličnog korisničkog imena ili predstavljanjem kao ta osoba u komentarima, e-porukama ili videima smatra se uznemiravanjem. Ako želite zadržati svoj račun, držite se podalje sudjelovanje u bilo kojem obliku lažnog predstavljanja ili uznemirujućih aktivnosti na stranici.";
$LANGS['cgcat10desc'] = "Korisnici se ne bi trebali osjećati ugroženo kada su na BitViewu. Točka. Ne ostavljajte prijeteće komentare na video zapisima drugih ljudi.";

/* Contests */
$LANGS['monthlycontest'] = "Mjesečno natjecanje";
$LANGS['monthlycontestschedule'] = "Raspored mjesečnih natjecanja videozapisa";
$LANGS['whatisit'] = "Što je?";
$LANGS['thismonthcontest'] = "Ovaj mjesec";
$LANGS['lastmonthwinners'] = "Pobjednici prošlog mjeseca";
$LANGS['howtoenter'] = "Kako se mogu prijavit?";
$LANGS['whowins'] = "Tko pobjeđuje?";
$LANGS['whowinsdesc'] = "Pobjednika će na kraju mjeseca odabrati BitView osoblje.";
$LANGS['theprize'] = "Nagrada?";
$LANGS['theprizedesc'] = "Slava, bogatstvo i zavist svih očiju.";
$LANGS['contestsuggestion'] = 'Imate li prijedlog za mjesečno natjecanje videozapisa? Molimo <a href="mailto:bitview@vistafan12.eu.org">recite nam</a> o tome.';

/* Help */
$LANGS['q1'] = 'P: Kako mogu podijeliti svoje video zapise i povezati se na njih sa svoje web stranice?';
$LANGS['a1'] = 'A: <a href="/sharing">Kako podijeliti svoje videozapise i povezati ih s njima</a>';
$LANGS['q2'] = 'P: Koju vrstu videa mogu uploadati?';
$LANGS['a2'] = 'O: Možete postaviti bilo koju vrstu osobnog videa koji želite podijeliti sa svijetom. Ne dopuštamo golotinju i vaš video mora biti prikladan za svu publiku.
<br/>
<br/>
Međutim, ovo još uvijek ostavlja puno prostora za kreativnost!! Imate li <a href="results?search=dog&t=Search+Videos">psa</a> ili <a href="/results?search=cat&t=Search+Videos">mačku</a>? Jeste li bili na odmoru u <a href="/results?search=mexico&t=Search+Videos">Meksiku</a>? Živite li u <a href="/results?search=netherlands&t=Search+Videos">Nizozemskoj</a>?
<br/>
<br/>
Ovo su samo neki od primjera videozapisa koje naši korisnici učitavaju. Na kraju krajeva, sami sebe najbolje poznajete. Što biste <i>vi</i> htjeli snimiti videom?';
$LANGS['q3'] = 'P: Koliko dug može biti moj video?';
$LANGS['a3'] = 'O: Videozapis mora biti kraći od 15 minuta i manji od 2GB (100MB ako koristite stari preglednik).';
$LANGS['q4'] = 'P: Koje formate video datoteka mogu uploadati?';
$LANGS['a4'] = 'O: BitView prihvaća video datoteke s većine digitalnih kamera i mobitela u formatima datoteka .WMV, .AVI, .MOV, .MPG, .MP4.';
$LANGS['q5'] = 'P: Kako mogu poboljšati svoje videozapise?';
$LANGS['a5'] = 'O: Potičemo vas da svoje videozapise uređujete softverom kao što je <a href="https://windows-movie-maker-vista.en.softonic.com/" target="_blank ">Windows Movie Maker</a> (uključen u svaku instalaciju sustava Windows) ili <a href="https://www.apple.com/lae/imovie/" target="_blank">Apple iMovie</a> . Pomoću ovih programa možete jednostavno uređivati ​​svoje video zapise, dodavati zvučne zapise itd.';
$LANGS['q6'] = 'P: Zadržavam li autorska prava i druga zakonska prava na svoje videozapise?';
$LANGS['a6'] = 'O: Da. Zadržavate sva prava na svoj sadržaj. BitView ne preuzima autorska prava na vaš materijal.';
$LANGS['q7'] = 'P: Koja je vaša politika o kršenju autorskih prava?';
$LANGS['a7'] = "O: BitView poštuje prava nositelja autorskih prava i izdavača i prihvaća prijenos videozapisa samo od osoba koje imaju sva potrebna prava na učitani materijal. Naša politika je odgovoriti na sve obavijesti o navodnom kršenju u skladu sa Zakonom o autorskim pravima u digitalnom tisućljeću (DMCA) Ako primimo obavijest ili na drugi način imamo razloga vjerovati da sadržaj koji ste poslali krši autorska prava druge strane, vaš račun može biti ukinut, a video uklonjen iz BitViewa.";
$LANGS['q8'] = 'P: Kako mogu prijaviti kršenje autorskih prava?';$LANGS['a8'] = 'O: Ako smatrate da je netko drugi prenio vaš sadržaj zaštićen autorskim pravima bez vašeg dopuštenja, potičemo vas da kontaktirate tu osobu kako biste izravno s njom riješili sve nesuglasice. Također možete kontaktirati naš tim za podršku putem ove <a href="mailto:bitview@vistafan12.eu.org">e-pošte</a>.';
$LANGS['q9'] = 'P: Što ako sam lažno optužen za kršenje autorskih prava?';
$LANGS['a9'] = "O: Obavijestit ćemo vas ako primimo pritužbu o autorskim pravima za bilo koji od vaših video sadržaja koji se nalazi na BitViewu. Dat ćemo vam priliku da na odgovarajući način odgovorite.";
$LANGS['q10'] = 'P: Što radite da spriječite pojavljivanje sadržaja koji krši vaša pravila u BitViewu?';
$LANGS['a10'] = 'O: Preliminarni pregled učitanih videozapisa vršimo ručnim i automatiziranim postupkom. Iako dajemo sve od sebe kako bismo otkrili i uklonili videozapise koji krše smjernice naših pravila, naš je postupak pregleda prvenstveno usmjeren na uklanjanje sadržaja za odrasle ili očitih kršenja autorskih prava i nije otporan na metke. Međutim, potičemo naše gledatelje da nas obavijeste kada otkriju kršenja pravila ili probleme s autorskim pravima -- imamo postupak za pregled prijavljenih kršenja pravila i reagiramo na prijavljena kršenja autorskih prava prema Zakonu o zaštiti autorskih prava u digitalnom tisućljeću.';
$LANGS['q11'] = 'P: Imate li Matrix Server ili Twitter?';
$LANGS['a11'] = 'Da! Zapravo imamo Matrix server i Twitter. Možete se pridružiti Matrix Server-u klikom <a href="https://matrix.to/#/#bittoco:matrix.org">ovdje</a> i pratiti nas na Twitteru <a href="https://twitter.com/bitview_ ">ovdje</a>.';
$LANGS['q12'] = "P: Koristim stari preglednik dok sam na BitViewu i stoga ne mogu gledati videozapise. Što mogu učiniti?";
$LANGS['activate'] = 'Aktiviraj';
$LANGS['deactivate'] = 'Deaktiviraj';
$LANGS['flashdisclaimer'] = "<b>Napomena:</b> BitView-ov Flash Player nudi se kao opcija kompatibilnosti. Ako vaš preglednik podržava BitViewov HTML5 player, ne biste trebali omogućiti ovu opciju.";

/* BitView on your site */
$LANGS['bvsitetitle1'] = "Osnove";
$LANGS['bvsitetitle2'] = "API-ji i angažman korisnika";
$LANGS['bvsitedesc1'] = 'Što god da ste prisutni na internetu—velika web stranica, blog, stranica na društvenoj mreži ili bilo što drugo—postoji mnogo načina za integraciju BitViewa u to. Od jednostavnih video ugradnji do naših API-ja pune snage, možete integrirati video na svim razinama tehničke stručnosti.';
$LANGS['bvsitedesc2'] = 'Dovođenje BitViewa na vaše web mjesto više je od pukog dodavanja nekih od tisuća videa dostupnih na BitViewu. Održava interes vaših posjetitelja i omogućuje samoizražavanje i interakciju s jednom od njihovih omiljenih usluga. I dovodi vašu web-lokaciju, blog ili stranicu u BitView video zajednicu — međunarodnu mrežu korisnika, kreatora i web-mjesta povezanih preko goleme zbirke online videa.';
$LANGS['bvsitedesc3'] = "Istaknuli smo neke tipične načine integriranja video sadržaja u nastavku — samo kliknite strelicu pokraj pitanja kako biste dobili odgovor. Ako imate bilo kakvih pitanja ili prijedloga, ili projekata koje želite da nas o kojima želite znati, ostavite pitanja u našem <a href='https://matrix.to/#/#bittoco:matrix.org'>Matrix Server-u</a>.";
$LANGS['bvsitesectiontitle1'] = "Kako mogu dodati video na svoj blog ili web stranicu?";
$LANGS['bvsitesectiontitle2'] = "Kako mogu dodati video na svoju stranicu na društvenoj mreži?";
$LANGS['bvsitesectiontitle3'] = "Radim za veliku blog/web tvrtku. Kako video može povećati angažman korisnika na našoj stranici?";
$LANGS['bvsitesectiontitle4'] = "Imamo stranicu i imamo vlastite videozapise. Možemo li ih objaviti na našoj stranici koristeći BitView?";
$LANGS['bvsitesection1desc1'] = "Morat ćete urediti HTML unosa ili stranice u blogu—ovo bi trebalo biti relativno jednostavno. U Bloggeru, na primjer, samo kliknite karticu &quot;Uredi HTML&quot;.";
$LANGS['bvsitesection1desc2'] = "Zatim, idite na videozapis koji želite i potražite okvir 'Ugradi' u odjeljku &quot;O ovom videu&quot;. Kopiranjem HTML koda koji se nalazi na vašoj web stranici stvorit ćete ugrađeni player; video će se reproducirati unutar vašeg web-mjesta kada korisnik klikne na gumb 'Reproduciraj'.";
$LANGS['bvsitesection1desc3'] = "Možete promijeniti veličinu playera uređivanjem polja <em>object width=&quot;425&quot;</em> i <em>height=&quot;350&quot;</em> na početku i kraj ugrađenog koda playera. Pazite da veličine koje odaberete imaju isti omjer kao zadani brojevi, tako da se video ne razvuče—samo pomnožite širinu s 0,8235 da biste dobili visinu.";
$LANGS['bvsitesection2desc1'] = "Dodavanje videozapisa u vaše profile na društvenim mrežama kao što je SpaceHey odličan je način za dijeljenje vaših videozapisa ili favorita s prijateljima. Ili, ako promovirate nešto (poput svog benda) na SpaceHeyu, videozapisi će pomozite privući posjetitelje na svoju stranicu, koji potom mogu dijeliti vezu sa svojim prijateljima, web stranice društvenih mreža imaju slične načine za dodavanje videozapisa, pa ćemo kao primjer koristiti SpaceHey.";
$LANGS['bvsitesection2desc2'] = 'Prijavite se na svoj SpaceHey profil, zatim kliknite gumb "Uredi profil".';
$LANGS['bvsitesection2desc3'] = "Zatim idite na željeni videozapis i potražite okvir 'Ugradi' u odjeljku &quot;O ovom videu&quot;. Kopiranjem HTML koda koji se nalazi na vašoj web stranici stvorit ćete ugrađeni igrač.";
$LANGS['bvsitesection2desc4'] = "Možete promijeniti veličinu playera uređivanjem polja object width=&quot;425&quot; i height=&quot;350&quot; na početku i na kraju koda ugrađenog playera. Provjerite jesu li veličine koje odaberite imati isti omjer kao zadani brojevi, tako da se video ne rasteže—samo pomnožite širinu s 0,8235 da biste dobili visinu.";
$LANGS['bvsitesection2desc5'] = 'Kliknite "Pregled", a zatim "Pošalji".';
$LANGS['bvsitesection3desc1'] = "Videozapis je mnogo zanimljiviji od teksta. Privlači više korisnika i zadržava ih dulje na vašoj stranici. BitView ima veliki repozitorij internetskog video sadržaja zajedno s alatima za pretraživanje, reprodukciju i API lakše vam je dodavanje videozapisa.";
$LANGS['bvsitesection3desc2'] = "Kada želite povećati angažman, pokušajte koristiti video kao način da započnete raspravu ili date komentar stvarajući više konteksta za svoje korisnike:";
$LANGS['bvsitesection4desc1'] = "Vrlo je jednostavno besplatno izgraditi vlastitu web stranicu s vlastitim video zapisima. Sve što trebate učiniti je prvo učitati videozapise u BitView. Nema naknade, a mi ćemo pokriti troškove hostinga i strujanja. To nije samo sjajan način za povećanje angažmana korisnika na vašoj web-lokaciji, već je i vrlo jednostavan, a također i besplatan.";
$LANGS['bvsitesection4desc2'] = "Jednom kada učitate video zapise, možete ih povući natrag na stranicu:";
$LANGS['bvsitesection4desc3'] = "<b>Ugradite videozapise jedan po jedan:</b> Idite na videozapis koji želite staviti na svoju web stranicu i potražite okvir 'Ugradi' pored video playera . Kopiranjem HTML koda koji se nalazi u vašem blogu stvorit će se ugrađeni player";

/* RSS Feeds */
$LANGS['rsstitle1'] = "Što su RSS Feed-ovi?";
$LANGS['rsstitle2'] = "Kako pristupiti RSS Feed-ovima";
$LANGS['rsstitle3'] = "Kako se pretplatiti na BitView RSS Feed-ove";
$LANGS['rssdesc1'] = "Really Simple Syndication (RSS) je format temeljen na XML-u koji se koristi za distribuciju i prijenos sadržaja. Pretplata na RSS izvore omogućuje vam primanje prilagođenih, ažurnih informacija iz vaših omiljenih izvora mrežnog sadržaja bez potrebe da redovito provjeravate ažuriranja na stranici.";
$LANGS['rssdesc2'] = "Čitači vijesti koji prikazuju RSS feedove s web stranica koje navedete—oni provjeravaju RSS feedove na koje ste se pretplatili i prikazuju nove stavke sa svakog feeda. Možete preuzeti aplikacije za čitanje vijesti za svoje računalo, a ovdje su dostupni i mnogi popularni čitači vijesti bazirani na webu, kao što su Google Reader i Bloglines. Neki web preglednici i aplikacije za e-poštu također imaju ugrađene RSS mogućnosti.";
$LANGS['rssdesc3'] = "Možete vidjeti popis mnogih dostupnih čitača vijesti na <a href='http://en.wikipedia.org/wiki/List_of_feed_aggregators'>Wikipedia</a>."; //Ako je moguće, upotrijebite članak Wikipedije na svom jeziku
$LANGS['rssdesc4'] = "BitView nudi nekoliko RSS feedova za kategorizirane grupe videozapisa (kao što su nedavno učitani, najgledaniji itd.), kao i prilagođene feedove za korisnike i oznake.";
$LANGS['rssdesc5'] = "Da biste se pretplatili na kategorizirane grupe videozapisa, jednostavno idite na kategoriju koju želite (na primjer, &quot;<a href='/browse'>Najgledanije - danas</a>&quot;) . Zatim kliknite na narančasti gumb 'RSS'. Ovo bi trebalo pokrenuti vaš odabrani čitač vijesti za dodavanje pretplate.";
$LANGS['rssdesc6'] = "Ako vaš preglednik ima RSS mogućnosti, tada možete tamo dodati feed. Naredba se razlikuje od preglednika do preglednika, ali se obično može pronaći u izbornicima 'Datoteka' ili 'Oznake', a bit će pozvana nešto poput &quot;Pretplatite se na ovu stranicu&quot;Nova oznaka uživo&quot;.";
$LANGS['rssthispage'] = "RSS ​​stranica";

/* TestView */
$LANGS['testviewdesc'] = "Dobrodošli u TestView, naš inkubator ideja. Ovo je mjesto gdje BitView inženjeri i programeri testiraju recepte i izmišljotine koji nisu baš do kraja pečeni i pozivaju vas da nam kažete kako napreduju." ;
$LANGS['flashvideo'] = "Flash video";
$LANGS['flashvideodesc'] = "Vaš preglednik ne podržava HTML5 video? Ne brinite! Isprobajte naš Flash player.";
$LANGS['feather'] = "Feather";
$LANGS['featherdesc'] = "Pogledajte BitView video zapise na stranici sa super niskom latencijom.";
$LANGS['tryitout'] = "Isprobajte";
$LANGS['disabletest'] = "Onemogući";
$LANGS['timemachine'] = "Vremenski stroj";
$LANGS['timemachinedesc'] = "Vratite se u prošlost, premotavajući svaki datum na BitViewu do kasnih 2000-ih.";
$LANGS['lightsout'] = "Gašenje svjetla";
$LANGS['lightsoutdesc'] = "Umorni ste od najsvjetlije bijele boje na svom ekranu? Obojite ga u crno i isprobajte novo cool sučelje.";
$LANGS['featherenabled'] = '"Feather" je sada omogućen!';
$LANGS['timemachineenabled'] = '"Vremenski stroj" je sada omogućen!';
$LANGS['lightsoutenabled'] = '"Gašenje svjetla" je sada omogućeno!';
$LANGS['featherdisabled'] = '"Feather" je sada onemogućen!';
$LANGS['timemachinedisabled'] = '"Vremenski stroj" sada je onemogućen!';
$LANGS['lightsoutdisabled'] = '"Gašenje svjetla" je sada onemogućeno!';

/* Email Confirmation */
$LANGS['checkemail'] = "Molimo pregledajte vašu e-poštu";
$LANGS['checkemaildesc'] = "E-pošta s potvrdom poslana je na vašu adresu e-pošte. Kliknite na poveznicu u e-poruci kako biste potvrdili svoju adresu e-pošte. Ako ne primite poruku u roku od nekoliko minuta, također provjerite svoje mape za masovnu ili neželjenu poštu.";
$LANGS['resendemail'] = "Ponovno pošalji e-poštu za potvrdu";

/* Footer */
$LANGS['youraccount'] = 'Vaš račun';
$LANGS['inbox'] = 'Pošta';
$LANGS['footmore'] = 'više...';
$LANGS['helpinfo'] = 'Pomoć';
$LANGS['helpcenter'] = 'Centar za Pomoć';
$LANGS['ourtwitter'] = 'Twitter';
$LANGS['ourmatrix'] = 'Matrix';
$LANGS['guidelines'] = 'Pravila';
$LANGS['partnerships'] = 'Partneri';
$LANGS['terms'] = 'Uvjeti';
$LANGS['about'] = 'O';
$LANGS['privacypolicy'] = 'Privatnost';
$LANGS['languageselector'] = 'Jezik';
$LANGS['currentlanguage'] = 'Trenutni jezik';
$LANGS['showlanguages'] = 'Prikaži jezike';
$LANGS['setlanguagepref'] = 'Odaberite svoj jezik';
$LANGS['programs'] = 'Programi';
$LANGS['developers'] = 'Programeri';
$LANGS['bitviewblog'] = 'BitView Blog';
$LANGS['policy'] = 'Politika';
$LANGS['discover'] = 'Istraži';
$LANGS['bvphone'] = 'BitView na vašem Mobitelu';
$LANGS['bvsite'] = 'BitView na vašoj Stranici';
$LANGS['bvrss'] = 'BitView RSS Feeds';
$LANGS['mobile'] = 'Mobilni pregled';
?>
