<?php

/* General stuff */
$LANGS['language'] = 'Italiano';
$LANGS['languageenglish'] = 'Italian';
$LANGS['languagecode'] = 'it_IT.UTF-8'; /* Leave the ".UTF-8" in the end as-is, as it might break some dates */
$LANGS['languagechange'] = 'La lingua è stata impostata a Italiano.';
$LANGS['numberformat'] = 1; /* If your language uses comma separators (example: 1,000,000), value will be 1. If it uses dots (example: 1.000.000) or doesn't use separators, value will be 0.*/

/* Language window */
$LANGS['welcometobitview'] = 'Benvenuto su BitView!';
$LANGS['languagesuggestion'] = 'Lingua suggerita (abbiamo impostato le tue preferenze a questo):';
$LANGS['languagesuggestiondesc1'] = 'Per cambiare la lingua del sito, usa il selettore lingue nel footer (fine della pagina).';
$LANGS['languagesuggestiondesc2'] = 'Clicca "OK" per accettare questa impostazione, o clicca "Annulla" per cambiare la lingua del sito a Inglese.';

/* Time, dates, etc */
$LANGS['second'] = 'secondo';
$LANGS['minute'] = 'minuto';
$LANGS['hour'] = 'ora';
$LANGS['day'] = 'giorno';
$LANGS['week'] = 'settimana';
$LANGS['month'] = 'mese';
$LANGS['year'] = 'anno';
$LANGS['seconds'] = 'secondi';
$LANGS['minutes'] = 'minuti';
$LANGS['hours'] = 'ore';
$LANGS['days'] = 'giorni';
$LANGS['weeks'] = 'settimane';
$LANGS['months'] = 'mesi';
$LANGS['years'] = 'anni';
$LANGS['ago1'] = ''; /* Explanation: Text before "x seconds/minutes/hours..." Example: "hace (1 día)" in Spanish. If your language doesn't use this, leave it empty like this: ''*/
$LANGS['ago2'] = ' fa'; /* Explanation: ago2 -> Text after "x seconds/minutes/hours..." Example: "(1 day) ago" in English, "(1 anno) fa" in Italian. If your language doesn't use this, leave it empty like this: ''*/
$LANGS['january'] = 'Gennaio';
$LANGS['february'] = 'Febbraio';
$LANGS['march'] = 'Marzo';
$LANGS['april'] = 'Aprile';
$LANGS['may'] = 'Maggio';
$LANGS['june'] = 'Giugno';
$LANGS['july'] = 'Luglio';
$LANGS['august'] = 'Agosto';
$LANGS['september'] = 'Settembre';
$LANGS['october'] = 'Ottobre';
$LANGS['november'] = 'Novembre';
$LANGS['december'] = 'Dicembre';
$LANGS['shorttimeformat'] = '%b %e, %Y';
$LANGS['videotimeformat'] = '%b %e, %Y';
$LANGS['longtimeformat'] = '%B %e, %Y';
$LANGS['timehourformat'] = '%b %e, %Y %H:%M';
$LANGS['myvideostimeformat'] = '%A, %b %e %Y, %H:%M:%S';
$LANGS['blogpostformat'] = '%A, %B %e, %Y';
$LANGS['timenumberformat'] = 'd.m.Y';

/* Header */
$LANGS['home'] = 'Home';
$LANGS['videos'] = 'Video';
$LANGS['channels'] = 'Canali';
$LANGS['community'] = 'Comunità';
$LANGS['search'] = 'Cerca';
$LANGS['login'] = 'Accedi';
$LANGS['or'] = 'o';
$LANGS['signup'] = 'Crea account';
$LANGS['logout'] = 'Esci';
$LANGS['upload'] = 'Carica';
$LANGS['subscriptions'] = 'Iscrizioni';
$LANGS['history'] = 'Cronologia';
$LANGS['account'] = 'Account';
$LANGS['myvideos'] = 'I miei video';
$LANGS['favorites'] = 'Preferiti';
$LANGS['playlists'] = 'Playlist';
$LANGS['help'] = 'Aiuto';
$LANGS['suggestions'] = 'Suggerimenti';

/* Homepage */
$LANGS['viewall'] = 'guarda tutto';
$LANGS['videoviews'] = 'visualizzazioni';
$LANGS['beingwatched'] = 'Video guardati ora';
$LANGS['featured'] = 'In primo piano';
$LANGS['recommendedforyou'] = 'Consigliati per te';
$LANGS['mostpopular'] = 'I più popolari';
$LANGS['inboxstats'] = 'Messaggi e Statistiche';
$LANGS['profilesettings'] = 'Impostazioni account';
$LANGS['messages'] = 'Messaggi';
$LANGS['message'] = 'Messaggio';
$LANGS['comments'] = 'Commenti';
$LANGS['comment'] = 'Commento';
$LANGS['friendinvites'] = 'Richieste di amicizia';
$LANGS['friendinvite'] = 'Richiesta di amicizia';
$LANGS['subscribers'] = 'Iscritti';
$LANGS['subscriber'] = 'Iscritto';
$LANGS['totalviews'] = 'Visualizzazioni totali';
$LANGS['sendmessage'] = 'Invia messaggio';
$LANGS['whatsnew'] = 'Cosa c\'è di nuovo';
$LANGS['readmore'] = 'Leggi di più sul nostro Blog';
$LANGS['videocontest'] = 'Videoconcorso';
$LANGS['joincontest'] = 'Unisciti al concorso ora!';
$LANGS['personalize'] = 'Vuoi personalizzare questa pagina home?';
$LANGS['signinnow'] = '<a href="/login">Accedi</a> o <a href="/signup">Crea un account</a> ora!';
$LANGS['nowconverting'] = 'Questo video sta convertendo, attendi qualche minuto.';
$LANGS['modules'] = 'Aggiungi/Rimuovi Moduli';
$LANGS['friendactivity'] = 'Attività degli amici';
$LANGS['customizehomepage'] = 'Personalizza la Homepage';
$LANGS['customizethehomepage'] = 'Personalizza la Homepage';
$LANGS['customizehomepagedesc'] = 'Seleziona i moduli che desideri visualizzare sulla tua homepage personalizzata.';
$LANGS['displaypreferences'] = 'Preferenze di visualizzazione';
$LANGS['thefeed'] = 'Il Feed';
$LANGS['thefeeddesc'] = 'Combina tutti i tuoi moduli in un unico feed.';
$LANGS['friendactivitytitle'] = 'Attività degli Amici - Possono vedere ciò che faccio?';
$LANGS['friendactivitydesc'] = 'Questa sezione mostra ai tuoi amici confermati le azioni che stai trasmettendo pubblicamente nella tua cronologia delle attività recenti. Ad esempio, se metti un video tra i preferiti, il tuo nuovo video preferito potrebbe apparire nella casella Attività Recenti del tuo canale, nonché sulla homepage dei tuoi amici.';
$LANGS['feedfeatured'] = 'Video in Primo Piano';
$LANGS['feedbeingwatched'] = 'Video in Visualizzazione Ora';
$LANGS['feedrecommended'] = 'Video Consigliati';
$LANGS['nosubscriptions'] = 'Non hai ancora sottoscritto nessun canale.';
$LANGS['nosubscriptionsdesc'] = 'Quando aggiungi nuove iscrizioni, mostreremo qui i loro caricamenti su questa pagina.';
$LANGS['nofriendactivity'] = 'I tuoi amici non sono stati attivi di recente.';
$LANGS['nofriendactivitydesc'] = 'Puoi provare ad aggiungere alcuni amici. In seguito, mostreremo la loro attività su questa pagina.';
$LANGS['homeediting'] = 'Modifica';
$LANGS['homedisplay'] = 'Visualizza come';
$LANGS['homerows'] = 'Numero di righe da visualizzare';
$LANGS['gridview'] = 'Vista a griglia';
$LANGS['listview'] = 'Vista a elenco';


/* Page title */
$LANGS['homepretitle'] = "BitView di "; /* Spiegazione: Usare se "BitView" precede il nome utente. Esempio: "BitView di username" in italiano. Se la tua lingua non lo usa, lascialo vuoto come questo: '' */
$LANGS['homeposttitle'] = ""; /* Spiegazione: Usare se "BitView" segue il nome utente. Esempio: "BitView di username" in inglese. Se la tua lingua non lo usa, lascialo vuoto come questo: '' */
$LANGS['chpretitle'] = "Canale di "; /* Spiegazione: Usare se "canale" precede il nome utente. Esempio: "Canale di username" in italiano. Se la tua lingua non lo usa, lascialo vuoto come questo: '' */
$LANGS['chposttitle'] = ""; /* Spiegazione: Usare se "canale" segue il nome utente. Esempio: "Canale di username" in inglese. Se la tua lingua non lo usa, lascialo vuoto come questo: '' */
$LANGS['signintitle'] = "Accedi";
$LANGS['historytitle'] = "Cronologia video";
$LANGS['favtitle'] = "Preferiti";
$LANGS['pltitle'] = "Playlist";
$LANGS['partnerprogram'] = "Programma Partner";

/* Notifications */
$LANGS['searcherror'] = 'Il testo di ricerca deve contenere almeno 2 caratteri!';
$LANGS['addvideoplaylist1'] = 'Hai aggiunto';
$LANGS['addvideoplaylist2'] = 'video nella tua playlist!';
$LANGS['addfavorite1'] = 'Hai aggiunto nei preferiti';
$LANGS['addfavorite2'] = 'video!';
$LANGS['groupdoesnotexist'] = 'Questo gruppo non esiste!';
$LANGS['uploaddisabled'] = "L'aggiunta di video è stata disattivata per manutenzione.";
$LANGS['10vidsday'] = 'Non puoi caricare più di 10 video al giorno! Riprova domani.';
$LANGS['3mins'] = 'Attendi 3 minuti prima di caricare un nuovo video!';
$LANGS['backgroundsuccess'] = 'Lo sfondo è stato aggiunto con successo!';
$LANGS['backgrounderror'] = 'Lo sfondo deve essere inferiore a 2 MB e deve essere un file immagine!';
$LANGS['backgrounddeleted'] = 'Lo sfondo è stato eliminato con successo!';
$LANGS['bannersuccess'] = 'Il banner è stato aggiunto con successo!';
$LANGS['bannererror'] = 'Il banner deve essere inferiore a 2 MB e deve essere un file immagine!';
$LANGS['bannerdeleted'] = 'Il tuo banner è stato eliminato con successo!';
$LANGS['minibannersuccess'] = 'Il mini banner è stato aggiunto con successo!';
$LANGS['minibannererror'] = 'Il mini banner deve essere inferiore a 2 MB e deve essere un file immagine!';
$LANGS['minibannerdeleted'] = 'Il tuo mini banner è stato eliminato con successo!';
$LANGS['sideimagesuccess'] = "L'immagine laterale è stata aggiunta con successo!";
$LANGS['sideimageerror'] = "L'immagine laterale deve essere inferiore a 2 MB e deve essere un file immagine!";
$LANGS['sideimagedeleted'] = "L'immagine laterale è stata eliminata con successo!";
$LANGS['avatarsuccess'] = "L'avatar è stato aggiunto con successo!";
$LANGS['avatarerror'] = "L'avatar deve essere inferiore a 2 MB e deve essere un file immagine!";
$LANGS['avatardeleted'] = "L'avatar è stato eliminato con successo!";
$LANGS['changessaved'] = 'Le preferenze sono state salvate con successo!';
$LANGS['profilesdisabled'] = 'I profili sono stati disattivati per manutenzione.';
$LANGS['bulletinposted'] = 'Il bollettino è stato pubblicato!';
$LANGS['channelcommentsent'] = 'Il commento è stato pubblicato!';
$LANGS['somethingwentwrong'] = 'Qualcosa è andato storto!';
$LANGS['replysubmitted'] = 'La risposta è stata pubblicata!';
$LANGS['onlyonecomment'] = 'Puoi lasciare solo un commento!';
$LANGS['vpnbrowser'] = "Non puoi utilizzare una VPN per creare un account BitView!";
$LANGS['torbrowser'] = "Non puoi utilizzare il browser TOR per creare un account BitView!";
$LANGS['captchaincorrect'] = 'Il captcha è errato.';
$LANGS['toomanyaccounts'] = 'Hai troppi account!';
$LANGS['banned2times'] = 'Sei stato bannato 2 volte. Non puoi creare ulteriori account!';
$LANGS['nohistory'] = 'Non hai ancora guardato nessun video in questa sessione!';
$LANGS['historycleared'] = 'La cronologia è stata cancellata.';
$LANGS['watchdisabled'] = 'La visione dei video è stata disattivata per manutenzione.';
$LANGS['videonotexist'] = 'Questo video non esiste o è stato rimosso a causa di una violazione dei Termini di Utilizzo.';
$LANGS['responseerror'] = 'Qualcosa è andato storto con la tua risposta video! Controlla l\'URL.';
$LANGS['responseexist'] = 'Il video è già stato richiesto!';
$LANGS['responseadded'] = 'Risposta video aggiunta con successo!';
$LANGS['responseaccepted'] = 'Nuova risposta video accettata!';
$LANGS['60secscomment'] = 'Attendi 1 minuto prima di aggiungere un altro commento!';
$LANGS['plnotexist'] = 'Questa playlist non esiste!';
$LANGS['positionnotexist'] = 'Questa posizione non esiste!';
$LANGS['positionchanged'] = 'La posizione del video è stata cambiata!';
$LANGS['invalidurl'] = 'URL non valido!';
$LANGS['videopladded'] = 'Video aggiunto con successo!';
$LANGS['videoalreadyinpl'] = 'Questo video è già nella playlist!';
$LANGS['plvideoremoved'] = 'Il video è stato rimosso dalla playlist!';
$LANGS['plinfochanged'] = 'Le informazioni sulla playlist sono state cambiate con successo!';
$LANGS['pltitleneeded'] = 'Devi inserire un titolo per la playlist!';
$LANGS['flashenabled'] = 'Adobe Flash Player abilitato!';
$LANGS['flashdisabled'] = 'Adobe Flash Player disabilitato!';
$LANGS['messagesent'] = 'Il messaggio è stato inviato con successo!';
$LANGS['usernotexist'] = 'Questo utente non esiste!';
$LANGS['nocriteria'] = 'Non soddisfi i criteri richiesti!';
$LANGS['alreadypartner'] = 'Sei già stato accettato nel Programma Partner!';
$LANGS['alreadyapplied'] = 'Hai già fatto richiesta!';
$LANGS['applicationsent'] = 'La tua richiesta è stata inviata!';
$LANGS['joinedgroup'] = 'Sei entrato nel gruppo con successo!';
$LANGS['leftgroup'] = 'Sei uscito dal gruppo con successo!';
$LANGS['grouprequest'] = 'Hai inviato con successo una richiesta di gruppo! Ora devi attendere che venga accettata.';
$LANGS['groupdeleted'] = 'Il gruppo è stato eliminato con successo!';
$LANGS['groupvideoadded'] = 'Il video è stato aggiunto al gruppo!';
$LANGS['groupvideoalreadyadded'] = 'Hai già aggiunto questo video!';
$LANGS['groupvideonotowned'] = 'Non possiedi questo video!';
$LANGS['3groups'] = 'Puoi possedere solo fino a 3 gruppi!';
$LANGS['groupnameempty'] = 'Il nome del gruppo non può essere vuoto!';
$LANGS['groupdescempty'] = 'La descrizione del gruppo non può essere vuota!';
$LANGS['groupnoimage'] = 'Devi aggiungere un\'immagine per il tuo gruppo!';
$LANGS['groupimageerror'] = "L'immagine del gruppo deve essere inferiore a 1 MB e deve essere un file immagine!";
$LANGS['groupcreated'] = 'Il gruppo è stato creato con successo!';
$LANGS['urlnotvalid'] = 'URL non valido!';
$LANGS['discussiondeleted'] = 'Discussione eliminata con successo!';
$LANGS['videodeleted'] = 'Il video è stato eliminato con successo!';
$LANGS['pldeleted'] = 'La playlist è stata eliminata con successo!';
$LANGS['invitesent'] = 'La richiesta di amicizia è stata inviata con successo!';
$LANGS['descriptionchanged'] = 'La descrizione è stata cambiata!';
$LANGS['emptymessage'] = 'Non puoi inviare messaggi vuoti!';
$LANGS['styleupdated'] = 'Lo stile del gruppo è stato aggiornato con successo!';
$LANGS['imageupdated'] = "L'immagine del gruppo è stata aggiornata con successo!";
$LANGS['plcreated'] = 'La playlist è stata creata con successo!';
$LANGS['discussiontitle2chars'] = 'Il titolo deve contenere almeno 2 caratteri!';
$LANGS['discussiondesc10chars'] = 'La descrizione deve contenere almeno 10 caratteri!';
$LANGS['5discussionsday'] = 'Puoi creare al massimo 5 discussioni al giorno!';
$LANGS['discussionsuccess'] = 'Discussione creata con successo!';
$LANGS['memberaccepted1'] = '';
$LANGS['memberaccepted2'] = 'è stato accettato con successo!';
$LANGS['memberdeclined1'] = '';
$LANGS['memberdeclined2'] = 'è stato rifiutato con successo!';
$LANGS['videoaccepted'] = 'Il video è stato accettato con successo!';
$LANGS['bulletindeleted'] = 'Il bollettino è stato eliminato con successo!';
$LANGS['messagedeleted'] = 'Il messaggio è stato eliminato con successo!';
$LANGS['responsedeleted'] = 'La risposta video è stata eliminata con successo!';
$LANGS['flagmod'] = 'Non puoi segnalare utenti che hanno i permessi di moderatore!';
$LANGS['userflagged'] = 'La segnalazione è stata inviata!';
$LANGS['discussionreplysubmitted'] = 'La risposta è stata inviata con successo!';
$LANGS['discussionreplyempty'] = 'Una risposta non può essere vuota!';

/* Watch */
$LANGS['moreinfo'] = 'più informazioni';
$LANGS['lessinfo'] = 'meno informazioni';
$LANGS['category'] = 'Categoria';
$LANGS['recordedon'] = 'Registrato il';
$LANGS['location'] = 'Posizione';
$LANGS['tags'] = 'Tag';
$LANGS['embed'] = 'Incorpora';
$LANGS['partnervideo'] = 'Video Partner';
$LANGS['subscribe'] = 'Iscriviti';
$LANGS['unsubscribe'] = 'Disiscriviti';
$LANGS['nodesc'] = 'Nessuna descrizione...';
$LANGS['logintosub'] = 'Accedi per iscriverti!';
$LANGS['logintosubbox'] = 'Vuoi iscriverti?';
$LANGS['subyourself'] = 'Non puoi iscriverti al tuo profilo!';
$LANGS['videoowner'] = 'Opzioni del proprietario del video';
$LANGS['editvideo'] = 'Modifica video';
$LANGS['insight'] = 'Statistiche visualizzazioni';
$LANGS['morefrom'] = 'Di più da:';
$LANGS['relatedvideos'] = 'Video correlati';
$LANGS['novideosfound'] = 'Nessun video trovato...';
$LANGS['morevideos'] = 'Guarda tutti i video';
$LANGS['changeplayersize'] = 'Cambia le dimensioni del player';
$LANGS['newwindow'] = 'Guarda questo video in una nuova finestra';
$LANGS['featuredtext'] = 'Questo video è stato messo in primo piano. Vuoi vedere altri video in primo piano? <a href="/browse?t=2">Clicca qui</a>.';
$LANGS['ratings'] = 'recensioni';
$LANGS['rating'] = 'recensione';
$LANGS['favorite'] = 'Preferito';
$LANGS['addtofav'] = 'Aggiungi ai Preferiti';
$LANGS['removefav'] = 'Rimuovi dai Preferiti';
$LANGS['favadded'] = 'Questo video è stato <strong>aggiunto</strong> ai tuoi <a href="/my_favorites">Preferiti</a>.';
$LANGS['favremoved'] = 'Questo video è stato <strong>rimosso</strong> dai tuoi <a href="/my_favorites">Preferiti</a>.';
$LANGS['undo'] = 'Annulla';
$LANGS['thanksforrating'] = 'Grazie per la recensione!';
$LANGS['playlistdesc'] = 'Per aggiungere un video alla tua playlist, vai alla pagina <a href="/my_playlists">"Playlist"</a>.';
$LANGS['addtoplaylist'] = 'Aggiungi a una Playlist';
$LANGS['addtoplaylistsuccess'] = 'Il video è stato aggiunto alla tua Playlist.';
$LANGS['share'] = 'Condividi';
$LANGS['flag'] = 'Segnala';
$LANGS['flagthisvid'] = 'Segnala questo Video';
$LANGS['removeflag'] = 'Rimuovi Segnalazione';
$LANGS['flagnote'] = "Prima di segnalare: assicurati che il video infranga qualsiasi regola. Non segnalare solo perché non ti piace quel video, altrimenti ostacolerai il lavoro dei moderatori.";
$LANGS['statadded'] = 'Aggiunto';
$LANGS['statviews'] = 'Visualizzazioni';
$LANGS['statratings'] = 'Recensione';
$LANGS['statresponses'] = 'Risposte';
$LANGS['statcomments'] = 'Commenti';
$LANGS['statfavorited'] = 'Preferito';
$LANGS['statsdata'] = 'Statistiche & Data';
$LANGS['honors'] = 'Onori per questo video';
$LANGS['mostviewed'] = 'Più visualizzati';
$LANGS['topfavorited'] = 'I top tra i Preferiti';
$LANGS['times'] = 'volte';
$LANGS['mostdiscussed'] = 'I più discussi';
$LANGS['toprated'] = 'I più votati';
$LANGS['videolinks'] = 'Siti che rimandano a questo video';
$LANGS['clicksfrom'] = 'click da';
$LANGS['responses'] = 'Risposte video';
$LANGS['responsespost'] = 'Pubblica una risposta video';
$LANGS['textcomments'] = 'Commenti testuali';
$LANGS['commentpost'] = 'Pubblica un commento testuale';
$LANGS['commentonthisvideo'] = 'Commenta questo video';
$LANGS['postcomment'] = 'Pubblica commento';
$LANGS['remainingcounter'] = 'Numero di caratteri rimanenti';
$LANGS['nocomments'] = 'Questo video non ha <b>nessun commento</b>.';
$LANGS['noresponses'] = 'Questo video non ha <b>nessuna risposta</b>.';
$LANGS['commviewall'] = 'Guarda tutti i';
$LANGS['delete'] = 'Elimina';
$LANGS['reply'] = 'Rispondi';
$LANGS['commentlogin'] = 'Vuoi commentare?';
$LANGS['commentlogindesc'] = '<a href="/signup">Unisciti a BitView</a> per un account gratuito o <a href="/login">accedi</a> se sei già un membro.';
$LANGS['logintoresponse'] = 'Accedi per pubblicare una risposta video';
$LANGS['logintocomment'] = 'Accedi per pubblicare un Commento';
$LANGS['logintofav'] = 'Vuoi aggiungere ai Preferiti? <a href="/login">Accedi</a> o <a href="/signup">Crea un account</a> ora!';
$LANGS['logintopl'] = 'Vuoi aggiungere a una Playlist? <a href="/login">Accedi</a> o <a href="/signup">Crea un account</a> ora!';
$LANGS['logintoflag'] = 'Vuoi segnalare un video? <a href="/login">Accedi</a> o <a href="/signup">Crea un account</a> ora!';
$LANGS['close'] = 'chiudi';
$LANGS['addresponse'] = 'Aggiungi risposta';
$LANGS['recentlyrated'] = 'Valutato di recente';
$LANGS['commentsdisabled'] = 'La possibilità di aggiungere commenti a questo video è stata disabilitata.';
$LANGS['ratingsdisabled'] = 'Valutazioni disabilitate';
$LANGS['rating1'] = 'Scarso';
$LANGS['rating2'] = 'Niente di speciale';
$LANGS['rating3'] = 'Degno di essere visto';
$LANGS['rating4'] = 'Abbastanza bello';
$LANGS['rating5'] = 'Fantastico!';
$LANGS['saving'] = 'Salvataggio...';
$LANGS['signintorate'] = '<a href="/login">Accedi</a> per valutare';
$LANGS['addingcomment'] = 'Aggiunta del commento...';
$LANGS['commentposted'] = 'Commento pubblicato!';
$LANGS['commentspammsg'] = 'Pubblicare lo stesso commento nuovamente è considerato spam. Riprova più tardi.';
$LANGS['commentspammsg2'] = 'Pubblicare più di 5 commenti consecutivamente è considerato spam. Riprova più tardi.';
$LANGS['emptycomment'] = 'Il tuo commento non può essere vuoto.';
$LANGS['spambutton'] = 'Spam';
$LANGS['notspambutton'] = 'Non è spam';
$LANGS['commentsspam'] = 'Commenti marcati come spam';
$LANGS['marked'] = 'Marcato come spam';
$LANGS['spamshow'] = 'Mostra';
$LANGS['spamhide'] = 'Nascondi';
$LANGS['poorcomment'] = 'Commento scarso';
$LANGS['goodcomment'] = 'Commento buono';
$LANGS['pleasesignin'] = 'Effettua l\'accesso, per favore';
$LANGS['showmorecomments'] = 'Mostra Altri Commenti';
$LANGS['showingamount'] = '<strong>Mostrando {number}</strong> di {total} commenti';

/* Watch comments */
$LANGS['allcomments'] = 'Tutti i Commenti';

/* Sign In */
$LANGS['username'] = "Nome utente";
$LANGS['password'] = "Password";
$LANGS['logindesc'] = "Accedi a BitView con il tuo account";
$LANGS['forgot'] = "Hai dimenticato la password del tuo account?";
$LANGS['forgotmsg'] = 'Contattaci su Twitter (@BitView_) o invia un messaggio ai moderatori su Discord. (trovi il link nel footer)';
$LANGS['noaccount'] = "Non hai ancora un account?";
$LANGS['signuptobv'] = "Crea un account su BitView!";
$LANGS['signintobv'] = "Accedi su BitView!";
$LANGS['signindesc1'] = "Unisciti alla più grande comunità mondiale di condivisione video!";
$LANGS['signindesc2'] = "BitView è un modo per condividere i tuoi video con le persone che contano per te. Con BitView puoi:";
$LANGS['signindesc3'] = "Mostrare i tuoi video preferiti al mondo";
$LANGS['signindesc4'] = "Condividere i video realizzati con la tua fotocamera digitale o il tuo cellulare";
$LANGS['signindesc5'] = "Mostrare i video in modo sicuro e privato ai tuoi amici e familiari in tutto il mondo";
$LANGS['notallowed'] = "Sei stato bannato 3 volte. Non sei più autorizzato ad utilizzare BitView!";
$LANGS['wrongpassword'] = 'Password errata! Per favore, riprova.';
$LANGS['staysigned'] = "Rimani connesso";

/* Sign Up */
$LANGS['email'] = "Indirizzo e-mail";
$LANGS['passwordstrength'] = "Sicurezza della password";
$LANGS['psnone'] = "Nessuna";
$LANGS['psweak'] = "Debole";
$LANGS['psfair'] = "Equa";
$LANGS['psgood'] = "Buona";
$LANGS['psstrong'] = "Forte";
$LANGS['repassword'] = "Riscrivi password";
$LANGS['usernamedesc'] = "Il tuo nome utente può contenere solo lettere dalla A alla Z o numeri da 0 a 9.";
$LANGS['captcha'] = "Captcha";
$LANGS['acceptterms'] = "Sono d'accordo con i <a href='/terms'>Termini di Utilizzo</a> e l'<a href='/privacy'>Informativa sulla privacy</a>.";
$LANGS['copyrighttext'] = 'Il caricamento di materiali che non si possiedono è una violazione del copyright e contro la legge. Se carichi materiale che non possiedi, il tuo account verrà eliminato.';
$LANGS['mustaccept'] = "Devi accettare i Termini di utilizzo e l'Informativa sulla privacy per creare il tuo account";
$LANGS['createaccount'] = 'Crea il mio account';
$LANGS['signuperror'] = 'Si è verificato un errore durante la creazione del tuo account.';
$LANGS['sameemail'] = 'Questo nome utente o e-mail è già in uso!';
$LANGS['usernamechar'] = 'I nomi utente possono contenere solo caratteri e numeri!';
$LANGS['required'] = 'Tutti i campi di testo sono obbligatori!';
$LANGS['notmatch'] = "Le password non corrispondono!";
$LANGS['signuphead'] = 'Inizia con il tuo account';

/* Videos Page */
$LANGS['recentvideos'] = 'Video recenti';
$LANGS['random'] = 'Casuale';
$LANGS['dropdownmore'] = 'di più';
$LANGS['allcatin'] = 'in';
$LANGS['allcat'] = 'Tutte le categorie';
$LANGS['categories'] = 'Categorie';
$LANGS['nomorevideos'] = 'Non sono stati trovati altri video...';
$LANGS['timetoday'] = 'Oggi';
$LANGS['timeweek'] = 'Questa settimana';
$LANGS['timemonth'] = 'Questo mese';
$LANGS['alltime'] = 'Tutto il tempo';
$LANGS['when'] = 'Quando';
$LANGS['videofavorites'] = 'preferiti';
$LANGS['videocomments'] = 'commenti';
$LANGS['trendingtopics'] = 'Argomenti di tendenza';

/* Channels Page */
$LANGS['mostsubscribed'] = 'Con più iscritti';
$LANGS['lastlogin'] = 'Ultimo accesso';
$LANGS['cstatviews'] = 'Visualizzazioni';
$LANGS['cstatvideos'] = 'Video';
$LANGS['cstatsubs'] = 'Iscritti';
$LANGS['nochannels'] = 'Non sono stati trovati altri canali...';

/* Video Categories */
$LANGS['cat1'] = "Film & Animazione";
$LANGS['cat2'] = "Auto & Veicoli";
$LANGS['cat3'] = "Educazione & Istruzione";
$LANGS['cat4'] = "Intrattenimento";
$LANGS['cat5'] = "Eventi & Matrimoni";
$LANGS['cat6'] = "Famiglia";
$LANGS['cat7'] = "Prezzi & Aste";
$LANGS['cat8'] = "Hobby & Interessi";
$LANGS['cat9'] = "Umore";
$LANGS['cat10'] = "Musica";
$LANGS['cat11'] = "Notizie & Politiche";
$LANGS['cat12'] = "Strano & Oltraggioso";
$LANGS['cat13'] = "Persone & Blog";
$LANGS['cat14'] = "Personali & Incontri";
$LANGS['cat15'] = "Animali Domestici & Animali";
$LANGS['cat16'] = "Scienza & Tecnologia";
$LANGS['cat17'] = "Cortometraggi";
$LANGS['cat18'] = "Sport";
$LANGS['cat19'] = "Viaggi & Eventi";
$LANGS['cat20'] = "Videogiochi";
$LANGS['cat21'] = "Videoblog";

/* Channel Types */
$LANGS['type0'] = "Nessuno";
$LANGS['type1'] = "Membro";
$LANGS['type1p'] = "Membri";
$LANGS['type2'] = "Commediante";
$LANGS['type2p'] = "Commedianti";
$LANGS['type3'] = "Direttore";
$LANGS['type3p'] = "Direttori";
$LANGS['type4'] = "Guru";
$LANGS['type4p'] = "Guru";
$LANGS['type5'] = "Musicista";
$LANGS['type5p'] = "Musicisti";
$LANGS['type6'] = "Segnalatore";
$LANGS['type6p'] = "Segnalatori";

/* Countries */
$LANGS['cat_AF'] = "Afghanistan";
$LANGS['cat_AX'] = "Isole Åland";
$LANGS['cat_AL'] = "Albania";
$LANGS['cat_DZ'] = "Algeria";
$LANGS['cat_AS'] = "Samoa Americane";
$LANGS['cat_AD'] = "Andorra";
$LANGS['cat_AO'] = "Angola";
$LANGS['cat_AI'] = "Anguilla";
$LANGS['cat_AQ'] = "Antartide";
$LANGS['cat_AG'] = "Antigua e Barbuda";
$LANGS['cat_AR'] = "Argentina";
$LANGS['cat_AM'] = "Armenia";
$LANGS['cat_AW'] = "Aruba";
$LANGS['cat_AU'] = "Australia";
$LANGS['cat_AT'] = "Austria";
$LANGS['cat_AZ'] = "Azerbaigian";
$LANGS['cat_BS'] = "Bahamas";
$LANGS['cat_BH'] = "Bahrein";
$LANGS['cat_BD'] = "Bangladesh";
$LANGS['cat_BB'] = "Barbados";
$LANGS['cat_BY'] = "Bielorussia";
$LANGS['cat_BE'] = "Belgio";
$LANGS['cat_BZ'] = "Belize";
$LANGS['cat_BJ'] = "Benin";
$LANGS['cat_BM'] = "Bermuda";
$LANGS['cat_BT'] = "Bhutan";
$LANGS['cat_BO'] = "Bolivia";
$LANGS['cat_BQ'] = "Caraibi Paesi Bassi";
$LANGS['cat_BA'] = "Bosnia ed Erzegovina";
$LANGS['cat_BW'] = "Botswana";
$LANGS['cat_BV'] = "Isola Bouvet";
$LANGS['cat_BR'] = "Brasile";
$LANGS['cat_IO'] = "Territorio Britannico dell'Oceano Indiano";
$LANGS['cat_BN'] = "Brunei Darussalam";
$LANGS['cat_BG'] = "Bulgaria";
$LANGS['cat_BF'] = "Burkina Faso";
$LANGS['cat_BI'] = "Burundi";
$LANGS['cat_KH'] = "Cambogia";
$LANGS['cat_CM'] = "Camerun";
$LANGS['cat_CA'] = "Canada";
$LANGS['cat_CV'] = "Capo Verde";
$LANGS['cat_KY'] = "Isole Cayman";
$LANGS['cat_CF'] = "Repubblica Centrafricana";
$LANGS['cat_TD'] = "Ciad";
$LANGS['cat_CL'] = "Cile";
$LANGS['cat_CN'] = "Cina";
$LANGS['cat_CX'] = "Isola di Natale";
$LANGS['cat_CC'] = "Isole Cocos (Keeling)";
$LANGS['cat_CO'] = "Colombia";
$LANGS['cat_KM'] = "Comore";
$LANGS['cat_CG'] = "Repubblica del Congo";
$LANGS['cat_CD'] = "Repubblica Democratica del Congo";
$LANGS['cat_CK'] = "Isole Cook";
$LANGS['cat_CR'] = "Costarica";
$LANGS['cat_CI'] = "Costa d'Avorio";
$LANGS['cat_HR'] = "Croazia";
$LANGS['cat_CU'] = "Cuba";
$LANGS['cat_CW'] = "Curaçao";
$LANGS['cat_CY'] = "Cipro";
$LANGS['cat_CZ'] = "Repubblica Ceca";
$LANGS['cat_DK'] = "Danimarca";
$LANGS['cat_DJ'] = "Gibuti";
$LANGS['cat_DM'] = "Dominica";
$LANGS['cat_DO'] = "Repubblica Dominicana";
$LANGS['cat_EC'] = "Ecuador";
$LANGS['cat_EG'] = "Egitto";
$LANGS['cat_SV'] = "El Salvador";
$LANGS['cat_GQ'] = "Guinea Equatoriale";
$LANGS['cat_ER'] = "Eritrea";
$LANGS['cat_EE'] = "Estonia";
$LANGS['cat_ET'] = "Etiopia";
$LANGS['cat_FK'] = "Isole Falkland (Malvine)";
$LANGS['cat_FO'] = "Isole Faroe";
$LANGS['cat_FJ'] = "Fiji";
$LANGS['cat_FI'] = "Finlandia";
$LANGS['cat_FR'] = "Francia";
$LANGS['cat_GF'] = "Guyana Francese";
$LANGS['cat_FG'] = "Guyana Francese";
$LANGS['cat_PF'] = "Polinesia francese";
$LANGS['cat_TF'] = "Territori Francesi del Sud";
$LANGS['cat_GA'] = "Gabon";
$LANGS['cat_GM'] = "Gambia";
$LANGS['cat_GE'] = "Georgia";
$LANGS['cat_DE'] = "Germania";
$LANGS['cat_GH'] = "Ghana";
$LANGS['cat_GI'] = "Gibilterra";
$LANGS['cat_GR'] = "Grecia";
$LANGS['cat_GL'] = "Groenlandia";
$LANGS['cat_GD'] = "Grenada";
$LANGS['cat_GP'] = "Guadalupa";
$LANGS['cat_GU'] = "Guam";
$LANGS['cat_GT'] = "Guatemala";
$LANGS['cat_GG'] = "Guernsey";
$LANGS['cat_GN'] = "Guinea";
$LANGS['cat_GW'] = "Guinea Bissau";
$LANGS['cat_GY'] = "Guyana";
$LANGS['cat_HT'] = "Haiti";
$LANGS['cat_HM'] = "Isola Heard e Isole McDonald";
$LANGS['cat_VA'] = "Santa Sede (Stato Città del Vaticano)";
$LANGS['cat_HN'] = "Honduras";
$LANGS['cat_HK'] = "Hong Kong";
$LANGS['cat_HU'] = "Ungheria";
$LANGS['cat_IS'] = "Islanda";
$LANGS['cat_IN'] = "India";
$LANGS['cat_ID'] = "Indonesia";
$LANGS['cat_IR'] = "Iran";
$LANGS['cat_IQ'] = "Iraq";
$LANGS['cat_IE'] = "Irlanda";
$LANGS['cat_IM'] = "Isola di Man";
$LANGS['cat_IL'] = "Israele";
$LANGS['cat_IT'] = "Italia";
$LANGS['cat_JM'] = "Giamaica";
$LANGS['cat_JP'] = "Giappone";
$LANGS['cat_JE'] = "Maglia";
$LANGS['cat_JO'] = "Giordania";
$LANGS['cat_KZ'] = "Kazakistan";
$LANGS['cat_KE'] = "Kenia";
$LANGS['cat_KI'] = "Kiribati";
$LANGS['cat_XK'] = "Kosovo";
$LANGS['cat_KP'] = "Corea del Nord";
$LANGS['cat_KR'] = "Corea del Sud";
$LANGS['cat_KW'] = "Kuwait";
$LANGS['cat_KG'] = "Kirghizistan";
$LANGS['cat_LA'] = "Laos";
$LANGS['cat_LV'] = "Lettonia";
$LANGS['cat_LB'] = "Libano";
$LANGS['cat_LS'] = "Lesotho";
$LANGS['cat_LR'] = "Liberia";
$LANGS['cat_LY'] = "Libia";
$LANGS['cat_LI'] = "Liechtenstein";
$LANGS['cat_LT'] = "Lituania";
$LANGS['cat_LU'] = "Lussemburgo";
$LANGS['cat_MO'] = "Macao";
$LANGS['cat_MK'] = "Macedonia del Nord";
$LANGS['cat_MG'] = "Madagascar";
$LANGS['cat_MW'] = "Malawi";
$LANGS['cat_MY'] = "Malesia";
$LANGS['cat_MV'] = "Maldive";
$LANGS['cat_ML'] = "Mali";
$LANGS['cat_MT'] = "Malta";
$LANGS['cat_MH'] = "Isole Marshall";
$LANGS['cat_MQ'] = "Martinica";
$LANGS['cat_MR'] = "Mauritania";
$LANGS['cat_MU'] = "Maurizio";
$LANGS['cat_YT'] = "Maiotte";
$LANGS['cat_MX'] = "Messico";
$LANGS['cat_FM'] = "Micronesia";
$LANGS['cat_MD'] = "Moldavia";
$LANGS['cat_MC'] = "Monaco";
$LANGS['cat_MN'] = "Mongolia";
$LANGS['cat_ME'] = "Montenegro";
$LANGS['cat_MS'] = "Montserrat";
$LANGS['cat_MA'] = "Marocco";
$LANGS['cat_MZ'] = "Mozambico";
$LANGS['cat_MM'] = "Myanmar";
$LANGS['cat_NA'] = "Namibia";
$LANGS['cat_NR'] = "Nauru";
$LANGS['cat_NP'] = "Nepal";
$LANGS['cat_NL'] = "Paesi Bassi";
$LANGS['cat_AN'] = "Antille Olandesi";
$LANGS['cat_NC'] = "Nuova Caledonia";
$LANGS['cat_NZ'] = "Nuova Zelanda";
$LANGS['cat_NI'] = "Nicaragua";
$LANGS['cat_NE'] = "Niger";
$LANGS['cat_NG'] = "Nigeria";
$LANGS['cat_NU'] = "Niue";
$LANGS['cat_NF'] = "Isola Norfolk";
$LANGS['cat_MP'] = "Isole Marianne Settentrionali";
$LANGS['cat_NO'] = "Norvegia";
$LANGS['cat_OM'] = "Oman";
$LANGS['cat_PK'] = "Pakistan";
$LANGS['cat_PW'] = "Palau";
$LANGS['cat_PS'] = "Palestina";
$LANGS['cat_PA'] = "Panama";
$LANGS['cat_PG'] = "Papua Nuova Guinea";
$LANGS['cat_PY'] = "Paraguay";
$LANGS['cat_PE'] = "Perù";
$LANGS['cat_PH'] = "Filippine";
$LANGS['cat_PN'] = "Pitcairn";
$LANGS['cat_PL'] = "Polonia";
$LANGS['cat_PT'] = "Portogallo";
$LANGS['cat_PR'] = "Porto Rico";
$LANGS['cat_QA'] = "Qatar";
$LANGS['cat_RE'] = "Riunione";
$LANGS['cat_RO'] = "Romania";
$LANGS['cat_RU'] = "Russia";
$LANGS['cat_RW'] = "Ruanda";
$LANGS['cat_BL'] = "San Bartolomeo";
$LANGS['cat_SH'] = "Sant'Elena";
$LANGS['cat_KN'] = "Saint Kitts e Nevis";
$LANGS['cat_LC'] = "Santa Lucia";
$LANGS['cat_MF'] = "Saint Martin (parte francese)";
$LANGS['cat_PM'] = "San Pietro e Miquelon";
$LANGS['cat_VC'] = "Saint Vincent e Grenadine";
$LANGS['cat_WS'] = "Samoa";
$LANGS['cat_SM'] = "San Marino";
$LANGS['cat_ST'] = "Sao Tomè e Principe";
$LANGS['cat_SA'] = "Arabia Saudita";
$LANGS['cat_SN'] = "Senegal";
$LANGS['cat_RS'] = "Serbia";
$LANGS['cat_SC'] = "Seychelles";
$LANGS['cat_SL'] = "Sierra Leone";
$LANGS['cat_SG'] = "Singapore";
$LANGS['cat_SX'] = "Sint Maarten";
$LANGS['cat_SK'] = "Slovacchia";
$LANGS['cat_SI'] = "Slovenia";
$LANGS['cat_SB'] = "Isole Salomone";
$LANGS['cat_SO'] = "Somalia";
$LANGS['cat_ZA'] = "Sud Africa";
$LANGS['cat_GS'] = "Georgia del Sud e Isole Sandwich Australi";
$LANGS['cat_ES'] = "Spagna";
$LANGS['cat_LK'] = "Sri Lanka";
$LANGS['cat_SD'] = "Sudan";
$LANGS['cat_SR'] = "Suriname";
$LANGS['cat_SJ'] = "Svalbard e Jan Mayen";
$LANGS['cat_SZ'] = "Swaziland";
$LANGS['cat_SE'] = "Svezia";
$LANGS['cat_CH'] = "Svizzera";
$LANGS['cat_SS'] = "Sud Sudan";
$LANGS['cat_SY'] = "Siria";
$LANGS['cat_TW'] = "Taiwan";
$LANGS['cat_TJ'] = "Tagikistan";
$LANGS['cat_TZ'] = "Tanzania";
$LANGS['cat_TH'] = "Thailandia";
$LANGS['cat_TL'] = "Timor Est";
$LANGS['cat_TG'] = "Togo";
$LANGS['cat_TK'] = "Tokelau";
$LANGS['cat_TO'] = "Tonga";
$LANGS['cat_TT'] = "Trinidad e Tobago";
$LANGS['cat_TN'] = "Tunisia";
$LANGS['cat_TR'] = "Turchia";
$LANGS['cat_TM'] = "Turkmenistan";
$LANGS['cat_TC'] = "Isole Turks e Caicos";
$LANGS['cat_TV'] = "Tuvalu";
$LANGS['cat_UG'] = "Uganda";
$LANGS['cat_UA'] = "Ucraina";
$LANGS['cat_AE'] = "Emirati Arabi Uniti";
$LANGS['cat_GB'] = "Regno Unito";
$LANGS['cat_US'] = "Stati Uniti";
$LANGS['cat_UM'] = "Isole minori esterne degli Stati Uniti";
$LANGS['cat_UY'] = "Uruguay";
$LANGS['cat_UZ'] = "Uzbekistan";
$LANGS['cat_VU'] = "Vanatu";
$LANGS['cat_VE'] = "Venezuela";
$LANGS['cat_VN'] = "Vietnam";
$LANGS['cat_VG'] = "Isole Vergini Britanniche";
$LANGS['cat_VI'] = "Isole Vergini, Stati Uniti";
$LANGS['cat_WF'] = "Wallis e Futuna";
$LANGS['cat_EH'] = "Sahara Occidentale";
$LANGS['cat_YE'] = "Yemen";
$LANGS['cat_ZM'] = "Zambia";
$LANGS['cat_ZW'] = "Zimbabwe";

/* My Subscriptions */
$LANGS['newvideos'] = "Video nuovi";

/* Account */
$LANGS['myaccount'] = "Il mio account";
$LANGS['vidsfavs'] = "Video, Preferiti e Playlist";
$LANGS['accountsettings'] = "Impostazioni Account";
$LANGS['viewinghistory'] = "Cronologia";
$LANGS['mychannel'] = "Il mio canale";
$LANGS['uploadedvideos'] = "Video caricati";
$LANGS['new'] = "Nuovo";
$LANGS['playlist'] = "Playlist";
$LANGS['videoupload'] = "Caricamento di video";
$LANGS['nosubvideos'] = "Non hai nessuna iscrizione...";
$LANGS['nofavvideos'] = "Non hai aggiunto alcun video ai preferiti...";

/* My Videos */
$LANGS['sortby'] = "Ordina per";
$LANGS['sorttitle'] = "Titolo";
$LANGS['sorttime'] = "Tempo";
$LANGS['sortdateadded'] = "Data aggiunta";
$LANGS['sortviews'] = "Visualizzazioni";
$LANGS['sortrating'] = "Recensione";
$LANGS['stattime'] = "Tempo";
$LANGS['statrating'] = "Recensione";
$LANGS['statbroadcast'] = "Trasmissione";
$LANGS['statrawfile'] = "File Raw";
$LANGS['public'] = "Pubblico";
$LANGS['private'] = "Privato";
$LANGS['live'] = "Dal vivo!";
$LANGS['converting'] = "Conversione...";
$LANGS['uploading'] = "Pubblicazione...";
$LANGS['addvidsto'] = "Aggiungi video a";
$LANGS['play'] = "Play";
$LANGS['edit'] = "Modifica";
$LANGS['setasavatar'] = "Imposta Miniatura come Avatar";
$LANGS['downloadmp4'] = "Download del file MP4";
$LANGS['deleteconfirmation'] = "Sei sicuro di voler eliminare questo video?";
$LANGS['novideos'] = 'Non hai caricato alcun video. <a href="/my_videos_upload">Inizia subito a caricare un video</a>!';
$LANGS['nomyvideosresults'] = "Nessun risultato. Controlla se l'ortografia è corretta.";

/* Edit Video */
$LANGS['title'] = "Titolo";
$LANGS['desc'] = "Descrizione";
$LANGS['privacy'] = "Privacy";
$LANGS['saveinfo'] = "Salva Informazioni";
$LANGS['saveinfoconfirm'] = "Sei sicuro di voler cambiare le informazioni sul video?";
$LANGS['viewchart'] = "Visualizza grafico";
$LANGS['backtopreviouspage'] = "Torna alla pagina precedente";
$LANGS['editsavechanges'] = "Salva Modifiche";
$LANGS['editcancel'] = "Annulla";
$LANGS['videoinfo'] = "Informazioni sul Video";
$LANGS['videothumbnail'] = "Miniatura del Video";
$LANGS['uploadthumbnail'] = "Carica Miniatura";
$LANGS['customthumbdesc'] = 'Per impostare una miniatura personalizzata, fai clic sulla miniatura sul lato sinistro e seleziona l\'immagine desiderata. Quindi fai clic su "Carica Miniatura".';
$LANGS['customthumbtitle'] = 'Vuoi cambiare questa miniatura?';
$LANGS['customthumbinfo'] = 'Le miniature personalizzate sono esclusive per i partner. Per saperne di più sui vantaggi del programma partner e i requisiti, fai clic sul pulsante qui sotto.';
$LANGS['partnerreadmore'] = 'Leggi di più';
$LANGS['broadcastingoptions'] = 'Opzioni di Trasmissione e Condivisione';
$LANGS['publicdesc'] = "chiunque può cercare e visualizzare - consigliato";
$LANGS['privatedesc'] = "solo utenti specifici di BitView possono visualizzare";
$LANGS['allowcomments'] = "Consenti commenti automaticamente";
$LANGS['allowfriendcomments'] = "Solo gli amici possono commentare";
$LANGS['disablecomments'] = "Non consentire commenti";
$LANGS['dateandmap'] = "Data e Mappa";
$LANGS['clear'] = "Cancella";
$LANGS['allowratings'] = "Sì, permetti che questo video sia valutato dagli altri.";
$LANGS['dontallowratings'] = "No, non permettere che questo video sia valutato.";


/* My Playlists */
$LANGS['addedpl'] = "Aggiunto";
$LANGS['frompl'] = "Da";
$LANGS['nopl'] = "Nessuna playlist trovata....";

/* My Playlist */
$LANGS['playlistedit'] = "Modifica Playlist";
$LANGS['videourl'] = "URL del Video";
$LANGS['add'] = "Aggiungi";
$LANGS['editinfo'] = "Modifica Informazioni";

/* Edit Playlist */
$LANGS['pledittitle'] = "Modifica Playlist";
$LANGS['pleditdesc'] = "Le playlist sono raccolte di video che puoi impostare nel modo che preferisci.";
$LANGS['cancel'] = "Annulla";

/* Create Playlist */
$LANGS['createplaylisttitle'] = "Crea playlist video";
$LANGS['createplaylist'] = "Crea playlist";

/* View Playlist */
$LANGS['plpermalink'] = "Playlist/URL (Permalink):";
$LANGS['sortcomments'] = "Commenti";
$LANGS['unsorted'] = "Non ordinati";
$LANGS['playallvideos'] = "Riproduci tutti i video";

/* Inbox */
$LANGS['compose'] = "Componi";
$LANGS['from'] = "Da";
$LANGS['subject'] = "Soggetto";
$LANGS['date'] = "Data";
$LANGS['allmsg'] = "Tutti i Messaggi";
$LANGS['msgcom'] = "Commenti";
$LANGS['sentmsg'] = "Messaggi inviati";
$LANGS['nomsg'] = "Non hai messaggi...";


/* Send Message */
$LANGS['messagecont'] = "Messaggio";
$LANGS['to'] = "A";
$LANGS['sendmessagebutton'] = "Invia messaggio";

/* Groups */
$LANGS['groups'] = "Gruppi";
$LANGS['joinedgroups'] = "Gruppi a cui ti sei unito";
$LANGS['recentgroups'] = "Gruppi recenti";
$LANGS['mostmembers'] = "Maggior parte dei membri";
$LANGS['mostvideos'] = "Maggior parte dei video";
$LANGS['groupmostdiscussed'] = "Più discusso";
$LANGS['createagroup'] = "Crea un gruppo";
$LANGS['groupvideos'] = "Video";
$LANGS['groupmembers'] = "Membri";
$LANGS['discussions'] = "Discussioni";
$LANGS['groupcreated'] = "Creato";
$LANGS['nogroups'] = "Nessun gruppo trovato...";

/* Group */
$LANGS['jointhisgroup'] = "Unisciti a questo gruppo";
$LANGS['removerequest'] = "Rimuovi Richiesta";
$LANGS['leavegroup'] = "Lascia il Gruppo";
$LANGS['moderation'] = "Moderazione";
$LANGS['viewallvideos'] = "Vedi tutti i video";
$LANGS['addvideo'] = "Aggiungi Video";
$LANGS['novideos'] = "Nessun video...";
$LANGS['nodiscussions'] = "Nessuna discussione...";
$LANGS['creatediscussion'] = "Crea discussione";
$LANGS['topostatopic'] = "per inserire un argomento.";
$LANGS['topic'] = "Argomento";
$LANGS['author'] = "Autore";
$LANGS['replies'] = "Risposte";
$LANGS['lastpost'] = "Ultimo post";
$LANGS['viewallmembers'] = "Visualizza tutti i membri";
$LANGS['owner'] = "Proprietario";
$LANGS['grouptype'] = "Tipo";
$LANGS['instantjoin'] = "Collegamento istantaneo";
$LANGS['approvalrequired'] = "Approvazione richiesta";
$LANGS['groupurl'] = "URL";
$LANGS['deletediscussion'] = "Elimina discussione";
$LANGS['postreply'] = "Invia risposta";
$LANGS['post'] = "Posta";
$LANGS['accept'] = "Accetta";
$LANGS['decline'] = "Rifiuta";

/* Group Moderation */
$LANGS['groupmoderation'] = "Moderazione di gruppo";
$LANGS['approvemembers'] = "Approva membri";
$LANGS['approvevideos'] = "Approva video";
$LANGS['yes'] = "Sì";
$LANGS['no'] = "No";
$LANGS['changeinfo'] = "Cambia info";
$LANGS['changeimage'] = "Cambia immagine";
$LANGS['image'] = "Immagine";
$LANGS['styling'] = "Stilizzazione";
$LANGS['cssdesc'] = "Avere sfondi o grafica che fanno o mostrano cose illegali comporterà la tua risoluzione.";
$LANGS['updatecss'] = "Aggiorna CSS";
$LANGS['groupmessage'] = "Messaggio";
$LANGS['sendmessagetomembers'] = "Invia messaggi ai Membri";
$LANGS['delgroup'] = "Elimina gruppo";

/* Submit Group Video */
$LANGS['submitvideotitle'] = "Invia video al gruppo";
$LANGS['submitvideo'] = "Invia video";

/* Create Group */
$LANGS['groupname'] = "Nome del gruppo";
$LANGS['groupimage'] = "Immagine del gruppo";
$LANGS['creategroup'] = "Crea gruppo";
$LANGS['creategroupdesc'] = "I gruppi ti consentono di creare discussioni con altri membri e di condividere facilmente i tuoi video con altri.";

/* Create Group Discussion */
$LANGS['discussiontitle'] = "Titolo della discussione";
$LANGS['creatediscussiondesc'] = "Le discussioni sono parti di gruppi in cui si discute l'argomento impostato.";

/* Search Results */
$LANGS['resultspre'] = ""; /* Explanation: Use if the search query goes before "results". Example: "Resultados para search" in Spanish. If your language doesn't use this, leave it empty like this: ''*/
$LANGS['resultspost'] = ""; /* Explanation: Use if "BitView" goes after the username. Example: "search results" in English. If your language doesn't use this, leave it empty like this: '' */
$LANGS['relevance'] = 'Rilevanza';
$LANGS['viewcount'] = 'Conteggio visualizzazioni';
$LANGS['searchrating'] = 'Recensioni';
$LANGS['newest'] = 'Più nuovo';
$LANGS['nochannelsfound'] = 'Nessun canale trovato...';
$LANGS['noplfound'] = 'Nessuna Playlist trovata...';
$LANGS['nogroupsfound'] = 'Nessun gruppo trovato...';

/* Profile */
$LANGS['channelsuspended'] = 'Questo account è stato sospeso.';
$LANGS['accountnotfound'] = 'Questo account non è stato trovato.';
$LANGS['channel'] = 'Canale';
$LANGS['friends'] = 'Amici';
$LANGS['channelsubscribers'] = 'Iscritti';
$LANGS['linkcomments'] = 'Commenti';
$LANGS['bulletins'] = 'Bollettini';
$LANGS['editchannel'] = 'Modifica canale';
$LANGS['type'] = 'Tipo';
$LANGS['joined'] = 'Iscritto su BitView';
$LANGS['videoswatched'] = 'Video guardati';
$LANGS['channelviews'] = 'Visualizzazioni Canale';
$LANGS['age'] = 'Età';
$LANGS['gender'] = 'Sesso';
$LANGS['male'] = 'Uomo';
$LANGS['female'] = 'Femmina';
$LANGS['status'] = 'Stato';
$LANGS['single_m'] = 'Singolo';
$LANGS['single_f'] = 'Singolo';
$LANGS['taken_m'] = 'Preso';
$LANGS['taken_f'] = 'Preso';
$LANGS['married_m'] = 'Sposato';
$LANGS['married_f'] = 'Sposato';
$LANGS['country'] = 'Paese';
$LANGS['website'] = 'Sito Web';
$LANGS['hobbies'] = 'Interessi e Hobby';
$LANGS['music'] = 'Musica';
$LANGS['movies'] = 'Film e Spettacoli';
$LANGS['books'] = 'Libri';
$LANGS['mostsub'] = 'Con più iscritti';
$LANGS['report'] = 'Segnala';
$LANGS['pfpviolation'] = 'violazione immagine profilo';
$LANGS['connectwith'] = 'Connettiti con';
$LANGS['profilesendmessage'] = 'Invia messaggio';
$LANGS['messagetoyourself'] = 'Non puoi inviare messaggi a te stesso!';
$LANGS['logintomessage'] = 'Accedi per inviare messaggi!';
$LANGS['addcomment'] = 'Aggiungi commento';
$LANGS['logintocommentchannel'] = 'Accedi per commentare';
$LANGS['sharechannel'] = 'Condividi canale';
$LANGS['addfriend'] = 'Aggiungi come amico';
$LANGS['retractinvite'] = 'Ritira Invito';
$LANGS['removefriend'] = 'Rimuovi amico';
$LANGS['notfriendyourself'] = 'Non puoi aggiungere te stesso agli amici!';
$LANGS['logintofriend'] = 'Accedi per aggiungere amici!';
$LANGS['blockuser'] = 'Blocca Utente';
$LANGS['channelembed'] = 'Incorpora questo canale';
$LANGS['recentratings'] = 'Recent Activity';
$LANGS['seeall'] = 'vedi tutto';
$LANGS['writebulletin'] = 'Scrivi Bollettino';
$LANGS['bulletin'] = 'Bollettino';
$LANGS['subvideos1'] = 'Iscriviti a ';
$LANGS['subvideos2'] = "i video di";
$LANGS['plvideos'] = 'Video';
$LANGS['playall'] = 'Riproduci tutto';
$LANGS['featuredchannels'] = 'Canali in primo piano';
$LANGS['channelcomments'] = 'Commenti Canale';
$LANGS['bggraphic'] = 'grafica di sfondo';
$LANGS['reportthisuser'] = 'questo utente.';
$LANGS['norecentratings'] = 'No Recent Activity Found...';
$LANGS['nosubscribers'] = 'Nessun iscritto...';
$LANGS['nosubscriptions'] = 'Nessun abbonamento...';
$LANGS['nofriends'] = 'Nessun amico...';
$LANGS['nobulletins'] = 'Nessun Bollettino...';
$LANGS['novideoschannel'] = 'Nessun video...';
$LANGS['nofavs'] = 'Nessun video preferito...';
$LANGS['noplchannel'] = 'Nessuna playlist...';
$LANGS['pvideos'] = 'Video Privati';
$LANGS['pvideosallow'] = 'Non sei autorizzato a vedere questi video...';
$LANGS['plvideoamount'] = 'video';
$LANGS['bulletinpost'] = 'Bollettino postale';
$LANGS['deletebulletin'] = 'Elimina Bollettino';
$LANGS['body'] = 'Corpo';
$LANGS['bulletincomments'] = 'Commenti Bollettino';
$LANGS['tocommentbulletin'] = 'per inviare una risposta a questo bollettino!';
$LANGS['addacomment'] = 'Aggiungi un commento:';
$LANGS['postreplychannel'] = 'Invia risposta';
$LANGS['writecomment'] = 'Scrivi commento';
$LANGS['for'] = 'per';
$LANGS['commentdesc'] = 'I commenti del canale appaiono sul canale degli utenti.';
$LANGS['postbulletin'] = 'Invia Bollettino';
$LANGS['writeabulletin'] = 'Scrivi un bollettino';
$LANGS['bulletindesc'] = 'I bollettini appaiono sulle tue pagine canale e su quelle dei tuoi amici.';
$LANGS['sharingoptions'] = 'Opzioni di condivisione';
$LANGS['sharingoptionsdesc'] = 'Ci sono 2 modi per condividere questo canale.';
$LANGS['sharingoptions1'] = "1. Copia e incolla questo link in un'email o in un messaggio istantaneo.";
$LANGS['sharingoptions2'] = "2. Invia questo canale utilizzando il programma di posta elettronica del tuo computer.";
$LANGS['clicktosend'] = 'Clicca per inviare!';
$LANGS['honorless'] = 'senza';
$LANGS['activitycomment'] = 'ha commentato';
$LANGS['activityfavorite'] = 'ha aggiunto ai preferiti un video';
$LANGS['activityrating'] = 'ha valutato un video:';
$LANGS['activityupload'] = 'ha caricato un nuovo video';
$LANGS['activityfriend'] = 'è diventato amico di';
$LANGS['activitysubscription'] = 'si è iscritto a';
$LANGS['next'] = "Successivo";
$LANGS['previous'] = "Precedente";
$LANGS['settings'] = "Impostazioni";
$LANGS['themescolors'] = "Temi e Colori";
$LANGS['channelmodules'] = "Moduli";
$LANGS['videosandpl'] = "Video e Playlist";
$LANGS['revert'] = "Ripristina! Voglio il mio vecchio canale";
$LANGS['all'] = "Tutto";
$LANGS['uploads'] = "Caricamenti";
$LANGS['channelpl'] = "Playlist";
$LANGS['backtoplaylists'] = "Torna alle Playlist";
$LANGS['searchuploads'] = "Cerca Caricamenti";
$LANGS['info'] = "Informazioni";
$LANGS['viewcomments'] = "Visualizza commenti, video correlati e altro";
$LANGS['seeallcommentsandresponses'] = "Visualizza tutti i commenti e le risposte ai video";
$LANGS['pastethislink'] = "Incolla questo link in un'email o messaggio istantaneo";
$LANGS['selectplaylist'] = "Seleziona Playlist";
$LANGS['profilemsg'] = 'Gli spettatori del tuo canale vedranno qui dei link, inclusi "Iscriviti" e "Aggiungi come amico".';
$LANGS['profile'] = 'Profilo';
$LANGS['profilechangessaved'] = 'Modifiche salvate.';
$LANGS['posting'] = 'caricamento...';
$LANGS['name'] = 'Nome';
$LANGS['totaluploadviews'] = 'Visualizzazioni totali caricamenti';
$LANGS['channeldesc'] = 'Descrizione del canale';
$LANGS['hometown'] = 'Città natale';
$LANGS['occupation'] = 'Occupazione';
$LANGS['companies'] = 'Aziende';
$LANGS['schools'] = 'Scuole';
$LANGS['interests'] = 'Interessi';
$LANGS['movies'] = 'Film';
$LANGS['featuredchannelsdefault'] = 'Clicca su "modifica" sopra per inserire i canali che desideri collegare.';
$LANGS['featuredchannelsdesc'] = 'Per favore, elenca fino a 4 canali di destinazione nell\'ordine in cui desideri che siano mostrati nel tuo canale, separati da virgole e senza spazi. Non elencare nessun canale impedirà che questa casella compaia sul tuo canale.';
$LANGS['backtochannel'] = "torna al canale di {c}";
$LANGS['refresh'] = "Aggiorna";
$LANGS['whichcontent'] = "Quali contenuti vuoi visualizzare?";
$LANGS['myuploadedvideos'] = "I Miei Caricamenti";
$LANGS['myfavorites'] = "I Miei Preferiti";
$LANGS['alsoshowall'] = 'Mostra anche la vista "Tutti"';
$LANGS['featuredvideo'] = 'Video in evidenza';
$LANGS['usemostrecent'] = 'Usa l\'ultimo video del mio set in evidenza';
$LANGS['autoplayfeatured'] = "Riproduci automaticamente il video in evidenza";
$LANGS['areyousure'] = "Sei sicuro di voler continuare?";
$LANGS['unsavedchanges'] = "Sei sicuro di voler cambiare il tema? Le modifiche non salvate verranno perse.";
$LANGS['showadvancedoptions'] = "mostra opzioni avanzate";
$LANGS['hideadvancedoptions'] = "nascondi opzioni avanzate";
$LANGS['general'] = "Generale";
$LANGS['colorpalettes'] = "Palette di colori";
$LANGS['font'] = "Carattere";
$LANGS['wrappercolor'] = "Colore del wrapper";
$LANGS['wrappertextcolor'] = "Colore del testo del wrapper";
$LANGS['wrapperlinkcolor'] = "Colore dei link del wrapper";
$LANGS['wrappertransparency'] = "Trasparenza del wrapper";
$LANGS['repeatbackground'] = "Ripeti sfondo";
$LANGS['titletextcolor'] = "Colore del testo del titolo";
$LANGS['bodytextcolor'] = "Colore del testo del corpo";
$LANGS['transparency'] = "Trasparenza";
$LANGS['bgimgdesc'] = "Carica un'immagine che verrà visualizzata come sfondo nel tuo canale (massimo 2 MB).";
$LANGS['channeltype'] = "Tipo di canale";
$LANGS['channeltags'] = "Tag del canale";
$LANGS['commaseparated'] = "(separati da virgole)";
$LANGS['channeltagsdesc'] = "I tag sono parole chiave utilizzate per aiutare le persone a trovare il tuo canale.";


/* My Profile page */
$LANGS['myprofiledesc'] = 'Questa pagina contiene tutte le impostazioni per il tuo canale BitView.';
$LANGS['profileimages'] = 'Immagini del profilo';
$LANGS['avatar'] = 'Avatar';
$LANGS['backgroundimage'] = 'Immagine dello sfondo';
$LANGS['deleteimage'] = 'Elimina immagine';
$LANGS['channelinformation'] = 'Informazioni del canale';
$LANGS['genderrelationprivate'] = 'Privato';
$LANGS['fctitle'] = 'Titolo F.C.';
$LANGS['relationship'] = 'Rapporto';
$LANGS['birthday'] = 'Compleanno';
$LANGS['showage'] = 'Mostra età';
$LANGS['aboutme'] = 'Su di me';
$LANGS['emailprefs'] = 'Preferenze e-mail';
$LANGS['emailpm'] = "Inviami un'e-mail sui messaggi privati";
$LANGS['emailcomm'] = "Inviami un'e-mail sui commenti video";
$LANGS['emailsub'] = "Inviami un'e-mail sui momenti salienti dell'abbonamento settimanale";
$LANGS['layoutprefs'] = 'Preferenze layout';
$LANGS['bgcolor'] = 'Colore di sfondo';
$LANGS['bgfixed'] = 'Corretto';
$LANGS['bgrepeat'] = 'Ripeti';
$LANGS['norepeat'] = 'Non ripetere';
$LANGS['repeat'] = 'Ripeti';
$LANGS['repeatx'] = 'Ripeti X';
$LANGS['repeaty'] = 'Ripeti Y';
$LANGS['bgposition'] = 'Posizione';
$LANGS['top'] = 'In alto';
$LANGS['middle'] = 'Centro';
$LANGS['bottom'] = 'In basso';
$LANGS['fontcolor'] = 'Colore carattere';
$LANGS['titlefontcolor'] = 'Colore carattere titolo';
$LANGS['linkcolor'] = 'Colore Link';
$LANGS['hlfontcolor'] = 'Colore font finestra info canale';
$LANGS['hlheadercolor'] = 'Colore intestazione finestra info canale';
$LANGS['hlinsidecolor'] = 'Colore sfondo finestra info canale';
$LANGS['headercolor'] = 'Colore instestazione altre finestre';
$LANGS['insidecolor'] = 'Colore sfondo altre finestre';
$LANGS['font'] = 'Carattere Canale';
$LANGS['featuredvideobox'] = 'Riquadro video in primo piano';
$LANGS['subscribersbox'] = 'Finestra Iscritti';
$LANGS['subscriptionsbox'] = 'Finestra dei tuoi Iscritti';
$LANGS['friendsbox'] = 'Finestra Amici';
$LANGS['bulletinsbox'] = 'Finestra Bollettini';
$LANGS['videosbox'] = 'Finestra Video';
$LANGS['favoritesbox'] = 'Finestra Preferiti';
$LANGS['playlistsbox'] = 'Finestra Playlist';
$LANGS['commentsbox'] = 'Finestra Commenti';
$LANGS['ratingsbox'] = 'Recent Activity Box';
$LANGS['partnersettings'] = 'Impostazioni partner';
$LANGS['bannerimage'] = 'Immagine banner';
$LANGS['minibannerimage'] = 'Immagine Mini Banner';
$LANGS['sideimage'] = 'Immagine laterale';
$LANGS['recommendedsize'] = 'dimensione consigliata';
$LANGS['bannerlink'] = 'Sito Web Banner';
$LANGS['sideimagelink'] = 'Sito web immagine laterale';
$LANGS['custombox'] = 'Finestra personalizzata';
$LANGS['customboxtitle'] = 'Titolo Finestra personalizzata';
$LANGS['customboxcontent'] = 'Contenuto Finestra personalizzata';
$LANGS['savechanges'] = 'Salva modifiche';
$LANGS['submitimage'] = 'Invia immagine';
$LANGS['overview'] = 'Panoramica';
$LANGS['profilesetup'] = 'Impostazioni Profilo';
$LANGS['playbacksetup'] = 'Impostazioni Riproduzione';
$LANGS['emailoptions'] = 'Opzioni Email';
$LANGS['manageaccount'] = 'Gestisci Account';
$LANGS['chvideoviews'] = 'Visualizzazioni Video';
$LANGS['change'] = "cambia";
$LANGS['mynetwork'] = "La Mia Rete";
$LANGS['contacts'] = "Contatti";
$LANGS['chvideocomments'] = "Commenti Video";
$LANGS['chmore'] = "Altro";
$LANGS['changepicture'] = "Cambia Immagine";
$LANGS['changepicturedesc'] = "Puoi caricare un file JPG, BMP o PNG. Non caricare immagini contenenti celebrità, nudità, opere d'arte o immagini protette da copyright. La tua immagine verrà visualizzata come un quadrato di 88px per 88px. <b>Dimensione massima del file: 2 MB.</b>";
$LANGS['describeyourself'] = "Descriviti";
$LANGS['personaldetails'] = "Dettagli Personali";
$LANGS['jobscareer'] = "Lavoro / Carriera";
$LANGS['education'] = "Educazione";
$LANGS['videoplaybackquality'] = "Qualità Riproduzione Video";
$LANGS['videoplaybackqualitydesc'] = "Scegli l'impostazione predefinita per la visualizzazione dei video";
$LANGS['alwayshd'] = "Riproduci sempre i video in qualità HD";
$LANGS['neverhd'] = "Non riprodurre mai video in qualità HD";
$LANGS['currentemail'] = "Indirizzo Email Attuale";
$LANGS['changeemailaddress'] = "Cambia Indirizzo Email";
$LANGS['changeemail'] = "Cambia Email";
$LANGS['partnerimages'] = "Immagini Partner";
$LANGS['partnerimagelinks'] = "Collegamenti Immagini Partner";

/* Upload page */
$LANGS['uploadpagetitle'] = 'Pubblicazione video';
$LANGS['step1of2'] = 'Passo 1 of 2';
$LANGS['step2of2'] = 'Passo 2 of 2';
$LANGS['videocategory'] = 'Categoria video';
$LANGS['tagsdesc'] = 'I tag sono parole chiave utilizzate per aiutare le persone a trovare il tuo video.<br> <i>(separati dalle virgole)</i>';
$LANGS['requiredfield'] = '(* indica un campo obbligatorio)';
$LANGS['datemapoptions'] = 'Opzioni data e mappa';
$LANGS['optional'] = '(opzionale)';
$LANGS['chooseoptions'] = 'scegli opzioni';
$LANGS['lessoptions'] = 'meno opzioni';
$LANGS['addressrecorded'] = 'Indirizzo registrato';
$LANGS['uploadcontinue'] = 'Scegli un file...';
$LANGS['file'] = 'File';
$LANGS['broadcastoptions'] = 'Opzioni di trasmissione';
$LANGS['uploadvideo'] = 'Pubblica Video';
$LANGS['needfilevideotoupload'] = 'Please select a video file to upload!';
$LANGS['aboutuploading'] = 'About uploading...';
$LANGS['uploaddesc1'] = 'I caricamenti in genere richiedono 1-5 minuti per MB su una connessione ad alta velocità e la conversione del video richiede alcuni minuti.';
$LANGS['videolimit1'] = 'Il tuo video è limitato a 100 MB - la durata massima del video è di 15 minuti.';
$LANGS['videolimit2'] = 'Il tuo video è limitato a 2GB - la durata massima del video è di 15 minuti.';
$LANGS['partnervideolimit1'] = 'Il tuo video è limitato a 100 MB - la durata massima del video è di 30 minuti.';
$LANGS['partnervideolimit2'] = 'Il tuo video è limitato a 2GB - la durata massima del video è di 30 minuti.';
$LANGS['myvideosdesc'] = 'Dopo il caricamento puoi modificare o rimuovere questo video in qualsiasi momento tramite il link "<a href="/my_videos">I miei video</a>" nella parte superiore della pagina.';
$LANGS['newuploader'] = 'Usa il nuovo caricatore di video';
$LANGS['olduploader'] = 'Usa il vecchio caricatore di video';
$LANGS['videoadded'] = 'Il tuo video è stato aggiunto con successo!';
$LANGS['videoaddeddesc'] = 'Il tuo video è attualmente in fase di elaborazione e sarà disponibile per la visualizzazione tra pochi minuti.';
$LANGS['thankyou'] = 'Grazie';
$LANGS['sharelink'] = 'Condividi il link del tuo video! Copia e incolla qui sotto:';
$LANGS['embedlink'] = 'Riproduci questo video direttamente SUL tuo sito web! Copia e incolla il seguente frammento:';
$LANGS['allrequiredinfo'] = 'Si prega di compilare tutti i campi obbligatori!';

/* Partners */
$LANGS['partnerhead'] = 'Partnership';
$LANGS['partnertitle'] = 'Collabora con BitView';
$LANGS['partnerdesc'] = "Hai ottimi video e un pubblico in crescita. Lascia che BitView ti aiuti a portarlo al livello successivo attraverso il nostro Programma Partner.";
$LANGS['applynow'] = 'Applica ora';
$LANGS['contentpartners'] = 'Partner per i contenuti';
$LANGS['partnerbenefits'] = 'Vantaggi per i partner';
$LANGS['partnerbenefitsdesc'] = 'Ci sono molti vantaggi nel diventare un partner BitView. Alcuni di essi includono:<br><br>- Branding: mettiti in risalto con il branding personalizzato, che include banner, una casella personalizzata per il tuo canale e un badge partner su tutti i tuoi video.<br><br>- Ci sono altri vantaggi in arrivo in futuro!';
$LANGS['qualificationsfaq'] = 'Qualifications & FAQ';
$LANGS['qualificationsfaqdesc'] = 'Per qualificarti per il programma BitView Partner, devi soddisfare alcuni criteri minimi:<br><br>- Crei video originali adatti allo streaming online.<br><br>- Hai >75 iscritti.<br><br> - Il tuo account non viola alcuna <a href="/guidelines">Linee guida della community.</a>';

/* Staff */
$LANGS['bvstaff'] = 'BitView Staff';
$LANGS['bvstaffdesc'] = "Questo è un elenco di persone che hanno lavorato (o lavorano ancora) su BitView - mantenendo vivo il sito - in modo che gli utenti possano esprimersi.";
$LANGS['owners'] = 'Proprietari';
$LANGS['ownerdesc'] = 'Persone che - che fatto scioccante - possiedono la cosa di BitView.';
$LANGS['coowndev'] = 'Comproprietario & Sviluppatore <br>';
$LANGS['owndev'] = 'Proprietario & <br> Sviluppatore';
$LANGS['coownserver'] = 'Comproprietario &<br>Proprietario/Sviluppatore del server';
$LANGS['modsanddevs'] = 'Moderatori e Sviluppatori';
$LANGS['modsanddevsdesc'] = 'Persone che mantengono il sito sicuro e chiaro. Hai qualche problema con il tuo account? Dovresti contattarli.';
$LANGS['moderator'] = 'Moderatore';
$LANGS['moddev'] = 'Sviluppatore &<br>Moderatore';
$LANGS['lettertitle'] = 'Lettera a tutte le persone che hanno aiutato con il sito';
$LANGS['letter'] = "Cari comproprietari, sviluppatori e moderatori di BitView,<br><br>
                 A nome dell'intero team di BitView, vorrei esprimere la mia sincera gratitudine per l'eccezionale dedizione e il duro lavoro. Come uno dei proprietari, mi riempie di immenso orgoglio assistere alla crescita e al successo della nostra piattaforma di condivisione video, e non sarebbe stato possibile senza il tuo prezioso contributo.
                 <br><br>
                 Per il resto dei comproprietari, grazie per il vostro incrollabile supporto e visione. Il tuo impegno per lo sviluppo e il miglioramento della piattaforma è stato determinante nel plasmare BitView.net nella straordinaria comunità che è oggi. La tua leadership e la tua guida strategica sono state fondamentali per affrontare le sfide e le opportunità che si sono presentate sulla nostra strada.
                 <br><br>
                 Ai nostri talentuosi sviluppatori, la tua competenza tecnica e le tue idee innovative hanno trasformato BitView in una piattaforma all'avanguardia che rappresenta perfettamente l'aspetto di YouTube ai tempi. Le tue innumerevoli ore di codifica, risoluzione dei problemi e implementazione delle funzionalità hanno migliorato l'esperienza dell'utente e reso la nostra piattaforma un centro di creatività e intrattenimento. La tua dedizione nel perfezionare la funzionalità e le prestazioni del sito è stata davvero encomiabile.
                 <br><br>
                 Ai nostri diligenti moderatori, estendo il mio più profondo apprezzamento per il mantenimento dell'integrità e della sicurezza della nostra comunità. La tua vigilanza nel far rispettare le regole e le linee guida, garantire interazioni rispettose e affrontare rapidamente eventuali problemi che si presentano è stata fondamentale per promuovere un ambiente accogliente per tutti gli utenti. I tuoi sforzi per mantenere BitView uno spazio per un coinvolgimento costruttivo e contenuti positivi sono altamente encomiabili.
                 <br><br>
                 Insieme, come un team unito, abbiamo raggiunto traguardi significativi e superato numerosi ostacoli. Il successo di BitView è una testimonianza dello sforzo collettivo e della passione che ognuno di voi mette in campo. Il tuo impegno per la nostra visione condivisa è stato davvero stimolante e sono grato di avere persone così eccezionali al mio fianco.
                 <br><br>
                 Mentre continuiamo a crescere ed evolverci, amiamo i legami che abbiamo stretto e rimaniamo fedeli ai valori che definiscono il nostro piccolo sito. Insieme, continueremo quel viaggio nostalgico e forniremo una piattaforma per i creatori per mostrare i loro talenti.
                 <br><br>
                 Ancora una volta, grazie: comproprietari, sviluppatori e moderatori, per la vostra incrollabile dedizione, competenza e incrollabile supporto. Il tuo duro lavoro non è passato inosservato e sono incredibilmente orgoglioso di far parte di questo straordinario team.
                 <br><br>
                 Continua a esprimerti,<br>
                 <3 vistafan12";
$LANGS['backtobitview'] = "Torna a BitView";

/* My Friends */
$LANGS['myfriends'] = 'I miei amici';
$LANGS['invites'] = 'Inviti';
$LANGS['myinvites'] = 'I miei inviti';
$LANGS['incominginvites'] = 'Inviti in arrivo';
$LANGS['noinvites'] = 'Non hai inviti...';
$LANGS['actions'] = 'Azioni';
$LANGS['retract'] = 'Ritiro';

/* About */
$LANGS['aboutus'] = 'Chi siamo';
$LANGS['abouttitle'] = "Cos'è BitView?";
$LANGS['aboutdesc'] = 'BitView è un modo per portare i tuoi video alle persone che ti interessano. Con BitView puoi:';
$LANGS['about1'] = 'Mostra al mondo i tuoi video preferiti';
$LANGS['about2'] = 'Registra video dei tuoi cani, gatti e altri animali domestici';
$LANGS['about3'] = 'Blog i video che fai con la tua fotocamera digitale o cellulare';
$LANGS['about4'] = 'Mostra video in modo sicuro e privato ai tuoi amici e familiari in tutto il mondo';
$LANGS['about5'] = '... e molto, molto altro!';
$LANGS['aboutsignup'] = '<a href="/signup">Registrati ora</a> e apri un account gratuito.';
$LANGS['abouthelp'] = 'Per saperne di più sul nostro servizio, consulta la nostra sezione <a href="help">Aiuto</a>.';
$LANGS['aboutmail'] = 'Non esitare a <a href="mailto:contact@vidlii.co">contattarci</a>.';

/* Community Guidelines */
$LANGS['bvguidelines'] = 'Linee guida della Comunità BitView';
$LANGS['cgtitle1'] = 'Rispetta la Comunità BitView';
$LANGS['cgtitle2'] = 'Non Superare il Limite';
$LANGS['cgtitle3'] = 'Applichiamo Queste Linee Guida';
$LANGS['cgtitle4'] = 'BitView è per la Comunità';
$LANGS['cgtitle5'] = 'Suggerimenti sulle Linee Guida della Comunità';
$LANGS['cgdesc1'] = "Non chiediamo il tipo di rispetto riservato alle suore, agli anziani e ai chirurghi del cervello. Intendiamo non abusare del sito. Ogni nuova funzionalità comunitaria interessante su BitView richiede un certo livello di fiducia. Fidiamo di te per essere responsabile, e milioni di utenti rispettano questa fiducia. Per favore, sii uno di loro.";
$LANGS['cgdesc2'] = "Ecco alcune regole sensate che ti aiuteranno a evitare guai:";
$LANGS['cgdesc3'] = "Prendi sul serio queste regole e tengile a cuore. Non cercare falle o tentare di aggirare le linee guida - limitati a comprenderle e cerca di rispettare lo spirito in cui sono state create. Se desideri ulteriori dettagli, consulta i nostri <a href='#tips'>Suggerimenti sulle Linee Guida della Comunità</a>.";
$LANGS['cgdesc4'] = "Okay, questa riguarda più noi che te. Lo staff di BitView rivede i video segnalati 24 ore al giorno, sette giorni alla settimana, per determinare se violano le nostre Linee Guida della Comunità. Quando lo fanno, li rimuoviamo. A volte un video non viola le nostre Linee Guida della Comunità, ma potrebbe non essere appropriato per tutti. Questi video possono essere soggetti a restrizioni d'età. Gli account vengono penalizzati per le violazioni delle Linee Guida della Comunità e le violazioni gravi o ripetute possono portare alla chiusura dell'account. Se il tuo account viene chiuso, non ti sarà consentito creare nuovi account. Per ulteriori informazioni su come vengono applicate le Linee Guida della Comunità e sulle conseguenze della loro violazione, visita il <a href='/help'>Centro Assistenza</a>.";
$LANGS['cgdesc5'] = "Ricorda che questa è la tua comunità! Ogni utente di BitView rende il sito ciò che è, quindi non aver paura di metterti in gioco e partecipare!";
$LANGS['cgdesc6'] = "Questo è tutto! Grazie per aver letto!";
$LANGS['cgdesc7'] = "Desideri ulteriori dettagli sui limiti e sulle eccezioni nelle Linee Guida della Comunità? Ecco alcuni utili esempi e suggerimenti:";
$LANGS['rule1'] = "BitView non è per la pornografia o contenuti sessualmente espliciti. Se il tuo video rientra in questa categoria, anche se si tratta di un video su te stesso, non pubblicarlo su BitView. Inoltre, sii consapevole che collaboriamo strettamente con le forze dell'ordine e segnaliamo lo sfruttamento minorile.";
$LANGS['rule2'] = "Non pubblicare video che mostrano cose negative come abusi sugli animali, abuso di droghe, consumo di alcol e fumo da parte di minori o la fabbricazione di bombe.";
$LANGS['rule3'] = "La violenza grafica o gratuita non è consentita. Se il tuo video mostra a qualcuno che viene fisicamente ferito, attaccato o umiliato, non pubblicarlo.";
$LANGS['rule4'] = "BitView non è un sito di shock. Non pubblicare video disgustosi su incidenti, cadaveri o simili, con l'intento di scioccare o disgustare.";
$LANGS['rule5'] = "Rispetta i diritti d'autore. Carica solo video che hai creato o per i quali hai l'autorizzazione all'uso. Questo significa che non devi caricare video che non hai creato, o utilizzare contenuti nei tuoi video di cui qualcun altro detiene i diritti d'autore, come tracce musicali, frammenti di programmi coperti da copyright o video realizzati da altri utenti, senza le autorizzazioni necessarie.";
$LANGS['rule6'] = "Sosteniamo la libertà di espressione e difendiamo il diritto di ognuno di esprimere punti di vista impopolari. Tuttavia, non consentiamo discorsi d'odio (discorsi che attaccano o denigrano un gruppo in base a razza o origine etnica, religione, disabilità, genere, età, status di veterano e orientamento sessuale/identità di genere). Questo si applica anche alla promozione di ideologie estremiste in modo positivo.";
$LANGS['rule7'] = "Comportamenti come il comportamento predatorio, il stalking, le minacce, il molesto, l'intimidazione, l'invasione della privacy, la divulgazione delle informazioni personali altrui e l'incitamento di altre persone a compiere atti violenti o a violare i Termini d'uso sono presi molto sul serio. Chiunque venga sorpreso a compiere tali azioni può essere bandito permanentemente da BitView.";
$LANGS['rule8'] = "Tutti odiano lo spam. Non creare descrizioni, tag, titoli o miniature fuorvianti per aumentare le visualizzazioni. Non è consentito pubblicare grandi quantità di contenuti non mirati, indesiderati o ripetitivi, compresi commenti e messaggi privati.";
$LANGS['rule9'] = "Manteniamo il sito sicuro. Non cercare di forzare un account che non ti appartiene. Inoltre, condividere pubblicamente le informazioni di accesso di un account non è consentito.";
$LANGS['rule10'] = "Gli account multipli sono vietati. Vogliamo numeri autentici su video e canali. Non utilizzare più di un account per valutare video e/o commenti. Non è consentito utilizzare account multipli per iscriverti da solo.";
$LANGS['rule11'] = "Hai violato una di queste regole e il tuo account è stato sospeso? È ovvio che sfuggire a questa punizione non è accettato. Ogni nuovo account creato da una persona sospesa verrà automaticamente eliminato.";
$LANGS['cglist1'] = "Divertiti con il sito. C'è molto da vedere qui, e molte persone stanno creando cose incredibili - una di esse potresti essere tu! L'attrezzatura è sempre più economica e facile da usare, quindi tuffati e goditi.";
$LANGS['cglist2'] = "Fai sapere agli altri cosa ne pensi. Il feedback fa parte dell'esperienza e, quando fatto con rispetto, può essere un ottimo modo per fare amicizia, condividere storie e arricchire il tuo tempo su BitView. Quindi lascia commenti, valuta i video, crea le tue risposte ai video che ti interessano, partecipa a concorsi di interesse - c'è molto in corso e molte modalità di partecipazione.";
$LANGS['cglist3'] = "Potresti non apprezzare tutto ciò che vedi. Alcuni contenuti qui potrebbero offenderti: se ritieni che violino i nostri Termini d'uso, clicca sul pulsante 'Segnala' sotto il video che stai guardando per sottoporlo alla revisione dello staff di BitView. Se ciò non avviene, considera semplicemente di fare clic su qualcos'altro: perché perdere tempo a guardare video che non ti piacciono?";
$LANGS['thebitviewteam'] = "— Il Team BitView";
$LANGS['cgcat1'] = "Sesso e Nudità";
$LANGS['cgcat2'] = "Discorsi d'Odio";
$LANGS['cgcat3'] = "Scioccante e Disgustoso";
$LANGS['cgcat4'] = "Comportamenti Illegali Pericolosi";
$LANGS['cgcat5'] = "Minori";
$LANGS['cgcat6'] = "Diritti d'Autore";
$LANGS['cgcat7'] = "Privacy";
$LANGS['cgcat8'] = "Molestie";
$LANGS['cgcat9'] = "Impersonificazione";
$LANGS['cgcat10'] = "Minacce";
$LANGS['cgcat1desc'] = "La maggior parte della nudità non è consentita, in particolare se è in un contesto sessuale. In generale, se un video è inteso a essere sessualmente provocatorio, è meno probabile che sia accettabile su BitView. Sono previste eccezioni per alcuni contenuti educativi, documentari e scientifici, ma solo se quello è l'unico scopo del video e non è gratuitamente grafico. Ad esempio, un documentario sul cancro al seno potrebbe essere appropriato, ma la pubblicazione di frammenti fuori contesto dal documentario potrebbe non esserlo. Questo si applica anche ai contenuti animati.";
$LANGS['cgcat2desc'] = 'Il "discorso d\'odio" si riferisce a contenuti che promuovono l\'odio verso i membri di un gruppo protetto. Ad esempio, contenuti razzisti o sessisti possono essere considerati discorsi d\'odio. A volte c\'è una sottile linea tra ciò che è considerato o non considerato un discorso d\'odio. Ad esempio, è generalmente accettabile criticare una nazione, ma non è accettabile fare generalizzazioni offensive sulle persone di una nazionalità specifica.';
$LANGS['cgcat3desc'] = "Il mondo è un posto pericoloso. A volte le persone si fanno del male ed è inevitabile che questi eventi possano essere documentati su BitView. Tuttavia, non è consentito pubblicare contenuti violenti o sanguinosi che siano principalmente intesi a essere scioccanti, sensazionali o irrispettosi. Se un video è particolarmente grafico o disturbante, dovrebbe essere bilanciato da ulteriori contesti e informazioni. Ad esempio, includere un frammento da un mattatoio in un video sulla produzione di massa di carne potrebbe essere appropriato. Tuttavia, concatenare clip non correlate e spaventose di animali macellati in un video potrebbe essere considerato gratuito se il suo scopo è scioccare piuttosto che illustrare.";
$LANGS['cgcat4desc'] = "BitView non è un sito di shock. Non pubblicare video scioccanti con lo scopo principale di essere scioccanti, sensazionali o disgustosi. Non pubblicare video disgustosi su incidenti, cadaveri o cose simili, con l'intento di scioccare o disgustare.";
$LANGS['cgcat5desc'] = "I video che coinvolgono minori (persone di età inferiore ai 18 anni) sono particolarmente delicati. I video contenenti minori non devono mai essere sessualmente suggestivi o violenti. Presta attenzione quando pubblichi qualcosa che coinvolge un bambino. Se condividi un momento privato o un filmato casalingo, considera la possibilità di renderlo un video privato in modo che solo la tua famiglia e i tuoi amici possano vederlo. Inoltre, accettando i <a href='/terms'>Termini d'uso</a>, confermi di avere più di 13 anni. Gli account appartenenti a utenti minorenni verranno sospesi.";
$LANGS['cgcat6desc'] = "Quando crei qualcosa di originale, ne detieni i diritti d'autore. Allo stesso modo, quando altre persone creano contenuti, potrebbero avere un copyright su di essi. Come comunità creativa, è essenziale che tutti su BitView rispettino i diritti d'autore degli altri. Se non sei sicuro se qualcosa violerà il copyright di qualcuno, la cosa più sicura da fare è creare qualcosa di completamente originale, con immagini e audio da te creati. Se è tutto tuo, non devi mai preoccuparti del copyright: è tuo. Se hai registrato qualcosa da un DVD, ripreso il tuo televisore o scaricato un video online, non pubblicarlo a meno che tu non abbia l'autorizzazione.";
$LANGS['cgcat7desc'] = "Se un video che hai registrato mostra persone facilmente identificabili che non hanno acconsentito a essere filmate, c'è la possibilità che essi possano presentare un reclamo per violazione della privacy per richiederne la rimozione. Ti avviseremo se ciò accade e ti daremo la possibilità di modificare e ri-caricare il tuo video prima di prendere provvedimenti. Se rimuoviamo il tuo video per motivi di privacy, evita di caricare un'altra versione con le stesse persone. È probabile che tali persone presenteranno un nuovo reclamo per la privacy o ti segnaleranno per molestie. Non pubblicare informazioni personali di altre persone, tra cui numeri di telefono, indirizzi, numeri di carte di credito e documenti d'identità. Siamo seri nella protezione della sicurezza dei nostri utenti e sospenderemo gli account che violano la privacy altrui.";
$LANGS['cgcat8desc'] = "Tutto si riduce al rispetto. BitView tratta di condividere e interagire con la community in modo rispettoso. Se non sei sicuro se un video o un commento che hai fatto superi il limite, segui una semplice regola: se non lo diresti a qualcuno in faccia, non dirlo su BitView. E se stai cercando di attaccare, molestare, denigrare o impersonare gli altri, cerca altrove.";
$LANGS['cgcat9desc'] = "L'impersonificazione di un altro utente copiando il layout del canale di qualcun altro, utilizzando un nome utente simile o fingendoti tale persona in commenti, email o video è considerata una forma di molestia. Se desideri mantenere il tuo account, evita di partecipare a qualsiasi forma di impersonificazione o attività di molestia sul sito.";
$LANGS['cgcat10desc'] = "Gli utenti non dovrebbero sentirsi minacciati quando sono su BitView. Punto. Non lasciare commenti minacciosi su video altrui.";

/* Contests */
$LANGS['monthlycontest'] = "Concorso mensile";
$LANGS['monthlycontestschedule'] = "Programma Concorso Video Mensile";
$LANGS['whatisit'] = "Che cos'è?";
$LANGS['thismonthcontest'] = "Questo mese";
$LANGS['lastmonthwinners'] = "Vincitori del mese scorso";
$LANGS['howtoenter'] = "Come posso entrare?";
$LANGS['whowins'] = "Chi vince?";
$LANGS['whowinsdesc'] = "Il vincitore sarà scelto alla fine del mese dallo staff di BitView.";
$LANGS['theprize'] = "Il Premio?";
$LANGS['theprizedesc'] = "Fama, fortuna e l'invidia di tutti.";
$LANGS['contestsuggestion'] = 'Hai un suggerimento per un concorso video mensile? <a href="mailto:contact@vidlii.co">Raccontacelo</a> per favore.';

/* Help */
$LANGS['q1'] = 'D: Come posso condividere i miei video e collegarli dal mio sito web?';
$LANGS['a1'] = 'A: <a href="/sharing">Come condividere e collegare i tuoi video</a>';
$LANGS['q2'] = 'D: Che tipo di video posso caricare?';
$LANGS['a2'] = 'A: Puoi caricare qualsiasi tipo di video personale che desideri condividere con il mondo. Non sono consentite scene di nudo e il tuo video deve essere appropriato per tutti i tipi di pubblico.
<br/>
<br/>
Tuttavia, questo lascia ancora molto spazio alla creatività!! Possiedi un <a href="results?search=dog&t=Search+Videos">cane</a> o un <a href="/results?search=cat&t=Search+Videos">gatto</a>? Sei andato in vacanza in <a href="/results?search=mexico&t=Search+Videos">Messico</a>? Vivi nei <a href="/results?search=netherlands&t=Search+Videos">Paesi Bassi</a>?
<br/>
<br/>
Questi sono solo alcuni esempi dei video che i nostri utenti stanno caricando. Alla fine, ti conosci meglio di te stesso. Cosa <i>vorresti</i> catturare su video?';
$LANGS['q3'] = 'D: Quanto può durare il mio video?';
$LANGS['a3'] = 'A: Il video deve avere una durata inferiore a 15 minuti e una dimensione inferiore a 2 GB (100 MB se utilizzi un vecchio browser).';
$LANGS['q4'] = 'D: Quali formati di file video posso caricare?';
$LANGS['a4'] = 'R: BitView accetta file video dalla maggior parte delle fotocamere digitali e dai cellulari nei formati .WMV, .AVI, .MOV, .MPG, .MP4.';
$LANGS['q5'] = 'D: Come posso migliorare i miei video?';
$LANGS['a5'] = 'R: Ti invitiamo a modificare i tuoi video con software come <a href="https://windows-movie-maker-vista.en.softonic.com/" target="_blank ">Windows Movie Maker</a> (incluso in ogni installazione di Windows) o <a href="https://www.apple.com/lae/imovie/" target="_blank">Apple iMovie</a> . Usando questi programmi puoi modificare facilmente i tuoi video, aggiungere colonne sonore, ecc.';
$LANGS['q6'] = 'D: Conservo i diritti d\'autore e altri diritti legali sui miei video?';
$LANGS['a6'] = 'R: Sì. Conservi tutti i diritti sui tuoi contenuti. BitView non si assume alcun copyright sul tuo materiale.';
$LANGS['q7'] = 'D: Qual è la tua politica sulla violazione del copyright?';
$LANGS['a7'] = "R: BitView rispetta i diritti dei detentori del copyright e degli editori e accetta caricamenti video solo da persone che detengono tutti i diritti necessari sul materiale caricato. La nostra politica è di rispondere a qualsiasi notifica di presunta violazione che rispettare il Digital Millennium Copyright Act (DMCA). Se riceviamo un avviso o altrimenti abbiamo motivo di ritenere che il contenuto inviato violi il copyright di un'altra parte, il tuo account potrebbe essere chiuso e il video rimosso da BitView.";
$LANGS['q8'] = 'D: Come posso segnalare una violazione del copyright?';
$LANGS['a8'] = 'R: Se ritieni che qualcun altro abbia caricato il tuo contenuto protetto da copyright senza il tuo permesso, ti invitiamo a contattare quella persona per risolvere eventuali divergenze direttamente con lei. Puoi anche contattare il nostro team di supporto utilizzando questa <a href="mailto:contact@vidlii.co">email</a>.';
$LANGS['q9'] = 'D: Cosa succede se sono stato falsamente accusato di violazione del copyright?';
$LANGS['a9'] = "R: Ti faremo sapere se riceviamo un reclamo per violazione del copyright su uno qualsiasi dei tuoi contenuti video ospitati su BitView. Ti daremo l'opportunità di rispondere in modo appropriato.";
$LANGS['q10'] = 'D: Cosa stai facendo per evitare che i contenuti che violano le tue policy vengano visualizzati in BitView?';
$LANGS['a10'] = 'R: Effettuiamo una revisione preliminare sui video caricati attraverso un processo sia manuale che automatizzato. Sebbene facciamo del nostro meglio per rilevare e rimuovere i video che violano le nostre linee guida sulle norme, il nostro processo di revisione si concentra principalmente sulla rimozione di contenuti per adulti o evidenti violazioni del copyright e non è infallibile. Tuttavia, incoraggiamo i nostri spettatori a informarci quando scoprono violazioni delle norme o problemi di copyright: abbiamo un processo per esaminare le violazioni delle norme segnalate e rispondere alle violazioni del copyright segnalate ai sensi del Digital Millennium Copyright Act.';
$LANGS['q11'] = 'D: Hai un server Discord o Twitter?';
$LANGS['a11'] = 'Sì! In realtà abbiamo un server Discord e Twitter. Puoi unirti al server Discord facendo clic <a href="https://discord.gg/wgGaqCmwuQ">qui</a> e seguici su Twitter <a href="https://twitter.com/bitview_ ">qui</a>.';
$LANGS['q12'] = "D: Sto usando un vecchio browser mentre sono su BitView e quindi non posso guardare i video. Cosa posso fare?";
$LANGS['activate'] = 'Attiva';
$LANGS['deactivate'] = 'Disattiva';
$LANGS['flashdisclaimer'] = "<b>Nota:</b> Flash Player di BitView viene offerto come opzione di compatibilità. Se il tuo browser supporta il player HTML5 di BitView non dovresti abilitare questa opzione.";
/* BitView on your site */
$LANGS['bvsitetitle1'] = "Le Basi";
$LANGS['bvsitetitle2'] = "API e Coinvolgimento degli Utenti";
$LANGS['bvsitedesc1'] = 'Indipendentemente dalla tua presenza su Internet - un grande sito web, un blog, una pagina su un social network o praticamente qualsiasi altra cosa - ci sono molti modi per integrare BitView al suo interno. Dai semplici embed dei video alle nostre API complete, puoi integrare i video a tutti i livelli di competenza tecnica.';
$LANGS['bvsitedesc2'] = 'Portare BitView sul tuo sito significa più che aggiungere alcuni dei migliaia di video disponibili su BitView. Mantiene i tuoi visitatori interessati e consente l'espressione e l'interazione con uno dei loro servizi preferiti. E porta il tuo sito, blog o pagina nella community video di BitView: una rete internazionale di utenti, creatori e siti connessi attraverso una vasta raccolta di video online.';
$LANGS['bvsitedesc3'] = "Abbiamo evidenziato alcuni modi tipici per integrare i contenuti video di seguito: basta fare clic sulla freccia accanto alla domanda per ottenere la risposta. Se hai domande o suggerimenti o progetti di cui vorresti che fossimo a conoscenza, lascia le domande nel nostro <a href='https://discord.gg/wgGaqCmwuQ'>server Discord</a>.";
$LANGS['bvsitesectiontitle1'] = "Come aggiungere un video al mio blog o alla mia pagina web?";
$LANGS['bvsitesectiontitle2'] = "Come aggiungere un video alla mia pagina su un social network?";
$LANGS['bvsitesectiontitle3'] = "Lavoro per un'importante azienda di blog/web. Come può il video aumentare l'interazione degli utenti sul nostro sito?";
$LANGS['bvsitesectiontitle4'] = "Abbiamo un sito e abbiamo i nostri video. Possiamo pubblicarli sul nostro sito usando BitView?";
$LANGS['bvsitesection1desc1'] = "Dovrai modificare l'HTML della tua voce del blog o della pagina, il che dovrebbe essere piuttosto semplice. In Blogger, ad esempio, basta fare clic sulla scheda &quot;Modifica HTML&quot;.";
$LANGS['bvsitesection1desc2'] = "Successivamente, vai al video che desideri e cerca il riquadro 'Incorpora' nella sezione &quot;Informazioni su questo video&quot;. Copiare il codice HTML presente creerà un player incorporato; il video verrà riprodotto all'interno del tuo sito quando l'utente fa clic sul pulsante 'Riproduci'.";
$LANGS['bvsitesection1desc3'] = "Puoi ridimensionare il player modificando i campi <em>object width=&quot;425&quot;</em> e <em>height=&quot;350&quot;</em> all'inizio e alla fine del codice del player incorporato. Assicurati che le dimensioni che scegli abbiano lo stesso rapporto dei numeri predefiniti, in modo che il video non venga allungato - moltiplica semplicemente la larghezza per 0,8235 per ottenere l'altezza.";
$LANGS['bvsitesection2desc1'] = "Aggiungere video ai profili sui social network come SpaceHey è un ottimo modo per condividere i tuoi video o i tuoi preferiti con gli amici. O, se stai promuovendo qualcosa (come la tua band) su SpaceHey, i video aiuteranno ad attirare visitatori alla tua pagina, che potranno poi condividere il link con i loro amici. I siti dei social network hanno modi simili per aggiungere video, quindi useremo SpaceHey come esempio.";
$LANGS['bvsitesection2desc2'] = 'Accedi al tuo profilo SpaceHey, quindi fai clic sul pulsante "Modifica Profilo".';
$LANGS['bvsitesection2desc3'] = "Successivamente, vai al video che desideri e cerca il riquadro 'Incorpora' nella sezione &quot;Informazioni su questo video&quot;. Copiare il codice HTML presente creerà un player incorporato.";
$LANGS['bvsitesection2desc4'] = "Puoi ridimensionare il player modificando i campi object width=&quot;425&quot; e height=&quot;350&quot; all'inizio e alla fine del codice del player incorporato. Assicurati che le dimensioni che scegli abbiano lo stesso rapporto dei numeri predefiniti, in modo che il video non venga allungato - moltiplica semplicemente la larghezza per 0,8235 per ottenere l'altezza.";
$LANGS['bvsitesection2desc5'] = 'Fai clic su "Anteprima", quindi su "Invia".';
$LANGS['bvsitesection3desc1'] = "Il video è molto più coinvolgente del testo. Attrae più utenti e li trattiene sul tuo sito per più tempo. BitView ha un ampio archivio di contenuti video su Internet insieme agli strumenti di ricerca, riproduzione e API per rendere più semplice l'aggiunta di video per te.";
$LANGS['bvsitesection3desc2'] = "Quando cerchi di aumentare l'interazione, prova a usare il video come un modo per iniziare una discussione o fare un commento, creando più contesto per i tuoi utenti:";
$LANGS['bvsitesection4desc1'] = "È molto facile costruire il tuo sito con i tuoi video gratuitamente. Tutto ciò che devi fare è caricare prima i video su BitView. Non c'è alcun costo e copriremo i costi di hosting e streaming. Non è solo un ottimo modo per aumentare l'interazione degli utenti sul tuo sito, ma è molto semplice e gratuito.";
$LANGS['bvsitesection4desc2'] = "Una volta caricati i video, puoi riportarli al sito:";
$LANGS['bvsitesection4desc3'] = "<b>Incorpora i video uno per uno:</b> Vai al video che desideri mettere sul tuo sito e cerca il riquadro 'Incorpora' accanto al player del video. Copiando il codice HTML presente, verrà creato un player incorporato; il video verrà riprodotto all'interno del tuo sito quando l'utente fa clic sul pulsante 'Riproduci'.";

/* RSS Feeds */
$LANGS['rsstitle1'] = "Cos'è RSS?";
$LANGS['rsstitle2'] = "Come Accedere ai Feed RSS";
$LANGS['rsstitle3'] = "Come Iscriversi ai Feed RSS di BitView";
$LANGS['rssdesc1'] = "Really Simple Syndication (RSS) è un formato basato su XML utilizzato per la distribuzione e la sindacazione di contenuti. Iscriversi ai feed RSS ti consente di ricevere informazioni personalizzate e aggiornate dai tuoi siti web preferiti senza doverli controllare regolarmente per gli aggiornamenti.";
$LANGS['rssdesc2'] = "I lettori di notizie visualizzano i feed RSS dai siti web che specifici: controllano i feed RSS a cui ti sei iscritto e mostrano i nuovi elementi da ciascun feed. Puoi scaricare applicazioni per lettori di notizie per il tuo computer, e ci sono anche molti lettori di notizie basati sul web popolari disponibili, come Google Reader e Bloglines. Alcuni browser web e applicazioni di posta elettronica hanno anche funzionalità RSS integrate.";
$LANGS['rssdesc3'] = "Puoi vedere un elenco di molti lettori di notizie disponibili su <a href='http://en.wikipedia.org/wiki/List_of_feed_aggregators'>Wikipedia</a>."; // Usa l'articolo Wikipedia nella tua lingua se possibile
$LANGS['rssdesc4'] = "BitView offre diversi feed RSS per gruppi di video categorizzati (come quelli caricati di recente, i più visti, ecc.) così come feed personalizzati per utenti e tag.";
$LANGS['rssdesc5'] = "Per iscriverti ai gruppi di video categorizzati, vai semplicemente alla categoria che desideri (ad esempio, &quot;<a href='/browse'>Più Visti - Oggi</a>&quot;). Quindi fai clic sul pulsante arancione 'RSS'. Questo dovrebbe far sì che il tuo lettore di notizie scelto aggiunga la sottoscrizione.";
$LANGS['rssdesc6'] = "Se il tuo browser ha funzionalità RSS, puoi aggiungere il feed lì. Il comando varia tra i browser, ma di solito si trova nei menu 'File' o 'Segnalibri' e sarà chiamato qualcosa come &quot;Iscriviti a questa pagina&quot; o &quot;Nuovo segnalibro live&quot;.";
$LANGS['rssthispage'] = "RSS di questa pagina";

/* TestView */
$LANGS['testviewdesc'] = "Benvenuti in TestView, il nostro laboratorio di idee. Qui gli ingegneri e gli sviluppatori di BitView testano ricette e preparati che non sono ancora completamente pronti e vi invitano a dirci come stanno procedendo.";
$LANGS['flashvideo'] = "Video Flash";
$LANGS['flashvideodesc'] = "Il tuo browser non supporta il video HTML5? Non preoccuparti! Prova il nostro lettore Flash.";
$LANGS['feather'] = "Feather";
$LANGS['featherdesc'] = "Guarda i video di BitView su una pagina a latenza estremamente bassa.";
$LANGS['tryitout'] = "Provalo";
$LANGS['disabletest'] = "Disabilita";
$LANGS['timemachine'] = "Macchina del Tempo";
$LANGS['timemachinedesc'] = "Torna indietro nel tempo, riportando ogni data di BitView agli anni 2000.";
$LANGS['lightsout'] = "Luci Spente";
$LANGS['lightsoutdesc'] = "Stanco di vedere il bianco più accecante sullo schermo? Coloralo di nero e prova una nuova interfaccia elegante.";
$LANGS['featherenabled'] = '"Feather" è ora abilitato!';
$LANGS['timemachineenabled'] = '"Time Machine" è ora abilitato!';
$LANGS['lightsoutenabled'] = '"Lights Out" è ora abilitato!';
$LANGS['featherdisabled'] = '"Feather" è ora disabilitato!';
$LANGS['timemachinedisabled'] = '"Time Machine" è ora disabilitato!';
$LANGS['lightsoutdisabled'] = '"Lights Out" è ora disabilitato!';

/* Footer */
$LANGS['youraccount'] = 'Il tuo Account';
$LANGS['inbox'] = 'Posta in arrivo';
$LANGS['footmore'] = 'di più...';
$LANGS['helpinfo'] = 'Aiuto & Informazioni';
$LANGS['helpcenter'] = 'Centro Aiuto';
$LANGS['ourtwitter'] = 'Il nostro Twitter';
$LANGS['ourdiscord'] = 'Il nostro Discord';
$LANGS['guidelines'] = 'Linee guida della comunità';
$LANGS['partnerships'] = 'Programma Partner';
$LANGS['terms'] = 'Termini di Utilizzo';
$LANGS['privacypolicy'] = 'Informativa sulla privacy';
$LANGS['currentlanguage'] = 'Lingua corrente';
$LANGS['showlanguages'] = 'Mostra lingue';
$LANGS['setlanguagepref'] = 'Imposta la tua lingua preferita';
$LANGS['programs'] = 'Programmi';
$LANGS['developers'] = 'Sviluppatori';
$LANGS['bitviewblog'] = 'Blog di BitView';
$LANGS['policy'] = 'Politica';
$LANGS['discover'] = 'Scopri';
$LANGS['bvphone'] = 'BitView sul Tuo Telefono';
$LANGS['bvsite'] = 'BitView sul Tuo Sito';
$LANGS['bvrss'] = 'Feed RSS di BitView';
$LANGS['mobile'] = 'Mobile';
?>