<?php

/* General stuff */
$LANGS['language'] = '한국어';
$LANGS['languageenglish'] = 'Korean';
$LANGS['languagecode'] = 'ko_KR.UTF-8';
$LANGS['languagechange'] = '언어는 한국어로 설정했습니다.';
$LANGS['numberformat'] = 0; /* If your language uses comma separators (example: 1,000,000), value will be 1. If it uses dots (example: 1.000.000) or doesn't use separators, value will be 0.*/

/* Language window */
$LANGS['welcometobitview'] = 'BitView에 오신 것을 환영합니다!';
$LANGS['languagesuggestion'] = '추천 언어 (우리는 여기에 선호도를 설정했습니다):';
$LANGS['languagesuggestiondesc1'] = '언어 설정을 변경하려면 페이지 맨 아래의 언어 선택기를 사용해주세요.';
$LANGS['languagesuggestiondesc2'] = '설정을 수락하려면 "확인"을 클릭하거나 영어로 사이트를 보려면 "취소"를 클릭하세요.';

/* Time, dates, etc */

$LANGS['second'] = '초';
$LANGS['minute'] = '분';
$LANGS['hour'] = '시간';
$LANGS['day'] = '일';
$LANGS['week'] = '주';
$LANGS['month'] = '달';
$LANGS['year'] = '년';
$LANGS['seconds'] = '초';
$LANGS['minutes'] = '분';
$LANGS['hours'] = '시간';
$LANGS['days'] = '일';
$LANGS['weeks'] = '주';
$LANGS['months'] = '달';
$LANGS['years'] = '년';
$LANGS['ago1'] = '전 '; /* Explanation: Text before "x seconds/minutes/hours..." Example: "hace (1 día)" in Spanish. If your language doesn't use this, leave it empty like this: ''*/
$LANGS['ago2'] = ''; /* Explanation: ago2 -> Text after "x seconds/minutes/hours..." Example: "(1 day) ago" in English, "(1 anno) fa" in Italian. If your language doesn't use this, leave it empty like this: ''*/
$LANGS['january'] = '1월';
$LANGS['february'] = '2월';
$LANGS['march'] = '3월';
$LANGS['april'] = '4월';
$LANGS['may'] = '5월';
$LANGS['june'] = '6월';
$LANGS['july'] = '7월';
$LANGS['august'] = '8월';
$LANGS['september'] = '9월';
$LANGS['october'] = '10월';
$LANGS['november'] = '11월';
$LANGS['december'] = '12월';
$LANGS['shorttimeformat'] = '%e %b %Y';
$LANGS['videotimeformat'] = '%e %B %Y';
$LANGS['longtimeformat'] = '%e %B %Y';
$LANGS['timehourformat'] = '%e %B %Y %I:%M %p';
$LANGS['myvideostimeformat'] = '%A, %e %b %Y, %I:%M:%S %p';
$LANGS['blogpostformat'] = '%A, %e %B %Y';
$LANGS['timenumberformat'] = 'd/m/Y';
$LANGS['monthformat'] = '%B %Y';

/* Header */
$LANGS['home'] = '홈';
$LANGS['videos'] = '동영상';
$LANGS['channels'] = '채널';
$LANGS['community'] = '커뮤니티';
$LANGS['search'] = '검색';
$LANGS['login'] = '로그인';
$LANGS['or'] = '또는';
$LANGS['signup'] = '계정 만들기';
$LANGS['logout'] = '로그아웃';
$LANGS['upload'] = '업로드';
$LANGS['subscriptions'] = '구독';
$LANGS['history'] = '기록';
$LANGS['account'] = '계정';
$LANGS['myvideos'] = '내 동영상';
$LANGS['favorites'] = '즐겨찾기';
$LANGS['playlists'] = '재생 목록';
$LANGS['help'] = '도움말';
$LANGS['suggestions'] = '제안';
$LANGS['quicklist'] = '빠른 목록';
$LANGS['browse'] = '찾아보기';

/* Homepage */
$LANGS['viewall'] = '모두 보기';
$LANGS['videoviews'] = '조회수';
$LANGS['beingwatched'] = '현재 시청 중인 동영상';
$LANGS['featured'] = '주요 동영상';
$LANGS['recommendedforyou'] = '추천합니다';
$LANGS['mostpopular'] = '가장 인기 있는 동영상';
$LANGS['inboxstats'] = '받은 편지함 및 통계';
$LANGS['profilesettings'] = '계정 설정';
$LANGS['messages'] = '편지';
$LANGS['message'] = '편지';
$LANGS['comments'] = '댓글';
$LANGS['comment'] = '댓글';
$LANGS['sharedwithyou'] = '공유된 것';
$LANGS['sharedwithyousingular'] = '당신과 공유';
$LANGS['videoresponses'] = '비디오 응답';
$LANGS['videoresponse'] = '비디오 응답';
$LANGS['friendinvites'] = '친구 초대';
$LANGS['friendinvite'] = '친구 초대';
$LANGS['subscribers'] = '구독자';
$LANGS['subscriber'] = '구독자';
$LANGS['totalviews'] = '총 조회수';
$LANGS['sendmessage'] = '편지 보내기';
$LANGS['whatsnew'] = '새로운 소식';
$LANGS['readmore'] = '블로그에서 자세히 읽기';
$LANGS['videocontest'] = '동영상 대회';
$LANGS['joincontest'] = '지금 대회에 참여하세요!';
$LANGS['personalize'] = '이 홈페이지를 사용자 정의하고 싶나요?';
$LANGS['signinnow'] = '<a href="/login">로그인</a> 또는 <a href="/signup">가입</a>하세요!';
$LANGS['nowconverting'] = '이 동영상은 변환이 진행 중입니다. 잠시 기다려 주세요.';
$LANGS['modules'] = '모듈 추가 / 제거';
$LANGS['friendactivity'] = "친구 활동";
$LANGS['customizehomepage'] = "홈페이지 사용자 정의";
$LANGS['customizethehomepage'] = "홈페이지를 사용자 정의하세요";
$LANGS['customizehomepagedesc'] = "사용자 정의된 홈페이지에서 보고 싶은 모듈을 선택하세요.";
$LANGS['displaypreferences'] = "디스플레이 환경 설정";
$LANGS['thefeed'] = "피드";
$LANGS['thefeeddesc'] = "모든 모듈을 하나의 피드로 결합합니다.";
$LANGS['friendactivitytitle'] = "친구 활동 - 다른 사람들이 내 활동을 볼 수 있을까요?";
$LANGS['friendactivitydesc'] = "이 섹션은 확인된 친구들에게 최근 활동 기록에서 공개적으로 방송하는 작업을 보여줍니다. 예를 들어, 비디오를 즐겨찾기하면 새로운 즐겨찾기 비디오가 채널의 최근 활동 상자뿐만 아니라 친구들의 홈페이지에도 나타날 수 있습니다.";
$LANGS['feedfeatured'] = "추천 비디오";
$LANGS['feedbeingwatched'] = "현재 시청 중인 비디오";
$LANGS['feedrecommended'] = "추천 비디오";
$LANGS['homenosubscriptions'] = "아직 어떤 채널도 구독하지 않았습니다.";
$LANGS['homenosubscriptionsdesc'] = "새로운 구독을 추가하면 해당 페이지에서 업로드를 보여줍니다.";
$LANGS['homenofriendactivity'] = "최근에 친구들의 활동이 없습니다.";
$LANGS['homenofriendactivitydesc'] = "몇몇 친구를 추가해 보세요. 그럼 그들의 활동을 이 페이지에서 볼 수 있습니다.";
$LANGS['homeediting'] = "편집";
$LANGS['homedisplay'] = "표시 방식";
$LANGS['homerows'] = "표시할 행 수";
$LANGS['gridview'] = "그리드 보기";
$LANGS['listview'] = "리스트 보기";

/* Page title */
$LANGS['homepretitle'] = ""; /* Explanation: Use if "BitView" goes before the username. Example: "BitView de username" in Spanish. If your language doesn't use this, leave it empty like this: ''*/
$LANGS['homeposttitle'] = "BitView"; /* Explanation: Use if "BitView" goes after the username. Example: "username's BitView" in English. If your language doesn't use this, leave it empty like this: '' */
$LANGS['chpretitle'] = ""; /* Explanation: Use if "channel" goes before the username. Example: "Canal de username" in Spanish. If your language doesn't use this, leave it empty like this: ''*/
$LANGS['chposttitle'] = " 채널"; /* Explanation: Use if "channel" goes after the username. Example: "username's Channel" in English. If your language doesn't use this, leave it empty like this: '' */
$LANGS['signintitle'] = "로그인";
$LANGS['historytitle'] = "시청 기록";
$LANGS['favtitle'] = "즐겨찾기";
$LANGS['pltitle'] = "재생 목록";
$LANGS['partnerprogram'] = "파트너 프로그램";

/* Notifications */
$LANGS['searcherror'] = '검색어는 최소 2자 이상이어야 합니다!';
$LANGS['addvideoplaylist1'] = "동영상이";
$LANGS['addvideoplaylist2'] = '재생 목록에 추가되었습니다!';
$LANGS['addfavorite1'] = "동영상이";
$LANGS['addfavorite2'] = '즐겨찾기에 추가되었습니다!';
$LANGS['groupdoesnotexist'] = "이 그룹은 존재하지 않습니다!";
$LANGS['uploaddisabled'] = '업로드가 유지 보수를 위해 비활성화되었습니다.';
$LANGS['10vidsday'] = '하루에 10개 이상의 동영상을 업로드할 수 없습니다! 내일 다시 업로드해보세요.';
$LANGS['3mins'] = '새 동영상을 업로드하기 전에 3분을 기다려주세요!';
$LANGS['backgroundsuccess'] = '배경이 성공적으로 업로드되었습니다!';
$LANGS['backgrounderror'] = '배경 이미지는 2MB 미만이어야 하며 이미지 파일이어야 합니다!';
$LANGS['backgrounddeleted'] = '배경이 성공적으로 삭제되었습니다!';
$LANGS['bannersuccess'] = '배너가 성공적으로 업로드되었습니다!';
$LANGS['bannererror'] = '배너 이미지는 2MB 미만이어야 하며 이미지 파일이어야 합니다!';
$LANGS['bannerdeleted'] = '배너가 성공적으로 삭제되었습니다!';
$LANGS['minibannersuccess'] = '미니 배너가 성공적으로 업로드되었습니다!';
$LANGS['minibannererror'] = '미니 배너 이미지는 2MB 미만이어야 하며 이미지 파일이어야 합니다!';
$LANGS['minibannerdeleted'] = '미니 배너가 성공적으로 삭제되었습니다!';
$LANGS['sideimagesuccess'] = '사이드 이미지가 성공적으로 업로드되었습니다!';
$LANGS['sideimageerror'] = '사이드 이미지는 2MB 미만이어야 하며 이미지 파일이어야 합니다!';
$LANGS['sideimagedeleted'] = '사이드 이미지가 성공적으로 삭제되었습니다!';
$LANGS['avatarsuccess'] = '아바타가 성공적으로 업로드되었습니다!';
$LANGS['avatarerror'] = '아바타 이미지는 1MB 미만이어야 하며 이미지 파일이어야 합니다!';
$LANGS['avatardeleted'] = '아바타가 성공적으로 삭제되었습니다!';
$LANGS['changessaved'] = '변경 내용이 성공적으로 저장되었습니다!';
$LANGS['profilesdisabled'] = '프로필이 유지 보수를 위해 비활성화되었습니다.';
$LANGS['bulletinposted'] = '게시판이 게시되었습니다!';
$LANGS['channelcommentsent'] = '채널 댓글이 제출되었습니다!';
$LANGS['somethingwentwrong'] = '문제가 발생했습니다!';
$LANGS['replysubmitted'] = '답글이 제출되었습니다!';
$LANGS['onlyonecomment'] = '한 번에 한 개의 댓글만 남길 수 있습니다!';
$LANGS['vpnbrowser'] = "VPN을 사용하여 BitView 계정을 만들 수 없습니다!";
$LANGS['torbrowser'] = "TOR를 사용하여 BitView 계정을 만들 수 없습니다!";
$LANGS['captchaincorrect'] = "코드를 올바르게 입력하지 않았습니다.";
$LANGS['toomanyaccounts'] = '계정이 너무 많습니다!';
$LANGS['banned2times'] = "이미 2번이나 차단당했습니다. 더 이상 계정을 만들 수 없습니다!";
$LANGS['nohistory'] = "이 세션 동안 시청한 동영상이 없습니다!";
$LANGS['historycleared'] = '시청 기록이 지워졌습니다.';
$LANGS['watchdisabled'] = '동영상 시청이 유지 보수를 위해 비활성화되었습니다.';
$LANGS['videonotexist'] = '해당 동영상이 존재하지 않거나 서비스 약관 위반으로 인해 제거되었습니다.';
$LANGS['responseerror'] = '동영상 응답 중에 오류가 발생했습니다! URL을 다시 확인해주세요.';
$LANGS['responseexist'] = '해당 동영상은 이미 요청되었습니다!';
$LANGS['responseadded'] = '동영상 응답이 성공적으로 추가되었습니다!';
$LANGS['responseaccepted'] = '새 동영상 응답이 승인되었습니다!';
$LANGS['60secscomment'] = '새 댓글을 추가하기 전에 60초를 기다려주세요!';
$LANGS['plnotexist'] = "해당 재생 목록이 존재하지 않습니다!";
$LANGS['positionnotexist'] = "해당 위치는 존재하지 않습니다!";
$LANGS['positionchanged'] = "동영상의 위치가 변경되었습니다!";
$LANGS['invalidurl'] = '잘못된 URL입니다!';
$LANGS['videopladded'] = '동영상이 성공적으로 추가되었습니다!';
$LANGS['videoalreadyinpl'] = '해당 동영상은 이미 이 재생 목록에 있습니다!';
$LANGS['plvideoremoved'] = '동영상이 제거되었습니다!';
$LANGS['plinfochanged'] = '재생 목록 정보가 성공적으로 변경되었습니다!';
$LANGS['pltitleneeded'] = '재생 목록에 제목을 설정해야 합니다!';
$LANGS['flashenabled'] = 'Adobe Flash Player가 활성화되었습니다!';
$LANGS['flashdisabled'] = 'Adobe Flash Player가 비활성화되었습니다!';
$LANGS['messagesent'] = '메시지가 성공적으로 전송되었습니다!';
$LANGS['usernotexist'] = "해당 사용자가 존재하지 않습니다!";
$LANGS['nocriteria'] = "요구 기준을 충족시키지 않습니다!";

$LANGS['alreadypartner'] = '이미 파트너 프로그램에 참여하였습니다!';
$LANGS['alreadyapplied'] = '이미 신청하였습니다!';
$LANGS['applicationsent'] = '신청이 제출되었습니다!';
$LANGS['joinedgroup'] = '그룹에 성공적으로 가입하였습니다!';
$LANGS['leftgroup'] = '그룹에서 성공적으로 탈퇴하였습니다!';
$LANGS['grouprequest'] = '그룹 요청이 성공적으로 전송되었습니다! 이제 수락될 때까지 기다려야 합니다.';
$LANGS['groupdeleted'] = '그룹이 성공적으로 삭제되었습니다!';
$LANGS['groupvideoadded'] = '동영상이 제출되었습니다!';
$LANGS['groupvideoalreadyadded'] = '이미 이 동영상을 제출하였습니다!';
$LANGS['groupvideonotowned'] = '이 동영상을 소유하고 있지 않습니다!';
$LANGS['3groups'] = '최대 3개의 그룹만 소유할 수 있습니다!';
$LANGS['groupnameempty'] = '그룹 이름을 비워둘 수 없습니다!';
$LANGS['groupdescempty'] = '그룹 설명을 비워둘 수 없습니다!';
$LANGS['groupnoimage'] = '그룹에 이미지를 업로드해야 합니다!';
$LANGS['groupimageerror'] = '그룹 이미지는 1MB 이하의 이미지 파일이어야 합니다!';
$LANGS['groupcreated'] = '그룹이 성공적으로 생성되었습니다!';
$LANGS['urlnotvalid'] = '유효한 동영상 URL이 아닙니다!';
$LANGS['discussiondeleted'] = '주제가 성공적으로 삭제되었습니다!';
$LANGS['videodeleted'] = '동영상이 성공적으로 삭제되었습니다!';
$LANGS['pldeleted'] = '재생 목록이 성공적으로 삭제되었습니다!';
$LANGS['invitesent'] = '친구 초대가 성공적으로 전송되었습니다!';
$LANGS['descriptionchanged'] = '설명이 변경되었습니다!';
$LANGS['emptymessage'] = '빈 메시지를 보낼 수 없습니다!';
$LANGS['styleupdated'] = '그룹 스타일이 성공적으로 업데이트되었습니다!';
$LANGS['imageupdated'] = '그룹 이미지가 성공적으로 업데이트되었습니다!';
$LANGS['plcreated'] = '재생 목록이 성공적으로 생성되었습니다!';
$LANGS['discussiontitle2chars'] = '제목은 2글자 이상이어야 합니다!';
$LANGS['discussiondesc10chars'] = '설명은 10글자 이상이어야 합니다!';
$LANGS['5discussionsday'] = '하루에 최대 5개의 토론을 만들 수 있습니다!';
$LANGS['discussionsuccess'] = '토론이 성공적으로 생성되었습니다!';
$LANGS['memberaccepted1'] = '';
$LANGS['memberaccepted2'] = '님이 성공적으로 수락되었습니다!';
$LANGS['memberdeclined1'] = '';
$LANGS['memberdeclined2'] = '님이 성공적으로 거부되었습니다!';
$LANGS['videoaccepted'] = '동영상이 성공적으로 수락되었습니다!';
$LANGS['bulletindeleted'] = '게시물이 성공적으로 삭제되었습니다!';
$LANGS['messagedeleted'] = '메시지가 성공적으로 삭제되었습니다!';
$LANGS['responsedeleted'] = '비디오 응답이 성공적으로 삭제되었습니다!';
$LANGS['flagmod'] = '관리자 권한을 가진 사용자는 신고할 수 없습니다!';
$LANGS['userflagged'] = '신고가 제출되었습니다!';
$LANGS['discussionreplysubmitted'] = '댓글이 성공적으로 전송되었습니다!';
$LANGS['discussionreplyempty'] = '댓글을 비워둘 수 없습니다!';

/* Watch */
$LANGS['moreinfo'] = '자세히 보기';
$LANGS['lessinfo'] = '간략히 보기';
$LANGS['category'] = '카테고리';
$LANGS['recordedon'] = '녹화일';
$LANGS['location'] = '위치';
$LANGS['tags'] = '태그';
$LANGS['embed'] = '임베드';
$LANGS['partnervideo'] = '파트너 비디오';
$LANGS['subscribe'] = '구독하기';
$LANGS['unsubscribe'] = '구독 취소하기';
$LANGS['nodesc'] = '설명 없음...';
$LANGS['logintosub'] = '구독하려면 로그인하세요!';
$LANGS['logintosubbox'] = '구독하시겠습니까?';
$LANGS['subyourself'] = '자신에게 구독할 수 없습니다!';
$LANGS['videoowner'] = '비디오 소유자 옵션';
$LANGS['editvideo'] = '비디오 편집';
$LANGS['insight'] = '인사이트';
$LANGS['morefrom'] = '다음에서 더 보기:';
$LANGS['relatedvideos'] = '관련 동영상';
$LANGS['novideosfound'] = '동영상을 찾을 수 없습니다...';
$LANGS['morevideos'] = '모든 동영상 보기';
$LANGS['changeplayersize'] = '플레이어 크기 변경';
$LANGS['newwindow'] = '이 동영상을 새 창에서 시청하기';
$LANGS['featuredtext'] = '이 동영상은 추천 동영상으로 선정되었습니다. 더 많은 추천 동영상을 보시려면 <a href="/browse?t=2">여기를 클릭하세요</a>.';
$LANGS['ratings'] = '평가';
$LANGS['rating'] = '평가';
$LANGS['favorite'] = '즐겨찾기';
$LANGS['addtofav'] = '즐겨찾기에 추가';
$LANGS['removefav'] = '즐겨찾기에서 제거';
$LANGS['favadded'] = '이 동영상이 <strong>즐겨찾기</strong>에 추가되었습니다. <a href="/my_favorites">즐겨찾기</a>.';
$LANGS['favremoved'] = '이 동영상이 <strong>즐겨찾기</strong>에서 삭제되었습니다. <a href="/my_favorites">즐겨찾기</a>.';
$LANGS['undo'] = '실행 취소';
$LANGS['thanksforrating'] = '평가해 주셔서 감사합니다!';
$LANGS['playlistdesc'] = '새 비디오를 재생목록에 추가하려면 <a href="/my_playlists">"내 재생목록"</a> 페이지로 이동하세요.';
$LANGS['addtoplaylist'] = '재생 목록에 추가';
$LANGS['addtoplaylistsuccess'] = '동영상이 재생 목록에 추가되었습니다.';
$LANGS['share'] = '공유하기';
$LANGS['flag'] = '신고하기';
$LANGS['flagthisvid'] = '이 동영상 신고하기';
$LANGS['removeflag'] = '신고 제거';
$LANGS['flagnote'] = '신고하기 전에, 동영상이 규칙을 어긴 것인지 확인하세요. 단순히 싫어서 신고하지 마세요. 그렇게 할 경우, 운영자의 업무에 방해가 됩니다.';
$LANGS['statadded'] = '추가됨';
$LANGS['statviews'] = '조회수';
$LANGS['statratings'] = '평가 수';
$LANGS['statresponses'] = '비디오 응답';
$LANGS['statcomments'] = '댓글 수';
$LANGS['statfavorited'] = '즐겨찾기 수';
$LANGS['statsdata'] = '통계 및 데이터';
$LANGS['honors'] = '이 동영상의 명예';
$LANGS['mostviewed'] = '가장 많이 조회된 동영상';
$LANGS['topfavorited'] = '최고로 즐겨찾기된 동영상';
$LANGS['times'] = '번';
$LANGS['mostdiscussed'] = '가장 많이 논의된 동영상';
$LANGS['toprated'] = '최고 평가 동영상';
$LANGS['videolinks'] = '이 동영상을 링크한 사이트';
$LANGS['clicksfrom'] = '방문 수:';
$LANGS['responses'] = '비디오 응답';
$LANGS['responsespost'] = '비디오 응답 올리기';
$LANGS['textcomments'] = '텍스트 댓글';
$LANGS['commentpost'] = '텍스트 댓글 올리기';
$LANGS['commentonthisvideo'] = '이 동영상에 댓글 남기기';
$LANGS['postcomment'] = '댓글 올리기';
$LANGS['remainingcounter'] = '남은 글자 수';
$LANGS['nocomments'] = '이 동영상에는 <b>댓글이 없습니다</b>.';
$LANGS['noresponses'] = '이 동영상에는 <b>비디오 응답이 없습니다</b>.';
$LANGS['commviewall'] = '전체 보기';
$LANGS['delete'] = '삭제';
$LANGS['reply'] = '답글';
$LANGS['commentlogin'] = '댓글을 남기시겠습니까?';
$LANGS['commentlogindesc'] = '무료 계정으로 <a href="/signup">BitView 가입</a>하거나, 이미 회원이라면 <a href="/login">로그인</a>하세요.';
$LANGS['logintoresponse'] = '비디오 응답을 올리려면 로그인하세요';
$LANGS['logintocomment'] = '댓글을 올리려면 로그인하세요';
$LANGS['logintofav'] = '즐겨찾기에 추가하고 싶으신가요? <a href="/login">로그인</a> 또는 <a href="/signup">가입하기</a>!';
$LANGS['logintopl'] = '재생목록에 추가하고 싶으신가요? <a href="/login">로그인</a> 또는 <a href="/signup">가입하기</a>!';
$LANGS['logintoflag'] = '동영상을 신고하고 싶으신가요? <a href="/login">로그인</a> 또는 <a href="/signup">가입하기</a>!';
$LANGS['close'] = '닫기';
$LANGS['addresponse'] = '비디오 응답 추가';
$LANGS['recentlyrated'] = '최근 평가한 동영상';
$LANGS['commentsdisabled'] = '이 동영상에 대한 댓글 추가가 비활성화되었습니다.';
$LANGS['ratingsdisabled'] = '평가 비활성화됨';
$LANGS['rating1'] = '약함';
$LANGS['rating2'] = '별로 특별하지 않음';
$LANGS['rating3'] = '시청 가치 있음';
$LANGS['rating4'] = '꽤 멋짐';
$LANGS['rating5'] = '멋져요!';
$LANGS['saving'] = '저장 중...';
$LANGS['signintorate'] = '<a href="/login">로그인</a>하여 평가하십시오';
$LANGS['addingcomment'] = "댓글 추가 중...";
$LANGS['commentposted'] = "댓글 게시됨!";
$LANGS['commentspammsg'] = "동일한 댓글을 반복해서 게시하면 스팸으로 간주됩니다. 나중에 다시 시도하세요.";
$LANGS['commentspammsg2'] = "연속으로 5개 이상의 댓글을 게시하면 스팸으로 간주됩니다. 나중에 다시 시도하세요.";
$LANGS['emptycomment'] = "댓글이 비어 있을 수 없습니다.";
$LANGS['spambutton'] = "스팸";
$LANGS['notspambutton'] = "스팸 아님";
$LANGS['commentsspam'] = "스팸으로 표시된 댓글(들)";
$LANGS['marked'] = "스팸으로 표시됨";
$LANGS['spamshow'] = "보기";
$LANGS['spamhide'] = "숨기기";
$LANGS['poorcomment'] = "별로인 댓글";
$LANGS['goodcomment'] = "좋은 댓글";
$LANGS['pleasesignin'] = "로그인해주세요";
$LANGS['showmorecomments'] = "더 많은 댓글 보기";
$LANGS['showingamount'] = "<strong>{number}개</strong> 중 {total}개의 댓글 표시";
$LANGS['customize'] = "맞춤설정";
$LANGS['customizedesc'] = "선택을 완료한 후에는 위의 임베드 코드를 복사하여 붙여넣으세요. 코드는 선택에 따라 변경됩니다.";

/* Watch comments */
$LANGS['allcomments'] = '모든 댓글';

/* Sign In */
$LANGS['username'] = "사용자 이름";
$LANGS['password'] = "비밀번호";
$LANGS['logindesc'] = "계정으로 BitView에 로그인하세요";
$LANGS['forgot'] = "계정에 접근할 수 없나요?";
$LANGS['forgotmsg'] = 'Twitter (@BitView_)에서 문의하거나 푸터에 있는 Discord를 통해 관리자에게 메시지를 보내주시기 바랍니다.';
$LANGS['noaccount'] = "계정이 없나요?";
$LANGS['signuptobv'] = "BitView 가입하기!";
$LANGS['signintobv'] = "BitView에 로그인하기!";
$LANGS['signindesc1'] = "가장 큰 글로벌 비디오 공유 커뮤니티에 가입하세요!";
$LANGS['signindesc2'] = "BitView를 통해 중요한 사람들에게 동영상을 보여줄 수 있습니다. BitView를 사용하면 다음과 같은 작업을 수행할 수 있습니다.";
$LANGS['signindesc3'] = "세상에 자랑할 수 있는 좋아하는 동영상 보여주기";
$LANGS['signindesc4'] = "디지털 카메라나 휴대전화로 찍은 동영상 블로그에 올리기";
$LANGS['signindesc5'] = "친구와 가족들과 전 세계 어디에서든 안전하고 비공개로 동영상 공유하기";
$LANGS['notallowed'] = "이미 3번 밴당했습니다. BitView를 더 이상 사용할 수 없습니다!";
$LANGS['wrongpassword'] = '잘못된 비밀번호입니다! 다시 시도해주세요.';
$LANGS['staysigned'] = "로그인 유지";

/* Sign Up */
$LANGS['email'] = "이메일 주소";
$LANGS['passwordstrength'] = "비밀번호 강도";
$LANGS['psnone'] = "없음";
$LANGS['psweak'] = "약함";
$LANGS['psfair'] = "보통";
$LANGS['psgood'] = "양호";
$LANGS['psstrong'] = "강력";
$LANGS['repassword'] = "비밀번호 재입력";
$LANGS['usernamedesc'] = "사용자 이름은 영문 대문자 A-Z 또는 숫자 0-9만 포함할 수 있습니다.";
$LANGS['captcha'] = "자동입력 방지";
$LANGS['acceptterms'] = '나는 <a href="/terms">이용약관</a>과 <a href="/privacy">개인정보 처리방침</a>에 동의합니다.';
$LANGS['copyrighttext'] = '저작권을 소유하지 않은 자료를 업로드하는 것은 저작권 침해로 간주되며 불법입니다. 자신이 소유하지 않은 자료를 업로드하면 계정이 삭제될 수 있습니다.';
$LANGS['mustaccept'] = '계정을 만들려면 이용약관과 개인정보 처리방침에 동의해야 합니다.';
$LANGS['createaccount'] = '계정 만들기';
$LANGS['signuperror'] = '계정을 만드는 동안 오류가 발생했습니다.';
$LANGS['sameemail'] = '이 사용자 이름 또는 이메일은 이미 사용 중입니다!';
$LANGS['usernamechar'] = '사용자 이름은 문자와 숫자만 포함할 수 있습니다!';
$LANGS['required'] = '모든 텍스트 필드는 필수입니다!';
$LANGS['notmatch'] = "비밀번호가 일치하지 않습니다!";
$LANGS['signuphead'] = '계정 만들기 시작하기';

/* Videos Page */
$LANGS['recentvideos'] = '최신 동영상';
$LANGS['random'] = '랜덤';
$LANGS['dropdownmore'] = '더보기';
$LANGS['allcatin'] = '분류:';
$LANGS['allcat'] = '모든 분류';
$LANGS['categories'] = '분류';
$LANGS['nomorevideos'] = '더 이상 동영상이 없습니다...';
$LANGS['timetoday'] = '오늘';
$LANGS['timeweek'] = '이번 주';
$LANGS['timemonth'] = '이번 달';
$LANGS['alltime'] = '전체 기간';
$LANGS['when'] = '언제';
$LANGS['videofavorites'] = '즐겨찾기';
$LANGS['videocomments'] = '댓글';
$LANGS['trendingtopics'] = '인기 주제';

/* Channels Page */
$LANGS['mostsubscribed'] = '가장 많은 구독자';
$LANGS['lastlogin'] = '최근 로그인';
$LANGS['cstatviews'] = '조회수';
$LANGS['cstatvideos'] = '동영상';
$LANGS['cstatsubs'] = '구독자';
$LANGS['nochannels'] = '더 이상 채널이 없습니다...';

/* Video Categories */
$LANGS['cat1'] = "영화 및 애니메이션";
$LANGS['cat2'] = "자동차 및 차량";
$LANGS['cat3'] = "교육 및 교육";
$LANGS['cat4'] = "엔터테인먼트";
$LANGS['cat5'] = "이벤트 및 결혼식";
$LANGS['cat6'] = "가족";
$LANGS['cat7'] = "판매 및 경매";
$LANGS['cat8'] = "취미 및 관심사";
$LANGS['cat9'] = "유머";
$LANGS['cat10'] = "음악";
$LANGS['cat11'] = "뉴스 및 정치";
$LANGS['cat12'] = "기이하고 엄청난";
$LANGS['cat13'] = "사람들과 블로그";
$LANGS['cat14'] = "개인 및 데이트";
$LANGS['cat15'] = "애완동물 및 동물";
$LANGS['cat16'] = "과학 및 기술";
$LANGS['cat17'] = "단편 영화";
$LANGS['cat18'] = "스포츠";
$LANGS['cat19'] = "여행 및 이벤트";
$LANGS['cat20'] = "게임";
$LANGS['cat21'] = "비디오 블로그";

/* Channel Types */
$LANGS['type0'] = "없음";
$LANGS['type1'] = "회원";
$LANGS['type1p'] = "회원들";
$LANGS['type2'] = "코미디언";
$LANGS['type2p'] = "코미디언들";
$LANGS['type3'] = "감독";
$LANGS['type3p'] = "감독들";
$LANGS['type4'] = "전문가";
$LANGS['type4p'] = "전문가들";
$LANGS['type5'] = "음악가";
$LANGS['type5p'] = "음악가들";
$LANGS['type6'] = "기자";
$LANGS['type6p'] = "기자들";

/* Countries */

$LANGS['cat_AF'] = "아프가니스탄";
$LANGS['cat_AX'] = "올란드 제도";
$LANGS['cat_AL'] = "알바니아";
$LANGS['cat_DZ'] = "알제리";
$LANGS['cat_AS'] = "아메리칸 사모아";
$LANGS['cat_AD'] = "안도라";
$LANGS['cat_AO'] = "앙골라";
$LANGS['cat_AI'] = "앵귈라";
$LANGS['cat_AQ'] = "남극 대륙";
$LANGS['cat_AG'] = "앤티가 바부다";
$LANGS['cat_AR'] = "아르헨티나";
$LANGS['cat_AM'] = "아르메니아";
$LANGS['cat_AW'] = "아루바";
$LANGS['cat_AU'] = "오스트레일리아";
$LANGS['cat_AT'] = "오스트리아";
$LANGS['cat_AZ'] = "아제르바이잔";
$LANGS['cat_BS'] = "바하마";
$LANGS['cat_BH'] = "바레인";
$LANGS['cat_BD'] = "방글라데시";
$LANGS['cat_BB'] = "바베이도스";
$LANGS['cat_BY'] = "벨라루스";
$LANGS['cat_BE'] = "벨기에";
$LANGS['cat_BZ'] = "벨리즈";
$LANGS['cat_BJ'] = "베냉";
$LANGS['cat_BM'] = "버뮤다";
$LANGS['cat_BT'] = "부탄";
$LANGS['cat_BO'] = "볼리비아";
$LANGS['cat_BQ'] = "카리브 네덜란드";
$LANGS['cat_BA'] = "보스니아 헤르체고비나";
$LANGS['cat_BW'] = "보츠와나";
$LANGS['cat_BV'] = "부베섬";
$LANGS['cat_BR'] = "브라질";
$LANGS['cat_IO'] = "영국령 인도양 지역";
$LANGS['cat_BN'] = "브루나이";
$LANGS['cat_BG'] = "불가리아";
$LANGS['cat_BF'] = "부르키나파소";
$LANGS['cat_BI'] = "부룬디";
$LANGS['cat_KH'] = "캄보디아";
$LANGS['cat_CM'] = "카메룬";
$LANGS['cat_CA'] = "캐나다";
$LANGS['cat_CV'] = "카보베르데";
$LANGS['cat_KY'] = "케이맨 제도";
$LANGS['cat_CF'] = "중앙 아프리카 공화국";
$LANGS['cat_TD'] = "차드";
$LANGS['cat_CL'] = "칠레";
$LANGS['cat_CN'] = "중국";
$LANGS['cat_CX'] = "크리스마스 섬";
$LANGS['cat_CC'] = "코코스 제도";
$LANGS['cat_CO'] = "콜롬비아";
$LANGS['cat_KM'] = "코모로";
$LANGS['cat_CG'] = "콩고 공화국";
$LANGS['cat_CD'] = "콩고 민주 공화국";
$LANGS['cat_CK'] = "쿡 제도";
$LANGS['cat_CR'] = "코스타리카";
$LANGS['cat_CI'] = "코트디부아르";
$LANGS['cat_HR'] = "크로아티아";
$LANGS['cat_CU'] = "쿠바";
$LANGS['cat_CW'] = "퀴라소";
$LANGS['cat_CY'] = "키프로스";
$LANGS['cat_CZ'] = "체코";
$LANGS['cat_DK'] = "덴마크";
$LANGS['cat_DJ'] = "지부티";
$LANGS['cat_DM'] = "도미니카";
$LANGS['cat_DO'] = "도미니카 공화국";
$LANGS['cat_EC'] = "에콰도르";
$LANGS['cat_EG'] = "이집트";
$LANGS['cat_SV'] = "엘살바도르";
$LANGS['cat_GQ'] = "적도 기니";
$LANGS['cat_ER'] = "에리트레아";
$LANGS['cat_EE'] = "에스토니아";
$LANGS['cat_ET'] = "에티오피아";
$LANGS['cat_FK'] = "포클랜드 제도";
$LANGS['cat_FO'] = "페로 제도";
$LANGS['cat_FJ'] = "피지";
$LANGS['cat_FI'] = "핀란드";
$LANGS['cat_FR'] = "프랑스";
$LANGS['cat_GF'] = "프랑스령 기아나";
$LANGS['cat_FG'] = "프랑스령 기아나";
$LANGS['cat_PF'] = "프랑스령 폴리네시아";
$LANGS['cat_TF'] = "프랑스령 남방 및 남극";
$LANGS['cat_GA'] = "가봉";
$LANGS['cat_GM'] = "감비아";
$LANGS['cat_GE'] = "조지아";
$LANGS['cat_DE'] = "독일";
$LANGS['cat_GH'] = "가나";
$LANGS['cat_GI'] = "지브롤터";
$LANGS['cat_GR'] = "그리스";
$LANGS['cat_GL'] = "그린란드";
$LANGS['cat_GD'] = "그레나다";
$LANGS['cat_GP'] = "과들루프";
$LANGS['cat_GU'] = "괌";
$LANGS['cat_GT'] = "과테말라";
$LANGS['cat_GG'] = "건지";
$LANGS['cat_GN'] = "기니";
$LANGS['cat_GW'] = "기니비사우";
$LANGS['cat_GY'] = "가이아나";
$LANGS['cat_HT'] = "아이티";
$LANGS['cat_HM'] = "허드 맥도널드 제도";
$LANGS['cat_VA'] = "바티칸 시국";
$LANGS['cat_HN'] = "온두라스";
$LANGS['cat_HK'] = "홍콩";
$LANGS['cat_HU'] = "헝가리";
$LANGS['cat_IS'] = "아이슬란드";
$LANGS['cat_IN'] = "인도";
$LANGS['cat_ID'] = "인도네시아";
$LANGS['cat_IR'] = "이란";
$LANGS['cat_IQ'] = "이라크";
$LANGS['cat_IE'] = "아일랜드";
$LANGS['cat_IM'] = "맨 섬";
$LANGS['cat_IL'] = "이스라엘";
$LANGS['cat_IT'] = "이탈리아";
$LANGS['cat_JM'] = "자메이카";
$LANGS['cat_JP'] = "일본";
$LANGS['cat_JE'] = "저지";
$LANGS['cat_JO'] = "요르단";
$LANGS['cat_KZ'] = "카자흐스탄";
$LANGS['cat_KE'] = "케냐";
$LANGS['cat_KI'] = "키리바시";
$LANGS['cat_XK'] = "코소보";
$LANGS['cat_KP'] = "북한";
$LANGS['cat_KR'] = "대한민국";
$LANGS['cat_KW'] = "쿠웨이트";
$LANGS['cat_KG'] = "키르기스스탄";
$LANGS['cat_LA'] = "라오스";
$LANGS['cat_LV'] = "라트비아";
$LANGS['cat_LB'] = "레바논";
$LANGS['cat_LS'] = "레소토";
$LANGS['cat_LR'] = "라이베리아";
$LANGS['cat_LY'] = "리비아";
$LANGS['cat_LI'] = "리히텐슈타인";
$LANGS['cat_LT'] = "리투아니아";
$LANGS['cat_LU'] = "룩셈부르크";
$LANGS['cat_MO'] = "마카오";
$LANGS['cat_MK'] = "북마케도니아";
$LANGS['cat_MG'] = "마다가스카르";
$LANGS['cat_MW'] = "말라위";
$LANGS['cat_MY'] = "말레이시아";
$LANGS['cat_MV'] = "몰디브";
$LANGS['cat_ML'] = "말리";
$LANGS['cat_MT'] = "몰타";
$LANGS['cat_MH'] = "마셜 제도";
$LANGS['cat_MQ'] = "마르티니크";
$LANGS['cat_MR'] = "모리타니";
$LANGS['cat_MU'] = "모리셔스";
$LANGS['cat_YT'] = "마요트";
$LANGS['cat_MX'] = "멕시코";
$LANGS['cat_FM'] = "미크로네시아";
$LANGS['cat_MD'] = "몰도바";
$LANGS['cat_MC'] = "모나코";
$LANGS['cat_MN'] = "몽골";
$LANGS['cat_ME'] = "몬테네그로";
$LANGS['cat_MS'] = "몬트세라트";
$LANGS['cat_MA'] = "모로코";
$LANGS['cat_MZ'] = "모잠비크";
$LANGS['cat_MM'] = "미얀마";
$LANGS['cat_NA'] = "나미비아";
$LANGS['cat_NR'] = "나우루";
$LANGS['cat_NP'] = "네팔";
$LANGS['cat_NL'] = "네덜란드";
$LANGS['cat_NC'] = "뉴칼레도니아";
$LANGS['cat_NZ'] = "뉴질랜드";
$LANGS['cat_NI'] = "니카라과";
$LANGS['cat_NE'] = "니제르";
$LANGS['cat_NG'] = "나이지리아";
$LANGS['cat_NU'] = "니우에";
$LANGS['cat_NF'] = "노퍽 섬";
$LANGS['cat_MP'] = "북마리아나 제도";
$LANGS['cat_NO'] = "노르웨이";
$LANGS['cat_OM'] = "오만";
$LANGS['cat_PK'] = "파키스탄";
$LANGS['cat_PW'] = "팔라우";
$LANGS['cat_PS'] = "팔레스타인";
$LANGS['cat_PA'] = "파나마";
$LANGS['cat_PG'] = "파푸아 뉴기니";
$LANGS['cat_PY'] = "파라과이";
$LANGS['cat_PE'] = "페루";
$LANGS['cat_PH'] = "필리핀";
$LANGS['cat_PN'] = "핏케언";
$LANGS['cat_PL'] = "폴란드";
$LANGS['cat_PT'] = "포르투갈";
$LANGS['cat_PR'] = "푸에르토리코";
$LANGS['cat_QA'] = "카타르";
$LANGS['cat_RE'] = "레위니옹";
$LANGS['cat_RO'] = "루마니아";
$LANGS['cat_RU'] = "러시아";
$LANGS['cat_RW'] = "르완다";
$LANGS['cat_BL'] = "생 바르텔레미";
$LANGS['cat_SH'] = "세인트 헬레나";
$LANGS['cat_KN'] = "세인트 키츠 네비스";
$LANGS['cat_LC'] = "세인트 루시아";
$LANGS['cat_MF'] = "세인트 마틴 (프랑스 영토)";
$LANGS['cat_PM'] = "생 피에르 미클롱";
$LANGS['cat_VC'] = "세인트 빈센트 그레나딘";
$LANGS['cat_WS'] = "사모아";
$LANGS['cat_SM'] = "산 마리노";
$LANGS['cat_ST'] = "상투메 프린시페";
$LANGS['cat_SA'] = "사우디아라비아";
$LANGS['cat_SN'] = "세네갈";
$LANGS['cat_RS'] = "세르비아";
$LANGS['cat_SC'] = "세이셸";
$LANGS['cat_SL'] = "시에라리온";
$LANGS['cat_SG'] = "싱가포르";
$LANGS['cat_SX'] = "신트마르턴";
$LANGS['cat_SK'] = "슬로바키아";
$LANGS['cat_SI'] = "슬로베니아";
$LANGS['cat_SB'] = "솔로몬 제도";
$LANGS['cat_SO'] = "소말리아";
$LANGS['cat_ZA'] = "남아프리카";
$LANGS['cat_GS'] = "사우스조지아 사우스샌드위치 제도";
$LANGS['cat_ES'] = "스페인";
$LANGS['cat_LK'] = "스리랑카";
$LANGS['cat_SD'] = "수단";
$LANGS['cat_SR'] = "수리남";
$LANGS['cat_SJ'] = "스발바르 얀마옌";
$LANGS['cat_SZ'] = "스와질란드";
$LANGS['cat_SE'] = "스웨덴";
$LANGS['cat_CH'] = "스위스";
$LANGS['cat_SS'] = "남수단";
$LANGS['cat_SY'] = "시리아";
$LANGS['cat_TW'] = "대만";
$LANGS['cat_TJ'] = "타지키스탄";
$LANGS['cat_TZ'] = "탄자니아";
$LANGS['cat_TH'] = "태국";
$LANGS['cat_TL'] = "동티모르";
$LANGS['cat_TG'] = "토고";
$LANGS['cat_TK'] = "토켈라우";
$LANGS['cat_TO'] = "통가";
$LANGS['cat_TT'] = "트리니다드 토바고";
$LANGS['cat_TN'] = "튀니지";
$LANGS['cat_TR'] = "터키";
$LANGS['cat_TM'] = "투르크메니스탄";
$LANGS['cat_TC'] = "터크스 케이커스 제도";
$LANGS['cat_TV'] = "투발루";
$LANGS['cat_UG'] = "우간다";
$LANGS['cat_UA'] = "우크라이나";
$LANGS['cat_AE'] = "아랍 에미리트";
$LANGS['cat_GB'] = "영국";
$LANGS['cat_US'] = "미국";
$LANGS['cat_UM'] = "미국령 군소 제도";
$LANGS['cat_UY'] = "우루과이";
$LANGS['cat_UZ'] = "우즈베키스탄";
$LANGS['cat_VU'] = "바누아투";
$LANGS['cat_VE'] = "베네수엘라";
$LANGS['cat_VN'] = "베트남";
$LANGS['cat_VG'] = "영국령 버진 아일랜드";
$LANGS['cat_VI'] = "미국령 버진 아일랜드";
$LANGS['cat_WF'] = "왈리스 퓌튀나";
$LANGS['cat_EH'] = "서사하라";
$LANGS['cat_YE'] = "예멘";
$LANGS['cat_ZM'] = "잠비아";
$LANGS['cat_ZW'] = "짐바브웨";

/* My Subscriptions */
$LANGS['newvideos'] = "새로운 비디오";

/* Account */
$LANGS['myaccount'] = "내 계정";
$LANGS['vidsfavs'] = "동영상, 즐겨찾기 및 재생 목록";
$LANGS['accountsettings'] = "계정 설정";
$LANGS['viewinghistory'] = "기록";
$LANGS['mychannel'] = "내 채널";
$LANGS['uploadedvideos'] = "업로드한 동영상";
$LANGS['new'] = "새로운";
$LANGS['playlist'] = "재생 목록";
$LANGS['videoupload'] = "동영상 업로드";
$LANGS['nosubvideos'] = "구독한 동영상이 없습니다...";
$LANGS['nofavvideos'] = "즐겨찾기한 동영상이 없습니다...";

/* My Videos */
$LANGS['sortby'] = "정렬 기준";
$LANGS['sorttitle'] = "제목";
$LANGS['sorttime'] = "시간";
$LANGS['sortdateadded'] = "추가 날짜";
$LANGS['sortviews'] = "조회수";
$LANGS['sortrating'] = "평점";
$LANGS['stattime'] = "시간";
$LANGS['statrating'] = "평점";
$LANGS['statbroadcast'] = "방송";
$LANGS['statrawfile'] = "원본 파일";
$LANGS['public'] = "공개";
$LANGS['private'] = "비공개";
$LANGS['live'] = "실시간!";
$LANGS['converting'] = "변환 중...";
$LANGS['uploading'] = "업로드 중...";
$LANGS['addvidsto'] = "동영상 추가";
$LANGS['play'] = "재생";
$LANGS['edit'] = "편집";
$LANGS['setasavatar'] = "섬네일을 아바타로 설정";
$LANGS['downloadmp4'] = "MP4 다운로드";
$LANGS['deleteconfirmation'] = "이 동영상을 삭제하시겠습니까?";
$LANGS['novideos'] = '업로드한 동영상이 없습니다. <a href="/my_videos_upload">지금 동영상을 업로드하세요</a>!';
$LANGS['nomyvideosresults'] = "검색 결과가 없습니다. 철자가 올바른지 확인하세요.";

/* Edit Video */
$LANGS['title'] = "제목";
$LANGS['desc'] = "설명";
$LANGS['privacy'] = "개인정보";
$LANGS['saveinfo'] = "정보 저장";
$LANGS['saveinfoconfirm'] = "동영상 정보를 변경하시겠습니까?";
$LANGS['viewchart'] = "차트 보기";
$LANGS['backtopreviouspage'] = "이전 페이지로 돌아가기";
$LANGS['editsavechanges'] = "변경 사항 저장";
$LANGS['editcancel'] = "취소";
$LANGS['videoinfo'] = "비디오 정보";
$LANGS['videothumbnail'] = "비디오 썸네일";
$LANGS['uploadthumbnail'] = "썸네일 업로드";
$LANGS['customthumbdesc'] = '사용자 정의 썸네일을 설정하려면 왼쪽에 있는 썸네일을 클릭하고 원하는 이미지 파일을 선택한 다음 "썸네일 업로드"를 클릭하세요.';
$LANGS['customthumbtitle'] = '이 썸네일을 변경하시겠습니까?';
$LANGS['customthumbinfo'] = '사용자 정의 썸네일은 파트너에게만 제공됩니다. 파트너 프로그램 가입의 장점과 요구 사항에 대해 더 알아보려면 아래 버튼을 클릭하세요.';
$LANGS['partnerreadmore'] = '더 읽기';
$LANGS['broadcastingoptions'] = '방송 및 공유 옵션';
$LANGS['publicdesc'] = "누구나 검색하고 보기 가능 - 권장됨";
$LANGS['privatedesc'] = "특정 BitView 사용자만 볼 수 있음";
$LANGS['allowcomments'] = "자동으로 댓글 허용";
$LANGS['allowfriendcomments'] = "친구만 댓글 작성 허용";
$LANGS['disablecomments'] = "댓글 허용하지 않음";
$LANGS['dateandmap'] = "날짜 및 지도";
$LANGS['clear'] = "지우기";
$LANGS['allowratings'] = '네, 다른 사람들이 이 비디오를 평가할 수 있도록 허용합니다.';
$LANGS['dontallowratings'] = '아니오, 이 비디오를 평가할 수 없도록 허용하지 않습니다.';

/* My Playlists */
$LANGS['addedpl'] = "추가됨";
$LANGS['frompl'] = "재생 목록";
$LANGS['nopl'] = "재생 목록을 찾을 수 없습니다....";

/* My Playlist */
$LANGS['playlistedit'] = "재생 목록 편집";
$LANGS['videourl'] = "동영상 URL";
$LANGS['add'] = "추가";
$LANGS['editinfo'] = "정보 편집";

/* Edit Playlist */
$LANGS['pledittitle'] = "재생 목록 편집";
$LANGS['pleditdesc'] = "재생 목록은 원하는대로 설정할 수 있는 동영상 모음입니다.";
$LANGS['cancel'] = "취소";

/* Create Playlist */
$LANGS['createplaylisttitle'] = "동영상 재생 목록 만들기";
$LANGS['createplaylist'] = "재생 목록 만들기";

/* View Playlist */
$LANGS['plpermalink'] = "재생목록/URL (퍼링크):";
$LANGS['sortcomments'] = "댓글";
$LANGS['unsorted'] = "미분류";
$LANGS['playallvideos'] = "모든 동영상 재생";

/* Inbox */
$LANGS['compose'] = "작성";
$LANGS['from'] = "보낸 사람";
$LANGS['subject'] = "제목";
$LANGS['date'] = "날짜";
$LANGS['allmsg'] = "모든 메시지";
$LANGS['msgcom'] = "댓글";
$LANGS['sentmsg'] = "보낸 메시지";
$LANGS['nomsg'] = "메시지가 없습니다...";
$LANGS['personalmessages'] = "개인 메시지";
$LANGS['sharedwithyouinbox'] = "당신과 공유";
$LANGS['friendinvitesinbox'] = "친구 초대";
$LANGS['videoresponsesinbox'] = "비디오 응답";
$LANGS['sent'] = "전송됨";
$LANGS['attachvideo'] = "비디오 첨부";
$LANGS['msgchannelcomment'] = "당신의 채널에 댓글";
$LANGS['msgcomment'] = "당신의 비디오에 댓글";
$LANGS['msgvideoresponse'] = "당신의 비디오에 대한 비디오 응답";
$LANGS['msgmention'] = "비디오에서 언급";
$LANGS['msgmentionchannel'] = "{channel} 채널에서 언급";

/* Address Book */
$LANGS['addressbook'] = "주소록";
$LANGS['allcontacts'] = "모든 연락처";
$LANGS['selectedcontacts'] = "선택한 연락처";
$LANGS['choosecontacts'] = "연락처 목록에서 선택하세요";
$LANGS['friendssince'] = "친구로 추가된 날짜";
$LANGS['friendsinvitenot'] = "친구 초대가 아직 수락되지 않았습니다";
$LANGS['friendstatus'] = "친구 상태";
$LANGS['unselect'] = "선택 해제";
$LANGS['unselectall'] = "모두 선택 해제";
$LANGS['nocontacts'] = "연락처 없음...";
$LANGS['selectacontact'] = "삭제하려면 적어도 하나의 연락처를 선택하세요!";
$LANGS['selectacontactmsg'] = "메시지를 보내려면 적어도 하나의 연락처를 선택하세요!";
$LANGS['selectonecompose'] = "한 번에 여러 연락처에게 메시지를 보낼 수 없습니다!<br>메시지를 보낼 연락처를 선택하세요.";

/* Insight */
$LANGS['insighttitle'] = "통찰력: 통계 및 데이터";
$LANGS['allvideos'] = "모든 비디오";
$LANGS['summary'] = "요약";
$LANGS['demographics'] = "인구 통계";
$LANGS['viewsdesc'] = "내 비디오가 얼마나 많은 조회수를 받고 있나요?";
$LANGS['demodesc'] = "내 채널에 가입한 사람들은 누구인가요?";
$LANGS['commdesc'] = "내 구독자들은 어디에 있나요?";
$LANGS['video'] = "비디오";
$LANGS['topvideos'] = "인기 비디오";
$LANGS['viewspercentage'] = "조회수 (&percnt; 전체)";
$LANGS['percentoftotalviews'] = "전체 조회수의 &percnt;";
$LANGS['searchmyvideos'] = "내 비디오 검색";
$LANGS['insufdemo'] = "인구 통계를 표시할 데이터가 충분하지 않습니다. 다른 시간 범위를 선택해 보세요.";
$LANGS['ageranges'] = "모든 성별 연령대";
$LANGS['genderranges'] = "모든 연령대 성별";
$LANGS['engdesc'] = "비디오에 댓글을 단, 좋아요를 누른 또는 평가한 사용자 수";
$LANGS['engagements'] = "커뮤니티 참여";
$LANGS['dailysubs'] = "일일 구독자";
$LANGS['daily'] = "일일";
$LANGS['total'] = "합계";
$LANGS['insightvideodesc'] = "이 비디오는 몇 번 시청되었나요?";
$LANGS['videototalviews'] = "총 조회수";
$LANGS['dailyviews'] = "일일 조회수";

/* Send Message */
$LANGS['messagecont'] = "메시지";
$LANGS['to'] = "받는 사람";
$LANGS['sendmessagebutton'] = "메시지 보내기";

/* Groups */
$LANGS['groups'] = "그룹";
$LANGS['joinedgroups'] = "가입한 그룹";
$LANGS['recentgroups'] = "최근 그룹";
$LANGS['mostmembers'] = "가장 많은 회원";
$LANGS['mostvideos'] = "가장 많은 동영상";
$LANGS['groupmostdiscussed'] = "가장 많이 논의된";
$LANGS['createagroup'] = "그룹 생성";
$LANGS['groupvideos'] = "동영상";
$LANGS['groupmembers'] = "회원";
$LANGS['discussions'] = "토론";
$LANGS['groupcreated'] = "생성됨";
$LANGS['nogroups'] = "그룹이 없습니다...";

/* Group */
$LANGS['jointhisgroup'] = "이 그룹 가입";
$LANGS['removerequest'] = "요청 제거";
$LANGS['leavegroup'] = "그룹 나가기";
$LANGS['moderation'] = "모더레이션";
$LANGS['viewallvideos'] = "모든 동영상 보기";
$LANGS['addvideo'] = "동영상 추가";
$LANGS['novideos'] = "동영상이 없습니다...";
$LANGS['nodiscussions'] = "토론이 없습니다...";
$LANGS['creatediscussion'] = "토론 생성";
$LANGS['topostatopic'] = "주제를 게시하려면.";
$LANGS['topic'] = "주제";
$LANGS['author'] = "작성자";
$LANGS['replies'] = "답변";
$LANGS['lastpost'] = "마지막 게시물";
$LANGS['viewallmembers'] = "모든 회원 보기";
$LANGS['owner'] = "소유자";
$LANGS['grouptype'] = "유형";
$LANGS['instantjoin'] = "즉시 가입";
$LANGS['approvalrequired'] = "승인 필요";
$LANGS['groupurl'] = "URL";
$LANGS['deletediscussion'] = "토론 삭제";
$LANGS['postreply'] = "답글 작성";
$LANGS['post'] = "게시";
$LANGS['accept'] = "수락";
$LANGS['decline'] = "거절";

/* Group Moderation */
$LANGS['groupmoderation'] = "그룹 모더레이션";
$LANGS['approvemembers'] = "회원 승인";
$LANGS['approvevideos'] = "동영상 승인";
$LANGS['yes'] = "예";
$LANGS['no'] = "아니오";
$LANGS['changeinfo'] = "정보 변경";
$LANGS['changeimage'] = "이미지 변경";
$LANGS['image'] = "이미지";
$LANGS['styling'] = "스타일링";
$LANGS['cssdesc'] = "불법적인 내용이나 그래픽을 가진 배경이나 이미지는 계정 종료로 이어질 수 있습니다.";
$LANGS['updatecss'] = "CSS 업데이트";
$LANGS['groupmessage'] = "메시지";
$LANGS['sendmessagetomembers'] = "회원에게 메시지 보내기";
$LANGS['delgroup'] = "그룹 삭제";

/* Submit Group Video */
$LANGS['submitvideotitle'] = "그룹에 동영상 제출";
$LANGS['submitvideo'] = "동영상 제출";

/* Create Group */
$LANGS['groupname'] = "그룹 이름";
$LANGS['groupimage'] = "그룹 이미지";
$LANGS['creategroup'] = "그룹 생성";
$LANGS['creategroupdesc'] = "그룹을 통해 다른 회원들과 토론을 할 수 있으며 다른 사람들과 쉽게 동영상을 공유할 수 있습니다.";

/* Create Group Discussion */
$LANGS['discussiontitle'] = "토론 제목";
$LANGS['creatediscussiondesc'] = "토론은 그룹 내에서 주제에 대해 토론하는 부분입니다.";

/* Search Results */
$LANGS['resultspre'] = ""; /* Explanation: Use if the search query goes before "results". Example: "Resultados para search" in Spanish. If your language doesn't use this, leave it empty like this: ''*/
$LANGS['resultspost'] = " 결과"; /* Explanation: Use if "BitView" goes after the username. Example: "search results" in English. If your language doesn't use this, leave it empty like this: '' */
$LANGS['relevance'] = '관련성';
$LANGS['viewcount'] = '조회수';
$LANGS['searchrating'] = '평점';
$LANGS['newest'] = '최신순';
$LANGS['nochannelsfound'] = '채널이 없습니다...';
$LANGS['noplfound'] = '재생 목록이 없습니다...';
$LANGS['nogroupsfound'] = '그룹이 없습니다...';
$LANGS['uploaded'] = '업로드됨';
$LANGS['anytime'] = '언제나';
$LANGS['partnervideos'] = '파트너 비디오';
$LANGS['resultcount'] = '결과 {r} / 전체 {t}';
$LANGS['searchoptions'] = '검색 옵션';
$LANGS['resulttype'] = '결과 유형';
$LANGS['duration'] = '길이';
$LANGS['durshort'] = '짧은 (~4분)';
$LANGS['durlong'] = '긴 (15분 이상)';
$LANGS['features'] = '기능';
$LANGS['novideosfoundfor'] = '다음을 위한 비디오를 찾을 수 없습니다';
$LANGS['noresultsfoundfor'] = '다음을 위한 결과를 찾을 수 없습니다';


/* Profile */
$LANGS['channelsuspended'] = '이 계정은 정지되었습니다.';
$LANGS['accountnotfound'] = '이 계정을 찾을 수 없습니다.';
$LANGS['channel'] = '채널';
$LANGS['friends'] = '친구';
$LANGS['channelsubscribers'] = '구독자';
$LANGS['linkcomments'] = '댓글';
$LANGS['bulletins'] = '소식지';
$LANGS['editchannel'] = '채널 편집';
$LANGS['type'] = '유형';
$LANGS['joined'] = '가입일';
$LANGS['videoswatched'] = '시청한 동영상';
$LANGS['channelviews'] = '채널 조회수';
$LANGS['age'] = '나이';
$LANGS['gender'] = '성별';
$LANGS['male'] = '남성';
$LANGS['female'] = '여성';
$LANGS['nonbinary'] = 'Non-Binary';
$LANGS['status'] = '상태';
$LANGS['single_m'] = '독신';
$LANGS['single_f'] = '독신';
$LANGS['taken_m'] = '연애 중';
$LANGS['taken_f'] = '연애 중';
$LANGS['married_m'] = '기혼';
$LANGS['married_f'] = '기혼';
$LANGS['country'] = '국가';
$LANGS['website'] = '웹사이트';
$LANGS['hobbies'] = '관심사 및 취미';
$LANGS['music'] = '음악';
$LANGS['movies'] = '영화 및 TV 프로그램';
$LANGS['books'] = '책';
$LANGS['mostsub'] = '가장 많은 구독자';
$LANGS['report'] = '신고';
$LANGS['pfpviolation'] = '프로필 이미지 위반';
$LANGS['connectwith'] = '연결하기';
$LANGS['profilesendmessage'] = '메시지 보내기';
$LANGS['messagetoyourself'] = '자기 자신에게 메시지를 보낼 수 없습니다!';
$LANGS['logintomessage'] = '메시지를 보내려면 로그인하세요!';
$LANGS['addcomment'] = '댓글 추가';
$LANGS['logintocommentchannel'] = '댓글을 작성하려면 로그인하세요!';
$LANGS['sharechannel'] = '채널 공유';
$LANGS['addfriend'] = '친구 추가';
$LANGS['retractinvite'] = '친구 초대 철회';
$LANGS['removefriend'] = '친구 삭제';
$LANGS['notfriendyourself'] = '자기 자신을 친구로 추가할 수 없습니다!';
$LANGS['logintofriend'] = '친구를 추가하려면 로그인하세요!';
$LANGS['blockuser'] = '사용자 차단';
$LANGS['channelembed'] = '채널 임베드';
$LANGS['recentratings'] = '최근 활동';
$LANGS['seeall'] = '모두 보기';
$LANGS['writebulletin'] = '소식지 작성';
$LANGS['bulletin'] = '소식지';
$LANGS['subvideos1'] = '구독하기: ';
$LANGS['subvideos2'] = '의 동영상';
$LANGS['plvideos'] = '동영상';
$LANGS['playall'] = '모두 재생';
$LANGS['featuredchannels'] = '추천 채널';
$LANGS['channelcomments'] = '채널 댓글';
$LANGS['bggraphic'] = '배경 그래픽';
$LANGS['reportthisuser'] = '이 사용자를 신고합니다.';
$LANGS['norecentratings'] = '최근 활동이 없습니다...';
$LANGS['nosubscribers'] = '구독자가 없습니다...';
$LANGS['nosubscriptions'] = '구독한 채널이 없습니다...';
$LANGS['nofriends'] = '친구가 없습니다...';
$LANGS['nobulletins'] = '소식지가 없습니다...';
$LANGS['novideoschannel'] = '동영상이 없습니다...';
$LANGS['nofavs'] = '즐겨찾기한 동영상이 없습니다...';
$LANGS['noplchannel'] = '재생 목록이 없습니다...';
$LANGS['pvideos'] = '비공개 동영상';
$LANGS['pvideosallow'] = '이 동영상을 볼 수 있는 권한이 없습니다...';
$LANGS['plvideoamount'] = '동영상';
$LANGS['bulletinpost'] = '소식지 게시';
$LANGS['deletebulletin'] = '소식지 삭제';
$LANGS['body'] = '내용';
$LANGS['bulletincomments'] = '소식지 댓글';
$LANGS['tocommentbulletin'] = '댓글을 작성하려면 로그인하세요!';
$LANGS['addacomment'] = '댓글 작성:';
$LANGS['postreplychannel'] = '답글 작성';
$LANGS['writecomment'] = '댓글 작성';
$LANGS['for'] = '대상:';
$LANGS['commentdesc'] = '채널 댓글은 사용자의 채널에 표시됩니다.';
$LANGS['postbulletin'] = '소식지 게시';
$LANGS['writeabulletin'] = '소식지 작성';
$LANGS['bulletindesc'] = '소식지는 자신과 친구의 채널 페이지에 표시됩니다.';
$LANGS['sharingoptions'] = '공유 옵션';
$LANGS['sharingoptionsdesc'] = '이 채널을 공유하는 두 가지 방법이 있습니다.';
$LANGS['sharingoptions1'] = '1. 링크를 복사하여 이메일이나 즉시 메시지로 보냅니다.';
$LANGS['sharingoptions2'] = '2. 컴퓨터의 이메일 프로그램을 사용하여 이 채널을 보냅니다.';
$LANGS['clicktosend'] = '보내려면 클릭하세요!';
$LANGS['honorless'] = '없음';
$LANGS['activitycomment'] = '댓글을 남겼습니다';
$LANGS['activityfavorite'] = '비디오를 즐겨찾기에 추가했습니다';
$LANGS['activityrating'] = '비디오를 평가했습니다:';
$LANGS['activityupload'] = '새로운 비디오를 업로드했습니다';
$LANGS['activityfriend'] = '친구가 되었습니다';
$LANGS['activitysubscription'] = '구독했습니다';
$LANGS['next'] = "다음";
$LANGS['previous'] = "이전";
$LANGS['settings'] = "설정";
$LANGS['themescolors'] = "테마 및 색상";
$LANGS['channelmodules'] = "모듈";
$LANGS['videosandpl'] = "동영상 및 재생 목록";
$LANGS['revert'] = "되돌리기! 이전 채널로 돌아가기";
$LANGS['all'] = "모두";
$LANGS['uploads'] = "업로드";
$LANGS['channelpl'] = "재생 목록";
$LANGS['backtoplaylists'] = "재생 목록으로 돌아가기";
$LANGS['searchuploads'] = "업로드 검색";
$LANGS['info'] = "정보";
$LANGS['viewcomments'] = "댓글, 관련 동영상 등 보기";
$LANGS['seeallcommentsandresponses'] = "모든 댓글 및 동영상 응답 보기";
$LANGS['pastethislink'] = "이 링크를 이메일이나 인스턴트 메시지에 붙여넣으세요";
$LANGS['selectplaylist'] = "재생 목록 선택";
$LANGS['profilemsg'] = '채널 뷰어들은 여기에 "구독" 및 "친구로 추가"와 같은 링크를 볼 것입니다.';
$LANGS['profile'] = '프로필';
$LANGS['profilechangessaved'] = '변경 사항이 저장되었습니다.';
$LANGS['posting'] = '게시 중...';
$LANGS['name'] = '이름';
$LANGS['totaluploadviews'] = '총 업로드 조회수';
$LANGS['channeldesc'] = '채널 설명';
$LANGS['hometown'] = '고향';
$LANGS['occupation'] = '직업';
$LANGS['companies'] = '회사';
$LANGS['schools'] = '학교';
$LANGS['interests'] = '관심사';
$LANGS['movies'] = '영화';
$LANGS['featuredchannelsdefault'] = '위의 "편집"을 클릭하여 연결하려는 채널을 입력하십시오.';
$LANGS['featuredchannelsdesc'] = '채널에 표시할 목적지 채널을 최대 4개까지 쉼표로 구분하여 나열하십시오. 채널을 나열하지 않으면이 상자가 채널에 나타나지 않습니다.';
$LANGS['backtochannel'] = "{c}의 채널로 돌아가기";
$LANGS['refresh'] = "새로고침";
$LANGS['whichcontent'] = "어떤 콘텐츠를 표시하시겠습니까?";
$LANGS['myuploadedvideos'] = "내 업로드 동영상";
$LANGS['myfavorites'] = "내 즐겨찾기";
$LANGS['alsoshowall'] = '"모두" 보기도 표시';
$LANGS['featuredvideo'] = '주요 동영상';
$LANGS['usemostrecent'] = '주요 집합에서 가장 최근의 동영상 사용';
$LANGS['autoplayfeatured'] = "주요 동영상 자동 재생";
$LANGS['areyousure'] = "계속하시겠습니까?";
$LANGS['unsavedchanges'] = "테마를 변경하시겠습니까? 저장되지 않은 변경 사항이 손실됩니다.";
$LANGS['showadvancedoptions'] = "고급 옵션 표시";
$LANGS['hideadvancedoptions'] = "고급 옵션 숨기기";
$LANGS['general'] = "일반";
$LANGS['colorpalettes'] = "색 팔레트";
$LANGS['font'] = "글꼴";
$LANGS['wrappercolor'] = "랩퍼 색상";
$LANGS['wrappertextcolor'] = "랩퍼 텍스트 색상";
$LANGS['wrapperlinkcolor'] = "랩퍼 링크 색상";
$LANGS['wrappertransparency'] = "랩퍼 투명도";
$LANGS['repeatbackground'] = "배경 반복";
$LANGS['titletextcolor'] = "제목 텍스트 색상";
$LANGS['bodytextcolor'] = "본문 텍스트 색상";
$LANGS['transparency'] = "투명도";
$LANGS['bgimgdesc'] = "채널에서 배경으로 표시 될 이미지를 업로드하십시오 (최대 2MB).";
$LANGS['channeltype'] = "채널 유형";
$LANGS['channeltags'] = "채널 태그";
$LANGS['commaseparated'] = "(쉼표로 구분)";
$LANGS['channeltagsdesc'] = "태그는 다른 사람들이 채널을 찾는 데 도움이되는 키워드입니다.";

/* My Profile page */
$LANGS['myprofiledesc'] = '이 페이지에는 BitView 채널의 모든 설정이 포함되어 있습니다.';
$LANGS['profileimages'] = '프로필 사진';
$LANGS['avatar'] = '아바타';
$LANGS['backgroundimage'] = '배경 이미지';
$LANGS['deleteimage'] = '이미지 삭제';
$LANGS['channelinformation'] = '채널 정보';
$LANGS['genderrelationprivate'] = '비공개';
$LANGS['fctitle'] = 'F.C. 타이틀';
$LANGS['relationship'] = '관계';
$LANGS['birthday'] = '생일';
$LANGS['showage'] = '나이 표시';
$LANGS['aboutme'] = '자기 소개';
$LANGS['emailprefs'] = '이메일 설정';
$LANGS['emailpm'] = '개인 메시지로 이메일 받기';
$LANGS['emailcomm'] = '동영상 댓글로 이메일 받기';
$LANGS['emailsub'] = '주간 구독 하이라이트로 이메일 받기';
$LANGS['layoutprefs'] = '레이아웃 설정';
$LANGS['bgcolor'] = '배경 색상';
$LANGS['bgfixed'] = '고정';
$LANGS['bgrepeat'] = '반복';
$LANGS['norepeat'] = '반복 없음';
$LANGS['repeat'] = '반복';
$LANGS['repeatx'] = 'X축 반복';
$LANGS['repeaty'] = 'Y축 반복';
$LANGS['bgposition'] = '위치';
$LANGS['top'] = '상단';
$LANGS['middle'] = '가운데';
$LANGS['bottom'] = '하단';
$LANGS['fontcolor'] = '글꼴 색상';
$LANGS['titlefontcolor'] = '타이틀 글꼴 색상';
$LANGS['linkcolor'] = '링크 색상';
$LANGS['hlfontcolor'] = '하이라이트 글꼴 색상';
$LANGS['hlheadercolor'] = '하이라이트 헤더';
$LANGS['hlinsidecolor'] = '하이라이트 내부';
$LANGS['headercolor'] = '일반 헤더';
$LANGS['insidecolor'] = '일반 내부';
$LANGS['font'] = '채널 글꼴';
$LANGS['featuredvideobox'] = '추천 동영상 상자';
$LANGS['subscribersbox'] = '구독자 상자';
$LANGS['subscriptionsbox'] = '구독 상자';
$LANGS['friendsbox'] = '친구 상자';
$LANGS['bulletinsbox'] = '소식지 상자';
$LANGS['videosbox'] = '동영상 상자';
$LANGS['favoritesbox'] = '즐겨찾기 상자';
$LANGS['playlistsbox'] = '재생 목록 상자';
$LANGS['commentsbox'] = '댓글 상자';
$LANGS['ratingsbox'] = '최근 활동 상자';
$LANGS['partnersettings'] = '파트너 설정';
$LANGS['bannerimage'] = '배너 이미지';
$LANGS['minibannerimage'] = '미니 배너 이미지';
$LANGS['sideimage'] = '사이드 이미지';
$LANGS['recommendedsize'] = '권장 크기';
$LANGS['bannerlink'] = '배너 웹사이트';
$LANGS['sideimagelink'] = '사이드 이미지 웹사이트';
$LANGS['custombox'] = '사용자 정의 상자';
$LANGS['customboxtitle'] = '사용자 정의 상자 제목';
$LANGS['customboxcontent'] = '사용자 정의 상자 내용';
$LANGS['savechanges'] = '변경 사항 저장';
$LANGS['submitimage'] = '이미지 제출';
$LANGS['overview'] = '개요';
$LANGS['profilesetup'] = '프로필 설정';
$LANGS['playbacksetup'] = '재생 설정';
$LANGS['emailoptions'] = '이메일 옵션';
$LANGS['manageaccount'] = '계정 관리';
$LANGS['chvideoviews'] = '동영상 조회수';
$LANGS['change'] = "변경";
$LANGS['mynetwork'] = "내 네트워크";
$LANGS['contacts'] = "연락처";
$LANGS['chvideocomments'] = "동영상 댓글";
$LANGS['chmore'] = "더 보기";
$LANGS['changepicture'] = "프로필 사진 변경";
$LANGS['changepicturedesc'] = "JPG, BMP 또는 PNG 파일을 업로드할 수 있습니다. 유명인, 노출, 아트워크 또는 저작권 보호 이미지가 포함 된 사진은 업로드하지 마십시오. 이미지는 88px x 88px 정사각형으로 표시됩니다. <b>최대 파일 크기는 2MB입니다.</b>";
$LANGS['describeyourself'] = "자기소개";
$LANGS['personaldetails'] = "개인 정보";
$LANGS['jobscareer'] = "직업 / 경력";
$LANGS['education'] = "교육";
$LANGS['videoplaybackquality'] = "동영상 재생 품질";
$LANGS['videoplaybackqualitydesc'] = "동영상 보기의 기본 설정 선택";
$LANGS['alwayshd'] = "동영상 항상 HD 품질로 재생";
$LANGS['neverhd'] = "동영상을 결코 HD 품질로 재생하지 않음";
$LANGS['currentemail'] = "현재 이메일 주소";
$LANGS['changeemailaddress'] = "이메일 주소 변경";
$LANGS['changeemail'] = "이메일 변경";
$LANGS['partnerimages'] = "파트너 이미지";
$LANGS['partnerimagelinks'] = "파트너 이미지 링크";
$LANGS['accountstatuscg'] = "계정 상태: 커뮤니티 가이드라인";
$LANGS['accountstatuscopy'] = "계정 상태: 저작권";
$LANGS['changeusername'] = "사용자 이름 변경";
$LANGS['changepassword'] = "비밀번호 변경";
$LANGS['deleteaccount'] = "계정 삭제";
$LANGS['goodaccount'] = "귀하의 계정은 정상입니다.";
$LANGS['accountstrike'] = "경고 {s}회가 있습니다. 조심하세요!";
$LANGS['accountstrikes'] = "경고 {s}회가 있습니다. 조심하세요!";
$LANGS['cannotchangeusername'] = "아직 사용자 이름을 변경할 수 없습니다! 기다려주세요 ";
$LANGS['usernamechangedesc'] = "사용자 이름은 매년 한 번만 변경할 수 있으므로 새로운 사용자 이름을 신중히 선택하세요.";
$LANGS['newusername'] = "새 사용자 이름";
$LANGS['currentpassword'] = "현재 비밀번호";
$LANGS['newpassword'] = "새 비밀번호";
$LANGS['confirmnewpassword'] = "새 비밀번호 확인";
$LANGS['enterpassword'] = "보안상의 이유로 비밀번호를 입력하세요";

/* Upload page */
$LANGS['uploadpagetitle'] = '동영상 업로드';
$LANGS['step1of2'] = '2단계 중 1단계';
$LANGS['step2of2'] = '2단계 중 2단계';
$LANGS['videocategory'] = '동영상 카테고리';
$LANGS['tagsdesc'] = '태그는 동영상을 찾는 데 도움이 되는 키워드입니다.<br> <i>(쉼표로 구분)</i>';
$LANGS['requiredfield'] = '(* 표시는 필수 항목임)';
$LANGS['datemapoptions'] = '날짜 및 지도 옵션';
$LANGS['optional'] = '(선택 사항)';
$LANGS['chooseoptions'] = '옵션 선택';
$LANGS['lessoptions'] = '옵션 감추기';
$LANGS['addressrecorded'] = '주소 기록됨';
$LANGS['uploadcontinue'] = '동영상 업로드...';
$LANGS['file'] = '파일';
$LANGS['broadcastoptions'] = '방송 옵션';
$LANGS['uploadvideo'] = '동영상 업로드';
$LANGS['needfilevideotoupload'] = '업로드할 동영상 파일을 선택해주세요!';
$LANGS['aboutuploading'] = '업로드에 대하여...';
$LANGS['uploaddesc1'] = '업로드는 고속 연결에서 1-5분 정도 소요되며, 동영상 변환에는 몇 분이 소요됩니다.';
$LANGS['videolimit1'] = '동영상은 100MB로 제한됩니다. 동영상의 최대 길이는 15분입니다.';
$LANGS['videolimit2'] = '동영상은 2GB로 제한됩니다. 동영상의 최대 길이는 15분입니다.';
$LANGS['partnervideolimit1'] = '동영상은 100MB로 제한됩니다. 동영상의 최대 길이는 30분입니다.';
$LANGS['partnervideolimit2'] = '동영상은 2GB로 제한됩니다. 동영상의 최대 길이는 30분입니다.';
$LANGS['myvideosdesc'] = '업로드 후에는 페이지 상단의 "<a href="/my_videos">내 동영상</a>" 링크에서 언제든지 동영상을 편집하거나 삭제할 수 있습니다.';
$LANGS['newuploader'] = '새로운 동영상 업로더 사용';
$LANGS['olduploader'] = '기존 동영상 업로더 사용';
$LANGS['videoadded'] = '동영상이 성공적으로 추가되었습니다!';
$LANGS['videoaddeddesc'] = '동영상이 현재 처리 중이며, 몇 분 후에 볼 수 있게 될 것입니다.';
$LANGS['thankyou'] = '감사합니다';
$LANGS['sharelink'] = '동영상 링크 공유! 아래를 복사하여 붙여넣으세요:';
$LANGS['embedlink'] = '동영상을 웹사이트에서 직접 재생하세요! 다음 코드 조각을 복사하여 붙여넣으세요:';
$LANGS['allrequiredinfo'] = '필수 항목을 모두 입력해주세요!';

/* Partners */

$LANGS['partnerhead'] = '파트너십';
$LANGS['partnertitle'] = 'BitView와 함께 파트너가 되세요';
$LANGS['partnerdesc'] = '좋은 동영상과 성장하는 관객을 보유하고 계신가요? BitView의 파트너 프로그램을 통해 다음 수준으로 이동하는 데 도움을 받아보세요.';
$LANGS['applynow'] = '지금 신청하기';
$LANGS['contentpartners'] = '콘텐츠 파트너';
$LANGS['partnerbenefits'] = '파트너 혜택';
$LANGS['partnerbenefitsdesc'] = 'BitView 파트너가 되는 것에는 많은 혜택이 있습니다. 일부 혜택은 다음과 같습니다:<br><br>- 브랜딩: 배너, 채널용 커스텀 상자 및 모든 동영상에 파트너 뱃지 등과 같은 커스텀 브랜딩으로 독특함을 부여하세요.<br><br>- 앞으로 더 많은 혜택을 제공할 예정입니다!';
$LANGS['qualificationsfaq'] = '자격 요건 및 FAQ';
$LANGS['qualificationsfaqdesc'] = 'BitView 파트너 프로그램에 자격을 얻으려면 일부 최소한의 기준을 충족해야 합니다:<br><br>- 온라인 스트리밍에 적합한 독자적인 동영상을 제작해야 합니다.<br><br>- 구독자 수가 75명 이상이어야 합니다.<br><br>- 계정이 <a href="/guidelines">커뮤니티 가이드라인</a>을 위반하지 않아야 합니다.';

/* Staff */
$LANGS['bvstaff'] = 'BitView 스태프';
$LANGS['bvstaffdesc'] = '이곳은 BitView 웹사이트를 운영하고 있거나 이전에 참여한 사람들의 목록입니다. 사용자들이 자유롭게 표현할 수 있도록 웹사이트를 유지하고 있습니다.';
$LANGS['owners'] = '소유자';
$LANGS['ownerdesc'] = 'BitView를 소유하고 있는 사람들입니다 - 놀라운 사실이죠.';
$LANGS['coowndev'] = '공동 소유자 및<br>개발자';
$LANGS['owndev'] = '소유자 및<br>개발자';
$LANGS['coownserver'] = '공동 소유자 및<br>서버 소유자/개발자';
$LANGS['modsanddevs'] = '모더레이터 및 개발자';
$LANGS['modsanddevsdesc'] = '웹사이트를 안전하고 깨끗하게 유지하는 사람들입니다. 계정에 문제가 있나요? 그들에게 문의하세요.';
$LANGS['moderator'] = '모더레이터';
$LANGS['moddev'] = '개발자 및<br>모더레이터';

$LANGS['lettertitle'] = '웹사이트에 도움을 준 모든 분들께 보내는 편지';
$LANGS['letter'] = "친애하는 BitView 공동 소유자, 개발자 및 모더레이터 여러분,<br><br>
BitView 전체 팀을 대표하여 깊은 감사의 말씀을 전하고 싶습니다. 여러분의 탁월한 헌신과 노고에 깊은 감동을 받고 있습니다. 소유자 중 한 명으로써, 우리의 비디오 공유 플랫폼의 성장과 성공을 목도하는 것은 여러분의 값진 기여 없이는 불가능했을 것입니다.
<br><br>
나머지 공동 소유자 분들께는 흔들림 없는 지원과 비전에 감사드립니다. 플랫폼의 발전과 개선에 대한 여러분의 헌신은 BitView.net을 오늘날과 같은 탁월한 커뮤니티로 만들어낸 데 결정적인 역할을 하였습니다. 여러분의 리더십과 전략적인 지도는 우리에게로 찾아온 도전과 기회를 잘 처리하는 데 매우 중요한 역할을 해 왔습니다.
<br><br>
재능 있는 개발자 분들께는 여러분의 기술적 전문성과 혁신적인 아이디어로 BitView를 첨단 플랫폼으로 변화시켰다는 점에 깊은 감사를 표합니다. 여러분이 코딩, 문제 해결, 기능 구현에 투여한 수많은 시간은 사용자 경험을 향상시키고 우리의 플랫폼을 창의성과 엔터테인먼트의 중심지로 만들었습니다. 사이트의 기능과 성능을 개선하기 위한 여러분의 헌신은 정말로 칭찬할 만합니다.
<br><br>
노력하는 모더레이터 분들께는 우리 커뮤니티의 정직성과 안전을 지키기 위해 깊은 감사의 말씀을 전합니다. 규칙과 지침을 엄격하게 시행하고, 예의 바른 상호 작용을 보장하며, 발생하는 문제에 신속하게 대응하는 여러분의 경계심은 모든 사용자를 위한 환영하는 분위기 조성에 중요한 역할을 하였습니다. BitView를 건설적인 참여와 긍정적인 콘텐츠를 위한 공간으로 유지하는 노력은 매우 칭찬할 만합니다.
<br><br>
하나로 통합된 팀으로, 우리는 상당한 성과를 이루었고 다양한 어려움을 극복해 왔습니다. BitView의 성공은 각자의 노력과 열정이 탁월한 팀이 가져온 결과입니다. 우리의 공유된 비전에 대한 여러분의 헌신은 진정으로 영감을 주었으며, 이러한 탁월한 개인들과 함께할 수 있어 감사합니다.
<br><br>
계속해서 성장하고 발전함에 있어서 우리가 형성한 유대를 소중히 여기며, 우리 작은 사이트를 정의하는 가치에 헌신하도록 합시다. 함께 우리는 그 향수 여행을 계속 진행하며 창작자들이 자신의 재능을 선보일 수 있는 플랫폼을 제공할 것입니다.
<br><br>
다시 한번, 공동 소유자, 개발자 및 모더레이터 여러분께 헌신적인 업적, 전문성 및 흔들림 없는 지원에 대해 감사의 말씀을 전합니다. 여러분의 노고가 간과되지 않았으며, 이 탁월한 팀의 일부가 될 수 있어서 대단히 자랑스럽습니다.
<br><br>
계속해서 자유롭게 표현하세요,<br>
<3 vistafan12";
$LANGS['backtobitview'] = "BitView로 돌아가기";

/* My Friends */
$LANGS['myfriends'] = '나의 친구들';
$LANGS['invites'] = '초대장';
$LANGS['myinvites'] = '내 초대장';
$LANGS['incominginvites'] = '들어오는 초대장';
$LANGS['noinvites'] = '초대장이 없습니다...';
$LANGS['actions'] = '동작';
$LANGS['retract'] = '철회';

/* History */
$LANGS['clearhistory'] = "시청 기록 지우기";
$LANGS['noviewinghistory'] = "시청 기록이 없습니다.";

/* QuickList */
$LANGS['playquicklist'] = "빠른 재생 목록 재생";
$LANGS['clearquicklist'] = "빠른 재생 목록 지우기";
$LANGS['noquicklist'] = "빠른 재생 목록에 동영상이 없습니다.";
$LANGS['noquicklistdesc'] = "빠른 재생 목록을 사용하면 나중에 시청할 동영상 목록을 작성할 수 있습니다. 동영상의 왼쪽 아래에 있는 \"+\"를 클릭하여 해당 동영상을 빠른 재생 목록에 추가할 수 있습니다. 목록을 보려면 시청 중인 동영상 아래에 빠른 재생 목록 막대를 찾으세요.";
$LANGS['quicklistcleared'] = "빠른 재생 목록이 성공적으로 지워졌습니다.";
$LANGS['addedtoquicklist'] = "빠른 재생 목록에 추가됨";


/* About */
$LANGS['aboutus'] = '회사 소개';
$LANGS['abouttitle'] = '비트뷰(BitView)란 무엇인가요?';
$LANGS['aboutdesc'] = '비트뷰는 당신에게 중요한 사람들에게 동영상을 전달하는 방법입니다. 비트뷰를 통해 다음과 같은 일들을 할 수 있습니다:';
$LANGS['about1'] = '세계에 가장 좋아하는 동영상을 자랑할 수 있습니다.';
$LANGS['about2'] = '강아지, 고양이 및 기타 애완동물의 동영상을 촬영할 수 있습니다.';
$LANGS['about3'] = '디지털 카메라나 휴대폰으로 찍은 동영상을 블로그에 올릴 수 있습니다.';
$LANGS['about4'] = '친구와 가족들에게 안전하고 비공개로 동영상을 보여줄 수 있습니다.';
$LANGS['about5'] = '... 그리고 더 많은 것들을 할 수 있습니다!';
$LANGS['aboutsignup'] = '<a href="/signup">지금 가입</a>하여 무료 계정을 만드세요.';
$LANGS['abouthelp'] = '더 많은 정보를 알고 싶으시면 <a href="help">도움말</a> 섹션을 참조하세요.';
$LANGS['aboutmail'] = '문의 사항이 있으시면 언제든지 <a href="mailto:bitview@vistafan12.eu.org">bitview@vistafan12.eu.org</a>로 문의해주세요.';

/* Community Guidelines */
$LANGS['bvguidelines'] = 'BitView 커뮤니티 지침';
$LANGS['cgtitle1'] = 'BitView 커뮤니티를 존중하세요';
$LANGS['cgtitle2'] = '선을 넘지 마세요';
$LANGS['cgtitle3'] = '이 지침을 우리는 시행합니다';
$LANGS['cgtitle4'] = 'BitView는 커뮤니티를 위한 공간입니다';
$LANGS['cgtitle5'] = '커뮤니티 지침 팁';
$LANGS['cgdesc1'] = '우리는 수녀, 노인 및 뇌외과 의사에게 보이는 예의를 요구하지 않습니다. 사이트를 남용하지 마십시오. BitView의 모든 멋진 새로운 커뮤니티 기능은 특정 수준의 신뢰를 필요로 합니다. 우리는 당신이 책임을 지리라 믿으며, 수백만 명의 사용자들이 그 신뢰를 존중합니다. 당신도 이 중 한 명이 되어 주십시오.';
$LANGS['cgdesc2'] = '다음은 곤란을 피하도록 도와줄 상식적인 규칙 몇 가지입니다:';
$LANGS['cgdesc3'] = '이 규칙들을 진지하게 받아들이고 심각하게 생각해주세요. 규칙의 구멍을 찾거나 규칙을 피해보려 하거나 변명하려 하지 마십시오. 단순히 그 규칙들을 이해하고 만들어진 의도를 존중하려 노력하십시오. 더 자세한 정보가 필요하다면, <a href="#tips">커뮤니티 지침 팁</a>을 확인해주십시오.';
$LANGS['cgdesc4'] = '이건 당신보다는 우리에 관한 내용입니다. BitView 직원들은 매일 24시간, 주 7일 동안 신고된 비디오를 검토하여 커뮤니티 지침을 위반하는지 여부를 판단합니다. 위반 사항이 확인되면 해당 비디오를 삭제합니다. 때로는 비디오가 커뮤니티 지침을 위반하지 않을 수 있지만 모두에게 적합하지 않을 수 있습니다. 이러한 비디오는 연령 제한이 걸릴 수 있습니다. 커뮤니티 지침 위반 시 계정에 제재가 가해지며 심각한 경우 또는 반복되는 위반은 계정 해지로 이어질 수 있습니다. 계정이 해지되면 새 계정을 만들 수 없습니다. 커뮤니티 지침이 어떻게 시행되며 위반 시 어떤 결과가 발생하는지에 대한 자세한 내용은 도움말 센터를 방문하여 확인하십시오.';
$LANGS['cgdesc5'] = '이것이 당신의 커뮤니티입니다! BitView의 모든 사용자가 사이트를 만드는데 기여하고 있습니다. 따라서 손을 놓고 관여하는 것을 두려워하지 마십시오!';
$LANGS['cgdesc6'] = '여기까지입니다! 읽어주셔서 감사합니다!';
$LANGS['cgdesc7'] = '커뮤니티 지침의 한계와 예외에 대한 더 많은 통찰력이 필요하신가요? 도움이 될만한 예시와 팁을 제공합니다:';
$LANGS['rule1'] = 'BitView는 음란물이나 성적으로 의도된 콘텐츠에 적합한 공간이 아닙니다. 이러한 콘텐츠가 당신의 비디오를 설명하는 내용이라 하더라도 BitView에 올리지 마십시오. 또한 우리는 법 집행기관과 긴밀하게 협력하며 아동 학대를 신고합니다.';
$LANGS['rule2'] = '동물 학대, 약물 남용, 미성년자 음주 및 흡연, 폭탄 제작 등 나쁜 내용을 보여주는 비디오를 게시하지 마십시오.';
$LANGS['rule3'] = '그래픽 또는 과도한 폭력은 허용되지 않습니다. 비디오가 누군가를 신체적으로 다치게 하거나 공격하거나 굴욕시키는 내용을 보여준다면 게시하지 마십시오.';
$LANGS['rule4'] = 'BitView는 충격적인 사이트가 아닙니다. 사고, 시체 또는 충격이나 혐오를 일으킬 의도로 비디오를 게시하지 마십시오.';
$LANGS['rule5'] = '저작권을 존중하세요. 당신이 만든 비디오나 권한을 가진 비디오만 업로드하십시오. 다른 사람이 저작권을 가지고 있는 콘텐츠를 업로드하지 마십시오. 이는 음악 트랙, 저작권이 있는 프로그램의 일부 또는 다른 사용자가 만든 비디오와 같은 콘텐츠를 권한 없이 사용하는 것을 포함합니다.';
$LANGS['rule6'] = '우리는 표현의 자유를 존중하며 누구나 비인기적인 견해를 표현할 권리를 지킵니다. 그러나 우리는 혐오 발언(인종 또는 민족 출신, 종교, 장애, 성별, 연령, 군인 지위 및 성 정체성/성별 식별에 기반한 집단을 공격하거나 모욕하는 발언)을 허용하지 않습니다. 이는 긍정적으로 극단적 이념을 선전하는 것에도 해당합니다.';
$LANGS['rule7'] = '폭행적인 행동, 스토킹, 위협, 괴롭힘, 협박, 사생활 침해, 다른 사람의 개인 정보 노출 및 폭력적인 행위를 부추기거나 이용하여 이용 약관을 위반하도록 선동하는 행위는 심각하게 받아들여집니다. 이러한 행위를 범하는 사용자는 BitView에서 영구히 차단될 수 있습니다.';
$LANGS['rule8'] = '누구나 스팸을 싫어합니다. 조회수를 늘리기 위해 오도한 설명, 태그, 제목 또는 썸네일을 만들지 마십시오. 목표 없이나 반복적인 콘텐츠, 댓글 및 개인 메시지를 포함하여 대량의 비목표 지향형 또는 원치 않는 콘텐츠를 게시하는 것은 허용되지 않습니다.';
$LANGS['rule9'] = '웹사이트를 안전하게 유지합시다. 소유하지 않는 계정을 무차별적으로 공격하려 하지 마십시오. 또한 계정의 로그인 정보를 공개적으로 공유하는 것은 허용되지 않습니다.';
$LANGS['rule10'] = '다중 계정은 허용되지 않습니다. 우리는 비디오 및 채널에서 진정한 수치를 원합니다. 비디오와/또는 댓글을 평가하는 데 여러 계정을 사용하지 마십시오. 여러 계정을 사용하여 자신에게 구독하는 것도 허용되지 않습니다.';
$LANGS['rule11'] = '이 규칙 중 하나를 어기고 계정이 중단된 경우, 이 처벌을 회피하는 것이 허용되지 않습니다. 중단된 사용자가 만든 새 계정은 자동으로 삭제됩니다.';
$LANGS['cglist1'] = '이 사이트에서 즐거움을 느껴보세요. 볼 거리가 많고 놀라운 콘텐츠를 만드는 많은 사람들이 있습니다. 그 중에는 당신도 있을 수 있습니다! 장비가 점점 저렴해지고 사용하기 쉬워지고 있으니 꽉 끼워 들어가서 즐기세요.';
$LANGS['cglist2'] = '당신의 생각을 다른 사람들에게 알려주세요. 피드백은 경험의 일부이며, 존중을 가지고 행하는 경우 친구를 사귈 수 있는 좋은 방법일 수 있습니다. 댓글을 남기고 비디오를 평가하며, 영향을 받은 비디오에 대한 당신만의 응답을 만들어보거나 관심 있는 대회에 참여하세요. 다양한 활동과 참여 방법이 많이 있습니다.';
$LANGS['cglist3'] = '당신이 본 모든 것을 좋아하지는 않을 수 있습니다. 여기에 있는 내용 중 일부가 당신을 불쾌하게 할 수 있습니다. 우리의 이용 약관을 위반하는 내용으로 판단된다면 시청 중인 비디오 아래에 "신고"라는 버튼을 클릭하여 BitView 직원의 검토를 받을 수 있습니다. 그렇지 않다면, 단순히 다른 내용을 클릭하는 것도 고려해보세요. 좋아하지 않는 비디오를 시청하는 시간을 낭비하는 대신 다른 비디오를 시청하는 것이 어떨까요?';
$LANGS['thebitviewteam'] = '— BitView 팀';
$LANGS['cgcat1'] = '성적 콘텐츠 및 노출';
$LANGS['cgcat2'] = '혐오 발언';
$LANGS['cgcat3'] = '충격적 및 혐오스러운';
$LANGS['cgcat4'] = '위험한 불법 행위';
$LANGS['cgcat5'] = '어린이';
$LANGS['cgcat6'] = '저작권';
$LANGS['cgcat7'] = '사생활';
$LANGS['cgcat8'] = '괴롭힘';
$LANGS['cgcat9'] = '사칭';
$LANGS['cgcat10'] = '협박';
$LANGS['cgcat1desc'] = '대부분의 노출은 특히 성적 맥락에서 허용되지 않습니다. 일반적으로 성적으로 자극적인 비디오는 BitView에서 허용되지 않을 가능성이 높습니다. 일부 교육적, 다큐멘터리 및 과학적 콘텐츠에는 예외가 있지만 그 콘텐츠의 목적이 되는 유일한 경우에만 허용되며 과도한 그래픽을 가지고 있어서는 안 됩니다. 예를 들어, 유방암에 대한 다큐멘터리는 적절하지만 다큐멘터리에서 벗어난 클립을 문맥 없이 게시하는 것은 그렇지 않을 수 있습니다. 이는 애니메이션 콘텐츠에도 적용됩니다.';
$LANGS['cgcat2desc'] = '"혐오 발언"은 보호되는 집단의 구성원에 대한 증오를 선동하는 콘텐츠를 나타냅니다. 예를 들어 인종적 또는 성별적 콘텐츠는 혐오 발언으로 간주될 수 있습니다. 때로는 어떤 것이 혐오 발언으로 간주되는지와 그렇지 않은지의 경계가 모호할 수 있습니다. 예를 들어 일반적으로 한 나라를 비판하는 것은 허용되지만 특정 국적의 사람들에 대한 모욕적인 일반화를 하는 것은 허용되지 않습니다.';
$LANGS['cgcat3desc'] = '세상은 위험한 곳입니다. 때로는 사람들이 다치기도 하며 이러한 사건이 BitView에서 문서화될 수 있습니다. 그러나 주로 충격, 감동 또는 경멸을 위한 것으로 의도된 폭력적이거나 무지개무늬한 콘텐츠를 게시하는 것은 허용되지 않습니다. 비디오가 특히 혐오스럽거나 불쾌할 경우 추가적인 문맥과 정보로 균형을 잡아야 합니다. 예를 들어 도축장에서의 클립을 공장 농업에 관한 비디오에 포함시키는 것은 적절할 수 있습니다. 그러나 무리한 목적으로 동물들이 학살당하는 비디오를 무리하게 연결하면 그 목적이 단순히 충격을 주기 위한 것이라면 과도할 수 있습니다.';
$LANGS['cgcat4desc'] = '시청자들이 반응으로 어떤 행동을 취할 수도 있는 가능성 때문에 어떤 콘텐츠를 보여주지 않아야 하는 것은 공정하지 않을 수 있습니다. 그러나 우리는 폭력을 부추기거나 심각한 신체적 손상이나 사망의 내재적 위험을 동반하는 위험한 불법 행위를 조장하려는 의도로 하는 콘텐츠에 한계를 두고 있습니다. 이는 폭탄 제작, 닌자 암살자 훈련, 저격수 공격, 테러리스트 훈련 비디오 또는 불법 스트리트 레이싱에 관한 비디오와 같은 것을 포함합니다. 이러한 내용의 표현은 교육적이거나 다큐멘터리적이어야 하며 다른 사람들이 이를 모방하거나 돕거나 장려하도록 디자인되지 않아야 합니다.';
$LANGS['cgcat5desc'] = '어린이(18세 미만의 모든 사람)가 참여하는 비디오는 특히 민감합니다. 어린이가 나타나는 비디오는 절대로 성적 매력을 표현하거나 폭력적이지 않아야 합니다. 어린이가 등장하는 내용을 게시할 때 신중해야 합니다. 개인적인 순간이나 가정 비디오를 공유하는 경우 해당 비디오를 비공개 비디오로 만들어서 가족과 친구만 볼 수 있게 할 수 있습니다. 또한 <a href="/terms">이용 약관</a>에 동의함으로써 당신이 13세 이상인 것을 확인합니다. 미성년자 사용자의 계정은 중단됩니다.';
$LANGS['cgcat6desc'] = '당신이 무언가를 창작하면 그것의 저작권을 소유합니다. 마찬가지로 다른 사람들이 콘텐츠를 만들 때 그들은 그에 대한 저작권을 가질 수 있습니다. 창조적인 커뮤니티로서 BitView의 모든 사용자가 다른 사람들의 저작권을 존중하는 것이 중요합니다. 만약 어떤 것이 누군가의 저작권을 위반할지 확실하지 않다면, 가장 안전한 방법은 완전히 독창적인 콘텐츠를 만드는 것입니다. 자신이 만든 이미지와 오디오로 완전히 독창적인 것을 만드는 것이 가장 좋습니다.';
$LANGS['cgcat7desc'] = '사생활은 중요하며 존중되어야 합니다. 비디오에 개인 정보를 게시하지 마십시오. 이는 전화번호, 주소, 신용카드 정보, 사회 보장 번호 등을 포함합니다. 또한 다른 사람의 사적인 정보를 게시하지 마십시오. 만약 다른 사람의 동의 없이 다른 사람의 비디오를 게시하려면 그들이 비디오를 제거하도록 요청하는 것이 매우 중요합니다.';
$LANGS['cgcat8desc'] = 'BitView는 모든 사용자의 안전과 원활한 경험을 보장하기 위해 노력하고 있습니다. 다른 사람을 괴롭히거나 협박하려는 의도가 있는 내용을 게시하지 마십시오. 다른 사용자를 존중하고 온라인 공동체에서 긍정적인 기여를 할 수 있도록 노력하십시오.';
$LANGS['cgcat9desc'] = '다른 사람들을 사칭하여 개인 정보를 빼낸다거나 누군가를 혼란스럽게 하려고 하는 행동은 허용되지 않습니다. BitView에서는 다른 사람들을 속이거나 사칭하는 행위가 금지되어 있습니다. 자신의 신분을 나타내는 것이 중요한 경우 실제 정보를 제공하십시오.';
$LANGS['cgcat10desc'] = '누군가를 위협하거나 협박하거나 겁먹게 하는 행동은 BitView에서 허용되지 않습니다. 다른 사용자를 존중하고 친근한 환경을 조성하는 데 기여하십시오. 언제나 긍정적으로 상호 작용하십시오.';

/* Contests */
$LANGS['monthlycontest'] = "월간 대회";
$LANGS['monthlycontestschedule'] = "월간 비디오 대회 일정";
$LANGS['whatisit'] = "이것은 무엇인가요?";
$LANGS['thismonthcontest'] = "이번 달";
$LANGS['lastmonthwinners'] = "지난 달 우승자";
$LANGS['howtoenter'] = "어떻게 참가하나요?";
$LANGS['whowins'] = "누가 우승하나요?";
$LANGS['whowinsdesc'] = "우승자는 비트뷰 스태프에 의해 달의 끝에서 결정됩니다.";
$LANGS['theprize'] = "상은?";
$LANGS['theprizedesc'] = "명예, 부와 모든 이들의 부러움을 얻게 됩니다.";
$LANGS['contestsuggestion'] = '월간 비디오 대회에 대한 제안이 있나요? <a href="mailto:bitview@vistafan12.eu.org">저희에게 알려주세요</a>.';

/* Help */
$LANGS['q1'] = 'Q: 어떻게 동영상을 공유하고 웹사이트에서 링크를 할 수 있나요?';
$LANGS['a1'] = 'A: <a href="/sharing">동영상 공유 및 링크하는 방법</a>';
$LANGS['q2'] = 'Q: 어떤 종류의 동영상을 업로드할 수 있나요?';
$LANGS['a2'] = 'A: 세계와 공유하고 싶은 모든 종류의 개인 동영상을 업로드할 수 있습니다. 우리는 노출 불량 및 모든 대중에게 적합한 동영상만 허용합니다.
<br/>
<br/>
하지만, 이것은 여전히 창의성을 위한 충분한 공간을 남깁니다!! 당신은 <a href="results?search=dog&t=Search+Videos">개</a> 또는 <a href="/results?search=cat&t=Search+Videos">고양이</a>를 소유하고 있나요? <a href="/results?search=mexico&t=Search+Videos">멕시코</a>에서 휴가를 다녀오셨나요? <a href="/results?search=netherlands&t=Search+Videos">네덜란드</a>에 사시나요?
<br/>
<br/>
이것은 우리 사용자들이 업로드하는 동영상의 일부 예시에 불과합니다. 결국, 당신이 가장 잘 알고 있습니다. 당신은 어떤 동영상을 촬영하고 싶으신가요?';
$LANGS['q3'] = 'Q: 동영상의 길이는 얼마나 될까요?';
$LANGS['a3'] = 'A: 동영상은 15분 이내이어야 하며 크기는 2GB 미만이어야 합니다 (구형 브라우저를 사용할 경우 100MB).';
$LANGS['q4'] = 'Q: 어떤 비디오 파일 형식을 업로드할 수 있나요?';
$LANGS['a4'] = 'A: BitView는 .WMV, .AVI, .MOV, .MPG, .MP4 파일 형식의 대부분의 디지털 카메라와 휴대폰에서 비디오 파일을 허용합니다.';
$LANGS['q5'] = 'Q: 동영상을 어떻게 개선할 수 있을까요?';
$LANGS['a5'] = 'A: <a href="https://windows-movie-maker-vista.en.softonic.com/" target="_blank">Windows Movie Maker</a> (Windows 설치 시 함께 제공) 또는 <a href="https://www.apple.com/lae/imovie/" target="_blank">Apple iMovie</a>와 같은 소프트웨어를 사용하여 동영상을 편집하고 배경 음악 등을 추가할 수 있습니다.';
$LANGS['q6'] = 'Q: 동영상에 대한 저작권 및 기타 법적 권리는 누구에게 있나요?';
$LANGS['a6'] = 'A: 네. 동영상에 대한 모든 권리는 여러분에게 있습니다. BitView는 여러분의 자료에 대한 저작권을 가지지 않습니다.';
$LANGS['q7'] = 'Q: 저작권 침해에 대한 정책은 어떻게 되나요?';
$LANGS['a7'] = "A: BitView는 저작권 소유자와 출판사의 권리를 존중하며, 모든 필요한 권리를 소지한 사람들에게만 동영상 업로드를 허용합니다. 저작권법 디지털 밀레니엄 저작권법 (DMCA)을 준수하는 모든 저작권 침해 통지에 대해 대응하는 것이 정책입니다. 만약 저희가 여러분이 제출한 콘텐츠가 다른 당사자의 저작권을 침해한다는 통지를 받거나 다른 이유로 여러분의 콘텐츠가 저작권을 침해한다고 판단하면, 여러분의 계정이 종료되고 비디오가 BitView에서 삭제될 수 있습니다.";
$LANGS['q8'] = 'Q: 저작권 침해를 신고하는 방법은 어떻게 되나요?';
$LANGS['a8'] = 'A: 다른 사람이 여러분의 저작권으로 보호되는 콘텐츠를 허가 없이 업로드했다고 믿으신다면, 해당 사람과 직접 해결하도록 권장합니다. 또는 지원팀에 <a href="mailto:bitview@vistafan12.eu.org">이메일</a>을 보내 저희와 연락할 수 있습니다.';
$LANGS['q9'] = 'Q: 저작권 침해로 잘못 신고받은 경우 어떻게 되나요?';
$LANGS['a9'] = "A: BitView에서 여러분의 비디오 콘텐츠 중 저작권 침해에 대한 신고를 받으면 알려드립니다. 적절한 대응 방법에 대해 여러분에게 기회를 드립니다.";
$LANGS['q10'] = 'Q: 여러분은 정책을 위반하는 콘텐츠가 BitView에 표시되지 않도록 하기 위해 무엇을 하고 있나요?';
$LANGS['a10'] = 'A: 업로드된 동영상에 대해 우리는 수동 및 자동화된 과정을 통해 사전 검토를 진행합니다. 우리는 정책을 위반하는 콘텐츠나 명백한 저작권 침해 콘텐츠를 탐지하고 제거하기 위해 최선을 다하지만, 우리의 검토 과정은 주로 성인 콘텐츠 또는 명백한 저작권 침해 사항을 제거하는 데 중점을 두고 있으며, 완벽하지 않을 수 있습니다. 그러나 우리는 시청자들이 정책 위반 또는 저작권 문제를 발견한 경우 알려주도록 권장하며, 정책 위반 신고에 대한 검토 과정이 있으며 디지털 밀레니엄 저작권법에 따라 저작권 침해 신고에 대응합니다.';
$LANGS['q11'] = 'Q: 디스코드 서버나 트위터가 있나요?';
$LANGS['a11'] = '네! 실제로 우리는 디스코드 서버와 트위터를 가지고 있습니다. 디스코드 서버에 참여하려면 <a href="https://discord.gg/wgGaqCmwuQ">여기를 클릭</a>하고, 트위터에서 우리를 팔로우할 수 있습니다 <a href="https://twitter.com/bitview_">여기에서</a>.';
$LANGS['q12'] = "Q: BitView에서 구식 브라우저를 사용하고 있어 동영상을 시청할 수 없습니다. 어떻게 해야 하나요?";
$LANGS['activate'] = '활성화';
$LANGS['deactivate'] = '비활성화';
$LANGS['flashdisclaimer'] = "<b>참고:</b> BitView의 Flash 플레이어는 호환성 옵션으로 제공됩니다. 브라우저가 BitView의 HTML5 플레이어를 지원하는 경우 이 옵션을 활성화하지 않아도 됩니다.";

/* BitView on your site */
$LANGS['bvsitetitle1'] = "기본 사항";
$LANGS['bvsitetitle2'] = "API 및 사용자 참여";
$LANGS['bvsitedesc1'] = '인터넷 상에서 웹 사이트, 블로그, 소셜 네트워크 페이지 또는 거의 모든 것에 BitView를 통합하는 방법은 많습니다. 간단한 비디오 삽입부터 전체 기능을 갖춘 API까지, 기술적 능력 수준에 관계없이 다양한 수준에서 비디오를 통합할 수 있습니다.';
$LANGS['bvsitedesc2'] = 'BitView를 사이트에 통합하는 것은 BitView에서 사용 가능한 수천 개의 비디오 중 일부를 추가하는 것 이상입니다. 이렇게 하면 방문자의 흥미를 유지하고, 자기 표현 및 즐겨 사용하는 서비스 중 하나와의 상호 작용을 가능하게 합니다. 그리고 이는 여러분의 사이트, 블로그 또는 페이지를 BitView 비디오 커뮤니티로 끌어들이며, 전 세계의 사용자, 창작자 및 온라인 비디오의 거대한 컬렉션을 통해 연결된 국제 네트워크로 이어집니다.';
$LANGS['bvsitedesc3'] = "아래에 비디오 콘텐츠를 통합하는 일반적인 방법 몇 가지를 강조했습니다. 질문 옆의 화살표를 클릭하여 답변을 얻을 수 있습니다. 궁금한 사항이나 제안사항이 있거나 알려주고 싶은 프로젝트가 있는 경우, <a href='https://discord.gg/wgGaqCmwuQ'>Discord 서버</a>에 질문을 남겨주시기 바랍니다.";
$LANGS['bvsitesectiontitle1'] = "블로그나 웹 페이지에 비디오를 추가하는 방법은 어떻게 되나요?";
$LANGS['bvsitesectiontitle2'] = "소셜 네트워크 페이지에 비디오를 추가하는 방법은 어떻게 되나요?";
$LANGS['bvsitesectiontitle3'] = "대형 블로그/웹 회사에서 사용자 참여를 어떻게 높일 수 있나요?";
$LANGS['bvsitesectiontitle4'] = "우리 사이트에는 우리 고유의 비디오가 있습니다. 이 비디오를 BitView를 통해 사이트에 게시할 수 있나요?";
$LANGS['bvsitesection1desc1'] = "블로그 게시물이나 페이지의 HTML을 편집해야 합니다. 이것은 비교적 간단할 것입니다. 예를 들어 Blogger에서는 &quot;HTML 편집&quot; 탭을 클릭하면 됩니다.";
$LANGS['bvsitesection1desc2'] = "다음으로 원하는 비디오로 이동하고, &quot;About This Video&quot; 섹션의 '임베드' 상자를 찾으십시오. 거기에 있는 HTML 코드를 웹 사이트에 복사하면 임베드된 플레이어가 생성됩니다. 사용자가 '재생' 버튼을 클릭할 때 비디오가 사이트 내에서 재생됩니다.";
$LANGS['bvsitesection1desc3'] = "<em>object width=&quot;425&quot;</em> 및 <em>height=&quot;350&quot;</em> 필드를 임베드된 플레이어 코드의 시작과 끝에서 편집하여 플레이어 크기를 조정할 수 있습니다. 선택한 크기가 기본값과 동일한 비율을 가져야 하므로, 높이를 구할 때 너비를 0.8235로 곱하면 됩니다.";
$LANGS['bvsitesection2desc1'] = "SpaceHey와 같은 소셜 네트워크 프로필에 비디오를 추가하는 것은 친구들과 비디오나 즐겨 찾는 항목을 공유하는 좋은 방법입니다. 또는 SpaceHey에서 밴드와 같은 것을 홍보하는 경우 비디오는 방문자를 페이지로 유치하는 데 도움이 되며, 방문자들은 그 후에 이 링크를 친구들과 공유할 수 있습니다. 소셜 네트워크 사이트에도 비디오를 추가하는 유사한 방법이 있으므로 여기서는 SpaceHey를 예시로 사용하겠습니다.";
$LANGS['bvsitesection2desc2'] = 'SpaceHey 프로필에 로그인한 후 "프로필 편집" 버튼을 클릭하십시오.';
$LANGS['bvsitesection2desc3'] = "다음으로 원하는 비디오로 이동하고, &quot;About This Video&quot; 섹션의 '임베드' 상자를 찾으십시오. 거기에 있는 HTML 코드를 웹 사이트에 복사하면 임베드된 플레이어가 생성됩니다.";
$LANGS['bvsitesection2desc4'] = "<em>object width=&quot;425&quot;</em> 및 <em>height=&quot;350&quot;</em> 필드를 임베드된 플레이어 코드의 시작과 끝에서 편집하여 플레이어 크기를 조정할 수 있습니다. 선택한 크기가 기본값과 동일한 비율을 가져야 하므로, 높이를 구할 때 너비를 0.8235로 곱하면 됩니다.";
$LANGS['bvsitesection2desc5'] = '"미리보기"를 클릭한 다음 "제출"을 클릭하십시오.';
$LANGS['bvsitesection3desc1'] = "비디오는 텍스트보다 더 많은 참여를 유도합니다. 사용자를 더 많이 유치하고 그들을 더 오래 사이트에 머무르게 합니다. BitView는 인터넷 비디오 콘텐츠의 큰 저장소와 비디오 추가를 더 쉽게 만드는 검색, 재생 및 API 도구를 제공합니다.";
$LANGS['bvsitesection3desc2'] = "참여를 높이려면 비디오를 논의를 시작하거나 사용자들에게 맥락을 제공하는 방법으로 댓글을 작성하여 코멘터리를 작성하는 방법을 시도해보세요:";
$LANGS['bvsitesection4desc1'] = "무료로 자체 비디오로 사이트를 확장하는 것은 매우 쉽습니다. 먼저 비디오를 BitView에 업로드하면 됩니다. 비용은 청구되지 않으며, 호스팅 및 스트리밍 비용도 커버됩니다. 사이트의 사용자 참여를 높이는 훌륭한 방법일 뿐만 아니라 매우 쉽고 무료입니다.";
$LANGS['bvsitesection4desc2'] = "비디오를 업로드한 후 사이트로 다시 가져올 수 있습니다:";
$LANGS['bvsitesection4desc3'] = "<b>비디오를 하나씩 임베드하기:</b> 사이트에 넣을 비디오를 선택한 후 비디오 플레이어 옆에 있는 '임베드' 상자를 찾으십시오. 거기에 있는 HTML 코드를 블로그에 복사하면 임베드된 플레이어가 생성됩니다. 사용자가 '재생' 버튼을 클릭할 때 비디오가 사이트 내에서 재생됩니다.";

/* RSS Feeds */
$LANGS['rsstitle1'] = "RSS 피드란 무엇인가요?";
$LANGS['rsstitle2'] = "RSS 피드에 접근하는 방법";
$LANGS['rsstitle3'] = "BitView의 RSS 피드 구독 방법";
$LANGS['rssdesc1'] = "RSS(Really Simple Syndication)는 콘텐츠 배포 및 연합에 사용되는 XML 기반 형식입니다. RSS 피드를 구독하면 웹 사이트를 주기적으로 확인하지 않고도 원하는 온라인 콘텐츠 소스로부터 사용자 정의 및 최신 정보를 수신할 수 있습니다.";
$LANGS['rssdesc2'] = "원하는 웹 사이트에서 RSS 피드를 표시하는 뉴스 리더는 구독한 RSS 피드를 확인하고 각 피드에서 새 항목을 표시합니다. 컴퓨터용 뉴스 리더 애플리케이션을 다운로드하거나 Google 리더 및 Bloglines와 같은 인기 있는 웹 기반 뉴스 리더도 사용할 수 있습니다. 일부 웹 브라우저 및 이메일 애플리케이션에도 내장된 RSS 기능이 있습니다.";
$LANGS['rssdesc3'] = "많은 뉴스 리더 목록은 <a href='http://en.wikipedia.org/wiki/List_of_feed_aggregators'>위키피디아 ( ENG )</a>에서 확인할 수 있습니다.";
$LANGS['rssdesc4'] = "BitView는 카테고리별 비디오 그룹(예: 최근 업로드된 비디오, 최상위 조회수 등)을 위한 여러 RSS 피드 및 사용자 및 태그를 위한 사용자 정의 피드를 제공합니다.";
$LANGS['rssdesc5'] = "비디오 카테고리 그룹을 구독하려면 원하는 카테고리(예: &quot;<a href='/browse'>오늘의 최상위 조회수</a>&quot;)로 이동하십시오. 그런 다음 주황색 'RSS' 버튼을 클릭하십시오. 이렇게 하면 선택한 뉴스 리더가 구독을 추가하도록 할 것입니다.";
$LANGS['rssdesc6'] = "웹 브라우저에 RSS 기능이 있는 경우 피드를 여기에 추가할 수 있습니다. 명령은 브라우저마다 다를 수 있지만 보통 '파일' 또는 '즐겨찾기' 메뉴에서 찾을 수 있으며 '이 페이지 구독' 또는 '새 라이브 북마크'와 같은 이름일 것입니다.";
$LANGS['rssthispage'] = "이 페이지의 RSS 피드";

/* TestView */
$LANGS['testviewdesc'] = "환영합니다. 이곳은 TestView, 아이디어를 시험해보는 창작 공간입니다. BitView 엔지니어와 개발자들이 완전히 완성되지 않은 레시피와 시험 요리를 테스트하며, 여러분께 그 진행 상황을 알려드립니다. 어떻게 진행되고 있는지 알려주세요.";
$LANGS['flashvideo'] = "플래시 비디오";
$LANGS['flashvideodesc'] = "HTML5 비디오를 지원하지 않는 브라우저인가요? 걱정하지 마세요! 플래시 플레이어를 사용해보세요.";
$LANGS['feather'] = "Feather";
$LANGS['featherdesc'] = "매우 낮은 지연 페이지에서 BitView 비디오를 시청해보세요.";
$LANGS['tryitout'] = "시험해보세요";
$LANGS['disabletest'] = "비활성화";
$LANGS['timemachine'] = "타임 머신";
$LANGS['timemachinedesc'] = "시간을 되돌아가서 BitView의 각 날짜를 2000년대 후반으로 되감습니다.";
$LANGS['lightsout'] = "라이츠 아웃";
$LANGS['lightsoutdesc'] = "화면에서 가장 밝은 흰색이 지겨우시다면? 화면을 검정색으로 칠하고 새로운 멋진 인터페이스를 시도해보세요.";
$LANGS['featherenabled'] = '"Feather"가 활성화되었습니다!';
$LANGS['timemachineenabled'] = '"타임 머신"이 활성화되었습니다!';
$LANGS['lightsoutenabled'] = '"라이츠 아웃"이 활성화되었습니다!';
$LANGS['featherdisabled'] = '"Feather"가 비활성화되었습니다!';
$LANGS['timemachinedisabled'] = '"타임 머신"이 비활성화되었습니다!';
$LANGS['lightsoutdisabled'] = '"라이츠 아웃"이 비활성화되었습니다!';

/* Footer */
$LANGS['youraccount'] = '내 계정';
$LANGS['inbox'] = '수신함';
$LANGS['footmore'] = '더 보기...';
$LANGS['helpinfo'] = '도움말 및 정보';
$LANGS['helpcenter'] = '도움말 센터';
$LANGS['ourtwitter'] = '우리의 Twitter';
$LANGS['ourdiscord'] = '우리의 Discord';
$LANGS['guidelines'] = '커뮤니티 가이드라인';
$LANGS['partnerships'] = '파트너십';
$LANGS['terms'] = '서비스 약관';
$LANGS['privacypolicy'] = '개인정보 보호 정책';
$LANGS['currentlanguage'] = '현재 언어';
$LANGS['showlanguages'] = '언어 표시';
$LANGS['setlanguagepref'] = '언어 설정';
$LANGS['programs'] = '프로그램';
$LANGS['developers'] = '개발자';
$LANGS['bitviewblog'] = 'BitView 블로그';
$LANGS['policy'] = '정책';
$LANGS['discover'] = '발견하기';
$LANGS['bvphone'] = '휴대전화에서 BitView';
$LANGS['bvsite'] = '사이트에 BitView';
$LANGS['bvrss'] = 'BitView RSS 피드';
$LANGS['mobile'] = '모바일';

