<?php
/* General stuff */
$LANGS['language'] = 'Norsk (bokmål)';
$LANGS['languageenglish'] = 'Norwegian (Bokmål)';
$LANGS['languagecode'] = 'nb_NO.UTF-8';
$LANGS['languagechange'] = 'Språket er satt til norsk (bokmål)';
$LANGS['numberformat'] = 1; /* If your language uses comma separators (example: 1,000,000), value will be 1. If it uses dots (example: 1.000.000) or doesn't use separators, value will be 0.*/

/* Language window */
$LANGS['welcometobitview'] = 'Velkommen til BitView!';
$LANGS['languagesuggestion'] = 'Foreslått språk (vi har satt din preferanse til dette):';
$LANGS['languagesuggestiondesc1'] = 'For å endre språkpreferansen din, bruk språkvelgeren i bunnteksten (slutten av siden).';
$LANGS['languagesuggestiondesc2'] = 'Klikk "OK" for å godta denne innstillingen, eller klikk "Avbryt" for å se nettstedet på engelsk.';

/* Time, dates, etc */
$LANGS['second'] = 'sekund';
$LANGS['minute'] = 'minutt';
$LANGS['hour'] = 'time';
$LANGS['day'] = 'dag';
$LANGS['week'] = 'uke';
$LANGS['month'] = 'måned';
$LANGS['year'] = 'år';
$LANGS['seconds'] = 'sekunder';
$LANGS['minutes'] = 'minutter';
$LANGS['hours'] = 'timer';
$LANGS['days'] = 'dager';
$LANGS['weeks'] = 'uker';
$LANGS['months'] = 'måneder';
$LANGS['years'] = 'år';
$LANGS['ago'] = '{t} siden';
$LANGS['january'] = 'januar';
$LANGS['february'] = 'februar';
$LANGS['march'] = 'mars';
$LANGS['april'] = 'april';
$LANGS['may'] = 'mai';
$LANGS['june'] = 'juni';
$LANGS['july'] = 'juli';
$LANGS['august'] = 'august';
$LANGS['september'] = 'september';
$LANGS['october'] = 'oktober';
$LANGS['november'] = 'november';
$LANGS['december'] = 'desember';
$LANGS['shorttimeformat'] = '%e %b %Y';
$LANGS['videotimeformat'] = '%e %B %Y';
$LANGS['longtimeformat'] = '%e %B %Y';
$LANGS['timehourformat'] = '%e %B %Y %I:%M %p';
$LANGS['myvideostimeformat'] = '%A, %e %b %Y, %I:%M:%S %p';
$LANGS['blogpostformat'] = '%A, %e %B %Y';
$LANGS['monthformat'] = '%B %Y';
$LANGS['timenumberformat'] = 'd/m/Y';

/* Header */
$LANGS['home'] = 'Hjem';
$LANGS['videos'] = 'Videoer';
$LANGS['channels'] = 'Kanaler';
$LANGS['community'] = 'Samfunnet';
$LANGS['search'] = 'Søk';
$LANGS['login'] = 'Logg inn';
$LANGS['or'] = 'eller';
$LANGS['signup'] = 'Opprett Konto';
$LANGS['logout'] = 'Logg Ut';
$LANGS['upload'] = 'Laste Opp';
$LANGS['subscriptions'] = 'Abonnementer';
$LANGS['history'] = 'Historie';
$LANGS['account'] = 'Konto';
$LANGS['myvideos'] = 'Mine Videoer';
$LANGS['favorites'] = 'Favoritter';
$LANGS['playlists'] = 'Spillelister';
$LANGS['help'] = 'Hjelp';
$LANGS['suggestions'] = 'Forslag';
$LANGS['quicklist'] = 'HurtigListe';
$LANGS['browse'] = 'Browse';
$LANGS['messagesmenu'] = 'Messages';

/* Homepage */
$LANGS['viewall'] = 'vis alle';
$LANGS['videoviews'] = 'visninger';
$LANGS['beingwatched'] = 'Videoer Som Blir Sett Nå';
$LANGS['featured'] = 'Utvalgte Videoer';
$LANGS['recommendedforyou'] = 'Anbefalt for deg';
$LANGS['mostpopular'] = 'Mest Populær';
$LANGS['inboxstats'] = 'Innboks og Statistikk';
$LANGS['profilesettings'] = 'kontoinnstillinger';
$LANGS['messages'] = 'Meldinger';
$LANGS['message'] = 'Melding';
$LANGS['comments'] = 'Kommentarer';
$LANGS['comment'] = 'Kommentar';
$LANGS['sharedwithyou'] = 'Shared with You';
$LANGS['sharedwithyousingular'] = 'Shared with You';
$LANGS['videoresponses'] = 'Video Responses';
$LANGS['videoresponse'] = 'Video Response';
$LANGS['friendinvites'] = 'Venneinvitasjoner';
$LANGS['friendinvite'] = 'Venneinvitasjon';
$LANGS['subscribers'] = 'Abonnenter';
$LANGS['subscriber'] = 'Abonnent';
$LANGS['totalviews'] = 'Totalt antall visninger';
$LANGS['sendmessage'] = 'sende melding';
$LANGS['whatsnew'] = "Hva er Nytt";
$LANGS['readmore'] = 'Les mer i bloggen vår';
$LANGS['videocontest'] = 'Videokonkurranse';
$LANGS['joincontest'] = 'Bli med i konkurransen nå!';
$LANGS['personalize'] = 'Vil du tilpasse denne hjemmesiden?';
$LANGS['signinnow'] = '<a href="/login">Logg Inn</a> eller <a href="/signup">Registrer</a> deg nå!';
$LANGS['nowconverting'] = "Denne videoen konverteres, vent noen minutter.";
$LANGS['modules'] = "Legg til / fjern moduler";
$LANGS['friendactivity'] = "Venneaktivitet";
$LANGS['customizehomepage'] = "Tilpass hjemmesiden";
$LANGS['customizethehomepage'] = "Tilpass hjemmesiden";
$LANGS['customizehomepagedesc'] = "Velg modulene du vil se på din tilpassede hjemmeside.";
$LANGS['displaypreferences'] = "Visningsinnstillinger";
$LANGS['thefeed'] = "Feeden";
$LANGS['thefeeddesc'] = "Kombiner alle modulene dine til én enkelt feed.";
$LANGS['friendactivitytitle'] = "Venneaktivitet – Kan folk se hva jeg gjør?";
$LANGS['friendactivitydesc'] = "Denne delen viser dine bekreftede venner handlingene du kringkaster offentlig i din nylige aktivitetshistorikk. Hvis du for eksempel favoritter en video, kan den nye favorittvideoen dukke opp i boksen for nylige aktiviteter på kanalen din, så vel som på vennenes hjemmesider.";
$LANGS['feedfeatured'] = "Utvalgt Video";
$LANGS['feedbeingwatched'] = "Video Blir Sett Nå";
$LANGS['feedrecommended'] = "Anbefalt Video";
$LANGS['homenosubscriptions'] = "Du har ikke abonnert på noen kanal ennå.";
$LANGS['homenosubscriptionsdesc'] = "Når du legger til nye abonnementer, viser vi opplastingene deres her på denne siden.";
$LANGS['homenofriendactivity'] = "Vennene dine har ikke vært aktive i det siste.";
$LANGS['homenofriendactivitydesc'] = "Du kan prøve å legge til noen venner. Deretter viser vi aktiviteten deres her på denne siden.";
$LANGS['homeediting'] = "Redigering";
$LANGS['homedisplay'] = "Vis som";
$LANGS['homerows'] = "Antall rader som skal vises";
$LANGS['gridview'] = "Rutenett Visning";
$LANGS['listview'] = "Liste Visning";

/* Page title */
$LANGS['hometitle'] = "{n}'s BitView";
$LANGS['channeltitle'] = "{n}'s Kanal";
$LANGS['signintitle'] = "Logg Inn";
$LANGS['historytitle'] = "Viser Historikk";
$LANGS['favtitle'] = "Favoritter";
$LANGS['pltitle'] = "Spillelister";
$LANGS['partnerprogram'] = "Partnerprogram";

/* Notifications */
$LANGS['searcherror'] = 'Søket ditt må være på minst 2 tegn!';
$LANGS['addvideoplaylist1'] = "Du har lagt til";
$LANGS['addvideoplaylist2'] = 'videoer i spillelisten din!';
$LANGS['addfavorite1'] = "Du satte";
$LANGS['addfavorite2'] = 'videoer som favoritt!';
$LANGS['groupdoesnotexist'] = "Denne gruppen eksisterer ikke!";
$LANGS['uploaddisabled'] = 'Opplasting er deaktivert for vedlikehold.';
$LANGS['10vidsday'] = 'Du kan ikke laste opp mer enn 10 videoer per dag! Prøv å laste opp i morgen.';
$LANGS['3mins'] = 'Vent 3 minutter til du laster opp en ny video!';
$LANGS['backgroundsuccess'] = 'Bakgrunnen er lastet opp!';
$LANGS['backgrounderror'] = 'Bakgrunnsbilde må være under 2MB og være en bildefil!';
$LANGS['backgrounddeleted'] = 'Bakgrunnen er slettet!';
$LANGS['bannersuccess'] = 'Banneret er lastet opp!';
$LANGS['bannererror'] = 'Bannerbilde må være under 2MB og være en bildefil!';
$LANGS['bannerdeleted'] = 'Banneret ditt er slettet!';
$LANGS['minibannersuccess'] = 'Minibanner er lastet opp!';
$LANGS['minibannererror'] = 'Minibannerbilde må være under 2MB og være en bildefil!';
$LANGS['minibannerdeleted'] = 'Minibanneret ditt er slettet!';
$LANGS['sideimagesuccess'] = 'Sidebilde er lastet opp!';
$LANGS['sideimageerror'] = 'Sidebilde må være under 2MB og være en bildefil!';
$LANGS['sideimagedeleted'] = 'Sidebilde er slettet!';
$LANGS['avatarsuccess'] = 'Avatar er lastet opp!';
$LANGS['avatarerror'] = 'Avatarbildet må være under 1 MB og være en bildefil!';
$LANGS['avatardeleted'] = '"Avataren har blitt slettet!';
$LANGS['changessaved'] = 'Endringene ble lagret!';
$LANGS['profilesdisabled'] = 'Profiler er deaktivert for vedlikehold.';
$LANGS['bulletinposted'] = 'Bulletin er lagt ut!';
$LANGS['channelcommentsent'] = 'Kanalkommentar er sendt inn!';
$LANGS['somethingwentwrong'] = 'Noe gikk galt!';
$LANGS['replysubmitted'] = 'Svar er sendt inn!';
$LANGS['onlyonecomment'] = 'Du kan bare legge igjen én kommentar!';
$LANGS['vpnbrowser'] = "Du kan ikke bruke en VPN til å opprette en BitView-konto!";
$LANGS['torbrowser'] = "Du kan ikke bruke TOR til å opprette en BitView-konto!";
$LANGS['captchaincorrect'] = "Du skrev ikke inn koden riktig.";
$LANGS['toomanyaccounts'] = 'Du har for mange kontoer!';
$LANGS['banned2times'] = "Du har blitt utestengt 2 ganger allerede. Du kan ikke opprette flere kontoer!";
$LANGS['nohistory'] = "Du har ikke sett noen videoer under denne økten ennå!";
$LANGS['historycleared'] = 'Seerloggen din er slettet.';
$LANGS['watchdisabled'] = 'Videovisning er deaktivert for vedlikehold.';
$LANGS['videonotexist'] = 'Denne videoen eksisterer ikke eller har blitt fjernet på grunn av brudd på vilkårene for bruk.';
$LANGS['responseerror'] = 'Noe gikk galt med videosvaret ditt! Vennligst sjekk URL på nytt.';
$LANGS['responseexist'] = 'Video er allerede forespurt!';
$LANGS['responseadded'] = 'Videosvar ble lagt til!';
$LANGS['responseaccepted'] = 'Godkjent ny videorespons!';
$LANGS['60secscomment'] = 'Vent 60 sekunder før du legger til en ny kommentar!';
$LANGS['plnotexist'] = "Denne spillelisten eksisterer ikke!";
$LANGS['positionnotexist'] = "Denne stillingen eksisterer ikke!";
$LANGS['positionchanged'] = "Videoens posisjon endret!";
$LANGS['invalidurl'] = 'Ugyldig URL!';
$LANGS['videopladded'] = 'Video ble lagt til!';
$LANGS['videoalreadyinpl'] = 'Denne videoen er allerede i denne spillelisten!';
$LANGS['plvideoremoved'] = 'Videoen er fjernet!';
$LANGS['plinfochanged'] = 'Spillelisteinformasjon ble endret!';
$LANGS['pltitleneeded'] = 'Du må angi en tittel for spillelisten!';
$LANGS['flashenabled'] = 'Adobe Flash Player aktivert!';
$LANGS['flashdisabled'] = 'Adobe Flash Player deaktivert!';
$LANGS['messagesent'] = 'Meldingen er sendt!';
$LANGS['usernotexist'] = "Denne brukeren eksisterer ikke!";
$LANGS['nocriteria'] = "Du oppfyller ikke de nødvendige kriteriene!";
$LANGS['alreadypartner'] = 'Du har allerede blitt akseptert i partnerprogrammet!';
$LANGS['alreadyapplied'] = 'Du har allerede søkt!';
$LANGS['applicationsent'] = 'Søknaden din er sendt inn!';
$LANGS['joinedgroup'] = 'Du ble med i gruppen!';
$LANGS['leftgroup'] = 'Du har forlatt gruppen!';
$LANGS['grouprequest'] = 'Du har sendt en gruppeforespørsel! Nå må du vente på at det blir akseptert.';
$LANGS['groupdeleted'] = 'Gruppen er slettet!';
$LANGS['groupvideoadded'] = 'Video er sendt inn!';
$LANGS['groupvideoalreadyadded'] = 'Du har allerede sendt inn denne videoen!';
$LANGS['groupvideonotowned'] = "Du eier ikke denne videoen!";
$LANGS['3groups'] = 'Du kan bare eie opptil 3 grupper!';
$LANGS['groupnameempty'] = 'Gruppenavn kan ikke stå tomt!';
$LANGS['groupdescempty'] = 'Gruppebeskrivelsen kan ikke stå tom!';
$LANGS['groupnoimage'] = 'Du må laste opp et bilde for gruppen din!';
$LANGS['groupimageerror'] = 'Gruppebilder må være under 1 MB og være en bildefil!';
$LANGS['groupcreated'] = 'Gruppen er opprettet!';
$LANGS['urlnotvalid'] = "Dette er ikke en gyldig video-URL!";
$LANGS['discussiondeleted'] = 'Emnet ble slettet!';
$LANGS['videodeleted'] = 'Videoen er slettet!';
$LANGS['pldeleted'] = 'Spillelisten er slettet!';
$LANGS['invitesent'] = 'Venneinvitasjon er sendt!';
$LANGS['descriptionchanged'] = 'Beskrivelsen er endret!';
$LANGS['emptymessage'] = 'Du kan ikke sende tomme meldinger!';
$LANGS['styleupdated'] = 'Gruppestilen er oppdatert!';
$LANGS['imageupdated'] = 'Gruppebildet er oppdatert!';
$LANGS['plcreated'] = 'Spilleliste er opprettet!';
$LANGS['discussiontitle2chars'] = 'Tittelen må bestå av mer enn 2 tegn!';
$LANGS['discussiondesc10chars'] = 'Beskrivelser må være på over 10 tegn!';
$LANGS['5discussionsday'] = 'Du kan bare ha opptil 5 diskusjoner om dagen!';
$LANGS['discussionsuccess'] = 'Diskusjonen ble opprettet!';
$LANGS['memberaccepted1'] = '';
$LANGS['memberaccepted2'] = 'ble godtatt!';
$LANGS['memberdeclined1'] = '';
$LANGS['memberdeclined2'] = 'ble avslått!';
$LANGS['videoaccepted'] = 'Videoen ble godtatt!';
$LANGS['bulletindeleted'] = 'Bulletinen er slettet!';
$LANGS['messagedeleted'] = 'Meldingen ble slettet!';
$LANGS['responsedeleted'] = 'Videoresponsen er slettet!';
$LANGS['flagmod'] = 'Du kan ikke rapportere brukere som har moderatortillatelser!';
$LANGS['userflagged'] = 'Rapport er sendt inn!';
$LANGS['discussionreplysubmitted'] = 'Svaret er sendt!';
$LANGS['discussionreplyempty'] = 'Et svar kan ikke stå tomt!';

/* Watch */
$LANGS['moreinfo'] = 'mer informasjon';
$LANGS['lessinfo'] = 'mindre informasjon';
$LANGS['category'] = 'Kategori';
$LANGS['recordedon'] = 'Innspilt på';
$LANGS['location'] = 'Plassering';
$LANGS['tags'] = 'Tagger';
$LANGS['embed'] = 'Bygg inn';
$LANGS['partnervideo'] = 'Partnervideo';
$LANGS['subscribe'] = 'Abonnere';
$LANGS['unsubscribe'] = 'Avslutte abonnementet';
$LANGS['nodesc'] = 'Ingen Beskrivelse...';
$LANGS['logintosub'] = 'Logg inn for å abonnere!';
$LANGS['logintosubbox'] = 'Vil du abonnere?';
$LANGS['subyourself'] = 'Du kan ikke abonnere på deg selv!';
$LANGS['videoowner'] = 'Alternativer for Videoeier';
$LANGS['editvideo'] = 'Redigere Video';
$LANGS['insight'] = 'Innsikt';
$LANGS['morefrom'] = 'Mer Fra:';
$LANGS['relatedvideos'] = 'Relaterte Videoer';
$LANGS['novideosfound'] = 'Ingen Videoer Funnet...';
$LANGS['morevideos'] = 'Se alle videoer';
$LANGS['changeplayersize'] = 'Endre Spillerstørrelse';
$LANGS['newwindow'] = 'Se denne videoen i et nytt vindu';
$LANGS['featuredtext'] = 'Denne videoen har blitt fremhevet. Vil du se flere fremhevede videoer? <a href="/browse?t=2">Klikk her</a>.';
$LANGS['ratings'] = 'rangeringer';
$LANGS['rating'] = 'rangering';
$LANGS['favorite'] = 'Favoritt';
$LANGS['addtofav'] = 'Legg til i favoritter';
$LANGS['removefav'] = 'Fjern fra favoritter';
$LANGS['favadded'] = 'Denne videoen har blitt <strong>lagt til</strong> i dine <a href="/my_favorites">favoritter</a>.';
$LANGS['favremoved'] = 'Denne videoen har blitt <strong>fjernet</strong> fra dine <a href="/my_favorites">favoritter</a>.';
$LANGS['undo'] = 'Angre';
$LANGS['thanksforrating'] = 'Takk for vurdering!';
$LANGS['playlistdesc'] = 'For å legge til en ny video i spillelisten din, gå til <a href="/my_playlists">"Mine Spillelister"</a>-siden.';
$LANGS['addtoplaylist'] = 'Legg til i Spilleliste';
$LANGS['addtoplaylistsuccess'] = 'Videoen er lagt til spillelisten din.';
$LANGS['share'] = 'Dele';
$LANGS['flag'] = 'Flagg';
$LANGS['flagthisvid'] = 'Flagg Denne Videoen';
$LANGS['removeflag'] = 'Fjern Flagg';
$LANGS['flagnote'] = "Før du rapporterer: sørg for at videoen bryter alle regler. Ikke rapporter bare fordi du ikke liker den videoen, ellers vil du hindre moderators jobb.";
$LANGS['statadded'] = 'La til';
$LANGS['statviews'] = 'Visninger';
$LANGS['statratings'] = 'Vurderinger';
$LANGS['statresponses'] = 'Svar';
$LANGS['statcomments'] = 'Kommentarer';
$LANGS['statfavorited'] = 'Favoritt';
$LANGS['statsdata'] = 'Statistikk og Data';
$LANGS['honors'] = 'Heder for denne videoen';
$LANGS['mostviewed'] = 'Mest Sett';
$LANGS['topfavorited'] = 'Topp Favoritt';
$LANGS['times'] = 'ganger';
$LANGS['mostdiscussed'] = 'Mest Diskutert';
$LANGS['toprated'] = 'Topp Rangert';
$LANGS['videolinks'] = 'Nettsteder som linker til denne videoen';
$LANGS['clicksfrom'] = 'klikk fra';
$LANGS['responses'] = 'Videosvar';
$LANGS['responsespost'] = 'Legg Ut Et Videosvar';
$LANGS['textcomments'] = 'Tekstkommentarer';
$LANGS['commentpost'] = 'Legg Inn En Tekstkommentar';
$LANGS['commentonthisvideo'] = 'Kommenter denne videoen';
$LANGS['postcomment'] = 'Skriv Kommentar';
$LANGS['remainingcounter'] = 'Gjenværende tegnantall';
$LANGS['nocomments'] = 'Denne videoen har <b>ingen Kommentarer</b>.';
$LANGS['noresponses'] = 'Denne videoen har <b>ingen Svar</b>.';
$LANGS['commviewall'] = 'Se Alt';
$LANGS['delete'] = 'Slett';
$LANGS['reply'] = 'Svare';
$LANGS['commentlogin'] = 'Vil du kommentere?';
$LANGS['commentlogindesc'] = '<a href="/signup">Bli med i BitView</a> for en gratis konto eller <a href="/login">logg på</a> hvis du allerede er medlem.';
$LANGS['logintoresponse'] = 'Logg på for å legge ut et Videosvar';
$LANGS['logintocomment'] = 'Logg på for å legge inn en Kommentar';
$LANGS['logintofav'] = 'Vil du legge til favoritter? <a href="/login">Logg på</a> eller <a href="/signup">Registrer deg</a> nå!';
$LANGS['logintopl'] = 'Vil du legge til i spillelister? <a href="/login">Logg på</a> eller <a href="/signup">Registrer deg</a> nå!';
$LANGS['logintoflag'] = 'Vil du flagge en video? <a href="/login">Logg på</a> eller <a href="/signup">Registrer deg</a> nå!';
$LANGS['close'] = 'lukk';
$LANGS['addresponse'] = 'Legg til Svar';
$LANGS['recentlyrated'] = 'Nylig vurdert';
$LANGS['commentsdisabled'] = 'Å legge til kommentarer er deaktivert for denne videoen.';
$LANGS['ratingsdisabled'] = 'Vurderinger deaktivert';
$LANGS['rating1'] = 'Dårlig';
$LANGS['rating2'] = 'Ikke noe spesielt';
$LANGS['rating3'] = 'Verdt å se';
$LANGS['rating4'] = 'Ganske kult';
$LANGS['rating5'] = 'Fantastisk!';
$LANGS['saving'] = 'Lagrer...';
$LANGS['signintorate'] = '<a href="/login">Logg på</a> for å vurdere';
$LANGS['addingcomment'] = "Legger til kommentar...";
$LANGS['commentposted'] = "Kommentar lagt ut!";
$LANGS['commentspammsg'] = "Å legge inn den samme kommentaren igjen regnes som spam. Prøv igjen senere.";
$LANGS['commentspammsg2'] = "Å legge ut mer enn 5 kommentarer etter hverandre anses som spam. Prøv igjen senere.";
$LANGS['emptycomment'] = "Kommentaren din kan ikke være tom.";
$LANGS['spambutton'] = "Spam";
$LANGS['notspambutton'] = "Ikke Spam";
$LANGS['commentsspam'] = "Kommentar(er) merket som spam";
$LANGS['marked'] = "Merket som spam";
$LANGS['spamshow'] = "Vis";
$LANGS['spamhide'] = "Skjul";
$LANGS['poorcomment'] = "Dårlig kommentar";
$LANGS['goodcomment'] = "God kommentar";
$LANGS['pleasesignin'] = "Vennligst logg inn";
$LANGS['showmorecomments'] = "Vis flere kommentarer";
$LANGS['showingamount'] = "<strong>Viser {number}</strong> av {total} kommentarer";
$LANGS['customize'] = "Tilpass";
$LANGS['customizedesc'] = "Etter å ha gjort valget ditt, kopier og lim inn innebyggingskoden ovenfor. Koden endres basert på valget ditt.";
$LANGS['editvideodetail'] = "Edit Video Detail";
$LANGS['editannotations'] = "Edit annotations";
$LANGS['insightstats'] = "Insight stats";
$LANGS['allowratingscheck'] = "Allow this video to be <b>rated</b> by others.";
$LANGS['thisvideoispublic'] = "This video is public.";
$LANGS['thisvideoisprivate'] = "This video is private.";
$LANGS['thisvideois'] = "This video is";
$LANGS['like'] = "Like";
$LANGS['saveto'] = "Save to";
$LANGS['uservideoamount'] = "{n} videos";
$LANGS['respondvideo'] = "Respond to this video...";
$LANGS['signinnowcomment'] = '<a href="/login">Sign In</a> or <a href="/signup">Sign Up</a> now to post a comment!';
$LANGS['charactersremaining'] = 'characters remaining';
$LANGS['attachavideo'] = 'Attach a video';
$LANGS['commentok'] = 'OK';
$LANGS['commenterror'] = 'Error';
$LANGS['highestratedcomments'] = 'Highest Rated Comments';
$LANGS['options'] = 'Options';
$LANGS['openplaylist'] = 'Open Playlist';
$LANGS['autoplayon'] = 'Autoplay (on)';
$LANGS['autoplayoff'] = 'Autoplay (off)';
$LANGS['playlistposition'] = '<b>{n1}</b> of {n2}';
$LANGS['nextin'] = 'Next in {n}';
$LANGS['subscribetooltip'] = "Click to be notified of new videos from this channel";
$LANGS['unsubscribetooltip'] = "Click to stop being notified of new videos from this channel";
$LANGS['liketooltip'] = "I like this";
$LANGS['disliketooltip'] = "I dislike this";
$LANGS['likeratiotooltip'] = "{l} likes, {d} dislikes";
$LANGS['savetotooltip'] = "Save to favorites or playlist";
$LANGS['sharetooltip'] = "Share this video";
$LANGS['embedtooltip'] = "Get video embed code";
$LANGS['flagtooltip'] = "Flag as inappropriate";
$LANGS['voteuptooltip'] = "Vote Up";
$LANGS['votedowntooltip'] = "Vote Down";
$LANGS['flagspamtooltip'] = "Flag for spam";
$LANGS['removetooltip'] = "Remove";

/* Watch comments */
$LANGS['allcomments'] = 'Alle kommentarer';

/* Sign In */
$LANGS['username'] = "Brukernavn";
$LANGS['password'] = "Passord";
$LANGS['logindesc'] = "Logg på BitView med kontoen din";
$LANGS['forgot'] = "Får du ikke tilgang til kontoen din?";
$LANGS['forgotmsg'] = 'Vennligst kontakt oss på Twitter (@BitView_) eller send en melding til moderatorene på Discord. (lenke i bunntekst)';
$LANGS['noaccount'] = "Har du ikke en konto?";
$LANGS['signuptobv'] = "Registrer deg for BitView!";
$LANGS['signintobv'] = "Logg på BitView!";
$LANGS['signindesc1'] = "Bli med i det største verdensomspennende videodelingsfellesskapet!";
$LANGS['signindesc2'] = "BitView er en måte å få videoene dine til folk som betyr noe for deg. Med BitView kan du:";
$LANGS['signindesc3'] = "Vis frem favorittvideoene dine til verden";
$LANGS['signindesc4'] = "Blogg videoene du tar med digitalkameraet eller mobiltelefonen";
$LANGS['signindesc5'] = "Vis videoer sikkert og privat til venner og familie rundt om i verden";
$LANGS['notallowed'] = "Du har blitt utestengt 3 ganger allerede. Du har ikke lov til å bruke BitView lenger!";
$LANGS['wrongpassword'] = 'Feil passord! Vær så snill, prøv på nytt.';
$LANGS['staysigned'] = "Logget inn";

/* Sign Up */
$LANGS['email'] = "Epostadresse";
$LANGS['passwordstrength'] = "Passordstyrke";
$LANGS['psnone'] = "Ingen";
$LANGS['psweak'] = "Svak";
$LANGS['psfair'] = "Rettferdig";
$LANGS['psgood'] = "Flink";
$LANGS['psstrong'] = "Sterk";
$LANGS['repassword'] = "Skriv inn passordet på nytt";
$LANGS['usernamedesc'] = "Brukernavnet ditt kan bare være alfanumerisk.";
$LANGS['captcha'] = "Captcha";
$LANGS['acceptterms'] = 'Jeg godtar <a href="/terms">vilkårene for bruk</a> og <a href="/privacy">personvernreglene</a>.';
$LANGS['copyrighttext'] = 'Å laste opp materiale som du ikke eier er et brudd på opphavsretten og mot loven. Hvis du laster opp materiale du ikke eier, vil kontoen din bli slettet.';
$LANGS['mustaccept'] = 'Du må godta vilkårene for bruk og personvernreglene for å opprette kontoen din.';
$LANGS['createaccount'] = 'Opprett min konto';
$LANGS['signuperror'] = 'Det oppsto en feil under opprettelsen av kontoen din.';
$LANGS['sameemail'] = 'Dette brukernavnet eller e-postadressen er allerede i bruk!';
$LANGS['usernamechar'] = 'Brukernavn kan bare inneholde tegn og tall!';
$LANGS['required'] = 'Alle tekstfelt er obligatoriske!';
$LANGS['notmatch'] = "Passordene stemmer ikke!";
$LANGS['signuphead'] = 'Kom i gang med kontoen din';

/* Videos Page */
$LANGS['recentvideos'] = 'Nylige Videoer';
$LANGS['random'] = 'Tilfeldig';
$LANGS['dropdownmore'] = 'mer';
$LANGS['allcatin'] = 'i';
$LANGS['allcat'] = 'Alle Kategorier';
$LANGS['categories'] = 'Kategorier';
$LANGS['nomorevideos'] = 'Ingen flere videoer ble funnet...';
$LANGS['timetoday'] = 'I Dag';
$LANGS['timeweek'] = 'Denne Uken';
$LANGS['timemonth'] = 'Denne Måneden';
$LANGS['alltime'] = 'Hele Tiden';
$LANGS['when'] = 'Når';
$LANGS['videofavorites'] = 'favoritter';
$LANGS['videocomments'] = 'kommentarer';
$LANGS['trendingtopics'] = 'Trending Topics';

/* Channels Page */
$LANGS['mostsubscribed'] = 'Mest Abonnerte';
$LANGS['lastlogin'] = 'Siste Pålogging';
$LANGS['cstatviews'] = 'Visninger';
$LANGS['cstatvideos'] = 'Videoer';
$LANGS['cstatsubs'] = 'Abonnenter';
$LANGS['nochannels'] = 'Ingen flere kanaler ble funnet...';

/* Video Categories */
$LANGS['cat1'] = "Film og Animasjon";
$LANGS['cat2'] = "Biler og Kjøretøy";
$LANGS['cat3'] = "Utdanning og Instruksjon";
$LANGS['cat4'] = "Underholdning";
$LANGS['cat5'] = "Arrangementer og Bryllup";
$LANGS['cat6'] = "Familie";
$LANGS['cat7'] = "Til Salgs og Auksjoner";
$LANGS['cat8'] = "Hobbyer og Interesser";
$LANGS['cat9'] = "Humor";
$LANGS['cat10'] = "Musikk";
$LANGS['cat11'] = "Nyheter og Politikk";
$LANGS['cat12'] = "Ulige og Opprørende";
$LANGS['cat13'] = "Folk og Blogger";
$LANGS['cat14'] = "Personlig og Dating";
$LANGS['cat15'] = "Kjæledyr og Dyr";
$LANGS['cat16'] = "Vitenskap og Teknologi";
$LANGS['cat17'] = "Kortfilmer";
$LANGS['cat18'] = "Sport";
$LANGS['cat19'] = "Reise og Arrangementer";
$LANGS['cat20'] = "Spill";
$LANGS['cat21'] = "Videoblogger";

/* Channel Types */
$LANGS['type0'] = "Ingen";
$LANGS['type1'] = "Medlem";
$LANGS['type1p'] = "Medlemmer";
$LANGS['type2'] = "Komiker";
$LANGS['type2p'] = "Komikere";
$LANGS['type3'] = "Regissør";
$LANGS['type3p'] = "Regissører";
$LANGS['type4'] = "Guru";
$LANGS['type4p'] = "Guru-er";
$LANGS['type5'] = "Musiker";
$LANGS['type5p'] = "Musikere";
$LANGS['type6'] = "Reporter";
$LANGS['type6p'] = "Reportere";

/* Countries */
$LANGS['cat_AF'] = "Afghanistan";
$LANGS['cat_AX'] = "Ålandsøyene";
$LANGS['cat_AL'] = "Albania";
$LANGS['cat_DZ'] = "Algeria";
$LANGS['cat_AS'] = "Amerikansk Samoa";
$LANGS['cat_AD'] = "Andorra";
$LANGS['cat_AO'] = "Angola";
$LANGS['cat_AI'] = "Anguilla";
$LANGS['cat_AQ'] = "Antarktis";
$LANGS['cat_AG'] = "Antigua og Barbuda";
$LANGS['cat_AR'] = "Argentina";
$LANGS['cat_AM'] = "Armenia";
$LANGS['cat_AW'] = "Aruba";
$LANGS['cat_AU'] = "Australia";
$LANGS['cat_AT'] = "Østerrike";
$LANGS['cat_AZ'] = "Aserbajdsjan";
$LANGS['cat_BS'] = "Bahamas";
$LANGS['cat_BH'] = "Bahrain";
$LANGS['cat_BD'] = "Bangladesh";
$LANGS['cat_BB'] = "Barbados";
$LANGS['cat_BY'] = "Hviterussland";
$LANGS['cat_BE'] = "Belgia";
$LANGS['cat_BZ'] = "Belize";
$LANGS['cat_BJ'] = "Benin";
$LANGS['cat_BM'] = "Bermuda";
$LANGS['cat_BT'] = "Bhutan";
$LANGS['cat_BO'] = "Bolivia";
$LANGS['cat_BQ'] = "Karibiske Nederland";
$LANGS['cat_BA'] = "Bosnia-Hercegovina";
$LANGS['cat_BW'] = "Botswana";
$LANGS['cat_BV'] = "Bouvetøya";
$LANGS['cat_BR'] = "Brasil";
$LANGS['cat_IO'] = "Det britiske territoriet i Det indiske hav";
$LANGS['cat_BN'] = "Brunei Darussalam";
$LANGS['cat_BG'] = "Bulgaria";
$LANGS['cat_BF'] = "Burkina Faso";
$LANGS['cat_BI'] = "Burundi";
$LANGS['cat_KH'] = "Kambodsja";
$LANGS['cat_CM'] = "Kamerun";
$LANGS['cat_CA'] = "Canada";
$LANGS['cat_CV'] = "Kapp Verde";
$LANGS['cat_KY'] = "Caymanøyene";
$LANGS['cat_CF'] = "Sentralafrikanske republikk";
$LANGS['cat_TD'] = "Tsjad";
$LANGS['cat_CL'] = "Chile";
$LANGS['cat_CN'] = "Kina";
$LANGS['cat_CX'] = "Juleøya";
$LANGS['cat_CC'] = "Cocos (Keeling) Islands";
$LANGS['cat_CO'] = "Colombia";
$LANGS['cat_KM'] = "Komorene";
$LANGS['cat_CG'] = "Republikken Kongo";
$LANGS['cat_CD'] = "Den demokratiske republikken Kongo";
$LANGS['cat_CK'] = "Cookøyene";
$LANGS['cat_CR'] = "Costa Rica";
$LANGS['cat_CI'] = "Elfenbenskysten";
$LANGS['cat_HR'] = "Kroatia";
$LANGS['cat_CU'] = "Cuba";
$LANGS['cat_CW'] = "Curaçao";
$LANGS['cat_CY'] = "Kypros";
$LANGS['cat_CZ'] = "Tsjekkia";
$LANGS['cat_DK'] = "Danmark";
$LANGS['cat_DJ'] = "Djibouti";
$LANGS['cat_DM'] = "Dominica";
$LANGS['cat_DO'] = "Dominikanske republikk";
$LANGS['cat_EC'] = "Ecuador";
$LANGS['cat_EG'] = "Egypt";
$LANGS['cat_SV'] = "El Salvador";
$LANGS['cat_GQ'] = "Ekvatorial-Guinea";
$LANGS['cat_ER'] = "Eritrea";
$LANGS['cat_EE'] = "Estland";
$LANGS['cat_ET'] = "Etiopia";
$LANGS['cat_FK'] = "Falklandsøyene (Malvinas)";
$LANGS['cat_FO'] = "Færøyene";
$LANGS['cat_FJ'] = "Fiji";
$LANGS['cat_FI'] = "Finland";
$LANGS['cat_FR'] = "Frankrike";
$LANGS['cat_GF'] = "Fransk Guyana";
$LANGS['cat_FG'] = "Fransk Guyana";
$LANGS['cat_PF'] = "Fransk Polynesia";
$LANGS['cat_TF'] = "Franske sørlige territorier";
$LANGS['cat_GA'] = "Gabon";
$LANGS['cat_GM'] = "Gambia";
$LANGS['cat_GE'] = "Georgia";
$LANGS['cat_DE'] = "Tyskland";
$LANGS['cat_GH'] = "Ghana";
$LANGS['cat_GI'] = "Gibraltar";
$LANGS['cat_GR'] = "Hellas";
$LANGS['cat_GL'] = "Grønland";
$LANGS['cat_GD'] = "Grenada";
$LANGS['cat_GP'] = "Guadalupe";
$LANGS['cat_GU'] = "Guam";
$LANGS['cat_GT'] = "Guatemala";
$LANGS['cat_GG'] = "Guernsey";
$LANGS['cat_GN'] = "Guinea";
$LANGS['cat_GW'] = "Guinea-Bissau";
$LANGS['cat_GY'] = "Guyana";
$LANGS['cat_HT'] = "Haiti";
$LANGS['cat_HM'] = "Heard Island og McDonald Islands";
$LANGS['cat_VA'] = "Den hellige stol (Vatikanstaten)";
$LANGS['cat_HN'] = "Honduras";
$LANGS['cat_HK'] = "Hong Kong";
$LANGS['cat_HU'] = "Ungarn";
$LANGS['cat_IS'] = "Island";
$LANGS['cat_IN'] = "India";
$LANGS['cat_ID'] = "Indonesia";
$LANGS['cat_IR'] = "Iran";
$LANGS['cat_IQ'] = "Irak";
$LANGS['cat_IE'] = "Irland";
$LANGS['cat_IM'] = "Isle of Man";
$LANGS['cat_IL'] = "Israel";
$LANGS['cat_IT'] = "Italia";
$LANGS['cat_JM'] = "Jamaica";
$LANGS['cat_JP'] = "Japan";
$LANGS['cat_JE'] = "Trøye";
$LANGS['cat_JO'] = "Jordan";
$LANGS['cat_KZ'] = "Kasakhstan";
$LANGS['cat_KE'] = "Kenya";
$LANGS['cat_KI'] = "Kiribati";
$LANGS['cat_XK'] = "Kosovo";
$LANGS['cat_KP'] = "Nord-Korea";
$LANGS['cat_KR'] = "Sør-Korea";
$LANGS['cat_KW'] = "Kuwait";
$LANGS['cat_KG'] = "Kirgisistan";
$LANGS['cat_LA'] = "Laos";
$LANGS['cat_LV'] = "Latvia";
$LANGS['cat_LB'] = "Libanon";
$LANGS['cat_LS'] = "Lesotho";
$LANGS['cat_LR'] = "Liberia";
$LANGS['cat_LY'] = "Libya";
$LANGS['cat_LI'] = "Liechtenstein";
$LANGS['cat_LT'] = "Litauen";
$LANGS['cat_LU'] = "Luxembourg";
$LANGS['cat_MO'] = "Macao";
$LANGS['cat_MK'] = "Nord-Makedonia";
$LANGS['cat_MG'] = "Madagaskar";
$LANGS['cat_MW'] = "Malawi";
$LANGS['cat_MY'] = "Malaysia";
$LANGS['cat_MV'] = "Maldivene";
$LANGS['cat_ML'] = "Mali";
$LANGS['cat_MT'] = "Malta";
$LANGS['cat_MH'] = "Marshalløyene";
$LANGS['cat_MQ'] = "Martinique";
$LANGS['cat_MR'] = "Mauritania";
$LANGS['cat_MU'] = "Mauritius";
$LANGS['cat_YT'] = "Mayotte";
$LANGS['cat_MX'] = "Mexico";
$LANGS['cat_FM'] = "Mikronesia";
$LANGS['cat_MD'] = "Moldova";
$LANGS['cat_MC'] = "Monaco";
$LANGS['cat_MN'] = "Mongolia";
$LANGS['cat_ME'] = "Montenegro";
$LANGS['cat_MS'] = "Montserrat";
$LANGS['cat_MA'] = "Marokko";
$LANGS['cat_MZ'] = "Mozambique";
$LANGS['cat_MM'] = "Myanmar";
$LANGS['cat_NA'] = "Namibia";
$LANGS['cat_NR'] = "Nauru";
$LANGS['cat_NP'] = "Nepal";
$LANGS['cat_NL'] = "Nederland";
$LANGS['cat_AN'] = "De nederlandske Antillene";
$LANGS['cat_NC'] = "Ny-Caledonia";
$LANGS['cat_NZ'] = "New Zealand";
$LANGS['cat_NI'] = "Nicaragua";
$LANGS['cat_NE'] = "Niger";
$LANGS['cat_NG'] = "Nigeria";
$LANGS['cat_NU'] = "Niue";
$LANGS['cat_NF'] = "Norfolkøya";
$LANGS['cat_MP'] = "Nord-Marianene";
$LANGS['cat_NO'] = "Norge";
$LANGS['cat_OM'] = "Oman";
$LANGS['cat_PK'] = "Pakistan";
$LANGS['cat_PW'] = "Palau";
$LANGS['cat_PS'] = "Palestina";
$LANGS['cat_PA'] = "Panama";
$LANGS['cat_PG'] = "Papua Ny-Guinea";
$LANGS['cat_PY'] = "Paraguay";
$LANGS['cat_PE'] = "Peru";
$LANGS['cat_PH'] = "Filippinene";
$LANGS['cat_PN'] = "Pitcairn";
$LANGS['cat_PL'] = "Polen";
$LANGS['cat_PT'] = "Portugal";
$LANGS['cat_PR'] = "Puerto Rico";
$LANGS['cat_QA'] = "Qatar";
$LANGS['cat_RE'] = "Reunion";
$LANGS['cat_RO'] = "Romania";
$LANGS['cat_RU'] = "Russland";
$LANGS['cat_RW'] = "Rwanda";
$LANGS['cat_BL'] = "Saint Barthélemy";
$LANGS['cat_SH'] = "Sankt Helena";
$LANGS['cat_KN'] = "Saint Kitts og Nevis";
$LANGS['cat_LC'] = "Saint Lucia";
$LANGS['cat_MF'] = "Saint Martin (fransk del)";
$LANGS['cat_PM'] = "Saint Pierre og Miquelon";
$LANGS['cat_VC'] = "Saint Vincent og Grenadinene";
$LANGS['cat_WS'] = "Samoa";
$LANGS['cat_SM'] = "San Marino";
$LANGS['cat_ST'] = "Sao Tome og Principe";
$LANGS['cat_SA'] = "Saudi-Arabia";
$LANGS['cat_SN'] = "Senegal";
$LANGS['cat_RS'] = "Serbia";
$LANGS['cat_SC'] = "Seychellene";
$LANGS['cat_SL'] = "Sierra Leone";
$LANGS['cat_SG'] = "Singapore";
$LANGS['cat_SX'] = "Sint Maarten";
$LANGS['cat_SK'] = "Slovakia";
$LANGS['cat_SI'] = "Slovenia";
$LANGS['cat_SB'] = "Salomonøyene";
$LANGS['cat_SO'] = "Somalia";
$LANGS['cat_ZA'] = "Sør-Afrika";
$LANGS['cat_GS'] = "Sør-Georgia og Sør-Sandwichøyene";
$LANGS['cat_ES'] = "Spania";
$LANGS['cat_LK'] = "Sri Lanka";
$LANGS['cat_SD'] = "Sudan";
$LANGS['cat_SR'] = "Surinam";
$LANGS['cat_SJ'] = "Svalbard og Jan Mayen";
$LANGS['cat_SZ'] = "Swaziland";
$LANGS['cat_SE'] = "Sverige";
$LANGS['cat_CH'] = "Sveits";
$LANGS['cat_SS'] = "Sør-Sudan";
$LANGS['cat_SY'] = "Syria";
$LANGS['cat_TW'] = "Taiwan";
$LANGS['cat_TJ'] = "Tadsjikistan";
$LANGS['cat_TZ'] = "Tanzania";
$LANGS['cat_TH'] = "Thailand";
$LANGS['cat_TL'] = "Timor-Leste";
$LANGS['cat_TG'] = "Togo";
$LANGS['cat_TK'] = "Tokelau";
$LANGS['cat_TO'] = "Tonga";
$LANGS['cat_TT'] = "Trinidad og Tobago";
$LANGS['cat_TN'] = "Tunisia";
$LANGS['cat_TR'] = "Tyrkia";
$LANGS['cat_TM'] = "Turkmenistan";
$LANGS['cat_TC'] = "Turks- og Caicosøyene";
$LANGS['cat_TV'] = "Tuvalu";
$LANGS['cat_UG'] = "Uganda";
$LANGS['cat_UA'] = "Ukraina";
$LANGS['cat_AE'] = "De forente arabiske emirater";
$LANGS['cat_GB'] = "Storbritannia";
$LANGS['cat_US'] = "USA";
$LANGS['cat_UM'] = "USAs mindre avsidesliggende øyer";
$LANGS['cat_UY'] = "Uruguay";
$LANGS['cat_UZ'] = "Usbekistan";
$LANGS['cat_VU'] = "Vanatu";
$LANGS['cat_VE'] = "Venezuela";
$LANGS['cat_VN'] = "Vietnam";
$LANGS['cat_VG'] = "Jomfruøyene, britiske";
$LANGS['cat_VI'] = "Jomfruøyene, USA.";
$LANGS['cat_WF'] = "Wallis og Futuna";
$LANGS['cat_EH'] = "Vest-Sahara";
$LANGS['cat_YE'] = "Jemen";
$LANGS['cat_ZM'] = "Zambia";
$LANGS['cat_ZW'] = "Zimbabwe";

/* My Subscriptions */
$LANGS['newvideos'] = "Nye Videoer";
$LANGS['addselectedto'] = "Add the selected videos to:";
$LANGS['addtoplaylists'] = "Add to Playlists";

/* Account */
$LANGS['myaccount'] = "Min konto";
$LANGS['vidsfavs'] = "Videoer, Favoritter og Spillelister";
$LANGS['accountsettings'] = "Kontoinnstillinger";
$LANGS['viewinghistory'] = "Historie";
$LANGS['mychannel'] = "Min kanal";
$LANGS['uploadedvideos'] = "Opplastede Videoer";
$LANGS['new'] = "Ny";
$LANGS['playlist'] = "Spilleliste";
$LANGS['videoupload'] = "Videoopplasting";
$LANGS['nosubvideos'] = "Du har ingen abonnementer...";
$LANGS['nofavvideos'] = "Du har ikke merket noen video som favoritt...";

/* My Videos */
$LANGS['sortby'] = "Sorter etter";
$LANGS['sorttitle'] = "Tittel";
$LANGS['sorttime'] = "Tid";
$LANGS['sortdateadded'] = "Dato Lagt Yil";
$LANGS['sortviews'] = "Visninger";
$LANGS['sortrating'] = "Vurdering";
$LANGS['stattime'] = "Tid";
$LANGS['statrating'] = "Vurdering";
$LANGS['statbroadcast'] = "Kringkasting";
$LANGS['statrawfile'] = "Råfil";
$LANGS['public'] = "Offentlig";
$LANGS['private'] = "Privat";
$LANGS['live'] = "Live!";
$LANGS['converting'] = "Konverterer...";
$LANGS['uploading'] = "Laster opp...";
$LANGS['addvidsto'] = "Legg Til Videoer Til";
$LANGS['play'] = "Spill";
$LANGS['edit'] = "Rediger";
$LANGS['setasavatar'] = "Sett Miniatyrbilde Som Avatar";
$LANGS['downloadmp4'] = "Last ned MP4";
$LANGS['deleteconfirmation'] = "Er du sikker på at du vil slette denne videoen?";
$LANGS['novideos'] = 'Du har ikke lastet opp noen videoer. <a href="/my_videos_upload">Begynn å laste opp en video nå</a>!';
$LANGS['nomyvideosresults'] = "Ingen resultater. Sjekk om stavemåten din er riktig.";

/* Edit Video */
$LANGS['infoandsettings'] = "Info and Settings";
$LANGS['annotations'] = "Annotations";
$LANGS['captionsandsubtitles'] = "Captions and Subtitles";
$LANGS['viewonvideopage'] = "View on video page »";
$LANGS['title'] = "Tittel";
$LANGS['desc'] = "Beskrivelse";
$LANGS['privacy'] = "Personvern";
$LANGS['saveinfo'] = "Lagre Informasjon";
$LANGS['saveinfoconfirm'] = "Er du sikker på at du vil endre videoinformasjonen?";
$LANGS['viewchart'] = "Se Diagram";
$LANGS['backtopreviouspage'] = "Tilbake til forrige side";
$LANGS['editsavechanges'] = "Lagre Endringer";
$LANGS['editcancel'] = "avbryt";
$LANGS['videoinfo'] = "Videoinformasjon";
$LANGS['videothumbnail'] = "Videominiatyrbilde";
$LANGS['uploadthumbnail'] = "Last Opp Miniatyrbilde";
$LANGS['customthumbdesc'] = 'For å sette et tilpasset miniatyrbilde, klikk på miniatyrbildet på venstre side og velg ønsket bildefil. Klikk deretter "Last opp miniatyrbilde".';
$LANGS['customthumbtitle'] = 'Vil du endre dette miniatyrbildet?';
$LANGS['customthumbinfo'] = 'Egendefinerte miniatyrbilder er eksklusive for partnere. For å lese mer om fordelene ved å bli med i partnerprogrammet og dets krav, klikk på knappen nedenfor.';
$LANGS['partnerreadmore'] = 'Les Mer';
$LANGS['broadcastingoptions'] = 'Kringkastings- og Delingsalternativer';
$LANGS['publicdesc'] = "alle kan søke etter og se - anbefales";
$LANGS['privatedesc'] = "bare spesifikke BitView-brukere kan se";
$LANGS['allowcomments'] = "Tillat kommentarer automatisk";
$LANGS['allowfriendcomments'] = "Bare venner kan kommentere";
$LANGS['disablecomments'] = "Ikke tillat kommentarer";
$LANGS['dateandmap'] = "Dato og Kart";
$LANGS['clear'] = "Slett";
$LANGS['allowratings'] = "Ja, la denne videoen bli vurdert av andre.";
$LANGS['dontallowratings'] = "Nei, ikke la denne videoen bli vurdert.";
$LANGS['updatevideo'] = "Update Video";
$LANGS['updatevideofilesize'] = "(maximum file size: 100MB)";

/* Edit Video Annotations */
$LANGS['publish'] = "Publish";
$LANGS['published'] = "Published";
$LANGS['saved'] = "Saved";
$LANGS['notvaliddate'] = "You have entered an unvalid timestamp!";
$LANGS['outsiderange'] = "You have entered a timestamp outside of the video duration range!";
$LANGS['video_pl'] = "Paste a link to a Video";
$LANGS['playlist_pl'] = "Paste a link to a Playlist";
$LANGS['channel_pl'] = "Enter an username";
$LANGS['group_pl'] = "Paste a link to a Group";
$LANGS['search_pl'] = "Enter your search query";
$LANGS['entertext'] = "Enter your text here";
$LANGS['loading'] = "Loading...";
$LANGS['addlink'] = "Add link";
$LANGS['linktype'] = "Link Type";
$LANGS['group'] = "Group";
$LANGS['composemessage'] = "Compose Message";
$LANGS['videoresponseupload'] = "Video Response Upload";
$LANGS['searchquery'] = "BitView Search Query";
$LANGS['entervalidurl'] = "Please enter a valid URL";

/* My Playlists */
$LANGS['addedpl'] = "Lagt til";
$LANGS['frompl'] = "Fra";
$LANGS['nopl'] = "Ingen spillelister ble funnet....";

/* My Playlist */
$LANGS['playlistedit'] = "Rediger Spilleliste";
$LANGS['videourl'] = "Video URL";
$LANGS['add'] = "Legg Til";
$LANGS['editinfo'] = "Rediger Informasjon";
$LANGS['editdetails'] = "Edit details";
$LANGS['deleteplaylist'] = "Delete playlist";
$LANGS['addvideostoplaylist'] = "Add videos to playlist";
$LANGS['novideoswerefound'] = "No videos were found.";
$LANGS['position'] = "Position";
$LANGS['move'] = "Move";
$LANGS['deleteplaylistconfirmdesc'] = "Are you sure you want to delete <strong>{p}</strong>?<br><br>Note: Deleting playlists is a permanent action and cannot be undone.";
$LANGS['deleteplaylistconfirm'] = "Yes, delete it";
$LANGS['titledesctags'] = "Title, description, tags";
$LANGS['savechangespl'] = "Save changes";

/* Edit Playlist */
$LANGS['pledittitle'] = "Rediger Spilleliste";
$LANGS['pleditdesc'] = "Spillelister er en samling av videoer som du kan sette opp slik du vil.";
$LANGS['cancel'] = "Avbryt";

/* Create Playlist */
$LANGS['createplaylisttitle'] = "Opprett Videospilleliste";
$LANGS['createplaylist'] = "Opprett Spilleliste";

/* View Playlist */
$LANGS['plpermalink'] = "Spilleliste/URL (Permalenke):";
$LANGS['sortcomments'] = "Kommentarer";
$LANGS['unsorted'] = "Usortert";
$LANGS['playallvideos'] = "Spill av Alle Videoer";

/* Inbox */
$LANGS['compose'] = "Skriv";
$LANGS['from'] = "Fra";
$LANGS['subject'] = "Emne";
$LANGS['date'] = "Dato";
$LANGS['allmsg'] = "Alle Meldinger";
$LANGS['msgcom'] = "Kommentarer";
$LANGS['sentmsg'] = "Sendte Meldinger";
$LANGS['nomsg'] = "Du har ingen meldinger...";
$LANGS['personalmessages'] = "Personlige Meldinger";
$LANGS['sharedwithyouinbox'] = "Delt med Deg";
$LANGS['friendinvitesinbox'] = "Venneinvitasjoner";
$LANGS['videoresponsesinbox'] = "Videoresponser";
$LANGS['sent'] = "Sendt";
$LANGS['attachvideo'] = "Legg ved video";
$LANGS['msgchannelcomment'] = "Kommenter kanalen din";
$LANGS['msgcomment'] = "Kommenter videoen din";
$LANGS['msgvideoresponse'] = "Videorespons på videoen din";
$LANGS['msgmention'] = "Omtale på en video";
$LANGS['msgmentionchannel'] = "Omtale på {channel} sin kanal";

/* Address Book */
$LANGS['addressbook'] = "Adressebok";
$LANGS['allcontacts'] = "Alle kontakter";
$LANGS['selectedcontacts'] = "Valgte kontakter";
$LANGS['choosecontacts'] = "Velg fra listen over kontakter";
$LANGS['friendssince'] = "Venner siden";
$LANGS['friendsinvitenot'] = "Venneinvitasjon er ikke akseptert ennå";
$LANGS['friendstatus'] = "Vennestatus";
$LANGS['unselect'] = "Opphev valget";
$LANGS['unselectall'] = "Opphev merkingen av alle";
$LANGS['nocontacts'] = "Ingen kontakter...";
$LANGS['selectacontact'] = "Vennligst velg minst en kontakt for å slette!";
$LANGS['selectacontactmsg'] = "Vennligst velg minst en kontakt for å sende melding!";
$LANGS['selectonecompose'] = "Du kan ikke skrive til flere kontakter samtidig!<br>Vennligst, velg kontakten du vil sende en melding.";

/* Insight */
$LANGS['insighttitle'] = "Innsikt: Statistikk og data";
$LANGS['allvideos'] = "Alle videoer";
$LANGS['summary'] = "Sammendrag";
$LANGS['demographics'] = "Demografi";
$LANGS['viewsdesc'] = "Hvor mange visninger får videoene mine?";
$LANGS['demodesc'] = "Hvem abonnerer på kanalen min?";
$LANGS['commdesc'] = "Hvor er abonnentene mine?";
$LANGS['video'] = "Video";
$LANGS['topvideos'] = "Toppvideoer";
$LANGS['viewspercentage'] = "Visninger (&percnt; av totalt)";
$LANGS['percentoftotalviews'] = "&prosent; av totalt antall visninger";
$LANGS['searchmyvideos'] = "Søk i mine videoer";
$LANGS['insufdemo'] = "Det er ikke nok data til å vise demografi. Prøv å velge en annen tidsperiode.";
$LANGS['ageranges'] = "Aldersintervaller for begge kjønn";
$LANGS['genderranges'] = "Kjønn for alle aldersgrupper";
$LANGS['engdesc'] = "Antall brukere som har kommentert, favoritt eller vurdert videoene dine";
$LANGS['engagements'] = "Fellesskapsengasjementer";
$LANGS['dailysubs'] = "Daglige abonnenter";
$LANGS['daily'] = "Daglig";
$LANGS['total'] = "Totalt";
$LANGS['insightvideodesc'] = "Hvor mange ganger har denne videoen blitt sett?";
$LANGS['videototalviews'] = "Totalt antall visninger";
$LANGS['dailyviews'] = "Daglige visninger";

/* Send Message */
$LANGS['messagecont'] = "Melding";
$LANGS['to'] = "Til";
$LANGS['send message button'] = "Send Melding";

/* Groups */
$LANGS['groups'] = "Grupper";
$LANGS['joinedgroups'] = "Bli med i Grupper";
$LANGS['recentgroups'] = "Nylige Grupper";
$LANGS['mostmembers'] = "De Fleste Medlemmer";
$LANGS['mostvideos'] = "De Fleste Videoer";
$LANGS['groupmostdiscussed'] = "Mest Diskutert";
$LANGS['createagroup'] = "Opprett en Gruppe";
$LANGS['groupvideos'] = "Videoer";
$LANGS['groupmembers'] = "Medlemmer";
$LANGS['discussions'] = "Diskusjoner";
$LANGS['groupcreated'] = "Opprettet";
$LANGS['nogroups'] = "Ingen Grupper Funnet...";

/* Group */
$LANGS['jointhisgroup'] = "Bli Med i Denne Gruppen";
$LANGS['removerequest'] = "Fjern Forespørsel";
$LANGS['leagroup'] = "Forlat Gruppen";
$LANGS['moderation'] = "Moderasjon";
$LANGS['viewallvideos'] = "Se Alle Videoer";
$LANGS['addvideo'] = "Legg Til Video";
$LANGS['novideos'] = "Ingen Videoer...";
$LANGS['nodiscussions'] = "Ingen Diskusjoner...";
$LANGS['creatediscussion'] = "Opprett Diskusjon";
$LANGS['topostatopic'] = "for å legge ut et emne.";
$LANGS['topic'] = "Emne";
$LANGS['author'] = "Forfatter";
$LANGS['replies'] = "Svar";
$LANGS['lastpost'] = "Siste Innlegg";
$LANGS['viewallmembers'] = "Se Alle Medlemmer";
$LANGS['owner'] = "Eier";
$LANGS['grouptype'] = "Type";
$LANGS['instantjoin'] = "Øyeblikkelig Bli Med";
$LANGS['approvalrequired'] = "Godkjenning Kreves";
$LANGS['groupurl'] = "URL";
$LANGS['deletediscussion'] = "Slett Diskusjon";
$LANGS['postreply'] = "Legg Inn Svar";
$LANGS['post'] = "Innlegg";
$LANGS['accept'] = "Godta";
$LANGS['decline'] = "Avslå";

/* Group Moderation */
$LANGS['groupmoderation'] = "Gruppemoderering";
$LANGS['approvemembers'] = "Godkjenn Medlemmer";
$LANGS['approvevideos'] = "Godkjenn Videoer";
$LANGS['yes'] = "Ja";
$LANGS['no'] = "Nei";
$LANGS['changeinfo'] = "Endre Informasjon";
$LANGS['changeimage'] = "Endre Bilde";
$LANGS['image'] = "Bilde";
$LANGS['styling'] = "Styling";
$LANGS['cssdesc'] = "Å ha bakgrunner eller grafikk som gjør eller viser ulovlige ting vil resultere i oppsigelse.";
$LANGS['updatecss'] = "Oppdater CSS";
$LANGS['groupmessage'] = "Melding";
$LANGS['sendmessagetomembers'] = "Send Melding til Medlemmer";
$LANGS['delgroup'] = "Slett Gruppe";

/* Submit Group Video */
$LANGS['submitvideotitle'] = "Send inn Video til Gruppe";
$LANGS['submitvideo'] = "Send inn Video";

/* Create Group */
$LANGS['groupname'] = "Gruppenavn";
$LANGS['groupimage'] = "Gruppebilde";
$LANGS['creategroup'] = "Opprett Gruppe";
$LANGS['creategroupdesc'] = "Grupper lar deg lage diskusjoner med andre medlemmer og enkelt dele videoene dine med andre.";

/* Create Group Discussion */
$LANGS['discussiontitle'] = "Diskusjonstittel";
$LANGS['creatediscussiondesc'] = "Diskusjoner er deler av grupper der du diskuterer det angitte emnet.";

/* Search Results */
$LANGS['results'] = "{s} resultater";
$LANGS['relevance'] = 'Relevans';
$LANGS['viewcount'] = 'Visningstall';
$LANGS['searchrating'] = 'Vurdering';
$LANGS['newest'] = 'Nyeste';
$LANGS['nochannelsfound'] = 'Ingen Kanaler Funnet...';
$LANGS['noplfound'] = 'Ingen Spillelister Funnet...';
$LANGS['nogroupsfound'] = 'Ingen Grupper Funnet...';
$LANGS['uploaded'] = 'Lastet opp';
$LANGS['anytime'] = 'Når som helst';
$LANGS['partnervideos'] = 'Partnervideoer';
$LANGS['resultcount'] = 'resultater {r} av ca. {t}';
$LANGS['searchoptions'] = 'Search options';
$LANGS['resulttype'] = 'Result type';
$LANGS['duration'] = 'Duration';
$LANGS['durshort'] = 'Short (~4 minutes)';
$LANGS['durlong'] = 'Long (15~ minutes)';
$LANGS['features'] = 'Features';
$LANGS['novideosfoundfor'] = 'No videos found for';
$LANGS['noresultsfoundfor'] = 'No results found for';

/* Profile */
$LANGS['channelsuspended'] = 'Denne kontoen er suspendert.';
$LANGS['accountnotfound'] = 'Denne kontoen ble ikke funnet.';
$LANGS['channel'] = 'Kanal';
$LANGS['friends'] = 'Venner';
$LANGS['channelsubscribers'] = 'Abonnenter';
$LANGS['linkcomments'] = 'Kommentarer';
$LANGS['bulletins'] = 'Bulletiner';
$LANGS['editchannel'] = 'Rediger kanal';
$LANGS['type'] = 'Type';
$LANGS['joined'] = 'Bli med';
$LANGS['videoswatched'] = 'Videoer sett';
$LANGS['channelviews'] = 'Kanalvisninger';
$LANGS['age'] = 'Alder';
$LANGS['gender'] = 'Kjønn';
$LANGS['male'] = 'Mann';
$LANGS['female'] = 'Kvinne';
$LANGS['nonbinary'] = 'Non-Binary';
$LANGS['status'] = 'Status';
$LANGS['single_m'] = 'Singel';
$LANGS['single_f'] = 'Singel';
$LANGS['taken_m'] = 'Tatt';
$LANGS['taken_f'] = 'Tatt';
$LANGS['married_m'] = 'Gift';
$LANGS['married_f'] = 'Gift';
$LANGS['country'] = 'Land';
$LANGS['website'] = 'Nettsted';
$LANGS['hobbies'] = 'Interesser og hobbyer';
$LANGS['music'] = 'Musikk';
$LANGS['movies'] = 'Filmer og serier';
$LANGS['books'] = 'Bøker';
$LANGS['mostsub'] = 'Mest abonnerte';
$LANGS['report'] = 'Rapporter';
$LANGS['pfpviolation'] = 'brudd på profilbilde';
$LANGS['connectwith'] = 'Koble til med';
$LANGS['profilesendmessage'] = 'Send melding';
$LANGS['messagetoyourself'] = 'Du kan ikke sende meldinger til deg selv!';
$LANGS['logintomessage'] = 'Vennligst logg på for å sende meldinger!';
$LANGS['addcomment'] = 'Legg til kommentar';
$LANGS['logintocommentchannel'] = 'Vennligst logg inn for å kommentere';
$LANGS['sharechannel'] = 'Del kanal';
$LANGS['addfriend'] = 'Legg til som venn';
$LANGS['retractinvite'] = 'Trekk tilbake invitasjon';
$LANGS['removefriend'] = 'Fjern venn';
$LANGS['notfriendyourself'] = 'Du kan ikke legge deg til venner!';
$LANGS['logintofriend'] = 'Logg på for å legge til venner!';
$LANGS['blockuser'] = 'Blokker bruker';
$LANGS['channelembed'] = 'Bygg inn denne kanalen';
$LANGS['recentratings'] = 'Nylig aktivitet';
$LANGS['seeall'] = 'se alle';
$LANGS['writebulletin'] = 'Skriv bulletin';
$LANGS['bulletin'] = 'Bulletin';
$LANGS['subvideos1'] = 'Abonner på ';
$LANGS['subvideos2'] = "s videoer";
$LANGS['plvideos'] = 'Videoer';
$LANGS['playall'] = 'Spill alle';
$LANGS['featuredchannels'] = 'Utvalgte kanaler';
$LANGS['channelcomments'] = 'Kanalkommentarer';
$LANGS['bggraphic'] = 'bakgrunnsgrafikk';
$LANGS['reportthisuser'] = 'denne brukeren.';
$LANGS['norecentratings'] = 'Ingen nylig aktivitet funnet...';
$LANGS['nosubscribers'] = 'Ingen abonnenter...';
$LANGS['nosubscriptions'] = 'Ingen abonnementer...';
$LANGS['nofriends'] = 'Ingen venner...';
$LANGS['nobulletins'] = 'Ingen bulletiner...';
$LANGS['novideoschannel'] = 'Ingen videoer...';
$LANGS['nofavs'] = 'Ingen favorittvideoer...';
$LANGS['noplchannel'] = 'Ingen spillelister...';
$LANGS['pvideos'] = 'Private videoer';
$LANGS['pvideosallow'] = 'Du har ikke lov til å se disse videoene...';
$LANGS['plvideoamount'] = 'videoer';
$LANGS['bulletinpost'] = 'Bulletininnlegg';
$LANGS['deletebulletin'] = 'Slett bulletin';
$LANGS['body'] = 'Bropp';
$LANGS['bulletincomments'] = 'Bulletinkommentarer';
$LANGS['tocommentbulletin'] = 'for å sende et svar på denne bulletinen!';
$LANGS['addacomment'] = 'Legg til en kommentar:';
$LANGS['postreplychannel'] = 'Legg inn svar';
$LANGS['writecomment'] = 'Skriv kommentar';
$LANGS['for'] = 'for';
$LANGS['commentdesc'] = 'Kanalkommentarer vises på brukerens kanal.';
$LANGS['postbulletin'] = 'Legg inn bulletin';
$LANGS['writeabulletin'] = 'Skriv en bulletin';
$LANGS['bulletindesc'] = 'Bulletiner vises på dine egne og dine venners kanalsider.';
$LANGS['sharingoptions'] = 'Delingsalternativer';
$LANGS['sharingoptionsdesc'] = 'Det er 2 måter å dele denne kanalen på.';
$LANGS['sharingoptions1'] = '1. Kopier og lim inn denne lenken i en e-post eller direktemelding.';
$LANGS['sharingoptions2'] = "2. Send denne kanalen ved å bruke datamaskinens e-postprogram.";
$LANGS['clicktosend'] = 'Klikk for å sende!';
$LANGS['honorless'] = 'mindre';
$LANGS['activitycomment'] = 'kommentert';
$LANGS['activityfavorite'] = 'favoriserte en video';
$LANGS['activitylike'] = 'liked a video';
$LANGS['activityrating'] = 'vurderte en video:';
$LANGS['activityupload'] = 'lastet opp en ny video';
$LANGS['activityfriend'] = 'ble venner med';
$LANGS['activitysubscription'] = 'abonnerer på';
$LANGS['next'] = "Neste";
$LANGS['previous'] = "Forrige";
$LANGS['settings'] = "Innstillinger";
$LANGS['themescolors'] = "Temaer og farger";
$LANGS['channelmodules'] = "Moduler";
$LANGS['videosandpl'] = "Videoer og spillelister";
$LANGS['revert'] = "Tilbake! Jeg vil ha tilbake min gamle kanal";
$LANGS['all'] = "Alle";
$LANGS['uploads'] = "Opplastninger";
$LANGS['channelpl'] = "Spillelister";
$LANGS['backtoplaylists'] = "Tilbake til spillelister";
$LANGS['searchuploads'] = "Søk opplastinger";
$LANGS['info'] = "Informasjon";
$LANGS['viewcomments'] = "Se kommentarer, relaterte videoer og mer";
$LANGS['seeallcommentsandresponses'] = "Se alle kommentarer og videosvar";
$LANGS['pastethislink'] = "Lim inn denne lenken i en e-post eller direktemelding";
$LANGS['selectplaylist'] = "Velg spilleliste";
$LANGS['profilemsg'] = 'Kanalseerne vil se lenker her, inkludert "abonner" og "legg til som venn".';
$LANGS['profile'] = 'Profil';
$LANGS['profilechangessaved'] = 'Endringer lagret.';
$LANGS['posting'] = 'poster...';
$LANGS['name'] = 'Navn';
$LANGS['totaluploadviews'] = 'Totalt Antall Opplastingsvisninger';
$LANGS['channeldesc'] = 'Kanalbeskrivelse';
$LANGS['hometown'] = 'Hjemby';
$LANGS['occupation'] = 'Yrke';
$LANGS['companies'] = 'Bedrifter';
$LANGS['schools'] = 'Skoler';
$LANGS['interests'] = 'Interesser';
$LANGS['movies'] = 'Filmer';
$LANGS['featuredchannelsdefault'] = 'Klikk på "rediger" ovenfor for å angi kanaler du vil koble til.';
$LANGS['featuredchannelsdesc'] = 'Vennligst oppgi opptil 4 destinasjonskanaler i den rekkefølgen du vil at de skal vises på kanalen din, atskilt med komma og ingen mellomrom. Hvis du ikke oppgir noen kanaler, vil denne boksen ikke vises på kanalen din.';
$LANGS['backtochannel'] = "tilbake til {c} sin kanal";
$LANGS['refresh'] = "Oppdater";
$LANGS['whichcontent'] = "Hvilket innhold vil du vise?";
$LANGS['myuploadedvideos'] = "Mine Opplastede Videoer";
$LANGS['myfavorites'] = "Mine Favoritter";
$LANGS['alsoshowall'] = 'Vis også "Alle"-visningen';
$LANGS['featuredvideo'] = 'Fremhevet Video';
$LANGS['usemostrecent'] = 'Bruk den nyeste videoen fra mitt utvalgte sett';
$LANGS['autoplayfeatured'] = "Spill av fremhevet video automatisk";
$LANGS['areyousure'] = "Er du sikker på at du vil fortsette?";
$LANGS['unsavedchanges'] = "Er du sikker på at du vil endre temaet? Ulagrede endringer vil gå tapt.";
$LANGS['showadvancedoptions'] = "vis avanserte alternativer";
$LANGS['hideadvancedoptions'] = "skjul avanserte alternativer";
$LANGS['general'] = "Generelt";
$LANGS['colorpalettes'] = "Fargepaletter";
$LANGS['font'] = "Skrift";
$LANGS['wrappercolor'] = "Wrapperfarge";
$LANGS['wrappertextcolor'] = "Wrappertekstfarge";
$LANGS['wrapperlinkcolor'] = "Wrapperlinkfarge";
$LANGS['wrappertransparency'] = "Innpakningsgjennomsiktighet";
$LANGS['repeatbackground'] = "Gjenta bakgrunn";
$LANGS['titletextcolor'] = "Tekstfarge på Tittelen";
$LANGS['bodytextcolor'] = "Brødtekstfarge";
$LANGS['transparency'] = "Åpenhet";
$LANGS['bgimgdesc'] = "Last opp et bilde som vil vises som bakgrunn på kanalen din (maks. 2MB).";
$LANGS['channeltype'] = "Kanaltype";
$LANGS['channeltags'] = "Kanalkoder";
$LANGS['commaseparated'] = "(kommaseparert)";
$LANGS['channeltagsdesc'] = "Tags er nøkkelord som brukes for å hjelpe folk med å finne kanalen din.";

/* My Profile page */
$LANGS['myprofiledesc'] = 'Denne siden inneholder alle innstillingene for BitView-kanalen din.';
$LANGS['profileimages'] = 'Profilbilder';
$LANGS['avatar'] = 'Avatar';
$LANGS['backgroundimage'] = 'Bakgrunnsbilde';
$LANGS['deleteimage'] = 'Slett Bilde';
$LANGS['channelinformation'] = 'Kanalinformasjon';
$LANGS['genderrelationprivate'] = 'Privat';
$LANGS['fctitle'] = 'F.C. Tittel';
$LANGS['relationship'] = 'Forhold';
$LANGS['birthday'] = 'Bursdag';
$LANGS['showage'] = 'Vis Alder';
$LANGS['aboutme'] = 'Om Meg';
$LANGS['emailprefs'] = 'E-postinnstillinger';
$LANGS['emailpm'] = 'E-post meg på private meldinger';
$LANGS['emailcomm'] = 'E-post meg på videokommentarer';
$LANGS['emailsub'] = 'E-post meg om ukentlige abonnementshøydepunkter';
$LANGS['layoutprefs'] = 'Layoutinnstillinger';
$LANGS['bgcolor'] = 'Bakgrunnsfarge';
$LANGS['bgfixed'] = 'Fikset';
$LANGS['bgrepeat'] = 'Gjenta';
$LANGS['norepeat'] = 'Ingen Repetisjon';
$LANGS['repeat'] = 'Gjenta';
$LANGS['repeatx'] = 'Gjenta X';
$LANGS['repeaty'] = 'Gjenta Y';
$LANGS['bgposition'] = 'Posisjon';
$LANGS['top'] = 'Topp';
$LANGS['middle'] = 'Midt';
$LANGS['bottom'] = 'Bunn';
$LANGS['fontcolor'] = 'Skriftfarge';
$LANGS['titlefontcolor'] = 'Skriftfarge for Tittel';
$LANGS['linkcolor'] = 'Koblingsfarge';
$LANGS['hlfontcolor'] = 'Uthev Skriftfarge';
$LANGS['hlheadercolor'] = 'Uthev Overskrift';
$LANGS['hlinsidecolor'] = 'Uthev Innsiden';
$LANGS['headercolor'] = 'Vanlig Iverskrift';
$LANGS['insidecolor'] = 'Vanlig Innside';
$LANGS['font'] = 'Kanalfont';
$LANGS['featuredvideobox'] = 'Utvalgt videoboks';
$LANGS['subscribersbox'] = 'Abonnentboks';
$LANGS['subscriptionsbox'] = 'Abonnementsboks';
$LANGS['friendsbox'] = 'Venneboks';
$LANGS['bulletinsbox'] = 'Bulletinsboks';
$LANGS['videosbox'] = 'Videoboks';
$LANGS['favoritesbox'] = 'Favorittboks';
$LANGS['playlistsbox'] = 'Spillelisteboks';
$LANGS['commentsbox'] = 'Kommentarboks';
$LANGS['ratingsbox'] = 'Siste aktivitetsboks';
$LANGS['partnersettings'] = 'Partnerinnstillinger';
$LANGS['bannerimage'] = 'Bannerbilde';
$LANGS['minibannerimage'] = 'Minibannerbilde';
$LANGS['sideimage'] = 'Sidebilde';
$LANGS['recommendedsize'] = 'anbefalt størrelse';
$LANGS['bannerlink'] = 'Bannernettsted';
$LANGS['sideimagelink'] = 'Nettsted for sidebilde';
$LANGS['custombox'] = 'Egendefinert boks';
$LANGS['customboxtitle'] = 'Egendefinert bokstittel';
$LANGS['customboxcontent'] = 'Egendefinert boksinnhold';
$LANGS['savechanges'] = 'Lagre Endringer';
$LANGS['submitimage'] = 'Send inn Bilde';
$LANGS['overview'] = 'Oversikt';
$LANGS['profilesetup'] = 'Profiloppsett';
$LANGS['playbacksetup'] = 'Avspillingsoppsett';
$LANGS['emailoptions'] = 'E-postalternativer';
$LANGS['manageaccount'] = 'Administrer Konto';
$LANGS['chvideoviews'] = 'Videovisninger';
$LANGS['change'] = "endre";
$LANGS['mynetwork'] = "Mitt Nettverk";
$LANGS['contacts'] = "Kontakter";
$LANGS['chvideocomments'] = "Videokommentarer";
$LANGS['chmore'] = "Mer";
$LANGS['changepicture'] = "Endre Bilde";
$LANGS['changepicturedesc'] = "Du kan laste opp en JPG-, BMP- eller PNG-fil. Ikke last opp bilder som inneholder kjendiser, nakenhet, kunstverk eller opphavsrettsbeskyttede bilder. Bildet ditt vil vises som en kvadrat på 88px x 88px. <b> Maksimal filstørrelse er 2 MB.</b>";
$LANGS['describeyourself'] = "Beskriv deg Selv";
$LANGS['personaldetails'] = "Personlige detaljer";
$LANGS['jobscareer'] = "Jobb / Karriere";
$LANGS['education'] = "Utdanning";
$LANGS['videoplaybackquality'] = "Videoavspillingskvalitet";
$LANGS['videoplaybackqualitydesc'] = "Velg standardinnstillingen for å se videoer";
$LANGS['alwayshd'] = "Spill alltid av videoer i HD-kvalitet";
$LANGS['neverhd'] = "Spill aldri av videoer i HD-kvalitet";
$LANGS['currentemail'] = "Gjeldende E-postadresse";
$LANGS['changeemailaddress'] = "Endre E-postadresse";
$LANGS['changeemail'] = "Endre E-post";
$LANGS['partnerimages'] = "Partnerbilder";
$LANGS['partnerimagelinks'] = "Koblinger til Partnerbilder";
$LANGS['accountstatuscg'] = "Kontostatus: Retningslinjer for fellesskapet";
$LANGS['accountstatuscopy'] = "Kontostatus: Opphavsrett";
$LANGS['changeusername'] = "Endre Brukernavn";
$LANGS['changepassword'] = "Endre Passord";
$LANGS['deleteaccount'] = "Slett Konto";
$LANGS['goodaccount'] = "Kontoen din har god anseelse.";
$LANGS['accountstrike'] = "Du har {s} advarsler. Vær forsiktig!";
$LANGS['accountstrikes'] = "Du har {s} advarsler. Vær forsiktig!";
$LANGS['cannotchangeusername'] = "Du kan ikke endre brukernavnet ditt ennå! Vent til ";
$LANGS['usernamechangedesc'] = "Du vil kun kunne endre brukernavnet ditt en gang i året, så velg ditt nye brukernavn med omhu.";
$LANGS['newusername'] = "Nytt Brukernavn";
$LANGS['currentpassword'] = "Gjeldende Passord";
$LANGS['newpassword'] = "Nytt Passord";
$LANGS['confirmnewpassword'] = "Bekreft Nytt Passord";
$LANGS['enterpassword'] = "Av sikkerhetsgrunner, vennligst skriv inn passordet ditt";

/* Upload page */
$LANGS['uploadpagetitle'] = 'Videoopplasting';
$LANGS['step1of2'] = 'Trinn 1 av 2';
$LANGS['step2of2'] = 'Trinn 2 av 2';
$LANGS['videocategory'] = 'Videokategori';
$LANGS['tagsdesc'] = 'Tags er nøkkelord som brukes for å hjelpe folk med å finne videoen din.<br> <i>(kommaseparert)</i>';
$LANGS['requiredfield'] = '(* indikerer obligatorisk felt)';
$LANGS['datemapoptions'] = 'Dato- og Kartalternativer';
$LANGS['optional'] = '(valgfritt)';
$LANGS['chooseoptions'] = 'velg alternativer';
$LANGS['lessoptions'] = 'mindre alternativer';
$LANGS['addressrecorded'] = 'Adresse Tegistrert';
$LANGS['uploadcontinue'] = 'Last opp en Video...';
$LANGS['file'] = 'Fil';
$LANGS['broadcastoptions'] = 'Kringkastingsalternativer';
$LANGS['uploadvideo'] = 'Last opp Video';
$LANGS['needfilevideotoupload'] = 'Vennligst velg en videofil å laste opp!';
$LANGS['aboutuploading'] = 'Om opplasting...';
$LANGS['uploaddesc1'] = 'Opplastninger tar vanligvis 1-5 minutter per MB på en høyhastighetsforbindelse, og konvertering av videoen din tar noen minutter.';
$LANGS['videolimit1'] = 'Videoen din er begrenset til 100MB - maksimal videolengde er 15 minutter.';
$LANGS['videolimit2'] = 'Videoen din er begrenset til 2 GB - maksimal videolengde er 15 minutter.';
$LANGS['partnervideolimit1'] = 'Videoen din er begrenset til 100MB - maksimal videolengde er 30 minutter.';
$LANGS['partnervideolimit2'] = 'Videoen din er begrenset til 2 GB - maksimal videolengde er 30 minutter.';
$LANGS['myvideosdesc'] = 'Etter opplasting kan du redigere eller fjerne denne videoen når som helst under "<a href="/my_videos">Mine videoer</a>-koblingen øverst på siden.';
$LANGS['newuploader'] = 'Bruk den nye videoopplastingen';
$LANGS['olduploader'] = 'Bruk den gamle videoopplastingen';
$LANGS['videoadded'] = 'Videoen din ble lagt til!';
$LANGS['videoaddeddesc'] = 'Videoen din blir behandlet og vil være tilgjengelig for visning om noen minutter.';
$LANGS['thankyou'] = 'Takk';
$LANGS['sharelink'] = 'Del videolenken din! Kopier og lim inn nedenfor:';
$LANGS['embedlink'] = 'Spill av denne videoen direkte PÅ nettstedet ditt! Kopier og lim inn følgende kodebit:';
$LANGS['allrequiredinfo'] = 'Vennligst fyll ut alle obligatoriske felter!';
$LANGS['videoscanbe'] = 'Videos can be...';
$LANGS['uploadhd'] = 'High Definition';
$LANGS['uploadsize'] = 'Up to 2 GB in size';
$LANGS['uploadlength'] = 'Up to 15 minutes in length';
$LANGS['uploadlengthpartners'] = 'Up to 1 hour in length';
$LANGS['uploadformats'] = 'A wide variety of formats';
$LANGS['basicuploader'] = 'Upload problems? Try the <a href="/my_videos_upload_basic">basic uploader</a> (works on older computers and web browsers).';
$LANGS['uploadinstruction1'] = '<strong>Important:</strong> Do not upload any TV shows, music videos, music concerts, or commercials without permission unless they consist entirely of content you created yourself.';
$LANGS['uploadinstruction2'] = 'The <a href="/guidelines">Community Guidelines</a> can help you determine whether your video infringes someone else\'s copyright.';
$LANGS['uploadinstruction3'] = 'By clicking "Upload Video", you are representing that this video does not violate BitView\'s <a id="terms-of-use-link" href="/terms">Terms of Use</a> and that you own all copyrights in this video or have authorization to upload it.';
$LANGS['fileuploaded'] = 'Your file has been uploaded. We are now processing the video...';
$LANGS['videosettingssaved'] = 'Your video settings have been saved.';
$LANGS['timeremaining'] = 'About {m} min. remaining...';
$LANGS['minuteremaining'] = 'Less than a minute remaining...';
$LANGS['preview'] = 'Preview';
$LANGS['processing'] = 'Processing';
$LANGS['generatingpreviews'] = 'Generating previews...';
$LANGS['errorpreview'] = "Error: couldn't generate preview";
$LANGS['infoandprivacy'] = "Video information and privacy settings";
$LANGS['sharingoptions'] = "Sharing options";
$LANGS['url'] = "URL";
$LANGS['durationerror'] = "You can only upload videos up to {n} minutes in length.";

/* Video Response Upload */
$LANGS['postingresponse'] = "You are posting a Video Response to: ";
$LANGS['responsessofar'] = "{n} Video Response(s) so far";
$LANGS['chooseavideo'] = "Choose a Video";
$LANGS['uploadavideo'] = "Upload a Video";
$LANGS['responsesdesc1'] = "<h4>What is a Video Response?</h4><p>Ever wanted to talk back to a video? Now's your chance – you can upload a response to this video and we'll link them together.</p>";
$LANGS['responsesdesc2'] = "<h4>How do I post a Video Response?</h4><p>You can record a new video, choose from the videos that you already have or create and upload a new video. Select the option on the left that best suits your needs.</p>";
$LANGS['responsesdesc3'] = '<h4>Oops! I actually meant to post a text comment. How do I do this?</h4><p>Return to the video (by hitting the "back" button on your browser or clicking the title of the video at the top of this page) and click "Post a Text Comment".</p>';
$LANGS['choosevideotitle'] = "Choose one of your existing videos as a response";
$LANGS['selectvideo'] = "Select the video that you want to respond with:";
$LANGS['useselectedvideo'] = "Use the selected video";
$LANGS['uploadvideoresponse'] = "Upload your Video Response";
$LANGS['clickstart'] = 'Click "Start" to begin uploading your Video Response.';
$LANGS['start'] = 'Start';

/* Partners */
$LANGS['partnerhead'] = 'Partnerskap';
$LANGS['partnertitle'] = 'Partner med BitView';
$LANGS['partnerdesc'] = "Du har flotte videoer og et voksende publikum. La BitView hjelpe deg å ta det til neste nivå gjennom vårt partnerprogram.";
$LANGS['applynow'] = 'Søk nå';
$LANGS['contentpartners'] = 'Innholdspartnere';
$LANGS['partnerbenefits'] = 'Partnerfordeler';
$LANGS['partnerbenefitsdesc'] = 'Det er mange fordeler ved å bli BitView-partner. Noen av dem inkluderer:<br><br>- Merkevarebygging: skiller deg ut med tilpasset merkevarebygging, som inkluderer bannere, en egendefinert boks for kanalen din og et partnermerke på alle videoene dine.<br><br>- Det er flere fordeler kommer i fremtiden!';
$LANGS['qualificationsfaq'] = 'Kvalifikasjoner og vanlige spørsmål';
$LANGS['qualificationsfaqdesc'] = 'For å kvalifisere deg for BitView Partner-programmet, må du oppfylle noen minimumskriterier:<br><br>- Du lager originale videoer som egner seg for nettstrømming.<br><br>- Du har > 75 abonnenter.<br><br>- Kontoen din bryter ingen <a href="/guidelines">retningslinjer for fellesskapet.</a>';

/* Staff */
$LANGS['bvstaff'] = 'BitView-ansatte';
$LANGS['bvstaffdesc'] = "Dette er en liste over personer som har jobbet (eller fortsatt jobber) på BitView - som holder nettstedet i live - slik at brukere kan uttrykke seg.";
$LANGS['owners'] = 'Eiere';
$LANGS['ownerdesc'] = 'Folk som - for et sjokkerende faktum - eier BitView-tingen.';
$LANGS['coowndev'] = 'Medeier og <br>-Utvikler';
$LANGS['owndev'] = 'Eier og <br>-Utvikler';
$LANGS['coownserver'] = 'Medeier &<br>Servereier/utvikler';
$LANGS['modsanddevs'] = 'Moderatorer og Utviklere';
$LANGS['modsanddevsdesc'] = 'Folk som holder nettstedet trygt og oversiktlig. Har du problemer med kontoen din? Du bør kontakte dem.';
$LANGS['moderator'] = 'Moderator';
$LANGS['moddev'] = 'Utvikler &<br>Moderator';
$LANGS['lettertitle'] = 'Brev til alle som hjalp til med nettsiden';
$LANGS['letter'] = "Kjære medeiere, utviklere og moderatorer av BitView,<br><br>
                 På vegne av hele BitView-teamet vil jeg uttrykke min dypeste takknemlighet for ditt eksepsjonelle engasjement og harde arbeid. Som en av eierne fyller det meg med enorm stolthet å være vitne til veksten og suksessen til videodelingsplattformen vår, og det hadde ikke vært mulig uten dine uvurderlige bidrag.
                 <br><br>
                 Til resten av medeierne, takk for din urokkelige støtte og visjon. Din forpliktelse til plattformens utvikling og forbedring har vært medvirkende til å forme BitView.net til det bemerkelsesverdige fellesskapet det er i dag. Ditt lederskap og strategiske veiledning har vært avgjørende for å navigere i utfordringene og mulighetene som har kommet vår vei.
                 <br><br>
                 Til våre talentfulle utviklere har din tekniske ekspertise og innovative ideer forvandlet BitView til en banebrytende plattform som perfekt representerer hvordan YouTube så ut i tiden. Dine utallige timer med koding, problemløsning og funksjonsimplementering har hevet brukeropplevelsen og gjort plattformen vår til et knutepunkt for kreativitet og underholdning. Din dedikasjon til å avgrense funksjonaliteten og ytelsen til nettstedet har vært virkelig prisverdig.
                 <br><br>
                 Til våre flittige moderatorer gir jeg min dypeste takknemlighet for å opprettholde integriteten og sikkerheten til samfunnet vårt. Din årvåkenhet med å håndheve reglene og retningslinjene, sikre respektfulle interaksjoner og raskt ta opp eventuelle problemer som oppstår har vært avgjørende for å fremme et innbydende miljø for alle brukere. Din innsats for å holde BitView et sted for konstruktivt engasjement og positivt innhold er svært prisverdig.
                 <br><br>
                 Sammen, som et samlet team, har vi oppnådd betydelige milepæler og overvunnet en rekke hindringer. Suksessen til BitView er et bevis på den kollektive innsatsen og lidenskapen hver og en av dere bringer til bordet. Ditt engasjement for vår felles visjon har virkelig vært inspirerende, og jeg er takknemlig for å ha slike eksepsjonelle personer ved min side.
                 <br><br>
                 Når vi fortsetter å vokse og utvikle oss, la oss verne om båndene vi har knyttet og forbli forpliktet til verdiene som definerer vår lille side. Sammen vil vi fortsette den nostalgituren og gi en plattform for skapere å vise frem talentene sine.
                 <br><br>
                 Nok en gang, takk: Medeiere, utviklere og moderatorer, for ditt urokkelige engasjement, ekspertise og urokkelige støtte. Ditt harde arbeid har ikke gått ubemerket hen, og jeg er utrolig stolt over å være en del av dette bemerkelsesverdige teamet.
                 <br><br>
                 Fortsett å uttrykke deg selv,<br>
                 <3 vistafan12 (oversatt)";
$LANGS['backtobitview'] = "Tilbake til BitView";

/* My Friends */
$LANGS['myfriends'] = 'Vennene mine';
$LANGS['invites'] = 'Invitasjoner';
$LANGS['myinvites'] = 'Mine Invitasjoner';
$LANGS['incominginvites'] = 'Innkommende Invitasjoner';
$LANGS['noinvites'] = 'Du har ingen invitasjoner...';
$LANGS['actions'] = 'Handlinger';
$LANGS['retract'] = 'Trekk Tilbake';

/* History */
$LANGS['clearhistory'] = "Tøm Visningshistorikk";
$LANGS['noviewinghistory'] = "Det er ingen videoer i historien din.";
$LANGS['addto'] = "Add to";
$LANGS['sortorder'] = "Order";
$LANGS['sortnewest'] = "Newest";
$LANGS['sortoldest'] = "Oldest";
$LANGS['sortmostviewed'] = "Most viewed";
$LANGS['sortlongest'] = "Longest";
$LANGS['sortshortest'] = "Shortest";
$LANGS['sortaz'] = "A-Z";
$LANGS['sortza'] = "Z-A";
$LANGS['newpltitle'] = "Playlist title";
$LANGS['newpldesc'] = "Playlist description";
$LANGS['newpltags'] = "Playlist tags";
$LANGS['newplbutton'] = "Create playlist";
$LANGS['addvideos'] = "Add videos";
$LANGS['liked'] = "Liked";
$LANGS['mylikedvideos'] = "My Liked Videos";
$LANGS['savedtoplaylist'] = "Videos saved to playlist(s) successfully!";
$LANGS['sureremovevideos'] = "Are you sure you want to delete the selected videos?";
$LANGS['remove'] = "Remove";
$LANGS['plvideoamountsingular'] = "video";

/* QuickList */
$LANGS['playquicklist'] = "Spill Hurtigliste";
$LANGS['clearquicklist'] = "Slett Hurtigliste";
$LANGS['noquicklist'] = "Det er ingen videoer i hurtiglisten din.";
$LANGS['noquicklistdesc'] = "Hurtigliste lar deg lage en videoliste for senere visning. Klikk på " + " (nederst til venstre) på en video for å legge den til hurtiglisten din. For å se listen din, se for hurtiglistelinjen under hvilken som helst video du ser på.";
$LANGS['quicklistcleared'] = "Hurtiglisten din har blitt slettet.";
$LANGS['addedtoquicklist'] = "Lagt til <br> Hurtigliste";
$LANGS['queue'] = "Queue";
$LANGS['playqueue'] = "Play Queue";
$LANGS['clearqueue'] = "Clear Queue";
$LANGS['addtoqueue'] = "Add to queue";
$LANGS['addedtoqueue'] = "Added to <br> queue";

/* About */
$LANGS['aboutus'] = 'Om Oss';
$LANGS['abouttitle'] = 'Hva er BitView?';
$LANGS['aboutdesc'] = 'BitView er en måte å få videoene dine til folk som betyr noe for deg. Med BitView kan du:';
$LANGS['about1'] = 'Vis frem favorittvideoene dine til verden';
$LANGS['about2'] = 'Ta videoer av dine hunder, katter og andre kjæledyr';
$LANGS['about3'] = 'Blogg videoene du tar med digitalkameraet eller mobiltelefonen';
$LANGS['about4'] = 'Vis videoer sikkert og privat til venner og familie rundt om i verden';
$LANGS['about5'] = '... og mye, mye mer!';
$LANGS['aboutsignup'] = '<a href="/signup">Registrer deg nå</a> og åpne en gratis konto.';
$LANGS['abouthelp'] = 'For å lære mer om tjenesten vår, se vår <a href="help">Hjelp</a>-seksjon.';
$LANGS['aboutmail'] = 'Vennligst <a href="mailto:bitview@vistafan12.eu.org">kontakt oss</a>.';

/* Community Guidelines */
$LANGS['bvguidelines'] = 'BitView Retningslinjer for fellesskapet';
$LANGS['cgtitle1'] = 'Respekter BitView-fellesskapet';
$LANGS['cgtitle2'] = "Ikke kryss linjen";
$LANGS['cgtitle3'] = 'Vi håndhever disse retningslinjene';
$LANGS['cgtitle4'] = 'BitView er for fellesskapet';
$LANGS['cgtitle5'] = 'Tips for fellesskapets retningslinjer';
$LANGS['cgdesc1'] = "Vi ber ikke om den typen respekt som er forbeholdt nonner, eldre og hjernekirurger. Vi mener ikke misbruk nettstedet. Hver kule ny fellesskapsfunksjon på BitView involverer et visst nivå av tillit. Vi stoler på at du er ansvarlig, og millioner av brukere respekterer denne tilliten. Vær en av dem.";
$LANGS['cgdesc2'] = "Her er noen sunne regler som vil hjelpe deg å unngå problemer:";
$LANGS['cgdesc3'] = "Vennligst ta disse reglene på alvor og ta dem til hjertet. Ikke prøv å se etter smutthull eller prøv å advokate deg rundt retningslinjene – bare forstå dem og prøv å respektere ånden de ble opprettet. Hvis du vil ha flere detaljer, sjekk ut våre <a href='#tips'>retningslinjer for fellesskapet</a>.";
$LANGS['cgdesc4'] = "Ok, denne handler mer om oss enn deg. BitView-ansatte gjennomgår flaggede videoer 24 timer i døgnet, syv dager i uken for å finne ut om de bryter retningslinjene våre for fellesskapet. Når de gjør det, fjerner vi dem . Noen ganger bryter ikke en video retningslinjene våre for fellesskapet, men er kanskje ikke passende for alle. Disse videoene kan være aldersbegrensede. Kontoer straffes for brudd på retningslinjene for fellesskapet, og alvorlige eller gjentatte brudd kan føre til kontooppsigelse. Hvis kontoen din er avsluttet, får du ikke lov til å opprette nye kontoer. For mer informasjon om hvordan retningslinjene for fellesskapet håndheves og konsekvensene av å bryte dem, kan du gå til <a href='/help'>brukerstøtten</a>. ";
$LANGS['cgdesc5'] = "Husk at dette er ditt fellesskap! Hver eneste bruker av BitView gjør siden til det den er, så ikke vær redd for å grave deg inn og bli involvert!";
$LANGS['cgdesc6'] = "Det var det! Takk for at du leste!";
$LANGS['cgdesc7'] = "Vil du ha litt mer innsikt i grensene og unntakene i retningslinjene for fellesskapet? Her er noen nyttige eksempler og tips:";
$LANGS['rule1'] = "BitView er ikke for pornografi eller seksuelt eksplisitt innhold. Hvis dette beskriver videoen din, selv om det er en video av deg selv, ikke legg den ut på BitView. Vær også oppmerksom på at vi jobber tett med rettshåndhevelse og vi rapporterer utnyttelse av barn.";
$LANGS['rule2'] = "Ikke legg ut videoer som viser dårlige ting som dyremishandling, narkotikamisbruk, mindreårige som drikker og røyker, eller bomber.";
$LANGS['rule3'] = "Grafisk eller umotivert vold er ikke tillatt. Hvis videoen din viser at noen blir fysisk skadet, angrepet eller ydmyket, ikke legg den ut.";
$LANGS['rule4'] = "BitView er ikke et sjokkside. Ikke legg ut grove videoer av ulykker, døde kropper eller lignende ting ment å sjokkere eller avsky.";
$LANGS['rule5'] = "Respekter opphavsretten. Last kun opp videoer du har laget eller som du har tillatelse til å bruke. Dette betyr at du ikke laster opp videoer du ikke har laget, eller bruk innhold i videoene dine som noen andre eier opphavsrett til, for eksempel musikkspor, utdrag av opphavsrettsbeskyttede programmer eller videoer laget av andre brukere, uten nødvendige autorisasjoner.";
$LANGS['rule6'] = "Vi oppfordrer til ytringsfrihet og forsvarer alles rett til å uttrykke upopulære synspunkter. Men vi tillater ikke hatytringer (ytringer som angriper eller fornedrer en gruppe basert på rase eller etnisk opprinnelse, religion, funksjonshemming , kjønn, alder, veteranstatus og seksuell legning/kjønnsidentitet). Dette gjelder også fremme av ekstremistiske ideologier i et positivt lys.";
$LANGS['rule7'] = "Ting som rov atferd, forfølgelse, trusler, trakassering, trusler, invadering av personvernet, avsløring av andres personopplysninger, og oppfordring til andre til å begå voldelige handlinger eller til å bryte vilkårene for bruk tas svært alvorlig. Alle som blir tatt i å gjøre disse tingene kan bli permanent utestengt fra BitView.";
$LANGS['rule8'] = "Alle hater spam. Ikke lag villedende beskrivelser, tagger, titler eller miniatyrbilder for å øke antallet visninger. Det er ikke greit å legge ut store mengder umålrettet, uønsket eller repeterende innhold, inkludert kommentarer og privat meldinger.";
$LANGS['rule9'] = "La oss holde nettstedet trygt. Ikke prøv å brute force en konto du ikke eier. Dessuten er det ikke tillatt å dele en kontos påloggingsinformasjon offentlig.";
$LANGS['rule10'] = "Multi-kontoer suger. Vi vil ha ekte tall på videoer og kanaler. Ikke bruk mer enn én konto for å rangere videoer og/eller kommentarer. Du har ikke lov til å bruke flere kontoer for å abonnere på deg selv heller.";
$LANGS['rule11'] = "Brote du en av disse reglene og kontoen din har blitt suspendert? Det sier seg selv at det ikke aksepteres å unngå denne straffen. Hver ny konto som er opprettet av en suspendert person vil automatisk bli slettet .";
$LANGS['cglist1'] = "Ha det gøy med siden. Det er mye å se her, og mange folk lager fantastiske ting - en av dem kan være du! Utstyret blir billigere og enklere å bruke hele tiden, så dykk inn og nyt.";
$LANGS['cglist2'] = "La folk få vite hva du synes. Tilbakemeldinger er en del av opplevelsen, og når det gjøres med respekt, kan det være en fin måte å få venner på, dele historier og gjøre tiden din på BitView rikere. Så la være kommenter, ranger videoer, lag dine egne svar på videoer som påvirker deg, delta i konkurranser av interesse — det er mye som skjer og mange måter å delta på.";
$LANGS['cglist3'] = "Du liker kanskje ikke alt du ser. Noe av innholdet her kan støte deg - hvis du finner ut at det bryter med våre vilkår for bruk, klikk deretter på knappen som sier 'Flagg' under videoen du ser på for å sende den inn for vurdering av BitView-ansatte. Hvis den ikke gjør det, kan du vurdere å bare klikke på noe annet — hvorfor kaste bort tid på å se videoer du ikke liker?";
$LANGS['thebitviewteam'] = "— BitView-teamet";
$LANGS['cgcat1'] = "Sex og nakenhet";
$LANGS['cgcat2'] = "Hatytringer";
$LANGS['cgcat3'] = "Sjokkerende og ekkelt";
$LANGS['cgcat4'] = "Farlige ulovlige handlinger";
$LANGS['cgcat5'] = "Barn";
$LANGS['cgcat6'] = "Opphavsrett";
$LANGS['cgcat7'] = "Personvern";
$LANGS['cgcat8'] = "Trakassering";
$LANGS['cgcat9'] = "Imitasjon";
$LANGS['cgcat10'] = "Trusler";
$LANGS['cgcat1desc'] = "Det meste av nakenhet er ikke tillatt, spesielt hvis det er i en seksuell kontekst. Generelt hvis en video er ment å være seksuelt provoserende, er det mindre sannsynlig at den er akseptabel for BitView. Det er unntak for noen pedagogisk, dokumentarisk og vitenskapelig innhold, men bare hvis det er det eneste formålet med videoen og den ikke er gratis grafisk. For eksempel vil en dokumentar om brystkreft være passende, men å legge ut klipp utenfor kontekst fra dokumentaren er det kanskje ikke. Dette gjelder også for animert innhold.";
$LANGS['cgcat2desc'] = 'Hatytringer" refererer til innhold som fremmer hat mot medlemmer av en beskyttet gruppe. For eksempel kan rasistisk eller sexistisk innhold betraktes som hatytringer. Noen ganger er det en fin linje mellom hva som er og hva som er ikke betraktet som hatefulle ytringer. For eksempel er det generelt greit å kritisere en nasjon, men ikke greit å komme med fornærmende generaliseringer om mennesker av en bestemt nasjonalitet.';
$LANGS['cgcat3desc'] = "Verden er et farlig sted. Noen ganger blir folk skadet og det er uunngåelig at disse hendelsene kan bli dokumentert på BitView. Det er imidlertid ikke greit å legge ut voldelig eller blodig innhold som først og fremst er ment å være sjokkerende , oppsiktsvekkende eller respektløst. Hvis en video er spesielt grafisk eller urovekkende, bør den balanseres med ekstra kontekst og informasjon. For eksempel kan det være hensiktsmessig å inkludere et klipp fra et slakteri i en video om fabrikkoppdrett. Men å sette sammen urelaterte og grufulle klipp av dyr som blir slaktet i en video kan betraktes som umotiverte hvis formålet er å sjokkere i stedet for å illustrere.";
$LANGS['cgcat4desc'] = "Selv om det kanskje ikke virker rettferdig å si at du ikke kan vise noe på grunn av hva seerne teoretisk kan gjøre som svar, trekker vi grensen for innhold som er ment å oppfordre til vold eller oppmuntre til farlige, ulovlige aktiviteter som har en iboende risiko for alvorlig fysisk skade eller død. Dette betyr at du ikke legger ut videoer om ting som instruksjonsbombeproduksjon, ninja-attentattrening, snikskytterangrep, videoer som trener terrorister eller tips om ulovlige gateløp. Eventuelle skildringer som disse bør være pedagogiske eller dokumentar og bør ikke være utformet for å hjelpe eller oppmuntre andre til å etterligne dem.";
$LANGS['cgcat5desc'] = "Videoer som involverer barn (alle under 18 år) er spesielt sensitive. Videoer som inneholder barn skal aldri være seksuelt antydende eller voldelige. Vær forsiktig når du legger ut noe som involverer et barn. Hvis du deler et privat øyeblikk eller en hjemmefilm, vurder å gjøre den til en privat video slik at bare familie og venner kan se den. Dessuten, ved å godta <a href='/terms'>vilkårene for bruk</a>, bekrefter du at du er over 13 år. Kontoer som tilhører mindreårige brukere vil bli suspendert.";
$LANGS['cgcat6desc'] = "Når du lager noe originalt, eier du opphavsretten til det. På samme måte, når andre mennesker lager innhold, kan de ha opphavsrett til det. Som et kreativt fellesskap er det viktig at alle på BitView respekterer andres opphavsrett. Hvis du ikke er sikker på om noe vil krenke noens opphavsrett, er det tryggeste å lage noe helt originalt, med bilder og lyd du har laget. Hvis alt er ditt, trenger du aldri å bekymre deg for opphavsretten — du eier den. Hvis du har spilt inn noe fra en DVD, filmet TV-skjermen eller lastet ned en video på nettet, ikke legg den ut med mindre du har tillatelse.";
$LANGS['cgcat7desc'] = "Hvis en video du har spilt inn inneholder personer som er lett identifiserbare og som ikke har samtykket til å bli filmet, er det en sjanse for at de vil sende inn en personvernklage for å få den fjernet. Vi varsler hvis det skjer og gi deg en sjanse til å redigere og laste opp på nytt videoen din før vi reagerer på klagen. Hvis vi fjerner videoen din av personvernhensyn, ikke last opp en annen versjon med de samme personene. Sjansen er stor for at disse personene vil sende inn en ny personvernklage eller rapportere deg for trakassering. Ikke legg ut andres personlige opplysninger, inkludert telefonnumre, adresser, kredittkortnumre og offentlige ID-er. Vi er seriøse med å holde brukerne våre trygge og suspendere kontoer som krenker folks personvern.";
$LANGS['cgcat8desc'] = "Det handler om respekt. BitView handler om å dele og samhandle med fellesskapet på respektfulle måter. Hvis du ikke er sikker på om en video eller kommentar du har laget går over grensen, følg en enkel tommelfingerregel: hvis du ikke vil si det til noens ansikt, ikke si det på BitView. Og hvis du ønsker å angripe, trakassere, nedverdige eller utgi deg for andre, gå et annet sted.";
$LANGS['cgcat9desc'] = "Å utgi seg for en annen bruker ved å kopiere noens eksakte kanaloppsett, bruke et lignende brukernavn eller utgi seg for denne personen i kommentarer, e-poster eller videoer anses som trakassering. Hvis du vil beholde kontoen din, hold deg unna deltar i noen form for etterligning eller trakasserende aktivitet på nettstedet.";
$LANGS['cgcat10desc'] = "Brukere skal ikke føle seg truet når de er på BitView. Punktum. Ikke legg igjen truende kommentarer på andres videoer.";

/* Contests */
$LANGS['monthlycontest'] = "Månedlig konkurranse";
$LANGS['monthlycontestschedule'] = "Månedlig videokonkurranseplan";
$LANGS['whatisit'] = "Hva er det?";
$LANGS['thismonthcontest'] = "Denne Måneden";
$LANGS['lastmonthwinners'] = "Siste Måneds Vinnere";
$LANGS['howtoenter'] = "Hvordan kommer jeg inn?";
$LANGS['whowins'] = "Hvem vinner?";
$LANGS['whowinsdesc'] = "Vinneren vil bli plukket ut i slutten av måneden av BitView-personalet.";
$LANGS['theprize'] = "Prisen?";
$LANGS['theprizedesc'] = "Berømmelse, formue og misunnelse av alle øyne.";
$LANGS['contestsuggestion'] = 'Har du et forslag til en månedlig videokonkurranse? Vennligst <a href="mailto:bitview@vistafan12.eu.org">Fortell oss</a> om det.';

/* Help */
$LANGS['q1'] = 'Sp: Hvordan kan jeg dele videoene mine og lenke til dem fra nettstedet mitt?';
$LANGS['a1'] = 'Sv: <a href="/sharing">Hvordan dele og koble til videoene dine</a>';
$LANGS['q2'] = 'Sp: Hva slags videoer kan jeg laste opp?';
$LANGS['a2'] = 'Sv: Du kan laste opp hvilken som helst personlig video du vil dele med verden. Vi tillater ikke nakenhet, og videoen din må passe for alle målgrupper.
<br/>
<br/>
Dette gir imidlertid fortsatt mye rom for kreativitet!! Eier du en <a href="results?search=dog&t=Search+Videos">hund</a> eller en <a href="/results?search=cat&t=Search+Videos">katt</a>? Har du reist på ferie i <a href="/results?search=mexico&t=Search+Videos">Mexico</a>? Bor du i <a href="/results?search=netherlands&t=Search+Videos">Nederland</a>?
<br/>
<br/>
Dette er bare noen eksempler på videoene våre brukere laster opp. Til slutt kjenner du deg selv best. Hva vil <i>du</i> fange på video?';
$LANGS['q3'] = 'Q: Hvor lang kan videoen min være?';
$LANGS['a3'] = 'A: Videoen må være under 15 minutter lang og mindre enn 2 GB (100 MB hvis du bruker en gammel nettleser).';
$LANGS['q4'] = 'Q: Hvilke videofilformater kan jeg laste opp?';
$LANGS['a4'] = 'A: BitView aksepterer videofiler fra de fleste digitale kameraer og fra mobiltelefoner i filformatene .WMV, .AVI, .MOV, .MPG, .MP4.';
$LANGS['q5'] = 'Q: Hvordan kan jeg forbedre videoene mine?';
$LANGS['a5'] = 'Sv: Vi oppfordrer deg til å redigere videoene dine med programvare som <a href="https://windows-movie-maker-vista.en.softonic.com/" target="_blank ">Windows Movie Maker</a> (inkludert med hver Windows-installasjon), eller <a href="https://www.apple.com/lae/imovie/" target="_blank">Apple iMovie</a> . Ved å bruke disse programmene kan du enkelt redigere videoene dine, legge til lydspor osv.';
$LANGS['q6'] = 'Sp: Beholder jeg opphavsrett og andre juridiske rettigheter til videoene mine?';
$LANGS['a6'] = 'A: Ja. Du beholder alle rettigheter til innholdet ditt. BitView påtar seg ingen opphavsrett til materialet ditt.';
$LANGS['q7'] = 'Q: Hva er din policy for brudd på opphavsrett?';
$LANGS['a7'] = "Sv: BitView respekterer rettighetene til opphavsrettsinnehavere og utgivere og aksepterer kun videoopplastinger fra personer som har alle nødvendige rettigheter til det opplastede materialet. Vår policy er å svare på eventuelle varsler om påståtte krenkelser som overholde Digital Millennium Copyright Act (DMCA). Hvis vi mottar et varsel eller på annen måte har grunn til å tro at innhold du har sendt inn krenker en annen parts opphavsrett, kan kontoen din bli avsluttet og videoen fjernet fra BitView.";
$LANGS['q8'] = 'Q: Hvordan rapporterer jeg brudd på opphavsretten?';
$LANGS['a8'] = 'Sv: Hvis du tror at noen andre har lastet opp det opphavsrettsbeskyttede innholdet ditt uten din tillatelse, oppfordrer vi deg til å kontakte vedkommende for å løse eventuelle uenigheter med dem direkte. Du kan også kontakte supportteamet vårt ved å bruke denne <a href="mailto:bitview@vistafan12.eu.org">e-posten</a>.';
$LANGS['q9'] = 'Q: Hva om jeg har blitt feilaktig anklaget for brudd på opphavsretten?';
$LANGS['a9'] = "Sv: Vi gir deg beskjed hvis vi mottar en opphavsrettsklage på noe av videoinnholdet ditt som er vert på BitView. Vi gir deg muligheten til å svare på riktig måte.";
$LANGS['q10'] = 'Q: Hva gjør du for å forhindre at innhold som bryter retningslinjene dine vises i BitView?';
$LANGS['a10'] = 'Sv: Vi gjør en foreløpig gjennomgang av opplastede videoer gjennom både en manuell og automatisert prosess. Selv om vi prøver vårt beste for å oppdage og fjerne videoer som bryter retningslinjene våre, er gjennomgangsprosessen vår primært fokusert på å fjerne voksent innhold eller åpenbare brudd på opphavsretten, og er ikke skuddsikker. Vi oppfordrer imidlertid seerne våre til å varsle oss når de oppdager brudd på retningslinjene eller opphavsrettsproblemer -- vi har en prosess for å vurdere rapporterte brudd på retningslinjene, og reagerer på rapporterte brudd på opphavsrett under Digital Millennium Copyright Act.';
$LANGS['q11'] = 'Q: Har du en Discord-server eller Twitter?';
$LANGS['a11'] = 'Ja! Vi har faktisk en Discord-server og Twitter. Du kan bli med på Discord-serveren ved å klikke <a href="https://discord.gg/wgGaqCmwuQ">her</a>, og følge oss på Twitter <a href="https://twitter.com/bitview_">her</a>.';
$LANGS['q12'] = "Q: Jeg bruker en gammel nettleser mens jeg er på BitView og kan derfor ikke se videoer. Hva kan jeg gjøre?";
$LANGS['activate'] = 'Aktiver';
$LANGS['deactivate'] = 'Deaktiver';
$LANGS['flashdisclaimer'] = "<b>Merk:</b> BitViews Flash Player tilbys som et kompatibilitetsalternativ. Hvis nettleseren din støtter BitViews HTML5-spiller, bør du ikke aktivere dette alternativet.";

/* BitView on your site */
$LANGS['bvsitetitle1'] = "Grunnleggende";
$LANGS['bvsitetitle2'] = "API-er og brukerengasjement";
$LANGS['bvsitedesc1'] = 'Uansett hvilken tilstedeværelse du har på Internett – et stort nettsted, en blogg, en sosial nettverksside eller stort sett alt annet – er det mange måter å integrere BitView på. Fra enkle videoinnbygginger til våre full-powered API-er, kan du integrere video på alle nivåer av teknisk ekspertise.';
$LANGS['bvsitedesc2'] = 'Å bringe BitView til nettstedet ditt er mer enn bare å legge til noen av de tusenvis av videoer som er tilgjengelige på BitView. Det holder de besøkende interessert og tillater selvuttrykk og interaksjon med en av favoritttjenestene deres. Og det bringer nettstedet, bloggen eller siden din inn i BitView-videofellesskapet – et internasjonalt nettverk av brukere, skapere og nettsteder koblet sammen gjennom en enorm samling av onlinevideoer.';
$LANGS['bvsitedesc3'] = "Vi har fremhevet noen typiske måter å integrere videoinnhold nedenfor - bare klikk på pilen ved siden av spørsmålet for å få svaret. Hvis du har spørsmål eller forslag, eller prosjekter som du ønsker oss å vite om, vennligst legg igjen spørsmålene på vår <a href='https://discord.gg/wgGaqCmwuQ'>Discord-server</a>.";
$LANGS['bvsitesectiontitle1'] = "Hvordan legger jeg til en video på bloggen eller nettsiden min?";
$LANGS['bvsitesectiontitle2'] = "Hvordan legger jeg til en video på min sosiale nettverksside?";
$LANGS['bvsitesectiontitle3'] = "Jeg jobber for et stort blogg-/nettfirma. Hvordan kan video øke brukerengasjementet på siden vår?";
$LANGS['bvsitesectiontitle4'] = "Vi har en side og vi har våre egne videoer. Kan vi legge disse ut på siden vår ved hjelp av BitView?";
$LANGS['bvsitesection1desc1'] = "Du må redigere HTML-en til blogginnlegget eller siden din – dette bør være relativt enkelt. I Blogger, for eksempel, klikker du bare på &quot;Rediger HTML&quot;-fanen.";
$LANGS['bvsitesection1desc2'] = "Deretter går du til videoen du vil ha, og se etter 'Bygg inn'-boksen i delen &quot;Om denne videoen&quot;. Hvis du kopierer HTML-koden som er der til nettstedet ditt, opprettes en innebygd spiller; videoen spilles av på nettstedet ditt når brukeren klikker på &quot;Spill av&quot;-knappen.";
$LANGS['bvsitesection1desc3'] = "Du kan endre størrelsen på spilleren ved å redigere feltene <em>object width=&quot;425&quot;</em> og <em>height=&quot;350&quot;</em> i begge begynnelsen og slutten av den innebygde spillerkoden. Sørg for at størrelsene du velger har samme forhold som standardnumrene, slik at videoen ikke blir strukket – bare multipliser bredden med 0,8235 for å få høyden.";
$LANGS['bvsitesection2desc1'] = "Å legge til videoer i profilene dine på sosiale nettverk som SpaceHey er en fin måte å dele videoer eller favoritter med venner på. Eller, hvis du promoterer noe (som bandet ditt) på SpaceHey, vil videoer bidra til å tiltrekke besøkende til siden din, som deretter kan dele lenken med vennene sine. De sosiale nettverkssidene har lignende måter å legge til videoer på, så vi bruker SpaceHey som et eksempel.";
$LANGS['bvsitesection2desc2'] = 'Logg på SpaceHey-profilen din, klikk deretter på "Rediger profil"-knappen.';
$LANGS['bvsitesection2desc3'] = "Deretter går du til videoen du vil ha, og se etter 'Bygg inn'-boksen i delen &quot;Om denne videoen&quot;. Hvis du kopierer HTML-koden som er der til nettstedet ditt, opprettes en innebygd spiller.";
$LANGS['bvsitesection2desc4'] = "Du kan endre størrelsen på spilleren ved å redigere feltene objektbredde=&quot;425&quot; og høyde=&quot;350&quot; både på begynnelsen og slutten av den innebygde spillerkoden. Pass på at størrelsene du velg ha samme forhold som standardtallene, slik at videoen ikke blir strukket – bare multipliser bredden med 0,8235 for å få høyden.";
$LANGS['bvsitesection2desc5'] = 'Klikk "Forhåndsvisning", og deretter "Send".';
$LANGS['bvsitesection3desc1'] = "Video er mye mer engasjerende enn tekst. Den tiltrekker seg flere brukere og holder dem på nettstedet ditt lenger. BitView har et stort arkiv med Internett-videoinnhold sammen med søke-, avspillings- og API-verktøyene som kan lages legge til video enklere for deg.";
$LANGS['bvsitesection3desc2'] = "Når du ønsker å øke engasjementet, prøv å bruke video som en måte å starte diskusjon på eller lage en kommentar ved å skape mer kontekst for brukerne dine:";
$LANGS['bvsitesection4desc1'] = "Det er veldig enkelt å bygge opp din egen side med dine egne videoer gratis. Alt du trenger å gjøre er å laste opp videoene til BitView først. Det koster ingenting, og vi dekker hosting- og strømmekostnader. Det er ikke bare en flott måte å øke brukerengasjementet på nettstedet ditt, men det er veldig enkelt og gratis også.";
$LANGS['bvsitesection4desc2'] = "Når du har lastet opp videoene kan du trekke dem tilbake til siden:";
$LANGS['bvsitesection4desc3'] = "<b>Bygg inn videoer én etter én:</b> Gå til videoen du vil legge på nettstedet ditt, og se etter 'Bygg inn'-boksen ved siden av videospilleren . Hvis du kopierer HTML-koden som er der inn i bloggen din, opprettes en innebygd spiller; videoen spilles av på nettstedet ditt når brukeren klikker på &quot;Spill av&quot;-knappen.";

/* RSS Feeds */
$LANGS['rsstitle1'] = "Hva er RSS-feeder?";
$LANGS['rsstitle2'] = "Hvordan få tilgang til RSS-feeder";
$LANGS['rsstitle3'] = "Hvordan abonnere på BitViews RSS-feeder";
$LANGS['rssdesc1'] = "Really Simple Syndication (RSS) er et XML-basert format som brukes for innholdsdistribusjon og syndikering. Ved å abonnere på RSS-feeder kan du motta tilpasset, oppdatert informasjon fra dine favorittinnholdskilder på nettet uten å måtte sjekke nettstedet regelmessig for oppdateringer.";
$LANGS['rssdesc2'] = "Nyhetslesere som viser RSS-feeds fra nettsidene du spesifiserer – de sjekker RSS-feedene du har abonnert på og viser nye elementer fra hver feed. Du kan laste ned nyhetsleserapplikasjoner til datamaskinen din, og her er også mange populære nettbaserte nyhetslesere tilgjengelig, for eksempel Google Reader og Bloglines. Noen nettlesere og e-postapplikasjoner har også innebygd RSS-funksjoner.";
$LANGS['rssdesc3'] = "Du kan se en liste over mange tilgjengelige nyhetslesere på <a href='http://en.wikipedia.org/wiki/List_of_feed_aggregators'>Wikipedia</a> (på engelsk). "; // Use your language's Wikipedia article if possible -- translator note: norwegian article on this doesnt exist yet.
$LANGS['rssdesc4'] = "BitView tilbyr flere RSS-feeds for kategoriserte grupper av videoer (som nylig lastet opp, mest sett osv.) samt tilpassede feeds for brukere og tags.";
$LANGS['rssdesc5'] = "For å abonnere på kategoriserte grupper med videoer, gå ganske enkelt til kategorien du ønsker (for eksempel &quot;<a href='/browse'>Mest sett - i dag</a>&quot;) . Klikk deretter på den oransje 'RSS'-knappen. Dette bør utløse den valgte nyhetsleseren til å legge til abonnementet.";
$LANGS['rssdesc6'] = "Hvis nettleseren din har RSS-funksjoner, kan du legge til feeden der. Kommandoen varierer mellom nettlesere, men kan vanligvis finnes på 'Fil' eller 'Bokmerker'-menyene, og vil bli kalt noe som &quot;Abonner på denne siden&quot; eller &quot;Nytt bokmerke&quot;.";
$LANGS['rssthispage'] = "RSS denne siden";

/* TestView */
$LANGS['testviewdesc'] = "Velkommen til TestView, vår idé-inkubator. Det er her BitView-ingeniører og -utviklere tester ut oppskrifter og blandinger som ikke er helt ferdige og inviterer deg til å fortelle oss hvordan de kommer." ;
$LANGS['flashvideo'] = "Flash-video";
$LANGS['flashvideodesc'] = "Nettleseren din støtter ikke HTML5-video? Ikke bekymre deg! Prøv vår Flash-spiller.";
$LANGS['feather'] = "Fjær";
$LANGS['featherdesc'] = "Se BitView-videoer på en side med svært lav ventetid.";
$LANGS['tryitout'] = "Prøv det ut";
$LANGS['disabletest'] = "Deaktiver";
$LANGS['timemachine'] = "Tidsmaskin";
$LANGS['timemachinedesc'] = "Gå tilbake i tid, spol tilbake hver dato på BitView til slutten av 2000-tallet.";
$LANGS['lightsout'] = "Slukker";
$LANGS['lightsoutdesc'] = "Lei av å se det lyseste hvite på skjermen din? Mal den svart og prøv ut et nytt kult grensesnitt.";
$LANGS['featherenabled'] = '"Fjær" er nå aktivert!';
$LANGS['timemachineenabled'] = '"Tidsmaskin" er nå aktivert!';
$LANGS['lightsoutenabled'] = '"Lyser ut" er nå aktivert!';
$LANGS['featherdisabled'] = '"Fjær" er nå deaktivert!';
$LANGS['timemachinedisabled'] = '"Tidsmaskin" er nå deaktivert!';
$LANGS['lightsoutdisabled'] = '"Lyser ut" er nå deaktivert!';

/* Email Confirmation */
$LANGS['checkemail'] = "Please Check Your Email";
$LANGS['checkemaildesc'] = "A confirmation email has been sent to your email address. Please click on the link in the email to verify your email address. If you do not recieve the message within a few minutes, please also check your bulk or spam folders.";
$LANGS['resendemail'] = "Resend Confirmation Email";

/* Footer */
$LANGS['youraccount'] = 'Din Konto';
$LANGS['inbox'] = 'Innboks';
$LANGS['footmore'] = 'mer...';
$LANGS['helpinfo'] = 'Hjelp';
$LANGS['helpcenter'] = 'Få Hjelp';
$LANGS['ourtwitter'] = 'Twitter';
$LANGS['ourdiscord'] = 'Discord';
$LANGS['guidelines'] = 'Guidelines';
$LANGS['partnerships'] = 'Partners';
$LANGS['terms'] = 'Terms';
$LANGS['about'] = 'About';
$LANGS['privacypolicy'] = 'Privacy';
$LANGS['languageselector'] = 'Language';
$LANGS['currentlanguage'] = 'Gjeldende Språk';
$LANGS['showlanguages'] = 'Vis språk';
$LANGS['setlanguagepref'] = 'Angi din Språkpreferanse';
$LANGS['programs'] = 'Programmer';
$LANGS['developers'] = 'Utviklere';
$LANGS['bitviewblog'] = 'BitView-blogg';
$LANGS['policy'] = 'Retningslinjer';
$LANGS['discover'] = 'Oppdag';
$LANGS['bvphone'] = 'BitView på Telefonen Din';
$LANGS['bvsite'] = 'BitView på Nettstedet Ditt';
$LANGS['bvrss'] = 'BitView RSS-feeder';
$LANGS['mobile'] = 'Mobil';
?>
