<?php
/* General stuff */
$LANGS['language'] = 'Português (Brasil)';
$LANGS['languageenglish'] = 'Portuguese (Brazil)';
$LANGS['languagecode'] = 'pt_BR.UTF-8'; /* Leave the ".UTF-8" in the end as-is, as it might break some dates */
$LANGS['languagechange'] = 'O idioma foi alterado para Português (Brasil).';
$LANGS['numberformat'] = 1; /* If your language uses comma separators (example: 1,000,000), value will be 1. If it uses dots (example: 1.000.000) or doesn't use separators, value will be 0.*/

/* Language window */
$LANGS['welcometobitview'] = 'Bem-vindo(a) ao BitView!';
$LANGS['languagesuggestion'] = 'Idioma sugerido (nós alteramos sua preferência para este idioma):';
$LANGS['languagesuggestiondesc1'] = 'Para alterar o seu idioma preferido, por favor utilize o seletor de idioma no rodapé (no fim desta página).';
$LANGS['languagesuggestiondesc2'] = 'Clique em "OK" para confirmar essa configuração, ou clique em "Cancelar" para visualizar esse site em inglês.';

/* Time, dates, etc */
$LANGS['second'] = 'segundo';
$LANGS['minute'] = 'minuto';
$LANGS['hour'] = 'hora';
$LANGS['day'] = 'dia';
$LANGS['week'] = 'semana';
$LANGS['month'] = 'mês';
$LANGS['year'] = 'ano';
$LANGS['seconds'] = 'segundos';
$LANGS['minutes'] = 'minutos';
$LANGS['hours'] = 'horas';
$LANGS['days'] = 'dias';
$LANGS['weeks'] = 'semanas';
$LANGS['months'] = 'meses';
$LANGS['years'] = 'anos';
$LANGS['ago'] = '{t} atrás';
$LANGS['january'] = 'Janeiro';
$LANGS['february'] = 'Fevereiro';
$LANGS['march'] = 'Março';
$LANGS['april'] = 'Abril';
$LANGS['may'] = 'Maio';
$LANGS['june'] = 'Junho';
$LANGS['july'] = 'Julho';
$LANGS['august'] = 'Agosto';
$LANGS['september'] = 'Setembro';
$LANGS['october'] = 'Outubro';
$LANGS['november'] = 'Novembro';
$LANGS['december'] = 'Dezembro';
$LANGS['shorttimeformat'] = '%e %b %Y';
$LANGS['videotimeformat'] = '%e de %B de %Y';
$LANGS['longtimeformat'] = '%e de %B de %Y';
$LANGS['timehourformat'] = '%e de %B de %Y, %k:%M:%S';
$LANGS['myvideostimeformat'] = '%a, %e %b %Y, %k:%M:%S';
$LANGS['blogpostformat'] = '%e de %B de %Y';
$LANGS['timenumberformat'] = 'd/m/y';
$LANGS['monthformat'] = '%B %Y';

/* Header */
$LANGS['home'] = 'Página inicial';
$LANGS['videos'] = 'Vídeos';
$LANGS['channels'] = 'Canais';
$LANGS['community'] = 'Comunidade';
$LANGS['search'] = 'Pesquisar';
$LANGS['login'] = 'Fazer login';
$LANGS['or'] = 'ou';
$LANGS['signup'] = 'Criar conta';
$LANGS['logout'] = 'Sair';
$LANGS['upload'] = 'Enviar vídeos';
$LANGS['subscriptions'] = 'Inscrições';
$LANGS['history'] = 'Histórico';
$LANGS['account'] = 'Conta';
$LANGS['myvideos'] = 'Meus vídeos';
$LANGS['favorites'] = 'Favoritos';
$LANGS['playlists'] = 'Listas de reprodução';
$LANGS['help'] = 'Ajuda';
$LANGS['suggestions'] = 'Sugestões';
$LANGS['quicklist'] = 'Lista rápida';
$LANGS['browse'] = 'Procurar';
$LANGS['messagesmenu'] = 'Mensagens';

/* Homepage */
$LANGS['viewall'] = 'exibir todas';
$LANGS['videoviews'] = 'exibições';
$LANGS['beingwatched'] = 'Vídeos sendo assistidos agora';
$LANGS['featured'] = 'Vídeos em destaque';
$LANGS['recommendedforyou'] = 'Recomendado para você';
$LANGS['mostpopular'] = 'Mais populares';
$LANGS['inboxstats'] = 'Caixa de entrada e estatísticas';
$LANGS['profilesettings'] = 'configurações do perfil';
$LANGS['messages'] = 'Mensagens';
$LANGS['message'] = 'Mensagem';
$LANGS['comments'] = 'Comentários';
$LANGS['comment'] = 'Comentário';
$LANGS['sharedwithyou'] = 'Compartilhados com Você';
$LANGS['sharedwithyousingular'] = 'Compartilhado com Você';
$LANGS['videoresponses'] = 'Vídeo-respostas';
$LANGS['videoresponse'] = 'Vídeo-resposta';
$LANGS['friendinvites'] = 'Convites de amizade';
$LANGS['friendinvite'] = 'Convite de amizade';
$LANGS['subscribers'] = 'Inscrições';
$LANGS['subscriber'] = 'Inscrição';
$LANGS['totalviews'] = 'Exibições totais';
$LANGS['sendmessage'] = 'enviar mensagem';
$LANGS['whatsnew'] = "O que há de novo";
$LANGS['readmore'] = 'Leia mais no nosso blog';
$LANGS['videocontest'] = 'Concurso de vídeo';
$LANGS['joincontest'] = 'Entre agora no concurso!';
$LANGS['personalize'] = 'Deseja personalizar esta página inicial?';
$LANGS['signinnow'] = '<a href="/login">Faça login</a> ou <a href="/signup">inscreva-se</a> agora!';
$LANGS['nowconverting'] = "Este vídeo está em conversão, aguarde alguns minutos.";
$LANGS['modules'] = "Adicionar / remover módulos";
$LANGS['friendactivity'] = "Atividade dos amigos";
$LANGS['customizehomepage'] = "Personalizar página inicial";
$LANGS['customizethehomepage'] = "Personalizar a página inicial";
$LANGS['customizehomepagedesc'] = "Selecione os módulos que você queira ver em sua página.";
$LANGS['displaypreferences'] = "Preferências de exibição";
$LANGS['thefeed'] = "O Feed";
$LANGS['thefeeddesc'] = "Combine todos os seus módulos em apenas um único feed.";
$LANGS['friendactivitytitle'] = "Atividades dos amigos - As pessoas podem ver o que eu faço?";
$LANGS['friendactivitydesc'] = "Esta seção mostra a suas amizades confirmadas as ações que você faz de forma pública em suas atividades recentes. Por exemplo, se você marcar um vídeo como favorito, o mesmo pode aparecer na caixa de atividades recentes de seu canal, e também pode aparecer na página inicial de suas amizades.";
$LANGS['feedfeatured'] = "Vídeos em destaque";
$LANGS['feedbeingwatched'] = "Vídeos sendo assistindos agora";
$LANGS['feedrecommended'] = "Vídeos recomendados";
$LANGS['homenosubscriptions'] = "Você ainda não se inscreveu em um canal.";
$LANGS['homenosubscriptionsdesc'] = "Quando você se inscrever em algum canal, os novos vídeos enviados por eles serão exibidos nesta página.";
$LANGS['homenofriendactivity'] = "Seus amigos não têm estado ativos ultimamente.";
$LANGS['homenofriendactivitydesc'] = "Você pode adicionar novas amizades, Quando você adicioná-las, as atividades deles serão exibidas aqui nesta página.";
$LANGS['homeediting'] = "Editando";
$LANGS['homedisplay'] = "Mostrar como";
$LANGS['homerows'] = "Número de linhas a exibir";
$LANGS['gridview'] = "Visão em grade";
$LANGS['listview'] = "Visão em lista";

/* Page title */
$LANGS['hometitle'] = "BitView de {n}";
$LANGS['channeltitle'] = "Canal de {n}";
$LANGS['signintitle'] = "Fazer login";
$LANGS['historytitle'] = "Histórico de exibição";
$LANGS['favtitle'] = "Favoritos";
$LANGS['pltitle'] = "Listas de reprodução";
$LANGS['partnerprogram'] = "Programa de parceria";

/* Notifications */
$LANGS['searcherror'] = 'Sua pesquisa precisa ter mais de 2 caracteres.';
$LANGS['addvideoplaylist1'] = "Você adicionou";
$LANGS['addvideoplaylist2'] = 'vídeos a sua lista de reprodução.';
$LANGS['addfavorite1'] = "Você favoritou";
$LANGS['addfavorite2'] = 'vídeos.';
$LANGS['groupdoesnotexist'] = "Este grupo não existe.";
$LANGS['uploaddisabled'] = 'O envio de vídeos foi desativado para manutenção.';
$LANGS['10vidsday'] = 'Você não pode enviar mais de 10 vídeos por dia. Por favor, tente novamente amanhã.';
$LANGS['3mins'] = 'Aguarde 3 minutos até enviar outro vídeo.';
$LANGS['backgroundsuccess'] = 'A imagem de fundo foi enviada com sucesso.';
$LANGS['backgrounderror'] = 'A imagem de fundo deve ser menor que 2MB em tamanho e ser um arquivo de imagem suportado.';
$LANGS['backgrounddeleted'] = 'A imagem de fundo foi removida com sucesso.';
$LANGS['bannersuccess'] = 'O banner foi enviado com sucesso.';
$LANGS['bannererror'] = 'O banner deve ser menor que 2MB e ser um arquivo de imagem suportado.';
$LANGS['bannerdeleted'] = 'O banner foi removida com sucesso.';
$LANGS['minibannersuccess'] = 'O mini banner foi enviado com sucesso.';
$LANGS['minibannererror'] = 'O mini banner deve ser menor que 2MB e ser um arquivo de imagem suportado.';
$LANGS['minibannerdeleted'] = 'O mini banner foi removido com sucesso.';
$LANGS['sideimagesuccess'] = 'A imagem de lado foi enviada com sucesso.';
$LANGS['sideimageerror'] = 'A imagem de lado deve ser menor que 2MB e ser um arquivo de imagem suportado.';
$LANGS['sideimagedeleted'] = 'A imagem de lado foi removida com sucesso.';
$LANGS['avatarsuccess'] = 'A imagem de perfil foi enviada com sucesso.';
$LANGS['avatarerror'] = 'A imagem de perfil deve ser menor que 1MB e ser um arquivo de imagm suportado.';
$LANGS['avatardeleted'] = 'A imagem de perfil foi removida com sucesso.';
$LANGS['changessaved'] = 'As mudanças foram salvas com sucesso.';
$LANGS['profilesdisabled'] = 'Os perfis foram desativados para manutenção.';
$LANGS['bulletinposted'] = 'O seu "bulletin" foi enviado com sucesso.';
$LANGS['channelcommentsent'] = 'O comentário foi enviado no canal com sucesso.';
$LANGS['somethingwentwrong'] = 'Algo de errado ocorreu.';
$LANGS['replysubmitted'] = 'Sua resposta foi enviada.';
$LANGS['onlyonecomment'] = 'Você apenas pode deixar um só comentário.';
$LANGS['vpnbrowser'] = "Você não pode utilizar uma VPN para criar uma conta.";
$LANGS['torbrowser'] = "Você não pode utilizar TOR para criar uma conta.";
$LANGS['captchaincorrect'] = "Você não inseriu o código corretamente.";
$LANGS['toomanyaccounts'] = 'Você tem contas demais.';
$LANGS['banned2times'] = "Você já foi banido duas vezes. Você não pode criar mais contas.";
$LANGS['nohistory'] = "Você não assistiu nenhum vídeo durante esta sessão.";
$LANGS['historycleared'] = 'Seu histórico de exibição foi limpo.';
$LANGS['watchdisabled'] = 'A exibição de vídeos foi desativada para manutenção.';
$LANGS['videonotexist'] = 'Este vídeo não existe, ou foi removido por violação dos Termos de Uso.';
$LANGS['responseerror'] = 'Algo deu errado ao enviar sua vídeo-resposta! Por favor cheque a URL.';
$LANGS['responseexist'] = 'O vídeo já foi enviado anteriormente.';
$LANGS['responseadded'] = 'Vídeo-resposta adicionada.';
$LANGS['responseaccepted'] = 'A vídeo-resposta foi aceita.';
$LANGS['60secscomment'] = 'Aguarde 60 segundos antes de adicionar outro comentário.';
$LANGS['plnotexist'] = "Esta lista de reprodução não existe.";
$LANGS['positionnotexist'] = "Esta posição não existe.";
$LANGS['positionchanged'] = "A posição do vídeo foi alterada.";
$LANGS['invalidurl'] = 'URL inválida.';
$LANGS['videopladded'] = 'Vídeo adicionado.';
$LANGS['videoalreadyinpl'] = 'Este vídeo já está na lista de reprodução.';
$LANGS['plvideoremoved'] = 'Vídeo removido.';
$LANGS['plinfochanged'] = 'As informações da lista de reprodução foram alteradas com sucesso.';
$LANGS['pltitleneeded'] = 'Você deve colocar um título para a lista de reprodução.';
$LANGS['flashenabled'] = 'Adobe Flash Player ativado.';
$LANGS['flashdisabled'] = 'Adobe Flash Player desativado.';
$LANGS['messagesent'] = 'Mensagem enviada com sucesso.';
$LANGS['usernotexist'] = "Esse usuário não existe.";
$LANGS['nocriteria'] = "Você não tem os critérios necessários.";
$LANGS['alreadypartner'] = 'Você já foi aceito no programa de parceiros.';
$LANGS['alreadyapplied'] = 'Você já se aplicou para a qualificação.';
$LANGS['applicationsent'] = 'Sua aplicação foi enviada.';
$LANGS['joinedgroup'] = 'Você entrou no grupo com sucesso.';
$LANGS['leftgroup'] = 'Você saiu do grupo com sucesso.';
$LANGS['grouprequest'] = 'Você enviou uma solicitação de entrada ao grupo! Agora você deve esperar ser aceito.';
$LANGS['groupdeleted'] = 'Grupo apagado com sucesso.';
$LANGS['groupvideoadded'] = 'O vídeo foi enviado.';
$LANGS['groupvideoalreadyadded'] = 'Você já enviou este vídeo.';
$LANGS['groupvideonotowned'] = "Você não é dono deste vídeo.";
$LANGS['3groups'] = 'Você apenas pode ter três grupos.';
$LANGS['groupnameempty'] = 'O nome do grupo não pode ser vazio.';
$LANGS['groupdescempty'] = 'A descrição do grupo não pode estar vazia.';
$LANGS['groupnoimage'] = 'Você deve enviar uma imagem para o grupo.';
$LANGS['groupimageerror'] = 'As imagens do grupo devem ser menor que 1MB e devem ser um arquivo suportado.';
$LANGS['groupcreated'] = 'Grupo criado com sucesso.';
$LANGS['urlnotvalid'] = "Este link não é uma URL de vídeo válida.";
$LANGS['discussiondeleted'] = 'Tópico apagado com sucesso.';
$LANGS['videodeleted'] = 'Vídeo apagado com sucesso.';
$LANGS['pldeleted'] = 'Lista de reprodução apagada com sucesso.';
$LANGS['invitesent'] = 'Convite de amizade enviado com sucesso.';
$LANGS['descriptionchanged'] = 'A descrição foi alterada.';
$LANGS['emptymessage'] = 'Você não pode enviar mensagens vazias.';
$LANGS['styleupdated'] = 'O estilo do grupo foi atualizado com sucesso.';
$LANGS['imageupdated'] = 'A imagem do grupo foi atualizada com sucesso.';
$LANGS['plcreated'] = 'Lista de reprodução criada com sucesso!';
$LANGS['discussiontitle2chars'] = 'O título deve ser maior que 2 caracteres.';
$LANGS['discussiondesc10chars'] = 'As descrições devem ser maiores que 10 caracteres.';
$LANGS['5discussionsday'] = 'Você apenas pode fazer 5 discussões por dia.';
$LANGS['discussionsuccess'] = 'Discussão criada com sucesso.';
$LANGS['memberaccepted1'] = '';
$LANGS['memberaccepted2'] = 'foi aceito(a) com sucesso.';
$LANGS['memberdeclined1'] = '';
$LANGS['memberdeclined2'] = 'foi recusado(a) com sucesso.';
$LANGS['videoaccepted'] = 'O vídeo foi aceito com sucesso.';
$LANGS['bulletindeleted'] = '"Bulletin" apagado com sucesso.';
$LANGS['messagedeleted'] = 'Mensagem apagada com sucesso.';
$LANGS['responsedeleted'] = 'Vídeo-resposta apagada com sucesso.';
$LANGS['flagmod'] = 'Você não pode reportar um usuário com poderes de moderação.';
$LANGS['userflagged'] = 'Usuário reportado com sucesso.';
$LANGS['discussionreplysubmitted'] = 'Resposta enviada com sucesso.';
$LANGS['discussionreplyempty'] = 'Uma reposta não pode ser vazia.';

/* Watch */
$LANGS['moreinfo'] = 'mais info';
$LANGS['lessinfo'] = 'menos info';
$LANGS['category'] = 'Categoria';
$LANGS['recordedon'] = 'Gravado em';
$LANGS['location'] = 'Local';
$LANGS['tags'] = 'Palavras-chave';
$LANGS['embed'] = 'Incorporar';
$LANGS['partnervideo'] = 'Vídeo de parceiro';
$LANGS['subscribe'] = 'Inscrever-se';
$LANGS['unsubscribe'] = 'Desinscrever';
$LANGS['nodesc'] = 'Sem descrição...';
$LANGS['logintosub'] = 'Entre para se inscrever.';
$LANGS['logintosubbox'] = 'Quer se inscrever?';
$LANGS['subyourself'] = 'Você não pode se inscrever a si mesmo(a).';
$LANGS['videoowner'] = 'Opções do dono(a) do vídeo';
$LANGS['editvideo'] = 'Editar vídeo';
$LANGS['insight'] = 'Insight';
$LANGS['morefrom'] = 'Mais de:';
$LANGS['relatedvideos'] = 'Vídeos relacionados';
$LANGS['novideosfound'] ='Nenhum vídeo encontrado...';
$LANGS['morevideos'] = 'Ver todos os vídeos';
$LANGS['changeplayersize'] = 'Mudar tamanho do reprodutor';
$LANGS['newwindow'] = 'Assistir este vídeo em uma nova janela';
$LANGS['featuredtext'] = 'Este vídeo está em Destaque. Quer ver mais vídeos em destaque? <a href="/browse?t=2">Clique aqui</a>.';
$LANGS['ratings'] = 'avaliações';
$LANGS['rating'] = 'avaliação';
$LANGS['favorite'] = 'Favorito';
$LANGS['addtofav'] = 'Adicionar aos Favoritos';
$LANGS['removefav'] = 'Remover dos Favoritos';
$LANGS['favadded'] = 'Esse vídeo foi <strong>adicionado</strong> aos seus <a href="/my_favorites">Favoritos</a>.';
$LANGS['favremoved'] = 'Esse vídeo foi <strong>removido</strong> dos seus <a href="/my_favorites">Favoritos</a>.';
$LANGS['undo'] = 'Desfazer';
$LANGS['thanksforrating'] = 'Obrigado por avaliar!';
$LANGS['playlistdesc'] = 'Para adicionar um novo vídeo à sua lista de reprodução, vá para a página <a href="/my_playlists">"Minhas listas de reprodução"</a>.';
$LANGS['addtoplaylist'] = 'Adicionar à lista de reprodução';
$LANGS['addtoplaylistsuccess'] = 'O vídeo foi adicionado a lista de reprodução.';
$LANGS['share'] = 'Compartilhar';
$LANGS['flag'] = 'Denunciar';
$LANGS['flagthisvid'] = 'Denunciar esse vídeo';
$LANGS['removeflag'] = 'Remover denúncia';
$LANGS['flagnote'] = "Antes de reportar: Tenha certeza que o vídeo quebra alguma regra. Não reporte apenas porque você não gosta do vídeo, ou você estará atrapalhando o trabalho dos moderadores.";
$LANGS['statadded'] = 'Adicionado';
$LANGS['statviews'] = 'Exibições';
$LANGS['statratings'] = 'Avaliações';
$LANGS['statresponses'] = 'Respostas';
$LANGS['statcomments'] = 'Comentários';
$LANGS['statfavorited'] = 'Favoritos';
$LANGS['statsdata'] = 'Estatísticas e dados';
$LANGS['honors'] = 'Honras para este vídeo';
$LANGS['mostviewed'] = 'Mais vistos';
$LANGS['topfavorited'] = 'Mais adotados como favoritos';
$LANGS['times'] = 'vezes';
$LANGS['mostdiscussed'] = 'Mais discutidos';
$LANGS['toprated'] = 'Melhor aaliados';
$LANGS['videolinks'] = 'Sites linkando a este video';
$LANGS['clicksfrom'] = 'cliques de';
$LANGS['responses'] = 'Vídeo-respostas';
$LANGS['responsespost'] = 'Publicar uma vídeo-resposta';
$LANGS['textcomments'] = 'Comentários de texto';
$LANGS['commentpost'] = 'Publicar um comentário de texto';
$LANGS['commentonthisvideo'] = 'Comentar neste vídeo';
$LANGS['postcomment'] = 'Publicar comentário';
$LANGS['remainingcounter'] = 'Caracteres restantes';
$LANGS['nocomments'] = '<b>Não há comentários</b> para este vídeo.';
$LANGS['noresponses'] = '<b>Não há respostas</b> para este vídeo.';
$LANGS['commviewall'] = 'Exibir tudo';
$LANGS['delete'] = 'Apagar';
$LANGS['reply'] = 'Responder';
$LANGS['commentlogin'] = 'Gostaria de comentar?';
$LANGS['commentlogindesc'] = '<a href="/signup">Junte-se ao BitView</a> em uma conta grátis ou <a href="/login">entre</a> se você já é um membro.';
$LANGS['logintoresponse'] = 'Entre para publicar uma Vídeo-resposta';
$LANGS['logintocomment'] = 'Entre para publicar um comentário';
$LANGS['logintofav'] = 'Quer adicionar aos Favoritos? <a href="/login">Faça login</a> ou <a href="/signup">Crie uma conta</a> agora mesmo!';
$LANGS['logintopl'] = 'Quer adicionar à lista de reprodução? <a href="/login">Faça login</a> ou <a href="/signup">Crie uma conta</a> agora mesmo!';
$LANGS['logintoflag'] = 'Quer denunciar esse vídeo? <a href="/login">Faça login</a> ou <a href="/signup">Crie uma conta</a> agora mesmo!';
$LANGS['close'] = 'fechar';
$LANGS['addresponse'] = 'Adicionar resposta';
$LANGS['recentlyrated'] = 'Recentemente avaliados';
$LANGS['commentsdisabled'] = 'Os comentários foram desabilitados para este vídeo.';
$LANGS['ratingsdisabled'] = 'Avaliações desabilitadas';
$LANGS['rating1'] = 'Ruim';
$LANGS['rating2'] = 'Nada de especial';
$LANGS['rating3'] = 'Vale a pena assistir';
$LANGS['rating4'] = 'Muito legal';
$LANGS['rating5'] = 'Incrível!';
$LANGS['saving'] = 'Salvando...';
$LANGS['signintorate'] = '<a href="/login">Entre</a> para avaliar';
$LANGS['addingcomment'] = "Adicionando comentário...";
$LANGS['commentposted'] = "Comentário enviado!";
$LANGS['commentspammsg'] = "Postar o mesmo comentário de novo é considerado como spam. Tente novamente mais tarde.";
$LANGS['commentspammsg2'] = "Postar mais de 5 comentários consecutivamente é considerado como spam. Tente novamente mais tarde.";
$LANGS['emptycomment'] = "Seu comentário não pode estar vazio.";
$LANGS['spambutton'] = "Spam";
$LANGS['notspambutton'] = "Não Spam";
$LANGS['commentsspam'] = "Comentário(s) marcados como spam";
$LANGS['marked'] = "Marcado como spam";
$LANGS['spamshow'] = "Mostrar";
$LANGS['spamhide'] = "Esconder";
$LANGS['poorcomment'] = "Comentário ruim";
$LANGS['goodcomment'] = "Comentário bom";
$LANGS['pleasesignin'] = "Por favor entre";
$LANGS['showmorecomments'] = "Mostrar mais comentários";
$LANGS['showingamount'] = "<strong>Mostrando {number}</strong> de {total} comentários";
$LANGS['customize'] = "Customizar";
$LANGS['customizedesc'] = "Após fazer suas mudanças, copie e cole o código acima em seu site. O código muda baseado em sua seleção.";
$LANGS['editvideodetail'] = "Editar detalhe de vídeo";
$LANGS['editannotations'] = "Editar anotações";
$LANGS['insightstats'] = "Estatísticas de insight";
$LANGS['allowratingscheck'] = "Permitir que este vídeo seja <b>avaliado</b> por outros.";
$LANGS['thisvideoispublic'] = "Este vídeo é público.";
$LANGS['thisvideoisprivate'] = "Este vídeo é privado.";
$LANGS['thisvideois'] = "Este vídeo é";
$LANGS['like'] = "Gostei";
$LANGS['saveto'] = "Salvar para";
$LANGS['uservideoamount'] = "{n} vídeos";
$LANGS['respondvideo'] = "Responder à este vídeo...";
$LANGS['signinnowcomment'] = '<a href="/login">Crie uma conta</a> ou <a href="/signup">Entre</a> agora para postar um commentário.';
$LANGS['charactersremaining'] = 'caracteres restantes';
$LANGS['attachavideo'] = 'Anexar um vídeo';
$LANGS['commentok'] = 'OK';
$LANGS['commenterror'] = 'Erro';
$LANGS['highestratedcomments'] = 'Comentários mais bem avaliados';
$LANGS['options'] = 'Opções';
$LANGS['openplaylist'] = 'Abir lista de reprodução';
$LANGS['autoplayon'] = 'Auto-reprodução (on)';
$LANGS['autoplayoff'] = 'Auto-reprodução (off)';
$LANGS['playlistposition'] = '<b>{n1}</b> de {n2}';
$LANGS['nextin'] = 'Próximo em {n}';
$LANGS['subscribetooltip'] = "Clique para ser notificado(a) de novos vídeos deste canal";
$LANGS['unsubscribetooltip'] = "Clique para parar de ser notificado(a) de novos vídeos deste canal";
$LANGS['liketooltip'] = "Eu gosto disso";
$LANGS['disliketooltip'] = "Eu não gosto disso";
$LANGS['likeratiotooltip'] = "{l} Gostei, {d} Não gostei";
$LANGS['savetotooltip'] = "Salvar para favoritos ou lista de reprodução";
$LANGS['sharetooltip'] = "Compartilhar este vídeo";
$LANGS['embedtooltip'] = "Obter código de incorporação do vídeo";
$LANGS['flagtooltip'] = "Marcar como inapropriado";
$LANGS['voteuptooltip'] = "Vote Up";
$LANGS['votedowntooltip'] = "Vote Down";
$LANGS['flagspamtooltip'] = "Marcar como spam";
$LANGS['removetooltip'] = "Remover";
$LANGS['likemessage'] = "Você gostou desse vídeo. Obrigado pelo feedback!<br>Veja mais <a href='/my_liked_videos'>vídeos que você gostou</a>.";
$LANGS['dislikemessage'] = "Você gostou desse vídeo. Obrigado pelo feedback!";
$LANGS['ratingsforthisvideo'] = "Avaliações para este vídeo";
$LANGS['liketotal'] = "{l} total";

/* Watch comments */
$LANGS['allcomments'] = 'Todos os comentários';

/* Player */
$LANGS['fullscreen'] = "Full screen";
$LANGS['expand'] = "Expand";
$LANGS['shrink'] = "Shrink";
$LANGS['popout'] = "Pop out";
$LANGS['mute'] = "Mute";
$LANGS['unmute'] = "Unmute";

/* Sign In */
$LANGS['username'] = "Nome de usuário";
$LANGS['password'] = "Senha";
$LANGS['logindesc'] = "Faça login no BitView com sua conta";
$LANGS['forgot'] = "Não consegue acessar a sua conta?";
$LANGS['forgotmsg'] = 'Por favor entre em contato conosco no Twitter (@BitView_) ou envie uma mensagem para os Moderadores no Discord. (link no rodapé)';
$LANGS['noaccount'] = "Não tem uma conta?";
$LANGS['signuptobv'] = "Inscreva-se no BitView!";
$LANGS['signintobv'] = "Faça login no BitView!";
$LANGS['signindesc1'] = "Ingresse na maior comunidade de vídeo do mundo!";
$LANGS['signindesc2'] = "Obtenha acesso total ao YouTube com a sua conta:";
$LANGS['signindesc3'] = "• Mostrar os seus vídeos favoritos para o mundo";
$LANGS['signindesc4'] = "• Blogar os vídeos que você tira com sua câmera digital ou celular";
$LANGS['signindesc5'] = "• Mostrar seus vídeos seguramente e privadamente para seus amigos e família";
$LANGS['notallowed'] = "Você já foi banido(a) três vezes. Você não pode mais usar o BitView!";
$LANGS['wrongpassword'] = 'Senha incorreta! Por favor tente novamente.';
$LANGS['staysigned'] = "Continuar conectado";

/* Sign Up */
$LANGS['email'] = "Endereço de Email";
$LANGS['passwordstrength'] = "Força da senha";
$LANGS['psnone'] = "Nenhuma";
$LANGS['psweak'] = "Fraca";
$LANGS['psfair'] = "Justa";
$LANGS['psgood'] = "Boa";
$LANGS['psstrong'] = "Forte";
$LANGS['repassword'] = "Reescrever senha";
$LANGS['usernamedesc'] = "Seu nome de usuário pode conter apenas letras de A a Z ou números de 0 9";
$LANGS['captcha'] = "Captcha";
$LANGS['acceptterms'] = 'Eu concordo com os <a href="/terms">Termos de Uso</a> e <a href="/privacy">Política de Privacidade</a>.';
$LANGS['copyrighttext'] = 'Enviar vídeos ou materiais que não sejam seus é uma violação dos direitos autorais e é contra a lei. Se você enviar materiais que não sejam seus, sua conta será excluída.';
$LANGS['mustaccept'] = 'Você deve concordar com os Termos de Uso e Política de Privacidade para criar a sua conta';
$LANGS['createaccount'] = 'Criar minha conta';
$LANGS['signuperror'] = 'Ocorreu um erro ao criar a sua conta.';
$LANGS['sameemail'] = 'Esse email ou nome de usuário já está em uso!';
$LANGS['usernamechar'] = 'Nomes de usuário podem apens conter letras e números!';
$LANGS['required'] = 'Todos os campos de texto são obrigatórios!';
$LANGS['notmatch'] = "As senhas não são exatas!";
$LANGS['signuphead'] = 'Comece a usar sua conta';

/* Videos Page */
$LANGS['recentvideos'] = 'Vídeos recentes';
$LANGS['random'] = 'Aleatório';
$LANGS['dropdownmore'] = 'mais';
$LANGS['allcatin'] = 'em';
$LANGS['allcat'] = 'Todas as categorias';
$LANGS['categories'] = 'Categorias';
$LANGS['nomorevideos'] = 'Não foram encontrados mais vídeos...';
$LANGS['timetoday'] = 'Hoje';
$LANGS['timeweek'] = 'Essa semana';
$LANGS['timemonth'] = 'Esse mês';
$LANGS['alltime'] = 'Todos os tempos';
$LANGS['when'] = 'Quando';
$LANGS['videofavorites'] = 'favoritos';
$LANGS['videocomments'] = 'comentários';
$LANGS['trendingtopics'] = 'Assuntos do momento';

/* Channels Page */
$LANGS['mostsubscribed'] = 'Mais inscrições';
$LANGS['lastlogin'] = 'Último acesso';
$LANGS['cstatviews'] = 'Exibições';
$LANGS['cstatvideos'] = 'Vídeos';
$LANGS['cstatsubs'] = 'Inscritos';
$LANGS['nochannels'] = 'Não foram encontrados mais canais...';

/* Video Categories */
$LANGS['cat1'] = "Filme e desenhos";
$LANGS['cat2'] = "Automóveis";
$LANGS['cat3'] = "Educação";
$LANGS['cat4'] = "Entretenimento";
$LANGS['cat5'] = "Eventos e casamentos";
$LANGS['cat6'] = "Família";
$LANGS['cat7'] = "Vendas e leilões";
$LANGS['cat8'] = "Hobbies e interesses";
$LANGS['cat9'] = "Humor";
$LANGS['cat10'] = "Música";
$LANGS['cat11'] = "Notícias e política";
$LANGS['cat12'] = "Estranho e ultrajante";
$LANGS['cat13'] = "Pessoas e blogs";
$LANGS['cat14'] = "Personals & Dating";
$LANGS['cat15'] = "Animais";
$LANGS['cat16'] = "Ciência e tecnologia";
$LANGS['cat17'] = "Filmes curtos";
$LANGS['cat18'] = "Esportes";
$LANGS['cat19'] = "Viagem e eventos";
$LANGS['cat20'] = "Jogos";
$LANGS['cat21'] = "Vídeo-blogging";

/* Channel Types */
$LANGS['type0'] = "Nenhum";
$LANGS['type1'] = "Membro";
$LANGS['type1p'] = "Membros";
$LANGS['type2'] = "Comediante";
$LANGS['type2p'] = "Comediantes";
$LANGS['type3'] = "Diretor(a)";
$LANGS['type3p'] = "Diretores(as)";
$LANGS['type4'] = "Guru";
$LANGS['type4p'] = "Gurus";
$LANGS['type5'] = "Músico(a)";
$LANGS['type5p'] = "Músicos(as)";
$LANGS['type6'] = "Repórter";
$LANGS['type6p'] = "Repórteres";

/* Countries */
$LANGS['cat_AF'] = "Afeganistão";
$LANGS['cat_AX'] = "Ilhas Åland";
$LANGS['cat_AL'] = "Albânia";
$LANGS['cat_DZ'] = "Argélia";
$LANGS['cat_AS'] = "Samoa Americana";
$LANGS['cat_AD'] = "Andorra";
$LANGS['cat_AO'] = "Angola";
$LANGS['cat_AI'] = "Anguila";
$LANGS['cat_AQ'] = "Antártida";
$LANGS['cat_AG'] = "Antígua e Barbuda";
$LANGS['cat_AR'] = "Argentina";
$LANGS['cat_AM'] = "Arménia";
$LANGS['cat_AW'] = "Aruba";
$LANGS['cat_AU'] = "Austrália";
$LANGS['cat_AT'] = "Áustria";
$LANGS['cat_AZ'] = "Azerbaijão";
$LANGS['cat_BS'] = "Bahamas";
$LANGS['cat_BH'] = "Bahrein";
$LANGS['cat_BD'] = "Bangladesh";
$LANGS['cat_BB'] = "Barbados";
$LANGS['cat_BY'] = "Bielorrússia";
$LANGS['cat_BE'] = "Bélgica";
$LANGS['cat_BZ'] = "Belize";
$LANGS['cat_BJ'] = "Benim";
$LANGS['cat_BM'] = "Bermudas";
$LANGS['cat_BT'] = "Butão";
$LANGS['cat_BO'] = "Bolívia";
$LANGS['cat_BQ'] = "Países Baixos Caribenhos";
$LANGS['cat_BA'] = "Bósnia e Herzegovina";
$LANGS['cat_BW'] = "Botswana";
$LANGS['cat_BV'] = "Ilha Bouvet";
$LANGS['cat_BR'] = "Brasil";
$LANGS['cat_IO'] = "British Indian Ocean Territory";
$LANGS['cat_BN'] = "Brunei Darussalam";
$LANGS['cat_BG'] = "Bulgaria";
$LANGS['cat_BF'] = "Burkina Faso";
$LANGS['cat_BI'] = "Burundi";
$LANGS['cat_KH'] = "Cambodia";
$LANGS['cat_CM'] = "Cameroon";
$LANGS['cat_CA'] = "Canadá";
$LANGS['cat_CV'] = "Cape Verde";
$LANGS['cat_KY'] = "Cayman Islands";
$LANGS['cat_CF'] = "Central African Republic";
$LANGS['cat_TD'] = "Chad";
$LANGS['cat_CL'] = "Chile";
$LANGS['cat_CN'] = "China";
$LANGS['cat_CX'] = "Christmas Island";
$LANGS['cat_CC'] = "Cocos (Keeling) Islands";
$LANGS['cat_CO'] = "Colômbia";
$LANGS['cat_KM'] = "Comoros";
$LANGS['cat_CG'] = "Republic of the Congo";
$LANGS['cat_CD'] = "Democratic Republic of the Congo";
$LANGS['cat_CK'] = "Cook Islands";
$LANGS['cat_CR'] = "Costa Rica";
$LANGS['cat_CI'] = "Côte d'Ivoire";
$LANGS['cat_HR'] = "Croatia";
$LANGS['cat_CU'] = "Cuba";
$LANGS['cat_CW'] = "Curaçao";
$LANGS['cat_CY'] = "Cyprus";
$LANGS['cat_CZ'] = "Czech Republic";
$LANGS['cat_DK'] = "Denmark";
$LANGS['cat_DJ'] = "Djibouti";
$LANGS['cat_DM'] = "Dominica";
$LANGS['cat_DO'] = "Dominican Republic";
$LANGS['cat_EC'] = "Ecuador";
$LANGS['cat_EG'] = "Egypt";
$LANGS['cat_SV'] = "El Salvador";
$LANGS['cat_GQ'] = "Equatorial Guinea";
$LANGS['cat_ER'] = "Eritrea";
$LANGS['cat_EE'] = "Estonia";
$LANGS['cat_ET'] = "Ethiopia";
$LANGS['cat_FK'] = "Falkland Islands (Malvinas)";
$LANGS['cat_FO'] = "Faroe Islands";
$LANGS['cat_FJ'] = "Fiji";
$LANGS['cat_FI'] = "Finland";
$LANGS['cat_FR'] = "France";
$LANGS['cat_GF'] = "French Guiana";
$LANGS['cat_FG'] = "French Guiana";
$LANGS['cat_PF'] = "French Polynesia";
$LANGS['cat_TF'] = "French Southern Territories";
$LANGS['cat_GA'] = "Gabon";
$LANGS['cat_GM'] = "Gambia";
$LANGS['cat_GE'] = "Georgia";
$LANGS['cat_DE'] = "Alemanha";
$LANGS['cat_GH'] = "Ghana";
$LANGS['cat_GI'] = "Gibraltar";
$LANGS['cat_GR'] = "Greece";
$LANGS['cat_GL'] = "Greenland";
$LANGS['cat_GD'] = "Grenada";
$LANGS['cat_GP'] = "Guadalupe";
$LANGS['cat_GU'] = "Guam";
$LANGS['cat_GT'] = "Guatemala";
$LANGS['cat_GG'] = "Guernsey";
$LANGS['cat_GN'] = "Guinea";
$LANGS['cat_GW'] = "Guinea-Bissau";
$LANGS['cat_GY'] = "Guyana";
$LANGS['cat_HT'] = "Haiti";
$LANGS['cat_HM'] = "Heard Island and McDonald Islands";
$LANGS['cat_VA'] = "Holy See (Vatican City State)";
$LANGS['cat_HN'] = "Honduras";
$LANGS['cat_HK'] = "Hong Kong";
$LANGS['cat_HU'] = "Hungary";
$LANGS['cat_IS'] = "Iceland";
$LANGS['cat_IN'] = "India";
$LANGS['cat_ID'] = "Indonésia";
$LANGS['cat_IR'] = "Iran";
$LANGS['cat_IQ'] = "Iraq";
$LANGS['cat_IE'] = "Ireland";
$LANGS['cat_IM'] = "Isle of Man";
$LANGS['cat_IL'] = "Israel";
$LANGS['cat_IT'] = "Italy";
$LANGS['cat_JM'] = "Jamaica";
$LANGS['cat_JP'] = "Japan";
$LANGS['cat_JE'] = "Jersey";
$LANGS['cat_JO'] = "Jordan";
$LANGS['cat_KZ'] = "Kazakhstan";
$LANGS['cat_KE'] = "Kenya";
$LANGS['cat_KI'] = "Kiribati";
$LANGS['cat_XK'] = "Kosovo";
$LANGS['cat_KP'] = "North Korea";
$LANGS['cat_KR'] = "South Korea";
$LANGS['cat_KW'] = "Kuwait";
$LANGS['cat_KG'] = "Kyrgyzstan";
$LANGS['cat_LA'] = "Laos";
$LANGS['cat_LV'] = "Latvia";
$LANGS['cat_LB'] = "Lebanon";
$LANGS['cat_LS'] = "Lesotho";
$LANGS['cat_LR'] = "Liberia";
$LANGS['cat_LY'] = "Libya";
$LANGS['cat_LI'] = "Liechtenstein";
$LANGS['cat_LT'] = "Lithuania";
$LANGS['cat_LU'] = "Luxembourg";
$LANGS['cat_MO'] = "Macao";
$LANGS['cat_MK'] = "North Macedonia";
$LANGS['cat_MG'] = "Madagascar";
$LANGS['cat_MW'] = "Malawi";
$LANGS['cat_MY'] = "Malaysia";
$LANGS['cat_MV'] = "Maldives";
$LANGS['cat_ML'] = "Mali";
$LANGS['cat_MT'] = "Malta";
$LANGS['cat_MH'] = "Marshall Islands";
$LANGS['cat_MQ'] = "Martinique";
$LANGS['cat_MR'] = "Mauritania";
$LANGS['cat_MU'] = "Mauritius";
$LANGS['cat_YT'] = "Mayotte";
$LANGS['cat_MX'] = "Mexico";
$LANGS['cat_FM'] = "Micronesia";
$LANGS['cat_MD'] = "Moldova";
$LANGS['cat_MC'] = "Monaco";
$LANGS['cat_MN'] = "Mongolia";
$LANGS['cat_ME'] = "Montenegro";
$LANGS['cat_MS'] = "Montserrat";
$LANGS['cat_MA'] = "Morocco";
$LANGS['cat_MZ'] = "Mozambique";
$LANGS['cat_MM'] = "Myanmar";
$LANGS['cat_NA'] = "Namibia";
$LANGS['cat_NR'] = "Nauru";
$LANGS['cat_NP'] = "Nepal";
$LANGS['cat_NL'] = "Netherlands";
$LANGS['cat_AN'] = "Netherlands Antilles";
$LANGS['cat_NC'] = "New Caledonia";
$LANGS['cat_NZ'] = "Nova Zelândia";
$LANGS['cat_NI'] = "Nicaragua";
$LANGS['cat_NE'] = "Niger";
$LANGS['cat_NG'] = "Nigeria";
$LANGS['cat_NU'] = "Niue";
$LANGS['cat_NF'] = "Norfolk Island";
$LANGS['cat_MP'] = "Northern Mariana Islands";
$LANGS['cat_NO'] = "Norway";
$LANGS['cat_OM'] = "Oman";
$LANGS['cat_PK'] = "Pakistan";
$LANGS['cat_PW'] = "Palau";
$LANGS['cat_PS'] = "Palestina";
$LANGS['cat_PA'] = "Panama";
$LANGS['cat_PG'] = "Papua New Guinea";
$LANGS['cat_PY'] = "Paraguay";
$LANGS['cat_PE'] = "Peru";
$LANGS['cat_PH'] = "Philippines";
$LANGS['cat_PN'] = "Pitcairn";
$LANGS['cat_PL'] = "Poland";
$LANGS['cat_PT'] = "Portugal";
$LANGS['cat_PR'] = "Puerto Rico";
$LANGS['cat_QA'] = "Qatar";
$LANGS['cat_RE'] = "Réunion";
$LANGS['cat_RO'] = "Romania";
$LANGS['cat_RU'] = "Russia";
$LANGS['cat_RW'] = "Rwanda";
$LANGS['cat_BL'] = "Saint Barthélemy";
$LANGS['cat_SH'] = "Saint Helena";
$LANGS['cat_KN'] = "Saint Kitts and Nevis";
$LANGS['cat_LC'] = "Saint Lucia";
$LANGS['cat_MF'] = "Saint Martin (French part)";
$LANGS['cat_PM'] = "Saint Pierre and Miquelon";
$LANGS['cat_VC'] = "Saint Vincent and the Grenadines";
$LANGS['cat_WS'] = "Samoa";
$LANGS['cat_SM'] = "San Marino";
$LANGS['cat_ST'] = "Sao Tome and Principe";
$LANGS['cat_SA'] = "Saudi Arabia";
$LANGS['cat_SN'] = "Senegal";
$LANGS['cat_RS'] = "Serbia";
$LANGS['cat_SC'] = "Seychelles";
$LANGS['cat_SL'] = "Sierra Leone";
$LANGS['cat_SG'] = "Singapore";
$LANGS['cat_SX'] = "Sint Maarten";
$LANGS['cat_SK'] = "Slovakia";
$LANGS['cat_SI'] = "Slovenia";
$LANGS['cat_SB'] = "Solomon Islands";
$LANGS['cat_SO'] = "Somalia";
$LANGS['cat_ZA'] = "África do Sul";
$LANGS['cat_GS'] = "South Georgia and the South Sandwich Islands";
$LANGS['cat_ES'] = "Espanha";
$LANGS['cat_LK'] = "Sri Lanka";
$LANGS['cat_SD'] = "Sudan";
$LANGS['cat_SR'] = "Suriname";
$LANGS['cat_SJ'] = "Svalbard and Jan Mayen";
$LANGS['cat_SZ'] = "Swaziland";
$LANGS['cat_SE'] = "Suécia";
$LANGS['cat_CH'] = "Switzerland";
$LANGS['cat_SS'] = "South Sudan";
$LANGS['cat_SY'] = "Syria";
$LANGS['cat_TW'] = "Taiwan";
$LANGS['cat_TJ'] = "Tajikistan";
$LANGS['cat_TZ'] = "Tanzania";
$LANGS['cat_TH'] = "Thailand";
$LANGS['cat_TL'] = "Timor-Leste";
$LANGS['cat_TG'] = "Togo";
$LANGS['cat_TK'] = "Tokelau";
$LANGS['cat_TO'] = "Tonga";
$LANGS['cat_TT'] = "Trinidad and Tobago";
$LANGS['cat_TN'] = "Tunisia";
$LANGS['cat_TR'] = "Turkey";
$LANGS['cat_TM'] = "Turkmenistan";
$LANGS['cat_TC'] = "Turks and Caicos Islands";
$LANGS['cat_TV'] = "Tuvalu";
$LANGS['cat_UG'] = "Uganda";
$LANGS['cat_UA'] = "Ucrânia";
$LANGS['cat_AE'] = "Emirados Árabes Unidos";
$LANGS['cat_GB'] = "Reino Unido";
$LANGS['cat_US'] = "Estados Unidos";
$LANGS['cat_UM'] = "United States Minor Outlying Islands";
$LANGS['cat_UY'] = "Uruguay";
$LANGS['cat_UZ'] = "Uzbekistan";
$LANGS['cat_VU'] = "Vanatu";
$LANGS['cat_VE'] = "Venezuela";
$LANGS['cat_VN'] = "Vietnam";
$LANGS['cat_VG'] = "Virgin Islands, British";
$LANGS['cat_VI'] = "Virgin Islands, U.S.";
$LANGS['cat_WF'] = "Wallis and Futuna";
$LANGS['cat_EH'] = "Western Sahara";
$LANGS['cat_YE'] = "Yemen";
$LANGS['cat_ZM'] = "Zambia";
$LANGS['cat_ZW'] = "Zimbabwe";

/* My Subscriptions */
$LANGS['newvideos'] = "Novos Vídeos";
$LANGS['addselectedto'] = "Adicionar os vídeos selecionados para:";
$LANGS['addtoplaylists'] = "Adicionar para listas de reprodução";

/* Account */
$LANGS['myaccount'] = "Minha Conta";
$LANGS['vidsfavs'] = "Vídeos, Favoritos and Listas de reprodução";
$LANGS['accountsettings'] = "Configurações de Conta";
$LANGS['viewinghistory'] = "Histórico";
$LANGS['mychannel'] = "Meu Canal";
$LANGS['uploadedvideos'] = "Vídeos Publicados";
$LANGS['new'] = "Novo";
$LANGS['playlist'] = "Listas de reprodução";
$LANGS['videoupload'] = "Video Upload";
$LANGS['nosubvideos'] = "Você não possui inscrições...";
$LANGS['nofavvideos'] = "Você não favoritou nenhum vídeo...";

/* My Videos */
$LANGS['sortby'] = "Classificar por";
$LANGS['sorttitle'] = "Título";
$LANGS['sorttime'] = "Tempo";
$LANGS['sortdateadded'] = "Data da inclusão";
$LANGS['sortviews'] = "Exibições";
$LANGS['sortrating'] = "Avaliação";
$LANGS['stattime'] = "Tempo";
$LANGS['statrating'] = "Avaliação";
$LANGS['statbroadcast'] = "Transmitir";
$LANGS['statrawfile'] = "Arquivo bruto";
$LANGS['public'] = "Público";
$LANGS['private'] = "Privado";
$LANGS['live'] = "Ao vivo!";
$LANGS['converting'] = "Convertendo...";
$LANGS['uploading'] = "Publicando...";
$LANGS['addvidsto'] = "Adicionar Vídeos para";
$LANGS['play'] = "Reproduzir";
$LANGS['edit'] = "Editar";
$LANGS['setasavatar'] = "Definir miniatura como avatar";
$LANGS['downloadmp4'] = "Baixar MP4";
$LANGS['deleteconfirmation'] = "Você tem certeza que quer deletar esse vídeo?";
$LANGS['novideos'] = 'Você não enviou nenhum vídeo. <a href="/my_videos_upload">Comece a enviar um vídeo agora</a>!';
$LANGS['nomyvideosresults'] = "Nenhum resultado. Certifique se a sua ortografia está correta.";

/* Edit Video */
$LANGS['infoandsettings'] = "Informações e Configurações";
$LANGS['annotations'] = "Anotações";
$LANGS['captionsandsubtitles'] = "Legendas";
$LANGS['viewonvideopage'] = "Assistir na página de vídeo »";
$LANGS['title'] = "Título";
$LANGS['title'] = "Título";
$LANGS['desc'] = "Descrição";
$LANGS['privacy'] = "Privacidade";
$LANGS['saveinfo'] = "Salvar Informação";
$LANGS['saveinfoconfirm'] = "Você tem certeza que quer trocar as informações do vídeo?";
$LANGS['viewchart'] = "Visualizar gráfico";
$LANGS['videodetails'] = "Detalhes do vídeo";
$LANGS['backtopreviouspage'] = "Voltar para página anterior";
$LANGS['editsavechanges'] = "Salvar alterações";
$LANGS['editcancel'] = "cancelar";
$LANGS['videoinfo'] = "Informação do Vídeo";
$LANGS['videothumbnail'] = "Miniatura do vídeo";
$LANGS['uploadthumbnail'] = "Enviar miniatura";
$LANGS['customthumbdesc'] = 'To set a custom thumbnail, click the thumbnail on the left side and select your desired image file. Then, click "Upload Thumbnail".';
$LANGS['customthumbtitle'] = 'Você quer trocar esta miniatura?';
$LANGS['customthumbinfo'] = 'Custom thumbnails are exclusive to partners. To read more about the advantages of joining the partner program and its requirements, click the button below.';
$LANGS['partnerreadmore'] = 'Ler mais';
$LANGS['broadcastingoptions'] = 'Opções de transmissão e compartilhamento';
$LANGS['publicdesc'] = "todos podem procurar e visualizar - recomendado";
$LANGS['privatedesc'] = "apenas usuários específicos do BitView podem visualizar";
$LANGS['allowcomments'] = "Permitir comentários automaticamente";
$LANGS['allowfriendcomments'] = "Apenas amigos podem comentar";
$LANGS['disablecomments'] = "Não permitir comentários";
$LANGS['dateandmap'] = "Data e mapa";
$LANGS['clear'] = "Limpar";
$LANGS['allowratings'] = "Sim, permitir que este vídeo seja avaliado por outros.";
$LANGS['dontallowratings'] = "Não, não permitir que este vídeo seja avaliado.";
$LANGS['updatevideo'] = "Atualizar vídeo";
$LANGS['updatevideofilesize'] = "(tamanho máximo de arquivo: 100MB)";

/* Edit Video Annotations */
$LANGS['publish'] = "Publicar";
$LANGS['published'] = "Publicado";
$LANGS['saved'] = "Salvo";
$LANGS['notvaliddate'] = "You have entered an unvalid timestamp!";
$LANGS['outsiderange'] = "You have entered a timestamp outside of the video duration range!";
$LANGS['video_pl'] = "Paste a link to a Video";
$LANGS['playlist_pl'] = "Paste a link to a Playlist";
$LANGS['channel_pl'] = "Enter an username";
$LANGS['group_pl'] = "Paste a link to a Group";
$LANGS['search_pl'] = "Enter your search query";
$LANGS['entertext'] = "Enter your text here";
$LANGS['loading'] = "Carregando...";
$LANGS['addlink'] = "Adicionar link";
$LANGS['linktype'] = "Link Type";
$LANGS['group'] = "Group";
$LANGS['composemessage'] = "Compor mensagem";
$LANGS['videoresponseupload'] = "Envio de vídeo-resposta";
$LANGS['searchquery'] = "BitView Search Query";
$LANGS['entervalidurl'] = "Please enter a valid URL";

/* My Playlists */
$LANGS['addedpl'] = "Adicionado";
$LANGS['frompl'] = "De";
$LANGS['nopl'] = "Nenhuma lista de reprodução foi encontrada....";

/* My Playlist */
$LANGS['playlistedit'] = "Editar lista de reprodução";
$LANGS['videourl'] = "URL do Vídeo";
$LANGS['add'] = "Adicionar";
$LANGS['editinfo'] = "Editar informações";
$LANGS['editdetails'] = "Editar detalhes";
$LANGS['deleteplaylist'] = "Deletar lista de reprodução";
$LANGS['addvideostoplaylist'] = "Adicionar vídeos à lista de reprodução";
$LANGS['novideoswerefound'] = "Nenhum vídeo foi encontrado.";
$LANGS['position'] = "Posição";
$LANGS['move'] = "Mover";
$LANGS['deleteplaylistconfirmdesc'] = "Você tem certeza que deseja deletar <strong>{p}</strong>?<br><br>Nota: Deletar uma lista de reprodução é uma ação permanente e não pode ser desfeita.";
$LANGS['deleteplaylistconfirm'] = "Sim, apagá-la";
$LANGS['titledesctags'] = "Título, descrição, palavras-chave";
$LANGS['savechangespl'] = "Salvar alterações";

/* Edit Playlist */
$LANGS['pledittitle'] = "Editar lista de reprodução";
$LANGS['pleditdesc'] = "Listas de reprodução são uma coleção de vídeos que você pode organizar do jeito que quiser.";
$LANGS['cancel'] = "Cancelar";

/* Create Playlist */
$LANGS['createplaylisttitle'] = "Criar lista de reprodução de vídeo";
$LANGS['createplaylist'] = "Criar lista de reprodução";

/* View Playlist */
$LANGS['plpermalink'] = "Lista de reprodução/URL (Permalink):";
$LANGS['sortcomments'] = "Comentários";
$LANGS['unsorted'] = "Não categorizado";
$LANGS['playallvideos'] = "Tocar todos os vídeos";

/* Inbox */
$LANGS['compose'] = "Compor";
$LANGS['from'] = "De";
$LANGS['subject'] = "Sujeito";
$LANGS['date'] = "Data";
$LANGS['allmsg'] = "Todas as mensagens";
$LANGS['msgcom'] = "Commentários";
$LANGS['sentmsg'] = "Mensagens enviadas";
$LANGS['nomsg'] = "Você não tem mensagens...";
$LANGS['personalmessages'] = "Mensagens pessoais";
$LANGS['sharedwithyouinbox'] = "Compartilhadas com Você";
$LANGS['friendinvitesinbox'] = "Convites de amigo";
$LANGS['videoresponsesinbox'] = "Vídeo-respostas";
$LANGS['sent'] = "Enviadas";
$LANGS['attachvideo'] = "Anexar vídeo";
$LANGS['msgchannelcomment'] = "Comentário no seu canal";
$LANGS['msgcomment'] = "Comentário no seu vídeo";
$LANGS['msgvideoresponse'] = "Vídeo-resposta no seu vídeo";
$LANGS['msgmention'] = "Mention on a video";
$LANGS['msgmentionchannel'] = "Menção no canal de {channel}";

/* Address Book */
$LANGS['addressbook'] = "Address Book";
$LANGS['allcontacts'] = "All Contacts";
$LANGS['selectedcontacts'] = "Selected Contacts";
$LANGS['choosecontacts'] = "Choose from your list of contacts";
$LANGS['friendssince'] = "Friends since";
$LANGS['friendsinvitenot'] = "Friend invite not accepted yet";
$LANGS['friendstatus'] = "Friend Status";
$LANGS['unselect'] = "Unselect";
$LANGS['unselectall'] = "Unselect All";
$LANGS['nocontacts'] = "No contacts...";
$LANGS['selectacontact'] = "Please select at least a contact to delete!";
$LANGS['selectacontactmsg'] = "Please select at least a contact to message!";
$LANGS['selectonecompose'] = "You can not compose to multiple contacts at once!<br>Please, select the contact you wish to send a message.";

/* Insight */
$LANGS['insighttitle'] = "Insight: Statistics and Data";
$LANGS['allvideos'] = "All Videos";
$LANGS['summary'] = "Summary";
$LANGS['demographics'] = "Demographics";
$LANGS['viewsdesc'] = "How many views are my videos getting?";
$LANGS['demodesc'] = "Who is subscribed to my channel?";
$LANGS['commdesc'] = "Where are my subscribers located?";
$LANGS['video'] = "Video";
$LANGS['topvideos'] = "Top videos";
$LANGS['viewspercentage'] = "Views (&percnt; of total)";
$LANGS['percentoftotalviews'] = "&percnt; of total views";
$LANGS['searchmyvideos'] = "Search My Videos";
$LANGS['insufdemo'] = "There is insufficient data to display Demographics. Try selecting a different time range.";
$LANGS['ageranges'] = "Age ranges for both genders";
$LANGS['genderranges'] = "Genders for all age groups";
$LANGS['engdesc'] = "Number of users that have commented, favorited or rated your videos";
$LANGS['engagements'] = "Community engagements";
$LANGS['dailysubs'] = "Daily subscribers";
$LANGS['daily'] = "Daily";
$LANGS['total'] = "Total";
$LANGS['insightvideodesc'] = "How many times has this video been watched?";
$LANGS['videototalviews'] = "Total views";
$LANGS['dailyviews'] = "Daily views";

/* Send Message */
$LANGS['messagecont'] = "Mensagem";
$LANGS['to'] = "Para";
$LANGS['sendmessagebutton'] = "Enviar Mensagem";

/* Groups */
$LANGS['groups'] = "Grupos";
$LANGS['joinedgroups'] = "Joined Groups";
$LANGS['recentgroups'] = "Grupos Recentes";
$LANGS['mostmembers'] = "Mais Membros";
$LANGS['mostvideos'] = "Mais Vídeos";
$LANGS['groupmostdiscussed'] = "Mais Discutidos";
$LANGS['createagroup'] = "Criar um Grupo";
$LANGS['groupvideos'] = "Vídeos";
$LANGS['groupmembers'] = "Membros";
$LANGS['discussions'] = "Discussões";
$LANGS['groupcreated'] = "Criado";
$LANGS['nogroups'] = "Nenhum Grupo encontrado...";

/* Group */
$LANGS['jointhisgroup'] = "Entrar nesse grupo";
$LANGS['removerequest'] = "Remove Request";
$LANGS['leavegroup'] = "Sair do Grupo";
$LANGS['moderation'] = "Moderação";
$LANGS['viewallvideos'] = "Assitir Todos Os Vídeos";
$LANGS['addvideo'] = "Adicionar Vídeo";
$LANGS['novideos'] = "Nenhum Vídeo...";
$LANGS['nodiscussions'] = "Nenhuma Discussão...";
$LANGS['creatediscussion'] = "Criar Discussão";
$LANGS['topostatopic'] = "para postar um tópico.";
$LANGS['topic'] = "Tópico";
$LANGS['author'] = "Autor(a)";
$LANGS['replies'] = "Respostas";
$LANGS['lastpost'] = "Última Postagem";
$LANGS['viewallmembers'] = "Ver Todos Os Membros";
$LANGS['owner'] = "Dono(a)";
$LANGS['grouptype'] = "Tipo";
$LANGS['instantjoin'] = "Entrada Instantânea";
$LANGS['approvalrequired'] = "Aprovação Requirida";
$LANGS['groupurl'] = "URL";
$LANGS['deletediscussion'] = "Deletar Discussão";
$LANGS['postreply'] = "Postar Resposta";
$LANGS['post'] = "Postar";
$LANGS['accept'] = "Aceitar";
$LANGS['decline'] = "Rejeitar";

/* Group Moderation */
$LANGS['groupmoderation'] = "Moderação Do Grupo";
$LANGS['approvemembers'] = "Aprovar Membros";
$LANGS['approvevideos'] = "Aprovar Vídeos";
$LANGS['yes'] = "Sim";
$LANGS['no'] = "Não";
$LANGS['changeinfo'] = "Trocar Informações";
$LANGS['changeimage'] = "Trocar Imagem";
$LANGS['image'] = "Imagem";
$LANGS['styling'] = "Styling";
$LANGS['cssdesc'] = "Having backgrounds or graphics that do or show illegal things will result in your termination.";
$LANGS['updatecss'] = "Atualizar CSS";
$LANGS['groupmessage'] = "Mensagem";
$LANGS['sendmessagetomembers'] = "Enviar Mensagem para Membros";
$LANGS['delgroup'] = "Deletar Grupo";

/* Submit Group Video */
$LANGS['submitvideotitle'] = "Submit Video to Group";
$LANGS['submitvideo'] = "Submit Video";

/* Create Group */
$LANGS['groupname'] = "Nome do Grupo";
$LANGS['groupimage'] = "Imagem do Grupo";
$LANGS['creategroup'] = "Criar Grupo";
$LANGS['creategroupdesc'] = "Groups allow you to create discussions with other members and easily share your videos with others.";

/* Create Group Discussion */
$LANGS['discussiontitle'] = "Título da Discussão";
$LANGS['creatediscussiondesc'] = "Discussions are parts of groups in which you discuss the set topic.";

/* Search Results */
$LANGS['results'] = "{s} results";
$LANGS['relevance'] = 'Relevância';
$LANGS['viewcount'] = 'Contagem de exibições';
$LANGS['searchrating'] = 'Avaliação';
$LANGS['newest'] = 'Mais Recente';
$LANGS['nochannelsfound'] = 'Nenhum Canal Encontrado...';
$LANGS['noplfound'] = 'Nenhuma Playlist Encontrada...';
$LANGS['nogroupsfound'] = 'Nenhum Grupo Encontrado...';
$LANGS['uploaded'] = 'Uploaded';
$LANGS['anytime'] = 'Anytime';
$LANGS['partnervideos'] = 'Partner Videos';
$LANGS['resultcount'] = 'results {r} of about {t}';
$LANGS['searchoptions'] = 'Opções de pesquisa';
$LANGS['resulttype'] = 'Tipo de resultado';
$LANGS['duration'] = 'Duração';
$LANGS['durshort'] = 'Curto (~4 minutos)';
$LANGS['durlong'] = 'Longo (15~ minutos)';
$LANGS['features'] = 'Features';
$LANGS['novideosfoundfor'] = 'No videos found for';
$LANGS['noresultsfoundfor'] = 'No results found for';

/* Profile */
$LANGS['channelsuspended'] = 'Esta conta é suspensa.';
$LANGS['accountnotfound'] = 'Esta conta não pôde ser encontrada.';
$LANGS['channel'] = 'Canal';
$LANGS['friends'] = 'Amigos';
$LANGS['channelsubscribers'] = 'Inscritos';
$LANGS['linkcomments'] = 'Comentários';
$LANGS['bulletins'] = 'Boletins';
$LANGS['editchannel'] = 'Editar canal';
$LANGS['type'] = 'Tipo';
$LANGS['joined'] = 'Participante desde';
$LANGS['videoswatched'] = 'Vídeos assistidos';
$LANGS['channelviews'] = 'Exibições do Canal';
$LANGS['age'] = 'Idade';
$LANGS['gender'] = 'Gênero';
$LANGS['male'] = 'Masculino';
$LANGS['female'] = 'Feminino';
$LANGS['nonbinary'] = 'Não-Binário';
$LANGS['status'] = 'Status';
$LANGS['single_m'] = 'Solteiro';
$LANGS['single_f'] = 'Solteira';
$LANGS['taken_m'] = 'Levado';
$LANGS['taken_f'] = 'Levada';
$LANGS['married_m'] = 'Casado';
$LANGS['married_f'] = 'Casada';
$LANGS['country'] = 'País';
$LANGS['website'] = 'Site';
$LANGS['hobbies'] = 'Interesses e hobbies';
$LANGS['music'] = 'Música';
$LANGS['movies'] = 'Filmes e séries';
$LANGS['books'] = 'Livros';
$LANGS['mostsub'] = 'Mais inscritos';
$LANGS['report'] = 'Sinalizar';
$LANGS['pfpviolation'] = 'violação de imagem de perfil';
$LANGS['connectwith'] = 'Conectar com';
$LANGS['profilesendmessage'] = 'Enviar mensagem';
$LANGS['messagetoyourself'] = 'Você não pode enviar mensagens para si mesmo(a)!';
$LANGS['logintomessage'] = 'Por favor entre para enviar mensagens!';
$LANGS['addcomment'] = 'Adicionar comentário';
$LANGS['logintocommentchannel'] = 'Por favor entre para comentar';
$LANGS['sharechannel'] = 'Compartilhar canal';
$LANGS['addfriend'] = 'Adicionar como amigo';
$LANGS['retractinvite'] = 'Retrair convite';
$LANGS['removefriend'] = 'Remover amigo';
$LANGS['notfriendyourself'] = 'Você não pode adicionar você mesmo(a) como amigo!';
$LANGS['logintofriend'] = 'Por favor entre para adicionar amigos!';
$LANGS['blockuser'] = 'Bloquear usuário';
$LANGS['channelembed'] = 'Incorporar este canal';
$LANGS['recentratings'] = 'Atividade recente';
$LANGS['seeall'] = 'ver todos';
$LANGS['writebulletin'] = 'Escrever boletim';
$LANGS['bulletin'] = 'Boletim';
$LANGS['subvideos1'] = 'Inscrever-se nos vídeos de ';
$LANGS['subvideos2'] = "";
$LANGS['plvideos'] = 'Vídeos';
$LANGS['playall'] = 'Tocar todos';
$LANGS['featuredchannels'] = 'Canais em destaque';
$LANGS['channelcomments'] = 'Comentários do canal';
$LANGS['bggraphic'] = 'gráfico de plano de fundo';
$LANGS['reportthisuser'] = 'este usuário.';
$LANGS['norecentratings'] = 'Nenhuma atividade recente encontrada...';
$LANGS['nosubscribers'] = 'Nenhum inscrito...';
$LANGS['nosubscriptions'] = 'Nenhuma inscrição...';
$LANGS['nofriends'] = 'Nenhum amigo...';
$LANGS['nobulletins'] = 'Nenhum boletim...';
$LANGS['novideoschannel'] = 'Nenhum vídeo...';
$LANGS['nofavs'] = 'Nenhum vídeo favorito...';
$LANGS['noplchannel'] = 'Nenhuma lista de reprodução...';
$LANGS['pvideos'] = 'Vídeos privados';
$LANGS['pvideosallow'] = 'Você não tem permissão para assistir esses vídeos...';
$LANGS['plvideoamount'] = 'videos';
$LANGS['bulletinpost'] = 'Postagem do boletim';
$LANGS['deletebulletin'] = 'Apagar boletim';
$LANGS['body'] = 'Corpo';
$LANGS['bulletincomments'] = 'Comentários do boletim';
$LANGS['tocommentbulletin'] = 'para postar uma resposta à este boletim!';
$LANGS['addacomment'] = 'Adicionar um comentário:';
$LANGS['postreplychannel'] = 'Postar resposta';
$LANGS['writecomment'] = 'Escrever comentário';
$LANGS['for'] = 'para';
$LANGS['commentdesc'] = 'Comentários do canal aparecem no canal do usuário.';
$LANGS['postbulletin'] = 'Postar boletim';
$LANGS['writeabulletin'] = 'Escrever boletim';
$LANGS['bulletindesc'] = 'O boletim será postado na página inicial dos seus amigos e na página do seu canal.';
$LANGS['sharingoptions'] = 'Opções de compartilhamento';
$LANGS['sharingoptionsdesc'] = 'Existem duas maneiras de compartilhar este canal.';
$LANGS['sharingoptions1'] = '1. Copie e cole este link em um e-mail ou mensagem instantânea.';
$LANGS['sharingoptions2'] = "2. Envie este canal utilizando o programa de e-mail do seu computador.";
$LANGS['clicktosend'] = 'Clique para enviar!';
$LANGS['honorless'] = 'menos';
$LANGS['activitycomment'] = 'comentou em';
$LANGS['activityfavorite'] = 'adotou um vídeo como favorito';
$LANGS['activitylike'] = 'gostou de um vídeo';
$LANGS['activityrating'] = 'avaliou um vídeo:';
$LANGS['activityupload'] = 'enviou um novo vídeo';
$LANGS['activityfriend'] = 'virou amigo de';
$LANGS['activitysubscription'] = 'inscritos em';
$LANGS['next'] = "Próximo";
$LANGS['previous'] = "Anterior";
$LANGS['settings'] = "Configurações";
$LANGS['themescolors'] = "Temas e cores";
$LANGS['channelmodules'] = "Módulos";
$LANGS['videosandpl'] = "Vídeos e listas de reprodução";
$LANGS['revert'] = "Reverter! Eu quero meu canal antigo de volta";
$LANGS['all'] = "Todos";
$LANGS['uploads'] = "Envios";
$LANGS['channelpl'] = "Listas de reprodução";
$LANGS['backtoplaylists'] = "Voltar para listas reprodução";
$LANGS['searchuploads'] = "Pesquisar envios";
$LANGS['info'] = "Informações";
$LANGS['viewcomments'] = "Visualizar comentários, vídeos relacionados, e muito mais";
$LANGS['seeallcommentsandresponses'] = "Ver todos os comentários e vídeos-resposta";
$LANGS['pastethislink'] = "Cole este link em um e-mail ou mensagem instantânea";
$LANGS['selectplaylist'] = "Selecionar lista de reprodução";
$LANGS['profilemsg'] = 'Os espectadores do seu canal verão links aqui, inclusive "Inscrever-se" e "Adicionar como amigo".';
$LANGS['profile'] = 'Perfil';
$LANGS['profilechangessaved'] = 'Alterações salvas.';
$LANGS['posting'] = 'postando...';
$LANGS['name'] = 'Nome';
$LANGS['totaluploadviews'] = 'Total exibições do material enviado';
$LANGS['channeldesc'] = 'Descrição do canal';
$LANGS['hometown'] = 'Cidade natal';
$LANGS['occupation'] = 'Ocupação';
$LANGS['companies'] = 'Empresas';
$LANGS['schools'] = 'Escolas';
$LANGS['interests'] = 'Interesses';
$LANGS['movies'] = 'Filmes';
$LANGS['featuredchannelsdefault'] = 'Clique em "editar" acima para inserir canais que você quer linkar para.';
$LANGS['featuredchannelsdesc'] = 'Por favor liste até 4 canais de destinação na ordem que você deseja mostrá-los no seu canal, separados por vírgulas e sem espaços. Não listar nenhum canal irá impedir está caixa de aparecer no seu canal.';
$LANGS['backtochannel'] = "voltar para o canal de {c}";
$LANGS['refresh'] = "atualizar";
$LANGS['whichcontent'] = "Qual conteúdo você deseja exibir?";
$LANGS['myuploadedvideos'] = "Meus vídeos enviados";
$LANGS['myfavorites'] = "Meus favoritos";
$LANGS['alsoshowall'] = 'Mostrar também "Todas" as visualizações';
$LANGS['featuredvideo'] = 'Vídeo em destaque';
$LANGS['usemostrecent'] = 'Usar o vídeo mais recente do meu conjunto em destaque';
$LANGS['autoplayfeatured'] = "Reproduzir automaticamente o vídeo em destaque";
$LANGS['areyousure'] = "Você tem certeza de que deseja continuar?";
$LANGS['unsavedchanges'] = "Você tem certeza de que deseja trocar o tema? Alterações não salvas serão perdidas.";
$LANGS['showadvancedoptions'] = "mostrar opções avançadas";
$LANGS['hideadvancedoptions'] = "ocultar opções avançadas";
$LANGS['general'] = "Geral";
$LANGS['colorpalettes'] = "Paletas de cores";
$LANGS['font'] = "Fonte";
$LANGS['wrappercolor'] = "Cor do invólucro";
$LANGS['wrappertextcolor'] = "Cor do texto do invólucro";
$LANGS['wrapperlinkcolor'] = "Cor do link do invólucro";
$LANGS['wrappertransparency'] = "Transparência do invólucro";
$LANGS['repeatbackground'] = "Repetir plano de fundo";
$LANGS['titletextcolor'] = "Cor do texto do título";
$LANGS['bodytextcolor'] = "Cor do corpo do texto";
$LANGS['transparency'] = "Transparência";
$LANGS['bgimgdesc'] = "Envie uma imagem que será exibida em segundo plano no seu canal (máximo de 2MB).";
$LANGS['channeltype'] = "Tipo de canal";
$LANGS['channeltags'] = "Palavras-chave do canal";
$LANGS['commaseparated'] = "(separados por vírgula)";
$LANGS['channeltagsdesc'] = "As palavras-chave são usadas para ajudar as pessoas a encontrarem o seu canal.";

/* My Profile page */
$LANGS['myprofiledesc'] = 'Esta página contém todas as configurações para seu canal do BitView.';
$LANGS['profileimages'] = 'Fotos de perfil';
$LANGS['avatar'] = 'Avatar';
$LANGS['backgroundimage'] = 'Imagem de fundo';
$LANGS['deleteimage'] = 'Remover imagem';
$LANGS['channelinformation'] = 'Informação do canal';
$LANGS['genderrelationprivate'] = 'Privado';
$LANGS['fctitle'] = 'F.C. Title';
$LANGS['relationship'] = 'Relacionamento';
$LANGS['birthday'] = 'Aniversário';
$LANGS['showage'] = 'Mostrar idade';
$LANGS['aboutme'] = 'Sobre mim';
$LANGS['emailprefs'] = 'Preferências de e-mail';
$LANGS['emailpm'] = 'Receber e-mail em mensagens privadas';
$LANGS['emailcomm'] = 'Receber e-mail em comentários de vídeo';
$LANGS['emailsub'] = 'Receber e-mail em Destaques de Inscrições semanais';
$LANGS['layoutprefs'] = 'Preferências de layout';
$LANGS['bgcolor'] = 'Cor de fundo';
$LANGS['bgfixed'] = 'Fixo';
$LANGS['bgrepeat'] = 'Repetir';
$LANGS['norepeat'] = 'Não repetir';
$LANGS['repeat'] = 'Repetir';
$LANGS['repeatx'] = 'Repetir X';
$LANGS['repeaty'] = 'Repetir Y';
$LANGS['bgposition'] = 'Posição';
$LANGS['top'] = 'Topo';
$LANGS['middle'] = 'Meio';
$LANGS['bottom'] = 'Fundo';
$LANGS['fontcolor'] = 'Cor da fonte';
$LANGS['titlefontcolor'] = 'Cor da fonte do título';
$LANGS['linkcolor'] = 'Cor do link';
$LANGS['hlfontcolor'] = 'Cor de destaque de fonte';
$LANGS['hlheadercolor'] = 'Destacar cabeçalho';
$LANGS['hlinsidecolor'] = 'Destacar interior';
$LANGS['headercolor'] = 'Cabeçalho regular';
$LANGS['insidecolor'] = 'Cabeçalho interior';
$LANGS['font'] = 'Fonte do canal';
$LANGS['featuredvideobox'] = 'Caixa de vídeo destacado';
$LANGS['subscribersbox'] = 'Caixa de inscritos';
$LANGS['subscriptionsbox'] = 'Caixa de inscrições';
$LANGS['friendsbox'] = 'Caixa de amigos';
$LANGS['bulletinsbox'] = 'Caixa de boletins';
$LANGS['videosbox'] = 'Caixa de vídeos';
$LANGS['favoritesbox'] = 'Caixa de favoritos';
$LANGS['playlistsbox'] = 'Caixa de listas de reprodução';
$LANGS['commentsbox'] = 'Caixa de comentários';
$LANGS['ratingsbox'] = 'Caixa de atividades recentes';
$LANGS['partnersettings'] = 'Configurações de parceiro(a)';
$LANGS['bannerimage'] = 'Imagem do banner';
$LANGS['minibannerimage'] = 'Mini imagem do banner';
$LANGS['sideimage'] = 'Imagem lateral';
$LANGS['recommendedsize'] = 'tamanho recomendado';
$LANGS['bannerlink'] = 'Site do banner';
$LANGS['sideimagelink'] = 'Site da imagem lateral';
$LANGS['custombox'] = 'Caixa customizada';
$LANGS['customboxtitle'] = 'Título da caixa customizada';
$LANGS['customboxcontent'] = 'Conteúdo da caixa customizada';
$LANGS['savechanges'] = 'Salvar alterações';
$LANGS['submitimage'] = 'Enviar imagem';
$LANGS['overview'] = 'Visão geral';
$LANGS['profilesetup'] = 'Configuração do perfil';
$LANGS['playbacksetup'] = 'Configuração da reprodução';
$LANGS['emailoptions'] = 'Opções de e-mail';
$LANGS['manageaccount'] = 'Gerenciar conta';
$LANGS['chvideoviews'] = 'Exibições de vídeo';
$LANGS['change'] = "mudar";
$LANGS['mynetwork'] = "Minha rede";
$LANGS['contacts'] = "Contatos";
$LANGS['chvideocomments'] = "Comentários de vídeo";
$LANGS['chmore'] = "Mais";
$LANGS['changepicture'] = "Mudar imagem";
$LANGS['changepicturedesc'] = "Você pode enviar um arquivo JPG, BMP, ou PNG. Não envie imagens contendo celebridades, nudez, trabalho artístico ou imagens protegidas por direitos autorais. Sua imagem será exibida como um quadrado 88px por 88px . <b>Tamanho de arquivo máximo é 2 MB.</b>";
$LANGS['describeyourself'] = "Descreva-se";
$LANGS['personaldetails'] = "Detalhes pessoais";
$LANGS['jobscareer'] = "Trabalhos / Carreira";
$LANGS['education'] = "Educação";
$LANGS['videoplaybackquality'] = "Qualidade da reprodução de vídeo";
$LANGS['videoplaybackqualitydesc'] = "Escolha a configuração padrão para visualizar vídeos";
$LANGS['alwayshd'] = "Sempre reproduzir vídeos em alta definição";
$LANGS['neverhd'] = "Nunca reproduzir vídeos em alta definição";
$LANGS['currentemail'] = "Endereço de e-mail atual";
$LANGS['changeemailaddress'] = "Alterar endereço de e-mail";
$LANGS['changeemail'] = "Alterar e-mail";
$LANGS['partnerimages'] = "Imagens de parceiro(a)";
$LANGS['partnerimagelinks'] = "Links de imagens de parceiro(a)";
$LANGS['accountstatuscg'] = "Status da conta: Diretrizes da comunidade";
$LANGS['accountstatuscopy'] = "Status da conta: Direitos autorais";
$LANGS['changeusername'] = "Mudar nome de usuário";
$LANGS['changepassword'] = "Mudar senha";
$LANGS['deleteaccount'] = "Apagar conta";
$LANGS['goodaccount'] = "Your account is in good standing.";
$LANGS['accountstrike'] = "Você tẽm {s} strike. Tome cuidado!";
$LANGS['accountstrikes'] = "Você têm {s} strikes. Tome cuidado!";
$LANGS['cannotchangeusername'] = "Você não pode trocar seu nome de usuário ainda! Por favor espere até ";
$LANGS['usernamechangedesc'] = "Você só poderá trocar seu nome de usuário uma vez por ano, então escolha seu novo nome de usuário bem.";
$LANGS['newusername'] = "Novo nome de usuário";
$LANGS['currentpassword'] = "Senha atual";
$LANGS['newpassword'] = "Nova senha";
$LANGS['confirmnewpassword'] = "Confirmar nova senha";
$LANGS['enterpassword'] = "Por razões de segurança, por favor digite sua senha";

/* Upload page */
$LANGS['uploadpagetitle'] = 'Envio de arquivo de vídeo';
$LANGS['step1of2'] = 'Passo 1 de 2';
$LANGS['step2of2'] = 'Passo 2 de 2';
$LANGS['videocategory'] = 'Categoria';
$LANGS['tagsdesc'] = 'Marcações são palavras-chave usadas para ajudar as pessoas à encontar seu vídeo..<br> <i>(comma separated)</i>';
$LANGS['requiredfield'] = '(* indicates required field)';
$LANGS['datemapoptions'] = 'Opções de data e mapa:';
$LANGS['optional'] = '(opicional)';
$LANGS['chooseoptions'] = 'escolher opções';
$LANGS['lessoptions'] = 'menos opções';
$LANGS['addressrecorded'] = 'Endereço gravado:';
$LANGS['uploadcontinue'] = 'Enviar um vídeo...';
$LANGS['file'] = 'Arquivo';
$LANGS['broadcastoptions'] = 'Opções de transmissão';
$LANGS['uploadvideo'] = 'Enviar vídeo';
$LANGS['needfilevideotoupload'] = 'Por favor selecione um arquivo de vídeo para enviar!';
$LANGS['aboutuploading'] = 'Sobre envio de vídeos...';
$LANGS['uploaddesc1'] = 'Uploads usually take 1-5 minutes per MB on a high-speed connection, and converting your video takes a few minutes.';
$LANGS['videolimit1'] = 'Your video is limited to 100MB - maximum video length is 15 minutes.';
$LANGS['videolimit2'] = 'Your video is limited to 2GB - maximum video length is 15 minutes.';
$LANGS['partnervideolimit1'] = 'Your video is limited to 100MB - maximum video length is 30 minutes.';
$LANGS['partnervideolimit2'] = 'Your video is limited to 2GB - maximum video length is 30 minutes.';
$LANGS['myvideosdesc'] = 'After uploading you can edit or remove this video at anytime under the "<a href="/my_videos">My Videos</a>" link on the top of the page.';
$LANGS['newuploader'] = 'Usar o novo aplicativo de envio';
$LANGS['olduploader'] = 'Usar o antigo aplicativo de envio';
$LANGS['videoadded'] = 'Your video was successfully added!';
$LANGS['videoaddeddesc'] = 'Your video is currently being processed and will be available to view in a few minutes.';
$LANGS['thankyou'] = 'Thank You';
$LANGS['sharelink'] = 'Share your video link! Copy and paste below:';
$LANGS['embedlink'] = 'Play this video directly ON your website! Copy and paste the following snippet:';
$LANGS['allrequiredinfo'] = 'Please fill all required fields!';
$LANGS['videoscanbe'] = 'Os vídeos podem ser...';
$LANGS['uploadhd'] = 'Alta definição';
$LANGS['uploadsize'] = 'Até 2 GB de espaço.';
$LANGS['uploadlength'] = 'Até 15 minutos de duração.';
$LANGS['uploadlengthpartners'] = 'Até 1 hora de duração.';
$LANGS['uploadformats'] = 'Uma grande variedade de formatos.';
$LANGS['basicuploader'] = 'Problemas com o envio? Tente o <a href="/my_videos_upload_basic">aplicativo de envio básico</a> (funciona em computadores e navegadores da web mais antigos.).';
$LANGS['uploadinstruction1'] = '<strong>Importante:</strong> Não envie nenhum programa de TV, videoclipe, show ou comercial sem permissão, a não ser que o conteúdo seja totalmente de sua autoria.';
$LANGS['uploadinstruction2'] = 'As <a href="/guidelines">Diretrizes da comunidade</a> podem ajudar a determinar se seu vídeo infringe os direitos autorais de algúem.';
$LANGS['uploadinstruction3'] = 'Ao clicar em "Enviar vídeo", você está declarando que este vídeo não viola os <a id="terms-of-use-link" href="/terms">Termos de Uso</a> do BitView e que você possui todos os direitos autorais deste vídeo ou tem autorização para enviá-lo.';
$LANGS['fileuploaded'] = 'Your file has been uploaded. We are now processing the video...';
$LANGS['videosettingssaved'] = 'Your video settings have been saved.';
$LANGS['uploadprogress'] = 'Progresso do envio:';
$LANGS['timeremaining'] = 'Sobre {m} min. restantes...';
$LANGS['minuteremaining'] = 'Menos de 1 minuto restante...';
$LANGS['preview'] = 'Visualizar:';
$LANGS['processing'] = 'Processando';
$LANGS['generatingpreviews'] = 'Gerando visualizações...';
$LANGS['errorpreview'] = "Erro: não conseguimos gerar uma visualização";
$LANGS['infoandprivacy'] = "Informações do vídeo e configurações de privacidade";
$LANGS['sharingoptions'] = "Opções de compartilhamento";
$LANGS['url'] = "URL";
$LANGS['durationerror'] = "You can only upload videos up to {n} minutes in length.";

/* Video Response Upload */
$LANGS['postingresponse'] = "You are posting a Video Response to: ";
$LANGS['responsessofar'] = "{n} Video Response(s) so far";
$LANGS['chooseavideo'] = "Choose a Video";
$LANGS['uploadavideo'] = "Upload a Video";
$LANGS['responsesdesc1'] = "<h4>What is a Video Response?</h4><p>Ever wanted to talk back to a video? Now's your chance – you can upload a response to this video and we'll link them together.</p>";
$LANGS['responsesdesc2'] = "<h4>How do I post a Video Response?</h4><p>You can record a new video, choose from the videos that you already have or create and upload a new video. Select the option on the left that best suits your needs.</p>";
$LANGS['responsesdesc3'] = '<h4>Oops! I actually meant to post a text comment. How do I do this?</h4><p>Return to the video (by hitting the "back" button on your browser or clicking the title of the video at the top of this page) and click "Post a Text Comment".</p>';
$LANGS['choosevideotitle'] = "Choose one of your existing videos as a response";
$LANGS['selectvideo'] = "Select the video that you want to respond with:";
$LANGS['useselectedvideo'] = "Use the selected video";
$LANGS['uploadvideoresponse'] = "Upload your Video Response";
$LANGS['clickstart'] = 'Click "Start" to begin uploading your Video Response.';
$LANGS['start'] = 'Start';

/* Partners */
$LANGS['partnerhead'] = 'Partnerships';
$LANGS['partnertitle'] = 'Partner With BitView';
$LANGS['partnerdesc'] = "You've got great videos and a growing audience. Let BitView help you take it to the next level through our Partner Program.";
$LANGS['applynow'] = 'Apply now';
$LANGS['contentpartners'] = 'Content Partners';
$LANGS['partnerbenefits'] = 'Partner Benefits';
$LANGS['partnerbenefitsdesc'] = 'There are many benefits to becoming a BitView Partner. Some of them include:<br><br>- Branding: make yourself stand out with custom branding, which includes banners, a custom box for your channel and a partner badge on all your videos.<br><br>- There are more benefits to come in the future!';
$LANGS['qualificationsfaq'] = 'Qualifications & FAQ';
$LANGS['qualificationsfaqdesc'] = 'To qualify for the BitView Partner program, you must meet some minimum criteria:<br><br>- You create original videos suitable for online streaming.<br><br>- You have >75 subscribers.<br><br>- Your account does not break any <a href="/guidelines">Community Guidelines.</a>';

/* Staff */
$LANGS['bvstaff'] = 'Equipe BitView';
$LANGS['bvstaffdesc'] = "This is a list of people who worked (or still works) on BitView - keeping the website' alive - so users can Express Themselves.";
$LANGS['owners'] = 'Owners';
$LANGS['ownerdesc'] = 'People who - what a shocking fact - owns the BitView thingy.';
$LANGS['coowndev'] = 'Co-Owner & <br> Developer';
$LANGS['owndev'] = 'Owner & <br> Developer';
$LANGS['coownserver'] = 'Co-Owner &<br>Server Owner/Developer';
$LANGS['modsanddevs'] = 'Moderators and Developers';
$LANGS['modsanddevsdesc'] = 'People who keep the website safe and clear. Have any problem with your account? You should contact them.';
$LANGS['moderator'] = 'Moderator';
$LANGS['moddev'] = 'Developer &<br>Moderator';
$LANGS['lettertitle'] = 'Letter to all the people who helped with the website';
$LANGS['letter'] = "Dear Co-Owners, Developers, and Moderators of BitView,<br><br>
                On behalf of the entire BitView team, I would like to express my heartfelt gratitude for your exceptional dedication and hard work. As one of the owners, it fills me with immense pride to witness the growth and success of our video-sharing platform, and it would not have been possible without your invaluable contributions.
                <br><br>
                To rest of the Co-Owners, thank you for your unwavering support and vision. Your commitment to the platform's development and improvement has been instrumental in shaping BitView.net into the remarkable community it is today. Your leadership and strategic guidance have been vital in navigating the challenges and opportunities that have come our way.
                <br><br>
                To our talented Developers, your technical expertise and innovative ideas have transformed BitView into a cutting-edge platform that perfectly represent how YouTube looked like back in the days. Your countless hours of coding, problem-solving, and feature implementation have elevated the user experience and made our platform a hub of creativity and entertainment. Your dedication to refining the functionality and performance of the site has been truly commendable.
                <br><br>
                To our diligent Moderators, I extend my deepest appreciation for maintaining the integrity and safety of our community. Your vigilance in enforcing the rules and guidelines, ensuring respectful interactions, and swiftly addressing any issues that arise has been crucial in fostering a welcoming environment for all users. Your efforts in keeping BitView a space for constructive engagement and positive content are highly commendable.
                <br><br>
                Together, as a unified team, we have achieved significant milestones and overcome numerous obstacles. The success of BitView is a testament to the collective effort and passion each one of you brings to the table. Your commitment to our shared vision has been truly inspiring, and I am grateful to have such exceptional individuals by my side.
                <br><br>
                As we continue to grow and evolve, let us cherish the bonds we have forged and remain committed to the values that define our little site. Together, we will continue that nostalgia trip and provide a platform for creators to showcase their talents.
                <br><br>
                Once again, thank you: Co-Owners, Developers, and Moderators, for your unwavering dedication, expertise, and unwavering support. Your hard work has not gone unnoticed, and I am incredibly proud to be part of this remarkable team.
                <br><br>
                Keep expressing yourself,<br>
                <3 vistafan12";
$LANGS['backtobitview'] = "Back to BitView";

/* My Friends */
$LANGS['myfriends'] = 'Meus amigos';
$LANGS['invites'] = 'Invites';
$LANGS['myinvites'] = 'My Invites';
$LANGS['incominginvites'] = 'Incoming Invites';
$LANGS['noinvites'] = 'You have no invites...';
$LANGS['actions'] = 'Actions';
$LANGS['retract'] = 'Retract';

/* History */
$LANGS['clearhistory'] = "Limpar o histórico de exi";
$LANGS['noviewinghistory'] = "There are no videos in your history.";
$LANGS['addto'] = "Add to";
$LANGS['sortorder'] = "Order";
$LANGS['sortnewest'] = "Newest";
$LANGS['sortoldest'] = "Oldest";
$LANGS['sortmostviewed'] = "Most viewed";
$LANGS['sortlongest'] = "Longest";
$LANGS['sortshortest'] = "Shortest";
$LANGS['sortaz'] = "A-Z";
$LANGS['sortza'] = "Z-A";
$LANGS['newpltitle'] = "Playlist title";
$LANGS['newpldesc'] = "Playlist description";
$LANGS['newpltags'] = "Playlist tags";
$LANGS['newplbutton'] = "Create playlist";
$LANGS['addvideos'] = "Add videos";
$LANGS['liked'] = "Liked";
$LANGS['mylikedvideos'] = "My Liked Videos";
$LANGS['savedtoplaylist'] = "Videos saved to playlist(s) successfully!";
$LANGS['sureremovevideos'] = "Are you sure you want to delete the selected videos?";
$LANGS['remove'] = "Remove";
$LANGS['plvideoamountsingular'] = "video";

/* QuickList */
$LANGS['playquicklist'] = "Reproduzir lista rápida";
$LANGS['clearquicklist'] = "Limpar lista rápida";
$LANGS['noquicklist'] = "Não há vídeos em sua lista rápida.";
$LANGS['noquicklistdesc'] = "QuickList lets you make a video list for later viewing. Click on the &quot;+&quot; (in the lower left) of any video to add it to your QuickList. To view your list, look for the QuickList bar under any video you're watching.";
$LANGS['quicklistcleared'] = "Your Quicklist has been cleared successfully.";
$LANGS['addedtoquicklist'] = "Added to <br> Quicklist";
$LANGS['queue'] = "Fila";
$LANGS['playqueue'] = "Play Queue";
$LANGS['clearqueue'] = "Clear Queue";
$LANGS['addtoqueue'] = "Adicionar à fila";
$LANGS['addedtoqueue'] = "Adicionadio á <br> fila";

/* About */
$LANGS['aboutus'] = 'Sobre nós';
$LANGS['abouttitle'] = 'O que é BitView?';
$LANGS['aboutdesc'] = 'BitView is a way to get your videos to the people who matter to you. With BitView you can:';
$LANGS['about1'] = 'Show off your favorite videos to the world';
$LANGS['about2'] = 'Take videos of your dogs, cats, and other pets';
$LANGS['about3'] = 'Blog the videos you take with your digital camera or cell phone';
$LANGS['about4'] = 'Securely and privately show videos to your friends and family around the world';
$LANGS['about5'] = '... and much, much more!';
$LANGS['aboutsignup'] = '<a href="/signup">Sign up now</a> and open a free account.';
$LANGS['abouthelp'] = 'To learn more about our service, please see our <a href="help">Help</a> section.';
$LANGS['aboutmail'] = 'Please feel free to <a href="mailto:bitview@vistafan12.eu.org">contact us</a>.';

/* Community Guidelines */
$LANGS['bvguidelines'] = 'BitView Community Guidelines';
$LANGS['cgtitle1'] = 'Respect the BitView Community';
$LANGS['cgtitle2'] = "Don't Cross the Line";
$LANGS['cgtitle3'] = 'We Enforce These Guidelines';
$LANGS['cgtitle4'] = 'BitView is for the Community';
$LANGS['cgtitle5'] = 'Community Guideline Tips';
$LANGS['cgdesc1'] = "We're not asking for the kind of respect reserved for nuns, the elderly, and brain surgeons. We mean don't abuse the site. Every cool new community feature on BitView involves a certain level of trust. We trust you to be responsible, and millions of users respect that trust. Please be one of them.";
$LANGS['cgdesc2'] = "Here are some common-sense rules that will help you steer clear of trouble:";
$LANGS['cgdesc3'] = "Please take these rules seriously and take them to heart. Don't try to look for loopholes or try to lawyer your way around the guidelines — just understand them and try to respect the spirit in which they were created. If you'd like more details, check out our <a href='#tips'>Community Guideline Tips</a>.";
$LANGS['cgdesc4'] = "Okay, this one is more about us than you. BitView staff review flagged videos 24 hours a day, seven days a week to determine whether they violate our Community Guidelines. When they do, we remove them. Sometimes a video doesn’t violate our Community Guidelines, but may not be appropriate for everyone. These videos may be age-restricted. Accounts are penalized for Community Guidelines violations and serious or repeated violations can lead to account termination. If your account is terminated, you won’t be allowed to create any new accounts. For more information about how the Community Guidelines are enforced and the consequences of violating them, please visit the <a href='/help'>Help Center</a>.";
$LANGS['cgdesc5'] = "Remember that this is your community! Each and every  user of BitView makes the site what it is, so don't be afraid to dig in and get involved!";
$LANGS['cgdesc6'] = "That's it! Thanks for reading!";
$LANGS['cgdesc7'] = "Want a little more insight into the limits and exceptions in the Community Guidelines? Here are some helpful examples and tips:";
$LANGS['rule1'] = "BitView is not for pornography or sexually explicit content. If this describes your video, even if it's a video of yourself, don't post it on BitView. Also, be advised that we work closely with law enforcement and we report child exploitation.";
$LANGS['rule2'] = "Don't post videos showing bad stuff like animal abuse, drug abuse, under-age drinking and smoking, or bomb making.";
$LANGS['rule3'] = "Graphic or gratuitous violence is not allowed. If your video shows someone being physically hurt, attacked, or humiliated, don't post it.";
$LANGS['rule4'] = "BitView is not a shock site. Don't post gross-out videos of accidents, dead bodies or similar things intended to shock or disgust.";
$LANGS['rule5'] = "Respect copyright. Only upload videos that you made or that you are authorized to use. This means don't upload videos you didn't make, or use content in your videos that someone else owns the copyright to, such as music tracks, snippets of copyrighted programs, or videos made by other users, without necessary authorizations.";
$LANGS['rule6'] = "We encourage free speech and defend everyone's right to express unpopular points of view. But we don't permit hate speech (speech which attacks or demeans a group based on race or ethnic origin, religion, disability, gender, age, veteran status, and sexual orientation/gender identity). This also applies to the promotion of extremist ideologies in a positive light.";
$LANGS['rule7'] = "Things like predatory behavior, stalking, threats, harassment, intimidation, invading privacy, revealing other people’s personal information, and inciting others to commit violent acts or to violate the Terms of Use are taken very seriously. Anyone caught doing these things may be permanently banned from BitView.";
$LANGS['rule8'] = "Everyone hates spam. Don’t create misleading descriptions, tags, titles or thumbnails in order to increase views. It's not okay to post large amounts of untargeted, unwanted or repetitive content, including comments and private messages.";
$LANGS['rule9'] = "Let's keep the website safe. Don't try to brute force an account you do not own. Moreover, sharing an account's login information publicly is not allowed.";
$LANGS['rule10'] = "Multi-accounts suck. We want genuine numbers on videos and channels. Don't use more than one account to rate videos and/or comments. You are not allowed to use multiple accounts to subscribe to yourself either.";
$LANGS['rule11'] = "Did you break one of this rules and your account has been suspended? It goes without saying that evading this punishment is not accepted. Every new account that has been created by a suspended person will be automatically deleted.";
$LANGS['cglist1'] = "Have fun with the site. There's a lot to see here, and lots of folks making amazing stuff — one of them might be you! Equipment's getting cheaper and easier to use all the time, so dive in and enjoy.";
$LANGS['cglist2'] = "Let folks know what you think. Feedback's part of the experience, and when done with respect, can be a great way to make friends, share stories, and make your time on BitView richer. So leave comments, rate videos, make your own responses to videos that affect you, enter contests of interest — there's a lot going on and a lot of ways to participate.";
$LANGS['cglist3'] = "You may not like everything you see. Some of the content here may offend you — if you find that it violates our Terms of Use, then click the button that says &quot;Flag&quot; under the video you're watching to submit it for review by BitView staff. If it doesn't, then consider just clicking on something else — why waste time watching videos you don't like?";
$LANGS['thebitviewteam'] = "— The BitView Team";
$LANGS['cgcat1'] = "Nudez e conteúdo pornográfico";
$LANGS['cgcat2'] = "Discurso de ódio";
$LANGS['cgcat3'] = "Shocking and Disgusting";
$LANGS['cgcat4'] = "Atos ilegais";
$LANGS['cgcat5'] = "Crianças";
$LANGS['cgcat6'] = "Direitos autorais";
$LANGS['cgcat7'] = "Privacidade";
$LANGS['cgcat8'] = "Harassment";
$LANGS['cgcat9'] = "Impersonação";
$LANGS['cgcat10'] = "Ameaças";
$LANGS['cgcat1desc'] = "Most nudity is not allowed, particularly if it is in a sexual context. Generally if a video is intended to be sexually provocative, it is less likely to be acceptable for BitView. There are exceptions for some educational, documentary and scientific content, but only if that is the sole purpose of the video and it is not gratuitously graphic. For example, a documentary on breast cancer would be appropriate, but posting clips out of context from the documentary might not be. This also applies for animated content.";
$LANGS['cgcat2desc'] = 'Hate speech" refers to content that promotes hatred against members of a protected group. For instance, racist or sexist content may be considered hate speech. Sometimes there is a fine line between what is and what is not considered hate speech. For instance, it is generally okay to criticize a nation, but not okay to make insulting generalizations about people of a particular nationality.';
$LANGS['cgcat3desc'] = "The world is a dangerous place. Sometimes people do get hurt and it’s inevitable that these events may be documented on BitView. However, it’s not okay to post violent or gory content that’s primarily intended to be shocking, sensational or disrespectful. If a video is particularly graphic or disturbing, it should be balanced with additional context and information. For instance, including a clip from a slaughter house in a video on factory farming may be appropriate. However, stringing together unrelated and gruesome clips of animals being slaughtered in a video may be considered gratuitous if its purpose is to shock rather than illustrate.";
$LANGS['cgcat4desc'] = "While it might not seem fair to say you can’t show something because of what viewers theoretically might do in response, we draw the line at content that’s intended to incite violence or encourage dangerous, illegal activities that have an inherent risk of serious physical harm or death. This means not posting videos on things like instructional bomb making, ninja assassin training, sniper attacks, videos that train terrorists, or tips on illegal street racing. Any depictions like these should be educational or documentary and shouldn’t be designed to help or encourage others to imitate them.";
$LANGS['cgcat5desc'] = "Videos involving children (anyone under the age of 18) are particularly sensitive. Videos containing children should never be sexually suggestive or violent. Please be cautious when posting something involving a child. If you’re sharing a private moment or home movie, consider making it a private video so that only your family and friends can see it. Moreover, by agreeing to the <a href='/terms'>Terms of Use</a>, you affirm that you are over the age of 13. Accounts belonging to underage users will be suspended.";
$LANGS['cgcat6desc'] = "When you create something original, you own the copyright for it. Likewise, when other people create content, they may have a copyright to it. As a creative community, it’s essential that everyone on BitView respect the copyrights of others. If you’re not sure if something will violate someone’s copyright, the safest thing to do is to create something completely original, with images and audio you’ve created. If it’s all yours you never have to worry about copyright — you own it. If you’ve recorded something from a DVD, videotaped your TV screen, or downloaded a video online, don’t post it unless you have permission.";
$LANGS['cgcat7desc'] = "If a video you've recorded features people who are readily identifiable and who haven't consented to being filmed, there's a chance they'll file a privacy complaint seeking its removal. We'll notify you if that happens and give you a chance to edit and re-upload your video before we act on the complaint. If we do remove your video for privacy reasons, don't upload another version featuring the same people. Chances are those people will file another privacy complaint or report you for harassment. Don't post other people's personal information, including phone numbers, addresses, credit card numbers, and government IDs. We're serious about keeping our users safe and suspend accounts that violate people's privacy.";
$LANGS['cgcat8desc'] = "It comes down to respect. BitView is all about sharing and interacting with the community in respectful ways. If you're not sure whether a video or comment you've made crosses the line, follow a simple rule of thumb: if you wouldn't say it to someone's face, don't say it on BitView. And if you're looking to attack, harass, demean, or impersonate others, go elsewhere.";
$LANGS['cgcat9desc'] = "Impersonating another user by copying someone's exact channel layout, using a similar username, or posing as that person in comments, emails or videos is considered harassment. If you want to keep your account, stay away from participating in any form of impersonation or harassing activity on the site.";
$LANGS['cgcat10desc'] = "Users shouldn't feel threatened when they're on BitView. Period. Don't leave threatening comments on other people's videos.";

/* Contests */
$LANGS['monthlycontest'] = "Concurso mensal";
$LANGS['monthlycontestschedule'] = "Monthly Video Contest Schedule";
$LANGS['whatisit'] = "What is it?";
$LANGS['thismonthcontest'] = "Este mês";
$LANGS['lastmonthwinners'] = "Last Month Winners";
$LANGS['howtoenter'] = "Como entrar?";
$LANGS['whowins'] = "Quem vence?";
$LANGS['whowinsdesc'] = "The winner will be picked at the end of the month by the BitView staff.";
$LANGS['theprize'] = "The Prize?";
$LANGS['theprizedesc'] = "Fame, fortune, and the envy of all eyes.";
$LANGS['contestsuggestion'] = 'Have a suggestion for a monthly video contest? Please <a href="mailto:bitview@vistafan12.eu.org">Tell us</a> about it.';

/* Help */
$LANGS['q1'] = 'Q: How can I share my videos and link to them from my website?';
$LANGS['a1'] = 'A: <a href="/sharing">How to share and link to your videos</a>';
$LANGS['q2'] = 'Q: What kind of videos can I upload?';
$LANGS['a2'] = 'A: You may upload any kind of personal video that you would like to share with the world. We do not allow any nudity and your video must be appropriate for all audiences.
<br/>
<br/>
However, this still leaves a lot of room for creativity!! Do you own a <a href="results?search=dog&t=Search+Videos">dog</a> or a <a href="/results?search=cat&t=Search+Videos">cat</a>? Have you gone on vacationing in <a href="/results?search=mexico&t=Search+Videos">Mexico</a>? Do you live in <a href="/results?search=netherlands&t=Search+Videos">The Netherlands</a>?
<br/>
<br/>
These are just some examples of the videos that our users are uploading. In the end, you know yourself best. What would <i>you</i> like to capture on video?';
$LANGS['q3'] = 'Q: How long can my video be?';
$LANGS['a3'] = 'A: The video must be under 15 minutes long and less than 2GB in size (100MB if you use an old browser).';
$LANGS['q4'] = 'Q: What video file formats can I upload?';
$LANGS['a4'] = 'A: BitView accepts video files from most digital cameras and from cell phones in the .WMV, .AVI, .MOV, .MPG, .MP4 file formats.';
$LANGS['q5'] = 'Q: How can I improve my videos?';
$LANGS['a5'] = 'A: We encourage you to edit your videos with software such as <a href="https://windows-movie-maker-vista.en.softonic.com/" target="_blank">Windows Movie Maker</a> (included with every Windows installation), or <a href="https://www.apple.com/lae/imovie/" target="_blank">Apple iMovie</a>. Using these programs you can easily edit your videos, add soundtracks, etc.';
$LANGS['q6'] = 'Q: Do I retain copyrights and other legal rights to my videos?';
$LANGS['a6'] = 'A: Yes. You retain all rights to your content. BitView assumes no copyright to your material.';
$LANGS['q7'] = 'Q: What is your policy on copyright infringement?';
$LANGS['a7'] = "A: BitView respects the rights of copyright holders and publishers and is only accepting video uploads from persons who hold all necessary rights to the uploaded material. Our policy is to respond to any notices of alleged infringement that comply with the Digital Millennium Copyright Act (DMCA). If we receive a notice or otherwise have reason to believe that content you submitted infringes another party's copyright, your account may be terminated and the video removed from BitView.";
$LANGS['q8'] = 'Q: How do I report copyright infringement?';
$LANGS['a8'] = 'A: If you believe that someone else has uploaded your copyrighted content without your permission, we encourage you to contact that person in order to resolve any differences with them directly. You can also contact our support team using this <a href="mailto:bitview@vistafan12.eu.org">email</a>.';
$LANGS['q9'] = 'Q: What if I have been falsely accused of copyright infringement?';
$LANGS['a9'] = "A: We'll let you know if we receive a copyright complaint about any of your video content that is hosted on BitView. We'll give you the opportunity to respond appropriately.";
$LANGS['q10'] = 'Q: What are you doing to prevent content that violates your policies from appearing in BitView?';
$LANGS['a10'] = 'A: We do a preliminary review on uploaded videos through both a manual and automated process. Although we try our best to detect and remove videos that violate our policy guidelines, our review process is primarily focused on removing adult content or obvious copyright violations, and is not bulletproof. However, we encourage our viewers to notify us when they discover policy violations or copyright issues -- we have a process for reviewing reported policy violations, and respond to reported copyright violations under the Digital Millennium Copyright Act.';
$LANGS['q11'] = 'Q: Do you have a Discord server or Twitter?';
$LANGS['a11'] = 'Yes! We actually have a Discord server and Twitter. You can join into the Discord server by clicking <a href="https://discord.gg/wgGaqCmwuQ">here</a>, and follow us on Twitter <a href="https://twitter.com/bitview_">here</a>.';
$LANGS['q12'] = "Q: I'm using an old browser while on BitView and thus can't watch videos. What can I do?";
$LANGS['activate'] = 'Activate';
$LANGS['deactivate'] = 'Deactivate';
$LANGS['flashdisclaimer'] = "<b>Note:</b> BitView's Flash Player is being offered as a compatibility option. If your browser supports BitView's HTML5 player you shouldn't enable this option.";

/* BitView on your site */
$LANGS['bvsitetitle1'] = "O básico";
$LANGS['bvsitetitle2'] = "APIs and User Engagement";
$LANGS['bvsitedesc1'] = 'Whatever presence you have on the Internet—a large website, a blog, a social network page, or pretty much anything else—there are many ways to integrate BitView into it. From simple video embeds to our full-powered APIs, you can integrate video at all levels of technical expertise.';
$LANGS['bvsitedesc2'] = 'Bringing BitView to your site is more than just adding some of the thousands of videos available on BitView. It keeps your visitors interested and allows self-expression and interaction with one of their favorite services. And it brings your site, blog, or page into the BitView video community — an international network of users, creators, and sites connected through a huge collection of online videos.';
$LANGS['bvsitedesc3'] = "We've highlighted some typical ways of integrating video content below — just click the arrow next to the question to get the answer. If you have any questions or suggestions, or projects that you would like us to know about, please leave the questions in our <a href='https://discord.gg/wgGaqCmwuQ'>Discord server</a>.";
$LANGS['bvsitesectiontitle1'] = "How do I add a video to my blog or web page?";
$LANGS['bvsitesectiontitle2'] = "How do I add a video to my social network page?";
$LANGS['bvsitesectiontitle3'] = "I work for a large blog/web company. How can video increase user engagement on our site?";
$LANGS['bvsitesectiontitle4'] = "We have a site and we have our own videos. Can we post these on our site using BitView?";
$LANGS['bvsitesection1desc1'] = "You'll need to edit the HTML of your blog entry or page—this should be relatively straightforward. In Blogger, for example, just click the &quot;Edit HTML&quot; tab.";
$LANGS['bvsitesection1desc2'] = "Next, go to the video that you want, and look for the 'Embed' box in the &quot;About This Video&quot; section. Copying the HTML code that's there into your website will create an embedded player; the video will play within your site when the user clicks on the 'Play' button.";
$LANGS['bvsitesection1desc3'] = "You can resize the player by editing the <em>object width=&quot;425&quot;</em> and  <em>height=&quot;350&quot;</em> fields at both the beginning and end of the embedded player code. Make sure that the sizes you choose have the same ratio as the default numbers, so that the video doesn't get stretched—just multiply the width by 0.8235 to get the height.";
$LANGS['bvsitesection2desc1'] = "Adding videos to your profiles on social networks like SpaceHey is a great way to share your videos or favorites with friends. Or, if you're promoting something (like your band) on SpaceHey, videos will help attract visitors to your page, who can then then share the link with their friends. The social network sites have similar ways to add videos, so we'll use SpaceHey as an example.";
$LANGS['bvsitesection2desc2'] = 'Sign in to your SpaceHey profile, then click the "Edit Profile" button.';
$LANGS['bvsitesection2desc3'] = "Next, go to the video that you want, and look for the 'Embed' box in the &quot;About This Video&quot; section. Copying the HTML code that's there into your website will create an embedded player.";
$LANGS['bvsitesection2desc4'] = "You can resize the player by editing the object width=&quot;425&quot; and height=&quot;350&quot; fields at both the beginning and end of the embedded player code. Make sure that the sizes you choose have the same ratio as the default numbers, so that the video doesn't get stretched—just multiply the width by 0.8235 to get the height.";
$LANGS['bvsitesection2desc5'] = 'Click "Preview", and then "Submit".';
$LANGS['bvsitesection3desc1'] = "Video is much more engaging than text. It draws more users and keeps them on your site for longer. BitView has a large repository of Internet video content along with the search, playback and API tools to make adding video easier for you.";
$LANGS['bvsitesection3desc2'] = "When looking to increase engagement, try using video as a way to start discussion or make a commentary by creating more context for your users:";
$LANGS['bvsitesection4desc1'] = "It's very easy to build out your own site with your own videos for free. All you need to do is upload the videos to BitView first. There's no charge and we will cover hosting and streaming costs. It's not only a great way to increase user engagement on your site, but it's very easy, and free as well.";
$LANGS['bvsitesection4desc2'] = "Once you have uploaded the videos you can pull them back to the site:";
$LANGS['bvsitesection4desc3'] = "<b>Embed videos one-by-one:</b> Go to the video that you want to put on your website, and look for the 'Embed' box next to the video player. Copying the HTML code that's there into your blog will create an embedded player; the video will play within your site when the user clicks on the 'Play' button.";

/* RSS Feeds */
$LANGS['rsstitle1'] = "O que são feeds RSS?";
$LANGS['rsstitle2'] = "How to Access RSS Feeds";
$LANGS['rsstitle3'] = "How to Subscribe to BitView's RSS Feeds";
$LANGS['rssdesc1'] = "Really Simple Syndication (RSS) is an XML-based format used for content distribution and syndication. Subscribing to RSS feeds allows you to receive custom, up-to-date information from your favorite online content sources without having to regularly check the site for updates.";
$LANGS['rssdesc2'] = "News readers that display RSS feeds from the websites you specify—they check the RSS feeds you have subscribed to and display new items from each feed. You can download news reader applications for your computer, and here are also many popular web-based news readers available, such as Google Reader and Bloglines. Some web browsers and email applications also have RSS capabilities built in.";
$LANGS['rssdesc3'] = "You can see a list of many available news readers at <a href='http://en.wikipedia.org/wiki/List_of_feed_aggregators'>Wikipedia</a>."; //Use your language's Wikipedia article if possible
$LANGS['rssdesc4'] = "BitView offers several RSS feeds for categorized groups of videos (such as recently uploaded, top viewed etc) as well as customized feeds for users and tags.";
$LANGS['rssdesc5'] = "To subscribe to categorized groups of videos, simply go to the category you want (for example, &quot;<a href='/browse'>Most Viewed - Today</a>&quot;). Then click on the orange 'RSS' button. This should trigger your chosen news reader to add the subscription.";
$LANGS['rssdesc6'] = "If your browser has RSS capabilities, then you can add the feed there. The command varies between browsers, but can usually be found on the 'File' or 'Bookmarks' menus, and will be called something like &quot;Subscribe to this page&quot; or &quot;New Live Bookmark&quot;.";
$LANGS['rssthispage'] = "RSS this page";

/* TestView */
$LANGS['testviewdesc'] = "Welcome to TestView, our ideas incubator. This is where BitView engineers and developers test out recipes and concoctions that aren't quite fully baked and invite you to tell us how they're coming along.";
$LANGS['flashvideo'] = "Flash Video";
$LANGS['flashvideodesc'] = "Your browser doesn't support HTML5 video? Don't worry! Try out our Flash player.";
$LANGS['feather'] = "Feather";
$LANGS['featherdesc'] = "View BitView videos on a super-low latency page.";
$LANGS['tryitout'] = "Try it out";
$LANGS['disabletest'] = "Disable";
$LANGS['timemachine'] = "Time Machine";
$LANGS['timemachinedesc'] = "Go back in time, rewinding every date on BitView to the late 2000's.";
$LANGS['lightsout'] = "Lights Out";
$LANGS['lightsoutdesc'] = "Tired of seeing the brightest of whites on your screen? Paint it, black and try out a new cool interface.";
$LANGS['featherenabled'] = '"Feather" is now enabled!';
$LANGS['timemachineenabled'] = '"Time Machine" is now enabled!';
$LANGS['lightsoutenabled'] = '"Lights Out" is now enabled!';
$LANGS['featherdisabled'] = '"Feather" is now disabled!';
$LANGS['timemachinedisabled'] = '"Time Machine" is now disabled!';
$LANGS['lightsoutdisabled'] = '"Lights Out" is now disabled!';

/* Email Confirmation */
$LANGS['checkemail'] = "Please Check Your Email";
$LANGS['checkemaildesc'] = "A confirmation email has been sent to your email address. Please click on the link in the email to verify your email address. If you do not recieve the message within a few minutes, please also check your bulk or spam folders.";
$LANGS['resendemail'] = "Resend Confirmation Email";

/* Footer */
$LANGS['youraccount'] = 'Sua conta';
$LANGS['inbox'] = 'Caixa de entrada';
$LANGS['footmore'] = 'mais...';
$LANGS['helpinfo'] = 'Ajuda';
$LANGS['helpcenter'] = 'Obtenha ajuda';
$LANGS['ourtwitter'] = 'Twitter';
$LANGS['ourdiscord'] = 'Discord';
$LANGS['guidelines'] = 'Diretrizes da comunidade';
$LANGS['partnerships'] = 'Partners';
$LANGS['terms'] = 'Termos';
$LANGS['about'] = 'Sobre';
$LANGS['privacypolicy'] = 'Privacidade';
$LANGS['languageselector'] = 'Idioma';
$LANGS['currentlanguage'] = 'Idioma atual';
$LANGS['showlanguages'] = 'Mostrar idiomas';
$LANGS['setlanguagepref'] = 'Set Your Language Preference';
$LANGS['programs'] = 'Programas';
$LANGS['developers'] = 'Desenvolvedores';
$LANGS['bitviewblog'] = 'Blog do BitView';
$LANGS['policy'] = 'Política de Privacidade';
$LANGS['discover'] = 'Descobrir';
$LANGS['bvphone'] = 'BitView no seu celular';
$LANGS['bvsite'] = 'BitView no seu site';
$LANGS['bvrss'] = 'Feeds RSS do BitView';
$LANGS['mobile'] = 'Mobile';
?>
