<?php

/* General stuff z */
$LANGS['language'] = '中文';
$LANGS['languageenglish'] = 'Chinese';
$LANGS['languagecode'] = 'zh_CN.UTF-8'; /* Leave the ".UTF-8" in the end as-is, as it might break some dates */
$LANGS['languagechange'] = '已成功设置成中文';
$LANGS['numberformat'] = 1; /* If your language uses comma separators (example: 1,000,000), value will be 1. If it uses dots (example: 1.000.000) or doesn't use separators, value will be 0.*/

/* Language window */
$LANGS['welcometobitview'] = '欢迎来到BitView!';
$LANGS['languagesuggestion'] = 'Suggested Language (we have set your preference to this):';
$LANGS['languagesuggestiondesc1'] = '如要更换语言，请点击“语言”（位于网站下方）';
$LANGS['languagesuggestiondesc2'] = '点击 "OK" 以同意此设定，或点击 "取消" 以继续使用英文。';

/* Time, dates, etc */
$LANGS['second'] = '秒';
$LANGS['minute'] = '分钟';
$LANGS['hour'] = '小时';
$LANGS['day'] = '天';
$LANGS['week'] = '周';
$LANGS['month'] = '个月';
$LANGS['year'] = '年';
$LANGS['seconds'] = '秒';
$LANGS['minutes'] = '分钟';
$LANGS['hours'] = '小时';
$LANGS['days'] = '天';
$LANGS['weeks'] = '周';
$LANGS['months'] = '个月';
$LANGS['years'] = '年';
$LANGS['ago1'] = ''; /* Explanation: Text before "x seconds/minutes/hours..." Example: "hace (1 día)" in Spanish. If your language doesn't use this, leave it empty like this: ''*/
$LANGS['ago2'] = '前'; /* Explanation: ago2 -> Text after "x seconds/minutes/hours..." Example: "(1 day) ago" in English, "(1 anno) fa" in Italian. If your language doesn't use this, leave it empty like this: ''*/
$LANGS['january'] = '1月';
$LANGS['february'] = '2月';
$LANGS['march'] = '3月';
$LANGS['april'] = '4月';
$LANGS['may'] = '5月';
$LANGS['june'] = '6月';
$LANGS['july'] = '7月';
$LANGS['august'] = '8月';
$LANGS['september'] = '9月';
$LANGS['october'] = '10月';
$LANGS['november'] = '11月';
$LANGS['december'] = '12月';
$LANGS['shorttimeformat'] = '%b %e, %Y';
$LANGS['videotimeformat'] = '%b %e, %Y';
$LANGS['longtimeformat'] = '%B %e, %Y';
$LANGS['timehourformat'] = '%b %e, %Y %I:%M %p';
$LANGS['myvideostimeformat'] = '%A, %b %e %Y, %I:%M:%S %p';
$LANGS['blogpostformat'] = '%A, %B %e, %Y';
$LANGS['timenumberformat'] = 'm.d.Y';

/* Header */
$LANGS['home'] = '主页';
$LANGS['videos'] = '视频';
$LANGS['channels'] = '频道';
$LANGS['community'] = '社区';
$LANGS['search'] = '搜索';
$LANGS['login'] = '登入';
$LANGS['or'] = '或';
$LANGS['signup'] = '创建新账号';
$LANGS['logout'] = '退出';
$LANGS['upload'] = '上传';
$LANGS['subscriptions'] = '订阅的频道';
$LANGS['history'] = '历史记录';
$LANGS['account'] = '账号';
$LANGS['myvideos'] = '上传的视频';
$LANGS['favorites'] = '喜爱的视频';
$LANGS['playlists'] = '播放列表';
$LANGS['help'] = '帮助';
$LANGS['suggestions'] = 'Suggestions';
$LANGS['quicklist'] = 'QuickList';

/* Homepage */
$LANGS['viewall'] = '展开';
$LANGS['videoviews'] = '次观看';
$LANGS['beingwatched'] = '最近观看的视频';
$LANGS['featured'] = '精选视频';
$LANGS['recommendedforyou'] = 'Recommended for You';
$LANGS['mostpopular'] = '时下最流行';
$LANGS['inboxstats'] = '通知与个人信息';
$LANGS['profilesettings'] = '账号设置';
$LANGS['messages'] = '信息';
$LANGS['message'] = '信息';
$LANGS['comments'] = '留言';
$LANGS['comment'] = '留言';
$LANGS['friendinvites'] = '好友邀请';
$LANGS['friendinvite'] = '好友邀请';
$LANGS['subscribers'] = '订阅者';
$LANGS['subscriber'] = '订阅者';
$LANGS['totalviews'] = '次播放';
$LANGS['sendmessage'] = '发送信息';
$LANGS['whatsnew'] = "公告";
$LANGS['readmore'] = '详细请见Blog';
$LANGS['videocontest'] = '视频创作大赛';
$LANGS['joincontest'] = '立即加入大赛吧！';
$LANGS['personalize'] = '想要加入这个天地吗？';
$LANGS['signinnow'] = '立即<a href="/login">登入</a> 或 <a href="/signup">注册</a> 吧！';
$LANGS['nowconverting'] = "这个视频正在解析中，请耐心等待。";
$LANGS['modules'] = "Add / Remove Modules";
$LANGS['friendactivity'] = "Friend Activity";
$LANGS['customizehomepage'] = "Customize Homepage";
$LANGS['customizethehomepage'] = "Customize the Homepage";
$LANGS['customizehomepagedesc'] = "Select the modules you want to see on your customized homepage.";
$LANGS['displaypreferences'] = "Display Preferences";
$LANGS['thefeed'] = "The Feed";
$LANGS['thefeeddesc'] = "Combine all of your modules into a single feed.";
$LANGS['friendactivitytitle'] = "Friend Activity - Can people see what I do?";
$LANGS['friendactivitydesc'] = "This section shows your confirmed friends the actions that you're publicly broacasting in your recent activity history. For example, if you favorite a video, then your new favorite video might show up in your channel's Recent Activity box, as well as on your friends' homepages.";
$LANGS['feedfeatured'] = "Featured Video";
$LANGS['feedbeingwatched'] = "Video Being Watched Now";
$LANGS['feedrecommended'] = "Recommended Video";
$LANGS['nosubscriptions'] = "You haven't subscribed to any channel yet.";
$LANGS['nosubscriptionsdesc'] = "When you add new subscriptions, we'll show their uploads here on this page.";
$LANGS['nofriendactivity'] = "Your friends haven't been active lately.";
$LANGS['nofriendactivitydesc'] = "You can try adding some friends. Then, we'll show their activity here on this page.";
$LANGS['homeediting'] = "Editing";
$LANGS['homedisplay'] = "Display as";
$LANGS['homerows'] = "Number of rows to display";
$LANGS['gridview'] = "Grid View";
$LANGS['listview'] = "List View";

/* Page title */
$LANGS['homepretitle'] = ""; /* Explanation: Use if "BitView" goes before the username. Example: "BitView de username" in Spanish. If your language doesn't use this, leave it empty like this: ''*/
$LANGS['homeposttitle'] = "的BitView"; /* Explanation: Use if "BitView" goes after the username. Example: "username's BitView" in English. If your language doesn't use this, leave it empty like this: '' */
$LANGS['chpretitle'] = ""; /* Explanation: Use if "channel" goes before the username. Example: "Canal de username" in Spanish. If your language doesn't use this, leave it empty like this: ''*/
$LANGS['chposttitle'] = "的频道"; /* Explanation: Use if "channel" goes after the username. Example: "username's Channel" in English. If your language doesn't use this, leave it empty like this: '' */
$LANGS['signintitle'] = "Sign In";
$LANGS['historytitle'] = "历史记录";
$LANGS['favtitle'] = "Favorites";
$LANGS['pltitle'] = "Playlists";
$LANGS['partnerprogram'] = "Partner Program";

/* Notifications */
$LANGS['searcherror'] = '你的搜索至少要达到2个字以上！';
$LANGS['addvideoplaylist1'] = "You've added";
$LANGS['addvideoplaylist2'] = 'videos to your playlist!';
$LANGS['addfavorite1'] = "You favorited";
$LANGS['addfavorite2'] = 'videos!';
$LANGS['groupdoesnotexist'] = "此小组不存在！";
$LANGS['uploaddisabled'] = 'Uploading has been disabled for maintenance.';
$LANGS['10vidsday'] = '一天不得上传超过10个视频！请等到下一天才可上传。';
$LANGS['3mins'] = '3分钟后，您才可上传新视频！';
$LANGS['backgroundsuccess'] = '背景已成功上传！';
$LANGS['backgrounderror'] = '背景必须低于2MB，并且只能使用照片！';
$LANGS['backgrounddeleted'] = '背景已成功移除！';
$LANGS['bannersuccess'] = '横幅已成功上传！';
$LANGS['bannererror'] = '横幅必须低于2MB，并且只能使用照片！';
$LANGS['bannerdeleted'] = '横幅已成功移除！';
$LANGS['minibannersuccess'] = '小横幅已成功上传！';
$LANGS['minibannererror'] = '小横幅必须低于2MB，并且只能使用照片！';
$LANGS['minibannerdeleted'] = '小横幅已成功移除！';
$LANGS['sideimagesuccess'] = 'Side image has been successfully uploaded!';
$LANGS['sideimageerror'] = 'Side image must be under 2MB and be an image file!';
$LANGS['sideimagedeleted'] = 'Side image has been successfully deleted!';
$LANGS['avatarsuccess'] = '个人头像已成功上传！Avatar has been successfully uploaded!';
$LANGS['avatarerror'] = '个人头像必须低于1MB，并且只能使用照片！';
$LANGS['avatardeleted'] = '"个人头像已成功移除！';
$LANGS['changessaved'] = '已成功更改！';
$LANGS['profilesdisabled'] = 'Profiles have been disabled for maintenance.';
$LANGS['bulletinposted'] = 'Bulletin has been posted!';
$LANGS['channelcommentsent'] = 'Channel comment has been submitted!';
$LANGS['somethingwentwrong'] = '发生错误！';
$LANGS['replysubmitted'] = 'Reply has been submitted!';
$LANGS['onlyonecomment'] = '您只能发布一个评论！';
$LANGS['vpnbrowser'] = "您不能使用VPN注册BitView账号！";
$LANGS['torbrowser'] = "您不能使用TOR浏览器注册BitView账号！";
$LANGS['captchaincorrect'] = "You didn't type in the code correctly.";
$LANGS['toomanyaccounts'] = '您所拥有的账号太多！';
$LANGS['banned2times'] = "由于您被封禁的次数已达到2次，您已不能再注册新账号！";
$LANGS['nohistory'] = "您目前无任何最近看过的视频！";
$LANGS['historycleared'] = '您的历史记录已成功清除！';
$LANGS['watchdisabled'] = '由于网站仍在维护当中，您暂时无法观看视频。';
$LANGS['videonotexist'] = '此视频不存在或由于此视频违反了我们的使用条款导致其被删除。';
$LANGS['responseerror'] = 'Something went wrong with your video response! Please check URL again.';
$LANGS['responseexist'] = 'Video has been already requested!';
$LANGS['responseadded'] = '视频回复已成功添加！';
$LANGS['responseaccepted'] = 'Accepted new Video Response!';
$LANGS['60secscomment'] = '请等待1分钟后才可发布新评论！';
$LANGS['plnotexist'] = "此播放列表不存在！";
$LANGS['positionnotexist'] = "This position doesn't exist!";
$LANGS['positionchanged'] = "Video's position changed!";
$LANGS['invalidurl'] = '此URL无效！';
$LANGS['videopladded'] = '视频已成功添加！';
$LANGS['videoalreadyinpl'] = '此视频已添加到此播放列表中！';
$LANGS['plvideoremoved'] = '视频已成功移除！';
$LANGS['plinfochanged'] = 'Playlist information got successfully changed!';
$LANGS['pltitleneeded'] = '您必须为播放列表添加名称！';
$LANGS['flashenabled'] = 'Adobe Flash Player enabled!';
$LANGS['flashdisabled'] = 'Adobe Flash Player disabled!';
$LANGS['messagesent'] = '信息已成功发送！';
$LANGS['usernotexist'] = "此用户不存在！";
$LANGS['nocriteria'] = "您的频道仍未达到要求的标准！";
$LANGS['alreadypartner'] = '您已成功被批准加入到合作伙伴计划中！';
$LANGS['alreadyapplied'] = '您已加入到计划中！';
$LANGS['applicationsent'] = 'Your application has been submitted!';
$LANGS['joinedgroup'] = '您已成功加入群组！';
$LANGS['leftgroup'] = '您已成功退出群组！';
$LANGS['grouprequest'] = '您已成功发送群组加入邀请，现在您只需要等待结果就可以啦！';
$LANGS['groupdeleted'] = '群组已成功删除！';
$LANGS['groupvideoadded'] = 'Video has been submitted!';
$LANGS['groupvideoalreadyadded'] = 'You already submitted this video!';
$LANGS['groupvideonotowned'] = "You don't own this video!";
$LANGS['3groups'] = '您不能拥有超过3个群组！';
$LANGS['groupnameempty'] = '群主名称不能为空白！';
$LANGS['groupdescempty'] = '群组介绍不能为空白！';
$LANGS['groupnoimage'] = '您必须为群组添加图片！';
$LANGS['groupimageerror'] = '群组图片不能超过1MB，并且只能使用图片文件！';
$LANGS['groupcreated'] = '群组已成功创建！';
$LANGS['urlnotvalid'] = "This isn't a valid video URL!";
$LANGS['discussiondeleted'] = '话题已成功删除！';
$LANGS['videodeleted'] = '视频已成功删除！';
$LANGS['pldeleted'] = '播放列表已成功删除！';
$LANGS['invitesent'] = '好友邀请已成功发送！';
$LANGS['descriptionchanged'] = '资讯栏已成功更改！';
$LANGS['emptymessage'] = '您不能发送空白信息！';
$LANGS['styleupdated'] = 'Group styling has been successfully updated!';
$LANGS['imageupdated'] = 'Group image has been successfully updated!';
$LANGS['plcreated'] = 'Playlist has been successfully created!';
$LANGS['discussiontitle2chars'] = ' must be over 2 characters!';
$LANGS['discussiondesc10chars'] = '话题资讯栏必须超过10个字符！';
$LANGS['5discussionsday'] = '您只能在一天内发起5次讨论！';
$LANGS['discussionsuccess'] = '讨论已成功发布！';
$LANGS['memberaccepted1'] = '';
$LANGS['memberaccepted2'] = 'was successfully accepted!';
$LANGS['memberdeclined1'] = '';
$LANGS['memberdeclined2'] = 'was successfully declined!';
$LANGS['videoaccepted'] = 'The video was successfully accepted!';
$LANGS['bulletindeleted'] = 'Bulletin successfully deleted!';
$LANGS['messagedeleted'] = 'Message successfully deleted!';
$LANGS['responsedeleted'] = 'Successfully deleted Video Response!';
$LANGS['flagmod'] = 'You cannot report user that have moderator permissions!';
$LANGS['userflagged'] = 'Report has been submitted!';
$LANGS['discussionreplysubmitted'] = 'Reply has been successfully sent!';
$LANGS['discussionreplyempty'] = 'A reply cannot be left empty!';

/* Watch */
$LANGS['moreinfo'] = '展开';
$LANGS['lessinfo'] = '关闭';
$LANGS['category'] = '类型';
$LANGS['recordedon'] = '拍摄于';
$LANGS['location'] = '位置';
$LANGS['tags'] = '标签';
$LANGS['embed'] = '嵌入';
$LANGS['partnervideo'] = '合作伙伴视频';
$LANGS['subscribe'] = '订阅';
$LANGS['unsubscribe'] = '退订';
$LANGS['nodesc'] = '无任何内容...';
$LANGS['logintosub'] = '请登入后才可订阅！';
$LANGS['logintosubbox'] = '订阅此频道？';
$LANGS['subyourself'] = '您无法订阅自己！';
$LANGS['videoowner'] = '查看';
$LANGS['editvideo'] = '编辑视频信息';
$LANGS['insight'] = '视频数据';
$LANGS['morefrom'] = '更多其他视频:';
$LANGS['relatedvideos'] = '相关视频';
$LANGS['novideosfound'] = '无任何视频...';
$LANGS['morevideos'] = '展示全部视频';
$LANGS['changeplayersize'] = '改变播放器大小';
$LANGS['newwindow'] = '在新窗口观看此视频';
$LANGS['featuredtext'] = '恭喜，您的视频被添加至精选视频中！想查看更多精选视频吗？请 <a href="/browse?t=2">点击这里</a>。';
$LANGS['ratings'] = '个评分';
$LANGS['rating'] = '个评分';
$LANGS['favorite'] = '喜爱';
$LANGS['addtofav'] = '添加至喜爱中';
$LANGS['removefav'] = '从喜爱中移除';
$LANGS['favadded'] = '此视频已 <strong>添加</strong> 至您 <a href="/my_favorites">喜爱的视频</a> 中！';
$LANGS['favremoved'] = '此视频已从您  <a href="/my_favorites">喜爱的视频</a> 中 <strong>移除</strong> ！';
$LANGS['undo'] = '撤销';
$LANGS['thanksforrating'] = '感谢评分！';
$LANGS['playlistdesc'] = '如要添加视频至播放列表中，请点击 <a href="/my_playlists">"我的播放列表"</a> 。';
$LANGS['addtoplaylist'] = '添加至播放列表中';
$LANGS['addtoplaylistsuccess'] = '此视频已添加到播放列表中。';
$LANGS['share'] = '分享';
$LANGS['flag'] = '举报';
$LANGS['flagthisvid'] = '举报此视频';
$LANGS['removeflag'] = '撤销举报';
$LANGS['flagnote'] = "注意！请确认此视频是因为违反了我们的规则，而不是您纯粹只是不喜欢此视频而举报。";
$LANGS['statadded'] = '上传于';
$LANGS['statviews'] = '播放次数';
$LANGS['statratings'] = '评分';
$LANGS['statresponses'] = '回复';
$LANGS['statcomments'] = '评论';
$LANGS['statfavorited'] = '收藏次数';
$LANGS['statsdata'] = '视频数据';
$LANGS['honors'] = '视频排名';
$LANGS['mostviewed'] = '最多观看';
$LANGS['topfavorited'] = '最多人喜爱';
$LANGS['times'] = '次';
$LANGS['mostdiscussed'] = '最多评论';
$LANGS['toprated'] = '最多评分';
$LANGS['videolinks'] = '从各个平台进入的次数';
$LANGS['clicksfrom'] = '来自';
$LANGS['responses'] = '视频回复';
$LANGS['responsespost'] = '回复';
$LANGS['textcomments'] = '评论';
$LANGS['commentpost'] = '留言';
$LANGS['commentonthisvideo'] = '请试着写些什么吧～如果没有请保持友善哦～';
$LANGS['postcomment'] = '发布评论';
$LANGS['remainingcounter'] = '剩余字符数';
$LANGS['nocomments'] = '此视频 <b>无任何留言</b>。';
$LANGS['noresponses'] = '此视频 <b>无任何回复</b>。';
$LANGS['commviewall'] = '展示所有评论';
$LANGS['delete'] = '删除';
$LANGS['reply'] = '回复';
$LANGS['commentlogin'] = '您是否要在视频下方评论？';
$LANGS['commentlogindesc'] = '<a href="/signup">加入BitView</a> 或 <a href="/login">登入</a> 吧！';
$LANGS['logintoresponse'] = '登入发布视频回复';
$LANGS['logintocomment'] = '登入发布评论';
$LANGS['logintofav'] = '想要添加至喜爱的视频中？ 立即 <a href="/login">登入</a> 或 <a href="/signup">注册</a> 吧！';
$LANGS['logintopl'] = '想要添加至播放列表中？ 立即 <a href="/login">登入</a> 或 <a href="/signup">注册</a> 吧！';
$LANGS['logintoflag'] = '想要举报此视频？ 立即 <a href="/login">登入</a> 或 <a href="/signup">注册</a> 吧！';
$LANGS['close'] = '关闭';
$LANGS['addresponse'] = 'Add Response';
$LANGS['recentlyrated'] = '最近评价的用户';
$LANGS['commentsdisabled'] = '此视频禁止用户发布评论。';
$LANGS['ratingsdisabled'] = 'Ratings disabled';
$LANGS['rating1'] = 'Poor';
$LANGS['rating2'] = 'Nothing special';
$LANGS['rating3'] = 'Worth watching';
$LANGS['rating4'] = 'Pretty cool';
$LANGS['rating5'] = 'Awesome!';
$LANGS['saving'] = 'Saving...';
$LANGS['signintorate'] = '<a href="/login">Sign in</a> to rate';
$LANGS['addingcomment'] = "Adding comment...";
$LANGS['commentposted'] = "Comment Posted!";
$LANGS['commentspammsg'] = "Posting the same comment again is considered spam. Try again later.";
$LANGS['commentspammsg2'] = "Posting more than 5 comments consecutively is considered spam. Try again later.";
$LANGS['emptycomment'] = "Your comment can't be empty.";
$LANGS['spambutton'] = "Spam";
$LANGS['notspambutton'] = "Not Spam";
$LANGS['commentsspam'] = "Comment(s) marked as spam";
$LANGS['marked'] = "Marked as spam";
$LANGS['spamshow'] = "Show";
$LANGS['spamhide'] = "Hide";
$LANGS['poorcomment'] = "Poor comment";
$LANGS['goodcomment'] = "Good comment";
$LANGS['pleasesignin'] = "Please sign in";
$LANGS['showmorecomments'] = "Show More Comments";
$LANGS['showingamount'] = "<strong>Showing {number}</strong> of {total} comments";
$LANGS['customize'] = "Customize";
$LANGS['customizedesc'] = "After making your selection, copy and paste the embed code above. The code changes based on your selection.";

/* Watch comments */
$LANGS['allcomments'] = 'All Comments';

/* Sign In */
$LANGS['username'] = "用户名";
$LANGS['password'] = "密码";
$LANGS['logindesc'] = "登入您的BitView账号";
$LANGS['forgot'] = "无法访问您的账号？";
$LANGS['forgotmsg'] = '请在推特（@BitView_）联系我们或在Discord（链接在下方）向版主报告。';
$LANGS['noaccount'] = "没有帐号？";
$LANGS['signuptobv'] = "创建新账号吧！";
$LANGS['signintobv'] = "立即登入吧！";
$LANGS['signindesc1'] = "加入全世界最大的视频分享网站吧！";
$LANGS['signindesc2'] = "BitView是一种将您的视频分享给他人的其中一方式。使用BitView，您可以：";
$LANGS['signindesc3'] = "向全世界展示您喜爱的视频";
$LANGS['signindesc4'] = "将向全世界分享您通过相机或手机所拍摄的视频";
$LANGS['signindesc5'] = "安全并私密地向您来自世界各地的朋友和家人展示视频";
$LANGS['notallowed'] = "您的账号已被封禁，已无法登入！";
$LANGS['wrongpassword'] = '密码错误，请重试！';
$LANGS['staysigned'] = "保持登入状态";

/* Sign Up */
$LANGS['email'] = "邮箱";
$LANGS['passwordstrength'] = "密码强度";
$LANGS['psnone'] = "无";
$LANGS['psweak'] = "弱";
$LANGS['psfair'] = "不弱";
$LANGS['psgood'] = "中等";
$LANGS['psstrong'] = "强";
$LANGS['repassword'] = "重添密码";
$LANGS['usernamedesc'] = "您的用户名只能包括A-和数字0-9。";
$LANGS['captcha'] = "验证";
$LANGS['acceptterms'] = '我同意 <a href="/terms">使用条款</a> 和 <a href="/privacy">用户隐私政策</a>。';
$LANGS['copyrighttext'] = 'Uploading materials that you do not own is a copyright violation and against the law. If you upload material you do not own, your account will be deleted.';
$LANGS['mustaccept'] = 'You must accept the Terms of Use and Privacy Policy to create your account';
$LANGS['createaccount'] = '创建账号';
$LANGS['signuperror'] = '抱歉，在创建账号期间发生了错误。';
$LANGS['sameemail'] = '这个用户名或邮箱已经被抢先！';
$LANGS['usernamechar'] = '用户名只能包括字母和数字而已！';
$LANGS['required'] = '所有空格必须被填满！';
$LANGS['notmatch'] = "密码并不正确！";
$LANGS['signuphead'] = 'Get started with your account';

/* Videos Page */
$LANGS['recentvideos'] = '最近上传的视频';
$LANGS['random'] = '推荐视频';
$LANGS['dropdownmore'] = 'more';
$LANGS['allcatin'] = '展示';
$LANGS['allcat'] = '所有类型';
$LANGS['categories'] = '类型';
$LANGS['nomorevideos'] = '没有更多视频了...';
$LANGS['timetoday'] = '今天';
$LANGS['timeweek'] = '这周';
$LANGS['timemonth'] = '这个月';
$LANGS['alltime'] = '全部';
$LANGS['when'] = 'When';
$LANGS['videofavorites'] = 'favorites';
$LANGS['videocomments'] = 'comments';
$LANGS['trendingtopics'] = 'Trending Topics';

/* Channels Page */
$LANGS['mostsubscribed'] = '最多订阅者';
$LANGS['lastlogin'] = '上次登入于';
$LANGS['cstatviews'] = '总观看';
$LANGS['cstatvideos'] = '视频';
$LANGS['cstatsubs'] = '订阅数';
$LANGS['nochannels'] = 'No more channels were found...';

/* Video Categories */
$LANGS['cat1'] = "影视与动画";
$LANGS['cat2'] = "汽车";
$LANGS['cat3'] = "教育与教学";
$LANGS['cat4'] = "娱乐";
$LANGS['cat5'] = "节日";
$LANGS['cat6'] = "家庭";
$LANGS['cat7'] = "拍卖";
$LANGS['cat8'] = "喜好";
$LANGS['cat9'] = "喜剧";
$LANGS['cat10'] = "音乐";
$LANGS['cat11'] = "时事与政治";
$LANGS['cat12'] = "奇特";
$LANGS['cat13'] = "人文与记录";
$LANGS['cat14'] = "个人";
$LANGS['cat15'] = "动物";
$LANGS['cat16'] = "科学与科技";
$LANGS['cat17'] = "短片";
$LANGS['cat18'] = "体育";
$LANGS['cat19'] = "旅游";
$LANGS['cat20'] = "游戏";
$LANGS['cat21'] = "日常记录";

/* Channel Types */
$LANGS['type0'] = "无";
$LANGS['type1'] = "成员";
$LANGS['type1p'] = "成员";
$LANGS['type2'] = "喜剧家";
$LANGS['type2p'] = "喜剧家";
$LANGS['type3'] = "指导员";
$LANGS['type3p'] = "指导员";
$LANGS['type4'] = "大师";
$LANGS['type4p'] = "大师";
$LANGS['type5'] = "音乐家";
$LANGS['type5p'] = "音乐家";
$LANGS['type6'] = "记者";
$LANGS['type6p'] = "记者";

/* Countries */
$LANGS['cat_AF'] = "阿富汗";
$LANGS['cat_AX'] = "奥兰群岛";
$LANGS['cat_AL'] = "阿尔巴尼亚";
$LANGS['cat_DZ'] = "阿尔及利亚";
$LANGS['cat_AS'] = "美属萨摩亚";
$LANGS['cat_AD'] = "安道拉";
$LANGS['cat_AO'] = "安哥拉";
$LANGS['cat_AI'] = "安圭拉";
$LANGS['cat_AQ'] = "南极洲";
$LANGS['cat_AG'] = "安提圭和巴布达";
$LANGS['cat_AR'] = "阿根廷";
$LANGS['cat_AM'] = "亚美尼亚";
$LANGS['cat_AW'] = "阿鲁巴";
$LANGS['cat_AU'] = "澳大利亚";
$LANGS['cat_AT'] = "奥地利";
$LANGS['cat_AZ'] = "阿塞拜疆";
$LANGS['cat_BS'] = "巴哈马";
$LANGS['cat_BH'] = "巴林";
$LANGS['cat_BD'] = "孟加拉";
$LANGS['cat_BB'] = "巴巴多斯";
$LANGS['cat_BY'] = "白俄罗斯";
$LANGS['cat_BE'] = "比利时";
$LANGS['cat_BZ'] = "伯利兹";
$LANGS['cat_BJ'] = "贝宁";
$LANGS['cat_BM'] = "百慕大";
$LANGS['cat_BT'] = "不丹";
$LANGS['cat_BO'] = "玻利维亚";
$LANGS['cat_BQ'] = "荷兰加勒比区";
$LANGS['cat_BA'] = "波斯尼亚和黑塞哥维那";
$LANGS['cat_BW'] = "博茨瓦纳";
$LANGS['cat_BV'] = "布韦岛";
$LANGS['cat_BR'] = "巴西";
$LANGS['cat_IO'] = "英属印度洋领地";
$LANGS['cat_BN'] = "文莱";
$LANGS['cat_BG'] = "保加利亚";
$LANGS['cat_BF'] = "布基纳法索";
$LANGS['cat_BI'] = "布隆迪";
$LANGS['cat_KH'] = "柬埔寨";
$LANGS['cat_CM'] = "喀麦隆";
$LANGS['cat_CA'] = "加拿大";
$LANGS['cat_CV'] = "佛得角";
$LANGS['cat_KY'] = "开曼群岛";
$LANGS['cat_CF'] = "中非共和国";
$LANGS['cat_TD'] = "乍得";
$LANGS['cat_CL'] = "智利";
$LANGS['cat_CN'] = "中华人民共和国";
$LANGS['cat_CX'] = "圣诞岛";
$LANGS['cat_CC'] = "科科斯（基林）群岛";
$LANGS['cat_CO'] = "哥伦比亚";
$LANGS['cat_KM'] = "科摩罗";
$LANGS['cat_CG'] = "刚果共和国";
$LANGS['cat_CD'] = "刚果人民共和国";
$LANGS['cat_CK'] = "库克群岛";
$LANGS['cat_CR'] = "哥斯达黎加";
$LANGS['cat_CI'] = "科特迪瓦";
$LANGS['cat_HR'] = "克罗地亚";
$LANGS['cat_CU'] = "古巴";
$LANGS['cat_CW'] = "库拉索";
$LANGS['cat_CY'] = "塞浦路斯";
$LANGS['cat_CZ'] = "捷克";
$LANGS['cat_DK'] = "丹麦";
$LANGS['cat_DJ'] = "吉布提";
$LANGS['cat_DM'] = "多米尼克";
$LANGS['cat_DO'] = "多米尼加共和国";
$LANGS['cat_EC'] = "厄瓜多";
$LANGS['cat_EG'] = "埃及";
$LANGS['cat_SV'] = "萨尔瓦多";
$LANGS['cat_GQ'] = "赤道几内亚";
$LANGS['cat_ER'] = "厄立特里亚";
$LANGS['cat_EE'] = "爱沙尼亚";
$LANGS['cat_ET'] = "埃塞俄比亚";
$LANGS['cat_FK'] = "福克兰（马尔维纳斯）群岛";
$LANGS['cat_FO'] = "法罗群岛";
$LANGS['cat_FJ'] = "斐济";
$LANGS['cat_FI'] = "芬兰";
$LANGS['cat_FR'] = "法国";
$LANGS['cat_GF'] = "法属圭亚那";
$LANGS['cat_FG'] = "法属圭亚那";
$LANGS['cat_PF'] = "法属波利尼西亚";
$LANGS['cat_TF'] = "法国南部属地";
$LANGS['cat_GA'] = "加蓬";
$LANGS['cat_GM'] = "冈比亚";
$LANGS['cat_GE'] = "乔治亚";
$LANGS['cat_DE'] = "德国";
$LANGS['cat_GH'] = "加纳";
$LANGS['cat_GI'] = "直布罗陀";
$LANGS['cat_GR'] = "希腊";
$LANGS['cat_GL'] = "格陵兰岛";
$LANGS['cat_GD'] = "格拉纳达";
$LANGS['cat_GP'] = "瓜德路普";
$LANGS['cat_GU'] = "关岛";
$LANGS['cat_GT'] = "危地马拉";
$LANGS['cat_GG'] = "根西岛";
$LANGS['cat_GN'] = "几内亚";
$LANGS['cat_GW'] = "几内亚比绍";
$LANGS['cat_GY'] = "圭亚那";
$LANGS['cat_HT'] = "海地";
$LANGS['cat_HM'] = "赫德岛和麦克唐纳群岛";
$LANGS['cat_VA'] = "梵蒂冈";
$LANGS['cat_HN'] = "洪都拉斯";
$LANGS['cat_HK'] = "香港地区";
$LANGS['cat_HU'] = "匈牙利";
$LANGS['cat_IS'] = "冰岛";
$LANGS['cat_IN'] = "印度";
$LANGS['cat_ID'] = "印度尼西亚";
$LANGS['cat_IR'] = "伊朗";
$LANGS['cat_IQ'] = "伊拉克";
$LANGS['cat_IE'] = "爱尔兰";
$LANGS['cat_IM'] = "曼岛";
$LANGS['cat_IL'] = "以色列";
$LANGS['cat_IT'] = "意大利";
$LANGS['cat_JM'] = "牙买加";
$LANGS['cat_JP'] = "日本";
$LANGS['cat_JE'] = "泽西岛";
$LANGS['cat_JO'] = "约旦";
$LANGS['cat_KZ'] = "哈萨克斯坦";
$LANGS['cat_KE'] = "肯尼亚";
$LANGS['cat_KI'] = "基里巴斯";
$LANGS['cat_XK'] = "科索沃地区";
$LANGS['cat_KP'] = "朝鲜";
$LANGS['cat_KR'] = "韩国";
$LANGS['cat_KW'] = "科威特";
$LANGS['cat_KG'] = "吉尔吉斯斯坦";
$LANGS['cat_LA'] = "老挝";
$LANGS['cat_LV'] = "拉脱维亚";
$LANGS['cat_LB'] = "黎巴嫩";
$LANGS['cat_LS'] = "莱索托";
$LANGS['cat_LR'] = "利比里亚";
$LANGS['cat_LY'] = "利比亚";
$LANGS['cat_LI'] = "列支敦士登";
$LANGS['cat_LT'] = "立陶宛";
$LANGS['cat_LU'] = "卢森堡";
$LANGS['cat_MO'] = "澳门地区";
$LANGS['cat_MK'] = "北马其顿";
$LANGS['cat_MG'] = "马达加斯加";
$LANGS['cat_MW'] = "马拉维";
$LANGS['cat_MY'] = "马来西亚";
$LANGS['cat_MV'] = "马尔代夫";
$LANGS['cat_ML'] = "马里";
$LANGS['cat_MT'] = "马耳他";
$LANGS['cat_MH'] = "马绍尔群岛";
$LANGS['cat_MQ'] = "马提尼克";
$LANGS['cat_MR'] = "毛里塔尼亚";
$LANGS['cat_MU'] = "毛里求斯";
$LANGS['cat_YT'] = "马约特";
$LANGS['cat_MX'] = "墨西哥";
$LANGS['cat_FM'] = "密克罗尼西亚联邦";
$LANGS['cat_MD'] = "摩尔多瓦";
$LANGS['cat_MC'] = "摩纳哥";
$LANGS['cat_MN'] = "蒙古";
$LANGS['cat_ME'] = "黑山";
$LANGS['cat_MS'] = "蒙特塞拉特";
$LANGS['cat_MA'] = "摩洛哥";
$LANGS['cat_MZ'] = "莫桑比克";
$LANGS['cat_MM'] = "缅甸";
$LANGS['cat_NA'] = "纳米比亚";
$LANGS['cat_NR'] = "瑙鲁";
$LANGS['cat_NP'] = "尼泊尔";
$LANGS['cat_NL'] = "荷兰";
$LANGS['cat_AN'] = "荷属安的列斯";
$LANGS['cat_NC'] = "新喀里多尼亚";
$LANGS['cat_NZ'] = "新西兰";
$LANGS['cat_NI'] = "尼加拉瓜";
$LANGS['cat_NE'] = "尼日尔";
$LANGS['cat_NG'] = "尼日利亚";
$LANGS['cat_NU'] = "纽埃";
$LANGS['cat_NF'] = "诺福克岛";
$LANGS['cat_MP'] = "北马里亚纳群岛";
$LANGS['cat_NO'] = "挪威";
$LANGS['cat_OM'] = "阿曼";
$LANGS['cat_PK'] = "巴基斯坦";
$LANGS['cat_PW'] = "帕劳";
$LANGS['cat_PS'] = "巴勒斯坦";
$LANGS['cat_PA'] = "巴拿马";
$LANGS['cat_PG'] = "巴布亚新几内亚";
$LANGS['cat_PY'] = "巴拉圭";
$LANGS['cat_PE'] = "秘鲁";
$LANGS['cat_PH'] = "菲律宾";
$LANGS['cat_PN'] = "皮特凯恩群岛";
$LANGS['cat_PL'] = "波兰";
$LANGS['cat_PT'] = "葡萄牙";
$LANGS['cat_PR'] = "波多黎各";
$LANGS['cat_QA'] = "卡塔尔";
$LANGS['cat_RE'] = "留尼汪岛";
$LANGS['cat_RO'] = "罗马尼亚";
$LANGS['cat_RU'] = "俄罗斯";
$LANGS['cat_RW'] = "卢旺达";
$LANGS['cat_BL'] = "圣巴勒泰米";
$LANGS['cat_SH'] = "圣赫勒纳";
$LANGS['cat_KN'] = "圣基茨和尼维斯";
$LANGS['cat_LC'] = "圣卢西亚";
$LANGS['cat_MF'] = "法属圣马丁";
$LANGS['cat_PM'] = "圣皮埃尔和密克隆";
$LANGS['cat_VC'] = "圣文森和格林那丁";
$LANGS['cat_WS'] = "萨摩亚";
$LANGS['cat_SM'] = "圣马力诺";
$LANGS['cat_ST'] = "圣多美和普林西比";
$LANGS['cat_SA'] = "沙特阿拉伯";
$LANGS['cat_SN'] = "塞内加尔";
$LANGS['cat_RS'] = "塞尔维亚";
$LANGS['cat_SC'] = "塞舌尔";
$LANGS['cat_SL'] = "塞拉利昂";
$LANGS['cat_SG'] = "新加坡";
$LANGS['cat_SX'] = "荷属圣马丁";
$LANGS['cat_SK'] = "斯洛伐克";
$LANGS['cat_SI'] = "斯洛文尼亚";
$LANGS['cat_SB'] = "所罗门群岛";
$LANGS['cat_SO'] = "索马里";
$LANGS['cat_ZA'] = "南非";
$LANGS['cat_GS'] = "南乔治亚和南桑威奇群岛";
$LANGS['cat_ES'] = "西班牙";
$LANGS['cat_LK'] = "斯里兰卡";
$LANGS['cat_SD'] = "苏丹";
$LANGS['cat_SR'] = "苏里南";
$LANGS['cat_SJ'] = "斯瓦尔巴和扬马延";
$LANGS['cat_SZ'] = "斯威士兰";
$LANGS['cat_SE'] = "瑞典";
$LANGS['cat_CH'] = "瑞士";
$LANGS['cat_SS'] = "南苏丹";
$LANGS['cat_SY'] = "叙利亚";
$LANGS['cat_TW'] = "台湾地区";
$LANGS['cat_TJ'] = "塔吉克斯坦";
$LANGS['cat_TZ'] = "坦桑尼亚";
$LANGS['cat_TH'] = "泰国";
$LANGS['cat_TL'] = "东帝汶";
$LANGS['cat_TG'] = "多哥";
$LANGS['cat_TK'] = "托克劳";
$LANGS['cat_TO'] = "汤加";
$LANGS['cat_TT'] = "特立尼达和多巴哥";
$LANGS['cat_TN'] = "突尼斯";
$LANGS['cat_TR'] = "土耳其";
$LANGS['cat_TM'] = "土库曼斯坦";
$LANGS['cat_TC'] = "特克斯和凯科斯群岛";
$LANGS['cat_TV'] = "图瓦卢";
$LANGS['cat_UG'] = "乌干达";
$LANGS['cat_UA'] = "乌克兰";
$LANGS['cat_AE'] = "阿联酋";
$LANGS['cat_GB'] = "英国";
$LANGS['cat_US'] = "美国";
$LANGS['cat_UM'] = "美国本土外小岛屿";
$LANGS['cat_UY'] = "乌拉圭";
$LANGS['cat_UZ'] = "乌兹别克斯坦";
$LANGS['cat_VU'] = "瓦努阿图";
$LANGS['cat_VE'] = "委内瑞拉";
$LANGS['cat_VN'] = "越南";
$LANGS['cat_VG'] = "英属维尔京群岛";
$LANGS['cat_VI'] = "美属维尔京群岛";
$LANGS['cat_WF'] = "瓦利斯和富图纳";
$LANGS['cat_EH'] = "西撒哈拉地区";
$LANGS['cat_YE'] = "也门";
$LANGS['cat_ZM'] = "赞比亚";
$LANGS['cat_ZW'] = "津巴布韦";

/* My Subscriptions */
$LANGS['newvideos'] = "新上传的视频";

/* Account */
$LANGS['myaccount'] = "我的账号";
$LANGS['vidsfavs'] = "视频、喜爱的视频和播放列表";
$LANGS['accountsettings'] = "账号设置";
$LANGS['viewinghistory'] = "历史记录";
$LANGS['mychannel'] = "My Channel";
$LANGS['uploadedvideos'] = "上传的视频";
$LANGS['new'] = "New";
$LANGS['playlist'] = "Playlist";
$LANGS['videoupload'] = "Video Upload";
$LANGS['nosubvideos'] = "You have no subscriptions...";
$LANGS['nofavvideos'] = "You haven't favorited any video...";

/* My Videos */
$LANGS['sortby'] = "排列顺序设置";
$LANGS['sorttitle'] = "标题";
$LANGS['sorttime'] = "时长";
$LANGS['sortdateadded'] = "上传日期";
$LANGS['sortviews'] = "观看";
$LANGS['sortrating'] = "评分";
$LANGS['stattime'] = "时长";
$LANGS['statrating'] = "评分";
$LANGS['statbroadcast'] = "状态";
$LANGS['statrawfile'] = "视频文件";
$LANGS['public'] = "公开";
$LANGS['private'] = "私享";
$LANGS['live'] = "可观看!";
$LANGS['converting'] = "解析中...";
$LANGS['uploading'] = "上传中...";
$LANGS['addvidsto'] = "将视频添加至：";
$LANGS['play'] = "播放";
$LANGS['edit'] = "编辑";
$LANGS['setasavatar'] = "将视频封面设为个人照";
$LANGS['downloadmp4'] = "下载视频";
$LANGS['deleteconfirmation'] = "您是否删除此视频？";
$LANGS['novideos'] = '您目前仍无任何视频。<a href="/my_videos_upload">Start uploading a video now</a>!';
$LANGS['nomyvideosresults'] = "没有任何结果。请检查您的搜索中是否有拼写错误。";

/* Edit Video */
$LANGS['title'] = "Title";
$LANGS['desc'] = "Description";
$LANGS['privacy'] = "Privacy";
$LANGS['saveinfo'] = "Save Info";
$LANGS['saveinfoconfirm'] = "Are you sure you want to change the video information?";
$LANGS['viewchart'] = "View Chart";
$LANGS['videodetails'] = "Video Details";
$LANGS['backtopreviouspage'] = "Back to Previous Page";
$LANGS['editsavechanges'] = "Save Changes";
$LANGS['editcancel'] = "cancel";
$LANGS['videoinfo'] = "Video Information";
$LANGS['videothumbnail'] = "Video Thumbnail";
$LANGS['uploadthumbnail'] = "Upload Thumbnail";
$LANGS['customthumbdesc'] = 'To set a custom thumbnail, click the thumbnail on the left side and select your desired image file. Then, click "Upload Thumbnail".';
$LANGS['customthumbtitle'] = 'Do you want to change this thumbnail?';
$LANGS['customthumbinfo'] = 'Custom thumbnails are exclusive to partners. To read more about the advantages of joining the partner program and its requirements, click the button below.';
$LANGS['partnerreadmore'] = 'Read more';
$LANGS['broadcastingoptions'] = 'Broadcasting and Sharing Options';
$LANGS['publicdesc'] = "anyone can search for and view - recommended";
$LANGS['privatedesc'] = "only specific BitView users can view";
$LANGS['allowcomments'] = "Allow comments automatically";
$LANGS['allowfriendcomments'] = "Only friends can comment";
$LANGS['disablecomments'] = "Don't allow comments";
$LANGS['dateandmap'] = "Date and Map";
$LANGS['clear'] = "Clear";
$LANGS['allowratings'] = "Yes, allow this video to be rated by others.";
$LANGS['dontallowratings'] = "No, don't allow this video to be rated.";

/* My Playlists */
$LANGS['addedpl'] = "Added";
$LANGS['frompl'] = "From";
$LANGS['nopl'] = "No Playlists were found....";

/* My Playlist */
$LANGS['playlistedit'] = "编辑";
$LANGS['videourl'] = "复制视频链接";
$LANGS['add'] = "添加";
$LANGS['editinfo'] = "编辑信息";

/* Edit Playlist */
$LANGS['pledittitle'] = "编辑播放列表";
$LANGS['pleditdesc'] = "播放列表是将您所喜爱或想看的视频整理起来的一种方式。";
$LANGS['cancel'] = "取消";

/* Create Playlist */
$LANGS['createplaylisttitle'] = "创建播放列表";
$LANGS['createplaylist'] = "创建";

/* View Playlist */
$LANGS['plpermalink'] = "Playlist/URL (Permalink):";
$LANGS['sortcomments'] = "Comments";
$LANGS['unsorted'] = "Unsorted";
$LANGS['playallvideos'] = "播放全部视频";

/* Inbox */
$LANGS['compose'] = "发送信息";
$LANGS['from'] = "来自";
$LANGS['subject'] = "内容";
$LANGS['date'] = "日期";
$LANGS['allmsg'] = "所有信息";
$LANGS['msgcom'] = "视频留言";
$LANGS['sentmsg'] = "您发送的信息";
$LANGS['nomsg'] = "您目前无任何信息...";


/* Send Message */
$LANGS['messagecont'] = "内容";
$LANGS['to'] = "发送至";
$LANGS['sendmessagebutton'] = "发送";

/* Groups */
$LANGS['groups'] = "群组";
$LANGS['joinedgroups'] = "已加入的群组";
$LANGS['recentgroups'] = "最近添加的群组";
$LANGS['mostmembers'] = "最多成员";
$LANGS['mostvideos'] = "最多视频";
$LANGS['groupmostdiscussed'] = "最多讨论";
$LANGS['createagroup'] = "创建新群组";
$LANGS['groupvideos'] = "视频";
$LANGS['groupmembers'] = "成员";
$LANGS['discussions'] = "讨论";
$LANGS['groupcreated'] = "创建于";
$LANGS['nogroups'] = "无任何群组...";

/* Group */
$LANGS['jointhisgroup'] = "加入此群组";
$LANGS['removerequest'] = "拒绝邀请";
$LANGS['leavegroup'] = "退出群组";
$LANGS['moderation'] = "设置群组";
$LANGS['viewallvideos'] = "展示全部视频";
$LANGS['addvideo'] = "添加视频";
$LANGS['novideos'] = "无任何视频...";
$LANGS['nodiscussions'] = "无任何讨论...";
$LANGS['creatediscussion'] = "添加讨论";
$LANGS['topostatopic'] = "去跟大家讨论共同话题吧！";
$LANGS['topic'] = "标题";
$LANGS['author'] = "发起者";
$LANGS['replies'] = "评论";
$LANGS['lastpost'] = "最近添加的评论";
$LANGS['viewallmembers'] = "展示全部成员";
$LANGS['owner'] = "管理员";
$LANGS['grouptype'] = "加入设置";
$LANGS['instantjoin'] = "即时加入";
$LANGS['approvalrequired'] = "须经批准";
$LANGS['groupurl'] = "链接";
$LANGS['deletediscussion'] = "删除讨论";
$LANGS['postreply'] = '发布评论';
$LANGS['post'] = "评论";
$LANGS['accept'] = "接受";
$LANGS['decline'] = "拒绝";

/* Group Moderation */
$LANGS['groupmoderation'] = "群主设置";
$LANGS['approvemembers'] = "成员加入";
$LANGS['approvevideos'] = "视频分享";
$LANGS['yes'] = "是";
$LANGS['no'] = "不";
$LANGS['changeinfo'] = "更换";
$LANGS['changeimage'] = "更";
$LANGS['image'] = "群组图片";
$LANGS['styling'] = "风格";
$LANGS['cssdesc'] = "如果群组的背景或主题违反了我们的条约，将导致您的账号遭到终止。";
$LANGS['updatecss'] = "更新";
$LANGS['groupmessage'] = "信息";
$LANGS['sendmessagetomembers'] = "发送至全部成员";
$LANGS['delgroup'] = "删除群组";

/* Submit Group Video */
$LANGS['submitvideotitle'] = "添加视频至小组";
$LANGS['submitvideo'] = "添加视频";

/* Create Group */
$LANGS['groupname'] = "群组名称";
$LANGS['groupimage'] = "群组图片";
$LANGS['creategroup'] = "创建群组";
$LANGS['creategroupdesc'] = "群组允许您与其他用户讨论共同话题并分享您的视频。";

/* Create Group Discussion */
$LANGS['discussiontitle'] = "讨论名称";
$LANGS['creatediscussiondesc'] = "Discussions are parts of groups in which you discuss the set topic.";

/* Search Results */
$LANGS['resultspre'] = ""; /* Explanation: Use if the search query goes before "results". Example: "Resultados para search" in Spanish. If your language doesn't use this, leave it empty like this: ''*/
$LANGS['resultspost'] = "搜索结果"; /* Explanation: Use if "BitView" goes after the username. Example: "search results" in English. If your language doesn't use this, leave it empty like this: '' */
$LANGS['relevance'] = '关于';
$LANGS['viewcount'] = '观看次数';
$LANGS['searchrating'] = '评分';
$LANGS['newest'] = '最近上传';
$LANGS['nochannelsfound'] = '无任何频道...';
$LANGS['noplfound'] = '无任何播放列表...';
$LANGS['nogroupsfound'] = '无任何群组...';
$LANGS['uploaded'] = 'Uploaded';
$LANGS['anytime'] = 'Anytime';
$LANGS['partnervideos'] = 'Partner Videos';
$LANGS['resultcount'] = 'results {r} of about {t}';

/* Profile */
$LANGS['channelsuspended'] = '此账号已被终止。';
$LANGS['accountnotfound'] = '此账号不存在。';
$LANGS['channel'] = '频道';
$LANGS['friends'] = '好友';
$LANGS['channelsubscribers'] = '订阅人数';
$LANGS['linkcomments'] = '评论';
$LANGS['bulletins'] = '公告栏';
$LANGS['editchannel'] = '编辑频道';
$LANGS['type'] = '类型';
$LANGS['joined'] = '注册于';
$LANGS['videoswatched'] = '总看过的视频';
$LANGS['channelviews'] = '频道浏览数';
$LANGS['age'] = '年龄';
$LANGS['gender'] = '性别';
$LANGS['male'] = '男';
$LANGS['female'] = '女';
$LANGS['status'] = '个人状态';
$LANGS['single_m'] = '单身';
$LANGS['single_f'] = '单身';
$LANGS['taken_m'] = '已婚';
$LANGS['taken_f'] = '已婚';
$LANGS['married_m'] = '已婚';
$LANGS['married_f'] = '已婚';
$LANGS['country'] = '国家与地区';
$LANGS['website'] = '相关网站';
$LANGS['hobbies'] = '兴趣和爱好';
$LANGS['music'] = '音乐';
$LANGS['movies'] = '影视';
$LANGS['books'] = '书籍';
$LANGS['mostsub'] = '最多订阅';
$LANGS['report'] = '举报';
$LANGS['pfpviolation'] = '个人照';
$LANGS['connectwith'] = '联系';
$LANGS['profilesendmessage'] = '发送信息';
$LANGS['messagetoyourself'] = '您不能向自己发送信息！';
$LANGS['logintomessage'] = '请登入后才执行此操作！';
$LANGS['addcomment'] = '添加留言';
$LANGS['logintocommentchannel'] = '请登入后才执行此操作！';
$LANGS['sharechannel'] = '分享频道';
$LANGS['addfriend'] = '加为好友';
$LANGS['retractinvite'] = '撤销邀请';
$LANGS['removefriend'] = '删除好友';
$LANGS['notfriendyourself'] = '您无法将自己加为好友！';
$LANGS['logintofriend'] = '请登入后才执行此操作！';
$LANGS['blockuser'] = '封锁用户';
$LANGS['channelembed'] = '嵌入此频道';
$LANGS['recentratings'] = 'Recent Activity';
$LANGS['seeall'] = '展开';
$LANGS['writebulletin'] = '发布公告栏';
$LANGS['bulletin'] = '公告栏';
$LANGS['subvideos1'] = '此频道';
$LANGS['subvideos2'] = "的视频";
$LANGS['plvideos'] = '视频';
$LANGS['playall'] = '播放全部';
$LANGS['featuredchannels'] = '精选频道';
$LANGS['channelcomments'] = '频道留言';
$LANGS['bggraphic'] = '背景';
$LANGS['reportthisuser'] = '此用户';
$LANGS['norecentratings'] = 'No Recent Activity Found...';
$LANGS['nosubscribers'] = '无任何订阅者...';
$LANGS['nosubscriptions'] = '无任何订阅的频道...';
$LANGS['nofriends'] = '无任何好友...';
$LANGS['nobulletins'] = '无任何公告栏...';
$LANGS['novideoschannel'] = '无任何视频...';
$LANGS['nofavs'] = '无任何喜爱的视频...';
$LANGS['noplchannel'] = '无任何播放列表...';
$LANGS['pvideos'] = '私享视频';
$LANGS['pvideosallow'] = '您无法观看这些视频...';
$LANGS['plvideoamount'] = 'videos';
$LANGS['bulletinpost'] = 'Bulletin Post';
$LANGS['deletebulletin'] = '删除';
$LANGS['body'] = '内容';
$LANGS['bulletincomments'] = '评论';
$LANGS['tocommentbulletin'] = 'to post a reply to this bulletin!';
$LANGS['addacomment'] = '添加留言:';
$LANGS['postreplychannel'] = '发布评论';
$LANGS['writecomment'] = '写评论';
$LANGS['for'] = 'for';
$LANGS['commentdesc'] = 'Channel comments appear on the users channel.';
$LANGS['postbulletin'] = '发布';
$LANGS['writeabulletin'] = '编写公告栏';
$LANGS['bulletindesc'] = '公告栏会展示在您和您的好友的频道页面上。';
$LANGS['sharingoptions'] = 'Sharing Options';
$LANGS['sharingoptionsdesc'] = '以下是分享频道的两个办法。';
$LANGS['sharingoptions1'] = '1. 复制并粘贴链接在您的信息或邮件中。';
$LANGS['sharingoptions2'] = "2. 使用电邮发送此频道。";
$LANGS['clicktosend'] = '点击以发送！';
$LANGS['honorless'] = 'less';
$LANGS['activitycomment'] = 'commented on';
$LANGS['activityfavorite'] = 'favorited a video';
$LANGS['activityrating'] = 'rated a video:';
$LANGS['activityupload'] = 'uploaded a new video';
$LANGS['activityfriend'] = 'became friends with';
$LANGS['activitysubscription'] = 'subscribed to';
$LANGS['next'] = "Next";
$LANGS['previous'] = "Previous";
$LANGS['settings'] = "Settings";
$LANGS['themescolors'] = "Themes and Colors";
$LANGS['channelmodules'] = "Modules";
$LANGS['videosandpl'] = "Videos and Playlists";
$LANGS['revert'] = "Revert! I want my old channel back";
$LANGS['all'] = "All";
$LANGS['uploads'] = "Uploads";
$LANGS['channelpl'] = "Playlists";
$LANGS['backtoplaylists'] = "Back to Playlists";
$LANGS['searchuploads'] = "Search Uploads";
$LANGS['info'] = "Info";
$LANGS['viewcomments'] = "View comments, related videos, and more";
$LANGS['seeallcommentsandresponses'] = "See all comments and video responses";
$LANGS['pastethislink'] = "Paste this link into an email or instant message";
$LANGS['selectplaylist'] = "Select Playlist";
$LANGS['profilemsg'] = 'Your channel viewers will see links here, including "subscribe" and "add as friend".';
$LANGS['profile'] = 'Profile';
$LANGS['profilechangessaved'] = 'Changes saved.';
$LANGS['posting'] = 'posting...';
$LANGS['name'] = 'Name';
$LANGS['totaluploadviews'] = 'Total Upload Views';
$LANGS['channeldesc'] = 'Channel Description';
$LANGS['hometown'] = 'Hometown';
$LANGS['occupation'] = 'Occupation';
$LANGS['companies'] = 'Companies';
$LANGS['schools'] = 'Schools';
$LANGS['interests'] = 'Interests';
$LANGS['movies'] = 'Movies';
$LANGS['featuredchannelsdefault'] = 'Click on "edit" above to enter channels you want to link to.';
$LANGS['featuredchannelsdesc'] = 'Please list up to 4 destination channels in the order you would like them to be shown in your channel, separated with commas and no spaces. Not listing any channels will prevent this box from appearing on your channel.';
$LANGS['backtochannel'] = "back to {c}'s channel";
$LANGS['refresh'] = "Refresh";
$LANGS['whichcontent'] = "Which content would you like to display?";
$LANGS['myuploadedvideos'] = "My Uploaded Videos";
$LANGS['myfavorites'] = "My Favorites";
$LANGS['alsoshowall'] = 'Also show "All" view';
$LANGS['featuredvideo'] = 'Featured video';
$LANGS['usemostrecent'] = 'Use the most recent video from my featured set';
$LANGS['autoplayfeatured'] = "Autoplay featured video";
$LANGS['areyousure'] = "Are you sure that you want to continue?";
$LANGS['unsavedchanges'] = "Are you sure do you want to change the theme? Unsaved changes will be lost.";
$LANGS['showadvancedoptions'] = "show advanced options";
$LANGS['hideadvancedoptions'] = "hide advanced options";
$LANGS['general'] = "General";
$LANGS['colorpalettes'] = "Color Palettes";
$LANGS['font'] = "Font";
$LANGS['wrappercolor'] = "Wrapper color";
$LANGS['wrappertextcolor'] = "Wrapper text color";
$LANGS['wrapperlinkcolor'] = "Wrapper link color";
$LANGS['wrappertransparency'] = "Wrapper transparency";
$LANGS['repeatbackground'] = "Repeat Background";
$LANGS['titletextcolor'] = "Title text color";
$LANGS['bodytextcolor'] = "Body text color";
$LANGS['transparency'] = "Transparency";
$LANGS['bgimgdesc'] = "Upload an image that will display as a background on your channel (maximum 2MB).";
$LANGS['channeltype'] = "Channel Type";
$LANGS['channeltags'] = "Channel Tags";
$LANGS['commaseparated'] = "(comma separated)";
$LANGS['channeltagsdesc'] = "Tags are keywords used to help people find your channel.";

/* My Profile page */
$LANGS['myprofiledesc'] = '这个页面展示了您的账号的所有信息。';
$LANGS['profileimages'] = '照片';
$LANGS['avatar'] = '个人照';
$LANGS['backgroundimage'] = '背景';
$LANGS['deleteimage'] = '删除';
$LANGS['channelinformation'] = '资讯';
$LANGS['genderrelationprivate'] = '不愿透露';
$LANGS['fctitle'] = '关于精选频道';
$LANGS['relationship'] = '个人状态';
$LANGS['birthday'] = '生日';
$LANGS['showage'] = '展示年龄';
$LANGS['aboutme'] = '关于我';
$LANGS['emailprefs'] = '邮件选择';
$LANGS['emailpm'] = '通过私人信息向我发送电邮';
$LANGS['emailcomm'] = 'E-Mail me on Video Comments';
$LANGS['emailsub'] = 'E-Mail me on weekly Subscription Highlights';
$LANGS['layoutprefs'] = '主题';
$LANGS['bgcolor'] = '背景颜色';
$LANGS['bgfixed'] = 'Fixed';
$LANGS['bgrepeat'] = '背景重复';
$LANGS['norepeat'] = '不重复';
$LANGS['repeat'] = '重复';
$LANGS['repeatx'] = '横向重复';
$LANGS['repeaty'] = '竖向重复';
$LANGS['bgposition'] = '背景位置';
$LANGS['top'] = '偏上';
$LANGS['middle'] = '正中心';
$LANGS['bottom'] = '偏下';
$LANGS['fontcolor'] = '字体颜色';
$LANGS['titlefontcolor'] = '标题颜色';
$LANGS['linkcolor'] = 'Link Color';
$LANGS['hlfontcolor'] = 'Highlight Font Color';
$LANGS['hlheadercolor'] = 'Highlight Header';
$LANGS['hlinsidecolor'] = 'Highlight Inside';
$LANGS['headercolor'] = 'Regular Header';
$LANGS['insidecolor'] = 'Regular Inside';
$LANGS['font'] = '频道字体';
$LANGS['featuredvideobox'] = 'Featured Video Box';
$LANGS['subscribersbox'] = '展示订阅者';
$LANGS['subscriptionsbox'] = '展示订阅';
$LANGS['friendsbox'] = '展示好友';
$LANGS['bulletinsbox'] = '展示公告栏';
$LANGS['videosbox'] = '展示视频';
$LANGS['favoritesbox'] = '展示喜爱的视频';
$LANGS['playlistsbox'] = '展示播放列表';
$LANGS['commentsbox'] = '展示频道评论';
$LANGS['ratingsbox'] = 'Recent Activity Box';
$LANGS['partnersettings'] = 'Partner Settings';
$LANGS['bannerimage'] = '横幅图片';
$LANGS['minibannerimage'] = '小横幅图片';
$LANGS['sideimage'] = 'Side Image';
$LANGS['recommendedsize'] = 'recommended size';
$LANGS['bannerlink'] = 'Banner Website';
$LANGS['sideimagelink'] = 'Side Image Website';
$LANGS['custombox'] = 'Custom Box';
$LANGS['customboxtitle'] = 'Custom Box Title';
$LANGS['customboxcontent'] = 'Custom Box Content';
$LANGS['savechanges'] = '保存';
$LANGS['submitimage'] = 'Submit Image';
$LANGS['overview'] = 'Overview';
$LANGS['profilesetup'] = 'Profile Setup';
$LANGS['playbacksetup'] = 'Playback Setup';
$LANGS['emailoptions'] = 'Email Options';
$LANGS['manageaccount'] = 'Manage Account';
$LANGS['chvideoviews'] = 'Video Views';
$LANGS['change'] = "change";
$LANGS['mynetwork'] = "My Network";
$LANGS['contacts'] = "Contacts";
$LANGS['chvideocomments'] = "Video Comments";
$LANGS['chmore'] = "More";
$LANGS['changepicture'] = "Change Picture";
$LANGS['changepicturedesc'] = "You can upload a JPG, BMP, or PNG file. Do not upload pictures containing celebrities, nudity, artwork or copyrighted images. Your image will be displayed as an 88px by 88px square. <b>Maximum file size is 2 MB.</b>";
$LANGS['describeyourself'] = "Describe Yourself";
$LANGS['personaldetails'] = "Personal Details";
$LANGS['jobscareer'] = "Jobs / Career";
$LANGS['education'] = "Education";
$LANGS['videoplaybackquality'] = "Video Playback Quality";
$LANGS['videoplaybackqualitydesc'] = "Choose the default setting for viewing videos";
$LANGS['alwayshd'] = "Always play videos in HD quality";
$LANGS['neverhd'] = "Never play any videos in HD quality";
$LANGS['currentemail'] = "Current Email Address";
$LANGS['changeemailaddress'] = "Change Email Address";
$LANGS['changeemail'] = "Change Email";
$LANGS['partnerimages'] = "Partner Images";
$LANGS['partnerimagelinks'] = "Partner Image Links";
$LANGS['accountstatuscg'] = "Account Status: Community Guidelines";
$LANGS['accountstatuscopy'] = "Account Status: Copyright";
$LANGS['changeusername'] = "Change Username";
$LANGS['changepassword'] = "Change Password";
$LANGS['deleteaccount'] = "Delete Account";
$LANGS['goodaccount'] = "Your account is in good standing.";
$LANGS['accountstrike'] = "You have {s} strikes. Be careful!";
$LANGS['accountstrikes'] = "You have {s} strikes. Be careful!";
$LANGS['cannotchangeusername'] = "You cannot change your username yet! Please wait until ";
$LANGS['usernamechangedesc'] = "You'll only be able to change your username once a year, so choose your new username wisely.";
$LANGS['newusername'] = "New username";
$LANGS['currentpassword'] = "Current password";
$LANGS['newpassword'] = "New password";
$LANGS['confirmnewpassword'] = "Confirm new password";
$LANGS['enterpassword'] = "For security reasons, please enter your password";

/* Upload page */
$LANGS['uploadpagetitle'] = '上传视频';
$LANGS['step1of2'] = '第一步';
$LANGS['step2of2'] = '第二步';
$LANGS['videocategory'] = '资讯栏';
$LANGS['tagsdesc'] = '放置标签会让您的视频更容易被人找到。<br> <i>(请用逗号隔开标签)</i>';
$LANGS['requiredfield'] = '(* 必填)';
$LANGS['datemapoptions'] = '日期和位置';
$LANGS['optional'] = '可选择';
$LANGS['chooseoptions'] = '展开';
$LANGS['lessoptions'] = '关闭';
$LANGS['addressrecorded'] = '位置';
$LANGS['uploadcontinue'] = '上传视频...';
$LANGS['file'] = '文件';
$LANGS['broadcastoptions'] = 'Broadcast Options';
$LANGS['uploadvideo'] = '上传';
$LANGS['needfilevideotoupload'] = '请选择您要上传的视频！';
$LANGS['aboutuploading'] = '关于上传...';
$LANGS['uploaddesc1'] = '如果您处于网络高速状态，那么上传每MB大约只需1-5分钟，并且只在几分钟内完成解析。';
$LANGS['videolimit1'] = '您的视频不可大于100MB，长度不可超过15分钟。';
$LANGS['videolimit2'] = '您的视频不可大于2GB，长度不可超过30分钟。';
$LANGS['partnervideolimit1'] = '您的视频不可大于100MB，长度不可超过30分钟。';
$LANGS['partnervideolimit2'] = '您的视频不可大于2GB，长度不可超过30分钟。';
$LANGS['myvideosdesc'] = '完成上传后，您可点击 <a href="/my_videos">我的视频</a>" 以编辑视频信息或删除此视频。';
$LANGS['newuploader'] = '使用新上传器';
$LANGS['olduploader'] = '使用旧上传器';
$LANGS['videoadded'] = '您的视频已成功添加！';
$LANGS['videoaddeddesc'] = '您的视频目前仍在解析当中，这一过程会几分钟内完成。';
$LANGS['thankyou'] = '感谢';
$LANGS['sharelink'] = '分享您的视频吧！复制下方的链接吧：';
$LANGS['embedlink'] = 'Play this video directly ON your website! Copy and paste the following snippet:';
$LANGS['allrequiredinfo'] = '请填写所有的空格！';

/* Partners */
$LANGS['partnerhead'] = 'BitView合作伙伴计划';
$LANGS['partnertitle'] = 'Partner With BitView';
$LANGS['partnerdesc'] = "您拥有精彩的视频和不断增长的观众。让BitView通过我们的合作伙伴计划帮助您并将其提高到一个崭新的阶段。";
$LANGS['applynow'] = '立即申请';
$LANGS['contentpartners'] = '已加入的用户';
$LANGS['partnerbenefits'] = '福利';
$LANGS['partnerbenefitsdesc'] = '如您加入了我们的合作团队计划，那么您将拥有以下福利：<br><br>- 更好塑造您的频道形象：通过可自定义的make yourself stand out with custom branding, which includes banners, a custom box for your channel and a partner badge on all your videos.<br><br>- There are more benefits to come in the future!';
$LANGS['qualificationsfaq'] = '申请资格';
$LANGS['qualificationsfaqdesc'] = '如果要申请BitView合作伙伴计划，那么您的频道必须符合以下条件：<br><br>- 您频道的视频必须主要以原创视频为主。<br><br>- 您的频道不可低于75订阅者。<br><br>- 您的频道必须没有违反到我们的 <a href="/guidelines">社区准则。</a>';

/* Staff */
$LANGS['bvstaff'] = 'BitView Staff';
$LANGS['bvstaffdesc'] = "This is a list of people who worked (or still works) on BitView - keeping the website' alive - so users can Express Themselves.";
$LANGS['owners'] = 'Owners';
$LANGS['ownerdesc'] = 'People who - what a shocking fact - owns the BitView thingy.';
$LANGS['coowndev'] = 'Co-Owner & <br> Developer';
$LANGS['owndev'] = 'Owner & <br> Developer';
$LANGS['coownserver'] = 'Co-Owner &<br>Server Owner/Developer';
$LANGS['modsanddevs'] = 'Moderators and Developers';
$LANGS['modsanddevsdesc'] = 'People who keep the website safe and clear. Have any problem with your account? You should contact them.';
$LANGS['moderator'] = 'Moderator';
$LANGS['moddev'] = 'Developer &<br>Moderator';
$LANGS['lettertitle'] = 'Letter to all the people who helped with the website';
$LANGS['letter'] = "Dear Co-Owners, Developers, and Moderators of BitView,<br><br>
                On behalf of the entire BitView team, I would like to express my heartfelt gratitude for your exceptional dedication and hard work. As one of the owners, it fills me with immense pride to witness the growth and success of our video-sharing platform, and it would not have been possible without your invaluable contributions.
                <br><br>
                To rest of the Co-Owners, thank you for your unwavering support and vision. Your commitment to the platform's development and improvement has been instrumental in shaping BitView.net into the remarkable community it is today. Your leadership and strategic guidance have been vital in navigating the challenges and opportunities that have come our way.
                <br><br>
                To our talented Developers, your technical expertise and innovative ideas have transformed BitView into a cutting-edge platform that perfectly represent how YouTube looked like back in the days. Your countless hours of coding, problem-solving, and feature implementation have elevated the user experience and made our platform a hub of creativity and entertainment. Your dedication to refining the functionality and performance of the site has been truly commendable.
                <br><br>
                To our diligent Moderators, I extend my deepest appreciation for maintaining the integrity and safety of our community. Your vigilance in enforcing the rules and guidelines, ensuring respectful interactions, and swiftly addressing any issues that arise has been crucial in fostering a welcoming environment for all users. Your efforts in keeping BitView a space for constructive engagement and positive content are highly commendable.
                <br><br>
                Together, as a unified team, we have achieved significant milestones and overcome numerous obstacles. The success of BitView is a testament to the collective effort and passion each one of you brings to the table. Your commitment to our shared vision has been truly inspiring, and I am grateful to have such exceptional individuals by my side.
                <br><br>
                As we continue to grow and evolve, let us cherish the bonds we have forged and remain committed to the values that define our little site. Together, we will continue that nostalgia trip and provide a platform for creators to showcase their talents.
                <br><br>
                Once again, thank you: Co-Owners, Developers, and Moderators, for your unwavering dedication, expertise, and unwavering support. Your hard work has not gone unnoticed, and I am incredibly proud to be part of this remarkable team.
                <br><br>
                Keep expressing yourself,<br>
                <3 vistafan12";
$LANGS['backtobitview'] = "Back to BitView";

/* My Friends */
$LANGS['myfriends'] = 'My Friends';
$LANGS['invites'] = 'Invites';
$LANGS['myinvites'] = 'My Invites';
$LANGS['incominginvites'] = 'Incoming Invites';
$LANGS['noinvites'] = 'You have no invites...';
$LANGS['actions'] = 'Actions';
$LANGS['retract'] = 'Retract';

/* History */
$LANGS['clearhistory'] = "Clear Viewing History";
$LANGS['noviewinghistory'] = "There are no videos in your history.";

/* QuickList */
$LANGS['playquicklist'] = "Play Quicklist";
$LANGS['clearquicklist'] = "Clear Quicklist";
$LANGS['noquicklist'] = "There are no videos in your quicklist.";
$LANGS['noquicklistdesc'] = "QuickList lets you make a video list for later viewing. Click on the &quot;+&quot; (in the lower left) of any video to add it to your QuickList. To view your list, look for the QuickList bar under any video you're watching.";
$LANGS['quicklistcleared'] = "Your Quicklist has been cleared successfully.";
$LANGS['addedtoquicklist'] = "Added to <br> Quicklist";

/* About */
$LANGS['aboutus'] = '关于我们';
$LANGS['abouttitle'] = '什么是BitView？';
$LANGS['aboutdesc'] = 'BitView是其中一种将您的视频分享给您的好友的方式。使用BitView，您可以：';
$LANGS['about1'] = '向全世界展示您所喜爱的视频';
$LANGS['about2'] = '拍摄关于您可爱的宠物的视频';
$LANGS['about3'] = '上传使用相机或手机拍摄的视频';
$LANGS['about4'] = '安全并私密地向您的家人和来自世界各地的好友展示您的视频';
$LANGS['about5'] = '...和其他用途！';
$LANGS['aboutsignup'] = '立即 <a href="/signup">注册</a> 一个新账号吧！';
$LANGS['abouthelp'] = '想要了解更多信息吗？请参见<a href="help">帮助</a> 。';
$LANGS['aboutmail'] = '请随时 <a href="mailto:contact@vidlii.co">联系我们</a>。';

/* Community Guidelines */
$LANGS['bvguidelines'] = 'BitView Community Guidelines';
$LANGS['cgtitle1'] = 'Respect the BitView Community';
$LANGS['cgtitle2'] = "Don't Cross the Line";
$LANGS['cgtitle3'] = 'We Enforce These Guidelines';
$LANGS['cgtitle4'] = 'BitView is for the Community';
$LANGS['cgtitle5'] = 'Community Guideline Tips';
$LANGS['cgdesc1'] = "We're not asking for the kind of respect reserved for nuns, the elderly, and brain surgeons. We mean don't abuse the site. Every cool new community feature on BitView involves a certain level of trust. We trust you to be responsible, and millions of users respect that trust. Please be one of them.";
$LANGS['cgdesc2'] = "Here are some common-sense rules that will help you steer clear of trouble:";
$LANGS['cgdesc3'] = "Please take these rules seriously and take them to heart. Don't try to look for loopholes or try to lawyer your way around the guidelines — just understand them and try to respect the spirit in which they were created. If you'd like more details, check out our <a href='#tips'>Community Guideline Tips</a>.";
$LANGS['cgdesc4'] = "Okay, this one is more about us than you. BitView staff review flagged videos 24 hours a day, seven days a week to determine whether they violate our Community Guidelines. When they do, we remove them. Sometimes a video doesn’t violate our Community Guidelines, but may not be appropriate for everyone. These videos may be age-restricted. Accounts are penalized for Community Guidelines violations and serious or repeated violations can lead to account termination. If your account is terminated, you won’t be allowed to create any new accounts. For more information about how the Community Guidelines are enforced and the consequences of violating them, please visit the <a href='/help'>Help Center</a>.";
$LANGS['cgdesc5'] = "Remember that this is your community! Each and every  user of BitView makes the site what it is, so don't be afraid to dig in and get involved!";
$LANGS['cgdesc6'] = "That's it! Thanks for reading!";
$LANGS['cgdesc7'] = "Want a little more insight into the limits and exceptions in the Community Guidelines? Here are some helpful examples and tips:";
$LANGS['rule1'] = "BitView is not for pornography or sexually explicit content. If this describes your video, even if it's a video of yourself, don't post it on BitView. Also, be advised that we work closely with law enforcement and we report child exploitation.";
$LANGS['rule2'] = "Don't post videos showing bad stuff like animal abuse, drug abuse, under-age drinking and smoking, or bomb making.";
$LANGS['rule3'] = "Graphic or gratuitous violence is not allowed. If your video shows someone being physically hurt, attacked, or humiliated, don't post it.";
$LANGS['rule4'] = "BitView is not a shock site. Don't post gross-out videos of accidents, dead bodies or similar things intended to shock or disgust.";
$LANGS['rule5'] = "Respect copyright. Only upload videos that you made or that you are authorized to use. This means don't upload videos you didn't make, or use content in your videos that someone else owns the copyright to, such as music tracks, snippets of copyrighted programs, or videos made by other users, without necessary authorizations.";
$LANGS['rule6'] = "We encourage free speech and defend everyone's right to express unpopular points of view. But we don't permit hate speech (speech which attacks or demeans a group based on race or ethnic origin, religion, disability, gender, age, veteran status, and sexual orientation/gender identity). This also applies to the promotion of extremist ideologies in a positive light.";
$LANGS['rule7'] = "Things like predatory behavior, stalking, threats, harassment, intimidation, invading privacy, revealing other people’s personal information, and inciting others to commit violent acts or to violate the Terms of Use are taken very seriously. Anyone caught doing these things may be permanently banned from BitView.";
$LANGS['rule8'] = "Everyone hates spam. Don’t create misleading descriptions, tags, titles or thumbnails in order to increase views. It's not okay to post large amounts of untargeted, unwanted or repetitive content, including comments and private messages.";
$LANGS['rule9'] = "Let's keep the website safe. Don't try to brute force an account you do not own. Moreover, sharing an account's login information publicly is not allowed.";
$LANGS['rule10'] = "Multi-accounts suck. We want genuine numbers on videos and channels. Don't use more than one account to rate videos and/or comments. You are not allowed to use multiple accounts to subscribe to yourself either.";
$LANGS['rule11'] = "Did you break one of this rules and your account has been suspended? It goes without saying that evading this punishment is not accepted. Every new account that has been created by a suspended person will be automatically deleted.";
$LANGS['cglist1'] = "Have fun with the site. There's a lot to see here, and lots of folks making amazing stuff — one of them might be you! Equipment's getting cheaper and easier to use all the time, so dive in and enjoy.";
$LANGS['cglist2'] = "Let folks know what you think. Feedback's part of the experience, and when done with respect, can be a great way to make friends, share stories, and make your time on BitView richer. So leave comments, rate videos, make your own responses to videos that affect you, enter contests of interest — there's a lot going on and a lot of ways to participate.";
$LANGS['cglist3'] = "You may not like everything you see. Some of the content here may offend you — if you find that it violates our Terms of Use, then click the button that says &quot;Flag&quot; under the video you're watching to submit it for review by BitView staff. If it doesn't, then consider just clicking on something else — why waste time watching videos you don't like?";
$LANGS['thebitviewteam'] = "— The BitView Team";
$LANGS['cgcat1'] = "Sex and Nudity";
$LANGS['cgcat2'] = "Hate Speech";
$LANGS['cgcat3'] = "Shocking and Disgusting";
$LANGS['cgcat4'] = "Dangerous Illegal Acts";
$LANGS['cgcat5'] = "Children";
$LANGS['cgcat6'] = "Copyright";
$LANGS['cgcat7'] = "Privacy";
$LANGS['cgcat8'] = "Harassment";
$LANGS['cgcat9'] = "Impersonation";
$LANGS['cgcat10'] = "Threats";
$LANGS['cgcat1desc'] = "Most nudity is not allowed, particularly if it is in a sexual context. Generally if a video is intended to be sexually provocative, it is less likely to be acceptable for BitView. There are exceptions for some educational, documentary and scientific content, but only if that is the sole purpose of the video and it is not gratuitously graphic. For example, a documentary on breast cancer would be appropriate, but posting clips out of context from the documentary might not be. This also applies for animated content.";
$LANGS['cgcat2desc'] = 'Hate speech" refers to content that promotes hatred against members of a protected group. For instance, racist or sexist content may be considered hate speech. Sometimes there is a fine line between what is and what is not considered hate speech. For instance, it is generally okay to criticize a nation, but not okay to make insulting generalizations about people of a particular nationality.';
$LANGS['cgcat3desc'] = "The world is a dangerous place. Sometimes people do get hurt and it’s inevitable that these events may be documented on BitView. However, it’s not okay to post violent or gory content that’s primarily intended to be shocking, sensational or disrespectful. If a video is particularly graphic or disturbing, it should be balanced with additional context and information. For instance, including a clip from a slaughter house in a video on factory farming may be appropriate. However, stringing together unrelated and gruesome clips of animals being slaughtered in a video may be considered gratuitous if its purpose is to shock rather than illustrate.";
$LANGS['cgcat4desc'] = "While it might not seem fair to say you can’t show something because of what viewers theoretically might do in response, we draw the line at content that’s intended to incite violence or encourage dangerous, illegal activities that have an inherent risk of serious physical harm or death. This means not posting videos on things like instructional bomb making, ninja assassin training, sniper attacks, videos that train terrorists, or tips on illegal street racing. Any depictions like these should be educational or documentary and shouldn’t be designed to help or encourage others to imitate them.";
$LANGS['cgcat5desc'] = "Videos involving children (anyone under the age of 18) are particularly sensitive. Videos containing children should never be sexually suggestive or violent. Please be cautious when posting something involving a child. If you’re sharing a private moment or home movie, consider making it a private video so that only your family and friends can see it. Moreover, by agreeing to the <a href='/terms'>Terms of Use</a>, you affirm that you are over the age of 13. Accounts belonging to underage users will be suspended.";
$LANGS['cgcat6desc'] = "When you create something original, you own the copyright for it. Likewise, when other people create content, they may have a copyright to it. As a creative community, it’s essential that everyone on BitView respect the copyrights of others. If you’re not sure if something will violate someone’s copyright, the safest thing to do is to create something completely original, with images and audio you’ve created. If it’s all yours you never have to worry about copyright — you own it. If you’ve recorded something from a DVD, videotaped your TV screen, or downloaded a video online, don’t post it unless you have permission.";
$LANGS['cgcat7desc'] = "If a video you've recorded features people who are readily identifiable and who haven't consented to being filmed, there's a chance they'll file a privacy complaint seeking its removal. We'll notify you if that happens and give you a chance to edit and re-upload your video before we act on the complaint. If we do remove your video for privacy reasons, don't upload another version featuring the same people. Chances are those people will file another privacy complaint or report you for harassment. Don't post other people's personal information, including phone numbers, addresses, credit card numbers, and government IDs. We're serious about keeping our users safe and suspend accounts that violate people's privacy.";
$LANGS['cgcat8desc'] = "It comes down to respect. BitView is all about sharing and interacting with the community in respectful ways. If you're not sure whether a video or comment you've made crosses the line, follow a simple rule of thumb: if you wouldn't say it to someone's face, don't say it on BitView. And if you're looking to attack, harass, demean, or impersonate others, go elsewhere.";
$LANGS['cgcat9desc'] = "Impersonating another user by copying someone's exact channel layout, using a similar username, or posing as that person in comments, emails or videos is considered harassment. If you want to keep your account, stay away from participating in any form of impersonation or harassing activity on the site.";
$LANGS['cgcat10desc'] = "Users shouldn't feel threatened when they're on BitView. Period. Don't leave threatening comments on other people's videos.";

/* Contests */
$LANGS['monthlycontest'] = "月度创作大赛";
$LANGS['monthlycontestschedule'] = "月度创作大赛每月主题";
$LANGS['whatisit'] = "这次大赛的主题是？";
$LANGS['thismonthcontest'] = "这次大赛的主题是？";
$LANGS['lastmonthwinners'] = "上次大赛的赢家";
$LANGS['howtoenter'] = "如何参加？";
$LANGS['whowins'] = "谁是赢家？";
$LANGS['whowinsdesc'] = "The winner will be picked at the end of the month by the BitView staff.";
$LANGS['theprize'] = "赢了有什么奖励？";
$LANGS['theprizedesc'] = "名声，财富和来自许多人羡（ji）慕（du）的眼光。";
$LANGS['contestsuggestion'] = '如您想对创作大赛提出建议，请 <a href="mailto:contact@vidlii.co">联系我们</a> 。';

/* Help */
$LANGS['q1'] = 'Q: 如何分享我上传的视频How can I share my videos and link to them from my website?';
$LANGS['a1'] = 'A: <a href="/sharing">How to share and link to your videos</a>';
$LANGS['q2'] = '问：我可以上传什么视频呢？';
$LANGS['a2'] = '答：您可以上传您想向全世界展示的任何类型的个人视频。我们绝不允许任何用户发布有关裸露内容的视频，并且您的视频必须使用任何观众。
<br/>
<br/>
然而，这仍然对您的创作并没有什么太大的影响！请问您的家中有养 <a href="results?search=dog&t=Search+Videos">狗</a> 或者 <a href="/results?search=cat&t=Search+Videos">猫</a>吗？请问您去了 <a href="/results?search=mexico&t=Search+Videos">墨西哥</a>度假吗？请问您住在 <a href="/results?search=netherlands&t=Search+Videos">荷兰</a>？
<br/>
<br/>
当然，这些仅仅只是我们举的一些例子，因为我们不能看透您的想法。最后请扪心自问，请问 <i>您</i> 想上传什么？';
$LANGS['q3'] = '问：我的视频长度最多可以达到多长？';
$LANGS['a3'] = '答：您上传的视频长度不可超过15分钟，而且大小必须低于2GB。（如您使用旧上传器，那么视频大小只能达到100MB）。';
$LANGS['q4'] = '问：上传的视频必须为哪些格式？';
$LANGS['a4'] = '答：BitView接受大多数来自相机或手机所使用，例如格式为.WMV、.AVI、.MOV、.MPG、.MP4的视频文件。';
$LANGS['q5'] = '问：如何提升我的视频质量？';
$LANGS['a5'] = '答：我们推荐一些视频剪辑软件。例如使用 <a href="https://windows-movie-maker-vista.en.softonic.com/" target="_blank">Windows Movie Maker</a> 或者 <a href="https://www.apple.com/lae/imovie/" target="_blank">Apple iMovie</a>。通过这些软件，您可以简单地对您的视频进行剪辑，在视频中添加配乐等等。';
$LANGS['q6'] = '问：我是否保留视频的版权和其他的合法权利？';
$LANGS['a6'] = '答：是的，您仍保留对您的视频的所有权利。BitView并不承担您所使用的材料的版权。';
$LANGS['q7'] = '问：BitView对于侵犯版权的政策是什么？';
$LANGS['a7'] = "答：BitView尊重版权所有者和发布者的权利，并且仅接受对所上传的材料拥有所有必要权利的人上传的视频。Our policy is to respond to any notices of alleged infringement that comply with the Digital Millennium Copyright Act (DMCA). If we receive a notice or otherwise have reason to believe that content you submitted infringes another party's copyright, your account may be terminated and the video removed from BitView.";
$LANGS['q8'] = 'Q: How do I report copyright infringement?';
$LANGS['a8'] = 'A: If you believe that someone else has uploaded your copyrighted content without your permission, we encourage you to contact that person in order to resolve any differences with them directly. You can also contact our support team using this <a href="mailto:contact@vidlii.co">email</a>.';
$LANGS['q9'] = 'Q: What if I have been falsely accused of copyright infringement?';
$LANGS['a9'] = "A: We'll let you know if we receive a copyright complaint about any of your video content that is hosted on BitView. We'll give you the opportunity to respond appropriately.";
$LANGS['q10'] = 'Q: What are you doing to prevent content that violates your policies from appearing in BitView?';
$LANGS['a10'] = 'A: We do a preliminary review on uploaded videos through both a manual and automated process. Although we try our best to detect and remove videos that violate our policy guidelines, our review process is primarily focused on removing adult content or obvious copyright violations, and is not bulletproof. However, we encourage our viewers to notify us when they discover policy violations or copyright issues -- we have a process for reviewing reported policy violations, and respond to reported copyright violations under the Digital Millennium Copyright Act.';
$LANGS['q11'] = 'Q: Do you have a Discord server or Twitter?';
$LANGS['a11'] = 'Yes! We actually have a Discord server and Twitter. You can join into the Discord server by clicking <a href="https://discord.gg/wgGaqCmwuQ">here</a>, and follow us on Twitter <a href="https://twitter.com/bitview_">here</a>.';
$LANGS['q12'] = "Q: I'm using an old browser while on BitView and thus can't watch videos. What can I do?";
$LANGS['activate'] = 'Activate';
$LANGS['deactivate'] = 'Deactivate';
$LANGS['flashdisclaimer'] = "<b>Note:</b> BitView's Flash Player is being offered as a compatibility option. If your browser supports BitView's HTML5 player you shouldn't enable this option.";

/* BitView on your site */
$LANGS['bvsitetitle1'] = "The Basics";
$LANGS['bvsitetitle2'] = "APIs and User Engagement";
$LANGS['bvsitedesc1'] = 'Whatever presence you have on the Internet—a large website, a blog, a social network page, or pretty much anything else—there are many ways to integrate BitView into it. From simple video embeds to our full-powered APIs, you can integrate video at all levels of technical expertise.';
$LANGS['bvsitedesc2'] = 'Bringing BitView to your site is more than just adding some of the thousands of videos available on BitView. It keeps your visitors interested and allows self-expression and interaction with one of their favorite services. And it brings your site, blog, or page into the BitView video community — an international network of users, creators, and sites connected through a huge collection of online videos.';
$LANGS['bvsitedesc3'] = "We've highlighted some typical ways of integrating video content below — just click the arrow next to the question to get the answer. If you have any questions or suggestions, or projects that you would like us to know about, please leave the questions in our <a href='https://discord.gg/wgGaqCmwuQ'>Discord server</a>.";
$LANGS['bvsitesectiontitle1'] = "How do I add a video to my blog or web page?";
$LANGS['bvsitesectiontitle2'] = "How do I add a video to my social network page?";
$LANGS['bvsitesectiontitle3'] = "I work for a large blog/web company. How can video increase user engagement on our site?";
$LANGS['bvsitesectiontitle4'] = "We have a site and we have our own videos. Can we post these on our site using BitView?";
$LANGS['bvsitesection1desc1'] = "You'll need to edit the HTML of your blog entry or page—this should be relatively straightforward. In Blogger, for example, just click the &quot;Edit HTML&quot; tab.";
$LANGS['bvsitesection1desc2'] = "Next, go to the video that you want, and look for the 'Embed' box in the &quot;About This Video&quot; section. Copying the HTML code that's there into your website will create an embedded player; the video will play within your site when the user clicks on the 'Play' button.";
$LANGS['bvsitesection1desc3'] = "You can resize the player by editing the <em>object width=&quot;425&quot;</em> and  <em>height=&quot;350&quot;</em> fields at both the beginning and end of the embedded player code. Make sure that the sizes you choose have the same ratio as the default numbers, so that the video doesn't get stretched—just multiply the width by 0.8235 to get the height.";
$LANGS['bvsitesection2desc1'] = "Adding videos to your profiles on social networks like SpaceHey is a great way to share your videos or favorites with friends. Or, if you're promoting something (like your band) on SpaceHey, videos will help attract visitors to your page, who can then then share the link with their friends. The social network sites have similar ways to add videos, so we'll use SpaceHey as an example.";
$LANGS['bvsitesection2desc2'] = 'Sign in to your SpaceHey profile, then click the "Edit Profile" button.';
$LANGS['bvsitesection2desc3'] = "Next, go to the video that you want, and look for the 'Embed' box in the &quot;About This Video&quot; section. Copying the HTML code that's there into your website will create an embedded player.";
$LANGS['bvsitesection2desc4'] = "You can resize the player by editing the object width=&quot;425&quot; and height=&quot;350&quot; fields at both the beginning and end of the embedded player code. Make sure that the sizes you choose have the same ratio as the default numbers, so that the video doesn't get stretched—just multiply the width by 0.8235 to get the height.";
$LANGS['bvsitesection2desc5'] = 'Click "Preview", and then "Submit".';
$LANGS['bvsitesection3desc1'] = "Video is much more engaging than text. It draws more users and keeps them on your site for longer. BitView has a large repository of Internet video content along with the search, playback and API tools to make adding video easier for you.";
$LANGS['bvsitesection3desc2'] = "When looking to increase engagement, try using video as a way to start discussion or make a commentary by creating more context for your users:";
$LANGS['bvsitesection4desc1'] = "It's very easy to build out your own site with your own videos for free. All you need to do is upload the videos to BitView first. There's no charge and we will cover hosting and streaming costs. It's not only a great way to increase user engagement on your site, but it's very easy, and free as well.";
$LANGS['bvsitesection4desc2'] = "Once you have uploaded the videos you can pull them back to the site:";
$LANGS['bvsitesection4desc3'] = "<b>Embed videos one-by-one:</b> Go to the video that you want to put on your website, and look for the 'Embed' box next to the video player. Copying the HTML code that's there into your blog will create an embedded player; the video will play within your site when the user clicks on the 'Play' button.";

/* RSS Feeds */
$LANGS['rsstitle1'] = "What Are RSS Feeds?";
$LANGS['rsstitle2'] = "How to Access RSS Feeds";
$LANGS['rsstitle3'] = "How to Subscribe to BitView's RSS Feeds";
$LANGS['rssdesc1'] = "Really Simple Syndication (RSS) is an XML-based format used for content distribution and syndication. Subscribing to RSS feeds allows you to receive custom, up-to-date information from your favorite online content sources without having to regularly check the site for updates.";
$LANGS['rssdesc2'] = "News readers that display RSS feeds from the websites you specify—they check the RSS feeds you have subscribed to and display new items from each feed. You can download news reader applications for your computer, and here are also many popular web-based news readers available, such as Google Reader and Bloglines. Some web browsers and email applications also have RSS capabilities built in.";
$LANGS['rssdesc3'] = "You can see a list of many available news readers at <a href='http://en.wikipedia.org/wiki/List_of_feed_aggregators'>Wikipedia</a>."; //Use your language's Wikipedia article if possible
$LANGS['rssdesc4'] = "BitView offers several RSS feeds for categorized groups of videos (such as recently uploaded, top viewed etc) as well as customized feeds for users and tags.";
$LANGS['rssdesc5'] = "To subscribe to categorized groups of videos, simply go to the category you want (for example, &quot;<a href='/browse'>Most Viewed - Today</a>&quot;). Then click on the orange 'RSS' button. This should trigger your chosen news reader to add the subscription.";
$LANGS['rssdesc6'] = "If your browser has RSS capabilities, then you can add the feed there. The command varies between browsers, but can usually be found on the 'File' or 'Bookmarks' menus, and will be called something like &quot;Subscribe to this page&quot; or &quot;New Live Bookmark&quot;.";
$LANGS['rssthispage'] = "RSS this page";

/* TestView */
$LANGS['testviewdesc'] = "Welcome to TestView, our ideas incubator. This is where BitView engineers and developers test out recipes and concoctions that aren't quite fully baked and invite you to tell us how they're coming along.";
$LANGS['flashvideo'] = "Flash Video";
$LANGS['flashvideodesc'] = "Your browser doesn't support HTML5 video? Don't worry! Try out our Flash player.";
$LANGS['feather'] = "Feather";
$LANGS['featherdesc'] = "View BitView videos on a super-low latency page.";
$LANGS['tryitout'] = "Try it out";
$LANGS['disabletest'] = "Disable";
$LANGS['timemachine'] = "Time Machine";
$LANGS['timemachinedesc'] = "Go back in time, rewinding every date on BitView to the late 2000's.";
$LANGS['lightsout'] = "Lights Out";
$LANGS['lightsoutdesc'] = "Tired of seeing the brightest of whites on your screen? Paint it, black and try out a new cool interface.";
$LANGS['featherenabled'] = '"Feather" is now enabled!';
$LANGS['timemachineenabled'] = '"Time Machine" is now enabled!';
$LANGS['lightsoutenabled'] = '"Lights Out" is now enabled!';
$LANGS['featherdisabled'] = '"Feather" is now disabled!';
$LANGS['timemachinedisabled'] = '"Time Machine" is now disabled!';
$LANGS['lightsoutdisabled'] = '"Lights Out" is now disabled!';

/* Footer */
$LANGS['youraccount'] = '您的账号';
$LANGS['inbox'] = '邮箱';
$LANGS['footmore'] = '设置';
$LANGS['helpinfo'] = 'Help';
$LANGS['helpcenter'] = '帮助';
$LANGS['ourtwitter'] = 'Twitter';
$LANGS['ourdiscord'] = 'Discord';
$LANGS['guidelines'] = '社区准则';
$LANGS['partnerships'] = '合作伙伴计划';
$LANGS['terms'] = 'Terms of Use';
$LANGS['privacypolicy'] = 'Privacy Policy';
$LANGS['currentlanguage'] = '目前所使用的语言';
$LANGS['showlanguages'] = '展示所有语言';
$LANGS['setlanguagepref'] = '选择您的语言';
$LANGS['programs'] = 'Programs';
$LANGS['developers'] = 'Developers';
$LANGS['bitviewblog'] = 'BitView Blog';
$LANGS['policy'] = 'Policy';
$LANGS['discover'] = 'Discover';
$LANGS['bvphone'] = 'BitView on Your Phone';
$LANGS['bvsite'] = 'BitView on Your Site';
$LANGS['bvrss'] = 'BitView RSS Feeds';
$LANGS['mobile'] = 'Mobile';
